### PR TITLE
Fix ignoring cells after null in appending hash

### LINKED ISSUE #4567: appending_hash<row> ignores cells after first null
Scylla version (or git commit hash): d773e4b9d4934aab44a0eba6131dc3a4a9397399

`appending_hash<row>` is supposed to update the provided hasher with information form the selected columns. However, the loops that is supposed to do that ends early if a requested column doesn't not exist. As a result, a row hash will not include information about the cells after the first missing one.

```c++
        for (auto id : columns) {
            const cell_and_hash* cell_and_hash = cells.find_cell_and_hash(id);
            if (!cell_and_hash) {
                return; // <- should be continue
            }
            auto&& def = s.column_at(kind, id);
            // add current cell to the hasher
```

### PR DESCRIPTION
**Pull request by psarna**
This series fixes a bug in `appending_hash<row>` that caused it to ignore any cells after the first NULL. It also adds a cluster feature which starts using the new hashing only after the whole cluster is aware of it. The series comes with tests, which reproduce the issue.

Fixes #4567
Based on #4574

### CODE REVIEW

**Comment by psarna** [comment]
Hm, perhaps I should have done it the other way round - change the old hasher to `xxhasher_without_null_digest` and use it only for legacy code, and make `xxhasher` implementation correct. Let me do that in v2, it will look cleaner and the users wouldn't have to wonder if they should use `xxhasher` of `xxhasher_with_null_digest`.

File: digest_algorithm.hh [hunk 1]
```diff
@@ -28,7 +28,8 @@ namespace query {
 enum class digest_algorithm : uint8_t {
     none = 0,  // digest not required
     MD5 = 1,
-    xxHash = 2,// default algorithm
+    xxHash = 2, // default algorithm
+    legacy_xxHash_without_null_digest = 3,
```
Comment (tgrabiec) [inline digest_algorithm.hh:32]: Shouldn't you set `legacy_xxHash_without_null_digest` to the old xxHash (2) value, so that old Scylla versions map to legacy_xxHash_without_null_digest during rolling upgrade?

**Review by tgrabiec — CHANGES_REQUESTED** [review]

File: digest_algorithm.hh (hunk 1 above)
Comment (psarna) [reply digest_algorithm.hh:32]: Yes, sounds like it.

**Comment by psarna** [comment]
By the way, unrelated: does it still make any sense to keep the `cluster_supports_xxhash_digest_algorithm` cluster feature? Can there ever be an upgrade path in which some nodes do not support it? Perhaps we should deprecate and remove it as a first step towards cleaning up the ever-growing list of cluster features.

**Comment by avikivity** [comment]
> By the way, unrelated: does it still make any sense to keep the `cluster_supports_xxhash_digest_algorithm` cluster feature? Can there ever be an upgrade path in which some nodes do not support it? Perhaps we should deprecate and remove it as a first step towards cleaning up the ever-growing list of cluster features.

Let's set a policy for it. Proposal: two years after  we keep sending it, but ignore it (and assume it is always set, and not store it locally), one year later we don't even send it.

**Comment by psarna** [comment]
I tested locally by performing a rolling upgrade on 3 nodes and verifying that a) nothing crashed and b) the feature bit was only active after the whole cluster was aware of it and it went fine. It proves nothing, but at least I'm a little bit more convinced that the upgrade path does not have any obvious bugs.

**Comment by avikivity** [comment]
Doesn't compile, dequeueing:

```
11:26:36  ld.lld: error: undefined symbol: void appending_hash<row, void>::operator()<xx_hasher>(xx_hasher&, row const&, schema const&, column_kind, utils::small_vector<unsigned int, 8ul> const&, max_timestamp&) const
11:26:36  >>> referenced by mutation_test.cc:3075 (test/boost/mutation_test.cc:3075)
11:26:36  >>>               build/release/test/boost/mutation_test.o:(test_appending_hash_row_4567::do_run_test_case())
11:26:36  >>> referenced by mutation_test.cc:3075 (test/boost/mutation_test.cc:3075)
11:26:36  >>>               build/release/test/boost/mutation_test.o:(test_appending_hash_row_4567::do_run_test_case())
11:26:36  >>> referenced by mutation_test.cc:3075 (test/boost/mutation_test.cc:3075)
11:26:36  >>>               build/release/test/boost/mutation_test.o:(test_appending_hash_row_4567::do_run_test_case())
11:26:36  >>> referenced by mutation_test.cc:3075 (test/boost/mutation_test.cc:3075)
11:26:36  >>>               build/release/test/boost/mutation_test.o:(test_appending_hash_row_4567::do_run_test_case())
11:26:36  >>> referenced by mutation_test.cc:3075 (test/boost/mutation_test.cc:3075)
11:26:36  >>>               build/release/test/boost/mutation_test.o:(test_appending_hash_row_4567::do_run_test_case())
11:26:36  >>> referenced by mutation_test.cc:3075 (test/boost/mutation_test.cc:3075)
11:26:36  >>>               build/release/test/boost/mutation_test.o:(test_appending_hash_row_4567::do_run_test_case())
11:26:36  >>> referenced by mutation_test.cc:3075 (test/boost/mutation_test.cc:3075)
11:26:36  >>>               build/release/test/boost/mutation_test.o:(test_appending_hash_row_4567::do_run_test_case())
11:26:36  >>> referenced by mutation_test.cc:3075 (test/boost/mutation_test.cc:3075)
11:26:36  >>>               build/release/test/boost/mutation_test.o:(test_appending_hash_row_4567::do_run_test_case())
11:26:36  >>> referenced by mutation_test.cc:3075 (test/boost/mutation_test.cc:3075)
11:26:36  >>>               build/release/test/boost/mutation_test.o:(test_appending_hash_row_4567::do_run_test_case())
11:26:36  >>> referenced by mutation_test.cc:3075 (test/boost/mutation_test.cc:3075)
11:26:36  >>>               build/release/test/boost/mutation_test.o:(test_appending_hash_row_4567::do_run_test_case())
11:26:36  collect2: error: ld returned 1 exit status
11:26:36  [2023/2420] LINK (stripped) build/release/test/boost/cartesian
```

**Comment by psarna** [comment]
Weird...I'll be back in the office in ~1h and fix, I'm sure I compiled and
ran all tests beforw submitting, maybe I pushed an uncommited branch or
something.

**Comment by avikivity** [comment]
@psarna it's a release build, probably due to differences in inlining between dev and release.

**Comment by psarna** [comment]
v3:
 - instantiated a template in order to make sure that the symbol is usable in tests (release mode only, dev compiles fine)
 - rebased onto fresh master
 - reran all tests in dev and release
