### PR TITLE
Alternator streams: Fix shard lengths, parenting, expiration, filter useless ones and improve paging

### LINKED ISSUE #7344: Alternator shard ID:s are to long
Docs says max 65 chars. We encode (potentially) 87 chars. 
Suggest removing the stream arn from shard_id, since it is redundant.

### LINKED ISSUE #7345: Alternator endsequencenumber is never set.
The code looks at "expired" in cdc stream gen from table query, but this is neither ever set nor does it really represent the "end" of a generation.

 EndSequenceNumber should be next generations StartSequenceNumber, with maybe a confidence interval overlap.

### LINKED ISSUE #7346: Alternator shards parent is not set very correctly
The code relies on the sort order of cdc streamid:s from query. Should 
a.) explicitly sort these so we can find token bounds
b.) Select parent so that it is the largest token < child token (i.e. start of range covering my range. (though this is somewhat beside the point).

### LINKED ISSUE #7347: Alternator shard ID:s should be filtered by time
Since we cannot have data read from any generation that expired more than 24h ago, nor any generation expired before the stream was created, we should filter out these generations from describe_streams.

Without this, we would get an ever larger, unbounded, set of shards as topology changes in the cluster.
Old code tries to do something like this, but looked at the wrong info (expired - never set - and not what we are looking for), and also was not very efficient.

### PR DESCRIPTION
**Pull request by elcallio**
The remains of the defunct #7246. 

Fixes #7344
Fixes #7345
Fixes #7346
Fixes #7347

Shard ID length is now within limits.
Shard end sequence number should be set when appropriate.
Shard parent is selected a bit more carefully (sorting)
Shards are filtered by time to exclude cdc generations we cannot get data from (too old)
Shard paging improved

### CODE REVIEW

File: alternator/streams.cc [hunk 1]
```diff
@@ -479,10 +481,18 @@ future<executor::request_return_type> executor::describe_stream(client_state& cl
     // or on expired...
     // TODO: maybe add secondary index to topology table to enable this?
     return _sdks.cdc_get_versioned_streams({ tm.count_normal_token_owners() }).then([this, &db, schema, shard_start, limit, ret = std::move(ret), stream_desc = std::move(stream_desc)](std::map<db_clock::time_point, cdc::streams_version> topologies) mutable {
-        auto i = topologies.begin();
+
+        // filter out cdc generations older than the table or now() - dynamo_streams_max_window (24h)
+        auto low_ts = std::max(as_timepoint(schema->id()), db_clock::now() - dynamo_streams_max_window);
+
+        auto i = topologies.lower_bound(low_ts);
```
Comment (nyh) [inline alternator/streams.cc:479]: Does this work correctly when paging through the list of shards and time goes by while we're having fun?
Maybe the non-first pages don't start with this "i" and start somewhere else? (I don't know if it does...).

File: alternator/streams.cc [hunk 2]
```diff
@@ -690,7 +685,7 @@ future<executor::request_return_type> executor::get_shard_iterator(client_state&
             inclusive_of_threshold = false;
             break;
         case shard_iterator_type::TRIM_HORIZON:
-            threshold = utils::UUID{};
+            threshold = utils::UUID_gen::min_time_UUID(sid->time.time_since_epoch().count());
```
Comment (nyh) [inline alternator/streams.cc:720]: Why is this change needed? In case by freak chance we reuse the same stream token for a new generation as was already used in an older generation?

File: alternator/streams.cc [hunk 3]
```diff
@@ -595,44 +592,39 @@ struct shard_iterator {
     static auto constexpr inclusive_marker = 'I';
     static auto constexpr exclusive_marker = 'i';
 
-    shard_id shard;
+    static auto constexpr uuid_str_length = 36;
```
Comment (nyh) [inline alternator/streams.cc:627]: I don't have a better place to leave this comment so I'll randomly leave it hereI:
If the purpose of this patch is to fix the length of shard ids, which need to be shorter than some length, please add a test which verifies this length - which should fail before this patch and pass after (and of course also on DynamoDB). It doesn't need to be a whole new test - can be an additional assert in one of the many existing tests which already deal with shard ids (please with a comment explaining what is being tested).

File: alternator/streams.cc [hunk 4]
```diff
@@ -673,9 +665,12 @@ future<executor::request_return_type> executor::get_shard_iterator(client_state&
         sid = rjson::get<shard_id>(request, "ShardId");
     } catch (...) {
     }
-    if (!schema || !cdc::get_base_table(db, *schema) || !is_alternator_keyspace(schema->ks_name()) || sid->table != schema->id()) {
+    if (!schema || !cdc::get_base_table(db, *schema) || !is_alternator_keyspace(schema->ks_name())) {
         throw api_error::resource_not_found("Invalid StreamArn");
     }
+    if (!sid) {
+        throw api_error::resource_not_found("Invalid ShardId");
+    }
```
Comment (nyh) [inline alternator/streams.cc:705]: I wanted to suggest that you add tests which try to pass invalid shard ids or arns, and check we get ResourceNotFound as expected (and run the same test against DynamoDB to confirm that this is the right error to return in this case). But when I tried to look, I found a test you already wrote, test_get_shard_iterator(), which seems to suggest that a bad ARN should throw ValidationException, not ResourceNotFound... What am I missing?

File: alternator/streams.cc [hunk 5]
```diff
@@ -357,44 +357,35 @@ namespace alternator {
...
  * is simply a 1:1 mapping, id=shard. Simple, and fairly easy
  * to do ranged queries later.
  * 
  * Downside is that we get a _lot_ of shards. And with actual
  * generations, we'll get hubba-hubba loads of them. 
  * 
- * Improvement ideas: 
- * 1.) Prune expired streams that cannot have records (check ttls)
- * 2.) Group cdc streams into N per shards (by token range)
+ * We would like to group cdc streams into N per shards
```
Comment (nyh) [inline alternator/streams.cc:366]: Adding a comment here because Github doesn't allow me to add comments on the commit message :-(
The word "paging" in the commit message is very ambigous. We do paging of almost everything in Alternator and Scylla, and it's not clear which one is intended here. I didn't understand what "efficient collection skip when doing paging" refers to in the commit message.
Also, please instead of talking about the "sanity" of the parent-child relationship, can you please say a few words about how this parent-child relationship actually works in Scylla? Do we even have this notion?

File: alternator/streams.cc [hunk 6]
```diff
@@ -357,44 +357,35 @@ namespace alternator {
 using namespace std::string_literals;
 
 /**
- * This implementation of CDC stream to dynamo shard mapping
```
Comment (nyh) [inline alternator/streams.cc:361]: I think you removed this line by mistake?

File: alternator/streams.cc [hunk 7]
```diff
@@ -405,6 +396,9 @@ static std::chrono::seconds confidence_interval(const database& db) {
     return std::chrono::seconds(db.get_config().alternator_streams_time_window_s());
 }
 
+// Dynamo docs says no data shall live longer than 24h.
+static constexpr auto dynamo_streams_max_window = 24h;
```
Comment (nyh) [inline alternator/streams.cc:400]: Oh, found it :-) The patches are in the wrong order (not bisectable).
As I mentioned in my earlier comment, please rename this constant (alternator, probably, or dynamodb if you must?) and please also think how we can use the same constant when configuring the CDC log TTL.

File: alternator/streams.cc [hunk 8]
```diff
@@ -494,40 +488,78 @@ future<executor::request_return_type> executor::describe_stream(client_state& cl
...
+
+        // for parent-child stuff we need id:s to be sorted by token
+        static auto cmp = [](const cdc::stream_id& id1, const cdc::stream_id& id2) {
+            return id1.token() < id2.token();
+        };
+
+        // need a prev even if we are skipping stuff
+        if (i != first) {
+            prev = std::prev(i);
+            std::stable_sort(prev->second.streams.begin(), prev->second.streams.end(), cmp);
```
Comment (nyh) [inline alternator/streams.cc:507]: I don't understand this parent-child stuff or what you are sorting or why so it's hard for me to review the validity of this change. Were you able to demonstrate a bug in the old code somehow and this change fixes it? Or how did you test this?

File: test/alternator/test_streams.py [hunk 9]
```diff
@@ -845,9 +848,11 @@ def test_streams_no_records(test_table_ss_keys_only, dynamodbstreams):
     table, arn = test_table_ss_keys_only
     # Get just one shard - any shard - and its LATEST iterator. Because it's
     # LATEST, there will be no data to read from this iterator.
-    shard_id = dynamodbstreams.describe_stream(StreamArn=arn, Limit=1)['StreamDescription']['Shards'][0]['ShardId']
+    shard = dynamodbstreams.describe_stream(StreamArn=arn, Limit=1)['StreamDescription']['Shards'][0]
+    shard_id = shard['ShardId']
     iter = dynamodbstreams.get_shard_iterator(StreamArn=arn, ShardId=shard_id, ShardIteratorType='LATEST')['ShardIterator']
     response = dynamodbstreams.get_records(ShardIterator=iter)
+    assert 'NextShardIterator' in response or 'EndingSequenceNumber' in shard['SequenceNumberRange']
```
Comment (nyh) [inline test/alternator/test_streams.py:855]: I had a comment about this line in the previous PR. I'm don't remember what it was ;-)

**Review by nyh — CHANGES_REQUESTED** [review]
Thanks. Most of the patches look good, but I did have some questions or doubts on some thing so please take a look. Thanks.

File: alternator/streams.cc (hunk 1 above)
Comment (elcallio) [reply alternator/streams.cc:479]: If someone used describe_streams and waits with getting page N until after cdc generations expire (i.e. shards effectively disappear - which will happen in DynamoDB as well), I would assume that he could potentially miss parts of the sequence. But in that case, we will resume at first point > exclusiveshardid in request.

File: alternator/streams.cc (hunk 2 above)
Comment (elcallio) [reply alternator/streams.cc:720]: Actually, on second thought, this should probably go. I put it there to handle potentially changing to range-based-shards eventually, but it is probably better to just retain the zero-uuid threshold so we don't miss any data in the time of generation overlap.

File: alternator/streams.cc (hunk 4 above)
Comment (elcallio) [reply alternator/streams.cc:705]: ARN == table id. `sid` above is shard id. That should generate resourcenotfound. And is tested.

File: alternator/streams.cc (hunk 8 above)
Comment (elcallio) [reply alternator/streams.cc:507]: Since we cannot force generation changes, we cannot really test this. Even if we can, the parent-child relationship will be ambiguous at best, so I don't know if we can verify it really. The code is mainly just trying to provide a better matching of parent-child via token range of ID:s. Old code used _almost_ but not quite sorted ID:s. 
I've added some more code comments on this in next iteration.

File: alternator/streams.cc (hunk 5 above)
Comment (elcallio) [reply alternator/streams.cc:367]: I've updated the comment to include more info.

File: alternator/streams.cc (hunk 8 above)
Comment (elcallio) [reply alternator/streams.cc:529]: See line 515

File: alternator/streams.cc (hunk 3 above)
Comment (elcallio) [reply alternator/streams.cc:649]: test assert added.

**Review by nyh — APPROVED** [review]
