### PR TITLE
cache, mvcc: Preempt cache update when applying range tombstone from memtable

### LINKED ISSUE #2578: Cache update should work with row granularity
Currently it works with partition granularity, which may impact latency if partitions are large.

Remaining work:
  - The algorithm which applies a range tombstone in partition_entry::apply_to_incomplete() scans existing rows covered by the applied range tombstone without preemption.

### LINKED ISSUE #23479: Long reactor stalls after upgrade to 2025.1.0
## Packages

Base Scylla version: `6.2.3-20250119.bff9ddde1283` with build-id `1d62472ad27cbcd54a8de19cc9171ebf3cde0af7`
Target Scylla version (or git commit hash): `2025.1.0-20250325.9dca28d2b818` with build-id `3a706305ef8ac6f14575e4f3441968f67d29d38c`

Kernel Version: `5.15.0-1078-gcp`

## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

In upgrade test from 6.2 (tablets, one rack only) we can observe long reactor stalls (35, from ~60ms to ~800ms), all look similar.
Example (longest one):
```
2025-03-27T14:35:11.100+00:00 rolling-upgrade-artifacts--ubuntu-f-db-node-16b49ef6-0-2     !INFO | scylla[23863]: Reactor stalled for 848 ms on shard 0, in scheduling group main. Backtrace:
[Backtrace #0]
char* std::__copy_move&lt;false, true, std::random_access_iterator_tag&gt;::__copy_m&lt;char const, char&gt;(char const*, char const*, char*) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/stl_algobase.h:452
 (inlined by) char* std::__copy_move_a2&lt;false, char const*, char*&gt;(char const*, char const*, char*) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/stl_algobase.h:520
 (inlined by) char* std::__copy_move_a1&lt;false, char const*, char*&gt;(char const*, char const*, char*) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/stl_algobase.h:548
 (inlined by) char* std::__copy_move_a&lt;false, char const*, char*&gt;(char const*, char const*, char*) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/stl_algobase.h:556
 (inlined by) char* std::copy&lt;char const*, char*&gt;(char const*, char const*, char*) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/stl_algobase.h:650
 (inlined by) seastar::basic_sstring&lt;char, unsigned int, 15u, true&gt;::basic_sstring(char const*, unsigned long) at ././seastar/include/seastar/core/sstring.hh:194
 (inlined by) seastar::basic_sstring&lt;char, unsigned int, 15u, true&gt;::basic_sstring(std::basic_string_view&lt;char, std::char_traits&lt;char&gt; &gt;) at ././seastar/include/seastar/core/sstring.hh:217
 (inlined by) (anonymous namespace)::parse_keyspace_and_table((anonymous namespace)::scylla_rest_client&, boost::program_options::variables_map const&, std::basic_string_view&lt;char, std::char_traits&lt;char&gt; &gt;)::$_0::operator()(std::basic_string_view&lt;char, std::char_traits&lt;char&gt; &gt;, std::basic_string_view&lt;char, std::char_traits&lt;char&gt; &gt;) const at ././tools/scylla-nodetool.cc:354
 (inlined by) (anonymous namespace)::parse_keyspace_and_table((anonymous namespace)::scylla_rest_client&, boost::program_options::variables_map const&, std::basic_string_view&lt;char, std::char_traits&lt;char&gt; &gt;) at ././tools/scylla-nodetool.cc:361
 (inlined by) (anonymous namespace)::tablehistograms_operation((anonymous namespace)::scylla_rest_client&, boost::program_options::variables_map const&) at ././tools/scylla-nodetool.cc:2191
(anonymous namespace)::status_operation((anonymous namespace)::scylla_rest_client&, boost::program_options::variables_map const&) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/stl_algobase.h:453
std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;::_M_data() const at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/basic_string.h:228
 (inlined by) std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;::_M_is_local() const at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/basic_string.h:269
 (inlined by) std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;::basic_string(std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;&&) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/basic_string.h:685
 (inlined by) decltype (::new ((void*)(0)) std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;((std::declval&lt;std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; &gt;)())) std::construct_at&lt;std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; &gt;(std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;*, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;&&) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/stl_construct.h:97
 (inlined by) void std::allocator_traits&lt;std::allocator&lt;std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; &gt; &gt;::construct&lt;std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; &gt;(std::allocator&lt;std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; &gt;&, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;*, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;&&) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/alloc_traits.h:536
 (inlined by) std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;& std::vector&lt;std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;, std::allocator&lt;std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; &gt; &gt;::emplace_back&lt;std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; &gt;(std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;&&) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/vector.tcc:117
 (inlined by) std::vector&lt;std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;, std::allocator&lt;std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; &gt; &gt;::push_back(std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;&&) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/stl_vector.h:1301
 (inlined by) void (anonymous namespace)::Tabulate::add&lt;std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;, seastar::basic_sstring&lt;char, unsigned int, 15u, true&gt;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;, seastar::basic_sstring&lt;char, unsigned int, 15u, true&gt;, seastar::basic_sstring&lt;char, unsigned int, 15u, true&gt;, seastar::basic_sstring&lt;char, unsigned int, 15u, true&gt; &gt;(std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;, seastar::basic_sstring&lt;char, unsigned int, 15u, true&gt;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;, seastar::basic_sstring&lt;char, unsigned int, 15u, true&gt;, seastar::basic_sstring&lt;char, unsigned int, 15u, true&gt;, seastar::basic_sstring&lt;char, unsigned int, 15u, true&gt;) at ././tools/scylla-nodetool.cc:614
 (inlined by) (anonymous namespace)::status_operation((anonymous namespace)::scylla_rest_client&, boost::program_options::variables_map const&) at ././tools/scylla-nodetool.cc:2137
fmt::v10::basic_memory_buffer&lt;char, 500ul, std::allocator&lt;char&gt; &gt;::basic_memory_buffer(std::allocator&lt;char&gt; const&) at /usr/include/fmt/format.h:926
 (inlined by) _ZN3fmt3v109to_stringIN7seastar13basic_sstringIcjLj15ELb1EEETnNSt9enable_ifIXaantsr3std11is_integralIT_EE5valuentsr6detail13has_format_asIS6_EE5valueEiE4typeELi0EEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS6_ at /usr/include/fmt/format.h:4320
 (inlined by) void (anonymous namespace)::Tabulate::add&lt;std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;, seastar::basic_sstring&lt;char, unsigned int, 15u, true&gt;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;, seastar::basic_sstring&lt;char, unsigned int, 15u, true&gt;, seastar::basic_sstring&lt;char, unsigned int, 15u, true&gt;, seastar::basic_sstring&lt;char, unsigned int, 15u, true&gt; &gt;(std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;, seastar::basic_sstring&lt;char, unsigned int, 15u, true&gt;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;, seastar::basic_sstring&lt;char, unsigned int, 15u, true&gt;, seastar::basic_sstring&lt;char, unsigned int, 15u, true&gt;, seastar::basic_sstring&lt;char, unsigned int, 15u, true&gt;) at ././tools/scylla-nodetool.cc:614
 (inlined by) (anonymous namespace)::status_operation((anonymous namespace)::scylla_rest_client&, boost::program_options::variables_map const&) at ././tools/scylla-nodetool.cc:2137
?? ??:0
?? ??:0
seastar::continuation&lt;seastar::internal::promise_base_with_type&lt;void&gt;, seastar::rpc::recv_helper&lt;netw::serializer, std::function&lt;seastar::future&lt;service::join_node_response_result&gt; (utils::tagged_uuid&lt;raft::server_id_tag&gt;, service::join_node_response_params)&gt;, seastar::future&lt;service::join_node_response_result&gt;, utils::tagged_uuid&lt;raft::server_id_tag&gt;, service::join_node_response_params, seastar::rpc::dont_want_client_info, seastar::rpc::dont_want_time_point&gt;(seastar::rpc::signature&lt;seastar::future&lt;service::join_node_response_result&gt; (utils::tagged_uuid&lt;raft::server_id_tag&gt;, service::join_node_response_params)&gt;, std::function&lt;seastar::future&lt;service::join_node_response_result&gt; (utils::tagged_uuid&lt;raft::server_id_tag&gt;, service::join_node_response_params)&gt;&&, seastar::rpc::dont_want_client_info, seastar::rpc::dont_want_time_point)::{lambda(seastar::shared_ptr&lt;seastar::rpc::server::connection&gt;, std::optional&lt;std::chrono::time_point&lt;seastar::lowres_clock, std::chrono::duration&lt;long, std::ratio&lt;1l, 1000000000l&gt; &gt; &gt; &gt;, long, seastar::rpc::rcv_buf, seastar::gate::holder)#1}::operator()(seastar::shared_ptr&lt;seastar::rpc::server::connection&gt;, std::optional&lt;std::chrono::time_point&lt;seastar::lowres_clock, std::chrono::duration&lt;long, std::ratio&lt;1l, 1000000000l&gt; &gt; &gt; &gt;, long, seastar::rpc::rcv_buf, seastar::gate::holder)::{lambda(auto:1)#1}::operator()&lt;seastar::semaphore_units&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt; &gt;(seastar::semaphore_units&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;)::{lambda()#1}::operator()()::{lambda(seastar::future&lt;service::join_node_response_result&gt;)#1}, seastar::future&lt;service::join_node_response_result&gt;::then_wrapped_nrvo&lt;seastar::future&lt;void&gt;, seastar::rpc::recv_helper&lt;netw::serializer, std::function&lt;seastar::future&lt;service::join_node_response_result&gt; (utils::tagged_uuid&lt;raft::server_id_tag&gt;, service::join_node_response_params)&gt;, seastar::future&lt;service::join_node_response_result&gt;, utils::tagged_uuid&lt;raft::server_id_tag&gt;, service::join_node_response_params, seastar::rpc::dont_want_client_info, seastar::rpc::dont_want_time_point&gt;(seastar::rpc::signature&lt;seastar::future&lt;service::join_node_response_result&gt; (utils::tagged_uuid&lt;raft::server_id_tag&gt;, service::join_node_response_params)&gt;, std::function&lt;seastar::future&lt;service::join_node_response_result&gt; (utils::tagged_uuid&lt;raft::server_id_tag&gt;, service::join_node_response_params)&gt;&&, seastar::rpc::dont_want_client_info, seastar::rpc::dont_want_time_point)::{lambda(seastar::shared_ptr&lt;seastar::rpc::server::connection&gt;, std::optional&lt;std::chrono::time_point&lt;seastar::lowres_clock, std::chrono::duration&lt;long, std::ratio&lt;1l, 1000000000l&gt; &gt; &gt; &gt;, long, seastar::rpc::rcv_buf, seastar::gate::holder)#1}::operator()(seastar::shared_ptr&lt;seastar::rpc::server::connection&gt;, std::optional&lt;std::chrono::time_point&lt;seastar::lowres_clock, std::chrono::duration&lt;long, std::ratio&lt;1l, 1000000000l&gt; &gt; &gt; &gt;, long, seastar::rpc::rcv_buf, seastar::gate::holder)::{lambda(auto:1)#1}::operator()&lt;seastar::semaphore_units&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt; &gt;(seastar::semaphore_units&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;)::{lambda()#1}::operator()()::{lambda(seastar::future&lt;service::join_node_response_result&gt;)#1}&gt;(std::function&lt;seastar::future&lt;service::join_node_response_result&gt; (utils::tagged_uuid&lt;raft::server_id_tag&gt;, service::join_node_response_params)&gt;&&)::{lambda(seastar::internal::promise_base_with_type&lt;void&gt;&&, seastar::rpc::recv_helper&lt;netw::serializer, std::function&lt;seastar::future&lt;service::join_node_response_result&gt; (utils::tagged_uuid&lt;raft::server_id_tag&gt;, service::join_node_response_params)&gt;, seastar::future&lt;service::join_node_response_result&gt;, utils::tagged_uuid&lt;raft::server_id_tag&gt;, service::join_node_response_params, seastar::rpc::dont_want_client_info, seastar::rpc::dont_want_time_point&gt;(seastar::rpc::signature&lt;auto:3 ((auto:4)...)&gt;, auto:2&&, auto:5, auto:6)::{lambda(seastar::shared_ptr&lt;seastar::rpc::server::connection&gt;, std::optional&lt;std::chrono::time_point&lt;seastar::lowres_clock, std::chrono::duration&lt;long, std::ratio&lt;1l, 1000000000l&gt; &gt; &gt; &gt;, long, seastar::rpc::rcv_buf, seastar::gate::holder)#1}::operator()(seastar::shared_ptr&lt;seastar::rpc::server::connection&gt;, std::optional&lt;std::chrono::time_point&lt;seastar::lowres_clock, std::chrono::duration&lt;long, std::ratio&lt;1l, 1000000000l&gt; &gt; &gt; &gt;, long, seastar::rpc::rcv_buf, seastar::gate::holder)::{lambda(auto:1)#1}::operator()&lt;seastar::semaphore_units&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt; &gt;(auto:1)::{lambda()#1}::operator()()::{lambda(seastar::future&lt;service::join_node_response_result&gt;)#1}&, seastar::future_state&lt;service::join_node_response_result&gt;&&)#1}, service::join_node_response_result&gt;::run_and_dispose() at ././seastar/include/seastar/core/abort_source.hh:66
std::_Optional_payload_base&lt;seastar::basic_semaphore&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::entry&gt;::_M_reset() at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/optional:?
 (inlined by) std::_Optional_payload&lt;seastar::basic_semaphore&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::entry, false, false, false&gt;::~_Optional_payload() at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/optional:437
 (inlined by) std::_Optional_base&lt;seastar::basic_semaphore&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::entry, false, false&gt;::~_Optional_base() at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/optional:508
 (inlined by) seastar::internal::abortable_fifo&lt;seastar::basic_semaphore&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::entry, seastar::basic_semaphore&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::expiry_handler&gt;::entry::~entry() at ././seastar/include/seastar/core/abortable_fifo.hh:61
 (inlined by) std::default_delete&lt;seastar::internal::abortable_fifo&lt;seastar::basic_semaphore&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::entry, seastar::basic_semaphore&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::expiry_handler&gt;::entry&gt;::operator()(seastar::internal::abortable_fifo&lt;seastar::basic_semaphore&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::entry, seastar::basic_semaphore&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::expiry_handler&gt;::entry*) const at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/unique_ptr.h:93
 (inlined by) std::__uniq_ptr_impl&lt;seastar::internal::abortable_fifo&lt;seastar::basic_semaphore&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::entry, seastar::basic_semaphore&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::expiry_handler&gt;::entry, std::default_delete&lt;seastar::internal::abortable_fifo&lt;seastar::basic_semaphore&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::entry, seastar::basic_semaphore&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::expiry_handler&gt;::entry&gt; &gt;::reset(seastar::internal::abortable_fifo&lt;seastar::basic_semaphore&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::entry, seastar::basic_semaphore&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::expiry_handler&gt;::entry*) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/unique_ptr.h:205
 (inlined by) std::unique_ptr&lt;seastar::internal::abortable_fifo&lt;seastar::basic_semaphore&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::entry, seastar::basic_semaphore&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::expiry_handler&gt;::entry, std::default_delete&lt;seastar::internal::abortable_fifo&lt;seastar::basic_semaphore&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::entry, seastar::basic_semaphore&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::expiry_handler&gt;::entry&gt; &gt;::reset(seastar::internal::abortable_fifo&lt;seastar::basic_semaphore&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::entry, seastar::basic_semaphore&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::expiry_handler&gt;::entry*) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/unique_ptr.h:503
 (inlined by) seastar::internal::abortable_fifo&lt;seastar::basic_semaphore&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::entry, seastar::basic_semaphore&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::expiry_handler&gt;::drop_expired_front() at ././seastar/include/seastar/core/abortable_fifo.hh:96
 (inlined by) seastar::internal::abortable_fifo&lt;seastar::basic_semaphore&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::entry, seastar::basic_semaphore&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::expiry_handler&gt;::pop_front() at ././seastar/include/seastar/core/abortable_fifo.hh:250
 (inlined by) seastar::basic_semaphore&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::signal(unsigned long) at ././seastar/include/seastar/core/semaphore.hh:405
 (inlined by) seastar::semaphore_units&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::return_all() at ././seastar/include/seastar/core/semaphore.hh:551
 (inlined by) seastar::semaphore_units&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;::~semaphore_units() at ././seastar/include/seastar/core/semaphore.hh:531
 (inlined by) seastar::rpc::recv_helper&lt;netw::serializer, std::function&lt;seastar::future&lt;service::join_node_response_result&gt; (utils::tagged_uuid&lt;raft::server_id_tag&gt;, service::join_node_response_params)&gt;, seastar::future&lt;service::join_node_response_result&gt;, utils::tagged_uuid&lt;raft::server_id_tag&gt;, service::join_node_response_params, seastar::rpc::dont_want_client_info, seastar::rpc::dont_want_time_point&gt;(seastar::rpc::signature&lt;seastar::future&lt;service::join_node_response_result&gt; (utils::tagged_uuid&lt;raft::server_id_tag&gt;, service::join_node_response_params)&gt;, std::function&lt;seastar::future&lt;service::join_node_response_result&gt; (utils::tagged_uuid&lt;raft::server_id_tag&gt;, service::join_node_response_params)&gt;&&, seastar::rpc::dont_want_client_info, seastar::rpc::dont_want_time_point)::{lambda(seastar::shared_ptr&lt;seastar::rpc::server::connection&gt;, std::optional&lt;std::chrono::time_point&lt;seastar::lowres_clock, std::chrono::duration&lt;long, std::ratio&lt;1l, 1000000000l&gt; &gt; &gt; &gt;, long, seastar::rpc::rcv_buf, seastar::gate::holder)#1}::operator()(seastar::shared_ptr&lt;seastar::rpc::server::connection&gt;, std::optional&lt;std::chrono::time_point&lt;seastar::lowres_clock, std::chrono::duration&lt;long, std::ratio&lt;1l, 1000000000l&gt; &gt; &gt; &gt;, long, seastar::rpc::rcv_buf, seastar::gate::holder)::{lambda(auto:1)#1}::operator()&lt;seastar::semaphore_units&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt; &gt;(seastar::semaphore_units&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;)::{lambda()#1}::operator()()::{lambda(seastar::future&lt;service::join_node_response_result&gt;)#1}::operator()(seastar::future&lt;service::join_node_response_result&gt;)::{lambda(std::__exception_ptr::exception_ptr)#1}::~exception_ptr() at ././seastar/include/seastar/rpc/rpc_impl.hh:601
 (inlined by) seastar::rpc::recv_helper&lt;netw::serializer, std::function&lt;seastar::future&lt;service::join_node_response_result&gt; (utils::tagged_uuid&lt;raft::server_id_tag&gt;, service::join_node_response_params)&gt;, seastar::future&lt;service::join_node_response_result&gt;, utils::tagged_uuid&lt;raft::server_id_tag&gt;, service::join_node_response_params, seastar::rpc::dont_want_client_info, seastar::rpc::dont_want_time_point&gt;(seastar::rpc::signature&lt;seastar::future&lt;service::join_node_response_result&gt; (utils::tagged_uuid&lt;raft::server_id_tag&gt;, service::join_node_response_params)&gt;, std::function&lt;seastar::future&lt;service::join_node_response_result&gt; (utils::tagged_uuid&lt;raft::server_id_tag&gt;, service::join_node_response_params)&gt;&&, seastar::rpc::dont_want_client_info, seastar::rpc::dont_want_time_point)::{lambda(seastar::shared_ptr&lt;seastar::rpc::server::connection&gt;, std::optional&lt;std::chrono::time_point&lt;seastar::lowres_clock, std::chrono::duration&lt;long, std::ratio&lt;1l, 1000000000l&gt; &gt; &gt; &gt;, long, seastar::rpc::rcv_buf, seastar::gate::holder)#1}::operator()(seastar::shared_ptr&lt;seastar::rpc::server::connection&gt;, std::optional&lt;std::chrono::time_point&lt;seastar::lowres_clock, std::chrono::duration&lt;long, std::ratio&lt;1l, 1000000000l&gt; &gt; &gt; &gt;, long, seastar::rpc::rcv_buf, seastar::gate::holder)::{lambda(auto:1)#1}::operator()&lt;seastar::semaphore_units&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt; &gt;(seastar::semaphore_units&lt;seastar::semaphore_default_exception_factory, seastar::lowres_clock&gt;)::{lambda()#1}::operator()()::{lambda(seastar::future&lt;service::join_node_response_result&gt;)#1}::operator()(seastar::future&lt;service::join_node_response_result&gt;) at ././seastar/include/seastar/rpc/rpc_impl.hh:601
seastar::internal::future_base::clear() at ././seastar/include/seastar/core/future.hh:1122
 (inlined by) seastar::future&lt;seastar::rpc::optional&lt;replica::exception_variant&gt; &gt;::operator=(seastar::future&lt;seastar::rpc::optional&lt;replica::exception_variant&gt; &gt;&&) at ././seastar/include/seastar/core/future.hh:1326
seastar::shared_ptr&lt;seastar::rpc::server::connection&gt;::~shared_ptr() at ././seastar/include/seastar/core/shared_ptr.hh:568
 (inlined by) seastar::rpc::recv_helper&lt;netw::serializer, std::function&lt;seastar::future&lt;seastar::rpc::no_wait_type&gt; (seastar::rpc::client_info const&, seastar::rpc::opt_time_point, utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;)&gt;, seastar::future&lt;seastar::rpc::no_wait_type&gt;, utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;, seastar::rpc::do_want_client_info, seastar::rpc::do_want_time_point&gt;(seastar::rpc::signature&lt;seastar::future&lt;seastar::rpc::no_wait_type&gt; (utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;)&gt;, std::function&lt;seastar::future&lt;seastar::rpc::no_wait_type&gt; (seastar::rpc::client_info const&, seastar::rpc::opt_time_point, utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;)&gt;&&, seastar::rpc::do_want_client_info, seastar::rpc::do_want_time_point)::{lambda(seastar::shared_ptr&lt;seastar::rpc::server::connection&gt;, std::optional&lt;std::chrono::time_point&lt;seastar::lowres_clock, std::chrono::duration&lt;long, std::ratio&lt;1l, 1000000000l&gt; &gt; &gt; &gt;, long, seastar::rpc::rcv_buf, seastar::gate::holder)#1}::operator()(seastar::shared_ptr&lt;seastar::rpc::server::connection&gt;, std::optional&lt;std::chrono::time_point&lt;seastar::lowres_clock, std::chrono::duration&lt;long, std::ratio&lt;1l, 1000000000l&gt; &gt; &gt; &gt;, long, seastar::rpc::rcv_buf, seastar::gate::holder)::{lambda()#1}::operator()() const at ././seastar/include/seastar/rpc/rpc_impl.hh:587
 (inlined by) seastar::future&lt;void&gt; seastar::futurize&lt;seastar::future&lt;void&gt; &gt;::invoke&lt;seastar::rpc::recv_helper&lt;netw::serializer, std::function&lt;seastar::future&lt;seastar::rpc::no_wait_type&gt; (seastar::rpc::client_info const&, seastar::rpc::opt_time_point, utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;)&gt;, seastar::future&lt;seastar::rpc::no_wait_type&gt;, utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;, seastar::rpc::do_want_client_info, seastar::rpc::do_want_time_point&gt;(seastar::rpc::signature&lt;seastar::future&lt;seastar::rpc::no_wait_type&gt; (utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;)&gt;, std::function&lt;seastar::future&lt;seastar::rpc::no_wait_type&gt; (seastar::rpc::client_info const&, seastar::rpc::opt_time_point, utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;)&gt;&&, seastar::rpc::do_want_client_info, seastar::rpc::do_want_time_point)::{lambda(seastar::shared_ptr&lt;seastar::rpc::server::connection&gt;, std::optional&lt;std::chrono::time_point&lt;seastar::lowres_clock, std::chrono::duration&lt;long, std::ratio&lt;1l, 1000000000l&gt; &gt; &gt; &gt;, long, seastar::rpc::rcv_buf, seastar::gate::holder)#1}::operator()(seastar::shared_ptr&lt;seastar::rpc::server::connection&gt;, std::optional&lt;std::chrono::time_point&lt;seastar::lowres_clock, std::chrono::duration&lt;long, std::ratio&lt;1l, 1000000000l&gt; &gt; &gt; &gt;, long, seastar::rpc::rcv_buf, seastar::gate::holder)::{lambda()#1}&gt;(seastar::rpc::recv_helper&lt;netw::serializer, std::function&lt;seastar::future&lt;seastar::rpc::no_wait_type&gt; (seastar::rpc::client_info const&, seastar::rpc::opt_time_point, utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;)&gt;, seastar::future&lt;seastar::rpc::no_wait_type&gt;, utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;, seastar::rpc::do_want_client_info, seastar::rpc::do_want_time_point&gt;(seastar::rpc::signature&lt;seastar::future&lt;seastar::rpc::no_wait_type&gt; (utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;)&gt;, std::function&lt;seastar::future&lt;seastar::rpc::no_wait_type&gt; (seastar::rpc::client_info const&, seastar::rpc::opt_time_point, utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;)&gt;&&, seastar::rpc::do_want_client_info, seastar::rpc::do_want_time_point)::{lambda(seastar::shared_ptr&lt;seastar::rpc::server::connection&gt;, std::optional&lt;std::chrono::time_point&lt;seastar::lowres_clock, std::chrono::duration&lt;long, std::ratio&lt;1l, 1000000000l&gt; &gt; &gt; &gt;, long, seastar::rpc::rcv_buf, seastar::gate::holder)#1}::operator()(seastar::shared_ptr&lt;seastar::rpc::server::connection&gt;, std::optional&lt;std::chrono::time_point&lt;seastar::lowres_clock, std::chrono::duration&lt;long, std::ratio&lt;1l, 1000000000l&gt; &gt; &gt; &gt;, long, seastar::rpc::rcv_buf, seastar::gate::holder)::{lambda()#1}&&) at ././seastar/include/seastar/core/future.hh:2032
 (inlined by) auto seastar::futurize_invoke&lt;seastar::rpc::recv_helper&lt;netw::serializer, std::function&lt;seastar::future&lt;seastar::rpc::no_wait_type&gt; (seastar::rpc::client_info const&, seastar::rpc::opt_time_point, utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;)&gt;, seastar::future&lt;seastar::rpc::no_wait_type&gt;, utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;, seastar::rpc::do_want_client_info, seastar::rpc::do_want_time_point&gt;(seastar::rpc::signature&lt;seastar::future&lt;seastar::rpc::no_wait_type&gt; (utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;)&gt;, std::function&lt;seastar::future&lt;seastar::rpc::no_wait_type&gt; (seastar::rpc::client_info const&, seastar::rpc::opt_time_point, utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;)&gt;&&, seastar::rpc::do_want_client_info, seastar::rpc::do_want_time_point)::{lambda(seastar::shared_ptr&lt;seastar::rpc::server::connection&gt;, std::optional&lt;std::chrono::time_point&lt;seastar::lowres_clock, std::chrono::duration&lt;long, std::ratio&lt;1l, 1000000000l&gt; &gt; &gt; &gt;, long, seastar::rpc::rcv_buf, seastar::gate::holder)#1}::operator()(seastar::shared_ptr&lt;seastar::rpc::server::connection&gt;, std::optional&lt;std::chrono::time_point&lt;seastar::lowres_clock, std::chrono::duration&lt;long, std::ratio&lt;1l, 1000000000l&gt; &gt; &gt; &gt;, long, seastar::rpc::rcv_buf, seastar::gate::holder)::{lambda()#1}&gt;(seastar::rpc::recv_helper&lt;netw::serializer, std::function&lt;seastar::future&lt;seastar::rpc::no_wait_type&gt; (seastar::rpc::client_info const&, seastar::rpc::opt_time_point, utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;)&gt;, seastar::future&lt;seastar::rpc::no_wait_type&gt;, utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;, seastar::rpc::do_want_client_info, seastar::rpc::do_want_time_point&gt;(seastar::rpc::signature&lt;seastar::future&lt;seastar::rpc::no_wait_type&gt; (utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;)&gt;, std::function&lt;seastar::future&lt;seastar::rpc::no_wait_type&gt; (seastar::rpc::client_info const&, seastar::rpc::opt_time_point, utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;)&gt;&&, seastar::rpc::do_want_client_info, seastar::rpc::do_want_time_point)::{lambda(seastar::shared_ptr&lt;seastar::rpc::server::connection&gt;, std::optional&lt;std::chrono::time_point&lt;seastar::lowres_clock, std::chrono::duration&lt;long, std::ratio&lt;1l, 1000000000l&gt; &gt; &gt; &gt;, long, seastar::rpc::rcv_buf, seastar::gate::holder)#1}::operator()(seastar::shared_ptr&lt;seastar::rpc::server::connection&gt;, std::optional&lt;std::chrono::time_point&lt;seastar::lowres_clock, std::chrono::duration&lt;long, std::ratio&lt;1l, 1000000000l&gt; &gt; &gt; &gt;, long, seastar::rpc::rcv_buf, seastar::gate::holder)::{lambda()#1}&&) at ././seastar/include/seastar/core/future.hh:2063
 (inlined by) auto seastar::internal::invoke_func_with_gate&lt;seastar::rpc::recv_helper&lt;netw::serializer, std::function&lt;seastar::future&lt;seastar::rpc::no_wait_type&gt; (seastar::rpc::client_info const&, seastar::rpc::opt_time_point, utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;)&gt;, seastar::future&lt;seastar::rpc::no_wait_type&gt;, utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;, seastar::rpc::do_want_client_info, seastar::rpc::do_want_time_point&gt;(seastar::rpc::signature&lt;seastar::future&lt;seastar::rpc::no_wait_type&gt; (utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;)&gt;, std::function&lt;seastar::future&lt;seastar::rpc::no_wait_type&gt; (seastar::rpc::client_info const&, seastar::rpc::opt_time_point, utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;)&gt;&&, seastar::rpc::do_want_client_info, seastar::rpc::do_want_time_point)::{lambda(seastar::shared_ptr&lt;seastar::rpc::server::connection&gt;, std::optional&lt;std::chrono::time_point&lt;seastar::lowres_clock, std::chrono::duration&lt;long, std::ratio&lt;1l, 1000000000l&gt; &gt; &gt; &gt;, long, seastar::rpc::rcv_buf, seastar::gate::holder)#1}::operator()(seastar::shared_ptr&lt;seastar::rpc::server::connection&gt;, std::optional&lt;std::chrono::time_point&lt;seastar::lowres_clock, std::chrono::duration&lt;long, std::ratio&lt;1l, 1000000000l&gt; &gt; &gt; &gt;, long, seastar::rpc::rcv_buf, seastar::gate::holder)::{lambda()#1}&gt;(seastar::gate::holder&&, seastar::rpc::recv_helper&lt;netw::serializer, std::function&lt;seastar::future&lt;seastar::rpc::no_wait_type&gt; (seastar::rpc::client_info const&, seastar::rpc::opt_time_point, utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;)&gt;, seastar::future&lt;seastar::rpc::no_wait_type&gt;, utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;, seastar::rpc::do_want_client_info, seastar::rpc::do_want_time_point&gt;(seastar::rpc::signature&lt;seastar::future&lt;seastar::rpc::no_wait_type&gt; (utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;)&gt;, std::function&lt;seastar::future&lt;seastar::rpc::no_wait_type&gt; (seastar::rpc::client_info const&, seastar::rpc::opt_time_point, utils::tagged_uuid&lt;table_schema_version_tag&gt;, partition_key, utils::UUID, std::optional&lt;tracing::trace_info&gt;)&gt;&&, seastar::rpc::do_want_client_info, seastar::rpc::do_want_time_point)::{lambda(seastar::shared_ptr&lt;seastar::rpc::server::connection&gt;, std::optional&lt;std::chrono::time_point&lt;seastar::lowres_clock, std::chrono::duration&lt;long, std::ratio&lt;1l, 1000000000l&gt; &gt; &gt; &gt;, long, seastar::rpc::rcv_buf, seastar::gate::holder)#1}::operator()(seastar::shared_ptr&lt;seastar::rpc::server::connection&gt;, std::optional&lt;std::chrono::time_point&lt;seastar::lowres_clock, std::chrono::duration&lt;long, std::ratio&lt;1l, 1000000000l&gt; &gt; &gt; &gt;, long, seastar::rpc::rcv_buf, seastar::gate::holder)::{lambda()#1}&&) at ././seastar/include/seastar/core/gate.hh:316
seastar::internal::promise_base_with_type&lt;void&gt;::promise_base_with_type(seastar::internal::promise_base_with_type&lt;void&gt;&&) at ././seastar/include/seastar/core/future.hh:879
 (inlined by) seastar::continuation_base_with_promise&lt;seastar::internal::promise_base_with_type&lt;void&gt;, void&gt;::continuation_base_with_promise(seastar::internal::promise_base_with_type&lt;void&gt;&&) at ././seastar/include/seastar/core/future.hh:723
 (inlined by) _ZN7seastar12continuationINS_8internal22promise_base_with_typeIvEEZNS_6futureIvE16handle_exceptionIZN15mutation_reader5closeEvEUlNSt15__exception_ptr13exception_ptrEE_Qoooooosr3stdE16is_invocable_r_vINS4_IT_EETL0__S9_Eaaeqsr3stdE12tuple_size_vINSt11conditionalIXsr3stdE9is_same_vINS1_18future_stored_typeIJSB_EE4typeENS1_9monostateEEESt5tupleIJEESK_IJSI_EEE4typeEELi0Esr3stdE16is_invocable_r_vIvSE_S9_Eaaeqsr3stdE12tuple_size_vISO_ELi1Esr3stdE16is_invocable_r_vISB_SE_S9_Eaagtsr3stdE12tuple_size_vISO_ELi1Esr3stdE16is_invocable_r_vISO_SE_S9_EEES5_OSB_EUlSP_E_ZNS5_17then_wrapped_nrvoIS5_SQ_EENS_8futurizeISB_E4typeEOT0_EUlOS3_RSQ_ONS_12future_stateISJ_EEE_vEC2ESX_OSQ_OS12_ at ././seastar/include/seastar/core/future.hh:743
 (inlined by) _ZN7seastar6futureIvE8scheduleINS_8internal22promise_base_with_typeIvEEZNS1_16handle_exceptionIZN15mutation_reader5closeEvEUlNSt15__exception_ptr13exception_ptrEE_Qoooooosr3stdE16is_invocable_r_vINS0_IT_EETL0__S9_Eaaeqsr3stdE12tuple_size_vINSt11conditionalIXsr3stdE9is_same_vINS3_18future_stored_typeIJSB_EE4typeENS3_9monostateEEESt5tupleIJEESK_IJSI_EEE4typeEELi0Esr3stdE16is_invocable_r_vIvSE_S9_Eaaeqsr3stdE12tuple_size_vISO_ELi1Esr3stdE16is_invocable_r_vISB_SE_S9_Eaagtsr3stdE12tuple_size_vISO_ELi1Esr3stdE16is_invocable_r_vISO_SE_S9_EEES1_OSB_EUlSP_E_ZNS1_17then_wrapped_nrvoIS1_SQ_EENS_8futurizeISB_E4typeEOT0_EUlOS5_RSQ_ONS_12future_stateISJ_EEE_EEvSP_SW_OT1_ at ././seastar/include/seastar/core/future.hh:1283
 (inlined by) _ZN7seastar6futureIvE17then_wrapped_nrvoIS1_ZNS1_16handle_exceptionIZN15mutation_reader5closeEvEUlNSt15__exception_ptr13exception_ptrEE_Qoooooosr3stdE16is_invocable_r_vINS0_IT_EETL0__S6_Eaaeqsr3stdE12tuple_size_vINSt11conditionalIXsr3stdE9is_same_vINS_8internal18future_stored_typeIJS8_EE4typeENSD_9monostateEEESt5tupleIJEESI_IJSG_EEE4typeEELi0Esr3stdE16is_invocable_r_vIvSB_S6_Eaaeqsr3stdE12tuple_size_vISM_ELi1Esr3stdE16is_invocable_r_vIS8_SB_S6_Eaagtsr3stdE12tuple_size_vISM_ELi1Esr3stdE16is_invocable_r_vISM_SB_S6_EEES1_OS8_EUlSN_E_EENS_8futurizeIS8_E4typeEOT0_ at ././seastar/include/seastar/core/future.hh:1563
 (inlined by) _ZN7seastar6futureIvE19then_wrapped_commonILb0ES1_ZNS1_16handle_exceptionIZN15mutation_reader5closeEvEUlNSt15__exception_ptr13exception_ptrEE_Qoooooosr3stdE16is_invocable_r_vINS0_IT_EETL0__S6_Eaaeqsr3stdE12tuple_size_vINSt11conditionalIXsr3stdE9is_same_vINS_8internal18future_stored_typeIJS8_EE4typeENSD_9monostateEEESt5tupleIJEESI_IJSG_EEE4typeEELi0Esr3stdE16is_invocable_r_vIvSB_S6_Eaaeqsr3stdE12tuple_size_vISM_ELi1Esr3stdE16is_invocable_r_vIS8_SB_S6_Eaagtsr3stdE12tuple_size_vISM_ELi1Esr3stdE16is_invocable_r_vISM_SB_S6_EEES1_OS8_EUlSN_E_EENS_8futurizeIT0_E4typeEOT1_ at ././seastar/include/seastar/core/future.hh:1588
 (inlined by) _ZN7seastar6futureIvE24then_wrapped_maybe_eraseILb0ES1_ZNS1_16handle_exceptionIZN15mutation_reader5closeEvEUlNSt15__exception_ptr13exception_ptrEE_Qoooooosr3stdE16is_invocable_r_vINS0_IT_EETL0__S6_Eaaeqsr3stdE12tuple_size_vINSt11conditionalIXsr3stdE9is_same_vINS_8internal18future_stored_typeIJS8_EE4typeENSD_9monostateEEESt5tupleIJEESI_IJSG_EEE4typeEELi0Esr3stdE16is_invocable_r_vIvSB_S6_Eaaeqsr3stdE12tuple_size_vISM_ELi1Esr3stdE16is_invocable_r_vIS8_SB_S6_Eaagtsr3stdE12tuple_size_vISM_ELi1Esr3stdE16is_invocable_r_vISM_SB_S6_EEES1_OS8_EUlSN_E_EENS_8futurizeIT0_E4typeEOT1_ at ././seastar/include/seastar/core/future.hh:1541
 (inlined by) _ZNR7seastar6futureIvE12then_wrappedITkSt9invocableINS0_IT_EEEZNS1_16handle_exceptionIZN15mutation_reader5closeEvEUlNSt15__exception_ptr13exception_ptrEE_Qoooooosr3stdE16is_invocable_r_vIS6_TL0__SA_Eaaeqsr3stdE12tuple_size_vINSt11conditionalIXsr3stdE9is_same_vINS_8internal18future_stored_typeIJS4_EE4typeENSE_9monostateEEESt5tupleIJEESJ_IJSH_EEE4typeEELi0Esr3stdE16is_invocable_r_vIvSC_SA_Eaaeqsr3stdE12tuple_size_vISN_ELi1Esr3stdE16is_invocable_r_vIS4_SC_SA_Eaagtsr3stdE12tuple_size_vISN_ELi1Esr3stdE16is_invocable_r_vISN_SC_SA_EEES1_OS4_EUlSO_E_S1_EENS_8futurizeIT0_E4typeESO_ at ././seastar/include/seastar/core/future.hh:1526
 (inlined by) _ZN7seastar6futureIvE16handle_exceptionIZN15mutation_reader5closeEvEUlNSt15__exception_ptr13exception_ptrEE_Qoooooosr3stdE16is_invocable_r_vINS0_IT_EETL0__S5_Eaaeqsr3stdE12tuple_size_vINSt11conditionalIXsr3stdE9is_same_vINS_8internal18future_stored_typeIJS7_EE4typeENSC_9monostateEEESt5tupleIJEESH_IJSF_EEE4typeEELi0Esr3stdE16is_invocable_r_vIvSA_S5_Eaaeqsr3stdE12tuple_size_vISL_ELi1Esr3stdE16is_invocable_r_vIS7_SA_S5_Eaagtsr3stdE12tuple_size_vISL_ELi1Esr3stdE16is_invocable_r_vISL_SA_S5_EEES1_OS7_ at ././seastar/include/seastar/core/future.hh:1726
 (inlined by) mutation_reader::close() at ././readers/mutation_reader.hh:564
 (inlined by) single_partition_populating_reader::close() at ././row_cache.cc:486
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 3 nodes (n2-highmem-64)

Scylla Nodes used in this run:
- rolling-upgrade-artifacts--ubuntu-f-db-node-16b49ef6-0-3 (35.227.79.159 | 10.142.0.36) (shards: 60)
- rolling-upgrade-artifacts--ubuntu-f-db-node-16b49ef6-0-2 (34.73.120.140 | 10.142.15.201) (shards: 60)
- rolling-upgrade-artifacts--ubuntu-f-db-node-16b49ef6-0-1 (34.74.105.126 | 10.142.0.32) (shards: 60)

OS / Image: `https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts` (gce: undefined_region)

Test: `rolling-upgrade-ubuntu2004-test`
Test id: `16b49ef6-0501-4b12-8ecb-678a48f2a9c3`
Test name: `scylla-2025.1/rolling-upgrade/rolling-upgrade-ubuntu2004-test`
Test method: `upgrade_test.UpgradeTest.test_generic_cluster_upgrade`
Test config file(s):

- [generic-rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/ed80f7a93d09efbfc801d5c1421755796615424f/test-cases/upgrades/generic-rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 16b49ef6-0501-4b12-8ecb-678a48f2a9c3`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=16b49ef6-0501-4b12-8ecb-678a48f2a9c3)
- Show all stored logs command: `$ hydra investigate show-logs 16b49ef6-0501-4b12-8ecb-678a48f2a9c3`

## Logs:
- **db-cluster-16b49ef6.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/16b49ef6-0501-4b12-8ecb-678a48f2a9c3/20250327_150021/db-cluster-16b49ef6.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/16b49ef6-0501-4b12-8ecb-678a48f2a9c3/20250327_150021/db-cluster-16b49ef6.tar.zst)
- **sct-runner-events-16b49ef6.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/16b49ef6-0501-4b12-8ecb-678a48f2a9c3/20250327_150021/sct-runner-events-16b49ef6.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/16b49ef6-0501-4b12-8ecb-678a48f2a9c3/20250327_150021/sct-runner-events-16b49ef6.tar.zst)
- **sct-16b49ef6.log.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/16b49ef6-0501-4b12-8ecb-678a48f2a9c3/20250327_150021/sct-16b49ef6.log.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/16b49ef6-0501-4b12-8ecb-678a48f2a9c3/20250327_150021/sct-16b49ef6.log.tar.zst)
- **loader-set-16b49ef6.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/16b49ef6-0501-4b12-8ecb-678a48f2a9c3/20250327_150021/loader-set-16b49ef6.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/16b49ef6-0501-4b12-8ecb-678a48f2a9c3/20250327_150021/loader-set-16b49ef6.tar.zst)
- **monitor-set-16b49ef6.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/16b49ef6-0501-4b12-8ecb-678a48f2a9c3/20250327_150021/monitor-set-16b49ef6.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/16b49ef6-0501-4b12-8ecb-678a48f2a9c3/20250327_150021/monitor-set-16b49ef6.tar.zst)
- **ssl-conf-16b49ef6.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/16b49ef6-0501-4b12-8ecb-678a48f2a9c3/20250327_150021/ssl-conf-16b49ef6.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/16b49ef6-0501-4b12-8ecb-678a48f2a9c3/20250327_150021/ssl-conf-16b49ef6.tar.zst)
- **builder-16b49ef6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/16b49ef6-0501-4b12-8ecb-678a48f2a9c3/upload_20250327_150211/builder-16b49ef6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/16b49ef6-0501-4b12-8ecb-678a48f2a9c3/upload_20250327_150211/builder-16b49ef6.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-2025.1/job/rolling-upgrade/job/rolling-upgrade-ubuntu2004-test/10/)
[Argus](https://argus.scylladb.com/test/92640463-b9be-4373-89d2-a06fffa2fba3/runs?additionalRuns[]=16b49ef6-0501-4b12-8ecb-678a48f2a9c3)
</details>

### PR DESCRIPTION
**Pull request by tgrabiec**
Range tombstones are represented as entry attributes, which applies to
the interval between entries. So if a range tombstone covers many
rows, to apply it we have to update all covered entries.  In some
workloads that could be many entries, even the whole cache.  Before
the patch, we did this update without preemption, which can cause
reactor stalls in such workloads.

This scenario is already covered by mvcc_tests,
e.g. test_apply_to_incomplete_respects_continuity. And I verified that
the new preemption point is hit in the test.

perf-row-cache-update results show no significant stalls anymore (max
2ms scheduling delay, instead of previous 1.5 s):

    Generated 1124195 rows
    Memtable fill took 4179.457520 [ms], {count: 8295, 99%: 0.654949 [ms], max: 32.817176 [ms]}
    Draining...
    took 0.000616 [ms]
    cache: 2506/2948 [MB], memtable: 781/1024 [MB], alloc/comp: 1051/662 [MB] (amp: 0.630)
    update: 2874.157471 [ms], preemption: {count: 26650, 99%: 1.131752 [ms], max: 2.068762 [ms]}, cache: 3027/3973 [MB], alloc/comp: 3951/2424 [MB] (amp: 0.614), pr/me/dr 1124195/0/0

Fixes #23479
Fixes #2578

### CODE REVIEW

File: db/partition_snapshot_row_cursor.hh [hunk 1]
```diff
@@ -542,6 +542,7 @@ public:
     // Returns the range tombstone for the key range adjacent to the cursor's position from the side of smaller keys.
     // Excludes the range for the row itself. That information is returned by range_tombstone_for_row().
     // It's possible that range_tombstone() is empty and range_tombstone_for_row() is not empty.
+    // Note that this is different from the meaning of rows_entry::range_tombstone(), which includes the row itself.
     tombstone range_tombstone() const { return _range_tombstone; }
```
Comment (avikivity) [inline db/partition_snapshot_row_cursor.hh:546]: Should be renamed to range_tombstone_up_to_this_clustering_key_exclusive() or something, but not in scope here.
