### PR TITLE
utf8: Print invalid UTF-8 character position

### LINKED ISSUE #3016: Improve validation error messages
If utf8 field validation fails, the CQL client will get:
```
marshaling error: Conversion failed
```

It's cryptic. We should mention that validation failed, for which table and which column. If possible, what was the offending position in the string.

### PR DESCRIPTION
**Pull request by avelanarius**
#### Summary
Before this change, if there was a UTF-8 validation error, Scylla provided no further information about location of invalid character inside the offending string.

Added new `validate_with_error_position` function, which returns a position of invalid UTF-8 byte in a string. Modified all "invalid UTF-8" exception messages to present a location information to user (below - in bold highlighted added new text):

- Invalid UTF-8 string inside prepared statement argument:
`exceptions::invalid_request_exception: Exception while binding column b: marshaling error: Validation failed - non-UTF8 character in a UTF8 string,` **`at byte offset 0`**
- Server-side message returned to the Java Cassandra client:
`Exception in thread "main" com.datastax.oss.driver.api.core.servererrors.ProtocolError: Cannot decode string as UTF8` **`, invalid character at byte offset 45`**

Fixes #3016 

#### Why `validate_with_error_position` is done in two passes?
At first I considered changing existing functions to return a error position instead of bool error/no error. One of the existing implementations is a SIMD branchfree (in the main loop) method, which goes through the entire string accumulating state in `error` vector (no short-circuit!). In order to return a position I would have to:

a) change the loop to short-circuit, eliminating the branchfree aspect of the implementation
or
b) somehow accumulate the position alongside/in the `error` vector, adding additional operations which might make it slower
https://github.com/scylladb/scylla/blob/6fadba56cc18bebe6648e6aec09be1b0b93f4817/utils/utf8.cc#L461-L462 

As (probably) most strings are valid UTF-8, in those cases only a one (SIMD optimized) pass is performed. If there is an UTF8 error, in current implementation a slower naive pass is performed to find the error position - I think a good tradeoff.

### CODE REVIEW

File: utils/utf8.cc [hunk 1]
```diff
@@ -491,16 +494,25 @@ bool validate(const uint8_t *data, size_t len) {
...
 
 #else
 // No SIMD implementation for this arch, fallback to naive method
 bool validate(const uint8_t *data, size_t len) {
-    return validate_naive(data, len);
+    return validate_naive(data, len) == -1;
 }
 #endif
 
+ssize_t validate_with_error_position(const uint8_t *data, size_t len) {
```
Comment (penberg) [inline utils/utf8.cc:507]: You could use `std::optional<size_t>` as the return type and indicate lack of error with `std::nullopt`.

**Review by penberg — CHANGES_REQUESTED** [review]

File: utils/utf8.cc (hunk 1 above)
Comment (avikivity) [reply utils/utf8.cc:507]: I agree that for the public interface it's better to avoid magic return values.

Comment (avelanarius) [reply utils/utf8.cc]: Changed to `std::optional` in amended commit.

Found that previously I forgot to fix one unit test (checking for hardcoded exception message) - it is now fixed and all unit tests pass correctly.

https://github.com/scylladb/scylla/pull/7169/files#diff-43be90fff306ebda1a2855a78a22daa1L577-R577
