### PR TITLE
cdc: disallow creating nested cdc logs

### LINKED ISSUE #5967: nested cdc for _scylla_cdc_log tables should not be enabled
*Installation details*
Scylla version (or git commit hash): 666.development-0.20200210.43097854a5e
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

### Description

I want to enable CDC for a _scylla_cdc_log table, when user's table has write/delete ops _scylla_cdc_log table will be updated by scylla.

CDC fusion wasn't caused in my test, the write of _scylla_cdc_log table is different from user's regular query.

But the alter succeeded and we can see CDC: true in schema of _scylla_cdc_log.
And there is a small stall in the alter.

```
cqlsh> alter table cdc_test.test_table_scylla_cdc_log  with cdc = {'preimage': 'true', 'enabled': 'true', 'ttl': '601'} ;
cqlsh> desc table cdc_test.test_table_scylla_cdc_log;

CREATE TABLE cdc_test.test_table_scylla_cdc_log (
    stream_id_1 bigint,
    stream_id_2 bigint,
    time timeuuid,
    batch_seq_no int,
    "_boy" frozen<tuple<tinyint, boolean>>,
    "_name" frozen<tuple<tinyint, text>>,
    "_number" frozen<tuple<tinyint, int>>,
    "_pkid" text,
    "_starttime" frozen<tuple<tinyint, timestamp>>,
    "_users" frozen<tuple<tinyint, frozen<list<int>>>>,
    "_vage" frozen<tuple<tinyint, varint>>,
    "_value" frozen<tuple<tinyint, blob>>,
    "_vname" frozen<tuple<tinyint, text>>,
    "_weight" frozen<tuple<tinyint, decimal>>,
    operation tinyint,
    ttl bigint,
    PRIMARY KEY ((stream_id_1, stream_id_2), time, batch_seq_no)
) WITH CLUSTERING ORDER BY (time ASC, batch_seq_no ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = 'CDC log for cdc_test.test_table'
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

cdc = {'preimage': 'true', 'enabled': 'true', 'ttl': '601'}
```

```
Mar 06 01:01:53 amos-centos7 scylla[3685]:  [shard 0] schema_tables - Creating cdc_test.test_table_scylla_cdc_log_scylla_cdc_log id=112665e0-5f46-11ea-8ed8-000000000000     version=8c697f59-cb64-3bcf-84d2-758457ceebe7
Mar 06 01:01:53 amos-centos7 scylla[3685]:  [shard 0] schema_tables - Altering cdc_test.test_table_scylla_cdc_log id=8f0011b0-5f45-11ea-8ed8-000000000000 version=90ab0f32-  7f67-375e-be55-3b98c84793b2
Mar 06 01:01:53 amos-centos7 scylla[3685]:  [shard 0] query_processor - Column definitions for cdc_test.test_table_scylla_cdc_log changed, invalidating related prepared     statements
Mar 06 01:01:53 scylla[3685]: Reactor stalled for 581 ms on shard 0.
01:01:53 scylla[3685]: Backtrace:
01:01:53 scylla[3685]: 0x0000000002d2f862
01:01:53 scylla[3685]: 0x0000000002cd167b
01:01:53 scylla[3685]: 0x0000000002cd1ba2
01:01:53 scylla[3685]: 0x0000000002cd1ed7
01:01:53 scylla[3685]: 0x00007f7be2bd8b1f
01:01:53 scylla[3685]: 0x0000000000f0d4df
01:01:53 scylla[3685]: 0x0000000000f3b11e
01:01:53 scylla[3685]: 0x0000000000f3b204
01:01:53 scylla[3685]: 0x0000000000e55661
01:01:53 scylla[3685]: 0x0000000000e57eb3
01:01:53 scylla[3685]: 0x0000000000ed405b
01:01:53 scylla[3685]: 0x0000000000ed4198
01:01:53 scylla[3685]: 0x0000000000ed4dcf
01:01:53 scylla[3685]: 0x0000000000ed5076
01:01:53 scylla[3685]: 0x0000000000ed6fc4
01:01:53 scylla[3685]: 0x0000000000d11d56
01:01:53 scylla[3685]: 0x0000000000cad117
01:01:53 scylla[3685]: 0x0000000000cad50f
01:01:53 scylla[3685]: 0x0000000000cc191b
01:01:53 scylla[3685]: 0x0000000000cee81a
01:01:53 scylla[3685]: 0x0000000000cee633
01:01:53 scylla[3685]: 0x0000000000ceee3c
01:01:53 scylla[3685]: 0x0000000002c6e8cc
01:01:53 scylla[3685]: 0x0000000002ccd870
01:01:53 scylla[3685]: 0x0000000002ccda7f
01:01:53 scylla[3685]: 0x0000000002d09425
01:01:53 scylla[3685]: 0x0000000002c6af8f
01:01:53 scylla[3685]: 0x0000000002c6c0be
01:01:53 scylla[3685]: 0x0000000000c70520
01:01:53 scylla[3685]: /opt/scylladb/libreloc/libc.so.6+0x00000000000271a2
01:01:53 scylla[3685]: 0x0000000000b9b02d
01:01:53 scylla[3685]:  [shard 0] database - Schema version changed to bd453399-9d0a-3469-8f20-6f3b160e6eff
```
### Additional

- a table `cdc_test.test_table_scylla_cdc_log_scylla_cdc_log` was created for `cdc_test.test_table_scylla_cdc_log`, but the content is empty.
- I tried to manually delete one record from `cdc_test.test_table_scylla_cdc_log`, then one recored was added to `cdc_test.test_table_scylla_cdc_log_scylla_cdc_log`;

```
cqlsh> desc TABLE cdc_test.test_table_scylla_cdc_log_scylla_cdc_log ;

CREATE TABLE cdc_test.test_table_scylla_cdc_log_scylla_cdc_log (
    stream_id_1 bigint,
    stream_id_2 bigint,
    time timeuuid,
    batch_seq_no int,
    "__boy" frozen<tuple<tinyint, frozen<tuple<tinyint, boolean>>>>,
    "__name" frozen<tuple<tinyint, frozen<tuple<tinyint, text>>>>,
    "__number" frozen<tuple<tinyint, frozen<tuple<tinyint, int>>>>,
    "__pkid" frozen<tuple<tinyint, text>>,
    "__starttime" frozen<tuple<tinyint, frozen<tuple<tinyint, timestamp>>>>,
    "__users" frozen<tuple<tinyint, frozen<tuple<tinyint, frozen<list<int>>>>>>,
    "__vage" frozen<tuple<tinyint, frozen<tuple<tinyint, varint>>>>,
    "__value" frozen<tuple<tinyint, frozen<tuple<tinyint, blob>>>>,
    "__vname" frozen<tuple<tinyint, frozen<tuple<tinyint, text>>>>,
    "__weight" frozen<tuple<tinyint, frozen<tuple<tinyint, decimal>>>>,
    "_batch_seq_no" int,
    "_operation" frozen<tuple<tinyint, tinyint>>,
    "_stream_id_1" bigint,
    "_stream_id_2" bigint,
    "_time" timeuuid,
    "_ttl" frozen<tuple<tinyint, bigint>>,
    operation tinyint,
    ttl bigint,
    PRIMARY KEY ((stream_id_1, stream_id_2), time, batch_seq_no)
) WITH CLUSTERING ORDER BY (time ASC, batch_seq_no ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = 'CDC log for cdc_test.test_table_scylla_cdc_log'
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 601
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';


cqlsh> select * from  cdc_test.test_table_scylla_cdc_log_scylla_cdc_log ;

 stream_id_1 | stream_id_2 | time | batch_seq_no | __boy | __name | __number | __pkid | __starttime | __users | __vage | __value | __vname | __weight | _batch_seq_no | _operation | _stream_id_1 | _stream_id_2 | _time | _ttl | operation | ttl
-------------+-------------+------+--------------+-------+--------+----------+--------+-------------+---------+--------+---------+---------+----------+---------------+------------+--------------+--------------+-------+------+-----------+-----

(0 rows)
cqlsh> select * from cdc_test.test_table_scylla_cdc_log limit 1;

 stream_id_1         | stream_id_2          | time                                 | batch_seq_no | _boy | _name | _number | _pkid   | _starttime | _users | _vage | _value  | _vname | _weight | operation | ttl
---------------------+----------------------+--------------------------------------+--------------+------+-------+---------+---------+------------+--------+-------+--------+--------+---------+-----------+------
 7025871201111925701 | -5305072577343960140 | 9125fef0-5f45-11ea-bc9d-72b8172edeff |            0 | null |  null |    null | @f!rIr7 |       null |   null |  null |   null  |   null |    null |         5 | null

(1 rows)
cqlsh> select * from  cdc_test.test_table_scylla_cdc_log_scylla_cdc_log ;

 stream_id_1         | stream_id_2          | time                                 | batch_seq_no | __boy | __name | __number | __pkid | __starttime | __users | __vage |    __value | __vname | __weight | _batch_seq_no | _operation | _stream_id_1        | _stream_id_2         | _time | _ttl | operation | ttl
---------------------+----------------------+--------------------------------------+--------------+-------+--------+----------+--------+-------------+---------+--------+---------+---------+----------+---------------+------------+---------------------+----------------------+-------+------+-----------+------
 7025871201111925701 | -5305072577343960140 | ad8f450e-5f47-11ea-c9e6-709e7ab09774 |            0 |  null |   null |     null |   null |        null |    null |   null |    null |    null |     null |          null |       null | 7025871201111925701 | -5305072577343960140 |  null | null |         5 | null

(1 rows)
cqlsh>

```

@haaawk @slivne

### PR DESCRIPTION
**Pull request by piodul**
This change disallows creating CDC log tables for already existing CDC log tables. CDC logs nested in that way are not really useful and do not work at the moment, therefore disallowing their creation prevents confusion.

Fixes #5967
Tests: unit(dev)

### CODE REVIEW

File: cdc/log.cc [hunk 1]
```diff
@@ -161,6 +164,15 @@ class cdc::cdc_service::impl : service::migration_listener::empty_listener {
     future<> append_mutations(Iter i, Iter e, schema_ptr s, lowres_clock::time_point, std::vector<mutation>&);
 
 private:
+    static void check_for_attempt_to_create_nested_cdc_log(const schema& schema) {
```
Comment (jul-stas) [inline cdc/log.cc]: nit: `schema` is a name collision here. Harmless, so I'm not insisting.

**Comment by psarna** [comment]
queued as 395c7eeb9
