### PR TITLE
repair: Handle everywhere_topology in bootstrap_with_repair  

### LINKED ISSUE #8503: bootstrap_with_repair badly formatted exception: expected 1 node losing range but found more nodes={}
As seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/3414/artifact/logs-gating.release.2/1618586526989_replace_address_test.TestReplaceAddress_rbo_enabled.replace_active_node_test/node2.log
```
ERROR 2021-04-16 15:22:05,952 [shard 0] init - Startup failed: std::runtime_error (bootstrap_with_repair: keyspace=system_distributed_everywhere, range=(9163005485582434440, 9188926636396914056], expected 1 node losing range but found more nodes={})
```

`nodes` is not formatted into the exception string.

Introduced in 9c67389cc8d77c6eb60234c96cc5ffbaae2771a6 (4.0)

### PR DESCRIPTION
**Pull request by asias**
repair: Handle everywhere_topology in bootstrap_with_repair
 
 The everywhere_topology returns the number of nodes in the cluster as
 RF. This makes only streaming from the node losing the range impossible
 since no node is losing the range after bootstrap.
 
 Shortcut to stream from all nodes in local dc in case the keyspace is
 everywhere_topology.
 
 Fixes #8503

### CODE REVIEW

File: repair/repair.cc [hunk 1]
```diff
@@ -1630,7 +1631,7 @@ future<> bootstrap_with_repair(seastar::sharded<database>& db, seastar::sharded<
                             auto nodes = boost::copy_range<std::vector<gms::inet_address>>(old_nodes |
                                     boost::adaptors::filtered([&] (const gms::inet_address& node) { return !new_nodes.contains(node); }));
                             if (nodes.size() != 1) {
-                                throw std::runtime_error(format("bootstrap_with_repair: keyspace={}, range={}, expected 1 node losing range but found more nodes={}",
+                                throw std::runtime_error(format("bootstrap_with_repair: keyspace={}, range={}, expected 1 node losing range but found nodes={}",
```
Comment (bhalevy) [inline repair/repair.cc:1634]: How about printing also `nodes.size()`?

Comment (bhalevy) [reply repair/repair.cc:1634]: I propose:
```
                                throw std::runtime_error(format("bootstrap_with_repair: keyspace={}, range={}, expected 1 node losing range but found {} nodes ({}),
                                        keyspace_name, desired_range, nodes.size(), nodes));
```

**Review by bhalevy — CHANGES_REQUESTED** [review]

File: repair/repair.cc (hunk 1 above)
Comment (asias) [reply repair/repair.cc]: Ok, I added the size in v2.

**Comment by asias** [comment]
Changes in v2:
- Print number of nodes

File: repair/repair.cc [hunk 2]
```diff
@@ -1656,7 +1657,9 @@ future<> bootstrap_with_repair(seastar::sharded<database>& db, seastar::sharded<
                         };
                         auto old_endpoints_in_local_dc = get_old_endpoints_in_local_dc();
                         auto rf_in_local_dc = get_rf_in_local_dc();
-                        if (old_endpoints.size() == strat.get_replication_factor()) {
+                        if (everywhere_topology) {
+                            neighbors = old_endpoints_in_local_dc;
```
Comment (nyh) [inline repair/repair.cc:1661]: Does this stream the data from *all* the nodes - potentially a hundred of them? Is this what we want to do?

Comment (asias) [reply repair/repair.cc:1661]: We do not need to stream all the same data N  times. We need to sync between all the nodes with repair though. In practice, I doubt real user would use everywhere topology to store massive data. Another point is that user uses few fat nodes instead of hundreds of tiny nodes.

Comment (bhalevy) [reply repair/repair.cc:1661]: Then why repair from endpoints only in local_dc rather than everywhere, i.e. in other dc's as well?

I'm not sure what are the defined/desired semantics of EverywhereStrategy.
https://docs.datastax.com/en/dse/5.1/cql/cql/cql_using/cqlKeyspacesAbout.html
```
EveryWhereStrategy is a specialized DataStax Enterprise strategy used by the dse_system keyspace and is not intended for customer use.
```

And https://support.datastax.com/hc/en-us/articles/208026816-DSE-EverywhereStrategy-is-not-understood-by-Apache-Cassandra-non-DSE-nodes-and-can-cause-restart-failures proposes:
```
Workaround
The best approach is to keep the DSE node in the cluster and then alter the replication strategy for the dse_system keyspace to one that is understood by all nodes, for example:

ALTER KEYSPACE dse_system WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1':1 ,'DC2':1};

```

So the recommendation above seems to indicate that it refers to nodes on all dc's.

Comment (bhalevy) [reply repair/repair.cc:1661]: How do we define it? Is it documented anywhere? (it should be wither in the source tree if it's internal or in the user docs if it's exposed to users)

**Review by tgrabiec — COMMENTED** [review]
I guess it's fine as a quick fix, but it's not good that we need to special case for strategy type like that. Can the code be refactored to work with any possible replication strategy?

**Comment by asias** [comment]
> I guess it's fine as a quick fix, but it's not good that we need to special case for strategy type like that. Can the code be refactored to work with any possible replication strategy?

The algorithm for the special strategy is special. We have to handle them on a case by case basis.

File: repair/repair.cc (hunk 2 above)
Comment (asias) [reply repair/repair.cc:1661]: The most safe way is to stream from all nodes from all dcs. It is comprise between speed and safety to stream from local dcs only. This is also consistent with network_topology where bootstrap streams from local dc.

I do not think we even want to allow user to use the  EverywhereStrategy at all. How we choose nodes to stream from is completely internal and should not be exposed to users. 

I will update docs/design-notes/repair_based_node_ops.md.

Comment (asias) [reply repair/repair.cc:1661]: PR sent: https://github.com/scylladb/scylla/pull/8518
