### PR TITLE
Compaction fix stall in perform cleanup

### LINKED ISSUE #6662: stall 16262 ms occurred on new added nemesis in cleanup table
*Installation details*
Scylla version (or git commit hash): 4.1.rc2-0.20200615.81dc8eeec74
Cluster size: 1
Loader number: 5
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-04779f357686fc0c0 (eu-west-1)

### Description

At the end of Decommission Nemesis, we try to cleanup all the test tables on all db nodes one by one, there was a big stall in the new added node in cleanup feeds table on the new node.

### Test job
- https://jenkins.scylladb.com/view/scylla-4.1/job/scylla-4.1/job/longevity/job/longevity-5000-tables/2/
- test id: e09e8414-1e92-48a8-ba88-2fbbe6af58c3
- SCT Config YAML: https://github.com/scylladb/scylla-cluster-tests/blob/branch-4.1/test-cases/longevity/longevity-5000-tables.yaml

### Test log:
- db log: https://cloudius-jenkins-test.s3.amazonaws.com/e09e8414-1e92-48a8-ba88-2fbbe6af58c3/20200616_202645/db-cluster-e09e8414.zip    

### Key logs with timestamp

- at the end of decommission, we try to clean up all test tables on all nodes one by one
- big stall occurred when feeds table is cleanup on the new added node

```
At the end of Decommission nemesis, there was a big stall in the new added node.

< t:2020-06-16 18:48:11,556 f:nemesis.py      l:662  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method show_toppartitions
< t:2020-06-16 19:19:04,969 f:nemesis.py      l:662  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method nodetool_decommission

< t:2020-06-16 19:33:17,196 f:nemesis.py      l:431  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: Adding new node
 to cluster...

< t:2020-06-16 19:47:15,488 f:cluster.py      l:2449 c:sdcm.cluster_aws     p:DEBUG > Node longevity-5000-tables-4-1-db-node-e0
9e8414-1 [63.34.20.48 | 10.0.44.9] (seed: False): Command 'nodetool  cleanup feeds' duration -> 58.269145011901855 s
< t:2020-06-16 19:48:13,664 f:cluster.py      l:2449 c:sdcm.cluster_aws     p:DEBUG > Node longevity-5000-tables-4-1-db-node-e0
9e8414-2 [34.254.89.106 | 10.0.131.15] (seed: False): Command 'nodetool  cleanup feeds' duration -> 58.17553377151489 s
< t:2020-06-16 19:49:12,047 f:cluster.py      l:2449 c:sdcm.cluster_aws     p:DEBUG > Node longevity-5000-tables-4-1-db-node-e0
9e8414-3 [176.34.68.57 | 10.0.247.24] (seed: False): Command 'nodetool  cleanup feeds' duration -> 58.36575698852539 s
< t:2020-06-16 19:50:08,060 f:cluster.py      l:2449 c:sdcm.cluster_aws     p:DEBUG > Node longevity-5000-tables-4-1-db-node-e0
9e8414-5 [54.171.51.254 | 10.0.158.167] (seed: False): Command 'nodetool  cleanup feeds' duration -> 55.98810267448425 s
< t:2020-06-16 19:51:01,981 f:cluster.py      l:2449 c:sdcm.cluster_aws     p:DEBUG > Node longevity-5000-tables-4-1-db-node-e09e8414-6 [3.250.140.41 | 10.0.171.237] (seed: False): Command 'nodetool  cleanup feeds' duration -> 53.90695643424988 s

### cleanup feeds table on db-node-7 (the new added node)
 < t:2020-06-16 19:51:01,981 f:remote.py       l:306  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@10.0.196.114]: Running command "nodetool  cleanup feeds"...

2020-06-16T19:51:33+00:00  longevity-5000-tables-4-1-db-node-e09e8414-7 !INFO
| scylla: Reactor stalled for 16262 ms on shard 4.
| scylla: Backtrace:
| scylla: 0x0000000002e0ce32
| scylla: 0x0000000002db6474
| scylla: 0x0000000002db69a2
| scylla: 0x0000000002db6cd7
| scylla: 0x00007fd1bdff1b1f
| scylla: 0x0000000002d73672
| scylla: 0x0000000001e880d5
| scylla: 0x0000000001e81936
| scylla: 0x0000000001e7de40
| scylla: 0x0000000001e7df30
| scylla: 0x00000000021fbb1e
| scylla: 0x00000000013add96
| scylla: 0x00000000013b35bf
| scylla: 0x00000000013cb60f
| scylla: 0x000000000267f347
| scylla: 0x00000000026aa7cf
| scylla: 0x0000000000c967e8
| scylla: 0x0000000002db29a0
| scylla: 0x0000000002db2baf
| scylla: 0x0000000002de79c5
| scylla: 0x0000000002df60fc
| scylla: 0x0000000002d8529d

< t:2020-06-16 19:52:57,973 f:remote.py       l:156  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.196.114]: Command "nodetool  cleanup feeds" finished with status 0
< t:2020-06-16 19:52:57,973 f:cluster.py      l:2449 c:sdcm.cluster_aws     p:DEBUG > Node longevity-5000-tables-4-1-db-node-e09e8414-7 [34.247.167.80 | 10.0.196.114] (seed: False): Command 'nodetool  cleanup feeds' duration -> 115.99123239517212 s

< t:2020-06-16 19:52:57,973 f:nemesis.py      l:672  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method nodetool_decommission
```

### PR DESCRIPTION
**Pull request by asias**
compaction_manager: Avoid stall in perform_cleanup
    
The following stall was seen during a cleanup operation:
    
    scylla: Reactor stalled for 16262 ms on shard 4.
    
    | std::_MakeUniq<locator::tokens_iterator_impl>::__single_object std::make_unique<locator::tokens_iterator_impl, locator::tokens_iterator_impl&>(locator::tokens_iterator_impl&) at /usr/include/fmt/format.h:1158
    |  (inlined by) locator::token_metadata::tokens_iterator::tokens_iterator(locator::token_metadata::tokens_iterator const&) at ./locator/token_metadata.cc:1602
    | locator::simple_strategy::calculate_natural_endpoints(dht::token const&, locator::token_metadata&) const at simple_strategy.cc:?
    |  (inlined by) locator::simple_strategy::calculate_natural_endpoints(dht::token const&, locator::token_metadata&) const at ./locator/simple_strategy.cc:56
    | locator::abstract_replication_strategy::get_ranges(gms::inet_address, locator::token_metadata&) const at /usr/include/fmt/format.h:1158
    | locator::abstract_replication_strategy::get_ranges(gms::inet_address) const at /usr/include/fmt/format.h:1158
    | service::storage_service::get_ranges_for_endpoint(seastar::basic_sstring<char, unsigned int, 15u, true> const&, gms::inet_address const&) const at /usr/include/fmt/format.h:1158
    | service::storage_service::get_local_ranges(seastar::basic_sstring<char, unsigned int, 15u, true> const&) const at /usr/include/fmt/format.h:1158
    |  (inlined by) operator() at ./sstables/compaction_manager.cc:691
    |  (inlined by) _M_invoke at /usr/include/c++/9/bits/std_function.h:286
    | std::function<std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > > (table const&)>::operator()(table const&) const at /usr/include/fmt/format.h:1158
    |  (inlined by) compaction_manager::rewrite_sstables(table*, sstables::compaction_options, std::function<std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > > (table const&)>) at ./sstables/compaction_manager.cc:604
    | compaction_manager::perform_cleanup(table*) at /usr/include/fmt/format.h:1158

To fix, we furturize the function to get sstables. If get_local_ranges()
is called inside a thread, get_local_ranges will yield automatically.
    
Fixes #6662

### CODE REVIEW

File: sstables/compaction_manager.cc [hunk 1]
```diff
@@ -731,15 +731,17 @@ future<> compaction_manager::perform_cleanup(column_family* cf) {
...
         auto sstables = std::vector<sstables::shared_sstable>{};
-        const auto candidates = table.candidates_for_compaction();
+        const auto candidates = cf->candidates_for_compaction();
         std::copy_if(candidates.begin(), candidates.end(), std::back_inserter(sstables), [&owned_ranges, schema] (const sstables::shared_sstable& sst) {
+            seastar::thread::maybe_yield();
             return owned_ranges.empty() || needs_cleanup(sst, owned_ranges, schema);
         });
-        return sstables;
+        rewrite_sstables(cf, sstables::compaction_options::make_cleanup(),
+                [sstables = std::move(sstables)] (const table&) { return sstables; }).get();
```
Comment (raphaelsc) [inline sstables/compaction_manager.cc:744]: While reviewing ur work, I realized we need to be careful about lambda storing a copy of sstables, because we want rewrite_sstables() to release space of a sstable already rewritten. But it turns out that the callback passed to rewrite_sstables() will be destroyed by the time it returns a future.

File: locator/abstract_replication_strategy.cc [hunk 2]
```diff
@@ -178,6 +178,9 @@ abstract_replication_strategy::get_ranges(inet_address ep, token_metadata& tm) c
     for (auto tok : tm.sorted_tokens()) {
         for (inet_address a : calculate_natural_endpoints(tok, tm)) {
             if (a == ep) {
+                if (seastar::thread::running_in_thread()) {
+                    seastar::thread::maybe_yield();
+                }
                 insert_token_range_to_sorted_container_while_unwrapping(prev_tok, tok, ret);
```
Comment (avikivity) [inline locator/abstract_replication_strategy.cc:184]: This is dangerous. A function can happen to be in a thread by accident.

```c++
    return std::async([] {
         // in a thread now
         func_that_returns_a_future().then([] {
              // not in a thread, bit running_in_thread() returns true
              int x = 3; // starts life in a thread stack
              seastar::thread::maybe_yield();
              // thread stack may be gone by now, or we may execute in a different thread
              print(x); // maybe not 3
         }).forward_to(some_promise);
    });

Comment (avikivity) [reply locator/abstract_replication_strategy.cc:184]: It is better to return a future. And even better to fix the function not to take 16 seconds. What is it computing, all the digits of pi?

File: sstables/compaction_manager.cc [hunk 3]
```diff
@@ -731,15 +731,17 @@ future<> compaction_manager::perform_cleanup(column_family* cf) {
...
-        auto schema = table.schema();
+    return seastar::async([this, cf] {
+        auto schema = cf->schema();
         auto owned_ranges = service::get_local_storage_service().get_local_ranges(schema->ks_name());
         auto sstables = std::vector<sstables::shared_sstable>{};
-        const auto candidates = table.candidates_for_compaction();
+        const auto candidates = cf->candidates_for_compaction();
         std::copy_if(candidates.begin(), candidates.end(), std::back_inserter(sstables), [&owned_ranges, schema] (const sstables::shared_sstable& sst) {
+            seastar::thread::maybe_yield();
             return owned_ranges.empty() || needs_cleanup(sst, owned_ranges, schema);
```
Comment (avikivity) [inline sstables/compaction_manager.cc:741]: If owned_ranges is sorted (and if not, we can sort it), then needs_cleanup can be optimized to take advantage of it.

**Comment by bhalevy** [comment]
@asias please see Avi's comments, and also please change target branch to `next`

File: locator/abstract_replication_strategy.cc (hunk 2 above)
Comment (asias) [reply locator/abstract_replication_strategy.cc:184]: Good example. Can we somehow tell if the code is really under a thread?

Comment (asias) [reply locator/abstract_replication_strategy.cc:184]: abstract_replication_strategy::get_ranges() loops all the vnode tokens, calculates natural_endpoints for each of the tokens to check if the node owns the range.

File: sstables/compaction_manager.cc (hunk 3 above)
Comment (asias) [reply sstables/compaction_manager.cc:741]: Yes, owned_ranges is sorted, so we can use that to optimize. However, compaction_manager::perform_cleanup is called on the slow path. It is more important to avoid stall.

**Comment by asias** [comment]
> @asias please see Avi's comments, and also please change target branch to `next`

I know we merge PR into next branch. But aren't developers supposed to develop against master branch not next branch? Also when one sends a url for a patch set, the branch should be based on master and not next. Why it is important to change the target branch to `next`?

File: locator/abstract_replication_strategy.cc (hunk 2 above)
Comment (avikivity) [reply locator/abstract_replication_strategy.cc:184]: > Good example. Can we somehow tell if the code is really under a thread?

Only by code inspection. At runtime Scylla kills this information.

Comment (avikivity) [reply locator/abstract_replication_strategy.cc:184]: > abstract_replication_strategy::get_ranges() loops all the vnode tokens, calculates natural_endpoints for each of the tokens to check if the node owns the range.

Why does it take 16 seconds?

File: sstables/compaction_manager.cc (hunk 3 above)
Comment (avikivity) [reply sstables/compaction_manager.cc:741]: If it takes 16 seconds on some test it might take 16 minutes on a large cluster (if there is quadratic behavior). When something is this bad, we need to understand it, not just add yields.

File: locator/abstract_replication_strategy.cc (hunk 2 above)
Comment (asias) [reply locator/abstract_replication_strategy.cc:184]: Note, the 16 seconds is not contributed only by the get_ranges. Also the copy_if: 

```
739         std::copy_if(candidates.begin(), candidates.end(), std::back_inserter(sstables), [&owned_ranges, schema] (const sstables::shared_sstable& sst) {
740             return owned_ranges.empty() || needs_cleanup(sst, owned_ranges, schema);
741         });
```

File: sstables/compaction_manager.cc (hunk 3 above)
Comment (asias) [reply sstables/compaction_manager.cc:741]: I think we know why it is slow: O(number_of_sstables * number_tokens_in_the_cluster)

File: locator/abstract_replication_strategy.cc (hunk 2 above)
Comment (avikivity) [reply locator/abstract_replication_strategy.cc:184]: The copy_if itself is O(n) with a moderate N. I expect the problem is in conjunction with needs_cleanup().

File: sstables/compaction_manager.cc (hunk 3 above)
Comment (avikivity) [reply sstables/compaction_manager.cc:741]: What are the numbers? Even if you have 100 sstables and 2000 tokens (8-node cluster), that's just 200,000 operations. Even if each operation takes 1usec (a huge amount) it should take 200ms.

So I think we don't know everything.

File: locator/abstract_replication_strategy.cc (hunk 2 above)
Comment (asias) [reply locator/abstract_replication_strategy.cc:184]: Yes,  it iterates the whole owned ranges. 

```
711 static bool needs_cleanup(const sstables::shared_sstable& sst,
712                    const dht::token_range_vector& owned_ranges,
713                    schema_ptr s) {
714     auto first = sst->get_first_partition_key();
715     auto last = sst->get_last_partition_key();
716     auto first_token = dht::get_token(*s, first);
717     auto last_token = dht::get_token(*s, last);
718     dht::token_range sst_token_range = dht::token_range::make(first_token, last_token);
719 
720     // return true iff sst partition range isn't fully contained in any of the owned ranges.
721     for (auto& r : owned_ranges) {
722         if (r.contains(sst_token_range, dht::token_comparator())) {
723             return false;
724         }
725     }   
726     return true;
727 }
```

File: sstables/compaction_manager.cc (hunk 3 above)
Comment (asias) [reply sstables/compaction_manager.cc:741]: I measured 2 nodes each with 2560 tokens on my dev machine.

```
diff --git a/sstables/compaction_manager.cc b/sstables/compaction_manager.cc
index b26a97fa7..20133c194 100644
--- a/sstables/compaction_manager.cc
+++ b/sstables/compaction_manager.cc
@@ -733,13 +733,20 @@ future<> compaction_manager::perform_cleanup(column_family* cf) {
     }
     return seastar::async([this, cf] {
         auto schema = cf->schema();
+        auto t1 = std::chrono::high_resolution_clock::now();
         auto owned_ranges = service::get_local_storage_service().get_local_ranges(schema->ks_name());
+        auto t2 = std::chrono::high_resolution_clock::now();
         auto sstables = std::vector<sstables::shared_sstable>{};
         const auto candidates = cf->candidates_for_compaction();
+        auto sz = candidates.size();
         std::copy_if(candidates.begin(), candidates.end(), std::back_inserter(sstables), [&owned_ranges, schema] (const sstables::shared_sstable& sst) {
             seastar::thread::maybe_yield();
             return owned_ranges.empty() || needs_cleanup(sst, owned_ranges, schema);
         });
+        auto t3 = std::chrono::high_resolution_clock::now();
+        auto d1 = std::chrono::duration_cast<std::chrono::nanoseconds>(t2 - t1).count();
+        auto d2 = std::chrono::duration_cast<std::chrono::nanoseconds>(t3 - t2).count();
+        cmlog.info("compaction_manager::perform_cleanup d1(get_ranges)={}, d2(needs_cleanup)={}, candidates={}", d1, d2, sz);
         rewrite_sstables(cf, sstables::compaction_options::make_cleanup(),
                 [sstables = std::move(sstables)] (const table&) { return sstables; }).get();
     });
```

INFO  2020-06-23 14:57:51,408 [shard 0] compaction_manager - compaction_manager::perform_cleanup ks=system_distributed, table=view_build_status, d1(get_ranges)=1204858379ns, d2(needs_cleanup)=2374ns, candidates=0


1.2s for get_ranges



INFO  2020-06-23 15:17:33,874 [shard 0] compaction_manager - compaction_manager::perform_cleanup ks=system_distributed, table=cdc_streams, d1(get_ranges)=5348718ns, d2(needs_cleanup)=5675718ns, candidates=1

5ms for get_ranges

5ms for 1 sstable -> 1000 sstables = 5s

Comment (avikivity) [reply sstables/compaction_manager.cc:741]: I guess you mean 5ms for needs_cleanup().

get_local_ranges() looks very slow. It is quadratic in terms of the number of tokens, and calculate_natural_endpoints() is itself slow. It is all pointless calculations, since the tokens change very rarely.

needs_cleanup() can be sped up significantly if owned_ranges was sorted.

**Comment by avikivity** [comment]
> > @asias please see Avi's comments, and also please change target branch to `next`
> 
> I know we merge PR into next branch. But aren't developers supposed to develop against master branch not next branch? Also when one sends a url for a patch set, the branch should be based on master and not next. Why it is important to change the target branch to `next`?

It's not important to me, I merge via the command line.

Yes, you should develop against master, not next.

File: sstables/compaction_manager.cc (hunk 3 above)
Comment (asias) [reply sstables/compaction_manager.cc:741]: Yes 5ms for 1 sstable to run needs_cleanup.

**Comment by bhalevy** [comment]
On Mon, Jun 22, 2020, 11:03 Asias He <notifications@github.com> wrote:

> @asias <https://github.com/asias> please see Avi's comments, and also
> please change target branch to next
>
> I know we merge PR into next branch. But aren't developers supposed to
> develop against master branch not next branch? Also when one sends a url
> for a patch set, the branch should be based on master and not next. Why it
> is important to change the target branch to next?
>
@asias we develop against master but merge to next.  The reason the
conventional target branch for PRs is `next` is for merging using the
github UI.

It can also detect merge conflicts and warn about them and maybe in the
future it could run some preliminary integration tests before merging.

**Comment by asias** [comment]
Changes in version  29b853182f1cfa64001a7f66c5e237745961b520:
- Add get_ranges_in_thread which can yield
- Drop dependency to global storage_service object

File: sstables/compaction_manager.cc (hunk 3 above)
Comment (asias) [reply sstables/compaction_manager.cc:742]: Yes 5ms for 1 sstable to run needs_cleanup.

> On Mon, Jun 22, 2020, 11:03 Asias He ***@***.***> wrote: @asias <https://github.com/asias> please see Avi's comments, and also please change target branch to next I know we merge PR into next branch. But aren't developers supposed to develop against master branch not next branch? Also when one sends a url for a patch set, the branch should be based on master and not next. Why it is important to change the target branch to next?
> @asias we develop against master but merge to next. The reason the conventional target branch for PRs is `next` is for merging using the github UI. It can also detect merge conflicts and warn about them and maybe in the future it could run some preliminary integration tests before merging.

Can we change the default to next for the sake of UI merge?

Comment (avikivity) [reply sstables/compaction_manager.cc:742]: We can't change the default, because then clones/forks will default to next, which is unstable.

Comment (avikivity) [reply sstables/compaction_manager.cc:742]: Note that cf352e7c1465e2ff16bb904eb0a74277b01312bc makes needs_cleanup() much faster.

File: sstables/compaction_manager.cc [hunk 4]
```diff
@@ -726,20 +726,23 @@ static bool needs_cleanup(const sstables::shared_sstable& sst,
...
         });
-        return sstables;
+        rewrite_sstables(cf, sstables::compaction_options::make_cleanup(),
+                [sstables = std::move(sstables)] (const table&) { return sstables; }).get();
```
Comment (avikivity) [inline sstables/compaction_manager.cc:745]: Please move rewrite_sstables() out of the thread, and keep the thread only for the calculation. There's no need to keep the thread active after that, it just wastes memory.

Comment (asias) [reply sstables/compaction_manager.cc:745]: OK. Done.

File: sstables/compaction_manager.cc (hunk 3 above)
Comment (asias) [reply sstables/compaction_manager.cc:742]: Yes. I chatted this with Raphael.

Comment (asias) [reply sstables/compaction_manager.cc:742]: > We can't change the default, because then clones/forks will default to next, which is unstable.

I meant changing the default branch for PR only. Sounds like github does not support it.

**Comment by asias** [comment]
Changes in d7a47b1f714ff5146416cb3de98488e9c6da2c53: 
- Move rewrite_sstables out of the thread. 

I will resolve the conflict once  cf352e7 is in master.

**Comment by asias** [comment]
Changes in 07e253542d6b2611ee4b1c8df2653b0af4ef085a:
- Rebased to master and resolve conflicts with cf352e7.

**Comment by avikivity** [comment]
Removing backport candidate label from pull request. Labels are added automatically to issues.
