### PR TITLE
cql3: min/max() on collections returns human-readable result

### LINKED ISSUE #5139: max and min on a inet column returns unexpected result
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): ReleaseVersion: 3.0.8
Cluster size: 
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

c* returns the value, as it is represented as a string:
```
cqlsh> CREATE KEYSPACE group_functions WITH replication={'class':'SimpleStrategy', 'replication_factor':1} ;
cqlsh> USE group_functions ;
cqlsh:group_functions> create TABLE all_types (id int PRIMARY KEY, my_inet inet);
cqlsh:group_functions> SELECT * from all_types ;

 id | my_inet
----+---------

(0 rows)
cqlsh:group_functions> INSERT INTO all_types (id, my_inet) VALUES (0, '1.1.1.1');
cqlsh:group_functions> INSERT INTO all_types (id, my_inet) VALUES (1, '1.1.1.2');
cqlsh:group_functions> INSERT INTO all_types (id, my_inet) VALUES (2, '1.1.1.3');
cqlsh:group_functions> INSERT INTO all_types (id, my_inet) VALUES (3, '1.1.1.4');
cqlsh:group_functions> INSERT INTO all_types (id, my_inet) VALUES (4, '1.1.1.5');
cqlsh:group_functions> INSERT INTO all_types (id, my_inet) VALUES (6, '1.1.1.6');
cqlsh:group_functions> SELECT cou
                       <blobLiteral>          <colname>              <float>                <identifier>           <pgStringLiteral>      <quotedStringLiteral>  <uuid>                 <wholenumber>          COUNT                  
cqlsh:group_functions> SELECT count(my_inet) from all_types ;

 system.count(my_inet)
-----------------------
                     6

(1 rows)

Warnings :
Aggregation query used without partition key

cqlsh:group_functions> SELECT min(my_inet) from all_types ;

 system.min(my_inet)
---------------------
             1.1.1.1

(1 rows)

Warnings :
Aggregation query used without partition key

cqlsh:group_functions> SELECT max(my_inet) from all_types ;

 system.max(my_inet)
---------------------
             1.1.1.6

(1 rows)

Warnings :
Aggregation query used without partition key

cqlsh:group_functions>
```

but scylla does something else:
```
cqlsh:group_functions> create TABLE all_types (id int PRIMARY KEY, my_inet inet);
cqlsh:group_functions> SELECT * from all_types ;

 id | my_inet
----+---------

(0 rows)
cqlsh:group_functions> INSERT INTO all_types (id, my_inet) VALUES (0, '1.1.1.1');
cqlsh:group_functions> INSERT INTO all_types (id, my_inet) VALUES (1, '1.1.1.2');
cqlsh:group_functions> INSERT INTO all_types (id, my_inet) VALUES (2, '1.1.1.3');
cqlsh:group_functions> INSERT INTO all_types (id, my_inet) VALUES (3, '1.1.1.4');
cqlsh:group_functions> INSERT INTO all_types (id, my_inet) VALUES (4, '1.1.1.5');
cqlsh:group_functions> INSERT INTO all_types (id, my_inet) VALUES (6, '1.1.1.6');
cqlsh:group_functions> SELECT count(my_inet) from all_types ;

 system.count(my_inet)
-----------------------
                     6

(1 rows)
cqlsh:group_functions> SELECT min(my_inet) from all_types ;

 system.min(my_inet)
---------------------
          0x01010101

(1 rows)
cqlsh:group_functions> SELECT max(my_inet) from all_types ;

 system.max(my_inet)
---------------------
          0x01010106

(1 rows)
```

### PR DESCRIPTION
**Pull request by jul-stas**
Previously, scylla used `min/max(blob)->blob` overload for collections, tuples and UDTs; effectively making the results being printed as blobs. This PR adds "dynamically"-typed `min()`/`max()` functions for compound types.

These types can be complicated, like `map<int,set<tuple<...`, and created in runtime, so functions for them are created on-demand, similarly to `tojson()`. The comparison remains unchanged - underneath this is still byte-by-byte weak lex ordering.

Fixes #5139

### CODE REVIEW

File: tests/cql_query_test.cc [hunk 1]
```diff
@@ -1632,6 +1637,35 @@ SEASTAR_TEST_CASE(test_aggregate_functions) {
...
+        ).test_min_max_count();
+
+        auto tuple_type_int_text = tuple_type_impl::get_instance({int32_type, utf8_type});
+        aggregate_function_test(e, tuple_type_int_text,
+            make_tuple_value(tuple_type_int_text, {1, "aaa"}),
+            make_tuple_value(tuple_type_int_text, {1, "bbb"}),
+            make_tuple_value(tuple_type_int_text, {2, "aaa"})
+        ).test_min_max_count();
+
+        auto map_kv_pair = tuple_type_impl::get_instance({int32_type, utf8_type});
```
Comment (psarna) [inline tests/cql_query_test.cc]: Is it a leftover from previous iterations? This type doesn't seem very useful, you could just use int32_type and utf8_type directly in `map_type_impl::get_instance`. I'm fine with this code as is, but if you happen to fix the order of `inline` keywords above, you could also tackle this.

File: cql3/functions/aggregate_fcts.hh [hunk 2]
```diff
@@ -313,6 +342,12 @@ make_max_function() {
     return make_shared<max_function_for<Type>>();
 }
 
+/// The same as `make_max_function()' but with type provided in runtime.
+shared_ptr<aggregate_function> inline
```
[the remark this answers is not in the document]
Comment (jul-stas) [reply cql3/functions/aggregate_fcts.hh]: 2x done

File: tests/cql_query_test.cc (hunk 1 above)
Comment (jul-stas) [reply tests/cql_query_test.cc]: done!
