### PR TITLE
cql3: implement WRITETIME() and TTL() of individual elements of map, set, and UDT

### LINKED ISSUE #13624: Add support for UDT subfields in LWT expression
Cassandra added in 2016 (Cassandra 3.6) support for using individual subfields of a UDT in expressions, and in particular LWT expressions. See https://issues.apache.org/jira/browse/CASSANDRA-7423 and commit https://github.com/apache/cassandra/commit/677230df694752c7ecf6d5459eee60ad7cf45ecf

For example, one can do `IF v.a = 0` when `v` is a UDT and `a` is one of its fields.

This doesn't work in Scylla. Our Cql.g supports in `columnCondition` only a `subscriptExpr` (a subscript `col[term]`) but not a UDT subfield `v.a`.

I consider this issue a bug and not an "enhancement", because I think users will consider it a bug that an expression syntax is supported in some situations but not in others. What is most surprising is that our Cql.g **does** include many of the cases of subfields added in  https://github.com/apache/cassandra/commit/677230df694752c7ecf6d5459eee60ad7cf45ecf - for example `unaliasedSelector` (SELECT expression) and `columnOperationDifferentiator`  (SET), but for some reason only the LWT support for it is missing. Maybe we forgot to do it when adding LWT support to our parser, or this feature was somehow lost (a regression?) during the recent CQL parsing cleanups?

Reproduced by the translated Cassandra unit test `cassandra_tests/validation/operations/insert_update_if_condition_collections_test.py`::`testUDTField`.

### LINKED ISSUE #15427: Provide a way to retrieve the writetime() and ttl() of a individual elements of a collection
we set different TTL for elements of a collection. After some time, we don't know when exactly the element will expire. We want to know about the TTL to have a insight about our data

### PR DESCRIPTION
**Pull request by nyh**
In commit 727f68e0f5b91e07d31b7216c294cc08306b6b7a we added the ability to SELECT:

* Individual elements of a map: `SELECT map_col[key]`.
* Individual elements of a set: `SELECT set_col[key]` returns key if the key exists in the set, or null if it doesn't, allowing to check if the element exists in the set.
* Individual pieces of a UDT: `SELECT udt_col.field`.

But at the time, we didn't provide any way to retrieve the **meta-data** for this value, namely its timestamp and TTL. We did not support `SELECT TIMESTAMP(collection[key])`, or `SELECT TIMESTAMP(udt.field)`. 

Users requested to support such SELECTs in the past (see issue #15427), and Cassandra 5.0 added support for this feature - for both maps and sets and udts - so we also need this feature for compatibility. This feature was also requested recently by vector-search developers, who wanted to read Alternator columns - stored as map elements, not individual columns - with their WRITETIME information.

The first four patches in this series adds the feature (in four smaller patches instead one big one), the fifth and sixth patches add tests (cqlpy and boost tests, respectively). The seventh patch adds documentation.

All the new tests pass on Cassandra 5, failed on Scylla before the present fix, and pass with it.

The fix was surprisingly difficult. Our existing implementation (from 727f68e0f5b91e07d31b7216c294cc08306b6b7a building on earlier machinery) doesn't just "read" `map_col[key]` and allow us to return just its timestamp. Rather, the implementation reads the entire map, serializes it in some temporary format that does **not** include the timestamps and ttls, and then takes the subscript key, at which point we no longer have the timestamp or ttl of the element. So the fix had to cross all these layers of the implementation.

While adding support for UDT fields in a pre-existing grammar nonterminal "subscriptExpr", we unintentionally added support for UDT fields also in LWT expressions (which used this nonterminal). LWT missing support for UDT fields was a long-time known compatibility issue (#13624) so we unintentionally fixed it :-) Actually, to completely fix it we needed another small change in the expression implementation, so the eighth patch in this series does this.

Fixes #15427
Fixes #13624

### CODE REVIEW

File: cql3/expr/expression.cc [hunk 1]
```diff
@@ -1206,6 +1206,43 @@ cql3::raw_value do_evaluate(const field_selection& field_select, const evaluatio
 static
 cql3::raw_value
 do_evaluate(const column_mutation_attribute& cma, const evaluation_inputs& inputs) {
+    // Handle WRITETIME(m[key]) / TTL(m[key]) on a map element
```
Comment (avikivity) [inline cql3/expr/expression.cc:1247]: I'd like to see expr_test.cc updated for this.

File: cql3/expr/expression.cc [hunk 2]
```diff
@@ -1206,6 +1206,43 @@ cql3::raw_value do_evaluate(const field_selection& field_select, const evaluatio
...
+    if (auto sub = expr::as_if<subscript>(&cma.column)) {
+        auto inner_col = expr::as_if<column_value>(&sub->val);
+        if (!inner_col) {
+            on_internal_error(expr_logger, fmt::format("evaluating column_mutation_attribute subscript: inner expression is not a column: {}", sub->val));
+        }
+        int32_t index = inputs.selection->index_of(*inner_col->col);
+        if (inputs.collection_element_metadata.empty() || index < 0 || size_t(index) >= inputs.collection_element_metadata.size()) {
+            return cql3::raw_value::make_null();
```
Comment (avikivity) [inline cql3/expr/expression.cc]: Is not an internal error in order here?

File: cql3/expr/prepare_expr.cc [hunk 3]
```diff
@@ -1259,6 +1259,23 @@ prepare_column_mutation_attribute(
                     receiver->type->name(), receiver->name->text()));
     }
     auto column = prepare_expression(cma.column, db, keyspace, schema_opt, nullptr);
+    // Handle WRITETIME(m[key]) / TTL(m[key]) - a subscript into a non-frozen map column
```
Comment (avikivity) [inline cql3/expr/prepare_expr.cc]: Could we not support it on a set as well? Need not do it now.

File: cql3/selection/selection.cc [hunk 4]
```diff
@@ -553,6 +566,9 @@ result_set_builder::result_set_builder(const selection& s, gc_clock::time_point
     if (s._collect_TTLs) {
         _ttls.resize(s._columns.size(), 0);
     }
+    if (s._collect_collection_timestamps) {
+        _collection_element_metadata.resize(s._columns.size());
+    }
```
Comment (avikivity) [inline cql3/selection/selection.cc:571]: Need to check here if we asked for collection timestamps and did not receive them, indicating we're in a mixed cluster.

File: cql3/selection/selection.cc [hunk 5]
```diff
@@ -585,8 +604,40 @@ void result_set_builder::add(const column_definition& def, const query::result_a
 }
 
 void result_set_builder::add_collection(const column_definition& def, bytes_view c) {
+    size_t col_idx = current.size();
+    if (!_collection_element_metadata.empty() && c.size() >= sizeof(int32_t)) {
+        // Peek at the first 4 bytes to see if we have the extended format (magic -1).
```
Comment (avikivity) [inline cql3/selection/selection.cc]: Why magic and not new fields?

File: query/query-request.hh [hunk 6]
```diff
@@ -219,7 +223,8 @@ public:
         option::bypass_cache,
         option::always_return_static_content,
         option::range_scan_data_variant,
-        option::allow_mutation_read_page_without_live_row>>;
+        option::allow_mutation_read_page_without_live_row,
+        option::send_collection_timestamps>>;
```
[the remark this answers is not in the document]
Comment (avikivity) [reply query/query-request.hh:228]: Correct analysis by @copilot (deeper than mine).

File: types/types.cc [hunk 7]
```diff
@@ -3718,6 +3718,42 @@ bytes_ostream serialize_for_cql(const abstract_type& type, collection_mutation_v
...
+                write_simple<int64_t>(out, e.second.timestamp());
+                int64_t expiry_raw = -1;
+                if (e.second.is_live_and_has_ttl()) {
+                    expiry_raw = e.second.expiry().time_since_epoch().count();
+                }
+                write_simple<int64_t>(out, expiry_raw);
+                ++elements;
+            }
+        }
+        write_collection_size(count_slot, elements);
```
Comment (avikivity) [inline types/types.cc:3747]: Alternative: serialize as a new, fake column, containing a map\<key_type, tuple\<int, long>>.

This avoids inventing yet another format on the wire.

File: cql3/expr/expression.cc (hunk 1 above)
Comment (nyh) [reply cql3/expr/expression.cc:1247]: Ok, will do. Note that I did add CQL-level tests (test/cqlpy) so expr_test.cc wouldn't add much, I think, but I guess it can't hurt.

Comment (avikivity) [reply cql3/expr/expression.cc:1247]: It's better to catch problems early.

Comment (nyh) [reply cql3/expr/expression.cc:1247]: I am not a fan of these tests - they make refactoring risky (the tests rely on non-interesting low-level details, and need to be rewritten if the implementation), and they have a lot of other downsides. If they can catch problems that you can't catch in CQL, fine, but in this isn't the case. Anyway, I (or my AI...) wrote new C++ tests, they will be in the next version I push.

File: cql3/expr/expression.cc (hunk 2 above)
Comment (nyh) [reply cql3/expr/expression.cc]: Indeed. Will fix.

File: cql3/expr/expression.cc [hunk 8]
```diff
@@ -1206,6 +1206,43 @@ cql3::raw_value do_evaluate(const field_selection& field_select, const evaluatio
...
+        }
+        case column_mutation_attribute::attribute_kind::ttl: {
+            const auto it = evaluated_key.view().with_linearized([&] (bytes_view key_bv) {
+                return meta.ttls.find(bytes(key_bv));
+            });
+            if (it == meta.ttls.end() || it->second < 0) {
+                return cql3::raw_value::make_null();
+            }
+            return raw_value::make_value(data_value(it->second).serialize());
+        }
```
[the remark this answers is not in the document]
Comment (nyh) [reply cql3/expr/expression.cc]: I'm not sure I understand what this even means, but you're right - the single-TTL case has ttl_v <= 0, not < 0, so it should be the same here.

File: cql3/expr/prepare_expr.cc (hunk 3 above)
Comment (nyh) [reply cql3/expr/prepare_expr.cc]: Good idea, I'll seriously consider it and either implement it or create a new issue. I thought we do not allow to select `s[key]` (although we could have returned a boolean for this!), but I forgot that we can **still** allow select `writetime(s[key])`, since our implementation of `writetime(s[key])` doesn't actually rely on the implementation of `s[key]`.

File: cql3/selection/selection.cc (hunk 4 above)
Comment (nyh) [reply cql3/selection/selection.cc:571]: I was worried I missed the case of mixed cluster, and forgot to say I was worried about it. Now I know what I missed. I'll take a look, thanks.

File: cql3/expr/expression.cc (hunk 1 above)
Comment (avikivity) [reply cql3/expr/expression.cc:1247]: The expression layer is a module boundary. It's not meant to be broken often.

File: cql3/expr/prepare_expr.cc (hunk 3 above)
Comment (avikivity) [reply cql3/expr/prepare_expr.cc]: The selection would be `key IN s`. No need to do it now.

File: cql3/selection/selection.cc (hunk 4 above)
Comment (avikivity) [reply cql3/selection/selection.cc:571]: It's possible that enum_set will cause it to be rejected like @copilot says.

File: cql3/expr/prepare_expr.cc (hunk 3 above)
Comment (nyh) [reply cql3/expr/prepare_expr.cc]: Wouldn't it be weird that the syntax for checking if key is in s is `key IN s`, but to get the write time you need to use a different syntax, `writetime(s[key])`? I'll have to check how Cassandra or other SQL-like systems do it, if they do it. 
And yes, I'll probably not do it now. What I really needed the map element for is Alternator + Vector Store (they wanted to know the timestamp of an Alternator attribute, which is stored in a map). Sad that I no longer have a site that I actually like to keep track of issues for the future.

Comment (avikivity) [reply cql3/expr/prepare_expr.cc]: `key IN s` is natural and (relatively) more common. Also works for maps.

`writetime(s[key])` is very rare, so it's not a problem if the syntax is somewhat forced. Happy to see a better suggestion.

Comment (avikivity) [reply cql3/expr/prepare_expr.cc]: Another option is comprehensions: `SELECT (SELECT writetime(key) FROM s WHERE key = :var) FROM tab`, but it returns a set, not a scalar.

Comment (avikivity) [reply cql3/expr/prepare_expr.cc]: Actually, `writetime(key in s)` works and is consistent.

File: query/query-request.hh (hunk 6 above)
[the remark this answers is not in the document]
Comment (nyh) [reply query/query-request.hh:228]: Failing queries when the cluster doesn't support them is actually a good thing, but perhaps a cluster feature is even nicer because it will allow us to fail with a nicer error message, and perhaps more importantly - fail consistently, not depending on which random replica gets contacted.

[the remark this answers is not in the document]
Comment (avikivity) [reply query/query-request.hh:228]: It's not worth the effort IMO. No one will try this query before the cluster is fully upgraded, people will wait. We just need to make sure it doesn't end in a disaster if someone does try it.

File: cql3/selection/selection.cc (hunk 4 above)
Comment (nyh) [reply cql3/selection/selection.cc:571]: If I understand correctly, the fix for a mixed cluster is very simple: we'll have a new cluster feature WRITETIME_TTL_MAP_ELEMENT that says the new writetime(map[key]) feature is supported, and in prepare_column_mutation_attribute() we just check if the cluster feature is not on, we reject the request. When the request is finally not rejected, it means all nodes will understand the new serialization.

Comment (avikivity) [reply cql3/selection/selection.cc:571]: You can just check if it happens to fail already, which is likely.

No need for subtlety here. As long as we don't crash, no need for a cluster feature.

File: cql3/expr/prepare_expr.cc (hunk 3 above)
Comment (nyh) [reply cql3/expr/prepare_expr.cc]: I checked, and we actually implemented in 5ef7afb968baeeec7929ee41dc38ad2629e4f564 the syntax "s[key]", not "key in s", for the element itself (s[key] returns key if the element exists). See test test_set_subscript. So it will be natural to support writetime(s[key]).

Maybe I should implement this right now - it will be strange to support s[key] but not writetime(s[key])...

Comment (nyh) [reply cql3/expr/prepare_expr.cc]: Also, I checked, and Cassandra supports the writetime(s[key]) syntax for a set. So that's the syntax I will implement. I'll do it in this patch, nobody will ever remember to come back to implement it.

Comment (avikivity) [reply cql3/expr/prepare_expr.cc]: Ok

File: query/query-request.hh (hunk 6 above)
[the remark this answers is not in the document]
Comment (nyh) [reply query/query-request.hh:228]: It's not a big effort - adding a cluster feature is one line (!) of code, and checking it is three more lines (an if and an error message). Do you think I should remove the new feature? Is having too many of those pesky cluster features a problem for us?

File: cql3/selection/selection.cc (hunk 4 above)
Comment (nyh) [reply cql3/selection/selection.cc:571]: As I also answered in another comment, it wasn't a big effort - adding a cluster feature is one line of code, and checking it is three more lines (an if and an error message). Do you think I should remove the new cluster feature? Is having too many of those pesky cluster features a problem for us?

File: gms/feature_service.hh [hunk 9]
```diff
@@ -179,6 +179,7 @@ public:
     gms::feature topology_noop_request { *this, "TOPOLOGY_NOOP_REQUEST"sv };
     gms::feature tablets_intermediate_fallback_cleanup { *this, "TABLETS_INTERMEDIATE_FALLBACK_CLEANUP"sv };
     gms::feature batchlog_v2 { *this, "BATCHLOG_V2"sv };
```
[the remark this answers is not in the document]
Comment (nyh) [reply gms/feature_service.hh:180]: Corret. Will fix.

File: mutation/collection_mutation.hh [hunk 10]
```diff
@@ -133,6 +133,12 @@ collection_mutation difference(const abstract_type&, collection_mutation_view, c
 // Serializes the given collection of cells to a sequence of bytes ready to be sent over the CQL protocol.
 bytes_ostream serialize_for_cql(const abstract_type&, collection_mutation_view);
 
+// Like serialize_for_cql, but uses an extended format that embeds per-element timestamps and expiries,
+// for use with WRITETIME(col[key]) and TTL(col[key]) selectors.
```
[the remark this answers is not in the document]
Comment (nyh) [reply mutation/collection_mutation.hh]: Correct.

File: query/query-request.hh [hunk 11]
```diff
@@ -204,6 +204,10 @@ public:
         // is a lot of dead rows. This flag is needed during rolling upgrades to support
         // old coordinators which do not tolerate pages with no live rows.
         allow_mutation_read_page_without_live_row,
+        // When set, collection cells in the query result use an extended format that
+        // embeds per-element timestamps and expiries, to support WRITETIME(col[key])
+        // and TTL(col[key]) selectors.
```
[the remark this answers is not in the document]
Comment (nyh) [reply query/query-request.hh]: Correct.

File: cql3/expr/expression.cc (hunk 1 above)
Comment (nyh) [reply cql3/expr/expression.cc:1247]: I forgot to mention, this is done - the third patch is now tests in test/boost/expr_test.cc (in addition to the second patch which are tests in test/cqlpy and check the SELECT feature end-to-end).

File: types/types.cc (hunk 7 above)
Comment (nyh) [reply types/types.cc:3747]: This magic number implementation is something that Claude came up with. I suggested to it what you suggested, and it didn't like your suggestion. This is what it explained - any retort?

Claude says:

The "fake column of [map<key_type, tuple<int, long>>" proposal:

For this to work, you'd need to add a second cell to the query result row for every collection column that has timestamps requested. The result builder would then consume the extra cell and populate _collection_element_metadata. This requires:

partition_slice to track which columns have metadata companions — but the slice currently only knows about real schema columns (identified by column_id). There's no slot for synthetic columns.
write_cell to write two cells per collection: the regular CQL value, then the metadata cell.
result_set_builder to know, for each collection column being read, to expect and consume a following companion cell — without exposing it to current (the client-visible result row).
That's at least as much special-casing as now, just distributed across more places. You'd be trading one focused hack (a magic prefix in a single function pair) for a larger architectural hack (phantom columns polluting the result pipeline).

The "avoids inventing a new wire format" argument also doesn't hold fully here: a phantom result column that gets silently consumed by the reader IS a new format convention, just at a higher level. The only real advantage is reuse of the existing collection serializer — but that's a thin benefit given the invasiveness of the change.

The magic -1 sentinel is actually a well-chosen idiom: it's not arbitrary — it's specifically impossible in valid CQL collection bytes (a collection always starts with a non-negative element count). The format is self-describing (the CQL bytes are embedded verbatim inside it), the writer and reader are a matched pair, and the format is fully documented in the comments. This is the same technique used in formats like JPEG (0xFFD8), BSON, and many others.

My recommendation: keep the current format, and leave this as-is. The reviewer's concern is understandable as a general principle, but in the specific context here the current design is more contained and requires fewer invasive changes than the proposed alternative. I would not reimplement this.

File: types/types.cc [hunk 12]
```diff
@@ -3709,6 +3709,48 @@ bytes_ostream serialize_for_cql(const abstract_type& type, collection_mutation_v
...
+            }
+        ));
+
+        // Step 2: build extended format:
+        // [int32: -1 magic][uint32: cql byte length][cql bytes]
+        // [int32: entry count][count entries: (int32 keylen)(key bytes)(int64 timestamp)(int64 expiry, -1 if no TTL)]
+        bytes_ostream out;
+        write_simple<int32_t>(out, int32_t(-1));            // magic marker (impossible as valid CQL count)
+        write_simple<uint32_t>(out, uint32_t(cql.size())); // length of regular CQL bytes
+        out.append(cql);                                    // regular CQL bytes
```
[the remark this answers is not in the document]
Comment (nyh) [reply types/types.cc]: I had a long discussion about this with your brother, Claude, and we believe this doesn't cause any problem in practice: the magic-value check (-1) in add_collection() is conditional on _collect_collection_timestamps = true. But when this is true, we also use send_collection_timestamps which causes the write to **add** this -1. This is because we never enter this code if we aren't sure that both sender and receiver have this extra code.
Even if a UDT has a null field whose serialization begins with -1, the writing code will either add an extra -1 in the beginning of it while the reading code removes it, or alternatively - if timestamp isn't requested - the writing code won't add the extra -1 and the reading code won't read it.

In fact, a followup question I asked (Claude wasn't smart enough to think of it?) is why do we even need this "-1" byte **at all**. If the writer always uses the "new format" if a certain flag is on, and the reader knows it always expects the same format back (no mixed cluster), this -1 not needed. And it's not even helping to detect bugs (e.g., on_internal_error if we get mismatch on this -1) because like copilot said, we can get a spurious -1 in the "old format" case as well.

So I asked claude to remove the unneeded "-1" stuff and will send a new version

File: types/types.cc (hunk 7 above)
Comment (avikivity) [reply types/types.cc:3747]: I think it's just lazy

File: cql3/expr/evaluate.hh [hunk 13]
```diff
@@ -16,6 +18,13 @@ class raw_value;
 
 namespace cql3::expr {
 
+// Per-element timestamps and TTLs for a collection cell (populated when a WRITETIME(m[key]) or TTL(m[key]) is in the query).
+// Keys are the raw serialized map keys as stored in the mutation cells.
+struct collection_cell_metadata {
+    std::map<bytes, api::timestamp_type> timestamps;  // key bytes -> per-element timestamp
+    std::map<bytes, int32_t> ttls;                    // key bytes -> remaining TTL in seconds (-1 if no TTL)
+};
```
[the remark this answers is not in the document]
Comment (nyh) [reply cql3/expr/evaluate.hh]: Good spot.

File: cql3/selection/selection.cc [hunk 14]
```diff
@@ -585,8 +604,39 @@ void result_set_builder::add(const column_definition& def, const query::result_a
...
 
 void result_set_builder::add_collection(const column_definition& def, bytes_view c) {
+    size_t col_idx = current.size();
+    if (!_collection_element_metadata.empty()) {
+        // Extended format: [uint32 cql_len][cql bytes][int32 entry_count][entries...]
+        // Serialized by serialize_collection_for_selection(). The flag
+        // _collect_collection_timestamps = true is what determines if this
+        // extended format is used - in both serialization deserialization.
+        // And we only allow this flag when a feature flag tells us that it
+        // is supported by both reader and writer.
```
[the remark this answers is not in the document]
Comment (nyh) [reply cql3/selection/selection.cc]: Oops, I messed that up (not Claude's fault, mine. Fixing.

File: types/types.cc (hunk 7 above)
Comment (nyh) [reply types/types.cc:3747]: In the new version I'll post in a minute I got rid of the "-1" byte - it's just not needed. We simply have one format for the case there are no timestamps/ttls, and one for the case there are, and we know which one we write and read because of the query flag.

File: test/cqlpy/test_select_collection_element.py [hunk 15]
```diff
@@ -7,6 +7,8 @@
 #############################################################################
 
 import pytest
+import time
```
[the remark this answers is not in the document]
Comment (nyh) [reply test/cqlpy/test_select_collection_element.py]: Copilot, who put you up to this nonsense? Did you find some misinformed "instructions for AIs" in our project that told you to do it?

"time" and "pytest" are both system libraries in this context.


I'll switch the order, under protest, to please you.

File: test/cqlpy/test_udt.py [hunk 16]
```diff
@@ -0,0 +1,88 @@
...
+import pytest
+from cassandra.protocol import InvalidRequest
+from .util import new_test_table, unique_key_int, new_type
+
+# The above tests checked we can select WRITETIME(m[key]) et al, an element
+# in a collection. Let's also check that we can select WRITETIME(a.field)
+# where a is a field of a UDT. This test doesn't strictly belong to this file
+# (it has nothing to do with collections), but it uses the same code paths in
+# the server as selecting WRITETIME(m[key]), so it's convenient to test it here
+# with the above tests.
```
[the remark this answers is not in the document]
Comment (nyh) [reply test/cqlpy/test_udt.py]: Good catch - I knew I had to fix this reference but then forgot... :-(

File: cql3/selection/selection.cc [hunk 17]
```diff
@@ -585,8 +604,41 @@ void result_set_builder::add(const column_definition& def, const query::result_a
...
+                int64_t ts = read_simple<int64_t>(peek);
+                int64_t expiry_raw = read_simple<int64_t>(peek);
+                meta.timestamps[key] = ts;
+                if (expiry_raw != -1) {
+                    auto expiry = gc_clock::time_point(gc_clock::duration(expiry_raw));
+                    auto ttl_left = expiry - _now;
+                    int32_t ttl = int32_t(ttl_left.count());
+                    meta.ttls[key] = ttl > 0 ? ttl : -1;
+                } else {
+                    meta.ttls[key] = -1;
```
[the remark this answers is not in the document]
Comment (nyh) [reply cql3/selection/selection.cc]: Good point. I'll do that.

File: types/types.cc (hunk 7 above)
Comment (avikivity) [reply types/types.cc:3747]: Hmm. Somewhat hacky. But given the serialization format is outside IDL, maybe okay.

File: cql3/expr/evaluate.hh [hunk 18]
```diff
@@ -27,6 +37,7 @@ struct evaluation_inputs {
     std::span<const api::timestamp_type> static_and_regular_timestamps;  // indexes match `selection` member
     std::span<const int32_t> static_and_regular_ttls;  // indexes match `selection` member
     std::span<const cql3::raw_value> temporaries; // indexes match temporary::index
+    std::span<const collection_cell_metadata> collection_element_metadata; // indexes match `selection` member
```
Comment (avikivity) [inline cql3/expr/evaluate.hh:31]: Perhaps we should merge static_and_regular_ttls, static_and_regular_timestamps, and collection_element_metadata into a single input with a variant type.

File: cql3/expr/expression.cc [hunk 19]
```diff
@@ -1206,6 +1206,75 @@ cql3::raw_value do_evaluate(const field_selection& field_select, const evaluatio
...
+        case column_mutation_attribute::attribute_kind::ttl: {
+            const auto it = meta.ttls.find(key);
+            if (it == meta.ttls.end() || it->second <= 0) {
+                return cql3::raw_value::make_null();
+            }
+            return raw_value::make_value(data_value(it->second).serialize());
+        }
```
Comment (avikivity) [inline cql3/expr/expression.cc:1235]: Need an on_internal_error() here. enums are allowed to have values outside the declared enumerations.

Comment (avikivity) [reply cql3/expr/expression.cc:1235]: Oh, there is.

File: cql3/selection/selection.cc [hunk 20]
```diff
@@ -585,8 +604,45 @@ void result_set_builder::add(const column_definition& def, const query::result_a
...
+        // Extended format produced by serialize_for_cql_with_timestamps()
+        // [uint32 cql_len][cql bytes][int32 entry_count]
+        // followed by entry_count entries, each:
+	    //   [int32 key_len][key bytes][int64 timestamp][int64 expiry_raw]
+        // where expiry_raw is -1 if the element does not expire, otherwise
+        // it is the serialized gc_clock time used to derive the remaining
+        // TTL. The flag _collect_collection_timestamps = true determines
+        // whether this extended format is used (instead of a plain CQL
+        // collection blob), and it is only enabled when a feature flag
+        // guarantees both reader and writer support it.
```
Comment (avikivity) [inline cql3/selection/selection.cc:618]: It's not good the the format is specified in a comment in some random place.

File: cql3/expr/evaluate.hh (hunk 18 above)
Comment (nyh) [reply cql3/expr/evaluate.hh:31]: Claude gave the following response, I tend to agree. What do you think?

**Recommendation**: The suggestion is reasonable but the benefit is modest (3 fields → 1 in a rarely-touched struct). The tricky part is that it silently changes the semantics of "TTL not collected" from empty span to sentinel -1 in an allocated entry, which must be done carefully and documented. If the codebase is likely to gain more per-column metadata fields later, the consolidation pays off; otherwise it's churn for minimal gain.

If the goal is purely reducing the field count, a simpler intermediate step would be to merge just static_and_regular_timestamps and static_and_regular_ttls into a single std::span<const std::pair<api::timestamp_type, int32_t>> (since they're always populated together in add() and add_empty(), and keep collection_element_metadata separate — that's a smaller, cleaner change.

**My addendum:** since the separation of static_and_regular_timestamps and static_and_regular_ttls was pre-existing, there is no reason to merge them now. And as Claude explained (if you agree with it), there's even less reason to merge the third one with it.

File: cql3/expr/expression.cc (hunk 19 above)
Comment (nyh) [reply cql3/expr/expression.cc:1235]: I probably agree it will be clearer to use "default:". I'll do it.

File: cql3/selection/selection.cc (hunk 20 above)
Comment (nyh) [reply cql3/selection/selection.cc:618]: It's not exactly a random place - the same format is explained once in serialize_for_cql_with_timestamps() (types/types.cc) which writes this format, and here in add_collection() which reads this format.
This is not a user-visible format, so it doesn't have a natural place to document it.
I (and Claude) couldn't think of any relevant document that already exist.

I can create a brand new file in in docs/dev which documents this, and instead of all this text explaining the format in two places, change both of them to refer to the new file. Would you like me to do it?

Personally I'm not sure which is better, because I think it's not that terrible that a format that is only used in two places (one reader and one writer) is described twice, next to the code that uses this format.

**Comment by nyh** [comment]
I'll appreciate someone reviewing this PR and hopefully merging it.

As explained above, it implements two long-standing missing CQL features needed for Cassandra compatibility (one with Cassandra 3.6! the second with Cassandra 5), and more urgently, needed for the vector store to support Alternator vector search that we want to get into the next branch date. Thanks.

File: types/types.cc [hunk 21]
```diff
@@ -3709,6 +3709,47 @@ bytes_ostream serialize_for_cql(const abstract_type& type, collection_mutation_v
     });
 }
 
+bytes_ostream serialize_for_cql_with_timestamps(const abstract_type& type, collection_mutation_view v) {
+    SCYLLA_ASSERT(type.is_multi_cell());
```
Comment (m-szymon) [inline types/types.cc]: After some time I already don't remember precisely where we landed on `SCYLLA_ASSERT`, but apparently now it fires a trigger in my mind when I see it.
To be sure - it is valid (and recommended) use now?

File: test/cqlpy/test_select_collection_element.py [hunk 22]
```diff
@@ -154,3 +160,212 @@ def test_subscript_function_arg(scylla_only, cql, test_keyspace, table1):
...
+    assert list(cql.execute(f"SELECT WRITETIME(s[30]) FROM {table2} WHERE p={p}")) == [(timestamp2,)]
+
+# Test that WRITETIME(col[key]) fails with a clear error when col is not a
+# map/set.
+def test_writetime_subscript_on_wrong_type(cql, test_keyspace):
+    schema = 'p int PRIMARY KEY, v int'
+    with new_test_table(cql, test_keyspace, schema) as table:
+        # Subscript on a non-map/set column should be rejected.
+        # Cassandra says "Invalid element selection: v is of type int is not a
+        # collection". Scylla says "Column v is not a map/set/list, cannot be
```
Comment (m-szymon) [inline test/cqlpy/test_select_collection_element.py:327]: But for list we don't support `WRITETIME(v[3])` anyway, right?

File: test/cqlpy/test_select_collection_element.py [hunk 23]
```diff
@@ -154,3 +160,212 @@ def test_subscript_function_arg(scylla_only, cql, test_keyspace, table1):
...
+        # subscripted"
+        with pytest.raises(InvalidRequest, match=' v '):
+            cql.execute(f"SELECT WRITETIME(v[3]) FROM {table}")
```
Comment (m-szymon) [inline test/cqlpy/test_select_collection_element.py:330]: Shouldn't we repeat it for TTL?

File: test/cqlpy/test_select_collection_element.py [hunk 24]
```diff
@@ -154,3 +160,212 @@ def test_subscript_function_arg(scylla_only, cql, test_keyspace, table1):
...
+    assert list(cql.execute(f"SELECT WRITETIME(m[99]) FROM {table1} WHERE p={p}")) == [(None,)]
+
+# Also, null as a subscript is allowed and returns null timestamp, instead of
+# erroring. This test is marked cassandra_bug because Cassandra returns an
+# ugly "NoHostAvailable ... java.lang.NullPointerException" error in this case
+# (see CASSANDRA-21248).
+def test_writetime_map_element_null_subscript(cql, table1, cassandra_bug):
+    p = unique_key_int()
+    cql.execute(f'INSERT INTO {table1}(p,m) VALUES ({p}, {{1:10}})')
+    assert list(cql.execute(f"SELECT WRITETIME(m[null]) FROM {table1} WHERE p={p}")) == [(None,)]
```
Comment (m-szymon) [inline test/cqlpy/test_select_collection_element.py:213]: 1. No need to do this for TTL?
2. null is allowed in select, but is not a valid key, right? No option of returning non-null value?

File: test/cqlpy/test_type_tuple.py [hunk 25]
```diff
@@ -0,0 +1,41 @@
...
+import time
+import pytest
+from cassandra.protocol import InvalidRequest
+from .util import new_test_table, unique_key_int
+
+
+# Unlike UDTs, tuples are always frozen, meaning that individual fields cannot
+# be updated separately. So there is no point in allowing writetime() or ttl()
+# on individual fields of a tuple - so we do reject them, and we'll test this
+# here. Additionally, we check that writetime() and ttl() on the entire tuple
```
Comment (m-szymon) [inline test/cqlpy/test_type_tuple.py:27]: Comment mentions ttl(), but we test writetime() only.

File: test/cqlpy/test_udt.py [hunk 26]
```diff
@@ -0,0 +1,102 @@
...
+    with new_type(cql, test_keyspace, '(a int, b int)') as typ:
+        schema = f'pk frozen<{typ}> PRIMARY KEY'
+        with new_test_table(cql, test_keyspace, schema) as table:
+            # Scylla's error message is "WRITETIME is not legal on primary key
+            # component pk". Cassandra's is "Cannot use selection function
+            # writetime on PRIMARY KEY part pk".
+            with pytest.raises(InvalidRequest, match='primary key|PRIMARY KEY'):
+                cql.execute(f"SELECT WRITETIME(pk.a) FROM {table}")
+            with pytest.raises(InvalidRequest, match='primary key|PRIMARY KEY'):
+                cql.execute(f"SELECT TTL(pk.a) FROM {table}")
```
Comment (m-szymon) [inline test/cqlpy/test_udt.py:127]: This is the only place in the file where we test TTL?

**Review by m-szymon — APPROVED** [review]
My only remark is that TTL tests are a little inconsistent. I am not sure if we need to repeat every case for both WRITETIME and TTL, but the decision why we do in some cases and why we don't in others is not clear.

The rest is some questions, mostly out of curiosity:
- no lists support - is it much different?
- no way to fetch metadata only, right? We need to get entire collection? Do I understand it well?
- chained subscripts/fields are not allowed at all, right? Besides the nested collections are frozen, but there is no need to test that?
- we don't have MAXWRITETIME function (right?), would its existence change anything?

File: cql3/expr/evaluate.hh [hunk 27]
```diff
@@ -3,6 +3,8 @@
 
 #pragma once
 
+#include <map>
+
```
Comment (avikivity) [inline cql3/expr/evaluate.hh]: > cql3: implement WRITETIME() and TTL() for elements of map, set, UDT


This is a huge patch.

File: cql3/expr/evaluate.hh (hunk 18 above)
Comment (avikivity) [reply cql3/expr/evaluate.hh:31]: >  The tricky part is that it silently changes the semantics of "TTL not collected" from empty span to sentinel -1 in an allocated entry

Seems wrong. We'd have a variant\<no_metadata, single_cell_metadata, multi_cell_metadata> with no -1 trickiness.

Certainly merging ttls and timestamps makes sense and is outside the scope here.

File: cql3/expr/expression.cc [hunk 28]
```diff
@@ -1206,6 +1206,76 @@ cql3::raw_value do_evaluate(const field_selection& field_select, const evaluatio
 static
 cql3::raw_value
 do_evaluate(const column_mutation_attribute& cma, const evaluation_inputs& inputs) {
+    // Handle WRITETIME(x.field) / TTL(x.field) on a UDT field
+    if (auto fs = expr::as_if<field_selection>(&cma.column)) {
```
Comment (avikivity) [inline cql3/expr/expression.cc]: I'm sorely tempted to ask Claude to write a translator-to-bytecode and accompanying bytecode interpreter.

File: cql3/expr/expression.cc (hunk 19 above)
Comment (avikivity) [reply cql3/expr/expression.cc:1235]: No, default: silences the compiler warning if/when we ever add a new enum.

File: cql3/selection/selection.cc (hunk 20 above)
Comment (avikivity) [reply cql3/selection/selection.cc:618]: It's a random place, compared to IDL which centralizes the encoding. We now have yet another custom encoding that bypasses IDL. This isn't good.

File: cql3/selection/selection.hh [hunk 29]
```diff
@@ -12,6 +12,7 @@
 
 #include "utils/assert.hh"
 #include "bytes.hh"
+#include "cql3/expr/evaluate.hh"
```
Comment (avikivity) [inline cql3/selection/selection.hh]: Please use forward declaration instead.

File: cql3/selection/selection.hh [hunk 30]
```diff
@@ -78,7 +80,9 @@ protected:
         std::vector<const column_definition*> columns,
         std::vector<lw_shared_ptr<column_specification>> metadata_,
         bool collect_timestamps,
-        bool collect_TTLs, trivial is_trivial = trivial::no);
+        bool collect_TTLs,
+        bool collect_collection_timestamps = false,
```
Comment (avikivity) [inline cql3/selection/selection.hh]: Avoid default parameters, they're bug magnets. This isn't some super-generic utility.

File: types/types.cc (hunk 21 above)
Comment (avikivity) [reply types/types.cc]: Please use on_internal_error instead.

File: types/types.cc (hunk 7 above)
Comment (avikivity) [reply types/types.cc:3747]: It's also bad the the serialization is here and the deserialization is in selection.cc.

**Comment by hshanghai** [comment]
您好，您的邮件我已经收到，我会尽快和你回复（自动回复）

File: cql3/expr/expression.cc [hunk 31]
```diff
@@ -1031,7 +1031,7 @@ expression search_and_replace(const expression& e,
                     return cast{c.style, recurse(c.arg), c.type};
                 },
                 [&] (const field_selection& fs) -> expression {
-                    return field_selection{recurse(fs.structure), fs.field};
+                    return field_selection{recurse(fs.structure), fs.field, fs.field_idx, fs.type};
```
Comment (avikivity) [inline cql3/expr/expression.cc:1034]: Please split into a separate patch (and pull request) and see if it needs to be backported. This is too central to assume it doesn't have more impact.

File: cql3/expr/evaluate.hh (hunk 27 above)
Comment (nyh) [reply cql3/expr/evaluate.hh]: It's not huge, it's 256 lines, and everything is about exactly one thing. But yes, it's split across 11 files because of the way the code is structured.
I'll try to split it but to be honest, I think this will only make things worse, as you start to get patches like "this patch adds a new cluster feature, it's not used yet but we'll need it in the next patch".

File: cql3/expr/evaluate.hh (hunk 18 above)
Comment (nyh) [reply cql3/expr/evaluate.hh:31]: I already removed the -1 trickiness because it wasn't needed at all. But I didn't merge static_and_regular_timestamps and static_and_regular_ttls because it was pre-existing and I don't see any reason to do this now.

File: cql3/expr/expression.cc (hunk 28 above)
Comment (nyh) [reply cql3/expr/expression.cc]: I don't know what you mean.

File: cql3/expr/expression.cc (hunk 19 above)
Comment (nyh) [reply cql3/expr/expression.cc:1235]: So... what did you ask for?

File: cql3/selection/selection.cc (hunk 20 above)
Comment (nyh) [reply cql3/selection/selection.cc:618]: But this place already had this encoding and decoding, just without the TTL. I am just trying to add a small missing feature, not to completely refactor this existing code.

File: types/types.cc (hunk 21 above)
Comment (nyh) [reply types/types.cc]: Sure, I'm pretty sure Claude wrote this and I missed it, because I wouldn't use SCYLLA_ASSERT myself. I'll fix it.

File: types/types.cc (hunk 7 above)
Comment (nyh) [reply types/types.cc:3747]: Maybe it's bad, this is this how this pre-existing code is structured.

File: test/cqlpy/test_select_collection_element.py (hunk 22 above)
Comment (nyh) [reply test/cqlpy/test_select_collection_element.py:327]: No, we don't because
1. Cassandra doesn't.
2. There is no obvious way how list[3] can be used - how did you know to ask for the third element?
3. 
I guess you're correct that the error message is now out of date and I should fix it.

File: test/cqlpy/test_udt.py (hunk 26 above)
Comment (nyh) [reply test/cqlpy/test_udt.py:127]: We do need to test the TTL as well, because there is **some** different for the code of TTL, but it's important to note that most code paths, involving the syntax, the query logic, etc., is the same, so it is not really helpful to make every single test repeated for TTL and WRITETIME. But I'll reconsider this case (and other cases) to see maybe I should add more tests for the TTL case.

File: cql3/expr/expression.cc (hunk 31 above)
Comment (nyh) [reply cql3/expr/expression.cc:1034]: Ok. I assume by "this" you mean this line, not this entire patch.

File: test/cqlpy/test_select_collection_element.py (hunk 22 above)
Comment (m-szymon) [reply test/cqlpy/test_select_collection_element.py:327]: I think Cassandra does support list, although it is not mentioned explicitly: https://cassandra.apache.org/doc/stable/cassandra/developing/cql/dml.html#writetime-and-ttl-function
I understand that this slicing `WRITETTIME(phones[2..4])` applies to list.

And returning list of values for non-frozen collections is also documented:
> The WRITETIME and TTL functions can be used on multi-cell columns such as non-frozen collections or non-frozen user-defined types. In that case, the functions will return the list of timestamps or TTLs for each selected cell.

File: cql3/expr/expression.cc (hunk 31 above)
Comment (nyh) [reply cql3/expr/expression.cc:1034]: I just spent a couple of hours on this, with Claude leading me into all sorts of wild (and incorrect) goose chases. To make a long story short, my conclusion (and Claude's final conclusion as well) is that this specific buggy code can only ever be called if UDT fields are used inside an expression, and before this pull request we simply do not have any SYNTAX in cql.g to use UDT fields in expressions. Only this pull request adds this syntax, in two places - in `SELECT udt.field` and in LWT (`IF udt.field = 4`).

So I think it is pointless to fix, or even report, this bug separately if it's not exposed by any syntax. Even more, I think it makes a lot of sense to fix this bug together with the pull request that exposes it in a syntax, to avoid any possibility that in the future we'll mistakenly backport one without the other - if we ever backport the syntax expension, this bug fix will come with it.

File: cql3/expr/expression.cc (hunk 28 above)
Comment (avikivity) [reply cql3/expr/expression.cc]: Bfore:
 - evaluate(expression, inputs) -> value

After:
  - compile(expression) -> program
  - evaluate(program, inputs) -> value

File: cql3/expr/expression.cc (hunk 31 above)
Comment (avikivity) [reply cql3/expr/expression.cc:1034]: Ok.

File: cql3/expr/expression.cc (hunk 28 above)
Comment (nyh) [reply cql3/expr/expression.cc]: Oh, so I guess you made this as a general comment for future development, not something specifically related to this PR. I thought it was something about this PR.

File: cql3/expr/evaluate.hh (hunk 27 above)
Comment (nyh) [reply cql3/expr/evaluate.hh]: I got Claude to split this patch into four patches, the largest of which is 112 lines and I think the split is sensible and helpful. I hope you'll like that better. I'll include that in the next version that I'll push (probably will take another hour, I'm also fixing other review comments).

File: test/cqlpy/test_select_collection_element.py (hunk 22 above)
Comment (m-szymon) [reply test/cqlpy/test_select_collection_element.py:327]: I was very curios so I checked. Lists elements cannot be accessed by index. But WRITETIME(list) returns list of all individual elements write times.
The slice syntax `[2..4]` actually applies to maps (e.g 'b'..'d') and sets.

File: cql3/selection/selection.hh (hunk 29 above)
Comment (nyh) [reply cql3/selection/selection.hh]: I can't use forward declaration, I need the definition of the new collection_cell_metadata, but I can easily put this specific thing (collection_cell_metadata) in a separate header file instead of the heavy evaluate.hh. I'll do this.

Comment (avikivity) [reply cql3/selection/selection.hh]: Isn't it only mentioned in a vector template argument list?

File: cql3/selection/selection.hh (hunk 30 above)
Comment (nyh) [reply cql3/selection/selection.hh]: Done.

File: types/types.cc (hunk 21 above)
Comment (nyh) [reply types/types.cc]: Done. Using the new throwing_assert() which is a drop-in replacement for SCYLLA_ASSERT() that uses on_internal_error.

File: cql3/expr/expression.cc (hunk 19 above)
Comment (nyh) [reply cql3/expr/expression.cc:1235]: Oh, I think I understand. You wanted an on_internal_error below the case, not as default. But this is what I had in the code already, no? I'll change it back and remove the "default".

Comment (nyh) [reply cql3/expr/expression.cc:1235]: Also looking at this code again I realized it has mostly the same code twice (one had "default", the other didn't). I'll reduce this duplication.

File: test/cqlpy/test_select_collection_element.py (hunk 24 above)
Comment (nyh) [reply test/cqlpy/test_select_collection_element.py:213]: 1. I'll add the test for TTL as well, it will match all the other duplication I already had for TTL and TIMESTAMP (I'm not sure all of it warrented).
2. No, null is not a valid key in a map, there is no way to set m[null] to any value. The fact that m[null] returns null follows from the philosophy that @avikivity has been correctly advocating: null should be an "infectious" value, if you compute an expression based on null the result should be null. So m[null], null+2, and even 2=null, should all result in null - not in an error, false, or anything else.

File: test/cqlpy/test_select_collection_element.py (hunk 22 above)
Comment (nyh) [reply test/cqlpy/test_select_collection_element.py:327]: Yes, Cassandra does allow WRITETIME(list) and WRITETIME(map) for the whole collection, but they did it very inconsistently and un-usefully - for example, WRITETIME(map) returns a list (!), not a map, so you know the write times - but not of which element :-) I created https://issues.apache.org/jira/browse/CASSANDRA-21240 about this. In the mean time, Scylla deliberately doesn't allow these who-collection WRITETIME and I have a test for it in this patch: test_writetime_ttl_whole_collection_forbidden

I don't remember the situation with slices - did we ever implement this?

File: test/cqlpy/test_select_collection_element.py (hunk 23 above)
Comment (nyh) [reply test/cqlpy/test_select_collection_element.py:330]: I can. I'm not sure it's important (the code is shared) but it can't hurt. I'll do it.

File: test/cqlpy/test_select_collection_element.py (hunk 22 above)
Comment (nyh) [reply test/cqlpy/test_select_collection_element.py:327]: Anyway, I'll add a test that enshrines (and explains) the fact that we don't support list elements here. This test will pass also on Cassandra, showing that we're compatible in the decision not to support it.

If you're curious why list[2] isn't supported, I guess it's because it's a really bad feature that the Cassandra guys didn't want to expand support for. If you are familiar with Cassandra's list, there is no way to actually find list[2] efficiently - you need to read the whole list, count the second element, and return that. Perhaps they didn't want to encourage this any more... Anyway, if we ever do want to support this as a Scylla-only extension, we can.

File: test/cqlpy/test_type_tuple.py (hunk 25 above)
Comment (nyh) [reply test/cqlpy/test_type_tuple.py:27]: I'll add a ttl() test as well.

File: test/cqlpy/test_udt.py (hunk 26 above)
Comment (nyh) [reply test/cqlpy/test_udt.py:127]: I'll add TTL tests as well.

**Comment by nyh** [comment]
Pushed a new version addressing (hopefully) all the reviewers comments. Among other smaller changes (to which I responded individually), the biggest changes are:
1. Split the first patch, that implemented the bulk of the feature, into four smaller patches, that are hopefully better explained and easier to read.
2. Some tests tested only WRITETIME() but should have also tested TTL() and now they do.

File: cql3/selection/selection.hh (hunk 29 above)
Comment (nyh) [reply cql3/selection/selection.hh]: Hmm, doesn't std::vector<cql3::expr::collection_cell_metadata>  need the full definition of cql3::expr::collection_cell_metadata?
I'm pretty sure it's at least needed for the constructor, but now I see the constructor of result_set_builder is external... So maybe you're right, just a forward declaration could have worked. But since I already moved the new class collection_cell_metadata to a new header file, I think that's fine too.

File: cql3/expr/expression.cc (hunk 19 above)
Comment (avikivity) [reply cql3/expr/expression.cc:1235]: Yes, I wanted on_internal_error() (https://github.com/scylladb/scylladb/pull/29134#discussion_r3004922925) then realized it was already there (https://github.com/scylladb/scylladb/pull/29134#discussion_r3004923251).

File: cql3/selection/selection.cc (hunk 20 above)
Comment (avikivity) [reply cql3/selection/selection.cc:618]: I'm not asking for a code refactor here. If you're just adding to the mess, not creating it, then okay. Please file a ticket to consolidate ser/deser to types/.

File: cql3/expr/evaluate.hh (hunk 27 above)
Comment (avikivity) [reply cql3/expr/evaluate.hh]: Typically you'd add the cluster feature in the patch that actually links the grammar.

Comment (avikivity) [reply cql3/expr/evaluate.hh]: And it's *technically* incorrect to add it before, since at that point, the node declares the feature, but doesn't actually support it.

**Review by avikivity — APPROVED** [review]

File: cql3/expr/evaluate.hh (hunk 27 above)
Comment (nyh) [reply cql3/expr/evaluate.hh]: I think it's fine:
1. Until the fourth patch, the new feature is in the grammar, but returns a InvalidRequest error if used (because the prepare() code forbids it). The series is bisectable - everything compiles, runs reasonably, and no test changes or breaks.
2. The feature flag is supposed to allow rolling upgrade of actual versions - nobody will upgrade into a version in the middle of this series, where the feature flag is on but the implementation still produces an error.

Comment (avikivity) [reply cql3/expr/evaluate.hh]: > I think it's fine:
> 
> 1. Until the fourth patch, the new feature is in the grammar, but returns a InvalidRequest error if used (because the prepare() code forbids it). The series is bisectable - everything compiles, runs reasonably, and no test changes or breaks.

Let's say a node on the last patch is acting as coordinator against a node on the patch that introduces on the feature flag.

> 2. The feature flag is supposed to allow rolling upgrade of actual versions - nobody will upgrade into a version in the middle of this series, where the feature flag is on but the implementation still produces an error.

That's why I wrote technically incorrect. In practice it doesn't matter. But logically, it's wrong, the feature flag should be added at the patch that completes the replica behavior.

File: test/cqlpy/test_select_collection_element.py (hunk 22 above)
Comment (m-szymon) [reply test/cqlpy/test_select_collection_element.py:327]: I think this is consistent with `map_keys`, `map_values`: https://cassandra.apache.org/doc/latest/cassandra/developing/cql/functions.html?utm_source=chatgpt.com#collection-functions
That way you can get what you need without duplicating keys.

**Comment by nyh** [comment]
test_row_ttl_scheduling_group failure is of course unrelated to this patch, I'll open a new issue about it and paste here the link. The link: https://scylladb.atlassian.net/browse/SCYLLADB-1495

@scylladbbot trigger-ci

**Comment by nyh** [comment]
@avikivity thanks for approving. The CI now passed. Can you please merge? Thanks.

**Comment by nyh** [comment]
Merge freeze is over, so it's a good time to merge this PR. 
Beyond fixing two long-standing Cassandra compatibility holes, it is also a pre-requisite of the Alternator Vector Search implementation that we're trying to push for the upcoming release.

**Review by piodul — APPROVED** [review]

**Comment by piodul** [comment]
Queued
