### PR TITLE
Make AWS & Azure KMS boost testing use fixture + include Azure in pytests

### LINKED ISSUE #26775: Boost test gather for test.py does not handle test suites
Test suites are only handled for "combined" tests, which means that any other test using a suite to group tests
(for, say, shared fixture usage) will not pick up the tests proper.

Right now, this means test.py does not run `gcp_object_storage_test`, which in turn lead to a typo level error 
passing through for object storage tests.

### LINKED ISSUE #26776: "Unlimited" semaphore in utils::gcp::object_storage is broken
The semaphore is initialised to `std::numeric_limits<size_t>::max()`. This value should be `std::numeric_limits<ssize_t>::max()` (since semaphore uses signed values).

This leads to unit tests not working. Which however was not noticed due to bug in test gathering: #26775

Fix is trivial.

### LINKED ISSUE #26780: AWS KMS EAR boost testing should allow using mock to ensure always run
Currently, AWS KMS EAR tests only run on actual jenkins CI, where we have vars signalling the actual AWS account settings used for test.

However, like dtest/pytest, we can use `local-kms` mock server to ensure these test always run (and faster), even 
in local test runs -> more consistency/earlier warning on breakage.

### LINKED ISSUE #26781: Azure KMS EAR testing should use fixtures instead of test.py-based mock server
Tests are better self-contained, and moving mock server to proper fixtures helps with this.
Right now, it is cumbersome and requires figuring out how to run the mock sidelined to 
debug the boost tests for Azure EAR.

### PR DESCRIPTION
**Pull request by elcallio**
* Adds test fixture for AWS KMS
* Adds test fixture for Azure KMS
* Adds key provider proxy for Azure to pytests (ported dtests)
* Make test gather for boost tests handle suites
* Fix GCP test snafu

Fixes #26781
Fixes #26780
Fixes #26776
Fixes #26775

### CODE REVIEW

File: test/lib/gcs_fixture.cc [hunk 1]
```diff
@@ -140,22 +142,29 @@ static future<std::tuple<tp::process_fixture, int>> start_fake_gcs_server(const
...
-        if (!p) {
+        while (!p) {
             try {
                 BOOST_TEST_MESSAGE("Attempting to connect");
                 // TODO: seastar does not have a connect with timeout. That would be helpful here. But alas...
                 co_await with_timeout(std::chrono::steady_clock::now() + 20s, seastar::connect(socket_address(net::inet_address("127.0.0.1"), port)));
                 BOOST_TEST_MESSAGE("fake-gcs-server up and available"); // debug print. Why not.
+            } catch (std::system_error&) {
+                retry = true;
+                if (++retries < 8) {
```
Comment (regevran) [inline test/lib/gcs_fixture.cc]: 8 is a [Magic Number](https://en.wikipedia.org/wiki/Magic_number_(programming))

File: test/lib/aws_kms_fixture.cc [hunk 2]
```diff
@@ -0,0 +1,283 @@
...
+    size_t port_index = 0;
+
+    auto exec = tp::find_file_in_path("local-kms");
+    if (exec.empty()) {
+        exec = tp::find_file_in_path("docker");
+        if (exec.empty()) {
+            exec = tp::find_file_in_path("podman");
+        }
+        if (exec.empty()) {
+            throw std::runtime_error("Could not find local-kms or docker.");
```
Comment (regevran) [inline test/lib/aws_kms_fixture.cc]:
```suggestion
            throw std::runtime_error("Could not find file named either `local-kms`, `docker` or `podman`.");

File: test/lib/aws_kms_fixture.cc [hunk 3]
```diff
@@ -0,0 +1,283 @@
...
+        }
+
+        auto port_string = std::to_string(port);
+
+        if (port_index != 0) {
+            params[port_index] = port_string + ":" + port_string;
+            params[port_index + 2] = "PORT=" + port_string;
+        }
+
+        BOOST_TEST_MESSAGE(fmt::format("Will run {}", params));
```
Comment (regevran) [inline test/lib/aws_kms_fixture.cc:83]: Maybe:
```suggestion
        BOOST_TEST_MESSAGE(fmt::format("start_fake_kms_server will run {}", params));
```

File: test/lib/aws_kms_fixture.cc [hunk 4]
```diff
@@ -0,0 +1,283 @@
...
+    endpoint = f->endpoint();
+    kms_key_alias = f->kms_key_alias();
+    kms_aws_region = f->kms_aws_region();
+    kms_aws_profile = f->kms_aws_profile();
+}
+
+seastar::future<> local_aws_kms_wrapper::teardown() {
+    if (_local) {
+        co_await _local->teardown();
+        _local = {};
```
Comment (regevran) [inline test/lib/aws_kms_fixture.cc:291]: nit:
```cpp
 _local.reset();
```

File: test/lib/aws_kms_fixture.cc [hunk 5]
```diff
@@ -0,0 +1,283 @@
...
+    }
+}
```
Comment (regevran) [inline test/lib/aws_kms_fixture.cc:293]: With two concurrent users - the first creates `aws_kms_fixture` (L267), the second just uses it (L266), but then one of them `teardown` and remove the server for the other one.
Don't we need ref-count?

File: ent/encryption/encryption.cc
Comment (regevran) [inline ent/encryption/encryption.cc:1]: What is the motivation?

File: test/lib/aws_kms_fixture.cc [hunk 6]
```diff
@@ -0,0 +1,283 @@
...
+
+        auto [proc, port] = co_await start_fake_kms_server(tmp, seed);
+        local_kms.emplace(std::move(proc));
+        kms_key_alias = "alias/testing";
+        endpoint = "http://127.0.0.1:" + std::to_string(port);
+        BOOST_TEST_MESSAGE(fmt::format("Test server endpoint {}, alias {}", endpoint, kms_key_alias));
+    }
+}
+
+seastar::future<> aws_kms_fixture::impl::teardown() {
```
Comment (regevran) [inline test/lib/aws_kms_fixture.cc:229]: Would be better to remove `tmp`, or at least ` tmp.path() / "seed.yaml"`

File: test/lib/azure_kms_fixture.hh [hunk 7]
```diff
@@ -0,0 +1,86 @@
...
+    * AZURE_TENANT_ID - the tenant where the principals live
+    * AZURE_USER_1_CLIENT_ID - the client ID of user1
+    * AZURE_USER_1_CLIENT_SECRET - the secret of user1
+    * AZURE_USER_1_CLIENT_CERTIFICATE - the PEM-encoded certificate and private key of user1
+    * AZURE_USER_2_CLIENT_ID - the client ID of user2
+    * AZURE_USER_2_CLIENT_SECRET - the secret of user2
+    * AZURE_USER_2_CLIENT_CERTIFICATE - the PEM-encoded certificate and private key of user2
+*/
+
+struct azure_test_env {
```
Comment (regevran) [inline test/lib/azure_kms_fixture.hh:35]: For aws, similar parameters are part of the [aws-wrapper](https://github.com/scylladb/scylladb/pull/26785/commits/e74713bccc1b8006252662130c2047173ef1cfdc#diff-51c79f73b40289b1afc632e6e520fd76046deb71243b64e5f0bbf3dbf42c4a85R71).
Here they are independent and [azure-wrapper](https://github.com/scylladb/scylladb/pull/26785/commits/124151968b85461f962c6fac1aaaf751e5b15b9b#diff-b107290bc875c6acab86c487b5562270e2a247584dd2724bf8d8e863b8b1c6dfR76) inherits them.

Not THAT important, we have independent implementations that may have different structures, but why?

Comment (regevran) [reply test/lib/azure_kms_fixture.hh:35]: I figured it out in the next commit - the code was shifted here.

**Comment by ndragazis** [comment]
I cannot even run a single test with the `gcs_fixture` on my system. `podman` is looking for `~/.config` which doesn't exist. I wonder how this works in CI (note: I'm running `dbuild` with docker).
```bash
$ tools/toolchain/dbuild ./build/dev/test/boost/gcp_object_storage_test --run_test=gcs_tests/test_gcp_storage_create_small_object --log_level=all
Running 1 test case...
Entering test module "Master Test Suite"
test/boost/gcp_object_storage_test.cc(121): Entering test suite "gcs_tests"
INFO  2025-10-31 21:22:24,955 seastar - Reactor backend: io_uring
INFO  2025-10-31 21:22:24,967 seastar - Perf-based stall detector creation failed (EACCESS), try setting /proc/sys/kernel/perf_event_paranoid to 1 or less to enable kernel backtraces: falling back to posix timer.
INFO  2025-10-31 21:22:24,971 [shard  5:main] io - IO queue was unable to find a suitable maximum request length, the search was cut-off early at: 16MB
INFO  2025-10-31 21:22:24,971 [shard  5:main] io - IO queue was unable to find a suitable maximum request length, the search was cut-off early at: 16MB
random-seed=1807394223
Will run ["/usr/sbin/podman", "run", "--rm", "-p", "36549:36549", "docker.io/fsouza/fake-gcs-server:1.52.3", "-scheme", "http", "-log-level", "debug", "--port", "36549"]
Waiting for process to laúnch...
stat /home/ndragazis/.config: no such file or directory
Got exception starting server: seastar::broken_promise (broken promise)
unknown location(0): fatal error: in "gcs_tests": seastar::broken_promise: broken promise
test/boost/gcp_object_storage_test.cc(121): Leaving test suite "gcs_tests"
Leaving test module "Master Test Suite"; testing time: 174538us

*** 1 failure is detected in the test module "Master Test Suite"
```

File: test/lib/gcs_fixture.cc [hunk 8]
```diff
@@ -140,22 +142,29 @@ static future<std::tuple<tp::process_fixture, int>> start_fake_gcs_server(const
...
 
-        if (!p) {
+        while (!p) {
             try {
                 BOOST_TEST_MESSAGE("Attempting to connect");
                 // TODO: seastar does not have a connect with timeout. That would be helpful here. But alas...
                 co_await with_timeout(std::chrono::steady_clock::now() + 20s, seastar::connect(socket_address(net::inet_address("127.0.0.1"), port)));
                 BOOST_TEST_MESSAGE("fake-gcs-server up and available"); // debug print. Why not.
+            } catch (std::system_error&) {
+                retry = true;
```
Comment (ndragazis) [inline test/lib/gcs_fixture.cc]: We shouldn't update the `retry` variable here. This is meant for the outer loop. The inner loop has its own retry logic.

It's actually a bug to set it here. Consider this scenario:
* The inner loop hits a system error once, so it sets `retry = true;`.
* Then, it hits a non-system error, which should not be retried, but it will be retried by the outer loop if we set the variable to `true`.

I would also suggest we rewrite the two loops in a serial format. The current nested format is quite confusing; the outer loop is never retried once we reach the inner loop.

File: test/lib/gcs_fixture.cc (hunk 1 above)
Comment (ndragazis) [inline test/lib/gcs_fixture.cc]: 1. What is the expected number of retries? This condition allows for 7 retries, but a few lines later we have another condition that allows 9 retries:
   ```cpp
   if (!retry || retries > 8) {
       std::rethrow_exception(p);
   }
   ```
2. Not related to this PR, but the retry logic of the outer loop is broken:
    ```cpp
            if (p != nullptr) {
                BOOST_TEST_MESSAGE(fmt::format("Got exception starting server: {}", p));
                ps.terminate();
                co_await ps.wait();
                if (!retry || retries > 8) {
                    std::rethrow_exception(p);
                }
            }

            co_return std::make_tuple(std::move(ps), port);
    ```
    We should either `continue;` if a retry is needed, or wrap the `co_return` in an `else` statement.

File: test/lib/aws_kms_fixture.cc [hunk 9]
```diff
@@ -0,0 +1,283 @@
...
+        }
+
+        // publish port ephemeral, allows parallel instances
+        params = {
+            "",
+            "run", "--rm", 
+            "-v", seed.string() + ":/init/seed.yaml",
+            "-p", "--", // set below
+            "-e", "--", // set below
+            "docker.io/nsmithuk/local-kms:3"
```
Comment (ndragazis) [inline test/lib/aws_kms_fixture.cc:52]: I wonder why this one and not [moto](https://docs.getmoto.org/en/latest/docs/server_mode.html#run-using-docker) which we also use in SCT.

File: test/lib/gcs_fixture.cc (hunk 1 above)
Comment (elcallio) [reply test/lib/gcs_fixture.cc]: No, seven is magic. Eight is quite ordinary. Seriously, hard-coded, arbitrary constants are not great, but in arbitrary test wait-loops they are fairly ok. Can make a constant of it, but that is just adding an abstraction that does not exist. That it gets repeated is however an argument for it.

File: test/lib/aws_kms_fixture.cc (hunk 2 above)
Comment (elcallio) [reply test/lib/aws_kms_fixture.cc]: True, I guess.

File: test/lib/aws_kms_fixture.cc (hunk 4 above)
Comment (elcallio) [reply test/lib/aws_kms_fixture.cc:291]: Why? It is literally the same thing.

File: test/lib/aws_kms_fixture.cc (hunk 5 above)
Comment (elcallio) [reply test/lib/aws_kms_fixture.cc:293]: No, we never create more than one instance here. However, your remark makes me realize the azure one does need a guard for overwriting the global var.

File: ent/encryption/encryption.cc
Comment (elcallio) [reply ent/encryption/encryption.cc:1]: For what?

Comment (elcallio) [reply ent/encryption/encryption.cc:1]: Ah, you mean moving to std::string? The fact that sstring usage is legacy behaviour and moving this to std::string means expressions using auto assignment and similar will get the expected/desired type without convertsions etc. 
Not needed, but I really would like to slowly move all encryption (and other) code to use std types when possible.

File: test/lib/aws_kms_fixture.cc (hunk 6 above)
Comment (elcallio) [reply test/lib/aws_kms_fixture.cc:229]: Why? It will be removed when the object dies. Since it is a temp dir, we will not clash with another instance.

**Comment by elcallio** [comment]
> I cannot even run a single test with the `gcs_fixture` on my system. `podman` is looking for `~/.config` which doesn't exist. I wonder how this works in CI (note: I'm running `dbuild` with docker).

Yeah, that is perhaps the downside: You are pretty much required to move to podman, as this is the "official" (primary) container used by dbuild. Even so, the podman-in-podman is somewhat weak, but at least functional.

File: test/lib/gcs_fixture.cc (hunk 8 above)
Comment (elcallio) [reply test/lib/gcs_fixture.cc]: The nesting is there for a reason. We can still fail the outer loop here (other exceptions). But the retry should probably change to a back-off instead.

File: test/lib/gcs_fixture.cc (hunk 1 above)
Comment (elcallio) [reply test/lib/gcs_fixture.cc]: Oops. bad partial commit-rebase...

File: test/lib/aws_kms_fixture.cc (hunk 9 above)
Comment (elcallio) [reply test/lib/aws_kms_fixture.cc:52]: We are not running python here. While it would be possible to call a python script, it is easier to just create the seed file.

File: test/lib/gcs_fixture.cc (hunk 8 above)
Comment (ndragazis) [reply test/lib/gcs_fixture.cc]: > We can still fail the outer loop here (other exceptions).

What do you mean? Is there any scenario where the outer loop would continue?

Comment (elcallio) [reply test/lib/gcs_fixture.cc]: !system_error -> catch -> check below (with continue fix) means if retry < max -> retry outer.

File: test/lib/aws_kms_fixture.cc (hunk 9 above)
Comment (ndragazis) [reply test/lib/aws_kms_fixture.cc:52]: You don't have to run Python. The tool has a "server mode"; you can run it in a container.

I'm asking because the image you used is two years old. The project seems unmaintained.

Comment (elcallio) [reply test/lib/aws_kms_fixture.cc:52]: Sounds even more complicated. Again, a simple config file seems ideal for the purpose...
Might not be much updated, but as it stands it fills all requirements/works well. Maybe feature complete? :-)

**Comment by ndragazis** [comment]
> > I cannot even run a single test with the `gcs_fixture` on my system. `podman` is looking for `~/.config` which doesn't exist. I wonder how this works in CI (note: I'm running `dbuild` with docker).
> 
> Yeah, that is perhaps the downside: You are pretty much required to move to podman, as this is the "official" (primary) container used by dbuild. Even so, the podman-in-podman is somewhat weak, but at least functional.

Well, I don't see any evidence for that. The `dbuild` script still supports Docker.

Let's discuss in an issue. I'll open a new one.

Edit: https://github.com/scylladb/scylladb/issues/26837

**Comment by elcallio** [comment]
> Well, I don't see any evidence for that. The `dbuild` script still supports Docker.
> 
> Let's discuss in an issue. I'll open a new one.

The script support docker, but the things to support container-in-container are podman only. Docker in docker requires (IIRC) quite a bit of tweaks from the host side. Not sure how doable it is on a dbuild script level...

File: test/lib/aws_kms_fixture.cc [hunk 10]
```diff
@@ -0,0 +1,285 @@
...
+        promise<> ready_promise;
+        auto ready_fut = ready_promise.get_future();
+
+        auto ps = co_await tp::process_fixture::create(exec
+            , params
+            , env
+            , tp::process_fixture::create_copy_handler(std::cout)
+            // Must look at stderr log for state, because if we are using podman (and docker?)
+            // the 4443 port will in fact be connectible even before the actual 
+            // fake-gcs-server is up (in container), due to the port publisher.
```
Comment (ndragazis) [inline test/lib/aws_kms_fixture.cc]: Please replace `fake-gcs-server` with `local-kms`.

Comment (ndragazis) [inline test/lib/aws_kms_fixture.cc]: Please replace `fake-gcs-server` with `local-kms`.

File: test/lib/aws_kms_fixture.cc [hunk 11]
```diff
@@ -0,0 +1,285 @@
...
+            // Could do actual HTTP connection etc, but seems tricky.
+            , [done = false, ready_promise = std::move(ready_promise), h = tp::process_fixture::create_copy_handler(std::cerr)](std::string_view line) mutable -> future<consumption_result<char>> {
+                if (!done && line.find("Local KMS started on") != std::string::npos) {
+                    BOOST_TEST_MESSAGE(fmt::format("Got start message: {}", line));
+                    done = true;
+                    ready_promise.set_value();
+                }
+                if (!done && line.find("address already in use") != std::string::npos) {
```
Comment (ndragazis) [inline test/lib/aws_kms_fixture.cc:109]: The error message depends on how you run it:

* If we run the executable directly:
   ```
   time="2025-11-03T16:47:05+02:00" level=fatal msg="ListenAndServe: listen tcp :8080: bind: address already in use"
   ```
* If we run it with Podman:
   ```
   Failed to bind port 8080 (Address already in use) for option '-t 8080-8080:8080-8080'
   ```
* If we run it with Docker:
   ```
   Bind for 0.0.0.0:8080 failed: port is already allocated
   ```

File: test/lib/aws_kms_fixture.hh [hunk 12]
```diff
@@ -0,0 +1,84 @@
...
+
+/*
+    Simple AWS KMS mock/real provider. Uses either real or local, fake, endpoint.
+
+    Note: fake kms server does not have any credentials or permissions
+
+    This fixture is parameterized with env vars, if set we will just expose 
+    a real (we assume) KMS endpoint:
+
+    * KMS_KEY_ALIAS - default "alias/kms_encryption_test" - set to key alias you have access to.
```
Comment (ndragazis) [inline test/lib/aws_kms_fixture.hh]: Please update this line. There is no default anymore.

**Comment by ndragazis** [comment]
@elcallio something is wrong with the test suites in `encryption_at_rest_test.cc`. It's like no suite is constructed (and therefore the fixture won't run):
```bash
ENABLE_KMS_TEST=1 ./build/dev/test/boost/encryption_at_rest_test --run_test=aws_kms/test_kms_provider/local_aws_kms_wrapper 
Test setup error: no test cases matching filter or all test cases were disabled
```
All tests are listed as top-level:
```bash
$ ENABLE_KMS_TEST=1 ./build/dev/test/boost/encryption_at_rest_test  --list_content
test_local_file_provider*
test_replicated_provider*
test_replicated_provider_with_restart*
test_replicated_provider_many_tables*
test_replicated_provider_shutdown_failure*
test_kmip_provider*
test_kmip_provider_multiple_hosts*
test_kms_provider*
test_kms_provider_with_master_key_in_cf*
test_user_info_encryption*
test_kms_provider_with_broken_algo*
test_commitlog_kms_encryption_with_slow_key_resolve*
test_commitlog_kmip_encryption_with_slow_key_resolve*
test_user_info_encryption_dont_allow_per_table_encryption*
test_gcp_provider*
test_gcp_provider_with_master_key_in_cf*
test_gcp_provider_with_invalid_user*
test_gcp_provider_with_impersonated_user*
test_kms_network_error*
test_kmip_network_error*
test_kmip_provider_broken_config_on_restart*
test_kmip_provider_broken_sstables_on_restart*
test_azure_provider_with_imds*
test_azure_provider_with_secret*
test_azure_provider_with_secret_real*
test_azure_provider_with_certificate*
test_azure_provider_with_certificate_real*
test_azure_provider_with_master_key_in_cf*
test_azure_provider_with_no_host*
test_azure_provider_with_incomplete_creds*
test_azure_provider_with_invalid_key*
test_azure_provider_with_invalid_key_real*
test_azure_provider_with_invalid_user*
test_azure_provider_with_invalid_user_real*
test_azure_provider_with_both_secret_and_cert*
test_azure_provider_with_both_secret_and_cert_real*
test_azure_network_error*
test_imds*
test_entra_sts*
test_azure_host*
```
For comparison, here is how the suite is listed for GCS tests:
```bash
$ ENABLE_KMS_TEST=1 ./build/dev/test/boost/gcp_object_storage_test  --list_content
gcs_tests*
    test_gcp_storage_create_small_object*
    test_gcp_storage_create_large_object*
    test_gcp_storage_list_objects*
    test_gcp_storage_delete_object*
    test_gcp_storage_skip_read*
    test_merge_objects*
```

**Comment by elcallio** [comment]
Not the output I get:
```
test_local_file_provider*
test_replicated_provider*
test_replicated_provider_many_tables*
test_replicated_provider_shutdown_failure*
test_kmip_provider*
test_kmip_provider_multiple_hosts*
test_commitlog_kmip_encryption_with_slow_key_resolve*
test_kmip_network_error*
test_kmip_provider_broken_config_on_restart*
test_kmip_provider_broken_sstables_on_restart*
aws_kms*
    test_kms_provider*
    test_kms_provider_with_master_key_in_cf*
    test_kms_provider_with_broken_algo*
    test_commitlog_kms_encryption_with_slow_key_resolve*
    test_kms_network_error*
test_user_info_encryption*
test_user_info_encryption_dont_allow_per_table_encryption*
test_gcp_provider*
test_gcp_provider_with_master_key_in_cf*
test_gcp_provider_with_invalid_user*
test_gcp_provider_with_impersonated_user*
azure_kms*
    test_azure_provider_with_imds*
    test_azure_provider_with_secret*
    test_azure_provider_with_secret_real*
    test_azure_provider_with_certificate*
    test_azure_provider_with_certificate_real*
    test_azure_provider_with_master_key_in_cf*
    test_azure_provider_with_no_host*
    test_azure_provider_with_incomplete_creds*
    test_azure_provider_with_invalid_key*
    test_azure_provider_with_invalid_key_real*
    test_azure_provider_with_invalid_user*
    test_azure_provider_with_invalid_user_real*
    test_azure_provider_with_both_secret_and_cert*
    test_azure_provider_with_both_secret_and_cert_real*
    test_azure_network_error*
    test_imds*
    test_entra_sts*
    test_azure_host*
```

**Comment by ndragazis** [comment]
Sorry, false alarm. For a moment I thought it was part of the `combined_tests` target.

File: test/lib/aws_kms_fixture.cc [hunk 13]
```diff
@@ -0,0 +1,285 @@
...
+            "run", "--rm", 
+            "-v", seed.string() + ":/init/seed.yaml",
+            "-p", "--", // set below
+            "-e", "--", // set below
+            "docker.io/nsmithuk/local-kms:3"
+        };
+        port_index = 6;
+    }
+
+    params[0] = exec.string();
```
Comment (ndragazis) [inline test/lib/aws_kms_fixture.cc:57]: This assignment is dangerous. The vector may be empty.

File: test/lib/gcs_fixture.cc (hunk 1 above)
Comment (elcallio) [reply test/lib/gcs_fixture.cc]: Fixed

File: test/lib/aws_kms_fixture.cc (hunk 2 above)
Comment (elcallio) [reply test/lib/aws_kms_fixture.cc]: Fixed

File: test/lib/aws_kms_fixture.cc (hunk 3 above)
Comment (elcallio) [reply test/lib/aws_kms_fixture.cc:83]: Clarified

File: test/lib/gcs_fixture.cc (hunk 8 above)
Comment (elcallio) [reply test/lib/gcs_fixture.cc]: Modified and corrected.

File: test/lib/gcs_fixture.cc (hunk 1 above)
Comment (elcallio) [reply test/lib/gcs_fixture.cc]: Fixed. Both original merge-problem and copy-paste.

File: test/pylib/cpp/boost.py [hunk 14]
```diff
@@ -144,29 +144,57 @@ def get_boost_test_list_content(executable: pathlib.Path, combined: bool = False
...
             continue
+        n = next((i for i, c in enumerate(line) if c != ' '), len(line))
+        if n > indent:
+            # last was a test suite
+            stack.append(current_suite)
+            current_suite = current_suite[last]
+        elif n < indent:
+            # end of a suite
+            current_suite = stack[-1]
+            stack.pop()
```
Comment (ndragazis) [inline test/pylib/cpp/boost.py]: 1. nit: `pop()` returns the removed item, so we can do the same with one statement:
    ```python
    current_suite = stack.pop()
    ```
2. How do we know that the end of a suite does not span across multiple nested suites? Consider this example:
    ```
    suite1
        nestedsuite1
            test1
    suite2
        test2
    ```
    We should be storing every suite in the stack along with its indentation level and pop until we match it.

File: test/lib/azure_kms_fixture.cc [hunk 15]
```diff
@@ -0,0 +1,225 @@
...
+    user_1_client_certificate = getenv_or_default("AZURE_USER_1_CLIENT_CERTIFICATE");
+    user_2_client_id = getenv_or_default("AZURE_USER_2_CLIENT_ID");
+    user_2_client_secret = getenv_or_default("AZURE_USER_2_CLIENT_SECRET");
+    user_2_client_certificate = getenv_or_default("AZURE_USER_2_CLIENT_CERTIFICATE", "");
+    authority_host = "''";
+    imds_endpoint = "''";
+}
+
+seastar::future<> azure_kms_fixture::impl::setup() {
+    if ((key_name.empty() || mode == azure_mode::local) && mode != azure_mode::real) {
```
Comment (ndragazis) [inline test/lib/azure_kms_fixture.cc]: Equivalent to:
```cpp
if (key_name.empty() && mode != azure_mode::real) {
```
but I think even the key name check is redundant.

**Comment by elcallio** [comment]
rebased

**Comment by elcallio** [comment]
@scylladbbot trigger-ci

**Comment by ndragazis** [comment]
@elcallio did you consider my latest review comments in your newest version? Only the first comment is marked as "Outdated".

File: test/lib/aws_kms_fixture.cc (hunk 11 above)
Comment (elcallio) [reply test/lib/aws_kms_fixture.cc:109]: So, this will only happen if running non-dbuild (which is valid though). For podman-in-podman, we're using host network, so only the actual image executable will cause the bind error. 

Technically, this should kill the container, so I guess checking process status might be sufficient. But adding extra parsing might be useful...

File: test/lib/aws_kms_fixture.cc (hunk 13 above)
Comment (elcallio) [reply test/lib/aws_kms_fixture.cc:57]: true

File: test/pylib/cpp/boost.py (hunk 14 above)
Comment (elcallio) [reply test/pylib/cpp/boost.py]: true.

**Review by ndragazis — APPROVED** [review]

File: test/lib/aws_kms_fixture.cc (hunk 5 above)
Comment (elcallio) [reply test/lib/aws_kms_fixture.cc:293]: Fixed.

File: test/lib/aws_kms_fixture.cc (hunk 10 above)
Comment (elcallio) [reply test/lib/aws_kms_fixture.cc]: Done

File: test/lib/aws_kms_fixture.cc (hunk 11 above)
Comment (elcallio) [reply test/lib/aws_kms_fixture.cc:109]: Done here and for python counterpart.

File: test/lib/aws_kms_fixture.cc (hunk 13 above)
Comment (elcallio) [reply test/lib/aws_kms_fixture.cc:57]: Fixed

File: test/pylib/cpp/boost.py (hunk 14 above)
Comment (elcallio) [reply test/pylib/cpp/boost.py]: Fixed

File: test/lib/aws_kms_fixture.hh (hunk 12 above)
Comment (elcallio) [reply test/lib/aws_kms_fixture.hh]: Done

**Comment by elcallio** [comment]
@scylladb/scylla-maint - ping?

File: test/lib/aws_kms_fixture.cc (hunk 9 above)
Comment (xemul) [reply test/lib/aws_kms_fixture.cc:52]: Probably a stupid question, but to start azure server mock, the corresponding boost fixture uses our own py script from test/pylib/. Why this fixture starts some 3rd party image "by hand"? There's test/pylib/encryption_provider.py that starts the very same image, why isn't this place made symmetrical to azure fixture?

**Comment by xemul** [comment]
Also a general question about fixtures -- we have "same thing" for tests running agains S3 and there are no boost fixtures for them. Is it because it makes no sense (in that case -- why?) or is it just in "would be nice to have too, but not this time" state?

**Review by xemul — APPROVED** [review]

File: test/lib/aws_kms_fixture.cc (hunk 9 above)
Comment (elcallio) [reply test/lib/aws_kms_fixture.cc:52]: The azure mock is pure python. No docker. So a better comparison would be KMIP fixture. Which works more or less like the Azure one.

The `encryption_provider` does more or less the same as this fixture setup (use docker image), and yes, technically we could call that code, but that would just mean we have to create a main method + arg parse + package same parameters for python invocation to do the image start.

The plus would be single point of code. The negative would be the code depending on yet another file in a different language. 
From my standpoint it seems cleaner to try to make running docker mocks into a pure boost part of the suite (there is still some room for code sharing here, but one risks running into false abstractions).

**Comment by elcallio** [comment]
> Also a general question about fixtures -- we have "same thing" for tests running agains S3 and there are no boost fixtures for them. Is it because it makes no sense (in that case -- why?) or is it just in "would be nice to have too, but not this time" state?

The latter. I would very much like to get rid of the always-on Minio server, and move it to proper on-demand fixtures for both pytests and boost. But it is legion, so left for a different, later, PR.
