### PR TITLE
alternator: add support for AttributeUpdates Add operation

### LINKED ISSUE #5893: alternator - missing support for UpdateItem ADD operation
In the old-style AttributeUpdates parameter for the UpdateItem operation (later superseded by newer UpdateExpression parameter), an ADD operation can be used to increment numbers or append to a set (i.e., this is a type of conditional expression, which would require LWT). We don't support this syntax yet, and don't even have a test for it yet.

In the code we have the following check, so at least it gives an error if used:
```c++
            } else {
                // FIXME: need to support "ADD" as well.
                throw api_error("ValidationException",
                        format("Unknown Action value '{}' in AttributeUpdates", action));
            }
```

### PR DESCRIPTION
**Pull request by nyh**
In UpdateItem's AttributeUpdates (old-style parameter) we were missing
support for the ADD operation - which can increment a number, or add
items to sets (or to lists, even though this fact isn't documented).

This two-patch series add this missing feature. The first patch just moves
an existing function to where we can reuse it, and the second patch is
the actual implementation of the feature (and enabling its test).
    
Fixes #5893

### CODE REVIEW

**Review by psarna — APPROVED** [review]

File: alternator/executor.cc [hunk 1]
```diff
@@ -2665,8 +2689,44 @@ update_item_operation::apply(std::unique_ptr<rjson::value> previous_item, api::t
                 const rjson::value& value = (it->value)["Value"];
                 validate_value(value, "AttributeUpdates");
                 do_update(std::move(column_name), value);
+            } else if (action == "ADD") {
```
Comment (psarna) [inline alternator/executor.cc:2692]: side note: with this routine, `update_item_operation::apply` hit >200 lines of code - maybe we should consider moving some of the subroutines out in a follow-up, to make it fit into a single screen

Comment (nyh) [reply alternator/executor.cc:2692]: Perhaps. My philosophy on splitting function is apparently very different from other developers' - whereas some view any function with more than 20 lines an abomination, I view a long linear function (which you can just read linearly to understand) better than artificially splitting it into 10 different functions that nobody will understand when reading them one by one. That doesn't say that we can't split it in a way that doesn't look artificial. I can try to think about this later.
