### PR TITLE
cql3: Fix missing aggregate functions for counters

### LINKED ISSUE #3174: Aggregation of counters
*Installation details*
Scylla version (or git commit hash): 2.1-rc2

Hello. I noticed that aggregation functions doesn't work on counters. I don't see any reason this shouldn't be possible.

How to reproduce:
```
CREATE TABLE test (
        key INT,
        ctr COUNTER,
        PRIMARY KEY (
                key
        )
);

UPDATE test SET ctr = ctr + 1 WHERE key = 1;
SELECT SUM(ctr) FROM test;
```

Result
> InvalidRequest: Error from server: code=2200 [Invalid query] message="Invalid call to function sum, none of its type signatures match (known type signatures: system.sum : (org.apache.cassandra.db.marshal.DecimalType) -> org.apache.cassandra.db.marshal.DecimalType, system.sum : (org.apache.cassandra.db.marshal.IntegerType) -> org.apache.cassandra.db.marshal.IntegerType, system.sum : (org.apache.cassandra.db.marshal.DoubleType) -> org.apache.cassandra.db.marshal.DoubleType, system.sum : (org.apache.cassandra.db.marshal.FloatType) -> org.apache.cassandra.db.marshal.FloatType, system.sum : (org.apache.cassandra.db.marshal.LongType) -> org.apache.cassandra.db.marshal.LongType, system.sum : (org.apache.cassandra.db.marshal.Int32Type) -> org.apache.cassandra.db.marshal.Int32Type, system.sum : (org.apache.cassandra.db.marshal.ShortType) -> org.apache.cassandra.db.marshal.ShortType, system.sum : (org.apache.cassandra.db.marshal.ByteType) -> org.apache.cassandra.db.marshal.ByteType)"

I also tried casting
`SELECT SUM(CAST(ctr as bigint)) FROM test`
but it's not working either

> Error from server: code=2200 [Invalid query] message="org.apache.cassandra.db.marshal.CounterColumnType cannot be cast to org.apache.cassandra.db.marshal.LongType"

### PR DESCRIPTION
**Pull request by jul-stas**
Aggregate functions for counters do not exist. Until now counters could, at best, fall back to blob->blob overloads, e.g.:

```
cqlsh> select max(cnt) from ks.tbl;

 system.max(cnt)
----------------------
   0x000000000000000a
(1 rows)
cqlsh> select sum(cnt) from ks.tbl;
InvalidRequest: Error from server: code=2200 [Invalid query]
message="Invalid call to function sum, none of its type signatures match
[...]
```

Meanwhile, bigint (`long_type`) overloads (e.g. `sum(bigint)->bigint`) can be used on counters just fine. In this patch this is achieved by special rule in "overload resolution". `selector` now perceives counters as an `EXACT_MATCH` to their underlying type (bigint).

Fixes #3174

### CODE REVIEW

**Comment by avikivity** [comment]
Subject looks like a bug report, not a fix. Fixes should say they are fixing something, not that there is a problem.

File: cql3/selection/selector.hh [hunk 1]
```diff
@@ -109,7 +109,10 @@ public:
     virtual assignment_testable::test_result test_assignment(database& db, const sstring& keyspace, ::shared_ptr<column_specification> receiver) override {
         auto t1 = receiver->type->underlying_type();
         auto t2 = get_type()->underlying_type();
-        if (t1 == t2) {
+        // We want columns of `counter_type' to be served by `long_type' overloads with
+        // an `EXACT_MATCH'. Weak assignability between the two would lead to ambiguity
+        // because `WEAKLY_ASSIGNABLE' counter->blob conversion exists and would compete.
+        if (t1 == t2 || (t1 == long_type && t2->is_counter())) {
```
Comment (avikivity) [inline cql3/selection/selector.hh]: An alternative solution is to create those aggregate functions for counter types. But I think it's not as good, because it won't work for user defined functions.

There is a risk here that this overload will compete with another overload that does have a counter type for the receiver, and we will lost it.

Comment (avikivity) [reply cql3/selection/selector.hh]: Yet another option is to change test_result into a class that can express EXACT_MATCH, NOT_ASSIGNABLE, and WEAKLY_ASSIGNABLE(score), and code that checks for WEAKLY_ASSIGNABLE can select the best score. Not sure if there is such a place in the code base.

Comment (avikivity) [reply cql3/selection/selector.hh]: @psarna @tgrabiec opinions please

Comment (psarna) [reply cql3/selection/selector.hh]: 1. I think that instead of open coding `long_type`, `counter_cell_view::total_value_type()` can be used to show why it's ok for counters to use that type.
2. As for exact_match and weakly_assignable, @jul-stas I need more context first - why do counters fall back to `blob->blob` in the first place? Is it because they're weakly assignable to both blobs and long_type, but blobs just happen to be first on the list?

Comment (jul-stas) [reply cql3/selection/selector.hh]: @psarna 
1. I don't understand - do you mean unification of `long_type`'s and `counter_type`'s `native` types? Or... I don't know... a static assert on identity of both types?
2. Almost. Blob is weakly assignable to every type, per:
 https://github.com/jul-stas/scylla/blob/ccaaf74cb91dfd3623c3a4775fe80a922ed53508/types.cc#L2475
Now, there is no `sum(blob)->blob` nor `avg(blob)->blob`, but we do have `min(blob)->blob` and `max(blob)->blob`. There is no implicit conversion `counter->int/bigint`. So when called on counters, `sum`/`avg` respond "Invalid, none of its signatures match". But `min`/`max` called on counters find the only weakly assignable overload: `(blob)->blob` (as in the example in top message).
Now if I grant counters any additional weak assignability, say `counter->bigint`, then `sum`/`avg` will start to work correctly - by using the only weakly assignable overload: `sum(bigint)->bigint`. But `min`/`max` will stop working because of competing overloads: `blob` and `bigint` (and the message will be "ambiguous call" because, sadly, we have no notion of overloads' priorities). So if we don't have an exactly matching overload and we have >1 weakly matching overload => error.

Comment (psarna) [reply cql3/selection/selector.hh]: 1. Oh, I just mean using `counter_cell_view::total_value_type()` instead of `long_type` in this very line :)
2. Ok, makes sense. It would be nice to have an assignability score and use that, but since we don't have it yet, I think that your way is simple and correct. Looks good.

**Comment by jul-stas** [comment]
ping @tgrabiec - would you be so kind to comment on this?

**Comment by haaawk** [comment]
@avikivity What do we need to do to move forward with this?

**Comment by avikivity** [comment]
@jul-stas please also update the commit subject itself (that's what gets merged).

**Comment by jul-stas** [comment]
@avikivity I removed `[RFC]` and "context description"
@psarna After some thinking I think you were right, so changed `long_type` to "counters underlying type"

**Comment by avikivity** [comment]
@jul-stas I still see "Counter values are consumed" which describes the bug, not the fix.

**Comment by jul-stas** [comment]
@avikivity OK, I changed title to "Fix missing aggregate functions for counters".
Sorry for bad wording but... counter being consumed by `func(bigint)` is exactly the desired behaviour :smiley:

**Comment by haaawk** [comment]
@avikivity Do we have to change anything else here?

**Comment by avikivity** [comment]
> @avikivity OK, I changed title to "Fix missing aggregate functions for counters".
> Sorry for bad wording but... counter being consumed by `func(bigint)` is exactly the desired behaviour

Oh, sorry for adding to the confusion.

But for the future, the passive voice is best avoided^W^W^W^W^W^Wplease avoid the passive voice. It's usually less clear.
