### PR TITLE
Distinguish single-column expressions in AST

### LINKED ISSUE #6825: test_tuple_indexes failure post 'Rewrite CQL3 restriction representation'
The regression started with b0698dfb38afacbd3daf8f64ec83e63ba0ce0cd9
and was seen in jenkins since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/549/testReport/secondary_indexes_test/TestSecondaryIndexesOnCollections/test_tuple_indexes/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/secondary_indexes_test.py", line 1232, in test_tuple_indexes
    list(session.execute(select_cmd.format(table_name, index_column, template.format(n))))))
  File "/usr/lib64/python3.7/unittest/case.py", line 869, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.7/unittest/case.py", line 862, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 5 != 0
```

@dekimir said:
> At first glance, the test looks correct to me.  Can you please file a bug?
￼

### PR DESCRIPTION
**Pull request by dekimir**
Fix #6825 by explicitly distinguishing single- from multi-column expressions in AST.

Tests: unit (dev), dtest secondary_indexes_test.py (dev)

### CODE REVIEW

File: cql3/restrictions/restriction.hh [hunk 1]
```diff
@@ -93,7 +93,7 @@ struct token {};
 
 /// Operator restriction: LHS op RHS.
 struct binary_operator {
-    std::variant<std::vector<column_value>, token> lhs;
+    std::variant<column_value, std::vector<column_value>, token> lhs;
```
Comment (avikivity) [inline cql3/restrictions/restriction.hh:96]: It will be good to further disambiguate std::vector<column_value> as a new struct column_value_tuple, later on. This makes the role of the vector visible in the name.

File: cql3/restrictions/statement_restrictions.cc [hunk 2]
```diff
@@ -871,40 +837,34 @@ bool contains(const data_value& collection, const raw_value_view& value) {
...
 
-/// True iff \p columns has a single element that's a map containing \p key.
-bool contains_key(const std::vector<column_value>& columns, cql3::raw_value_view key, const column_value_eval_bag& bag) {
-    if (columns.size() != 1) {
-        throw exceptions::unsupported_operation_exception("CONTAINS KEY on a tuple");
-    }
-    if (columns[0].sub) {
+/// True iff a column is a map containing \p key.
+bool contains_key(const column_value& col, cql3::raw_value_view key, const column_value_eval_bag& bag) {
+    if (col.sub) {
```
Comment (avikivity) [inline cql3/restrictions/statement_restrictions.cc:855]: That's a nice improvement.

File: cql3/restrictions/statement_restrictions.cc [hunk 3]
```diff
@@ -970,30 +930,6 @@ bool like(const column_value& cv, const bytes_opt& pattern, const column_value_e
     return (pattern && value) ? like_matcher(*pattern)(*value) : false;
 }
 
-/// True iff columns' values match rhs pattern(s) as defined by CQL LIKE.
-bool like(const std::vector<column_value>& columns, term& rhs, const column_value_eval_bag& bag) {
-    if (columns.size() > 1) {
-        if (const auto tup = get_tuple(rhs, bag.options)) {
```
Comment (avikivity) [inline cql3/restrictions/statement_restrictions.cc:954]: What happened to this? (and what does multi-column like mean?)

File: cql3/restrictions/statement_restrictions.cc [hunk 4]
```diff
@@ -1085,23 +1011,35 @@ value_set intersection(value_set a, value_set b, const abstract_type* type) {
...
+            },
+            [&] (const std::vector<column_value>& cvs) {
+                if (*opr.op == operator_type::EQ) {
+                    return equal(*opr.rhs, cvs, bag);
+                } else if (opr.op->is_slice()) {
+                    return limits(cvs, *opr.op, *opr.rhs, bag);
                 } else if (*opr.op == operator_type::IN) {
                     return is_one_of(cvs, *opr.rhs, bag);
                 } else {
-                    throw exceptions::unsupported_operation_exception("Unhandled binary_operator");
```
Comment (avikivity) [inline cql3/restrictions/statement_restrictions.cc:1062]: I see multi-column like is gone.

**Comment by avikivity** [comment]
Looks reasonable.

File: cql3/restrictions/statement_restrictions.cc (hunk 4 above)
Comment (dekimir) [reply cql3/restrictions/statement_restrictions.cc:1062]: Yeah, multi-column LIKE was a fancy generalization that the upstream might allow one day.  We don't need it right now.

**Comment by dekimir** [comment]
> Looks reasonable.

Can it be merged, then? ;)  There are dtest failures waiting on this.

File: cql3/restrictions/statement_restrictions.cc (hunk 4 above)
Comment (avikivity) [reply cql3/restrictions/statement_restrictions.cc:1062]: Is it in any branch? (4.2?)

Comment (dekimir) [reply cql3/restrictions/statement_restrictions.cc:1062]: > Is it in any branch? (4.2?)

No, it's a part of the big rewrite b0698dfb38afacbd3daf8f64ec83e63ba0ce0cd9.

**Comment by avikivity** [comment]
Queued.
