### PR TITLE
Make sure that cache_flat_mutation_reader::do_fill_buffer does not fast forward finished underlying reader

### LINKED ISSUE #8411: "Reader was forwarded before returning partition start" Exception using TWCS in 4.4
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.4.0
Cluster size: 9
OS (RHEL/CentOS/Ubuntu/AWS AMI): Debian

We have a test deployment using 4.4.0 with TWCS for a fairly large table (1 hour time windows). We just upgraded from 4.3.y (separate deployment and transitioned from LCS, so it's a bit difficult to pinpoint if this is new with 4.4 or an TWCS vs LCS issue). We're seeing a high occurrence of backtraces like this:

```
[shard 0] storage_proxy - Exception when communicating with <another_node_ip>, to read from <table>: std::runtime_error (reader was forwarded before returning partition start Backtrace:    0x3c7720e
                                                                                0x3c77680
                                                                                0x3c77a08
                                                                                0x38b8b52
                                                                                0x38b89f6
                                                                                0x38b8910
                                                                                0x38b8794
                                                                                0x38b868f
                                                                                0x13e34d2
                                                                                0x13c5326
                                                                                0x13c2fde
                                                                                0x1175e36
                                                                                0x1177735
                                                                                0x38ed6cf
                                                                                0x38ee8b7
                                                                                0x388c785
                                                                                0x388bba6
                                                                                0xdfa15c
                                                                                /opt/scylladb/libreloc/libc.so.6+0x281e1
                                                                                0xdf704d
                                                                                --------
                                                                                seastar::continuation<seastar::internal::promise_base_with_type<void>, cache::cache_flat_mutation_reader::do_fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}, seastar::future<void>::then_impl_nrvo<{lambda()#1}, seastar::future>({lambda()#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, {lambda()#1}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
                                                                                --------
                                                                                seastar::internal::do_until_state<cache::cache_flat_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#2}, cache::cache_flat_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}>
                                                                                --------
                                                                                seastar::continuation<seastar::internal::promise_base_with_type<seastar::optimized_optional<mutation_fragment> >, flat_mutation_reader::impl::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}, seastar::future<void>::then_impl_nrvo<{lambda()#1}, flat_mutation_reader::impl::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}<seastar::optimized_optional<mutation_fragment> > >({lambda()#1}&&)::{lambda(seastar::internal::promise_base_with_type<seastar::optimized_optional<mutation_fragment> >&&, {lambda()#1}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
                                                                                --------
                                                                                seastar::continuation<seastar::internal::promise_base_with_type<seastar::bool_class<mutation_reader_merger::needs_merge_tag> >, mutation_reader_merger::prepare_one(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3, seastar::future<seastar::optimized_optional<mutation_fragment> >::then_impl_nrvo<mutation_reader_merger::prepare_one(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3, seastar::future<seastar::bool_class<mutation_reader_merger::needs_merge_tag> > >(mutation_reader_merger::prepare_one(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3&&)::{lambda(seastar::internal::promise_base_with_type<seastar::bool_class<mutation_reader_merger::needs_merge_tag> >&&, mutation_reader_merger::prepare_one(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>)::$_3&, seastar::future_state<seastar::optimized_optional<mutation_fragment> >&&)#1}, seastar::optimized_optional<mutation_fragment> >
                                                                                --------
                                                                                N7seastar12continuationINS_8internal22promise_base_with_typeIvEEZNS_6futureINS_10bool_classIN22mutation_reader_merger15needs_merge_tagEEEE14discard_resultEvEUlDpOT_E_ZNS9_14then_impl_nrvoISD_NS4_IvEEEET0_OT_EUlOS3_RSD_ONS_12future_stateIS8_EEE_S8_EE
                                                                                --------
                                                                                seastar::parallel_for_each_state
                                                                                --------
                                                                                seastar::continuation<seastar::internal::promise_base_with_type<void>, mutation_reader_merger::prepare_next(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_1, seastar::future<void>::then_impl_nrvo<mutation_reader_merger::prepare_next(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_1, seastar::future<void> >(mutation_reader_merger::prepare_next(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_1&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, mutation_reader_merger::prepare_next(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_1&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
                                                                                --------
                                                                                seastar::continuation<seastar::internal::promise_base_with_type<boost::iterator_range<mutation_fragment*> >, mutation_reader_merger::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_6, seastar::future<void>::then_impl_nrvo<mutation_reader_merger::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_6, seastar::future<boost::iterator_range<mutation_fragment*> > >(mutation_reader_merger::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_6&&)::{lambda(seastar::internal::promise_base_with_type<boost::iterator_range<mutation_fragment*> >&&, mutation_reader_merger::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_6&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
                                                                                --------
                                                                                seastar::continuation<seastar::internal::promise_base_with_type<void>, mutation_fragment_merger<mutation_reader_merger>::fetch(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(boost::iterator_range<mutation_fragment*>)#1}, seastar::future<boost::iterator_range<mutation_fragment*> >::then_impl_nrvo<{lambda(boost::iterator_range<mutation_fragment*>)#1}, mutation_fragment_merger<mutation_reader_merger>::fetch(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(boost::iterator_range<mutation_fragment*>)#1}<void> >({lambda(boost::iterator_range<mutation_fragment*>)#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, {lambda(boost::iterator_range<mutation_fragment*>)#1}&, seastar::future_state<boost::iterator_range<mutation_fragment*> >&&)#1}, boost::iterator_range<mutation_fragment*> >
                                                                                --------
                                                                                seastar::continuation<seastar::internal::promise_base_with_type<seastar::optimized_optional<mutation_fragment> >, mutation_fragment_merger<mutation_reader_merger>::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}, seastar::future<void>::then_impl_nrvo<{lambda()#1}, mutation_fragment_merger<mutation_reader_merger>::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}<seastar::optimized_optional<mutation_fragment> > >({lambda()#1}&&)::{lambda(seastar::internal::promise_base_with_type<seastar::optimized_optional<mutation_fragment> >&&, {lambda()#1}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
                                                                                --------
                                                                                seastar::continuation<seastar::internal::promise_base_with_type<seastar::bool_class<seastar::stop_iteration_tag> >, merging_reader<mutation_reader_merger>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}::operator()() const::{lambda(seastar::optimized_optional<mutation_fragment>)#1}, seastar::future<mutation_fragment>::then_impl_nrvo<seastar::optimized_optional<mutation_fragment>, {lambda(seastar::optimized_optional<mutation_fragment>)#1}<seastar::bool_class<seastar::stop_iteration_tag> > >(seastar::optimized_optional<mutation_fragment>&&)::{lambda(seastar::internal::promise_base_with_type<seastar::bool_class<seastar::stop_iteration_tag> >&&, seastar::optimized_optional<mutation_fragment>&, seastar::future_state<mutation_fragment>&&)#1}, mutation_fragment>
                                                                                --------
                                                                                seastar::internal::repeater<merging_reader<mutation_reader_merger>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}>
                                                                                --------
                                                                                seastar::continuation<seastar::internal::promise_base_with_type<mutation_fragment*>, flat_mutation_reader::peek(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}, seastar::future<void>::then_impl_nrvo<{lambda()#1}, flat_mutation_reader::peek(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}<mutation_fragment*> >({lambda()#1}&&)::{lambda(seastar::internal::promise_base_with_type<mutation_fragment*>&&, {lambda()#1}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
                                                                                --------
                                                                                seastar::continuation<seastar::internal::promise_base_with_type<std::tuple<std::optional<clustering_key_prefix> > >, query::consume_page<(emit_only_live_rows)1, query_result_builder>(flat_mutation_reader&, seastar::lw_shared_ptr<compact_mutation_state<(emit_only_live_rows)1, (compact_for_sstables)0> >, query::partition_slice const&, query_result_builder&&, unsigned long, unsigned int, std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, query::max_result_size)::{lambda(mutation_fragment*)#1}, seastar::future<mutation_fragment*>::then_impl_nrvo<{lambda(mutation_fragment*)#1}, query::consume_page<(emit_only_live_rows)1, query_result_builder>(flat_mutation_reader&, seastar::lw_shared_ptr<compact_mutation_state<(emit_only_live_rows)1, (compact_for_sstables)0> >, query::partition_slice const&, query_result_builder&&, unsigned long, unsigned int, std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, query::max_result_size)::{lambda(mutation_fragment*)#1}<std::tuple<std::optional<clustering_key_prefix> > > >({lambda(mutation_fragment*)#1}&&)::{lambda(seastar::internal::promise_base_with_type<std::tuple<std::optional<clustering_key_prefix> > >&&, {lambda(mutation_fragment*)#1}&, seastar::future_state<mutation_fragment*>&&)#1}, mutation_fragment*>
                                                                                --------
                                                                                seastar::continuation<seastar::internal::promise_base_with_type<void>, query::querier<(emit_only_live_rows)1>::consume_page<query_result_builder>(query_result_builder&&, unsigned long, unsigned int, std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, query::max_result_size)::{lambda(auto:1&&)#1}, seastar::future<std::tuple<std::optional<clustering_key_prefix> > >::then_impl_nrvo<{lambda(auto:1&&)#1}, query::querier<(emit_only_live_rows)1>::consume_page<query_result_builder>(query_result_builder&&, unsigned long, unsigned int, std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, query::max_result_size)::{lambda(auto:1&&)#1}<void> >(query_result_builder&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, {lambda(auto:1&&)#1}&, seastar::future_state<std::optional<clustering_key_prefix> >&&)#1}, std::optional<clustering_key_prefix> >
                                                                                --------
                                                                                seastar::continuation<seastar::internal::promise_base_with_type<void>, data_query(seastar::lw_shared_ptr<schema const>, mutation_source const&, nonwrapping_interval<dht::ring_position> const&, query::partition_slice const&, unsigned long, unsigned int, std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >, query::result::builder&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, query::query_class_config, tracing::trace_state_ptr, query::querier_cache_context)::$_25::operator()(query::querier<(emit_only_live_rows)1>&)::{lambda()#1}, seastar::future<void>::then_impl_nrvo<{lambda()#1}, seastar::future>({lambda()#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, {lambda()#1}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
                                                                             )
                                                                             
```

How should we go about debugging this further?

Thanks!

### LINKED ISSUE #8435: `cache_flat_mutation_reader` position-fast-forwards readers that are not inside a partition, if they immediately return eof
The documentation for `flat_mutation_reader::fast_forward_to(position_range, ...)` says:
```cpp
    // `fast_forward_to` can be called only when the reader is within a partition
    // and it affects the set of fragments returned from that partition.
    // In particular one must first enter a partition by fetching a `partition_start`
    // fragment before calling `fast_forward_to`.
```
However, `cache_flat_mutation_reader` does not conform to this spec.

Steps to  catch the bug:
1. Apply the fix from PR #8433 because the bug fixed there masks this issue...
2. Create a single node cluster
3. `cqlsh> create keyspace ks with replication = {'class': 'SimpleStrategy', 'replication_factor': 1};`
4. `cqlsh> create table ks.t (pk int, ck int, primary key (pk, ck)) with compaction = {'class': 'TimeWindowCompactionStrategy'} and bloom_filter_fp_chance = 1;`
5. `cqlsh> insert into ks.t (pk, ck) values (0, 1);`
6. `nodetool flush`
7. `cqlsh> insert into ks.t (pk, ck) values (1, 0);`
8. `nodetool flush`
9. restart the node
10. `select * from ks.t where pk = 1 and ck = 0;`
11. `select * from ks.t where pk = 1 and ck = 1;`

Result:
```
storage_proxy - Exception when communicating with 127.0.0.1, to read from ks.t: seastar::internal::backtraced<std::runtime_error> (reader was forwarded before returning partition start Backtrace: 0x262d6bb 0x262d63a 0x262daa0 0x262dcf8 0x1b55ad2 0x1b558d6 0x24088fe 0x2408569 0x24083af 0x11a1aa2 0x119db05 0x119426b 0x11983f1 0x1198171 0x1196ade 0x1081e10 0x10824e2 0xec1947 0x108215b 0x1072a7d 0x10725e9 0x10726e4 0x116eccb 0x11954eb 0x1195376 0x119514a 0x1194768 0x1126a8f 0x1126784 0x11265b7 0x1106241 0x1100fc2 0xfe3559 0xfe301b 0x100f581 0xfca01d 0xf9a570 0xf9a477 0xf80787 0xfa5216 0xfa50e3 0xf80787 0xf8064a 0xf80063 0x23d14db 0x23d149b 0x23d143a 0x2434ede 0x24359df 0x2436397 0x23c5537 0x23c518a 0xe4ed41 /lib64/libc.so.6+0x27041 0xe4dc6d
   --------
   seastar::lambda_task<seastar::execution_stage::flush()::$_5>)
```

Relevant part of the backtrace:
```
seastar::on_internal_error(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at on_internal_error.cc:?                                                                                                                                                                                                 clustering_order_reader_merger::fast_forward_to(position_range, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at mutation_reader.cc:?                                                                                                                                 merging_reader<clustering_order_reader_merger>::fast_forward_to(position_range, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at mutation_reader.cc:?                                                                                                                 flat_mutation_reader::fast_forward_to(position_range, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at mutation_reader.cc:?
restricting_mutation_reader::fast_forward_to(position_range, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(flat_mutation_reader&)#1}::operator()(flat_mutation_reader&) at mutation_reader.cc:?                                                              decltype(auto) restricting_mutation_reader::with_reader<restricting_mutation_reader::fast_forward_to(position_range, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(flat_mutation_reader&)#1}>(restricting_mutation_reader::fast_forward_to(position_range, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda(flat_mutation_reader&)#1}, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at mutation_reader.cc:?                                                         restricting_mutation_reader::fast_forward_to(position_range, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at mutation_reader.cc:?                                                                                                                                    cache::cache_flat_mutation_reader::do_fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at row_cache.cc:?                                                                                                                                                     _ZN7seastar20noncopyable_functionIFNS_6futureIvEEvEE17direct_vtable_forIZNS2_4thenIZN5cache26cache_flat_mutation_reader14do_fill_bufferENSt6chrono10time_pointINS_12lowres_clockENS9_8durationIlSt5ratioILl1ELl1000EEEEEEEUlvE_S2_EET0_OT_EUlDpOT_E_E4callEPKS4_ at row_cache.cc:?                                            seastar::future<void> seastar::future<void>::then_impl<seastar::noncopyable_function<seastar::future<void> ()>, seastar::future<void> >(seastar::noncopyable_function<seastar::future<void> ()>&&) at main.cc:?
cache::cache_flat_mutation_reader::do_fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at row_cache.cc:?                                                                                                                                                     seastar::future<void> seastar::do_until<cache::cache_flat_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}, cache::cache_flat_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duratio
n<long, std::ratio<1l, 1000l> > >)::{lambda()#2}>(cache::cache_flat_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#2}, cache::cache_flat_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chron
o::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}) at row_cache.cc:?                                                                                                                                                                                                                                                 
cache::cache_flat_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at row_cache.cc:?
cache::cache_flat_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at row_cache.cc:?
```

This is most probably the root cause of #8411.

What happens in the reproducer:
1. We create two sstables: one contains the partition `0`, the other doesn't but contains the ck `1` in a different partition.
2. The first `select` pulls the contents of the first sstable into cache.
3. The second `select` causes Scylla to find an entry for partition `0` in the cache and start reading from the cache. However it then moves to an underlying sstable reader (`cache_flat_mutation_reader::start_reading_from_underlying()`); the underlying sstable reader is created by `time_series_sstable_set::create_single_key_sstable_reader`, which uses the `clustering_order_reader_merger` underneath. Also this special reader does clustering key filtering which is important to catch the bug. Also this special reader merger actually asserts for the property mentioned at the beginning, causing the bug to be catched.
4. The underlying reader reads from the second sstable which does not contain partition `0` (and only from that sstable due to the ck filtering) but passed the bloom filter because `bloom_filter_fp_chance = 1` (note it is possible to reproduce with normal values of `bloom_filter_fp_chance` but we would need this sstable to contain a large number of partitions).
5. We start reading from the underlying reader in `cache_flat_mutation_reader::do_fill_buffer` and do this:
```cpp
        return _underlying->fast_forward_to(position_range{_lower_bound, std::move(end)}, timeout).then([this, timeout] {
            return read_from_underlying(timeout);
        });
```
this position-fast-forwards the reader, but we are not inside any partition (it did not return `partition_start` fragment for partition `0` because this sstable does not have it), causing the underlying `clustering_order_reader_merger` to throw an error.


cc @haaawk @tgrabiec

### PR DESCRIPTION
**Pull request by haaawk**
It is possible that a partition is in cache but is not present in sstables that are underneath.
In such case:
1. cache_flat_mutation_reader will fast forward underlying reader to that partition
2. The underlying reader will enter the state when it's empty and its is_end_of_stream() returns true
3. Previously cache_flat_mutation_reader::do_fill_buffer would try to fast forward such empty underlying reader
4. This PR fixes that

Test: unit(dev)

Fixes #8435 
Fixes #8411

### CODE REVIEW

**Comment by kbr-** [comment]
I checked that with this fix rebased on top of #8433 the reproducer described in #8435 no longer works.

File: cache_flat_mutation_reader.hh [hunk 1]
```diff
@@ -275,8 +275,16 @@ future<> cache_flat_mutation_reader::do_fill_buffer(db::timeout_clock::time_poin
             }
         };
         if (!_underlying) {
-            return ensure_underlying(read_context::skip_first_fragment_t::yes, timeout).then([this, timeout] (read_context::created_new_underlying_t){
-                return do_fill_buffer(timeout);
+            return ensure_underlying(read_context::skip_first_fragment_t::no, timeout).then([this, timeout, prepare_underlying = std::move(prepare_underlying)] (read_context::created_new_underlying_t created_new_underlying) mutable {
```
Comment (tgrabiec) [inline cache_flat_mutation_reader.hh:278]: I think it would be overall simpler if we put this logic in read_context. We add a flag `read_context::partition_exists_in_underlying()`, and the impl of `ensure_underlying()` and `create_underlying()` would set it. 

Then, this layer doesn't have to deal with the details of whether the underlying is reused or not.

Something like this:
```diff
diff --git a/cache_flat_mutation_reader.hh b/cache_flat_mutation_reader.hh
index 54a578c60b..b11d214536 100644
--- a/cache_flat_mutation_reader.hh
+++ b/cache_flat_mutation_reader.hh
@@ -267,6 +267,9 @@ future<> cache_flat_mutation_reader::do_fill_buffer(db::timeout_clock::time_poin
         }
         _state = state::reading_from_underlying;
         _population_range_starts_before_all_rows = _lower_bound.is_before_all_clustered_rows(*_schema);
+        if (!_read_context->partition_exists()) {
+            return read_from_underlying(timeout);
+        }
         auto end = _next_row_in_range ? position_in_partition(_next_row.position())
                                       : position_in_partition(_upper_bound);
         return _underlying->fast_forward_to(position_range{_lower_bound, std::move(end)}, timeout).then([this, timeout] {
diff --git a/read_context.hh b/read_context.hh
index 29010618cf..7170b7486d 100644
--- a/read_context.hh
+++ b/read_context.hh
@@ -137,6 +137,7 @@ class read_context final : public enable_lw_shared_from_this<read_context> {
     //     are set so that _underlying_flat can be fast forwarded to the right partition.
     //
     autoupdating_underlying_reader _underlying;
+    bool _partition_exists;
     uint64_t _underlying_created = 0;
 
     mutation_source_opt _underlying_snapshot;
@@ -190,13 +191,19 @@ class read_context final : public enable_lw_shared_from_this<read_context> {
     autoupdating_underlying_reader& underlying() { return _underlying; }
     row_cache::phase_type phase() const { return _phase; }
     const dht::decorated_key& key() const { return *_key; }
+    bool partition_exists() const { return _partition_exists; }
     void on_underlying_created() { ++_underlying_created; }
     bool digest_requested() const { return _slice.options.contains<query::partition_slice::option::with_digest>(); }
 public:
     future<> ensure_underlying(db::timeout_clock::time_point timeout) {
         if (_underlying_snapshot) {
-            return create_underlying(true, timeout);
+            return create_underlying(false, timeout).then([this] {
+                return _underlying.underlying()(timeout).then([this](auto&& mfopt) {
+                    _partition_exists = bool(mfopt);
+                });
+            })
         }
+        _partition_exists = true;
         return make_ready_future<>();
     }
 public:

```

**Review by tgrabiec — CHANGES_REQUESTED** [review]

File: cache_flat_mutation_reader.hh (hunk 1 above)
Comment (haaawk) [reply cache_flat_mutation_reader.hh:278]: I agree that the patch is smaller then but I'm not a fan of adding semi-global state when the same information can go through a regular function param/return value path. read_context lifetime is much longer than the call to do_fill_buffer. When we add state to read_context we're leaking complexity from a localised scope of function calls stack/chain to much broader scope of cache_flat_mutation_reader lifetime.

In general, I think we should avoid state and side effects when possible because it (avoiding state and side effects) makes the code cleaner and easier to understand. Having a use case specific logic `L` that requires some input data `I`, I think :
```
I input = shared_object_with_much_longer_lifetime.function_with_limited_side_effects();
<input being returned from 2 levels of stack/function calls>
auto result = L(input);
```
is cleaner/easier to understand than:
```
shared_object_with_much_longer_lifetime.function_with_side_effect_that_applies_L_to_I_and_saves_the_state();
<2 levels of stack/function calls>
auto result = shared_object_with_much_longer_lifetime.get_state_with_result_of_L_applied_to_I();
```

I know that `read_context::ensure_underlying` is not a pure function but adding even more state makes it even less pure. The more pure the function the better in general because it's easier to reason about functions that take input returns output and doesn't have side effects. So I think that it's better to keep `read_context::ensure_underlying` side effects to the minimum. The fact that it sometimes creates the underlying as a side effect is somehow understandable/expected from its name.

So I guess my argument is that `was_underlying_created read_context::ensure_underlying(...)` is easy to understand by just looking at a declaration. While the relation between `void read_context::ensure_underlying(...)` and `bool read_context::partition_exists()` needs to be discovered by reading the implementation so I think it's a less useful abstraction that is more demanding on the reader that tries to understand what's going on.

Comment (haaawk) [reply cache_flat_mutation_reader.hh:278]: BTW I see your point about exposing whether underlying was reused or not but:
1. figuring out that partition exists or not in underlying is at the moment needed in just one use case so I think it's better to keep the logic where it's needed than pushing it into shared object and extending the scope it lives in.
2. I find it less complex to expose this instead of adding a state to a shared object with much longer lifetime

Comment (haaawk) [reply cache_flat_mutation_reader.hh:278]: I think there's a hybrid approach possible that avoids both new state and exposition of internals of ensure_underlying. Will post a draft today/tomorrow.

Comment (haaawk) [reply cache_flat_mutation_reader.hh:278]: Here's how a hybrid approach would work: https://github.com/scylladb/scylla/compare/master...haaawk:fix_cache_flat_mutation_reader_alternative

It encapsulates the logic that checks underlying being in non-existent partition into read_context but at the same time does not introduce more state. @tgrabiec what do you think?

Comment (tgrabiec) [reply cache_flat_mutation_reader.hh:278]: > Here's how a hybrid approach would work: [master...haaawk:fix_cache_flat_mutation_reader_alternative](https://github.com/scylladb/scylla/compare/master...haaawk:fix_cache_flat_mutation_reader_alternative)
> 

This hybrid approach looks better than the previous one.

I think there is a problem with it (and with the previous one), that I didn't mention. It's not enough to inhibit f_f_t() at the time we create the underlying. If there is no partition in the underlying, we must not f_f_t() each time we try to read from this partition, even if the underlying reader is ensured for the current partition. So we need to record partition_exists somewhere.

I don't accept the criticism of adding state to read_context. It's true that stateless is in general better than stateful, however, in this case we do need to hold the state. What we need is a cursor over partitions, and part of read_context state is for implementing this cursor. ensure_underlying() makes sure the cursor is valid for the current partition. We already have state for the current partition there (e.g. `read_context::_key`). Adding more state would be in line with this design.

Comment (haaawk) [reply cache_flat_mutation_reader.hh:278]: > I think there is a problem with it (and with the previous one), that I didn't mention. It's not enough to inhibit f_f_t() at the time we create the underlying. If there is no partition in the underlying, we must not f_f_t() each time we try to read from this partition, even if the underlying reader is ensured for the current partition. So we need to record partition_exists somewhere.

Ok. I get your point. If you have started with that I wouldn't have wasted time fighting the inevitable :)

I will rework the PR.

Comment (haaawk) [reply cache_flat_mutation_reader.hh:278]: > I don't accept the criticism of adding state to read_context. It's true that stateless is in general better than stateful, however, in this case we do need to hold the state. What we need is a cursor over partitions, and part of read_context state is for implementing this cursor. ensure_underlying() makes sure the cursor is valid for the current partition. We already have state for the current partition there (e.g. `read_context::_key`). Adding more state would be in line with this design.

The criticism was about adding a state to make the code simpler. When the state is needed for correctness then it's a whole different story.

**Comment by haaawk** [comment]
I reworked the PR according to @tgrabiec directions.

**Comment by tgrabiec** [comment]
Looks very nice, thanks!
