### PR TITLE
streaming: make_streaming_consumer: close reader on errors

### LINKED ISSUE #8776: [flat_mutation_reader - 12queue_reader] permit drop_table_during_repair_ks_6.standard1:repair-meta: was not closed before destruction
*Installation details*
Kernel version: `5.4.0-1035-aws`
Scylla version (or git commit hash): `4.6.dev-0.20210526.72cc59684 with build-id 143904870d237d353528af679d937336272cc0b8`
Cluster size: 6 nodes (i3.4xlarge)
Scylla running with shards number (live nodes):
   longevity-tls-50gb-3d-master-db-node-1164cbe2-1 (13.48.13.123 | 10.0.3.116): 14 shards
   longevity-tls-50gb-3d-master-db-node-1164cbe2-3 (13.48.70.5 | 10.0.1.118): 14 shards
   longevity-tls-50gb-3d-master-db-node-1164cbe2-5 (13.48.48.29 | 10.0.0.254): 14 shards
   longevity-tls-50gb-3d-master-db-node-1164cbe2-6 (13.51.156.192 | 10.0.0.241): 14 shards
   longevity-tls-50gb-3d-master-db-node-1164cbe2-8 (13.49.80.189 | 10.0.3.101): 14 shards
   longevity-tls-50gb-3d-master-db-node-1164cbe2-9 (13.48.106.60 | 10.0.3.248): 14 shards
Scylla running with shards number (terminated nodes):
   longevity-tls-50gb-3d-master-db-node-1164cbe2-4 (13.51.64.29 | 10.0.3.243): 14 shards
   longevity-tls-50gb-3d-master-db-node-1164cbe2-2 (13.51.237.235 | 10.0.1.31): 14 shards
   longevity-tls-50gb-3d-master-db-node-1164cbe2-7 (13.51.167.140 | 10.0.0.226): 14 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-03b0daeb661454793` (aws: eu-north-1)

Test: `longevity-50gb-3days`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/27b59253648831cba683ba58818a8fb4791a5b64/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)

**Issue description**

Node 6 crashed during drop table when repair in progress and caused coredump and corruption in the commitlog.
```
May 28 20:05:59 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[359539]:  [shard 11] compaction - [Compact keyspace1.standard1 1ea9c1b0-bff0-11eb-b72c-36770b68b051] Compacting [/var/lib/scylla/data/keyspace1/standard1
-8279fa50bf6b11eb8d596879517fb126/md-23867-big-Data.db:level=0:origin=compaction, /var/lib/scylla/data/keyspace1/standard1-8279fa50bf6b11eb8d596879517fb126/md-21963-big-Data.db:level=0:origin=compaction, ]
May 28 20:06:16 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[359539]:  [shard 0] compaction - [Compact system_schema.columns 292af730-bff0-11eb-a253-366c0b68b051] Compacting [/var/lib/scylla/data/system_schema/colu
mns-24101c25a2ae3af787c1b40ee1aca33f/md-12838-big-Data.db:level=0:origin=memtable, /var/lib/scylla/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/md-12824-big-Data.db:level=0:origin=compaction, ]
May 28 20:06:16 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[359539]:  [shard 6] schema_tables - Dropping drop_table_during_repair_ks_6.standard1 id=3e39ecb0-bfed-11eb-beda-27a6e03f5fc9 version=c114a702-fbd3-3622-a
c71-c1a2e6e709c3
May 28 20:06:16 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[359539]:  [shard 10] flat_mutation_reader - 12queue_reader [0x60a00c23c620]: permit drop_table_during_repair_ks_6.standard1:repair-meta: was not closed before destruction, at: 0x447242e 0x44728d0 0x4472c78 0x40a1313 0x156a938 0x3402131 0x35ce9cd 0x40d64bf 0x40d7747 0x40f61cb 0x40a1c3a /opt/scylladb/libreloc/libpthread.so.0+0x93f8 /opt/scylladb/libreloc/libc.so.6+0x101902
                                                                                   --------
                                                                                   seastar::continuation<seastar::internal::promise_base_with_type<void>, mutation_writer::shard_writer::consume()::$_0, seastar::future<mutation_fragment*>::then_impl_nrvo<mutation_writer::shard_writer::consume()::$_0, seastar::future<void> >(mutation_writer::shard_writer::consume()::$_0&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, mutation_writer::shard_writer::consume()::$_0&, seastar::future_state<mutation_fragment*>&&)#1}, mutation_fragment*>
                                                                                   --------
                                                                                   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::future<void>::finally_body<seastar::smp::submit_to<mutation_writer::multishard_writer::consume(unsigned int)::$_12>(unsigned int, seastar::smp_submit_to_options, mutation_writer::multishard_writer::consume(unsigned int)::$_12&&)::{lambda()#1}, false>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::smp::submit_to<mutation_writer::multishard_writer::consume(unsigned int)::$_12>(unsigned int, seastar::smp_submit_to_options, mutation_writer::multishard_writer::consume(unsigned int)::$_12&&)::{lambda()#1}>(seastar::smp::submit_to<mutation_writer::multishard_writer::consume(unsigned int)::$_12>(unsigned int, seastar::smp_submit_to_options, mutation_writer::multishard_writer::consume(unsigned int)::$_12&&)::{lambda()#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::smp::submit_to<mutation_writer::multishard_writer::consume(unsigned int)::$_12>(unsigned int, seastar::smp_submit_to_options, auto:1&&)::{lambda()#1}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
                                                                                   --------
                                                                                   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::future<void>::handle_exception<mutation_writer::multishard_writer::consume(unsigned int)::$_13>(mutation_writer::multishard_writer::consume(unsigned int)::$_13&&)::{lambda(auto:1&&)#1}, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, {lambda(auto:1&&)#1}>({lambda(auto:1&&)#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, {lambda(auto:1&&)#1}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
May 28 20:06:16 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[359539]: Aborting on shard 10.
May 28 20:06:16 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[359539]: Backtrace:
May 28 20:06:16 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[359539]:   0x40c35c8
May 28 20:06:16 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[359539]:   0x40f5c82
May 28 20:06:16 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[359539]:   0x7f56434dd1df
May 28 20:06:16 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[359539]:   /opt/scylladb/libreloc/libc.so.6+0x3d9d4
May 28 20:06:16 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[359539]:   /opt/scylladb/libreloc/libc.so.6+0x268a3
May 28 20:06:16 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[359539]:   0x40a1391
May 28 20:06:16 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[359539]:   0x156a938
May 28 20:06:16 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[359539]:   0x3402131
May 28 20:06:16 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[359539]:   0x35ce9cd
May 28 20:06:16 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[359539]:   0x40d64bf
May 28 20:06:16 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[359539]:   0x40d7747
May 28 20:06:16 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[359539]:   0x40f61cb
May 28 20:06:16 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[359539]:   0x40a1c3a
May 28 20:06:16 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[359539]:  /opt/scylladb/libreloc/libpthread.so.0+0x93f8
May 28 20:06:16 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[359539]:   /opt/scylladb/libreloc/libc.so.6+0x101902
May 28 20:09:33 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[474335]: Scylla version 4.6.dev-0.20210526.72cc59684 with build-id 143904870d237d353528af679d937336272cc0b8 starting ...
May 28 20:09:33 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[474335]: command used: "/usr/bin/scylla --blocked-reactor-notify-ms 100 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --abort-on-ebadf 1 --enable-sstable-key-validation 1 --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 1-7,9-15 --lock-memory=1"

```

Decoded backtrace `Aborting on shard 10.`
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:766
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:796
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:808
 (inlined by) seastar::sigabrt_action() at ./build/release/seastar/./seastar/src/core/reactor.cc:3573
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3555
 (inlined by) __invoke at ./build/release/seastar/./seastar/src/core/reactor.cc:3551
?? ??:0
?? ??:0
?? ??:0
seastar::on_internal_error_noexcept(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at ./build/release/seastar/./seastar/src/core/on_internal_error.cc:57
~flat_mutation_reader at ./flat_mutation_reader.cc:57
seastar::future<void> std::__invoke_impl<seastar::future<void>, repair_writer::create_writer(seastar::sharded<database>&, seastar::sharded<db::system_distributed_keyspace>&, seastar::sharded<db::view::view_update_generator>&)::{lambda(flat_mutation_reader)#1}&, flat_mutation_reader>(std::__invoke_other, repair_writer::create_writer(seastar::sharded<database>&, seastar::sharded<db::system_distributed_keyspace>&, seastar::sharded<db::view::view_update_generator>&)::{lambda(flat_mutation_reader)#1}&, flat_mutation_reader&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
 (inlined by) std::enable_if<is_invocable_r_v<seastar::future<void>, repair_writer::create_writer(seastar::sharded<database>&, seastar::sharded<db::system_distributed_keyspace>&, seastar::sharded<db::view::view_update_generator>&)::{lambda(flat_mutation_reader)#1}&, flat_mutation_reader>, std::enable_if>::type std::__invoke_r<seastar::future<void>, repair_writer::create_writer(seastar::sharded<database>&, seastar::sharded<db::system_distributed_keyspace>&, seastar::sharded<db::view::view_update_generator>&)::{lambda(flat_mutation_reader)#1}&, flat_mutation_reader>(seastar::future<void>&&, (repair_writer::create_writer(seastar::sharded<database>&, seastar::sharded<db::system_distributed_keyspace>&, seastar::sharded<db::view::view_update_generator>&)::{lambda(flat_mutation_reader)#1}&)...) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:113
 (inlined by) std::_Function_handler<seastar::future<void> (flat_mutation_reader), repair_writer::create_writer(seastar::sharded<database>&, seastar::sharded<db::system_distributed_keyspace>&, seastar::sharded<db::view::view_update_generator>&)::{lambda(flat_mutation_reader)#1}>::_M_invoke(std::_Any_data const&, flat_mutation_reader&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:291
std::function<seastar::future<void> (flat_mutation_reader)>::operator()(flat_mutation_reader) const at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:622
 (inlined by) operator() at ./mutation_writer/multishard_writer.cc:94
 (inlined by) seastar::future<void> std::__invoke_impl<seastar::future<void>, mutation_writer::shard_writer::consume()::$_0&, mutation_fragment*>(std::__invoke_other, mutation_writer::shard_writer::consume()::$_0&, mutation_fragment*&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
 (inlined by) std::__invoke_result<mutation_writer::shard_writer::consume()::$_0&, mutation_fragment*>::type std::__invoke<mutation_writer::shard_writer::consume()::$_0&, mutation_fragment*>(mutation_writer::shard_writer::consume()::$_0&, mutation_fragment*&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:95
 (inlined by) std::invoke_result<mutation_writer::shard_writer::consume()::$_0&, mutation_fragment*>::type std::invoke<mutation_writer::shard_writer::consume()::$_0&, mutation_fragment*>(mutation_writer::shard_writer::consume()::$_0&, mutation_fragment*&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/functional:88
 (inlined by) auto seastar::internal::future_invoke<mutation_writer::shard_writer::consume()::$_0&, mutation_fragment*>(mutation_writer::shard_writer::consume()::$_0&, mutation_fragment*&&) at ././seastar/include/seastar/core/future.hh:1211
 (inlined by) operator() at ././seastar/include/seastar/core/future.hh:1582
 (inlined by) void seastar::futurize<seastar::future<void> >::satisfy_with_result_of<seastar::future<mutation_fragment*>::then_impl_nrvo<mutation_writer::shard_writer::consume()::$_0, seastar::future<void> >(mutation_writer::shard_writer::consume()::$_0&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, mutation_writer::shard_writer::consume()::$_0&, seastar::future_state<mutation_fragment*>&&)#1}::operator()(seastar::internal::promise_base_with_type<void>&&, mutation_writer::shard_writer::consume()::$_0&, seastar::future_state<mutation_fragment*>&&) const::{lambda()#1}>(seastar::internal::promise_base_with_type<void>&&, mutation_writer::shard_writer::consume()::$_0&&) at ././seastar/include/seastar/core/future.hh:2120
 (inlined by) operator() at ././seastar/include/seastar/core/future.hh:1575
 (inlined by) seastar::continuation<seastar::internal::promise_base_with_type<void>, mutation_writer::shard_writer::consume()::$_0, seastar::future<mutation_fragment*>::then_impl_nrvo<mutation_writer::shard_writer::consume()::$_0, seastar::future<void> >(mutation_writer::shard_writer::consume()::$_0&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, mutation_writer::shard_writer::consume()::$_0&, seastar::future_state<mutation_fragment*>&&)#1}, mutation_fragment*>::run_and_dispose() at ././seastar/include/seastar/core/future.hh:767
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2240
 (inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:2649
seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2808
operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:4004
 (inlined by) void std::__invoke_impl<void, seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&>(std::__invoke_other, seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
 (inlined by) std::enable_if<is_invocable_r_v<void, seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&>, void>::type std::__invoke_r<void, seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&>(seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:110
 (inlined by) std::_Function_handler<void (), seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97>::_M_invoke(std::_Any_data const&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:291
std::function<void ()>::operator()() const at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:622
 (inlined by) seastar::posix_thread::start_routine(void*) at ./build/release/seastar/./seastar/src/core/posix.cc:60
?? ??:0
?? ??:0

```
Decoded backtrace from:
`shard 10] flat_mutation_reader - 12queue_reader [0x60a00c23c620]: permit drop_table_during_repair_ks_6.standard1:repair-meta: was not closed b
efore destruction, at: `

```
void seastar::backtrace<seastar::current_backtrace_tasklocal()::$_3>(seastar::current_backtrace_tasklocal()::$_3&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::current_backtrace_tasklocal() at ./build/release/seastar/./seastar/src/util/backtrace.cc:86
seastar::current_tasktrace() at ./build/release/seastar/./seastar/src/util/backtrace.cc:137
seastar::current_backtrace() at ./build/release/seastar/./seastar/src/util/backtrace.cc:170
seastar::on_internal_error_noexcept(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at ./build/release/seastar/./seastar/src/core/on_internal_error.cc:55
~flat_mutation_reader at ./flat_mutation_reader.cc:57
seastar::future<void> std::__invoke_impl<seastar::future<void>, repair_writer::create_writer(seastar::sharded<database>&, seastar::sharded<db::system_distributed_keyspace>&, seastar::sharded<db::view::view_update_generator>&)::{lambda(flat_mutation_reader)#1}&, flat_mutation_reader>(std::__invoke_other, repair_writer::create_writer(seastar::sharded<database>&, seastar::sharded<db::system_distributed_keyspace>&, seastar::sharded<db::view::view_update_generator>&)::{lambda(flat_mutation_reader)#1}&, flat_mutation_reader&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
 (inlined by) std::enable_if<is_invocable_r_v<seastar::future<void>, repair_writer::create_writer(seastar::sharded<database>&, seastar::sharded<db::system_distributed_keyspace>&, seastar::sharded<db::view::view_update_generator>&)::{lambda(flat_mutation_reader)#1}&, flat_mutation_reader>, std::enable_if>::type std::__invoke_r<seastar::future<void>, repair_writer::create_writer(seastar::sharded<database>&, seastar::sharded<db::system_distributed_keyspace>&, seastar::sharded<db::view::view_update_generator>&)::{lambda(flat_mutation_reader)#1}&, flat_mutation_reader>(seastar::future<void>&&, (repair_writer::create_writer(seastar::sharded<database>&, seastar::sharded<db::system_distributed_keyspace>&, seastar::sharded<db::view::view_update_generator>&)::{lambda(flat_mutation_reader)#1}&)...) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:113
 (inlined by) std::_Function_handler<seastar::future<void> (flat_mutation_reader), repair_writer::create_writer(seastar::sharded<database>&, seastar::sharded<db::system_distributed_keyspace>&, seastar::sharded<db::view::view_update_generator>&)::{lambda(flat_mutation_reader)#1}>::_M_invoke(std::_Any_data const&, flat_mutation_reader&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:291
std::function<seastar::future<void> (flat_mutation_reader)>::operator()(flat_mutation_reader) const at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:622
 (inlined by) operator() at ./mutation_writer/multishard_writer.cc:94
 (inlined by) seastar::future<void> std::__invoke_impl<seastar::future<void>, mutation_writer::shard_writer::consume()::$_0&, mutation_fragment*>(std::__invoke_other, mutation_writer::shard_writer::consume()::$_0&, mutation_fragment*&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
 (inlined by) std::__invoke_result<mutation_writer::shard_writer::consume()::$_0&, mutation_fragment*>::type std::__invoke<mutation_writer::shard_writer::consume()::$_0&, mutation_fragment*>(mutation_writer::shard_writer::consume()::$_0&, mutation_fragment*&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:95
 (inlined by) std::invoke_result<mutation_writer::shard_writer::consume()::$_0&, mutation_fragment*>::type std::invoke<mutation_writer::shard_writer::consume()::$_0&, mutation_fragment*>(mutation_writer::shard_writer::consume()::$_0&, mutation_fragment*&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/functional:88
 (inlined by) auto seastar::internal::future_invoke<mutation_writer::shard_writer::consume()::$_0&, mutation_fragment*>(mutation_writer::shard_writer::consume()::$_0&, mutation_fragment*&&) at ././seastar/include/seastar/core/future.hh:1211
 (inlined by) operator() at ././seastar/include/seastar/core/future.hh:1582
 (inlined by) void seastar::futurize<seastar::future<void> >::satisfy_with_result_of<seastar::future<mutation_fragment*>::then_impl_nrvo<mutation_writer::shard_writer::consume()::$_0, seastar::future<void> >(mutation_writer::shard_writer::consume()::$_0&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, mutation_writer::shard_writer::consume()::$_0&, seastar::future_state<mutation_fragment*>&&)#1}::operator()(seastar::internal::promise_base_with_type<void>&&, mutation_writer::shard_writer::consume()::$_0&, seastar::future_state<mutation_fragment*>&&) const::{lambda()#1}>(seastar::internal::promise_base_with_type<void>&&, mutation_writer::shard_writer::consume()::$_0&&) at ././seastar/include/seastar/core/future.hh:2120
 (inlined by) operator() at ././seastar/include/seastar/core/future.hh:1575
 (inlined by) seastar::continuation<seastar::internal::promise_base_with_type<void>, mutation_writer::shard_writer::consume()::$_0, seastar::future<mutation_fragment*>::then_impl_nrvo<mutation_writer::shard_writer::consume()::$_0, seastar::future<void> >(mutation_writer::shard_writer::consume()::$_0&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, mutation_writer::shard_writer::consume()::$_0&, seastar::future_state<mutation_fragment*>&&)#1}, mutation_fragment*>::run_and_dispose() at ././seastar/include/seastar/core/future.hh:767
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2240
 (inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:2649
```
When Scylla started up after the coredump, it appeared that some commitlog files were corrupted:
```
ay 28 20:09:44 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[474335]:  [shard 0] init - replaying commit log
May 28 20:09:45 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[474335]: Reactor stalled for 278 ms on shard 0. Backtrace: 0x40c3564 0x40c28a1 0x40c342f 0x7fc92495c1df 0x3f0e650 0x3f159b2 0x7fc923edb9b4 0x1793e0a 0x1>
May 28 20:09:53 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[474335]:  [shard 6] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-108086391101300988.log. 204792 bytes skipped.
May 28 20:09:55 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[474335]:  [shard 13] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-234187180667674889.log. 30801912 bytes skipped.
May 28 20:09:56 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[474335]:  [shard 4] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-72057594082337004.log. 31830008 bytes skipped.
May 28 20:10:11 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[474335]:  [shard 1] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-18014398553891147.log. 1650680 bytes skipped.
May 28 20:10:19 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[474335]:  [shard 7] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-126100789610782968.log. 8937464 bytes skipped.
May 28 20:10:24 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[474335]:  [shard 0] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-44409077.log. 16175096 bytes skipped.
May 28 20:11:02 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[474335]:  [shard 11] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-198158383648710887.log. 13967352 bytes skipped.
May 28 20:11:19 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[474335]:  [shard 8] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-144115188120264995.log. 8249336 bytes skipped.
May 28 20:11:35 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[474335]:  [shard 10] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-180143985139228898.log. 11325432 bytes skipped.
May 28 20:11:39 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[474335]:  [shard 5] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-90071992591818986.log. 15597560 bytes skipped.
May 28 20:11:48 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[474335]:  [shard 2] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-36028797063373042.log. 31502328 bytes skipped.
May 28 20:11:52 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[474335]:  [shard 3] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-54043195572855035.log. 8491000 bytes skipped.
May 28 20:12:08 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[474335]:  [shard 9] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-162129586629746926.log. 22282232 bytes skipped.
May 28 20:12:09 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[474335]:  [shard 12] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-216172782158192883.log. 5058552 bytes skipped.
May 28 20:12:23 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[474335]:  [shard 0] commitlog_replayer - Log replay complete, 85743722 replayed mutations (0 invalid, 0 skipped)
May 28 20:12:23 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[474335]:  [shard 0] init - replaying commit log - flushing memtables
May 28 20:12:30 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[474335]:  [shard 0] init - replaying commit log - removing old commitlog segments
May 28 20:12:30 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 scylla[474335]:  [shard 0] compaction - [Compact mview.users_by_last_name 07c003a0-bff1-11eb-8a34-4e45e403c97e] Compacting [/var/lib/scylla/data/mview/users_by>

```

Coredump was missing for some reason.

```
May 28 20:09:33 longevity-tls-50gb-3d-master-db-node-1164cbe2-6 systemd-coredump[471932]: Process 359539 (scylla) of user 113 dumped core.
                                                                                          
                                                                                          Stack trace of thread 359549:
                                                                                          #0  0x00007f56427bf9d5 raise (libc.so.6 + 0x3d9d5)
                                                                                          #1  0x00007f56427a8954 abort (libc.so.6 + 0x26954)
                                                                                          #2  0x00000000040a1392 _ZN7seastar26on_internal_error_noexceptERNS_6loggerESt17basic_string_viewIcSt11char_traitsIcEE (scylla + 0x3ea1392)
                                                                                          #3  0x000000000156a939 _ZN20flat_mutation_readerD1Ev (scylla + 0x136a939)
                                                                                          #4  0x0000000003402132 _ZNSt17_Function_handlerIFN7seastar6futureIvEE20flat_mutation_readerEZN13repair_writer13create_writerERNS0_7shardedI8databaseEERNS6_IN2db27system_distributed_keyspaceEEERNS6_INSA_4view21view_update_generatorEEEEUlS3_E_E9_M_invokeERKSt9_Any_dataOS3_ (scylla + 0x3202132)
                                                                                          #5  0x00000000035ce9ce _ZN7seastar12continuationINS_8internal22promise_base_with_typeIvEEZN15mutation_writer12shard_writer7consumeEvE3$_0ZNS_6futureIP17mutation_fragmentE14then_impl_nrvoIS6_NS7_IvEEEET0_OT_EUlOS3_RS6_ONS_12future_stateIS9_EEE_S9_E15run_and_disposeEv (scylla + 0x33ce9ce)
                                                                                          #6  0x00000000040d64c0 _ZN7seastar7reactor14run_some_tasksEv (scylla + 0x3ed64c0)
                                                                                          #7  0x00000000040d7748 _ZN7seastar7reactor3runEv (scylla + 0x3ed7748)
                                                                                          #8  0x00000000040f61cc _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureEN5boost15program_options13variables_mapENS1_14reactor_configEE4$_97E9_M_invokeERKSt9_Any_data (scylla + 0x3ef61cc)
                                                                                          #9  0x00000000040a1c3b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x3ea1c3b)
                                                                                          #10 0x00007f56434d23f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                                          #11 0x00007f5642883903 __clone (libc.so.6 + 0x101903)
                                                                                          
                                                                                          Stack trace of thread 359545:
                                                                                          #0  0x00007f56434dc0fc read (libpthread.so.0 + 0x130fc)
                                                                                          #1  0x000000000410faeb _ZN7seastar9file_desc4readEPvm (scylla + 0x3f0faeb)
                                                                                          #2  0x00000000040ede05 _ZZN7seastar7reactor12do_read_someERNS_17pollable_fd_stateEPNS_8internal16buffer_allocatorEENK3$_5clEv (scylla + 0x3eede05)
                                                                                          #3  0x00000000040edf34 _ZN7seastar12continuationINS_8internal22promise_base_with_typeINS_16temporary_bufferIcEEEEZNS_7reactor12do_read_someERNS_17pollable_fd_stateEPNS1_16buffer_allocatorEE3$_5ZNS_6futureIvE14then_impl_nrvoISB_NSC_IS4_EEEET0_OT_EUlOS5_RSB_ONS_12future_stateINS1_9monostateEEEE_vE15run_and_disposeEv (scylla + 0x3eedf34)
                                                                                          #4  0x00000000040d64c0 _ZN7seastar7reactor14run_some_tasksEv (scylla + 0x3ed64c0)
                                                                                          #5  0x00000000040d7748 _ZN7seastar7reactor3runEv (scylla + 0x3ed7748)
                                                                                          #6  0x00000000040f61cc _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureEN5boost15program_options13variables_mapENS1_14reactor_configEE4$_97E9_M_invokeERKSt9_Any_data (scylla + 0x3ef61cc)
                                                                                          #7  0x00000000040a1c3b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x3ea1c3b)
                                                                                          #8  0x00007f56434d23f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                                          #9  0x00007f5642883903 __clone (libc.so.6 + 0x101903)
                                                                                          
                                                                                          Stack trace of thread 359559:
                                                                                          #0  0x00007f56434dc0fc read (libpthread.so.0 + 0x130fc)
                                                                                          #1  0x0000000004119786 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla + 0x3f19786)
                                                                                          #2  0x0000000004119e40 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x3f19e40)
                                                                                          #3  0x00000000040a1c3b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x3ea1c3b)
                                                                                          #4  0x00007f56434d23f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                                          #5  0x00007f5642883903 __clone (libc.so.6 + 0x101903)
                                                                                          
                                                                                          Stack trace of thread 359548:
                                                                                          #0  0x0000000001233190 _ZNK6schema15get_partitionerEv (scylla + 0x1033190)
                                                                                          #1  0x000000000232e07d _ZN4cql312restrictions12_GLOBAL__N_116range_from_bytesERK6schemaRKSt6vectorI13managed_bytesSaIS6_EE (scylla + 0x212e07d)
                                                                                          #2  0x00000000023155ea _ZNK4cql312restrictions22statement_restrictions24get_partition_key_rangesERKNS_13query_optionsE (scylla + 0x211
55ea)
                                                                                          #3  0x0000000001cfdea0 _ZNK4cql310statements22modification_statement20build_partition_keysERKNS_13query_optionsERKSt8optionalISt13unordered_mapIN7seastar13basic_sstringIcjLj15ELb1EEES5_INS8_IajLj31ELb0EEEESt4hashIS9_ESt8equal_toIS9_ESaISt4pairIKS9_SB_EEEE (scylla + 0x1afdea0)
                                                                                          #4  0x0000000001cf89d0 _ZNK4cql310statements22modification_statement13get_mutationsERN7service13storage_proxyERKNS_13query_optionsENSt6chrono10time_pointIN7seastar12lowres_clockENS8_8durationIlSt5ratioILl1ELl1000EEEEEEblRNS2_11query_stateE (scylla + 0x1af89d0)
                                                                                          #5  0x0000000001d02c15 _ZNK4cql310statements22modification_statement25execute_without_conditionERN7service13storage_proxyERNS2_11query_stateERKNS_13query_optionsE (scylla + 0x1b02c15)
                                                                                          #6  0x0000000001cffa52 _ZNK4cql310statements22modification_statement10do_executeERN7service13storage_proxyERNS2_11query_stateERKNS_13query_optionsE (scylla + 0x1affa52)
                                                                                          #7  0x0000000001d0b9a8 _ZN7seastar20noncopyable_functionIFNS_6futureINS_10shared_ptrIN13cql_transport8messages14result_messageEEEEEPKN4cql310statements22modification_statementERN7service13storage_proxyERNSD_11query_stateERKNS8_13query_optionsEEE17direct_vtable_forISt7_Mem_fnIMSA_KFS7_SF_SH_SK_EEE4callEPKSM_SC_SF_SH_SK_ (scylla + 0x1b0b9a8)
                                                                                          #8  0x0000000001d0b9ed _ZN7seastar20noncopyable_functionIFNS_6futureINS_10shared_ptrIN13cql_transport8messages14result_messageEEEEEPKN4cql310statements22modification_statementERN7service13storage_proxyERNSD_11query_stateERKNS8_13query_optionsEEE17direct_vtable_forIZNS_35inheriting_concrete_execution_stageIS7_JSC_SF_SH_SK_EE20make_stage_for_groupENS_16scheduling_groupEEUlSC_SF_SH_SK_E_E4callEPKSM_SC_SF_SH_SK_ (scylla + 0x1b0b9ed)
                                                                                          #9  0x0000000001d09b25 _ZN7seastar24concrete_execution_stageINS_6futureINS_10shared_ptrIN13cql_transport8messages14result_messageEEEEEJPKN4cql310statements22modification_statementERN7service13storage_proxyERNSD_11query_stateERKNS8_13query_optionsEEE8do_flushEv (scylla + 0x1b09b25)
                                                                                          #10 0x000000000407e486 _ZN7seastar11lambda_taskIZNS_15execution_stage5flushEvE3$_5E15run_and_disposeEv (scylla + 0x3e7e486)
                                                                                          #11 0x00000000040d64c0 _ZN7seastar7reactor14run_some_tasksEv (scylla + 0x3ed64c0)
                                                                                          #12 0x00000000040d7748 _ZN7seastar7reactor3runEv (scylla + 0x3ed7748)
                                                                                          #13 0x00000000040f61cc _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureEN5boost15program_options13variables_mapENS1_14reactor_configEE4$_97E9_M_invokeERKSt9_Any_data (scylla + 0x3ef61cc)
                                                                                          #14 0x00000000040a1c3b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x3ea1c3b)
                                                                                          #15 0x00007f56434d23f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                                          #16 0x00007f5642883903 __clone (libc.so.6 + 0x101903)
                                                                                          
                                                                                          Stack trace of thread 359544:
                                                                                          #0  0x00000000040e4b01 _ZN7seastar3smp11poll_queuesEv (scylla + 0x3ee4b01)
                                                                                          #1  0x00000000041121b6 _ZN7seastar7reactor10smp_pollfn4pollEv (scylla + 0x3f121b6)
                                                                                          #2  0x00000000040f5329 _ZNSt17_Function_handlerIFbvEZN7seastar7reactor3runEvE4$_79E9_M_invokeERKSt9_Any_data (scylla + 0x3ef5329)
                                                                                          #3  0x00000000040d7776 _ZN7seastar7reactor3runEv (scylla + 0x3ed7776)
                                                                                          #4  0x00000000040f61cc _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureEN5boost15program_options13variables_mapENS1_14reactor_configEE4$_97E9_M_invokeERKSt9_Any_data (scylla + 0x3ef61cc)
                                                                                          #5  0x00000000040a1c3b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x3ea1c3b)
                                                                                          #6  0x00007f56434d23f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                                          #7  0x00007f5642883903 __clone (libc.so.6 + 0x101903)
                                                                                          
                                                                                          Stack trace of thread 359554:
                                                                                          #0  0x00007f56434dc0fc read (libpthread.so.0 + 0x130fc)
                                                                                          #1  0x0000000004119786 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla + 0x3f19786)
                                                                                          #2  0x0000000004119e40 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x3f19e40)
                                                                                          #3  0x00000000040a1c3b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x3ea1c3b)
                                                                                          #4  0x00007f56434d23f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                                          #5  0x00007f5642883903 __clone (libc.so.6 + 0x101903)
                                                                                          
                                                                                          Stack trace of thread 359563:
                                                                                          #0  0x00007f56434dc0fc read (libpthread.so.0 + 0x130fc)
                                                                                          #1  0x0000000004119786 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla + 0x3f19786)
                                                                                          #2  0x0000000004119e40 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x3f19e40)
                                                                                          #3  0x00000000040a1c3b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x3ea1c3b)
                                                                                          #4  0x00007f56434d23f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                                          #5  0x00007f5642883903 __clone (libc.so.6 + 0x101903)
                                                                                          
                                                                                          Stack trace of thread 359564:
                                                                                          #0  0x00007f56434dc0fc read (libpthread.so.0 + 0x130fc)
                                                                                          #1  0x0000000004119786 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla + 0x3f19786)
                                                                                         #2  0x0000000004119e40 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x3f19e40)
                                                                                          #3  0x00000000040a1c3b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x3ea1c3b)
                                                                                          #4  0x00007f56434d23f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                                          #5  0x00007f5642883903 __clone (libc.so.6 + 0x101903)
                                                                                          
                                                                                          Stack trace of thread 359546:
                                                                                          #0  0x00000000014a5c55 _ZNK23mutation_partition_view9do_acceptI17partition_builderEEvRK14column_mappingRT_ (scylla + 0x12a5c55)
                                                                                          #1  0x00000000013404ad _ZN8memtable5applyERK15frozen_mutationRKN7seastar13lw_shared_ptrIK6schemaEEON2db9rp_handleE (scylla + 0x11404ad)
                                                                                          #2  0x000000000112ed3f _ZN5table5applyERK15frozen_mutationRKN7seastar13lw_shared_ptrIK6schemaEEON2db9rp_handleE (scylla + 0xf2ed3f)
                                                                                          #3  0x00000000010733df _ZN8database15apply_in_memoryERK15frozen_mutationN7seastar13lw_shared_ptrIK6schemaEEON2db9rp_handleENSt6chrono10time_pointINS3_12lowres_clockENSB_8durationIlSt5ratioILl1ELl1000EEEEEE (scylla + 0xe733df)
                                                                                          #4  0x000000000107683a _ZN8database20apply_with_commitlogEN7seastar13lw_shared_ptrIK6schemaEER5tableN5utils4UUIDERK15frozen_mutationNSt6chrono10time_pointINS0_12lowres_clockENSC_8durationIlSt5ratioILl1ELl1000EEEEEENS0_10bool_classI14force_sync_tagEE (scylla + 0xe7683a)
                                                                                          #5  0x000000000101a47c _ZN8database8do_applyEN7seastar13lw_shared_ptrIK6schemaEERK15frozen_mutationN7tracing15trace_state_ptrENSt6chrono10time_pointINS0_12lowres_clockENSA_8durationIlSt5ratioILl1ELl1000EEEEEENS0_10bool_classI14force_sync_tagEE (scylla + 0xe1a47c)
                                                                                          #6  0x00000000010b22db _ZN7seastar20noncopyable_functionIFNS_6futureIvEEP8databaseNS_13lw_shared_ptrIK6schemaEERK15frozen_mutationN7tracing15trace_state_ptrENSt6chrono10time_pointINS_12lowres_clockENSE_8durationIlSt5ratioILl1ELl1000EEEEEENS_10bool_classI14force_sync_tagEEEE17direct_vtable_forISt7_Mem_fnIMS3_FS2_S8_SB_SD_SL_SO_EEE4callEPKSQ_S4_S8_SB_SD_SL_SO_ (scylla + 0xeb22db)
                                                                                          #7  0x00000000010df3fd _ZN7seastar20noncopyable_functionIFNS_6futureIvEEP8databaseNS_13lw_shared_ptrIK6schemaEERK15frozen_mutationN7tracing15trace_state_ptrENSt6chrono10time_pointINS_12lowres_clockENSE_8durationIlSt5ratioILl1ELl1000EEEEEENS_10bool_classI14force_sync_tagEEEE17direct_vtable_forIZNS_35inheriting_concrete_execution_stageIS2_JS4_S8_SB_SD_SL_SO_EE20make_stage_for_groupENS_16scheduling_groupEEUlS4_S8_SB_SD_SL_SO_E_E4callEPKSQ_S4_S8_SB_SD_SL_SO_ (scylla + 0xedf3fd)
                                                                                          #8  0x000000000108bc8c _ZN7seastar24concrete_execution_stageINS_6futureIvEEJP8databaseNS_13lw_shared_ptrIK6schemaEERK15frozen_mutationN7tracing15trace_state_ptrENSt6chrono10time_pointINS_12lowres_clockENSE_8durationIlSt5ratioILl1ELl1000EEEEEENS_10bool_classI14force_sync_tagEEEE8do_flushEv (scylla + 0xe8bc8c)
                                                                                          #9  0x000000000407e486 _ZN7seastar11lambda_taskIZNS_15execution_stage5flushEvE3$_5E15run_and_disposeEv (scylla + 0x3e7e486)
                                                                                          #10 0x00000000040d64c0 _ZN7seastar7reactor14run_some_tasksEv (scylla + 0x3ed64c0)
                                                                                          #11 0x00000000040d7748 _ZN7seastar7reactor3runEv (scylla + 0x3ed7748)
                                                                                          #12 0x00000000040f61cc _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureEN5boost15program_options13variables_mapENS1_14reactor_configEE4$_97E9_M_invokeERKSt9_Any_data (scylla + 0x3ef61cc)
                                                                                          #13 0x00000000040a1c3b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x3ea1c3b)
                                                                                          #14 0x00007f56434d23f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                                          #15 0x00007f5642883903 __clone (libc.so.6 + 0x101903)
                                                                                          
                                                                                          Stack trace of thread 359562:
                                                                                          #0  0x00007f56434dc0fc read (libpthread.so.0 + 0x130fc)
                                                                                          #1  0x0000000004119786 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla + 0x3f19786)
                                                                                          #2  0x0000000004119e40 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x3f19e40)
                                                                                          #3  0x00000000040a1c3b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x3ea1c3b)
                                                                                          #4  0x00007f56434d23f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                                          #5  0x00007f5642883903 __clone (libc.so.6 + 0x101903)
                                                                                          
                                                                                          Stack trace of thread 359540:
                                                                                          #0  0x0000000001480119 _ZNK18compact_radix_tree4treeI13cell_and_hashjE9node_baseIS1_JNS2_15indirect_layoutIS1_LNS2_6layoutE1ELj4ELS5_2ELj0ELS5_0ELj0EEENS4_IS1_LS5_2ELj8ELS5_3ELj0ELS5_1ELj4EEENS4_IS1_LS5_3ELj16ELS5_4ELj0ELS5_2ELj8EEENS4_IS1_LS5_4ELj32ELS5_6ELj0ELS5_3ELj16EEENS2_13direct_layoutIS1_LS5_6ELS5_0ELj0ELS5_4ELj32EEEEE5visitIRZNS2_5visitIZNS2_5clearEvE16clearing_visitorEEvOT_E7adaptorS7_S8_JS9_SB_EEEbRKNS_14variadic_unionIJT0_T1_DpT2_EEESH_j (scylla + 0x1280119)
                                                                                          #1  0x000000000144371f _ZN18mutation_partition12clear_gentlyEP13cache_tracker (scylla + 0x124371f)
                                                                                          #2  0x000000000129c635 _ZN15partition_entry5evictER16mutation_cleaner (scylla + 0x109c635)
                                                                                          #3  0x0000000001322237 _ZN7seastar20noncopyable_functionIFvvEE17direct_vtable_forIZNS_5asyncIZZN9row_cache10invalidateENS5_16external_updaterEOSt6vectorI20nonwrapping_intervalIN3dht13ring_positionEESaISB_EEENK4$_25clEvEUlvE_JEEENS_8futurizeINSt9result_ofIFNSt5decayIT_E4typeEDpNSJ_IT0_E4typeEEE4typeEE4typeENS_17thread_attributesEOSK_DpOSN_EUlvE_E4callEPKS2_ (scylla + 0x1122237)
                                                                                          #4  0x0000000004355652 _ZN7seastar14thread_context4mainEv (scylla + 0x4155652)
                                                                                          
                                                                                          Stack trace of thread 359555:
                                                                                          #0  0x00007f56434dc0fc read (libpthread.so.0 + 0x130fc)
                                                                                          #1  0x0000000004119786 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla + 0x3f19786)
                                                                                          #2  0x0000000004119e40 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x3f19e40)
                                                                                          #3  0x00000000040a1c3b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x3ea1c3b)
                                                                                          #4  0x00007f56434d23f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                                          #5  0x00007f5642883903 __clone (libc.so.6 + 0x101903)
                                                                                          
                                                                                          Stack trace of thread 359565:
                                                                                          #0  0x00007f56434dc0fc read (libpthread.so.0 + 0x130fc)
                                                                                          #1  0x0000000004119786 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla + 0x3f19786)
                                                                                          #2  0x0000000004119e40 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x3f19e40)
                                                                                          #3  0x00000000040a1c3b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x3ea1c3b)
                                                                                          #4  0x00007f56434d23f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                                          #5  0x00007f5642883903 __clone (libc.so.6 + 0x101903)
                                                                                          
                                                                                          Stack trace of thread 359547:
                                                                                          #0  0x0000000002ca7316 _ZN7seastar3rpc13do_unmarshallIN4netw10serializerENS_19memory_input_streamIN9__gnu_cxx17__normal_iteratorIPNS_16temporary_bufferIcEESt6vectorIS8_SaIS8_EEEEEEN5query12read_commandEJ17wrapping_intervalIN3dht13ring_positionEENS0_8optionalINSF_16digest_algorithmEEEEEESt5tupleIJT1_DpT2_EERNS0_10connectionERT0_ (scylla + 0x2aa7316)
                                                                                          #1  0x0000000002cdc832 _ZZZZN7seastar3rpc11recv_helperIN4netw10serializerESt8functionIFNS_6futureINS0_5tupleIJN5query13result_digestEl17cache_temperatureEEEEERKNS0_11client_infoENS0_14opt_time_pointENS7_12read_commandE17wrapping_intervalIN3dht13ring_positionEENS0_8optionalINS7_16digest_algorithmEEEEESB_JSG_SK_SN_ENS0_19do_want_client_infoENS0_18do_want_time_pointEEEDaNS0_9signatureIFT1_DpT2_EEEOT0_T3_T4_ENUlNS_10shared_ptrINS0_6server10connectionEEESt8optionalINSt6chrono10time_pointINS_12lowres_clockENS17_8durationIlSt5ratioILl1ELl1000EEEEEEElNS0_7rcv_bufEE_clES15_S1F_lS1G_ENUlT_E_clINS_15semaphore_unitsINS_35semaphore_default_exception_factoryES19_EEEEDaS1I_ENUlvE_clEv (scylla + 0x2adc832)
                                                                                          #2  0x0000000002cdbc18 _ZZZN7seastar3rpc11recv_helperIN4netw10serializerESt8functionIFNS_6futureINS0_5tupleIJN5query13result_digestEl17cache_temperatureEEEEERKNS0_11client_infoENS0_14opt_time_pointENS7_12read_commandE17wrapping_intervalIN3dht13ring_positionEENS0_8optionalINS7_16digest_algorithmEEEEESB_JSG_SK_SN_ENS0_19do_want_client_infoENS0_18do_want_time_pointEEEDaNS0_9signatureIFT1_DpT2_EEEOT0_T3_T4_ENUlNS_10shared_ptrINS0_6server10connectionEEESt8optionalINSt6chrono10time_pointINS_12lowres_clockENS17_8durationIlSt5ratioILl1ELl1000EEEEEEElNS0_7rcv_bufEE_clES15_S1F_lS1G_ENUlT_E_clINS_15semaphore_unitsINS_35semaphore_default_exception_factoryES19_EEEEDaS1I_ (scylla + 0x2adbc18)
                                                                                          #3  0x0000000002cd8cb3 _ZZN7seastar3rpc11recv_helperIN4netw10serializerESt8functionIFNS_6futureINS0_5tupleIJN5query13result_digestEl17cache_temperatureEEEEERKNS0_11client_infoENS0_14opt_time_pointENS7_12read_commandE17wrapping_intervalIN3dht13ring_positionEENS0_8optionalINS7_16digest_algorithmEEEEESB_JSG_SK_SN_ENS0_19do_want_client_infoENS0_18do_want_time_pointEEEDaNS0_9signatureIFT1_DpT2_EEEOT0_T3_T4_ENUlNS_10shared_ptrINS0_6server10connectionEEESt8optionalINSt6chrono10time_pointINS_12lowres_clockENS17_8durationIlSt5ratioILl1ELl1000EEEEEEElNS0_7rcv_bufEE_clES15_S1F_lS1G_ (scylla + 0x2ad8cb3)
                                                                                          #4  0x0000000002cd811e _ZSt13__invoke_implIN7seastar6futureIvEERZNS0_3rpc11recv_helperIN4netw10serializerESt8functionIFNS1_INS3_5tupleIJN5query13result_digestEl17cache_temperatureEEEEERKNS3_11client_infoENS3_14opt_time_pointENS9_12read_commandE17wrapping_intervalIN3dht13ring_positionEENS3_8optionalINS9_16digest_algorithmEEEEESD_JSI_SM_SP_ENS3_19do_want_client_infoENS3_18do_want_time_pointEEEDaNS3_9signatureIFT1_DpT2_EEEOT0_T3_T4_EUlNS0_10shared_ptrINS3_6server10connectionEEESt8optionalINSt6chrono10time_pointINS0_12lowres_clockENS19_8durationIlSt5ratioILl1ELl1000EEEEEEElNS3_7rcv_bufEE_JS17_S1H_lS1I_EET_St14__invoke_otherS11_DpOT1_ (scylla + 0x2ad811e)
                                                                                          #5  0x0000000002cd7f8c _ZNSt17_Function_handlerIFN7seastar6futureIvEENS0_10shared_ptrINS0_3rpc6server10connectionEEESt8optionalINSt6chrono10time_pointINS0_12lowres_clockENS9_8durationIlSt5ratioILl1ELl1000EEEEEEElNS4_7rcv_bufEEZNS4_11recv_helperIN4netw10serializerESt8functionIFNS1_INS4_5tupleIJN5query13result_digestEl17cache_temperatureEEEEERKNS4_11client_infoENS4_14opt_time_pointENSP_12read_commandE17wrapping_intervalIN3dht13ring_positionEENS4_8optionalINSP_16digest_algorithmEEEEEST_JSY_S12_S15_ENS4_19do_want_client_infoENS4_18do_want_time_pointEEEDaNS4_9signatureIFT1_DpT2_EEEOT0_T3_T4_EUlS7_SH_lSI_E_E9_M_invokeERKSt9_Any_dataOS7_OSH_OlOSI_ (scylla + 0x2ad7f8c)
                                                                                          #6  0x0000000004454fab _ZZZZZZN7seastar3rpc6server10connection7processEvEN4$_15clEvENKUlvE_clEvENUlvE0_clEvENKUlSt5tupleIJSt8optionalImEmlS7_INS0_7rcv_bufEEEEE_clESB_ENUlvE_clEv (scylla + 0x4254fab)
                                                                                          #7  0x00000000044554a8 _ZN7seastar11lambda_taskIZNS_21with_scheduling_groupIZZZZZNS_3rpc6server10connection7processEvEN4$_15clEvENKUlvE_clEvENUlvE0_clEvENKUlSt5tupleIJSt8optionalImEmlS9_INS2_7rcv_bufEEEEE_clESD_EUlvE_JEEEDaNS_16scheduling_groupET_DpOT0_EUlvE_E15run_and_disposeEv (scylla + 0x42554a8)
                                                                                          #8  0x00000000040d64c0 _ZN7seastar7reactor14run_some_tasksEv (scylla + 0x3ed64c0)
                                                                                          #9  0x00000000040d7748 _ZN7seastar7reactor3runEv (scylla + 0x3ed7748)
                                                                                          #10 0x00000000040f61cc _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureEN5boost15program_options13variables_mapENS1_14reactor_configEE4$_97E9_M_invokeERKSt9_Any_data (scylla + 0x3ef61cc)
                                                                                          #11 0x00000000040a1c3b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x3ea1c3b)
                                                                                          #12 0x00007f56434d23f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                                          #13 0x00007f5642883903 __clone (libc.so.6 + 0x101903)
                                                                                          
                                                                                          Stack trace of thread 359560:
                                                                                          #0  0x00007f56434dc0fc read (libpthread.so.0 + 0x130fc)
                                                                                          #1  0x0000000004119786 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla + 0x3f19786)
                                                                                          #2  0x0000000004119e40 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x3f19e40)
                                                                                          #3  0x00000000040a1c3b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x3ea1c3b)
                                                                                          #4  0x00007f56434d23f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                                         #5  0x00007f5642883903 __clone (libc.so.6 + 0x101903)
                                                                                          
                                                                                          Stack trace of thread 359551:
                                                                                          #0  0x00000000028444a3 _ZN5utils6filter12bloom_filter3addERKSt17basic_string_viewIaSt11char_traitsIaEE (scylla + 0x26444a3)
                                                                                          #1  0x0000000001858932 _ZN8sstables2mc6writer21consume_new_partitionERKN3dht13decorated_keyE (scylla + 0x1658932)
                                                                                          #2  0x00000000018d08ee _ZN8sstables25compacting_sstable_writer21consume_new_partitionERKN3dht13decorated_keyE (scylla + 0x16d08ee)
                                                                                          #3  0x000000000191ed7e _ZN22compact_mutation_stateIL19emit_only_live_rows0EL20compact_for_sstables1EE7consumeIN8sstables25compacting_sstable_writerE33noop_compacted_fragments_consumerEEN7seastar10bool_classINS7_18stop_iteration_tagEEEO14clustering_rowRT_RT0_ (scylla + 0x171ed7e)
                                                                                          #4  0x000000000191c2f1 _ZNO17mutation_fragment7consumeIN20flat_mutation_reader4impl16consumer_adapterI35stable_flattened_mutations_consumerI22compact_for_compactionIN8sstables25compacting_sstable_writerE33noop_compacted_fragments_consumerEEEEEEDcRT_ (scylla + 0x171c2f1)
                                                                                          #5  0x000000000191b669 _ZN20flat_mutation_reader4impl17consume_in_threadI35stable_flattened_mutations_consumerI22compact_for_compactionIN8sstables25compacting_sstable_writerE33noop_compacted_fragments_consumerEENS_9no_filterEEEDaT_T0_NSt6chrono10time_pointIN7seastar12lowres_clockENSC_8durationIlSt5ratioILl1ELl1000EEEEEE (scylla + 0x171b669)
                                                                                          #6  0x000000000191aefa _ZN20flat_mutation_reader17consume_in_threadI35stable_flattened_mutations_consumerI22compact_for_compactionIN8sstables25compacting_sstable_writerE33noop_compacted_fragments_consumerEENS_9no_filterEEEDaT_T0_NSt6chrono10time_pointIN7seastar12lowres_clockENSB_8durationIlSt5ratioILl1ELl1000EEEEEE (scylla + 0x171aefa)
                                                                                          #7  0x0000000001919de7 _ZN20flat_mutation_reader17consume_in_threadI35stable_flattened_mutations_consumerI22compact_for_compactionIN8sstables25compacting_sstable_writerE33noop_compacted_fragments_consumerEEEEDaT_NSt6chrono10time_pointIN7seastar12lowres_clockENS9_8durationIlSt5ratioILl1ELl1000EEEEEE (scylla + 0x1719de7)
                                                                                          #8  0x0000000001918dce _ZZZN8sstables10compaction5setupI33noop_compacted_fragments_consumerEEN7seastar6futureIvEET_ENUl20flat_mutation_readerE_clES7_ENUlvE_clEv (scylla + 0x1718dce)
                                                                                          #9  0x0000000001918b54 _ZN7seastar20noncopyable_functionIFvvEE17direct_vtable_forIZNS_5asyncIZZN8sstables10compaction5setupI33noop_compacted_fragments_consumerEENS_6futureIvEET_ENUl20flat_mutation_readerE_clESC_EUlvE_JEEENS_8futurizeINSt9result_ofIFNSt5decayISB_E4typeEDpNSH_IT0_E4typeEEE4typeEE4typeENS_17thread_attributesEOSB_DpOSK_EUlvE_E4callEPKS2_ (scylla + 0x1718b54)
                                                                                          #10 0x0000000004355652 _ZN7seastar14thread_context4mainEv (scylla + 0x4155652)
                                                                                          
                                                                                          Stack trace of thread 359557:
                                                                                          #0  0x00007f56434dc0fc read (libpthread.so.0 + 0x130fc)
                                                                                          #1  0x0000000004119786 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla + 0x3f19786)
                                                                                          #2  0x0000000004119e40 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x3f19e40)
                                                                                          #3  0x00000000040a1c3b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x3ea1c3b)
                                                                                          #4  0x00007f56434d23f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                                          #5  0x00007f5642883903 __clone (libc.so.6 + 0x101903)
                                                                                          
                                                                                          Stack trace of thread 359550:
                                                                                          #0  0x0000000004091fc9 _ZN7seastar6memory5statsEv (scylla + 0x3e91fc9)
                                                                                          #1  0x00000000013824a3 _ZN8logalloc12segment_pool16allocate_segmentEm (scylla + 0x11824a3)
                                                                                          #2  0x000000000139d778 _ZN8logalloc18allocating_section7reserveEv (scylla + 0x119d778)
                                                                                          #3  0x000000000133cd17 _ZN8memtable16make_flat_readerEN7seastar13lw_shared_ptrIK6schemaEE13reader_permitRK20nonwrapping_intervalIN3dht13ring_positionEERKN5query15partition_sliceERKNS0_17io_priority_classEN7tracing15trace_state_ptrENS0_10bool_classIN17streamed_mutation14forwarding_tagEEENSL_IN20flat_mutation_reader30partition_range_forwarding_tagEEE (scylla + 0x113cd17)
                                                                                          #4  0x00000000010f79d7 _ZNK5table11make_readerEN7seastar13lw_shared_ptrIK6schemaEE13reader_permitRK20nonwrapping_intervalIN3dht13ring_positionEERKN5query15partition_sliceERKNS0_17io_priority_classEN7tracing15trace_state_ptrENS0_10bool_classIN17streamed_mutation14forwarding_tagEEENSL_IN20flat_mutation_reader30partition_range_forwarding_tagEEE (scylla + 0xef79d7)
                                                                                          #5  0x00000000011e21f3 _ZNSt17_Function_handlerIF20flat_mutation_readerN7seastar13lw_shared_ptrIK6schemaEE13reader_permitRK20nonwrapping_intervalIN3dht13ring_positionEERKN5query15partition_sliceERKNS1_17io_priority_classEN7tracing15trace_state_ptrENS1_10bool_classIN17streamed_mutation14forwarding_tagEEENSM_INS0_30partition_range_forwarding_tagEEEEZNK5table18as_mutation_sourceEvE4$_58E9_M_invokeERKSt9_Any_dataOS5_OS6_SC_SG_SJ_OSL_OSP_OSR_ (scylla + 0xfe21f3)
                                                                                          #6  0x0000000001136c4a _ZN5query7querierIL19emit_only_live_rows1EEC2ERK15mutation_sourceN7seastar13lw_shared_ptrIK6schemaEE13reader_permit20nonwrapping_intervalIN3dht13ring_positionEENS_15partition_sliceERKNS6_17io_priority_classEN7tracing15trace_state_ptrE (scylla + 0xf36c4a)
                                                                                          #7  0x0000000001130dc3 _ZN5table5queryEN7seastar13lw_shared_ptrIK6schemaEERKN5query12read_commandENS5_18query_class_configENS5_14result_optionsERKSt6vectorI20nonwrapping_intervalIN3dht13ring_positionEESaISF_EEN7tracing15trace_state_ptrERNS5_21result_memory_limiterENSt6chrono10time_pointINS0_12lowres_clockENSO_8durationIlSt5ratioILl1ELl1000EEEEEENS5_21querier_cache_contextE (scylla + 0xf30dc3)
                                                                                          #8  0x00000000010b18f1 _ZN7seastar20noncopyable_functionIFNS_6futureINS_13lw_shared_ptrIN5query6resultEEEEEP5tableNS2_IK6schemaEERKNS3_12read_commandENS3_18query_class_configENS3_14result_optionsERKSt6vectorI20nonwrapping_intervalIN3dht13ring_positionEESaISL_EEN7tracing15trace_state_ptrERNS3_21result_memory_limiterENSt6chrono10time_pointINS_12lowres_clockENSU_8durationIlSt5ratioILl1ELl1000EEEEEENS3_21querier_cache_contextEEE17direct_vtable_forISt7_Mem_fnIMS7_FS6_SB_SE_SF_SG_SP_SR_ST_S11_S12_EEE4callEPKS14_S8_SB_SE_SF_SG_SP_SR_ST_S11_S12_ (scylla + 0xeb18f1)
                                                                                          #9  0x00000000010c453b _ZN7seastar20noncopyable_functionIFNS_6futureINS_13lw_shared_ptrIN5query6resultEEEEEP5tableNS2_IK6schemaEERKNS3_12read_commandENS3_18query_class_configENS3_14result_optionsERKSt6vectorI20nonwrapping_intervalIN3dht13ring_positionEESaISL_EEN7tracing15trace_state_ptrERNS3_21result_memory_limiterENSt6chrono10time_pointINS_12lowres_clockENSU_8durationIlSt5ratioILl1ELl1000EEEEEENS3_21querier_cache_contextEEE17direct_vtable_forIZNS_35inheriting_concrete_execution_stageIS6_JS8_SB_SE_SF_SG_SP_SR_ST_S11_S12_EE20make_stage_for_groupENS_16scheduling_groupEEUlS8_SB_SE_SF_SG_SP_SR_ST_S11_S12_E_E4callEPKS14_S8_SB_SE_SF_SG_SP_SR_ST_S11_S12_ (scylla + 0xec453b)
                                                                                         #10 0x000000000108fffc _ZN7seastar24concrete_execution_stageINS_6futureINS_13lw_shared_ptrIN5query6resultEEEEEJP5tableNS2_IK6schemaEERKNS3_12read_commandENS3_18query_class_configENS3_14result_optionsERKSt6vectorI20nonwrapping_intervalIN3dht13ring_positionEESaISL_EEN7tracing15trace_state_ptrERNS3_21result_memory_limiterENSt6chrono10time_pointINS_12lowres_clockENSU_8durationIlSt5ratioILl1ELl1000EEEEEENS3_21querier_cache_contextEEE8do_flushEv (scylla + 0xe8fffc)
                                                                                          #11 0x000000000407e486 _ZN7seastar11lambda_taskIZNS_15execution_stage5flushEvE3$_5E15run_and_disposeEv (scylla + 0x3e7e486)
                                                                                          #12 0x00000000040d64c0 _ZN7seastar7reactor14run_some_tasksEv (scylla + 0x3ed64c0)
                                                                                          #13 0x00000000040d7748 _ZN7seastar7reactor3runEv (scylla + 0x3ed7748)
                                                                                          #14 0x00000000040f61cc _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureEN5boost15program_options13variables_mapENS1_14reactor_configEE4$_97E9_M_invokeERKSt9_Any_data (scylla + 0x3ef61cc)
                                                                                          #15 0x00000000040a1c3b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x3ea1c3b)
                                                                                          #16 0x00007f56434d23f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                                          #17 0x00007f5642883903 __clone (libc.so.6 + 0x101903)
                                                                                          
                                                                                          Stack trace of thread 359566:
                                                                                          #0  0x00007f56434dc0fc read (libpthread.so.0 + 0x130fc)
                                                                                          #1  0x0000000004119786 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla + 0x3f19786)
                                                                                          #2  0x0000000004119e40 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x3f19e40)
                                                                                          #3  0x00000000040a1c3b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x3ea1c3b)
                                                                                          #4  0x00007f56434d23f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                                          #5  0x00007f5642883903 __clone (libc.so.6 + 0x101903)
                                                                                          
                                                                                          Stack trace of thread 359542:
                                                                                          #0  0x00000000040e4b01 _ZN7seastar3smp11poll_queuesEv (scylla + 0x3ee4b01)
                                                                                          #1  0x00000000041121b6 _ZN7seastar7reactor10smp_pollfn4pollEv (scylla + 0x3f121b6)
                                                                                          #2  0x00000000040f5329 _ZNSt17_Function_handlerIFbvEZN7seastar7reactor3runEvE4$_79E9_M_invokeERKSt9_Any_data (scylla + 0x3ef5329)
                                                                                          #3  0x00000000040d7776 _ZN7seastar7reactor3runEv (scylla + 0x3ed7776)
                                                                                          #4  0x00000000040f61cc _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureEN5boost15program_options13variables_mapENS1_14reactor_configEE4$_97E9_M_invokeERKSt9_Any_data (scylla + 0x3ef61cc)
                                                                                          #5  0x00000000040a1c3b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x3ea1c3b)
                                                                                          #6  0x00007f56434d23f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                                          #7  0x00007f5642883903 __clone (libc.so.6 + 0x101903)
                                                                                          
                                                                                          Stack trace of thread 359543:
                                                                                          #0  0x00007f564284a70e __clock_gettime (libc.so.6 + 0xc870e)
                                                                                          #1  0x00007f5642a35ce5 _ZNSt6chrono3_V212steady_clock3nowEv (libstdc++.so.6 + 0xcdce5)
                                                                                          #2  0x00000000040d77a1 _ZN7seastar7reactor3runEv (scylla + 0x3ed77a1)
                                                                                          #3  0x00000000040f61cc _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureEN5boost15program_options13variables_mapENS1_14reactor_configEE4$_97E9_M_invokeERKSt9_Any_data (scylla + 0x3ef61cc)
                                                                                          #4  0x00000000040a1c3b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x3ea1c3b)
                                                                                          #5  0x00007f56434d23f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                                          #6  0x00007f5642883903 __clone (libc.so.6 + 0x101903)
                                                                                          
                                                                                          Stack trace of thread 359552:
                                                                                          #0  0x0000000001a60265 _ZNK5query11result_view7consumeIRN4cql316result_generator20query_result_visitorIRZN13cql_transport10cql_server11fmt_visitor5visitERKNS5_8messages14result_message4rowsEE7visitorEEEEvRKNS_15partition_sliceEOT_ (scylla + 0x1860265)
                                                                                          #1  0x0000000001a5ffea _ZN13cql_transport10cql_server11fmt_visitor5visitERKNS_8messages14result_message4rowsE (scylla + 0x185ffea)
                                                                                          #2  0x0000000001a45308 _ZN13cql_transport11make_resultEsRNS_8messages14result_messageERKN7tracing15trace_state_ptrEhb (scylla + 0x1845308)
                                                                                          #3  0x0000000001a5b6fb _ZN7seastar12continuationINS_8internal22promise_base_with_typeISt7variantIJNS_11foreign_ptrISt10unique_ptrIN13cql_transport8responseESt14default_deleteIS7_EEEEjEEEEZNS6_L24process_execute_internalERN7service12client_stateERNS_7shardedIN4cql315query_processorEEENS6_14request_readerEth24cql_serialization_format14service_permitN7tracing15trace_state_ptrEbE4$_14ZNS_6futureINS_10shared_ptrINS6_8messages14result_messageEEEE14then_impl_nrvoISR_NSS_ISC_EEEET0_OT_EUlOSD_RSR_ONS_12future_stateISW_EEE_SW_E15run_and_disposeEv (scylla + 0x185b6fb)
                                                                                          #4  0x00000000040d64c0 _ZN7seastar7reactor14run_some_tasksEv (scylla + 0x3ed64c0)
                                                                                          #5  0x00000000040d7748 _ZN7seastar7reactor3runEv (scylla + 0x3ed7748)
                                                                                          #6  0x00000000040f61cc _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureEN5boost15program_options13variables_mapENS1_14reactor_configEE4$_97E9_M_invokeERKSt9_Any_data (scylla + 0x3ef61cc)
                                                                                          #7  0x00000000040a1c3b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x3ea1c3b)
                                                                                          #8  0x00007f56434d23f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                                         #9  0x00007f5642883903 __clone (libc.so.6 + 0x101903)
                                                                                          
                                                                                          Stack trace of thread 359553:
                                                                                          #0  0x00007f56434dc0fc read (libpthread.so.0 + 0x130fc)
                                                                                          #1  0x0000000004119786 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla + 0x3f19786)
                                                                                          #2  0x0000000004119e40 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x3f19e40)
                                                                                          #3  0x00000000040a1c3b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x3ea1c3b)
                                                                                          #4  0x00007f56434d23f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                                          #5  0x00007f5642883903 __clone (libc.so.6 + 0x101903)
                                                                                          
                                                                                          Stack trace of thread 359556:
                                                                                          #0  0x00007f56434dc0fc read (libpthread.so.0 + 0x130fc)
                                                                                          #1  0x0000000004119786 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla + 0x3f19786)
                                                                                          #2  0x0000000004119e40 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x3f19e40)
                                                                                          #3  0x00000000040a1c3b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x3ea1c3b)
                                                                                          #4  0x00007f56434d23f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                                          #5  0x00007f5642883903 __clone (libc.so.6 + 0x101903)
                                                                                          
                                                                                          Stack trace of thread 359539:
                                                                                          #0  0x00007f56434dc05f __write (libpthread.so.0 + 0x1305f)
                                                                                          #1  0x00000000040dd2e7 _ZN7seastar17writeable_eventfd6signalEm (scylla + 0x3edd2e7)
                                                                                          #2  0x00000000040d8ed1 _ZN7seastar18syscall_work_queue11submit_itemESt10unique_ptrINS0_9work_itemESt14default_deleteIS2_EE (scylla + 0x3ed8ed1)
                                                                                          #3  0x00000000040718b2 _ZN7seastar18syscall_work_queue6submitINS_14syscall_resultIiEEEENS_6futureIT_EENS_20noncopyable_functionIFS5_vEEE (scylla + 0x3e718b2)
                                                                                          #4  0x0000000004061cc8 _ZN7seastar15posix_file_impl5closeEv (scylla + 0x3e61cc8)
                                                                                          #5  0x000000000406f84e _ZZN7seastar33append_challenged_posix_file_impl5closeEvENK4$_19clEv (scylla + 0x3e6f84e)
                                                                                          #6  0x00000000040678fe _ZN7seastar33append_challenged_posix_file_impl5closeEv (scylla + 0x3e678fe)
                                                                                          #7  0x000000000116625d _ZN17checked_file_impl5closeEv (scylla + 0xf6625d)
                                                                                          #8  0x0000000004067f7e _ZN7seastar4file5closeEv (scylla + 0x3e67f7e)
                                                                                          #9  0x0000000004088550 _ZN7seastar6futureIvE12finally_bodyIZNS_19file_data_sink_impl5closeEvEUlvE_Lb1EEclEOS1_ (scylla + 0x3e88550)
                                                                                          #10 0x0000000004088421 _ZN7seastar6futureIvE19then_wrapped_commonILb0ES1_NS1_12finally_bodyIZNS_19file_data_sink_impl5closeEvEUlvE_Lb1EEEEENS_8futurizeIT0_E4typeEOT1_ (scylla + 0x3e88421)
                                                                                          #11 0x0000000004084331 _ZN7seastar19file_data_sink_impl5closeEv (scylla + 0x3e84331)
                                                                                          #12 0x00000000011a877c _ZN7seastar12continuationINS_8internal22promise_base_with_typeIvEENS_6futureIvE12finally_bodyIZNS_13output_streamIcE5closeEvEUlvE1_Lb1EEEZNS5_17then_wrapped_nrvoIS5_SA_EENS_8futurizeIT_E4typeEOT0_EUlOS3_RSA_ONS_12future_stateINS1_9monostateEEEE_vE15run_and_disposeEv (scylla + 0xfa877c)
                                                                                          #13 0x00000000040d64c0 _ZN7seastar7reactor14run_some_tasksEv (scylla + 0x3ed64c0)
                                                                                          #14 0x00000000040d7748 _ZN7seastar7reactor3runEv (scylla + 0x3ed7748)
                                                                                          #15 0x0000000004075086 _ZN7seastar12app_template14run_deprecatedEiPPcOSt8functionIFvvEE (scylla + 0x3e75086)
                                                                                          #16 0x00000000040744a7 _ZN7seastar12app_template3runEiPPcOSt8functionIFNS_6futureIiEEvEE (scylla + 0x3e744a7)
                                                                                          #17 0x0000000000ecf322 main (scylla + 0xccf322)
                                                                                          #18 0x00007f56427aa1e2 __libc_start_main (libc.so.6 + 0x281e2)
                                                                                          #19 0x0000000000ecc08e _start (scylla + 0xccc08e)
                                                                                          
                                                                                          Stack trace of thread 359541:
                                                                                          #0  0x00007f56434dcecd sendmsg (libpthread.so.0 + 0x13ecd)
                                                                                          #1  0x000000000410fc2b _ZN7seastar9file_desc7sendmsgEPK6msghdri (scylla + 0x3f0fc2b)
                                                                                          #2  0x00000000040bae83 _ZN7seastar7reactor13do_write_someERNS_17pollable_fd_stateERNS_3net6packetE (scylla + 0x3ebae83)
                                                                                          #3  0x000000000411bd04 _ZN7seastar19reactor_backend_aio10write_someERNS_17pollable_fd_stateERNS_3net6packetE (scylla + 0x3f1bd04)
                                                                                          #4  0x00000000040bb468 _ZN7seastar17pollable_fd_state9write_allERNS_3net6packetE (scylla + 0x3ebb468)
                                                                                          #5  0x00000000043f45c3 _ZN7seastar3net20posix_data_sink_impl3putENS0_6packetE (scylla + 0x41f45c3)
                                                                                          #6  0x00000000040abe49 _ZN7seastar9data_sink3putENS_3net6packetE (scylla + 0x3eabe49)
                                                                                          #7  0x00000000044355e4 _ZN7seastar3tls7session8vec_pushEPK5ioveci (scylla + 0x42355e4)
                                                                                          #8  0x00007f5643c90d20 _gnutls_io_write_flush (libgnutls.so.30 + 0x37d20)
                                                                                          #9  0x00007f5643c92738 _gnutls_send_tlen_int (libgnutls.so.30 + 0x39738)
                                                                                          #10 0x00007f5643c93cb0 gnutls_record_send2 (libgnutls.so.30 + 0x3acb0)
                                                                                          #11 0x0000000004432e85 _ZN7seastar8futurizeINS_6futureINS_10bool_classINS_18stop_iteration_tagEEEEEE6invokeIRZZNS_3tls7session6do_putEPNS_3net8fragmentESC_ENKUlRSB_E_clESD_EUlvE_JEEES5_OT_DpOT0_ (scylla + 0x4232e85)
                                                                                          #12 0x0000000004432c49 _ZN7seastar6repeatIZZNS_3tls7session6do_putEPNS_3net8fragmentES5_ENKUlRS4_E_clES6_EUlvE_EENS_6futureIvEEOT_ (scylla + 0x4232c49)
                                                                                          #13 0x0000000004432947 _ZN7seastar8internal16do_for_each_implIPNS_3net8fragmentEZNS_3tls7session6do_putES4_S4_EUlRS3_E_EENS_6futureIvEET_SB_T0_ (scylla + 0x4232947)
                                                                                          #14 0x0000000004431c9f _ZN7seastar3tls7session6do_putEPNS_3net8fragmentES4_ (scylla + 0x4231c9f)
                                                                                          #15 0x0000000004432387 _ZZN7seastar14with_semaphoreINS_35semaphore_default_exception_factoryESt5_BindIFMNS_3tls7sessionEFNS_6futureIvEEPNS_3net8fragmentES9_EPS4_S9_S9_EENSt6chrono3_V212steady_clockEEENS_8futurizeINSt9result_ofIFT0_vEE4typeEE4typeERNS_15basic_semaphoreIT_T1_EEmOSK_ENUlSR_E_clINS_15semaphore_unitsIS1_SH_EEEEDaSR_ (scylla + 0x4232387)
                                                                                          #16 0x000000000443220e _ZN7seastar6futureINS_15semaphore_unitsINS_35semaphore_default_exception_factoryENSt6chrono3_V212steady_clockEEEE9then_implIZNS_14with_semaphoreIS2_St5_BindIFMNS_3tls7sessionEFNS0_IvEEPNS_3net8fragmentESG_EPSC_SG_SG_EES5_EENS_8futurizeINSt9result_ofIFT0_vEE4typeEE4typeERNS_15basic_semaphoreIT_T1_EEmOSO_EUlSV_E_SD_EESO_OSV_ (scylla + 0x423220e)
                                                                                          #17 0x0000000004431c14 _ZN7seastar14with_semaphoreINS_35semaphore_default_exception_factoryESt5_BindIFMNS_3tls7sessionEFNS_6futureIvEEPNS_3net8fragmentES9_EPS4_S9_S9_EENSt6chrono3_V212steady_clockEEENS_8futurizeINSt9result_ofIFT0_vEE4typeEE4typeERNS_15basic_semaphoreIT_T1_EEmOSK_ (scylla + 0x4231c14)
                                                                                          #18 0x00000000044319ff _ZN7seastar3tls7session3putENS_3net6packetE (scylla + 0x42319ff)
                                                                                          #19 0x00000000044317c1 _ZN7seastar3tls25tls_connected_socket_impl9sink_impl3putENS_3net6packetE (scylla + 0x42317c1)
                                                                                          #20 0x00000000040abe49 _ZN7seastar9data_sink3putENS_3net6packetE (scylla + 0x3eabe49)
                                                                                          #21 0x00000000040fe809 _ZN7seastar13output_streamIcE10poll_flushEv (scylla + 0x3efe809)
                                                                                          #22 0x00000000041125e7 _ZN7seastar7reactor18batch_flush_pollfn4pollEv (scylla + 0x3f125e7)
                                                                                          #23 0x00000000040f5329 _ZNSt17_Function_handlerIFbvEZN7seastar7reactor3runEvE4$_79E9_M_invokeERKSt9_Any_data (scylla + 0x3ef5329)
                                                                                          #24 0x00000000040d7776 _ZN7seastar7reactor3runEv (scylla + 0x3ed7776)
                                                                                          #25 0x00000000040f61cc _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureEN5boost15program_options13variables_mapENS1_14reactor_configEE4$_97E9_M_invokeERKSt9_Any_data (scylla + 0x3ef61cc)
                                                                                          #26 0x00000000040a1c3b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x3ea1c3b)
                                                                                          #27 0x00007f56434d23f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                                          #28 0x00007f5642883903 __clone (libc.so.6 + 0x101903)
                                                                                          
                                                                                          Stack trace of thread 359558:
                                                                                          #0  0x00007f564287cacb ftruncate64 (libc.so.6 + 0xfaacb)
                                                                                          #1  0x0000000004068c80 _ZN7seastar20noncopyable_functionIFNS_14syscall_resultIiEEvEE17direct_vtable_forIZNS_15posix_file_impl8truncateEmE4$_24E4callEPKS4_ (scylla + 0x3e68c80)
                                                                                          #2  0x0000000004071a3e _ZN7seastar18syscall_work_queue19work_item_returningINS_14syscall_resultIiEEE7processEv (scylla + 0x3e71a3e)
                                                                                          #3  0x0000000004119a3b _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla + 0x3f19a3b)
                                                                                          #4  0x0000000004119e40 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x3f19e40)
                                                                                          #5  0x00000000040a1c3b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x3ea1c3b)
                                                                                          #6  0x00007f56434d23f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                                          #7  0x00007f5642883903 __clone (libc.so.6 + 0x101903)
                                                                                          
                                                                                          Stack trace of thread 359561:
                                                                                          #0  0x00007f564287cacb ftruncate64 (libc.so.6 + 0xfaacb)
                                                                                          #1  0x0000000004068c80 _ZN7seastar20noncopyable_functionIFNS_14syscall_resultIiEEvEE17direct_vtable_forIZNS_15posix_file_impl8truncateEmE4$_24E4callEPKS4_ (scylla + 0x3e68c80)
                                                                                          #2  0x0000000004071a3e _ZN7seastar18syscall_work_queue19work_item_returningINS_14syscall_resultIiEEE7processEv (scylla + 0x3e71a3e)
                                                                                          #3  0x0000000004119a3b _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla + 0x3f19a3b)
                                                                                          #4  0x0000000004119e40 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x3f19e40)
                                                                                          #5  0x00000000040a1c3b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x3ea1c3b)
                                                                                          #6  0x00007f56434d23f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                                          #7  0x00007f5642883903 __clone (libc.so.6 + 0x101903)

```

Same happened on node 8, 9

Restore Monitor Stack command: `$ hydra investigate show-monitor 1164cbe2-b688-4ec2-a093-4eba1d4ceb76`
Show all stored logs command: `$ hydra investigate show-logs 1164cbe2-b688-4ec2-a093-4eba1d4ceb76`

Test id: `1164cbe2-b688-4ec2-a093-4eba1d4ceb76`

Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/1164cbe2-b688-4ec2-a093-4eba1d4ceb76/20210528_211321/grafana-screenshot-longevity-50gb-3days-scylla-per-server-metrics-nemesis-20210528_211724-longevity-tls-50gb-3d-master-monitor-node-1164cbe2-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/1164cbe2-b688-4ec2-a093-4eba1d4ceb76/20210528_211321/grafana-screenshot-longevity-50gb-3days-scylla-per-server-metrics-nemesis-20210528_211724-longevity-tls-50gb-3d-master-monitor-node-1164cbe2-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/1164cbe2-b688-4ec2-a093-4eba1d4ceb76/20210531_052102/db-cluster-1164cbe2.zip](https://cloudius-jenkins-test.s3.amazonaws.com/1164cbe2-b688-4ec2-a093-4eba1d4ceb76/20210531_052102/db-cluster-1164cbe2.zip)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/1164cbe2-b688-4ec2-a093-4eba1d4ceb76/20210531_052102/loader-set-1164cbe2.zip](https://cloudius-jenkins-test.s3.amazonaws.com/1164cbe2-b688-4ec2-a093-4eba1d4ceb76/20210531_052102/loader-set-1164cbe2.zip)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/1164cbe2-b688-4ec2-a093-4eba1d4ceb76/20210531_052102/monitor-set-1164cbe2.zip](https://cloudius-jenkins-test.s3.amazonaws.com/1164cbe2-b688-4ec2-a093-4eba1d4ceb76/20210531_052102/monitor-set-1164cbe2.zip)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/1164cbe2-b688-4ec2-a093-4eba1d4ceb76/20210531_052102/sct-runner-1164cbe2.zip](https://cloudius-jenkins-test.s3.amazonaws.com/1164cbe2-b688-4ec2-a093-4eba1d4ceb76/20210531_052102/sct-runner-1164cbe2.zip)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-50gb-3days/79/)

### PR DESCRIPTION
**Pull request by bhalevy**
Currently, if e.g. find_column_family throws an error,
as seen in #8776 when the table was dropped during repair,
the reader is not closed.

Use a coroutine to simplify error handling and
close the reader if an exception is caught.

Also, catch an error inside the lambda passed to make_interposer_consumer
when making the shared_sstable for streaming, and close the reader
their and return an exceptional future early, since
the reader will not be moved to sst->write_components, that assumes
ownership over it and closes it in all cases.

Fixes #8776

Test: unit(dev)
DTest: repair_additional_test.py:RepairAdditionalTest.repair_while_table_is_dropped_test (dev, debug) w/ https://github.com/scylladb/scylla/pull/8635#issuecomment-856661138

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>

### CODE REVIEW

File: repair/row_level.cc [hunk 1]
```diff
@@ -586,9 +587,11 @@ class repair_writer : public enable_lw_shared_from_this<repair_writer> {
         _mq = std::move(queue_handle);
         auto writer = shared_from_this();
         _writer_done = mutation_writer::distribute_reader_and_consume_on_shards(_schema, std::move(queue_reader),
-                [&db, &sys_dist_ks, &view_update_gen, reason = this->_reason, estimated_partitions = this->_estimated_partitions] (flat_mutation_reader reader) {
-            auto& t = db.local().find_column_family(reader.schema());
-            return db::view::check_needs_view_update_path(sys_dist_ks.local(), t, reason).then([t = t.shared_from_this(), estimated_partitions, reader = std::move(reader), reason, &view_update_gen] (bool use_view_update_path) mutable {
+                [&db, &sys_dist_ks, &view_update_gen, reason = this->_reason, estimated_partitions = this->_estimated_partitions] (flat_mutation_reader reader) -> future<> {
```
Comment (avikivity) [inline repair/row_level.cc:590]: I think this is broken. Lambda coroutines are captured by reference, and create_writer() is not called in a thread or is a coroutine itself.

Comment (avikivity) [reply repair/row_level.cc:590]: Let's split the coroutinization into its own patch, it is delicate.

Comment (bhalevy) [reply repair/row_level.cc:590]: It passes debug unit tests for me, but I'm not sure they cover repair very well.
I'll look into extracting the lambda function it into a method, it will probably also simplify things a bit.

**Comment by bhalevy** [comment]
In v2:
- factored out lambda functions into static methods for coroutinization.

File: repair/row_level.cc (hunk 1 above)
Comment (bhalevy) [reply repair/row_level.cc]: @avikivity fixed in v2.

**Comment by denesb** [comment]
@xemul has a patch which extracts the two consumer methods into a common place. @xemul was that patch merged? If not, maybe worth incorporating them here, fixing the bug only once.

**Comment by xemul** [comment]
It's in next. 49179f2a35dcb6eaac57d09e48b13f7b2d2f218f

**Comment by bhalevy** [comment]
I'll rebase my branch on top of 49179f2 once it's promoted to master.

File: repair/row_level.cc (hunk 1 above)
Comment (avikivity) [reply repair/row_level.cc]: unit tests don't repair at all. I hope to improve this with seastar support for multiple instances and @xemul war on globals.

**Comment by bhalevy** [comment]
In v3:
- rebased master post 0944d694753c4c3cffc487ff330c17bc25d94d4a (repair, streaming: Generalize consumer lambdas)
-  tested repair_while_table_is_dropped_test in dev/debug modes with https://github.com/scylladb/scylla/pull/8635#issuecomment-856661138

File: streaming/consumer.cc [hunk 2]
```diff
@@ -70,6 +79,13 @@ std::function<future<> (flat_mutation_reader)> make_streaming_consumer(sstring o
                 });
             });
             co_return co_await consumer(std::move(reader));
+        } catch (...) {
+            ex = std::current_exception();
+        }
+        if (ex) {
+            co_await reader.close();
```
Comment (xemul) [inline streaming/consumer.cc:86]: The `reader` is moved into `consumer()` inside try block, so if the `consumer()` throws won't this line close moved reader?

Comment (bhalevy) [reply streaming/consumer.cc:86]: it's safe to close the reader after it was std::moved
it's left in a valid state where close would be a noop.
See https://github.com/scylladb/scylla/blob/fa29b79c200d81de6e35685c5b70ff6ae278d12a/flat_mutation_reader.hh#L468-L482

**Comment by bhalevy** [comment]
@avikivity please re-review, I believe it's now ready to move forward.

**Comment by avikivity** [comment]
Wow, this is complicated. But I think ok.
