### PR TITLE
gossip: Reduce unncessary VIEW_BACKLOG updates

### LINKED ISSUE #5970: Reduce unncessary VIEW_BACKLOG updates in gossip
The blacklog of current and max in VIEW_BACKLOG is not update but the nodes are updating it all the time.  For example: 

```
INFO  2020-03-06 17:13:46,761 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.3, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486026590,718)
INFO  2020-03-06 17:13:46,821 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.2, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486026531,742)
INFO  2020-03-06 17:13:47,765 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.3, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486027590,721)                                       
INFO  2020-03-06 17:13:47,825 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.2, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486027531,745)
INFO  2020-03-06 17:13:48,772 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.3, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486028590,726)
INFO  2020-03-06 17:13:48,833 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.2, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486028531,750)
INFO  2020-03-06 17:13:49,772 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.3, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486029590,729)
INFO  2020-03-06 17:13:49,832 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.2, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486029531,753)
```

The code in question is:

```
246 future<> view_update_backlog_broker::start() {
247     _gossiper.register_(shared_from_this());
248     if (engine().cpu_id() == 0) {
249         // Gossiper runs only on shard 0, and there's no API to add multiple, per-shard application states.
250         // Also, right now we aggregate all backlogs, since the coordinator doesn't keep per-replica shard backlogs.
251         _started = seastar::async([this] {
252             while (!_as.abort_requested()) {
253                 auto backlog = _sp.local().get_view_update_backlog();
254                 auto now = api::timestamp_type(std::chrono::duration_cast<std::chrono::milliseconds>(
255                         std::chrono::system_clock::now().time_since_epoch()).count());
256                 //FIXME: discarded future.
257                 (void)_gossiper.add_local_application_state(
258                         gms::application_state::VIEW_BACKLOG,
259                         gms::versioned_value(seastar::format("{}:{}:{}", backlog.current, backlog.max, now)));
260                 sleep_abortable(gms::gossiper::INTERVAL, _as).get();
261             }
262         }).handle_exception_type([] (const seastar::sleep_aborted& ignored) { });
263     }
264     return make_ready_future<>();
265 }
```

The time `now` is update. I am wondering if we could avoid sending if the blacklog current and max do not change. 

The downside of such updates:

- Introduces more gossip exchange traffic

- Updates system.peers all the time

### PR DESCRIPTION
**Pull request by asias**
The blacklog of current and max in VIEW_BACKLOG is not update but the
nodes are updating VIEW_BACKLOG all the time. For example:

```
INFO  2020-03-06 17:13:46,761 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.3, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486026590,718)
INFO  2020-03-06 17:13:46,821 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.2, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486026531,742)
INFO  2020-03-06 17:13:47,765 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.3, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486027590,721)
INFO  2020-03-06 17:13:47,825 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.2, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486027531,745)
INFO  2020-03-06 17:13:48,772 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.3, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486028590,726)
INFO  2020-03-06 17:13:48,833 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.2, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486028531,750)
INFO  2020-03-06 17:13:49,772 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.3, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486029590,729)
INFO  2020-03-06 17:13:49,832 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.2, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486029531,753)
```

The downside of such updates:

 - Introduces more gossip exchange traffic
 - Updates system.peers all the time

The extra unnecessary gossip traffic is fine to a cluster in a good
shape but when some of the nodes or shards are loaded, such messages and
the handling of such messages can make the system even busy.

With this patch, VIEW_BACKLOG is updated only when the backlog is really
updated.

Btw, we can even make the update only when the change of the backlog is
great than a threshold, e.g., 5%, which can reduce the traffic even
further.

Fixes #5970

### CODE REVIEW

File: service/misc_services.cc [hunk 1]
```diff
@@ -246,14 +246,20 @@ future<> view_update_backlog_broker::start() {
         // Gossiper runs only on shard 0, and there's no API to add multiple, per-shard application states.
         // Also, right now we aggregate all backlogs, since the coordinator doesn't keep per-replica shard backlogs.
         _started = seastar::async([this] {
+            std::optional<db::view::update_backlog> backlog_published;
             while (!_as.abort_requested()) {
                 auto backlog = _sp.local().get_view_update_backlog();
+                if (backlog_published && *backlog_published == backlog) {
```
Comment (nyh) [inline service/misc_services.cc:252]: I see that @avikivity has already committed this patch, but I still want to comment. In https://github.com/scylladb/scylla/issues/5970 I commented that the strict equality you check here will be useful ONLY in the case where the view backlog is exactly zero, and this means basically that MV are not used. I thought the goal of this patch was to solve a problem that involved MV, so this will not help. So I think you need to check whether backlog changed from backlog_published by 10% or 5% or whatever, and not look for strict equality.

Comment (asias) [reply service/misc_services.cc:252]: Yes, Nadav. I mentioned in the commit log, we can make the comparison to be a range in the future patch. In this patch, I want to ensure we all agree we want to reduce the updates.

What percentage do you think make more sense 5% or 10% or 15%?
