### PR TITLE
sstables: remove large allocations when parsing cells

### LINKED ISSUE #7457: Avoid large contiguous allocation for large cells in the sstable parser / writer
When sstable parses a large cell, it will force a large contiguous allocation due to use of temporary_buffer. Potentially triggering foreground reclaiming and causing reactor stalls. Before the large cell is placed into cache, IMR fragments it and store it in a  managed_bytes (fragmented). To fix this inefficiency, let's make sstable parser switch to fragmented temp buffer. Will require a few API changes, like in the parser and also atomic_cell.

Follow a backtrace when this happens:
```
 (inlined by) seastar::memory::reclaimer::do_reclaim() at /usr/src/debug/scylla-enterprise-2019.1.12/seastar/core/memory.hh:124
 (inlined by) seastar::memory::cpu_pages::run_reclaimers(seastar::memory::reclaimer_scope) at /usr/src/debug/scylla-enterprise-2019.1.12/seastar/core/memory.cc:1013
 (inlined by) seastar::memory::cpu_pages::find_and_unlink_span_reclaiming(unsigned int) at /usr/src/debug/scylla-enterprise-2019.1.12/seastar/core/memory.cc:555
 (inlined by) seastar::memory::cpu_pages::allocate_large_and_trim(unsigned int) at /usr/src/debug/scylla-enterprise-2019.1.12/seastar/core/memory.cc:578
seastar::memory::cpu_pages::allocate_large(unsigned int) at /usr/src/debug/scylla-enterprise-2019.1.12/seastar/core/memory.cc:624
 (inlined by) seastar::memory::allocate_large(unsigned long) at /usr/src/debug/scylla-enterprise-2019.1.12/seastar/core/memory.cc:1194
 (inlined by) seastar::memory::allocate(unsigned long) at /usr/src/debug/scylla-enterprise-2019.1.12/seastar/core/memory.cc:1244
seastar::temporary_buffer<char>::temporary_buffer(unsigned long) at /usr/src/debug/scylla-enterprise-2019.1.12/seastar/core/temporary_buffer.hh:71
 (inlined by) data_consumer::continuous_data_consumer<sstables::data_consume_rows_context_m>::read_bytes(seastar::temporary_buffer<char>&, unsigned int, seastar::temporary_buffer<char>&) at /usr/src/debug/scylla-enterprise-2019.1.12/sstables/consumer.hh:193
 (inlined by) data_consumer::continuous_data_consumer<sstables::data_consume_rows_context_m>::read_unsigned_vint_length_bytes(seastar::temporary_buffer<char>&, seastar::temporary_buffer<char>&) at /usr/src/debug/scylla-enterprise-2019.1.12/sstables/consumer.hh:244
sstables::data_consume_rows_context_m::do_process_state(seastar::temporary_buffer<char>&) at /usr/src/debug/scylla-enterprise-2019.1.12/sstables/row.hh:1140
sstables::data_consume_rows_context_m::process_state(seastar::temporary_buffer<char>&) at /usr/src/debug/scylla-enterprise-2019.1.12/sstables/row.hh:790
 (inlined by) data_consumer::continuous_data_consumer<sstables::data_consume_rows_context_m>::process(seastar::temporary_buffer<char>&) at /usr/src/debug/scylla-enterprise-2019.1.12/sstables/consumer.hh:396
data_consumer::continuous_data_consumer<sstables::data_consume_rows_context_m>::operator()(seastar::temporary_buffer<char>) at /usr/src/debug/scylla-enterprise-2019.1.12/sstables/consumer.hh:429
```

### PR DESCRIPTION
**Pull request by wmitros**
sstable cells are parsed into temporary_buffers, which causes large contiguous allocations for some cells. 
This is fixed by storing fragments of the cell value in a fragmented_temporary_buffer instead. 
To achieve this, this patch also adds new methods to the fragmented_temporary_buffer(size(), ostream& operator<<()) and adds methods to the underlying parser(primitive_consumer) for parsing byte strings into fragmented buffers.

Fixes #7457, and (as the last of 4 patches) #6376

### CODE REVIEW

**Comment by raphaelsc** [comment]
thanks a lot for working on this @wmitros

File: utils/fragmented_temporary_buffer.hh [hunk 1]
```diff
@@ -193,6 +193,7 @@ public:
     }
 
     bool empty() const noexcept { return !size_bytes(); }
+    size_t size() const noexcept { return _total_size; }
```
Comment (avikivity) [inline utils/fragmented_temporary_buffer.hh:196]: This is problematic. The view is also an std::ranges::range, adding size() would make it std::ranges::sized_range, but with the wrong result for size(). (we're not using std::ranges at the moment but the same principle applies).

fragmented_temporary_buffer represents two things, a container of fragments and a container of bytes, we should be careful not to mix them.

Comment (avikivity) [reply utils/fragmented_temporary_buffer.hh:196]: /cc @michoecho

File: sstables/consumer.hh [hunk 2]
```diff
@@ -114,8 +116,10 @@ private:
     } _read_int;
 
     // state for READING_BYTES prestate
+    size_t _read_bytes_len = 0;
     temporary_buffer<char> _read_bytes;
-    temporary_buffer<char>* _read_bytes_where; // which temporary_buffer to set, _key or _val?
+    std::vector<temporary_buffer<char>> _read_bytes_fragments;
```
Comment (avikivity) [inline sstables/consumer.hh:121]: Suggest to use utils::small_vector<temporary_buffer<char>, 1> here, it can collapse _read_bytes and _read_bytes_fragments into one variable.

File: sstables/consumer.hh [hunk 3]
```diff
@@ -114,8 +116,10 @@ private:
...
+    std::variant<temporary_buffer<char>*, fragmented_temporary_buffer*> _read_bytes_where; // which buffer to set, _key, _val, _cell_path or _pk?
```
Comment (avikivity) [inline sstables/consumer.hh:122]: And here, perhaps, you can avoid the variant.

File: sstables/consumer.hh [hunk 4]
```diff
@@ -319,21 +365,34 @@ public:
...
             break;
         }
         case prestate::READING_BYTES: {
-            auto n = std::min(_read_bytes.size() - _pos, data.size());
-            std::copy(data.begin(), data.begin() + n,
-                    _read_bytes.get_write() + _pos);
+            auto n = std::min(_read_bytes_len - _pos, data.size());
+            std::visit(overloaded_functor {
+                [&] (temporary_buffer<char>*) {
+                    std::copy(data.begin(), data.begin() + n, _read_bytes.get_write() + _pos);
```
Comment (avikivity) [inline sstables/consumer.hh:379]: Not sure why you'd ever want to copy. In the previous implementation, if the cell spanned two sstable buffers, then we have to copy to linearize. But here, can't you always append fragments?

File: sstables/consumer.hh (hunk 3 above)
Comment (avikivity) [reply sstables/consumer.hh:122]: Ah, is the variant in order to handle both fragmented keys and fragmented cells?

If so, it's okay as a temporary construct, but let's move quickly towards parsing fragmented keys too.

File: sstables/row.hh [hunk 5]
```diff
@@ -448,7 +449,7 @@ private:
                 break;
             }
         case state::CELL_VALUE_BYTES:
-            if (read_bytes(data, _u32, _val) != read_status::ready) {
+            if ((_deleted ? read_bytes(data, _u32, _val) : read_bytes(data, _u32, _val_fragmented)) != read_status::ready) {
```
Comment (avikivity) [inline sstables/row.hh:452]: This is somewhat messy. How do we keep track when we parse into _val and when into _patse_fragmented?

Will it be cleaner if we parse into _val_fragmented in the _deleted case too?

File: sstables/consumer.hh [hunk 6]
```diff
@@ -204,14 +208,33 @@ public:
...
+            _read_bytes_where = &where;
+            _pos = data.size();
+            data.trim(0);
+            _prestate = prestate::READING_BYTES;
+            return read_status::waiting;
+        }
+    }
+    inline read_status read_bytes(temporary_buffer<char>& data, uint32_t len, fragmented_temporary_buffer& where) {
+        _read_bytes_fragments = std::vector<temporary_buffer<char>>();
+        if (data.size() >=  len) {
```
Comment (denesb) [inline sstables/consumer.hh:229]: extra whitespace

File: sstables/consumer.hh (hunk 3 above)
Comment (denesb) [reply sstables/consumer.hh:122]: I think we can avoid the variant by having just a `small_vector<temporary_buffer<char>, 1>* _read_bytes_where` and have differently named methods for reading fragmented/non-fragmented values. The variant in question would know whether there are multiple fragments or not.

Comment (avikivity) [reply sstables/consumer.hh:122]: Well, if we move keys towards fragmented buffers then we'll have to merge them again. But yes, the variant is just confusing so better to have two separate methods (and two pre-states etc.). Or bite the bullet and convert keys too.

Comment (avikivity) [reply sstables/consumer.hh:122]: Yet another option is to read keys as a vector<temporary_buffer>, and then when we extract the key convert to a temporary_buffer. Usually the key will be in a single fragment so this is a cheap operation. Later, we can keep keys fragmented all the way.

Comment (denesb) [reply sstables/consumer.hh:122]: We are already linearizing keys, we just do it as we get the buffers. With my proposal we'd just postpone it. The cost is that we either have to copy the fragment, or keep the buffer containing it alive. Previously we eagerly copied the fragment into the linearizing buffer eagerly.

Comment (haaawk) [inline sstables/consumer.hh:122]: Would it make sense to always use fragmented_temporary_buffer and don't have those special cases?

File: utils/fragmented_temporary_buffer.hh (hunk 1 above)
Comment (wmitros) [reply utils/fragmented_temporary_buffer.hh:196]: The size() was added solely to make compound_type::serialize_value work with fragmented_temporary_buffer::view, we can change serialize_value() to use size_bytes() instead of size() when it's appropriate (currently it works with managed_bytes_view because size() is the same as size_bytes() there)

File: sstables/consumer.hh (hunk 2 above)
Comment (wmitros) [reply sstables/consumer.hh:121]: std::vector is useful for the constructor of fragmented_temporary_buffer, where it can be std::moved, but we can collapse the variables anyway

File: utils/fragmented_temporary_buffer.hh (hunk 1 above)
Comment (avikivity) [reply utils/fragmented_temporary_buffer.hh:196]: You are referring to compound.hh's serialized_value?

Comment (avikivity) [reply utils/fragmented_temporary_buffer.hh:196]: If so, I think it's better to indeed change it to use size_bytes (and add a constraint to serialize_value to make it clear what it expects).

Comment (wmitros) [reply utils/fragmented_temporary_buffer.hh:196]: > You are referring to compound.hh's serialized_value?

yes, it's compound_type::serialize_value()
> If so, I think it's better to indeed change it to use size_bytes (and add a constraint to serialize_value to make it clear what it expects).

Ok

File: sstables/consumer.hh (hunk 3 above)
Comment (wmitros) [reply sstables/consumer.hh]: I've removed the variant and merged _read_bytes and _read_bytes_fragments. Now we have separate methods for reading fragmented and non-fragmented values. Notice that if we want to read a non-fragmented value and it's within a single fragment, we return immediately. Otherwise, we still copy fragments into the linearizing buffer, because after keeping them as vector<temporary_buffer> we would need to linearize them anyway.
The linearizing buffer is now front() of the _read_bytes vector.

File: sstables/row.hh (hunk 5 above)
Comment (wmitros) [reply sstables/row.hh]: It will be a bit more complex but easier to read, so I'll change it to parse into _val_fragmented first and then, if possible, into _val.

File: sstables/consumer.hh (hunk 6 above)
Comment (wmitros) [reply sstables/consumer.hh]: Ok

File: sstables/consumer.hh (hunk 3 above)
Comment (wmitros) [reply sstables/consumer.hh]: There are still some cases where we want to parse bytes into a contiguous buffer(mostly keys), so instead of linearizing a fragmented_temporary_buffer in every such place, I've left optional methods for contiguous parsing.
At least, after the last changes, these don't look like 'special' cases, just like separate cases.

**Comment by avikivity** [comment]
@wmitros when you push, add a log of changes so reviewers know where to focus.

**Comment by wmitros** [comment]
Ok, so the most meaningful changes were from [here](https://github.com/scylladb/scylla/pull/8182#discussion_r604785566)
> removed the variant and merged _read_bytes and _read_bytes_fragments. 
> added separate methods for reading fragmented and non-fragmented values. 
> when reading non-fragmented value, we still copy fragments into the linearizing buffer, because after keeping them as vector<temporary_buffer> we would need to linearize them anyway.
> The linearizing buffer is now front() of the _read_bytes vector.

 and [here](https://github.com/scylladb/scylla/pull/8182#discussion_r600507582)
> changed serialize_value() to use size_bytes() instead of size() when it's appropriate

> also changed serialized_size to make it work

**Review by denesb — APPROVED** [review]
LGTM, I like the way you got rid of the variant.

File: sstables/consumer.hh [hunk 7]
```diff
@@ -138,8 +144,10 @@ private:
                 data.trim_front(len);
                 return read_status::ready;
             } else {
-                _read_bytes = make_tracked_temporary_buffer(temporary_buffer<char>(len), _permit);
-                std::copy(data.begin(), data.end(), _read_bytes.get_write());
+                _read_bytes = std::vector<temporary_buffer<char>>();
+                _read_bytes.push_back(make_tracked_temporary_buffer(temporary_buffer<char>(len), _permit));
+                std::copy(data.begin(), data.end(), _read_bytes.front().get_write());
```
Comment (avikivity) [inline sstables/consumer.hh:149]: Note: `data` itself is a temporary_buffer, so instead of a copy you can use temporary_buffer::share().

It can make a nice follow-up.

File: sstables/consumer.hh [hunk 8]
```diff
@@ -114,9 +119,10 @@ private:
     } _read_int;
 
     // state for READING_BYTES prestate
-    temporary_buffer<char> _read_bytes;
-    temporary_buffer<char>* _read_bytes_where; // which temporary_buffer to set, _key or _val?
-
+    size_t _read_bytes_len = 0;
+    std::vector<temporary_buffer<char>> _read_bytes;
```
Comment (avikivity) [inline sstables/consumer.hh:123]: Can probably use small_vector here, possible follow up.

File: sstables/consumer.hh (hunk 7 above)
Comment (denesb) [reply sstables/consumer.hh:149]: We need to make it tracked though, but I think it is possible to add a new deleter to the deleter chain.

Comment (avikivity) [reply sstables/consumer.hh:149]: Actually, we shouldn't be using temporary_buffer for something that has a fixed maximum size. We should read into a nice array of char8_t.

Comment (avikivity) [reply sstables/consumer.hh:149]: Ah, it doesn't really matter. This only kicks in if the vint spans two disk buffers, which is super rare. So it doesn't matter if we're inefficient here.

File: sstables/consumer.hh [hunk 9]
```diff
@@ -311,29 +372,55 @@ public:
...
+                return read_status::ready;
+            }
+            break;
+        }
         case prestate::READING_BYTES: {
-            auto n = std::min(_read_bytes.size() - _pos, data.size());
-            std::copy(data.begin(), data.begin() + n,
-                    _read_bytes.get_write() + _pos);
+            auto n = std::min(_read_bytes_len - _pos, data.size());
+            _read_bytes.push_back(make_tracked_temporary_buffer(data.share(0, n), _permit));
```
Comment (avikivity) [inline sstables/consumer.hh:419]: I don't think it's correct to call make_tracked_temporary_buffer() on the result of data.share() here. `data` is already tracked, you you're double-tracking it. @denesb ?

File: sstables/kl/reader_impl.hh [hunk 10]
```diff
@@ -334,32 +335,36 @@ private:
...
                 _state = state::CELL_VALUE_BYTES_2;
                 break;
             }
         case state::CELL_VALUE_BYTES_2:
         {
             row_consumer::proceed ret;
             if (_deleted) {
+                _val = temporary_buffer<char>(4);
+                auto v = fragmented_temporary_buffer::view(_val_fragmented);
+                read_fragmented(v, 4, reinterpret_cast<bytes::value_type*>(_val.get_write()));
```
Comment (avikivity) [inline sstables/kl/reader_impl.hh:348]: I think you need to move this below the size check.

Comment (avikivity) [reply sstables/kl/reader_impl.hh:348]: (and change the size check to reference _val_fragmented, right now it can be optimized out since _val is created with a size of 4).

**Comment by avikivity** [comment]
@nyh do you remember the hacks we had to test the sstable readers with buffer size = 1, to force buffer crossings? @wmitros wants to test this series with it.

File: sstables/consumer.hh (hunk 8 above)
Comment (wmitros) [reply sstables/consumer.hh]: I have another change to fix so I'm adding the small_vector as well in a new commit

File: sstables/consumer.hh (hunk 9 above)
Comment (wmitros) [reply sstables/consumer.hh]: I couldn't find the place in code where we're adding tracking to the `data` bufffer, but it makes sense that's it's already tracked. I'm changing it so that we're only adding tracking to the linearizing buffer

File: sstables/kl/reader_impl.hh (hunk 10 above)
Comment (wmitros) [reply sstables/kl/reader_impl.hh:351]: Ok, fixed in the update

**Comment by wmitros** [comment]
I've applied the suggestions from @avikivity, but I'm yet to test it with readers with buffer size = 1

File: sstables/consumer.hh (hunk 9 above)
Comment (avikivity) [reply sstables/consumer.hh]: It's tracked in `tracking_file_impl`.

Comment (denesb) [reply sstables/consumer.hh]: Yes, you are right @avikivity, these buffers should already be tracked, sharing just bumps a reference counter on it.

**Comment by wmitros** [comment]
> @nyh do you remember the hacks we had to test the sstable readers with buffer size = 1, to force buffer crossings? @wmitros wants to test this series with it.

@nyh you've probably just missed it, but if you do remember that trick, I'd greatly appreciate if you could help with it. Otherwise, I'll jsut try to hack it myself

**Comment by wmitros** [comment]
I found the hack: https://github.com/wmitros/scylla/blob/201b86b0426f76a8ec62d7e9fe59efd8f15ef92e/sstables/kl/reader_impl.hh#L200-L216 

When I ran the unit tests with `#if 1`, there was an error with exception messages in broken_sstable_test, but it was caused by the hack: because we want to work on small buffers (size 1), we're calling `process()` on them recursively, so the exception thrown there is caught twice, and the sstable filename is also attached to the message twice.

I've also run most of the sstable dtests, do we need to add anything more to this patch?

**Comment by avikivity** [comment]
No, I'll merge. We should productize the small-buffer testing, perhaps using sstable::sstable_buffer_size.
