### PR TITLE
Service Level Controller: Stop polling distributed data when decommissioned

### LINKED ISSUE #8836: service_level_controller fails to update configuration for 10 minutes after after decommission
*Installation details*
Scylla version (or git commit hash):4.6.dev-0.20210531.b0c22f2e39 with build-id 6a2a6e52891ef3f81d9a844a9b84d45da27c6cbe
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI):https://www.googleapis.com/compute/v1/projects/scylla-images/global/images/533390617289533465 

At `2021-06-06 01:39:11,653`, we executed `nodetool decommission` on node 2 (34.75.175.203 | 10.142.0.8). The decommission starts and ends successfully:
```
2021-06-06T01:39:13+00:00  longevity-10gb-3h-master-db-node-754e09a7-0-2 !INFO    | scylla:  [shard 0] storage_service - DECOMMISSIONING: starts
...
2021-06-06T01:39:52+00:00  longevity-10gb-3h-master-db-node-754e09a7-0-2 !INFO    | scylla:  [shard 0] storage_service - DECOMMISSIONED: 
2021-06-06T01:39:52+00:00  longevity-10gb-3h-master-db-node-754e09a7-0-2 !INFO    | scylla:  [shard 0] storage_service - DECOMMISSIONING: done
```

However, after the decommission has ended (and the streaming has started), the node consistently failed to update its configuration for the following 10 minutes, due to timeouts:
```
2021-06-06T01:41:23+00:00  longevity-10gb-3h-master-db-node-754e09a7-0-2 !WARNING | scylla:  [shard 0] service_level_controller - update_from_distributed_data: failed to update configuration for more than  90 seconds : exceptions::read_timeout_exception (Operation timed out for system_distributed.service_levels - received only 0 responses from 1 CL=ONE.)
2021-06-06T01:42:43+00:00  longevity-10gb-3h-master-db-node-754e09a7-0-2 !WARNING | scylla:  [shard 0] service_level_controller - update_from_distributed_data: failed to update configuration for more than  180 seconds : exceptions::read_timeout_exception (Operation timed out for system_distributed.service_levels - received only 0 responses from 1 CL=ONE.)
2021-06-06T01:44:23+00:00  longevity-10gb-3h-master-db-node-754e09a7-0-2 !WARNING | scylla:  [shard 0] service_level_controller - update_from_distributed_data: failed to update configuration for more than  270 seconds : exceptions::read_timeout_exception (Operation timed out for system_distributed.service_levels - received only 0 responses from 1 CL=ONE.)
2021-06-06T01:45:43+00:00  longevity-10gb-3h-master-db-node-754e09a7-0-2 !WARNING | scylla:  [shard 0] service_level_controller - update_from_distributed_data: failed to update configuration for more than  360 seconds : exceptions::read_timeout_exception (Operation timed out for system_distributed.service_levels - received only 0 responses from 1 CL=ONE.)
2021-06-06T01:47:23+00:00  longevity-10gb-3h-master-db-node-754e09a7-0-2 !WARNING | scylla:  [shard 0] service_level_controller - update_from_distributed_data: failed to update configuration for more than  450 seconds : exceptions::read_timeout_exception (Operation timed out for system_distributed.service_levels - received only 0 responses from 1 CL=ONE.)
```
The timeouts only stopped after the node's instance was shut down (by sct, as part of the running nemesis).

Logs:
```
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                          Log links for testrun with test id 754e09a7-aaf7-4347-a3ed-63082fae9c05                                                                                                           |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type    | Link                                                                                                                                                                                                                                                       |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 20210606_052219 | grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/754e09a7-aaf7-4347-a3ed-63082fae9c05/20210606_052219/grafana-screenshot-longevity-10gb-3h-gce-test-scylla-per-server-metrics-nemesis-20210606_052657-longevity-10gb-3h-master-monitor-node-754e09a7-0-1.png |
| 20210606_054810 | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/754e09a7-aaf7-4347-a3ed-63082fae9c05/20210606_054810/db-cluster-754e09a7.zip                                                                                                                                |
| 20210606_054810 | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/754e09a7-aaf7-4347-a3ed-63082fae9c05/20210606_054810/loader-set-754e09a7.zip                                                                                                                                |
| 20210606_054810 | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/754e09a7-aaf7-4347-a3ed-63082fae9c05/20210606_054810/monitor-set-754e09a7.zip                                                                                                                               |
| 20210606_054810 | sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/754e09a7-aaf7-4347-a3ed-63082fae9c05/20210606_054810/sct-runner-754e09a7.zip                                                                                                                                |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by eliransin**
The polling loop of the service level controller queries a distributed table in order to detect
configuration changes. If a node gets decommissioned, this loop continues to run until shutdown, if a node
stays in the decommissioned mode without being shut down, the loop will fail to query the table and this will
result in warnings and eventually errors in the log. This is not really harmful but it adds unnecessary noise
to the log.
The series below lays the infrastructure for observing storage service state changes, which eventually being
used to break the loop upon preparation for decommissioning.
Tests:
Unit test (dev)
Next Gating Dtests

Fixes #8836

### CODE REVIEW

File: service/qos/service_level_controller.cc [hunk 1]
```diff
@@ -298,6 +298,22 @@ void service_level_controller::update_from_distributed_data(std::chrono::duratio
...
+        return make_ready_future();
+    }
+    // abort the loop of the distributed data checking if it is running
+    if (!_global_controller_db->distributed_data_update.available()) {
+        if (!_global_controller_db->dist_data_update_aborter.abort_requested()) {
+            _global_controller_db->dist_data_update_aborter.request_abort();
+        }
+    }
+    _global_controller_db->distributed_data_update = _global_controller_db->distributed_data_update.get_future().then([this] () {
+        // "Recreate" abort source
```
Comment (psarna) [inline service/qos/service_level_controller.cc:312]: why?

File: service/qos/service_level_controller.cc [hunk 2]
```diff
@@ -298,6 +298,22 @@ void service_level_controller::update_from_distributed_data(std::chrono::duratio
...
 }
 
+future<> service_level_controller::stop_update_from_distributed_data() {
+    if (this_shard_id() != global_controller) {
+        return make_ready_future();
+    }
+    // abort the loop of the distributed data checking if it is running
+    if (!_global_controller_db->distributed_data_update.available()) {
+        if (!_global_controller_db->dist_data_update_aborter.abort_requested()) {
+            _global_controller_db->dist_data_update_aborter.request_abort();
```
Comment (psarna) [inline service/qos/service_level_controller.cc:308]: you don't need to wrap `request_abort` in a check - it's an idempotent operation, so you can just call it unconditionally

File: service/qos/service_level_controller.cc [hunk 3]
```diff
@@ -298,6 +298,22 @@ void service_level_controller::update_from_distributed_data(std::chrono::duratio
     }
 }
 
+future<> service_level_controller::stop_update_from_distributed_data() {
+    if (this_shard_id() != global_controller) {
+        return make_ready_future();
+    }
+    // abort the loop of the distributed data checking if it is running
+    if (!_global_controller_db->distributed_data_update.available()) {
```
Comment (psarna) [inline service/qos/service_level_controller.cc:306]: I think this check is also not really needed - requesting an abort if this future is ready should have no effect on anything anyway, so we may execute `request_abort` unconditionally

File: service/storage_service.cc [hunk 4]
```diff
@@ -1936,17 +1934,20 @@ future<> storage_service::decommission() {
             std::unordered_set<gms::inet_address> nodes_down;
             auto req = node_ops_cmd_request{node_ops_cmd::decommission_prepare, uuid, ignore_nodes, leaving_nodes, {}};
             try {
-                parallel_for_each(nodes, [&ss, &req, &nodes_unknown_verb, &nodes_down, uuid] (const gms::inet_address& node) {
-                    return ss._messaging.local().send_node_ops_cmd(netw::msg_addr(node), req).then([uuid, node] (node_ops_cmd_response resp) {
+                ss.send_node_ops_cmd_wrapped(nodes, req, [uuid, &nodes_unknown_verb, &nodes_down] (const gms::inet_address& node,future<node_ops_cmd_response> resp_fut) {
```
Comment (psarna) [inline service/storage_service.cc:1937]: To consider: there's potential to deduplicate the code even further. All 4 handlers do pretty much the same thing, except that they log a slightly different message. So instead of `send_node_ops_cmd_wrapped` you can actually have a helper that takes the following parameters: the verb ("decommission", "bootstrap", "replace", "removenode"), the list of unknown verbs and the list of nodes down, and works like that:
```cpp
try {
    resp_fut.get();
    slogger.debug("{}[{}]: Got prepare response from node={}", verb, uuid, node);
} catch (seastar::rpc::unknown_verb_error&) {
    slogger.warn("{}[{}]: Node {} does not support {} verb", verb, uuid, node, verb);
    nodes_unknown_verb.emplace(node);
} catch (seastar::rpc::closed_error&) {
    slogger.warn("{}[{}]: Node {} is down for node_ops_cmd verb", verb, uuid, node);
    nodes_down.emplace(node);
}
return make_ready_future<>();
```

File: service/storage_service.hh [hunk 5]
```diff
@@ -911,6 +911,37 @@ private:
...
     bool is_repair_based_node_ops_enabled();
+    using node_operations_observer =  noncopyable_function<future<>(const node_ops_cmd_request& req, storage_service& ss)>;
+    void register_node_operation_observer(node_operations_observer observer);
+private:
+    std::vector<node_operations_observer> _node_operations_observers;
+
+    using wrapped_node_ops_cmd_response_processor = noncopyable_function<future<>(const gms::inet_address&, future<node_ops_cmd_response>)>;
+    using node_ops_cmd_response_processor = noncopyable_function<future<>(const gms::inet_address&, node_ops_cmd_response)>;
+
+    future<> send_node_ops_cmd(auto&& nodes,node_ops_cmd_request &req, node_ops_cmd_response_processor resp_process) {
```
Comment (psarna) [inline service/storage_service.hh:922]: 1. nitpick: missing space after `auto&& nodes,`

2. Unless I'm mistaken, `send_node_ops_cmd` and `send_node_ops_cmd_wrapped` are already only called from within a seastar thread. So instead of allocating data with `do_with`, it would be better to explicitly mark these functions with a "needs to be called from a seastar thread context" comment and write their code as if it was inside a thread (so there's no need to use `do_with`). Note that you already assume that one of the parameters is alive during the whole call (`node_ops_cmd_request &req`), and that's because it's implicitly known that these functions are only called from seastar threads anyway.

File: service/storage_service.hh [hunk 6]
```diff
@@ -911,6 +911,37 @@ private:
...
+        return do_with(std::move(resp_process), [this, &nodes, &req] (const node_ops_cmd_response_processor& resp_process) {
+            return notify_observers(req).then([this, &nodes, &req, &resp_process] {
+                return parallel_for_each(nodes, [this, &resp_process, &req] (const gms::inet_address& node) {
+                    return send_node_ops_cmd_to_node(resp_process, node, req);
+                });
+            });
+        });
+    }
+
+    future<> send_node_ops_cmd_wrapped(auto&& nodes,node_ops_cmd_request &req, wrapped_node_ops_cmd_response_processor resp_process) {
```
Comment (psarna) [inline service/storage_service.hh:932]: ditto

File: service/storage_service.cc [hunk 7]
```diff
@@ -1868,11 +1868,9 @@ future<> storage_service::node_ops_cmd_heartbeat_updater(const node_ops_cmd& cmd
...
-            parallel_for_each(nodes, [this, ops, uuid, &req] (const gms::inet_address& node) {
-                return _messaging.local().send_node_ops_cmd(netw::msg_addr(node), req).then([ops, uuid, node] (node_ops_cmd_response resp) {
-                    slogger.info("{}[{}]: Got heartbeat response from node={}", ops, uuid, node);
-                    return make_ready_future<>();
-                });
+            send_node_ops_cmd(nodes, req, [ops, uuid, &req] (const gms::inet_address& node, node_ops_cmd_response) {
+                slogger.info("{}[{}]: Got heartbeat response from node={}", ops, uuid, node);
+                return make_ready_future<>();
             }).handle_exception([ops, uuid] (std::exception_ptr ep) {
                 slogger.warn("{}[{}]: Failed to send heartbeat: {}", ops, uuid, ep);
```
Comment (avikivity) [inline service/storage_service.cc:1875]: @asias please review this patch

File: service/storage_service.cc [hunk 8]
```diff
@@ -4011,5 +4011,14 @@ future<> storage_service::send_node_ops_cmd_to_node(const node_ops_cmd_response_
...
 }
 
+void storage_service::register_node_operation_observer(node_operations_observer observer) {
+        _node_operations_observers.emplace_back(std::move(observer));
+}
+
+future<> storage_service::notify_observers(const node_ops_cmd_request& req) {
+    return parallel_for_each(_node_operations_observers, [&req, this] (node_operations_observer& observer) {
+        return observer(req, *this);
+    });
```
Comment (avikivity) [inline service/storage_service.cc:4021]: I don't know if the point where we send/receive the command is the right one. We already have node status (normal/joining/leaving), perhaps we should observe where the state is maintained, not changed. This is more resilient against failures, and against new APIs.

Comment (avikivity) [reply service/storage_service.cc:4021]: /cc @asias

Comment (asias) [reply service/storage_service.cc:4021]: I think it is a bad idea to depend on the new node ops cmd infrastructure to do something when a node is decommissioned. 

We already have ways to listen for a node is decommissioned. We can use endpoint_lifecycle_subscriber::on_leave_cluster.

If you do not like the notifier, you can even check the gossip status of the node directly in your loop. For instance take a look: storage_service::restore_replica_count.

Also, should we take care of node that is removed by  `nodetool removenode`. With on_leave_cluster, both cases are handled. Maybe you care less about removenode because the node is DOWN anyway.

**Comment by asias** [comment]
@eliransin 

Did you see the problem even with the following patch? I think with the patch below the decommissioned node will be marked as down. Hopefully, the node will be excluded from your service level loop.

```
commit 0665d9c346170517e7e3fc16f45bcfac54e865cb
Author: Asias He <asias@scylladb.com>
Date:   Tue Jun 1 09:35:22 2021 +0800

    gossip: Handle nodes removed from live endpoints directly
    
    When a node is removed from the _live_endpoints list directly, e.g., a
    node being decommissioned, it is possible the node might not be marked
    as down in gossiper::failure_detector_loop_for_node loop before the loop
    exits. When the gossiper::failure_detector_loop loop starts again, the
    node will not be considered because it is not present in _live_endpoints
    list any more. As a result, the node will not be marked as down though
    gossiper::failure_detector_loop_for_node loop.
    
    To fix, we mark the nodes that are removed from _live_endpoints
    lists as down in the gossiper::failure_detector_loop loop.
    
    Fixes #8712
    
    Closes #8770
```

File: service/qos/service_level_controller.cc (hunk 2 above)
Comment (eliransin) [reply service/qos/service_level_controller.cc:308]: Will change.

File: service/storage_service.cc (hunk 4 above)
Comment (eliransin) [reply service/storage_service.cc:1937]: I will do this change if I keep the code.

File: service/storage_service.hh (hunk 5 above)
Comment (eliransin) [reply service/storage_service.hh:922]: Yes, it is a conceptual mistake on my part, I was trying to be prepared for the day this whole thread is co-routinized, 
however, it will be very similar in terms of objects life scope so I can do the change anyway :slightly_smiling_face:

File: service/storage_service.hh (hunk 6 above)
Comment (eliransin) [reply service/storage_service.hh:932]: will fix

File: service/storage_service.cc (hunk 8 above)
Comment (eliransin) [reply service/storage_service.cc:4021]: OK sure.
I guess that the subscriber is what I was looking for. I just missed it when I searched for a way to get notified.

File: service/qos/service_level_controller.cc (hunk 1 above)
Comment (eliransin) [reply service/qos/service_level_controller.cc:312]: To be prepared to the scenario of `start->stop->start`
I guess you think it doesn't worth being prepared for.

> @eliransin
> 
> Did you see the problem even with the following patch? I think with the patch below the decommissioned node will be marked as down. Hopefully, the node will be excluded from your service level loop.
> 
> ```
> commit 0665d9c346170517e7e3fc16f45bcfac54e865cb
> Author: Asias He <asias@scylladb.com>
> Date:   Tue Jun 1 09:35:22 2021 +0800
> 
>     gossip: Handle nodes removed from live endpoints directly
>     
>     When a node is removed from the _live_endpoints list directly, e.g., a
>     node being decommissioned, it is possible the node might not be marked
>     as down in gossiper::failure_detector_loop_for_node loop before the loop
>     exits. When the gossiper::failure_detector_loop loop starts again, the
>     node will not be considered because it is not present in _live_endpoints
>     list any more. As a result, the node will not be marked as down though
>     gossiper::failure_detector_loop_for_node loop.
>     
>     To fix, we mark the nodes that are removed from _live_endpoints
>     lists as down in the gossiper::failure_detector_loop loop.
>     
>     Fixes #8712
>     
>     Closes #8770
> ```

@asias 
I only need to know on the current node so IIUC this will not affect my code.
However, what do you think about the rest of the code? I am considering to break it into two separate patches, one that
refactors the storage_proxy parallel_for_each usage (the first patch).
And all of the rest I am going to change to implement using your and @psarna pointers above. Do you think the refactor is
beneficial?

File: service/qos/service_level_controller.cc (hunk 3 above)
Comment (eliransin) [reply service/qos/service_level_controller.cc:306]: Except it will invalidate the abort source (which I will have to recreate), unless we decide that stop always get **called** only 
after start and you can never restart this loop until you restart Scylla.

**Comment by eliransin** [comment]
> @eliransin
> 
> Did you see the problem even with the following patch? I think with the patch below the decommissioned node will be marked as down. Hopefully, the node will be excluded from your service level loop.
> 
> ```
> commit 0665d9c346170517e7e3fc16f45bcfac54e865cb
> Author: Asias He <asias@scylladb.com>
> Date:   Tue Jun 1 09:35:22 2021 +0800
> 
>     gossip: Handle nodes removed from live endpoints directly
>     
>     When a node is removed from the _live_endpoints list directly, e.g., a
>     node being decommissioned, it is possible the node might not be marked
>     as down in gossiper::failure_detector_loop_for_node loop before the loop
>     exits. When the gossiper::failure_detector_loop loop starts again, the
>     node will not be considered because it is not present in _live_endpoints
>     list any more. As a result, the node will not be marked as down though
>     gossiper::failure_detector_loop_for_node loop.
>     
>     To fix, we mark the nodes that are removed from _live_endpoints
>     lists as down in the gossiper::failure_detector_loop loop.
>     
>     Fixes #8712
>     
>     Closes #8770
> ```

@asias 
I only need to know on the current node so IIUC this will not affect my code.
However, what do you think about the rest of the code? I am considering to break it into two separate patches, one that
refactors the storage_proxy parallel_for_each usage (the first patch).
And all of the rest I am going to change to implement using your and @psarna pointers above. Do you think the refactor is
beneficial?

**Comment by asias** [comment]
> > @eliransin
> > Did you see the problem even with the following patch? I think with the patch below the decommissioned node will be marked as down. Hopefully, the node will be excluded from your service level loop.
> > ```
> > commit 0665d9c346170517e7e3fc16f45bcfac54e865cb
> > Author: Asias He <asias@scylladb.com>
> > Date:   Tue Jun 1 09:35:22 2021 +0800
> > 
> >     gossip: Handle nodes removed from live endpoints directly
> >     
> >     When a node is removed from the _live_endpoints list directly, e.g., a
> >     node being decommissioned, it is possible the node might not be marked
> >     as down in gossiper::failure_detector_loop_for_node loop before the loop
> >     exits. When the gossiper::failure_detector_loop loop starts again, the
> >     node will not be considered because it is not present in _live_endpoints
> >     list any more. As a result, the node will not be marked as down though
> >     gossiper::failure_detector_loop_for_node loop.
> >     
> >     To fix, we mark the nodes that are removed from _live_endpoints
> >     lists as down in the gossiper::failure_detector_loop loop.
> >     
> >     Fixes #8712
> >     
> >     Closes #8770
> > ```
> 
> @asias
> I only need to know on the current node so IIUC this will not affect my code.

Did you mean that only the node where nodetool decommission run was affected? What is the current node?

> However, what do you think about the rest of the code? I am considering to break it into two separate patches, one that
> refactors the storage_proxy parallel_for_each usage (the first patch).

To be honest, I do not like the extra indirection introduced by the helpers send_node_ops_cmd_to_node_wrapped and send_node_ops_cmd_to_node_wrapped,  and the extra wrapped_node_ops_cmd_response_processor and node_ops_cmd_response_processor.  The gain the helper to combine parallel_for_each and ms.send_node_ops_cmd gives is not that much in my view.

> And all of the rest I am going to change to implement using your and @psarna pointers above. Do you think the refactor is
> beneficial?

**Comment by eliransin** [comment]
> Did you mean that only the node where nodetool decommission run was affected? What is the current node?

yes, the decommissioned node itself is the one that is affected. I'll verify that the standard mechanism can help me with that,
I believe it will. Thanks.

> To be honest, I do not like the extra indirection introduced by the helpers send_node_ops_cmd_to_node_wrapped and send_node_ops_cmd_to_node_wrapped, and the extra wrapped_node_ops_cmd_response_processor and node_ops_cmd_response_processor. The gain the helper to combine parallel_for_each and ms.send_node_ops_cmd gives is not that much in my view.

I respect that, will not do this part at all :slightly_smiling_face:

File: service/endpoint_lifecycle_subscriber.hh [hunk 9]
```diff
@@ -63,29 +63,37 @@ public:
      * bootstrapped or "instajoins".
      *
      * @param endpoint the newly added endpoint.
+     * @param this_node true if the notification is regarging this node false
+     *                  otherwise
      */
-    virtual void on_join_cluster(const gms::inet_address& endpoint) = 0;
+    virtual void on_join_cluster(const gms::inet_address& endpoint, bool this_node) = 0;
```
Comment (asias) [inline service/endpoint_lifecycle_subscriber.hh:69]: Why this node.

File: service/qos/service_level_controller.cc [hunk 10]
```diff
@@ -410,4 +410,16 @@ future<> service_level_controller::do_remove_service_level(sstring name, bool re
     return make_ready_future();
 }
 
+void service_level_controller::on_join_cluster(const gms::inet_address& endpoint, bool this_node) { }
+
+void service_level_controller::on_leave_cluster(const gms::inet_address& endpoint, bool this_node) {
```
Comment (asias) [inline service/qos/service_level_controller.cc:415]: We can pass the ip address of this node to service_level_controller to avoid modifying this_node. It is weird and redundant.

Comment (eliransin) [reply service/qos/service_level_controller.cc:415]: I disagree. I think that exposing the fact that nodes are identified entirely by their IP is redundant. What if we will support IP change one day?

Comment (eliransin) [reply service/qos/service_level_controller.cc:415]: I could make `service::storage_service::get_broadcast_address()` public but it feels too intrusive for me.
If this is weird to you, I can add another subscription for local_endpoint_notifications. Do you think it is a better solution?

Comment (eliransin) [reply service/qos/service_level_controller.cc:415]: @asias does my last solution proposal sounds better?

Comment (asias) [reply service/qos/service_level_controller.cc:415]: There is no point to change the ip address of the node while decommissioning the node. We do not support that neither. 

IMO, It is over kill to add a another subscription for local_endpoint_notifications and it is unnecessary because we can know if the node is the node itself or not  using the endpoint parameter.

File: service/qos/service_level_controller.cc [hunk 11]
```diff
@@ -410,4 +410,16 @@ future<> service_level_controller::do_remove_service_level(sstring name, bool re
...
+    if (this_node && this_shard_id() == global_controller) {
```
Comment (asias) [inline service/qos/service_level_controller.cc:416]: So, request_abort is called either when a node is decommissioned or the node stops, right? Why not just stop it like we stop other things (e.g., ss.stop_transport()) in storage_service::decommission.

File: service/qos/service_level_controller.cc (hunk 10 above)
Comment (asias) [reply service/qos/service_level_controller.cc:415]: When we support changing the ip address in the middle without restarting a node, we probably need to change on_leave_cluster(inet_address endpoint)  to on_leave_cluster(node_id id) instead. We can still use the node_id to tell if the node is is_node.

File: service/qos/service_level_controller.cc (hunk 11 above)
Comment (eliransin) [reply service/qos/service_level_controller.cc:416]: I think that this coupling is unhealthy. It means that storage_service needs to know about every module that is dependent upon endpoints (or at least the local endpoint) life-cycle.
I don't have anything about doing it this way, I simply think it will strongly couple the `service_level_controller` and `storage_service` together. But if you think this is the best approach, I don't mind.

File: service/qos/service_level_controller.cc (hunk 10 above)
Comment (eliransin) [reply service/qos/service_level_controller.cc:415]: OK @asias fair enough. I will change it.

File: service/qos/service_level_controller.cc (hunk 11 above)
Comment (eliransin) [reply service/qos/service_level_controller.cc:416]: > So, request_abort is called either when a node is decommissioned or the node stops, right? Why not just stop it like we stop other things (e.g., ss.stop_transport()) in storage_service::decommission.

Here I took your advice, I will need to stop this process for other cases of leaving the cluster too :slightly_smiling_face:

Comment (asias) [reply service/qos/service_level_controller.cc:416]: Hi @eliransin, we can just pass the ip address to service_level_controller when we construct service_level_controller to avoid coupling with stotrage_service. I do not like coupling them together neither ;)

Comment (eliransin) [reply service/qos/service_level_controller.cc:416]: > Hi @eliransin, we can just pass the ip address to service_level_controller when we construct service_level_controller to avoid coupling with stotrage_service. I do not like coupling them together neither ;)

I have actually noticed that there is a utility function (which storage_service uses) that gives you the broadcast address.
Another version will come soon (I am testing it).

**Review by asias — APPROVED** [review]
Thanks. Looks good to me.

File: main.cc [hunk 12]
```diff
@@ -1224,6 +1224,8 @@ int main(int ac, char** av) {
             sl_controller.invoke_on_all([] (qos::service_level_controller& controller) {
                 controller.set_distributed_data_accessor(::static_pointer_cast<qos::service_level_controller::service_level_distributed_data_accessor>(
                         ::make_shared<qos::standard_service_level_distributed_data_accessor>(sys_dist_ks.local())));
+                auto& ss = service::get_local_storage_service();
+                ss.register_subscriber(&controller);
```
[the remark this answers is not in the document]
Comment (eliransin) [reply main.cc]: OK

**Comment by eliransin** [comment]
Changes in v3:
1. remove usage in get_local_storage_service in main function.
2. Don't use get_local_storage_service in the new code.

**Comment by eliransin** [comment]
ping, I think I addressed all issues here.

**Review by psarna — APPROVED** [review]
