### PR TITLE
commitlog: make_checked_file for segments, report and ignore other errors on shutdown

### LINKED ISSUE #8577: Scylla shutdown process stuck when Shutting down drain storage proxy
*Installation details*
Scylla version (or git commit hash): 4.6.dev-0.20210424.f7e00e781c2 with build-id cf643cfd81b2c4b5b659b84a6ba411aa1939581c
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0d88d7366cb227e2b (eu-north-1)
This is a short **alternator** longevity

At `2021-04-25 02:22:45.517` an Enospc nemesis started on node 4 (13.53.173.30 | 10.0.1.229). The nemesis deliberately fills the target node's machine, clean it and afterwards restarts the scylla service.
However, the restart command in this iteration failed on timeout (after 500 seconds). Looking at the node's log, it's seems that the process got stuck while hutting down drain storage proxy:
```
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 0] init - Shutting down CDC Generation Management service was successful
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 0] init - Shutting down repair message handlers
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 0] init - Shutting down repair message handlers was successful
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 0] init - Shutting down repair service
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 0] init - Shutting down repair service was successful
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 0] init - Shutting down drain storage proxy
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 0] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 0] hints_manager - Stopped
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 0] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 1] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 10] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 2] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 11] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 8] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 11] hints_manager - Stopped
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 7] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 5] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 7] hints_manager - Stopped
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 7] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 5] hints_manager - Stopped
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 6] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 12] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 6] hints_manager - Stopped
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 3] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 6] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 3] hints_manager - Stopped
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 8] hints_manager - Stopped
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 9] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 1] hints_manager - Stopped
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 10] hints_manager - Stopped
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 1] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 5] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 2] hints_manager - Stopped
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 2] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 3] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 11] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 8] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 9] hints_manager - Stopped
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 9] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 10] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 12] hints_manager - Stopped
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 12] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 13] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 13] hints_manager - Stopped
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 13] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 4] hints_manager - Asked to stop
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 4] hints_manager - Stopped
2021-04-25T02:24:10+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 4] hints_manager - Asked to stop
2021-04-25T02:24:13+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 12] hints_manager - Stopped
2021-04-25T02:24:13+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 10] hints_manager - Stopped
2021-04-25T02:24:13+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 0] hints_manager - Stopped
2021-04-25T02:24:13+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 2] hints_manager - Stopped
2021-04-25T02:24:13+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 4] hints_manager - Stopped
2021-04-25T02:24:13+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 11] hints_manager - Stopped
2021-04-25T02:24:13+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 7] hints_manager - Stopped
2021-04-25T02:24:13+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 5] hints_manager - Stopped
2021-04-25T02:24:13+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 9] hints_manager - Stopped
2021-04-25T02:24:13+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 8] hints_manager - Stopped
2021-04-25T02:24:13+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 1] hints_manager - Stopped
2021-04-25T02:24:13+00:00  alternator-3h-master-db-node-2c4eaef5-4 !INFO    | scylla:  [shard 13] hints_manager - Stopped
```

And at this point the messages from scylla stops. Comparing to one of the other nodes, the shutdown process suppose to continue int confirming that the drain storage proxy was successfully shut down, like so:
`2021-04-25T00:42:58+00:00  alternator-3h-master-db-node-2c4eaef5-1 !INFO    | scylla:  [shard 0] init - Shutting down drain storage proxy was successful`,
But node 4 never reached that stage.

Logs:
```
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                        Log links for testrun with test id 2c4eaef5-7fb1-4b4f-adb8-f462312ce0d6                                                                                                         |
+-----------------+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type    | Link                                                                                                                                                                                                                                                   |
+-----------------+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 20210425_024240 | grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/2c4eaef5-7fb1-4b4f-adb8-f462312ce0d6/20210425_024240/grafana-screenshot-longevity-alternator-3h-test-scylla-per-server-metrics-nemesis-20210425_024650-alternator-3h-master-monitor-node-2c4eaef5-1.png |
| 20210425_054051 | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/2c4eaef5-7fb1-4b4f-adb8-f462312ce0d6/20210425_054051/db-cluster-2c4eaef5.zip                                                                                                                            |
| 20210425_054051 | kubernetes  | https://cloudius-jenkins-test.s3.amazonaws.com/2c4eaef5-7fb1-4b4f-adb8-f462312ce0d6/20210425_054051/kubernetes-2c4eaef5.zip                                                                                                                            |
| 20210425_054051 | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/2c4eaef5-7fb1-4b4f-adb8-f462312ce0d6/20210425_054051/loader-set-2c4eaef5.zip                                                                                                                            |
| 20210425_054051 | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/2c4eaef5-7fb1-4b4f-adb8-f462312ce0d6/20210425_054051/monitor-set-2c4eaef5.zip                                                                                                                           |
| 20210425_054051 | sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/2c4eaef5-7fb1-4b4f-adb8-f462312ce0d6/20210425_054051/sct-runner-2c4eaef5.zip                                                                                                                            |
+-----------------+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by bhalevy**
Shutdown must never fail, otherwise it may cause hangs
as seen in https://github.com/scylladb/scylla/issues/8577.

This change wraps the file created in `allocate_segment_ex` in `make_checked_file` so that scylla will abort when failing to write to the commitlog files.

In case other errors are seen during shutdown, just log them and continue with shutting down to prevent scylla from hanging.

Fixes #8577

Test: unit(dev)
Signed-off-by: Benny Halevy <bhalevy@scylladb.com>

### CODE REVIEW

File: db/commitlog/commitlog.cc [hunk 1]
```diff
@@ -1698,13 +1698,16 @@ future<> db::commitlog::segment_manager::shutdown() {
         // Wait for all pending requests to finish. Need to sync first because segments that are
         // alive may be holding semaphore permits.
         auto block_new_requests = get_units(_request_controller, max_request_controller_units());
-        return sync_all_segments().then([this, block_new_requests = std::move(block_new_requests)] () mutable {
+        return sync_all_segments().then_wrapped([this, block_new_requests = std::move(block_new_requests)] (future<> f) mutable {
+            if (f.failed()) {
+                clogger.error("Syncing all segments failed during shutdown: {}. Continuing with shutdown anyway...", f.get_exception());
+            }
```
Comment (avikivity) [inline db/commitlog/commitlog.cc:1704]: How can we fail here? What error?

I/O errors should be caught by the commitlog I/O error handler. We can't perform a clean shutdown, since we may lose data.

If it's a non-I/O error, then what is it?

File: db/commitlog/commitlog.cc [hunk 2]
```diff
@@ -1713,10 +1716,9 @@ future<> db::commitlog::segment_manager::shutdown() {
                 return std::move(_reserve_replenisher).then_wrapped([this] (auto f) {
                     // Could be cleaner with proper seastar support
                     if (f.failed()) {
-                        _shutdown_promise->set_exception(f.get_exception());
-                    } else {
-                        _shutdown_promise->set_value();
+                        clogger.error("Reserve replenisher failed during shutdown: {}. Continuing with shutdown anyway...", f.get_exception());
```
Comment (avikivity) [inline db/commitlog/commitlog.cc:1719]: I see that replenish_reserve() already handles errors.

Comment (avikivity) [reply db/commitlog/commitlog.cc:1719]: btw, maybe badly, it will ignore a gate closed exception.

File: db/commitlog/commitlog.cc (hunk 1 above)
Comment (bhalevy) [reply db/commitlog/commitlog.cc:1704]: Hmm, according to https://github.com/scylladb/scylla/issues/8577#issue-874223808
> At 2021-04-25 02:22:45.517 an Enospc nemesis started on node 4 (13.53.173.30 | 10.0.1.229). The nemesis deliberately fills the target node's machine, clean it and afterwards restarts the scylla service.

File: db/commitlog/commitlog.cc (hunk 2 above)
Comment (bhalevy) [reply db/commitlog/commitlog.cc:1719]: you're right.  yet there is existing error handling code here that propagates the impossible to reach error to _shutdown_promise.

I'll remove this hunk.

File: db/commitlog/commitlog.cc (hunk 1 above)
Comment (avikivity) [reply db/commitlog/commitlog.cc:1704]: Yes, but what was the error?

File: db/commitlog/commitlog.cc (hunk 2 above)
Comment (avikivity) [reply db/commitlog/commitlog.cc:1719]: But let's fix replenish not to ignore the gate closed. Maybe that's the root cause.

File: db/commitlog/commitlog.cc (hunk 1 above)
Comment (bhalevy) [reply db/commitlog/commitlog.cc:1704]: sync_all_segments ends up calling `segment::sync -> segment::cycle` which reports `_file.dma_write` errors to the log.
If this is the case, we should see https://github.com/scylladb/scylla/blob/4c351ff26009ece329231560cbcb0b54a468da0a/db/commitlog/commitlog.cc#L846

Comment (bhalevy) [reply db/commitlog/commitlog.cc:1704]: @avikivity the question is what should be done if we can't ensure a clean shutdown?
Should the node just drain and hang?

Comment (avikivity) [reply db/commitlog/commitlog.cc:1704]: If there is an I/O error, we should isolate the node like we usually do. Provided we do that, it's okay to swallow the error (since the bad node can't affect the cluster without maintenance intervention). But shutting down cleanly isn't good, if the operator doesn't look at the logs, nobody will notice the error.

If it's not an I/O error, it should be fixed.

File: db/commitlog/commitlog.cc (hunk 2 above)
Comment (bhalevy) [reply db/commitlog/commitlog.cc:1719]: I don't think that's the root cause since
https://github.com/scylladb/scylla/blob/4c351ff26009ece329231560cbcb0b54a468da0a/db/commitlog/commitlog.cc#L1179
will throw in the then clause and the the error will propagate as an exceptional future here (that's a subtle difference between `with_gate` and `try_with_gate`, so it's not ignoring a possible gate_closed exception.

If it did, and with `_shutdown` not set to true in case `sync_all_segments` fails, it could stay in its `do_until` loop, but then we should see a warning coming from https://github.com/scylladb/scylla/blob/4c351ff26009ece329231560cbcb0b54a468da0a/db/commitlog/commitlog.cc#L1193
but we see no error or warning, according to https://github.com/scylladb/scylla/issues/8577#issue-874223808

File: db/commitlog/commitlog.cc (hunk 1 above)
Comment (bhalevy) [reply db/commitlog/commitlog.cc:1704]: @elcallio why don't we use `make_checked_file` in `db::commitlog::segment_manager::allocate_segment_ex`?
https://github.com/scylladb/scylla/blob/4c351ff26009ece329231560cbcb0b54a468da0a/db/commitlog/commitlog.cc#L1458

Comment (elcallio) [reply db/commitlog/commitlog.cc:1704]: I'm gonna go out on a limb and say because the (original) code was written long before check_file existed.

File: db/commitlog/commitlog.cc (hunk 2 above)
Comment (avikivity) [reply db/commitlog/commitlog.cc:1719]: Ah, yes. Those gotchas are terrible. Let's rewrite it as a coroutine (after we fix it).

**Review by elcallio — APPROVED** [review]
I'm ok with this, but it feels like more bandaid/added complexity. A better long-term solution would be to rewrite it so segments that cause IO exceptions on sync etc simply are "released" - i.e. left on disk, and we still ensure trying to clean as much as possible of other segments (won't do anything for nemesis, but that is not really real world).

**Comment by bhalevy** [comment]
@scylladb/scylla-maint please merge

File: db/commitlog/commitlog.cc (hunk 1 above)
Comment (avikivity) [reply db/commitlog/commitlog.cc:1707]: Maybe we should use make_checked_file() then?

Comment (bhalevy) [reply db/commitlog/commitlog.cc:1707]: @avikivity: this change now uses `make_checked_file` wrapping the opened file in `allocate_segment_ex`

**Comment by avikivity** [comment]
@bhalevy please update the cover letter, it is outdated.

**Comment by bhalevy** [comment]
> @bhalevy please update the cover letter, it is outdated.

@avikivity cover letter updated.

**Comment by bhalevy** [comment]
@avikivity ping

**Comment by avikivity** [comment]
The title is now wrong.

Also, @elcallio wants to review it.

**Comment by elcallio** [comment]
I stand by what I said before: I'm ok with this, but it should be revisited and reduced to just propagating the exception(s), not aborting. But since the various tasks here are still a tangled mess, why not use axes on them...

**Comment by bhalevy** [comment]
> I stand by what I said before: I'm ok with this, but it should be revisited and reduced to just propagating the exception(s), not aborting. But since the various tasks here are still a tangled mess, why not use axes on them...

@elcallio what do you refer to in "it should be revisited" above?
The whole point in using make_check_file here was to abort on disk errors.
We do that also when writing sstables.

Not aborting but rather propagating the exception requires rigorous testing that rejecting queries this way works flawlessly.
I think it's a good goal to shoot for but we're not there.
We can open a github issue for that as a follow-up.

**Comment by elcallio** [comment]
That is what I mean with "revisited".

**Comment by bhalevy** [comment]
@avikivity / @scylladb/scylla-maint let's merge this PR then.

**Review by nyh — APPROVED** [review]
I'll commit this. @bhalevy, @elcallio suggested that we should create a new issue on the remaining improvements that can be done. If you understood what improvements he suggested, and agree with them, then please open a new issue because this commit will close the existing one.
