### PR TITLE
raft ropology: prevent crashes of multiple nodes

### LINKED ISSUE #27987: multiple consecutive group0 leaders can chain-crash until there is no majority
Consider a recent customer issues:
- the topology somehow ended up with a `left` node for which there still was a `leave` (decommission) request in the topology,
- the topology coordinator hit segfault in
https://github.com/scylladb/scylladb/blob/e03d24e3f399480af427b664af14957bc3283e2e/service/topology_coordinator.cc#L2271
after using `nullptr` returned by `_topo_sm._topology.find(id)`,
- the following group0 leaders kept crashing in the same way until there was no majority.

There clearly is a bug. Having such a node in topology shouldn't be possible, or it should be handled properly. However, another problem is that even in the presence of such a bug there is no need to chain-crash multiple leaders. Note that with dynamic voters no more than 3 nodes can crash, but it can still cause availability issues in some clusters. It would be much better to raise a non-fatal internal error in such a case, so that the topology coordinator will keep failing in a loop, and the node won't crash.

We could try to make the topology coordinator (or the group0 leader in general) as "crash-free" as possible when it comes to deterministic crashes caused by an unexpected state of the state machine. A simple first step would be to replace all `SCYLLA_ASSERTS`s and `on_fatal_internal_error`s with `fatal_internal_error`s. We can also look for places like the one in `cancel_all_requests` above.

cc @scylladb/core-cluster

### PR DESCRIPTION
**Pull request by patjed41**
Some assertions in the Raft-based topology are likely to cause crashes of
multiple nodes due to the consistent nature of the Raft-based code. If the
failing assertion is executed in the code run by each follower (e.g., the code
reloading the in-memory topology state machine), then all nodes can crash. If
the failing assertion is executed only by the leader (e.g., the topology
coordinator fiber), then multiple consecutive group0 leaders will chain-crash
until there is no group0 majority.

Crashing multiple nodes is much more severe than necessary. It's enough to
prevent the topology state machine from making more progress. This will
naturally happen after throwing a runtime error. The problematic fiber will be
killed or will keep failing in a loop. Note that it should be safe to block
the topology state machine, but not the whole group0, as the topology state
machine is mostly isolated from the rest of group0.

We replace some occurrences of `on_fatal_internal_error` and `SCYLLA_ASSERT`
with `on_internal_error`. These are not all occurrences, as some fatal
assertions make sense, for example, in the bootstrap procedure.

We also raise an internal error to prevent a segmentation fault in a few places.

Fixes #27987

Backporting this PR is not required, but we can consider it at least for 2026.1
because:
- it is LTS,
- the changes are low-risk,
- there shouldn't be many conflicts.

### CODE REVIEW

File: service/topology_coordinator.cc [hunk 1]
```diff
@@ -3631,7 +3657,7 @@ class topology_coordinator : public endpoint_lifecycle_subscriber
         try {
             co_await _vb_coordinator->run();
         } catch (...) {
-            on_fatal_internal_error(rtlogger, format("unhandled exception in view_building_coordinator::run(): {}", std::current_exception()));
+            on_internal_error(rtlogger, format("unhandled exception in view_building_coordinator::run(): {}", std::current_exception()));
         }
         co_await _lifecycle_notifier.unregister_subscriber(_vb_coordinator.get());
```
Comment (tgrabiec) [inline service/topology_coordinator.cc:3667]: This one probably needs some cleanup (unregister from _lifecycle_notifier), or a retry loop.

Comment (patjed41) [reply service/topology_coordinator.cc:3667]: I looked more carefully at `view_building_coordinator::run()`, and it looks like this function cannot really throw unless the node is shutting down, and then `on_fatal_internal_error` makes sense. The same pattern is in `run_topology_coordinator()` and `topology_coordinator::run()`. There also is `on_fatal_internal_error`: https://github.com/scylladb/scylladb/blob/a04dbac369a705b2784da27a7979822595a3d5ed/service/topology_coordinator.cc#L4412
So, I should probably take the same approach for both the topology coordinator and the view building coordinator. I'm currently more inclined to keep both `on_fatal_internal_error`s. Wdyt?

**Comment by patjed41** [comment]
v2: restored `on_fatal_internal_error(rtlogger, format("unhandled exception in view_building_coordinator::run(): {}", std::current_exception()));`

File: service/topology_coordinator.cc (hunk 1 above)
Comment (patjed41) [reply service/topology_coordinator.cc:3667]: I restored this `on_fatal_internal_error`.

Comment (tgrabiec) [reply service/topology_coordinator.cc:3667]: Right. This exception is in the cleanup flow, exceptions during normal execution are handled inside run() and cause retries.

File: db/system_keyspace.cc [hunk 2]
```diff
@@ -1714,7 +1714,9 @@ std::unordered_set<dht::token> decode_tokens(const set_type_impl::native_type& t
     std::unordered_set<dht::token> tset;
     for (auto& t: tokens) {
         auto str = value_cast<sstring>(t);
-        SCYLLA_ASSERT(str == dht::token::from_sstring(str).to_sstring());
+        if (str != dht::token::from_sstring(str).to_sstring()) {
```
Comment (gusev-p) [inline db/system_keyspace.cc:1717]: (out of scope of this PR) Maybe we should consider introducing another macro? `SCYLLA_ENSURE`, `SCYLLA_BUG_ON` or something. The `on_internal_error`api is not very convenient to use. The syntax could be

`SCYLLA_ENSURE(str == dht::token::from_sstring(str).to_sstring(), str)` - use some default logger, macro params are forwarded to `format("on_internal_error, args: {}, ...")`

Pros:
* more compact syntax
* no need to invert the condition
* no need to specify the logger
* not need for custom message -- it's clear what the problem is from the source code line:column reference

Comment (patjed41) [reply db/system_keyspace.cc:1717]: Yes, we could consider that.

`SCYLLA_ASSERT` is much more convenient than `on_internal_error` and using it is sometimes incorrect for reasons not obvious to everyone. That's a bad combination leading to mistakes.
