### PR TITLE
Fix use-after-free when queue reader is destroyed before its handle

### LINKED ISSUE #10528: heap use-after-free when destroying shared repair writer
seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-debug/10/artifact/logs-full.debug.001/1652111820147_bootstrap_test.py%3A%3ATestBootstrap%3A%3Atest_manual_bootstrap/node2.log
```
==4404==ERROR: AddressSanitizer: heap-use-after-free on address 0x6110000c5a50 at pc 0x000013dbb2ee bp 0x7ff45ee331b0 sp 0x7ff45ee331a8 READ of size 8 at 0x6110000c5a50 thread T1 (reactor-1)
 #0 0x13dbb2ed (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x13dbb2ed)
 #1 0x13dbb132 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x13dbb132)
 #2 0x14ef6ced (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x14ef6ced)
 #3 0x14e9bdfe (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x14e9bdfe)
 #4 0x14e9bb93 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x14e9bb93)
 #5 0x14e9c2d0 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x14e9c2d0)
 #6 0x18997bc8 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x18997bc8)
 #7 0x189976a8 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x189976a8)
 #8 0x189976e0 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x189976e0)
 #9 0x1885ce0c (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1885ce0c)
 #10 0x1885db99 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1885db99)
 #11 0x18863b13 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x18863b13)
 #12 0x18863c40 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x18863c40)
 #13 0x1886a519 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1886a519)
 #14 0x1886a40a (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1886a40a)
 #15 0x1886a1b2 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1886a1b2)
 #16 0x1886a16d (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1886a16d)
 #17 0x1886a13d (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1886a13d)
 #18 0x1888887a (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1888887a)
 #19 0x189dbb38 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x189dbb38)
 #20 0x189dbb70 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x189dbb70)
 #21 0x1886345c (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1886345c)
 #22 0x189c1760 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x189c1760) #23 0x189c25f0 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x189c25f0)
 #24 0x189c2802 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x189c2802)
 #25 0x13dd2618 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x13dd2618)
 #26 0x13dd37c8 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x13dd37c8)
 #27 0x13dd3528 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x13dd3528)
 #28 0x1a31866e (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1a31866e)
 #29 0x1a31ece6 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1a31ece6)
 #30 0x1a323952 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1a323952)
 #31 0x1a3fc196 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1a3fc196)
 #32 0x1a3fadf2 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1a3fadf2)
 #33 0x1a3faca2 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1a3faca2)
 #34 0x1a3fa2f2 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1a3fa2f2)
 #35 0x1451c99a (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1451c99a)
 #36 0x1a226c0b (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1a226c0b)
 #37 0x7ff465c052a4 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libreloc/libpthread.so.0+0x92a4)
 #38 0x7ff46510e322 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libreloc/libc.so.6+0x100322)

0x6110000c5a50 is located 208 bytes inside of 216-byte region [0x6110000c5980,0x6110000c5a58) freed by thread T1 (reactor-1) here:
 #0 0x13c6d487 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x13c6d487)
 #1 0x14f1e508 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x14f1e508)
 #2 0x18863b0a (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x18863b0a)

previously allocated by thread T1 (reactor-1) here:
 #0 0x13c6ca87 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x13c6ca87)
 #1 0x14ef6f8b (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x14ef6f8b)
 #2 0x14e9cc4a (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x14e9cc4a)
 #3 0x187b5f3b (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x187b5f3b)
 #4 0x18881282 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x18881282)
 #5 0x189db6a6 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x189db6a6)
 #6 0x189db2a8 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x189db2a8)

Thread T1 (reactor-1) created by T0 here:
 #0 0x13ba5e46 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x13ba5e46)
 #1 0x1a2273e0 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1a2273e0)
 #2 0x1a226e49 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1a226e49)
 #3 0x1a605455 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1a605455)
 #4 0x1a603de6 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1a603de6)
 #5 0x1a60446f (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1a60446f)
 #6 0x1a467e08 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1a467e08)
 #7 0x1a340134 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1a340134)
 #8 0x1a345789 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1a345789)
 #9 0x1a0e408b (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1a0e408b)
 #10 0x1a0e2055 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x1a0e2055)
 #11 0x13c71dff (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x13c71dff)
 #12 0x14148e26 (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x14148e26)

SUMMARY: AddressSanitizer: heap-use-after-free (/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libexec/scylla+0x13dbb2ed)
Shadow bytes around the buggy address:
0x0c2280010af0: fd fd fd fd fd fd fd fd fd fd fd fa fa fa fa fa
0x0c2280010b00: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
0x0c2280010b10: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
0x0c2280010b20: fd fd fd fd fa fa fa fa fa fa fa fa fa fa fa fa
0x0c2280010b30: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd =>
0x0c2280010b40: fd fd fd fd fd fd fd fd fd fd[fd]fa fa fa fa fa
0x0c2280010b50: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
0x0c2280010b60: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
0x0c2280010b70: fd fd fd fd fd fa fa fa fa fa fa fa fa fa fa fa
0x0c2280010b80: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
0x0c2280010b90: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fa fa

Shadow byte legend (one shadow byte represents 8 application bytes):
Addressable: 00
Partially addressable: 01 02 03 04 05 06 07
Heap left redzone: fa
Freed heap region: fd
Stack left redzone: f1
Stack mid redzone: f2
Stack right redzone: f3
Stack after return: f5
Stack use after scope: f8
Global redzone: f9
Global init order: f6
Poisoned by user: f7
Container overflow: fc
Array cookie: ac
Intra object redzone: bb
ASan internal: fe
Left alloca redzone: ca
Right alloca redzone: cb
Shadow gap: cc

 ==4404==ABORTING Aborting on shard 1. Backtrace: 0x13bdb510 0x1a488cfd 0x1a4888fc 0x1a2f99e4 0x1a3254ce 0x1a3f9e3c 0x1a3fa08d 0x1a3f9eba 0x7ff465c0fa1f /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libreloc/libc.so.6+0x3d2a1 /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libreloc/libc.so.6+0x268a3
0x13c56c3e 0x13c54b6b 0x13c3c1cf 0x13c3bc55 0x13c3c91b 0x13dbb2ed 0x13dbb132 0x14ef6ced 0x14e9bdfe 0x14e9bb93 0x14e9c2d0 0x18997bc8 0x189976a8 0x189976e0 0x1885ce0c 0x1885db99 0x18863b13 0x18863c40 0x1886a519 0x1886a40a 0x1886a1b2 0x1886a16d 0x1886a13d 0x1888887a 0x189dbb38 0x189dbb70 0x1886345c 0x189c1760 0x189c25f0 0x189c2802 0x13dd2618 0x13dd37c8 0x13dd3528 0x1a31866e 0x1a31ece6 0x1a323952 0x1a3fc196 0x1a3fadf2 0x1a3faca2 0x1a3fa2f2 0x1451c99a 0x1a226c0b /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/a2901a376daa7468e52b69593153940afab02347/scylla/libreloc/libpthread.so.0+0x92a4 /jenkins/workspace/scylla-master/dtest
```

### PR DESCRIPTION
**Pull request by bhalevy**
The handle must not point at this reader implementation after it's destroyed.

This fixes use-after-free when the queue_reader_v2
is destroyed first as repair_writer_impl::_queue_reader,
before repair_writer_impl::_mq is destroyed.
    
The issue was introduced in 39205917a8d77ebd4608f95afd0fb40ab38d6c0a
in the definition of `repair_writer_impl`.

Fixes #10528

While at it, fix also an ignored exceptional future seen in the test:
`repair_additional_test.py::TestRepairAdditional::test_repair_kill_3`

### CODE REVIEW

**Review by mikolajsieluzycki — APPROVED** [review]
LGTM based on the description of the problem.

**Comment by avikivity** [comment]
@asias please review (patch 1)

**Comment by avikivity** [comment]
also @gleb-cloudius

**Comment by asias** [comment]
Looks good to me.  Btw, do_make_sink_source is used on the slow path. Perhaps we can coroutine do_make_sink_source to make it clear and safer.

**Comment by bhalevy** [comment]
> Looks good to me. Btw, do_make_sink_source is used on the slow path. Perhaps we can coroutine do_make_sink_source to make it clear and safer.

Coroutinizing `do_make_sink_source` sounds good as a followup.

**Comment by bhalevy** [comment]
@gleb-cloudius ping.  Please review first patch (f8b4a7149f6a6f417880f40f98c6ee055d2def7b).

File: message/messaging_service.cc [hunk 1]
```diff
@@ -838,9 +838,12 @@ do_make_sink_source(messaging_verb verb, uint32_t repair_meta_id, shared_ptr<mes
...
         return rpc_handler(*rpc_client, repair_meta_id, sink).then_wrapped([sink, rpc_client] (future<rpc::source<SourceType>> source) mutable {
-            return (source.failed() ? sink.close() : make_ready_future<>()).then([sink = std::move(sink), source = std::move(source)] () mutable {
-                return make_ready_future<value_type>(value_type(std::move(sink), std::move(source.get0())));
-            });
+            if (source.failed()) {
+                return make_exception_future<value_type>(source.get_exception()).finally([sink = std::move(sink), rpc_client = std::move(rpc_client)] () mutable {
+                    return sink.close().finally([sink] {});
+                });
+            }
+            return make_ready_future<value_type>(value_type(std::move(sink), std::move(source.get0())));
```
Comment (gleb-cloudius) [inline message/messaging_service.cc:846]: If you touch this code wouldn't it be better to co-routinize it?

Comment (bhalevy) [reply message/messaging_service.cc:846]: Yes, see https://github.com/scylladb/scylla/pull/10591#issuecomment-1129577691
This is tangential to this PR

Comment (gleb-cloudius) [reply message/messaging_service.cc:846]: I do not see why it should be done as a follow up. This patch makes the code even more complicated and making it a co-routine will simplify it instead. Actually co-routinize it will probably solve the problem.

Comment (bhalevy) [reply message/messaging_service.cc:846]: I'm not sure its much simpler (if you want to return a possible sink.close() error as nested exception).
Something like this:
```c++
    using value_type = std::tuple<rpc::sink<SinkType>, rpc::source<SourceType>>;
    auto sink = co_await rpc_client->make_stream_sink<netw::serializer, SinkType>();
    auto rpc_handler = rpc->make_client<rpc::source<SourceType> (uint32_t, rpc::sink<SinkType>)>(verb);
    auto source_fut = co_await coroutine::as_future(rpc_handler(*rpc_client, repair_meta_id, sink));
    if (source_fut.failed()) {
        auto ex = source_fut.get_exception();
        try {
            co_await sink.close();
        } catch (...) {
            std::throw_with_nested(std::move(ex));
        }
        co_return coroutine::exception(std::move(ex));
    }
    co_return value_type(std::move(sink), std::move(source_fut.get0()));
```

Comment (gleb-cloudius) [reply message/messaging_service.cc:846]: Your original fix does not return nested exception, no? Do not remember what finally does if body throws. But the co-routine code looks better to me.

Comment (bhalevy) [reply message/messaging_service.cc]: ok, just passed testing (unit(dev) + repair_additional_test.py::TestRepairAdditional::test_repair_kill_3(debug)), pushed v2 with coroutine.

**Comment by bhalevy** [comment]
In v2:
- fixed ignored future in do_make_sink_source using a coroutine.
- rebased + retested
  - unit(dev) + repair_additional_test.py::TestRepairAdditional::test_repair_kill_3(debug)

**Review by gleb-cloudius — APPROVED** [review]

**Comment by bhalevy** [comment]
@scylladb/scylla-maint please merge.  This blocks many dtests in debug mode.
