### PR TITLE
Fix filtering static columns on empty partitions

### LINKED ISSUE #5248: Filtering on a static column in an empty partition is incorrect
While debugging my weekend project on rewriting restrictions I found a test case for filtering which does not work correctly:
```cql
CREATE TABLE t (p int, c int, s int static, PRIMARY KEY(p, c));
INSERT INTO t (p, s) VALUES (1, 1);
SELECT * FROM t WHERE s = 2 ALLOW FILTERING;

 p | c    | s
---+------+---
 1 | null | 1

```
The problem is that an otherwise empty partition can still have a valid static column. Filtering didn't take that fact into account and only filtered full-fledged rows, which may a result in an intruder like the one above sneaking in.

I have the solution ready along with a test case, I'll post it today.

### PR DESCRIPTION
**Pull request by psarna**
An otherwise empty partition can still have a valid static column.
Filtering didn't take that fact into account and only filtered
full-fledged rows, which may result in non-matching rows being returned
to the client.

Fixes #5248 

@nyh @avikivity @eliransin

### CODE REVIEW

**Comment by psarna** [comment]
Tests: unit(dev)
Branches: 3.0, 3.1

**Comment by psarna** [comment]
Changelog after the force push:
 * added a test case for filtering over a clustering key value, when a static column exists and the partition is empty
 * add handling the case above

File: cql3/selection/selection.cc [hunk 1]
```diff
@@ -395,14 +395,17 @@ bool result_set_builder::restrictions_filter::do_filter(const selection& selecti
     }
 
     auto static_row_iterator = static_row.iterator();
-    auto row_iterator = row.iterator();
+    auto row_iterator = row ? std::optional<query::result_row_view::iterator_type>(row->iterator()) : std::nullopt;
```
Comment (nyh) [inline cql3/selection/selection.cc]: I'm surprised this syntax worked - the alternatives don't have the same type...

File: cql3/selection/selection.cc [hunk 2]
```diff
@@ -395,14 +395,17 @@ bool result_set_builder::restrictions_filter::do_filter(const selection& selecti
...
     auto non_pk_restrictions_map = _restrictions->get_non_pk_restriction();
     for (auto&& cdef : selection.get_columns()) {
         switch (cdef->kind) {
         case column_kind::static_column:
             // fallthrough
         case column_kind::regular_column: {
-            auto& cell_iterator = (cdef->kind == column_kind::static_column) ? static_row_iterator : row_iterator;
+            if (cdef->kind == column_kind::regular_column && !row_iterator) {
```
Comment (nyh) [inline cql3/selection/selection.cc]: Nitpick: If you just switched the two "case"s (static_column and regular_column), and which falls through to which, you wouldn't need to check cdef-kind here again. The if(!row_iterator) could be just in the regular_column case.

Comment (psarna) [reply cql3/selection/selection.cc]: Yeah - it was a concious decision. I felt tempted to simply switch the cases, but I think that it will make the code much less backport-friendly and could easily lead to incorrect backports, so I went with this slightly longer way. I believe the compiler will take care of generating optimal code from this one as well.

File: cql3/selection/selection.cc (hunk 1 above)
Comment (psarna) [reply cql3/selection/selection.cc]: The ternary operator assumes it will return the type of the first alternative, and if the second one is implicitly convertible to that type as well, it will work fine. (that's why I explicitly specified the type in the first alternative instead of:
```cpp
std::optional<query::result_row_view::iterator_type> row_iterator = row ? row->iterator() : std::nullopt;
```
the one above wouldn't work.
