### PR TITLE
alternator: Fix EQ operator for sets

### LINKED ISSUE #5021: Alternator: in "Expect" conditional operations, wrong equality check for sets
In the handling of Expect (conditional operations), the test for EQ (equality) of set values is wrong: we just compare the stored JSON representation. But because sets do not have order, we can have two different JSON representations for the same set, and wrongly conclude these are different sets.

We have an xfailing test - `test_update_expected_1_eq_set` - to reproduce this bug.

To fix this bug we need to change the EQ implementation to compare sets without regard to item order. This will require parsing the the serialized JSON stored for the value (the second JSON, the one given in the query, is already parsed with the entire query).

A possible optimization of the above is to always keep the stored JSON value sorted in some particular way (e.g., lexicographically). The set will need to be sorted when first assigned, and when modified (e.g., the ADD operation). If we do this we don't need to parse or sort this JSON so the comparison is faster. But I don't know if it's worth optimizing this case. Moreover, we can't do this optimization if we ever change our implementation of sets to use a CRDT instead of serialized JSON.

### PR DESCRIPTION
**Pull request by psarna**
Checking the EQ relation for alternator attributes is usually performed
simply by comparing underlying JSON objects, but sets (SS, BS, NS types)
need a special routine, as we need to make sure that sets stored in
a different order underneath are still equal, e.g:
```python
[1, 3, 2] == [1, 2, 3]
```

Fixes #5021

### CODE REVIEW

File: alternator/conditions.cc [hunk 1]
```diff
@@ -143,9 +143,44 @@ static void verify_operand_count(const rjson::value* array, const size_check& ex
...
+    const rjson::value* set2 = unwrap_set(s2).second;
+
+    if (!set1 || !set2) {
+        return !set1 && !set2;
+    }
+    if (set1->Size() != set2->Size()) {
+        return false;
+    }
+    std::set<rjson::value, rjson::single_value_comp> set1_raw;
+    for (auto it = set1->Begin(); it != set1->End(); ++it) {
```
Comment (dekimir) [inline alternator/conditions.cc]: Nit: isn't there a `set` constructor that takes a pair of iterators?

Comment (psarna) [reply alternator/conditions.cc]: there is, but copying an rjson value must be explicit, so it would fail. While we're at it, I didn't really like the fact that I need to actually copy the rjson value just to add it to a set, but I decide to ignore it as it's probably not a super hot path. I changed my mind though, I'll send v2 which uses a set of pointers, so that copying is elided.

Comment (psarna) [reply alternator/conditions.cc]: done

File: alternator/rjson.cc [hunk 2]
```diff
@@ -113,6 +113,48 @@ void push_back(rjson::value& base_array, rjson::value&& item) {
...
+       auto r2_type = r2.GetType();
+       switch (r1_type) {
+       case rjson::type::kNullType:
+           return r1_type < r2_type;
+       case rjson::type::kFalseType:
+           return r1_type < r2_type;
+       case rjson::type::kTrueType:
+           return r1_type < r2_type;
+       case rjson::type::kObjectType:
+           throw rjson::error("Object type comparison is not supported");
```
Comment (nyh) [inline alternator/rjson.cc]: So, if I r1 is True and r2 is an object, the result is 1, but if it's the opposite order - r1 is object and r2 is true, the result is an exception? This doesn't make any sense....
Also, throwing an exception like this will cause - unless caught - the user to experience and "internal error" instead of a normal API error.

File: alternator/rjson.cc [hunk 3]
```diff
@@ -113,6 +113,48 @@ void push_back(rjson::value& base_array, rjson::value&& item) {
...
+       case rjson::type::kArrayType:
+           throw rjson::error("Array type comparison is not supported");
+       case rjson::type::kStringType: {
+           const size_t r1_len = r1.GetStringLength();
+           const size_t r2_len = r2.GetStringLength();
```
Comment (nyh) [inline alternator/rjson.cc]: But we just verified that r1 is a string - and here we also assume r2 is a string as well... How can we assume this?

File: alternator/rjson.cc [hunk 4]
```diff
@@ -113,6 +113,48 @@ void push_back(rjson::value& base_array, rjson::value&& item) {
...
+           size_t len = std::min(r1_len, r2_len);
+           int result = std::strncmp(r1.GetString(), r2.GetString(), len);
+           return result < 0 || (result == 0 && r1_len < r2_len);
+       }
+       case rjson::type::kNumberType: {
+           if (r1_type != r2_type) {
+               throw rjson::error("All numbers in a set should have the same type");
```
Comment (nyh) [inline alternator/rjson.cc]: What "set"?
And why is this r1_type != r2_type done only for numbertype, and not as the first thing in this function?
And again, you'll need to catch this exception so the user don't see internal errors).

File: alternator/rjson.cc [hunk 5]
```diff
@@ -113,6 +113,48 @@ void push_back(rjson::value& base_array, rjson::value&& item) {
...
+           }
+           if (r1.IsDouble()) {
```
Comment (nyh) [inline alternator/rjson.cc]: These if()s, inside a switch(), are so strange - don't all these IsDouble, IsInt, etc. correspond to something that could be used in the switch()

File: alternator/conditions.cc [hunk 6]
```diff
@@ -143,9 +143,50 @@ static void verify_operand_count(const rjson::value* array, const size_check& ex
...
+};
+
+// It's not enough to compare underlying JSON objects when comparing sets,
+// as internally they're stored in an array, and the order of elements is
+// not important in set equality. See issue #5021
+static bool check_EQ_for_sets(const rjson::value& s1, const rjson::value& s2) {
+    const rjson::value* set1 = unwrap_set(s1).second;
+    const rjson::value* set2 = unwrap_set(s2).second;
+
+    if (!set1 || !set2) {
```
Comment (nyh) [inline alternator/conditions.cc]: Please add a comment what you're checking here and why, it's very unclear. What does !set1 even mean? You only call this function if both objects are really sets, and of the same type. Can !set1 happen - when? And why is !set && !set2 the proper return value?

File: alternator/conditions.cc [hunk 7]
```diff
@@ -143,9 +143,50 @@ static void verify_operand_count(const rjson::value* array, const size_check& ex
...
+        return !set1 && !set2;
+    }
+    if (set1->Size() != set2->Size()) {
+        return false;
+    }
+    std::set<const rjson::value*, rjson_engaged_ptr_comp> set1_raw;
+    for (auto it = set1->Begin(); it != set1->End(); ++it) {
+        set1_raw.insert(&*it);
```
Comment (nyh) [inline alternator/conditions.cc]: As I commented earlier, if this insert() sees an item with the wrong type, it can cause an "internal server error" instead of a normal invlaidation. This is not great (although I agree nobody will ever reach this case anyway in a real application.

File: alternator/rjson.cc [hunk 8]
```diff
@@ -113,6 +113,48 @@ void push_back(rjson::value& base_array, rjson::value&& item) {
 
 }
 
+bool single_value_comp::operator()(const rjson::value& r1, const rjson::value& r2) const {
+       auto r1_type = r1.GetType();
+       auto r2_type = r2.GetType();
+       switch (r1_type) {
+       case rjson::type::kNullType:
+           return r1_type < r2_type;
```
[the remark this answers is not in the document]
Comment (psarna) [reply alternator/rjson.cc]: As for this one - null compares less to all other types, except other nulls (to which it is equal). I'm using the fact that kNullType is the smallest value in this enum.

File: alternator/rjson.cc (hunk 2 above)
Comment (psarna) [reply alternator/rjson.cc]: right... something is off here, unfortunately this code is no longer fresh in my mind at all. I'll take a look at it all and perhaps fix these issues as a separate patch, unrelated to this series.

File: alternator/rjson.cc (hunk 3 above)
Comment (psarna) [reply alternator/rjson.cc]: we can't, it's a bug (not quite reachable now since we currently use this comparison for instances of the same type only, but it's nonetheless a bug)

File: alternator/rjson.cc (hunk 5 above)
Comment (psarna) [reply alternator/rjson.cc]: This code is taken straight from rjson internal implementations of its visitors. Using anything else was either not possible or relying on some undocumented internals, I don't remember which one.

File: alternator/rjson.cc (hunk 8 above)
[the remark this answers is not in the document]
Comment (nyh) [reply alternator/rjson.cc]: If this is what you want to do (I don't know why you want this order specifically), you can also write r1_type != r2_type (so not to rely on the enum order - unless you really want that?) and a comment explaining what it is you're trying to do.

File: alternator/rjson.cc (hunk 2 above)
Comment (nyh) [reply alternator/rjson.cc]: Ok, makes sense. So I'll commit your next version without insisting you fix these pre-existing problems now (although, maybe we should have an issue about it to remember it? Or something?)

Comment (psarna) [reply alternator/rjson.cc]: I vaguely remember that this type comparison was added as a "smart" way of using the fact that `kNullType < kFalseType < kTrueType`... well, it doesn't look that smart any more once you consider comparing `kTrueType` against `kObjectType`...

File: alternator/rjson.cc (hunk 4 above)
Comment (psarna) [reply alternator/rjson.cc]: >  And why is this r1_type != r2_type done only for numbertype, and not as the first thing in this function?

That's not that simple, since some types can compare against each other, e.g. `kFalseType < kTrueType`. It should be present for most cases though.

**Comment by nyh** [comment]
Ok. @psarna let me know when you push whatever things you do want to fix in this series (without fixing all the issues of the preexisting code), and I'll commit it.

File: alternator/rjson.cc (hunk 4 above)
Comment (psarna) [reply alternator/rjson.cc]: and mentioning "set" here is obviously a mistake as well - I guess I started with coding this struct as a local way of providing a comparison operator for a set, but then decided to make it more general.

**Comment by psarna** [comment]
@nyh done - I already pushed the updated implementation which is based on pointers instead of copying. As for your very well-founded doubts against the comparator, I filed https://github.com/scylladb/scylla/issues/5454

File: alternator/conditions.cc (hunk 6 above)
Comment (nyh) [reply alternator/conditions.cc]: @psarna I'm still curious about the answer to this question.

Comment (psarna) [reply alternator/conditions.cc]: Ah, sorry, missed the question yesterday. I just didn't assume here that the caller already checked if both of the items are sets. In case a non-set is passed to unwrap_set(), a nullptr will be returned, and the semantics I had in mind is that if any of the items is not a set, it will return true only if both are non-sets. As I'm writing this response though, I see how flawed this reasoning is, because the fact that both items are not sets does not by any means make them equal. I'll just fix this by throwing an internal error if (!set! || !set2) - as a light version of asserting that both items passed here should really be sets.

Comment (nyh) [reply alternator/conditions.cc]: Sure. Let me know when you push a new version, and I can commit it to next.

**Comment by psarna** [comment]
I pushed a new version. I actually over-engineered this `!set1 || !set2` check, as what I passed tot his function was not a typed set (.e.g `{type: "NS", value: [1,2,3]}`, but an already unwrapped array representing a set (e.g. `[1,2,3]`), because we needed to check its type in the caller anyway. That means that it's enough to just pass const references to these already unwrapped sets and compare them, which makes the code even simpler.

**Comment by nyh** [comment]
Thanks! Merged to next.
