### PR TITLE
Harden table truncate

### LINKED ISSUE #10281: Reactor stall from memtable_list::clear_and_add
Seen with the cql pytest mentioned in https://github.com/scylladb/scylla/issues/7929#issue-787821416.

```
Reactor stalled for 6 ms on shard 0. Backtrace: 0x449f802 0x449e460 0x449f710 0x7fcc740f5a1f 0x154866d 0x154b8b5 0x12c75ac 0x115d87e 0x10ab985 0x1079434 0x287013b 0x2869946 0x286951b 0xfc36ca 0x44b07f4 0x44b1bd7 0x44b0e2c 0x4458028 0x4457501 0xeff28c 0xefcada 0x27b74 0xefba6d
```

Decoded:
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace_oneline() at ./build/release/seastar/./seastar/src/core/reactor.cc:764
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:783
seastar::internal::cpu_stall_detector::generate_trace() at ./build/release/seastar/./seastar/src/core/reactor.cc:1358
seastar::internal::cpu_stall_detector::maybe_report() at ./build/release/seastar/./seastar/src/core/reactor.cc:1100
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1117
 (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1341
?? ??:0
compact_radix_tree::tree<cell_and_hash, unsigned int>::node_head_ptr::is(compact_radix_tree::tree<cell_and_hash, unsigned int>::node_head const&) const at ././utils/compact-radix-tree.hh:550
 (inlined by) void compact_radix_tree::tree<cell_and_hash, unsigned int>::visit<compact_radix_tree::tree<cell_and_hash, unsigned int>::visit<compact_radix_tree::tree<cell_and_hash, unsigned int>::clear()::clearing_visitor>(compact_radix_tree::tree<cell_and_hash, unsigned int>::clear()::clearing_visitor&&)::adaptor>(compact_radix_tree::tree<cell_and_hash, unsigned int>::clear()::clearing_visitor&&) const at ././utils/compact-radix-tree.hh:1627
 (inlined by) void compact_radix_tree::tree<cell_and_hash, unsigned int>::visit<compact_radix_tree::tree<cell_and_hash, unsigned int>::clear()::clearing_visitor>(compact_radix_tree::tree<cell_and_hash, unsigned int>::clear()::clearing_visitor&&) at ././utils/compact-radix-tree.hh:1647
 (inlined by) compact_radix_tree::tree<cell_and_hash, unsigned int>::clear() at ././utils/compact-radix-tree.hh:1844
 (inlined by) ~tree at ././utils/compact-radix-tree.hh:1777
 (inlined by) ~row at ./mutation_partition.cc:1473
 (inlined by) ~deletable_row at ././mutation_partition.hh:812
 (inlined by) ~rows_entry at ././mutation_partition.hh:884
 (inlined by) void allocation_strategy::destroy<rows_entry>(rows_entry*) at ././utils/allocation_strategy.hh:167
 (inlined by) operator() at ././utils/allocation_strategy.hh:244
 (inlined by) void intrusive_b::node<rows_entry, &rows_entry::_link, rows_entry::tri_compare, 12ul, 20ul, (intrusive_b::key_search)0, (intrusive_b::with_debug)0>::dispose_key<current_deleter<rows_entry>()::{lambda(rows_entry*)#1}&>(intrusive_b::member_hook*, current_deleter<rows_entry>()::{lambda(rows_entry*)#1}&) at ././utils/intrusive_btree.hh:1300
 (inlined by) intrusive_b::tree<rows_entry, &rows_entry::_link, rows_entry::tri_compare, 12ul, 20ul, (intrusive_b::key_search)0, (intrusive_b::with_debug)0>::iterator intrusive_b::tree<rows_entry, &rows_entry::_link, rows_entry::tri_compare, 12ul, 20ul, (intrusive_b::key_search)0, (intrusive_b::with_debug)0>::iterator::erase_and_dispose<current_deleter<rows_entry>()::{lambda(rows_entry*)#1}&>(current_deleter<rows_entry>()::{lambda(rows_entry*)#1}&) at ././utils/intrusive_btree.hh:897
 (inlined by) intrusive_b::tree<rows_entry, &rows_entry::_link, rows_entry::tri_compare, 12ul, 20ul, (intrusive_b::key_search)0, (intrusive_b::with_debug)0>::iterator intrusive_b::tree<rows_entry, &rows_entry::_link, rows_entry::tri_compare, 12ul, 20ul, (intrusive_b::key_search)0, (intrusive_b::with_debug)0>::erase_and_dispose<current_deleter<rows_entry>()::{lambda(rows_entry*)#1}&>(current_deleter<rows_entry>()::{lambda(rows_entry*)#1}&, current_deleter<rows_entry>()::{lambda(rows_entry*)#1}&) at ././utils/intrusive_btree.hh:584
 (inlined by) mutation_partition::clear_gently(cache_tracker*) at ./mutation_partition.cc:2239
mutation_cleaner_impl::clear_some() at ./mutation_partition.cc:2350
 (inlined by) mutation_cleaner_impl::clear_gently() at ./mutation_partition.cc:2336
 (inlined by) mutation_cleaner_impl::clear() at ./mutation_partition.cc:2332
 (inlined by) operator() at ./mutation_partition.cc:2327
 (inlined by) decltype(auto) with_allocator<mutation_cleaner_impl::~mutation_cleaner_impl()::$_23>(allocation_strategy&, mutation_cleaner_impl::~mutation_cleaner_impl()::$_23&&) at ././utils/allocation_strategy.hh:313
 (inlined by) ~mutation_cleaner_impl at ./mutation_partition.cc:2326
~lw_shared_ptr_no_esft at ././seastar/include/seastar/core/shared_ptr.hh:158
 (inlined by) seastar::internal::lw_shared_ptr_accessors_no_esft<mutation_cleaner_impl>::dispose(seastar::lw_shared_ptr_counter_base*) at ././seastar/include/seastar/core/shared_ptr.hh:214
 (inlined by) ~lw_shared_ptr at ././seastar/include/seastar/core/shared_ptr.hh:301
 (inlined by) ~mutation_cleaner at ././mutation_cleaner.hh:103
 (inlined by) ~memtable at ./replica/memtable.cc:138
seastar::internal::lw_shared_ptr_accessors_esft<replica::memtable>::dispose(replica::memtable*) at ././seastar/include/seastar/core/shared_ptr.hh:199
 (inlined by) seastar::internal::lw_shared_ptr_accessors_esft<replica::memtable>::dispose(seastar::lw_shared_ptr_counter_base*) at ././seastar/include/seastar/core/shared_ptr.hh:196
 (inlined by) ~lw_shared_ptr at ././seastar/include/seastar/core/shared_ptr.hh:301
 (inlined by) void std::destroy_at<seastar::lw_shared_ptr<replica::memtable> >(seastar::lw_shared_ptr<replica::memtable>*) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_construct.h:88
 (inlined by) void std::_Destroy<seastar::lw_shared_ptr<replica::memtable> >(seastar::lw_shared_ptr<replica::memtable>*) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_construct.h:149
 (inlined by) void std::_Destroy_aux<false>::__destroy<seastar::lw_shared_ptr<replica::memtable>*>(seastar::lw_shared_ptr<replica::memtable>*, seastar::lw_shared_ptr<replica::memtable>*) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_construct.h:163
 (inlined by) void std::_Destroy<seastar::lw_shared_ptr<replica::memtable>*>(seastar::lw_shared_ptr<replica::memtable>*, seastar::lw_shared_ptr<replica::memtable>*) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_construct.h:195
 (inlined by) void std::_Destroy<seastar::lw_shared_ptr<replica::memtable>*, seastar::lw_shared_ptr<replica::memtable> >(seastar::lw_shared_ptr<replica::memtable>*, seastar::lw_shared_ptr<replica::memtable>*, std::allocator<seastar::lw_shared_ptr<replica::memtable> >&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/alloc_traits.h:854
 (inlined by) std::vector<seastar::lw_shared_ptr<replica::memtable>, std::allocator<seastar::lw_shared_ptr<replica::memtable> > >::_M_erase_at_end(seastar::lw_shared_ptr<replica::memtable>*) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_vector.h:1796
 (inlined by) std::vector<seastar::lw_shared_ptr<replica::memtable>, std::allocator<seastar::lw_shared_ptr<replica::memtable> > >::clear() at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_vector.h:1499
 (inlined by) replica::memtable_list::clear_and_add() at ././replica/database.hh:227
 (inlined by) replica::table::clear() at ./replica/table.cc:1513
replica::database::truncate(replica::keyspace const&, replica::table&, std::function<seastar::future<std::chrono::time_point<db_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > > > ()>, bool) at ./replica/database.cc:2077
operator() at ./replica/database.cc:944
 (inlined by) seastar::future<void> seastar::futurize<seastar::future<void> >::invoke<replica::database::drop_column_family(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&, std::function<seastar::future<std::chrono::time_point<db_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > > > ()>, bool)::$_10>(replica::database::drop_column_family(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&, std::function<seastar::future<std::chrono::time_point<db_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > > > ()>, bool)::$_10&&) at ././seastar/include/seastar/core/future.hh:2141
 (inlined by) seastar::future<void> seastar::futurize<seastar::future<void> >::invoke<replica::database::drop_column_family(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&, std::function<seastar::future<std::chrono::time_point<db_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > > > ()>, bool)::$_10>(replica::database::drop_column_family(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&, std::function<seastar::future<std::chrono::time_point<db_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > > > ()>, bool)::$_10&&, seastar::internal::monostate) at ././seastar/include/seastar/core/future.hh:1985
 (inlined by) seastar::future<void> seastar::future<void>::then_impl<replica::database::drop_column_family(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&, std::function<seastar::future<std::chrono::time_point<db_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > > > ()>, bool)::$_10, seastar::future<void> >(replica::database::drop_column_family(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&, std::function<seastar::future<std::chrono::time_point<db_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > > > ()>, bool)::$_10&&) at ././seastar/include/seastar/core/future.hh:1607
 (inlined by) seastar::internal::future_result<replica::database::drop_column_family(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&, std::function<seastar::future<std::chrono::time_point<db_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > > > ()>, bool)::$_10, void>::future_type seastar::internal::call_then_impl<seastar::future<void> >::run<replica::database::drop_column_family(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&, std::function<seastar::future<std::chrono::time_point<db_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > > > ()>, bool)::$_10>(seastar::future<void>&, replica::database::drop_column_family(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&, std::function<seastar::future<std::chrono::time_point<db_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > > > ()>, bool)::$_10&&) at ././seastar/include/seastar/core/future.hh:1240
 (inlined by) seastar::future<void> seastar::future<void>::then<replica::database::drop_column_family(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&, std::function<seastar::future<std::chrono::time_point<db_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > > > ()>, bool)::$_10, seastar::future<void> >(replica::database::drop_column_family(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&, std::function<seastar::future<std::chrono::time_point<db_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > > > ()>, bool)::$_10&&) at ././seastar/include/seastar/core/future.hh:1526
 (inlined by) replica::database::drop_column_family(seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&, std::function<seastar::future<std::chrono::time_point<db_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > > > ()>, bool) at ./replica/database.cc:943
operator() at ./db/schema_tables.cc:1248
seastar::future<void> seastar::futurize<seastar::future<void> >::invoke<db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10::operator()(replica::database&) const::{lambda(db::schema_tables::schema_diff::dropped_schema&)#2}, db::schema_tables::schema_diff::dropped_schema&>(db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10::operator()(replica::database&) const::{lambda(db::schema_tables::schema_diff::dropped_schema&)#2}&&, db::schema_tables::schema_diff::dropped_schema&) at ././seastar/include/seastar/core/future.hh:2141
 (inlined by) auto seastar::futurize_invoke<db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10::operator()(replica::database&) const::{lambda(db::schema_tables::schema_diff::dropped_schema&)#2}, db::schema_tables::schema_diff::dropped_schema&>(db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10::operator()(replica::database&) const::{lambda(db::schema_tables::schema_diff::dropped_schema&)#2}&&, db::schema_tables::schema_diff::dropped_schema&) at ././seastar/include/seastar/core/future.hh:2172
 (inlined by) seastar::future<void> seastar::parallel_for_each<__gnu_cxx::__normal_iterator<db::schema_tables::schema_diff::dropped_schema*, std::vector<db::schema_tables::schema_diff::dropped_schema, std::allocator<db::schema_tables::schema_diff::dropped_schema> > >, __gnu_cxx::__normal_iterator<db::schema_tables::schema_diff::dropped_schema*, std::vector<db::schema_tables::schema_diff::dropped_schema, std::allocator<db::schema_tables::schema_diff::dropped_schema> > >, db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10::operator()(replica::database&) const::{lambda(db::schema_tables::schema_diff::dropped_schema&)#2}>(__gnu_cxx::__normal_iterator<db::schema_tables::schema_diff::dropped_schema*, std::vector<db::schema_tables::schema_diff::dropped_schema, std::allocator<db::schema_tables::schema_diff::dropped_schema> > >, __gnu_cxx::__normal_iterator<db::schema_tables::schema_diff::dropped_schema*, std::vector<db::schema_tables::schema_diff::dropped_schema, std::allocator<db::schema_tables::schema_diff::dropped_schema> > >, db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10::operator()(replica::database&) const::{lambda(db::schema_tables::schema_diff::dropped_schema&)#2}&&) at ././seastar/include/seastar/core/loop.hh:566
 (inlined by) seastar::future<void> seastar::internal::parallel_for_each_impl<std::vector<db::schema_tables::schema_diff::dropped_schema, std::allocator<db::schema_tables::schema_diff::dropped_schema> >&, db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10::operator()(replica::database&) const::{lambda(db::schema_tables::schema_diff::dropped_schema&)#2}>(std::vector<db::schema_tables::schema_diff::dropped_schema, std::allocator<db::schema_tables::schema_diff::dropped_schema> >&, db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10::operator()(replica::database&) const::{lambda(db::schema_tables::schema_diff::dropped_schema&)#2}&&) at ././seastar/include/seastar/core/loop.hh:616
 (inlined by) seastar::future<void> seastar::futurize<seastar::future<void> >::invoke<seastar::future<void> (*&)(std::vector<db::schema_tables::schema_diff::dropped_schema, std::allocator<db::schema_tables::schema_diff::dropped_schema> >&, db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10::operator()(replica::database&) const::{lambda(db::schema_tables::schema_diff::dropped_schema&)#2}&&), std::vector<db::schema_tables::schema_diff::dropped_schema, std::allocator<db::schema_tables::schema_diff::dropped_schema> >&, {lambda(db::schema_tables::schema_diff::dropped_schema&)#2}>(seastar::future<void> (*&)(std::vector<db::schema_tables::schema_diff::dropped_schema, std::allocator<db::schema_tables::schema_diff::dropped_schema> >&, db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10::operator()(replica::database&) const::{lambda(db::schema_tables::schema_diff::dropped_schema&)#2}&&), std::vector<db::schema_tables::schema_diff::dropped_schema, std::allocator<db::schema_tables::schema_diff::dropped_schema> >&, {lambda(db::schema_tables::schema_diff::dropped_schema&)#2}&&) at ././seastar/include/seastar/core/future.hh:2141
 (inlined by) auto seastar::futurize_invoke<seastar::future<void> (*&)(std::vector<db::schema_tables::schema_diff::dropped_schema, std::allocator<db::schema_tables::schema_diff::dropped_schema> >&, db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10::operator()(replica::database&) const::{lambda(db::schema_tables::schema_diff::dropped_schema&)#2}&&), std::vector<db::schema_tables::schema_diff::dropped_schema, std::allocator<db::schema_tables::schema_diff::dropped_schema> >&, {lambda(db::schema_tables::schema_diff::dropped_schema&)#2}>(seastar::future<void> (*&)(std::vector<db::schema_tables::schema_diff::dropped_schema, std::allocator<db::schema_tables::schema_diff::dropped_schema> >&, db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10::operator()(replica::database&) const::{lambda(db::schema_tables::schema_diff::dropped_schema&)#2}&&), std::vector<db::schema_tables::schema_diff::dropped_schema, std::allocator<db::schema_tables::schema_diff::dropped_schema> >&, {lambda(db::schema_tables::schema_diff::dropped_schema&)#2}&&) at ././seastar/include/seastar/core/future.hh:2172
 (inlined by) seastar::future<void> seastar::parallel_for_each<std::vector<db::schema_tables::schema_diff::dropped_schema, std::allocator<db::schema_tables::schema_diff::dropped_schema> >&, db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10::operator()(replica::database&) const::{lambda(db::schema_tables::schema_diff::dropped_schema&)#2}>(std::vector<db::schema_tables::schema_diff::dropped_schema, std::allocator<db::schema_tables::schema_diff::dropped_schema> >&, db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10::operator()(replica::database&) const::{lambda(db::schema_tables::schema_diff::dropped_schema&)#2}&&) at ././seastar/include/seastar/core/loop.hh:631
 (inlined by) operator() at ./db/schema_tables.cc:1246
seastar::future<void> std::__invoke_impl<seastar::future<void>, db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10&, replica::database&>(std::__invoke_other, db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10&, replica::database&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
 (inlined by) std::__invoke_result<db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10&, replica::database&>::type std::__invoke<db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10&, replica::database&>(db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10&, replica::database&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:96
 (inlined by) decltype(auto) std::__apply_impl<db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10&, std::tuple<replica::database&>, 0ul>(db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10&, std::tuple<replica::database&>&&, std::integer_sequence<unsigned long, 0ul>) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/tuple:1858
 (inlined by) decltype(auto) std::apply<db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10&, std::tuple<replica::database&> >(db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10&, std::tuple<replica::database&>&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/tuple:1869
 (inlined by) seastar::future<void> seastar::futurize<seastar::future<void> >::apply<db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10&, replica::database&>(db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10&, std::tuple<replica::database&>&&) at ././seastar/include/seastar/core/future.hh:2108
 (inlined by) auto seastar::futurize_apply<db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10&, replica::database&>(db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10&, std::tuple<replica::database&>&&) at ././seastar/include/seastar/core/future.hh:2184
 (inlined by) operator() at ././seastar/include/seastar/core/sharded.hh:768
 (inlined by) seastar::future<void> std::__invoke_impl<seastar::future<void>, seastar::sharded<replica::database>::invoke_on_all<db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10>(seastar::smp_submit_to_options, db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10)::{lambda(replica::database&)#1}&, replica::database&>(std::__invoke_other, seastar::sharded<replica::database>::invoke_on_all<db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10>(seastar::smp_submit_to_options, db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10)::{lambda(replica::database&)#1}&, replica::database&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
 (inlined by) std::enable_if<is_invocable_r_v<seastar::future<void>, seastar::sharded<replica::database>::invoke_on_all<db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10>(seastar::smp_submit_to_options, db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10)::{lambda(replica::database&)#1}&, replica::database&>, seastar::future<void> >::type std::__invoke_r<seastar::future<void>, seastar::sharded<replica::database>::invoke_on_all<db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10>(seastar::smp_submit_to_options, db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10)::{lambda(replica::database&)#1}&, replica::database&>(std::enable_if&&, (seastar::sharded<replica::database>::invoke_on_all<db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10>(seastar::smp_submit_to_options, db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10)::{lambda(replica::database&)#1}&)...) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:114
 (inlined by) std::_Function_handler<seastar::future<void> (replica::database&), seastar::sharded<replica::database>::invoke_on_all<db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10>(seastar::smp_submit_to_options, db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_10)::{lambda(replica::database&)#1}>::_M_invoke(std::_Any_data const&, replica::database&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:290
std::function<seastar::future<void> (replica::database&)>::operator()(replica::database&) const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:590
 (inlined by) operator() at ././seastar/include/seastar/core/sharded.hh:750
 (inlined by) seastar::future<void> seastar::futurize<seastar::future<void> >::invoke<seastar::sharded<replica::database>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (replica::database&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&>(seastar::sharded<replica::database>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (replica::database&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&) at ././seastar/include/seastar/core/future.hh:2141
 (inlined by) seastar::smp_message_queue::async_work_item<seastar::sharded<replica::database>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (replica::database&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::run_and_dispose() at ././seastar/include/seastar/core/smp.hh:231
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2344
 (inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:2754
seastar::reactor::do_run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2923
seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2806
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:265
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:156
scylla_main(int, char**) at ./main.cc:531
std::function<int (int, char**)>::operator()(int, char**) const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:590
 (inlined by) main at ./main.cc:1558
?? ??:0
_start at ??:?
```

### LINKED ISSUE #10423: Truncating a table during memtable flush might trigger an assert failure in ~flush_memory_accounter
While investigating #10421 and trying to reproduce it with a unit test I hit this issue where
https://github.com/scylladb/scylla/blob/bcd35af7cf93eac9664a044816847521cfddb0ac/replica/memtable.cc#L546-L548
is triggered when truncating a table while there are memtable flushes in the background.

### PR DESCRIPTION
**Pull request by bhalevy**
This series fixes a few issue on the table truncate path:
- "memtable_list: safely futurize clear_and_add"
  - reinstates an async version of table::clear_and_add, just safe against #10421
- a unit test reproducing #10421 was added to make sure the new version is indeed safe.
- "table: clear: serialize with ongoing flush" fixes #10423
- a unit test reproducing #10423 was added

Fixes #10281
Fixes #10423

Test: unit(dev), database_test. test_truncate_without_snapshot_during_{writes,flushes} (debug)

### CODE REVIEW

File: replica/table.cc [hunk 1]
```diff
@@ -1501,8 +1501,8 @@ future<> table::clear() {
             _commitlog->discard_completed_segments(_schema->id(), t->get_and_discard_rp_set());
         }
     }
-    _memtables->clear_and_add();
-    return _cache.invalidate(row_cache::external_updater([] { /* There is no underlying mutation source */ }));
+    co_await _memtables->clear_and_add();
```
Comment (avikivity) [inline replica/table.cc:1505]: Can this be called concurrently? Previously, clear_and_add() was atomic, but now two concurrent invocations can race.

File: replica/database.cc [hunk 2]
```diff
@@ -1574,6 +1574,32 @@ lw_shared_ptr<memtable> memtable_list::new_memtable() {
...
 }
 
+future<> memtable_list::clear_and_add() {
+    auto mt = new_memtable();
+    std::vector<replica::shared_memtable> new_memtables;
+    try {
+        // try preparing the cleared memtables vector ahead of time
+        // so we can clear the old memtables gently later
+        new_memtables.reserve(_memtables.size());
+        new_memtables.emplace_back(std::move(mt));
```
Comment (avikivity) [inline replica/database.cc:1584]: Why do we need so many new memtables? Isn't one enough?

Comment (avikivity) [reply replica/database.cc:1584]: Well, a reservation for so many new memtables.

File: replica/database.cc [hunk 3]
```diff
@@ -1574,6 +1574,32 @@ lw_shared_ptr<memtable> memtable_list::new_memtable() {
...
+        _memtables.emplace_back(std::move(mt));
+        co_return;
+    }
+    auto old_memtables = std::exchange(_memtables, std::move(new_memtables));
+    for (auto& smt : old_memtables) {
+        co_await smt->clear_gently();
+    }
+}
+
 } // namespace replica
```
Comment (avikivity) [inline replica/database.cc:1603]: What was the problem in the old implementation? Just curious.

File: replica/table.cc [hunk 4]
```diff
@@ -1496,6 +1496,7 @@ bool table::can_flush() const {
 }
 
 future<> table::clear() {
+    auto permits = co_await _config.dirty_memory_manager->get_all_flush_permits();
     if (_commitlog) {
```
Comment (avikivity) [inline replica/table.cc:1500]: Strictly speaking maybe this should be the first patch.

File: replica/database.cc (hunk 2 above)
Comment (bhalevy) [reply replica/database.cc:1584]: I didn't want to change the outcome of this function that kept the vector capacity (since it only called clear) in the synchronous path by calling `std::vector::clear()`.

File: replica/table.cc (hunk 1 above)
Comment (bhalevy) [reply replica/table.cc:1505]: Yes, since `clear_and_add` now swaps the `_memtables` vector atomically and clears the old memtables in the background.

File: replica/database.cc (hunk 3 above)
Comment (bhalevy) [reply replica/database.cc:1603]: It was hard to tell due, even in debug mode, due to coroutines frames since ASAN didn't produce full backtraces.
My understanding is that since clear_gently was called while iterating the "live" _memtables vector, concurrent writes caused reallocation of the vector leading to user-after-free of the memtable shared ptr.

File: replica/table.cc (hunk 4 above)
Comment (bhalevy) [reply replica/table.cc:1500]: I can do that, though it makes reproducing https://github.com/scylladb/scylla/issues/10421 harder.

File: replica/database.cc (hunk 2 above)
Comment (bhalevy) [reply replica/database.cc:1584]: The question is we indeed want to keep that.
I agree that replacing the `_memtables` vector with a vector of size 1 seems reasonable and would be simpler.

File: replica/table.cc (hunk 1 above)
Comment (avikivity) [reply replica/table.cc:1505]: Yes. Worth to add a comment so people don't add co_awaits before that exchange.

**Comment by bhalevy** [comment]
In v3 (c2f0d75d96dc2ba46a76fdeca9a4aef35ca0d757):
- Beefed up comments for memtable_list::clear_and_add to describe what it is expected to do synchronously and when can it yield.

**Comment by bhalevy** [comment]
@avikivity please rereview

**Comment by bhalevy** [comment]
@avikivity ping

**Comment by bhalevy** [comment]
@avikivity ping, please re-review

File: replica/database.cc [hunk 5]
```diff
@@ -1574,6 +1574,20 @@ lw_shared_ptr<memtable> memtable_list::new_memtable() {
...
+future<> memtable_list::clear_and_add() {
+    std::vector<replica::shared_memtable> new_memtables;
+    new_memtables.emplace_back(new_memtable());
+    auto old_memtables = std::exchange(_memtables, std::move(new_memtables));
+    // Now that the existing _memtables vector is swapped with new_memtables
+    // the function can yield for clearing the old_memtables.
+    for (auto& smt : old_memtables) {
+        co_await smt->clear_gently();
+    }
+}
```
Comment (avikivity) [inline replica/database.cc:1589]: Please follow-up with splitting this into two functions. Having a future-returning function with an atomic part and a non-atomic part makes it easy to think there's a problem when looking at the caller (and easy to introduce bugs by adding waits before the atomic part).

Comment (bhalevy) [reply replica/database.cc:1589]: Will do
