### PR TITLE
Make it possible to turn caching off per table and stop caching CDC Log

### LINKED ISSUE #6098: CDC: reactor stalled up to 17000 ms after change cdc log table property
*Installation details*
Scylla version (or git commit hash):
version 666.development-0.20200325.9fee712d62 with build-id 0908e1527b1f134a4e4a46ca44ffe85f0f877318
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-045e69a7ca1cb853f

Cluster was configured with cdc feature. For base table cdc_test.test_table_preimage  cdc preimage was enabled. After several minutes, for cdc log table properties was changed: 
ALTER TABLE cdc_test.test_table_preimage_scylla_cdc_log WITH dclocal_read_repair_chance = 0.5

after that, on several nodes were found next messages in log
```
2020-03-26T13:48:28+00:00  longevity-cdc-100gb-4h-master-db-node-77890b52-5 !WARNING | scylla: [shard 3] storage_proxy - Failed to apply mutation from 10.0.135.90#3: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 13->3 semaphore)
2020-03-26T13:48:28+00:00  longevity-cdc-100gb-4h-master-db-node-77890b52-5 !WARNING | scylla: [shard 3] storage_proxy - Failed to apply mutation from 10.0.135.90#3: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 13->3 semaphore)
2020-03-26T13:48:28+00:00  longevity-cdc-100gb-4h-master-db-node-77890b52-5 !ERR     | scylla: [shard 3] storage_proxy - exception during mutation write to 10.0.121.232: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 13->3 semaphore)
2020-03-26T13:48:28+00:00  longevity-cdc-100gb-4h-master-db-node-77890b52-5 !ERR     | scylla: [shard 3] storage_proxy - exception during mutation write to 10.0.121.232: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 13->3 semaphore)
```

and reactor stalled reached up to 17000 ms:
```
2020-03-26T13:48:32+00:00  longevity-cdc-100gb-4h-master-db-node-77890b52-5 !INFO    | scylla: Reactor stalled for 8759 ms on shard 13.

void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/fmt/format.h:1158
seastar::backtrace_buffer::append_backtrace() at /usr/include/fmt/format.h:1158
 (inlined by) print_with_backtrace at ./build/release/seastar/./seastar/src/core/reactor.cc:755
seastar::internal::cpu_stall_detector::generate_trace() at /usr/include/fmt/format.h:1158
seastar::internal::cpu_stall_detector::maybe_report() at /usr/include/fmt/format.h:1158
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1062
 (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1185
?? ??:0
managed_bytes::size() const at /usr/include/fmt/format.h:1158
 (inlined by) managed_bytes::managed_bytes(managed_bytes const&) at ././utils/managed_bytes.hh:233
compound_wrapper<clustering_key_prefix, clustering_key_prefix_view>::compound_wrapper(compound_wrapper<clustering_key_prefix, clustering_key_prefix_view> const&) at /usr/include/boost/intrusive/pointer_plus_bits.hpp:89
 (inlined by) prefix_compound_wrapper<clustering_key_prefix, clustering_key_prefix_view, clustering_key_prefix>::prefix_compound_wrapper(prefix_compound_wrapper<clustering_key_prefix, clustering_key_prefix_view, clustering_key_prefix> const&) at ./keys.hh:558
 (inlined by) clustering_key_prefix::clustering_key_prefix(clustering_key_prefix const&) at ./keys.hh:784
 (inlined by) rows_entry::rows_entry(schema const&, rows_entry const&) at ./mutation_partition.hh:1054
 (inlined by) rows_entry* allocation_strategy::construct<rows_entry, schema const&, rows_entry const&>(schema const&, rows_entry const&) at ././utils/allocation_strategy.hh:152
 (inlined by) operator()<rows_entry> at ./mutation_partition.cc:161
 (inlined by) operator() at ./intrusive_set_external_comparator.hh:229
 (inlined by) operator() at /usr/include/boost/intrusive/rbtree_algorithms.hpp:59
 (inlined by) clone_subtree<boost::intrusive::rbtree_node_cloner<boost::intrusive::rbtree_node_traits<void*, true>, intrusive_set_external_comparator<Elem, PtrToMember>::clone_from(const intrusive_set_external_comparator<Elem, PtrToMember>&, Cloner, Disposer) [with Cloner = mutation_partition::mutation_partition(const schema&, const mutation_partition&)::<lambda(const auto:147&)>; Disposer = current_deleter() [with T = rows_entry]::<lambda(rows_entry*)>; Elem = rows_entry; intrusive_set_external_comparator_member_hook Elem::* PtrToMember = &rows_entry::_link]::<lambda(boost::intrusive::compact_rbtree_node<void*>* const&)> >, intrusive_set_external_comparator<Elem, PtrToMember>::clone_from(const intrusive_set_external_comparator<Elem, PtrToMember>&, Cloner, Disposer) [with Cloner = mutation_partition::mutation_partition(const schema&, const mutation_partition&)::<lambda(const auto:147&)>; Disposer = current_deleter() [with T = rows_entry]::<lambda(rows_entry*)>; Elem = rows_entry; intrusive_set_external_comparator_member_hook Elem::* PtrToMember = &rows_entry::_link]::<lambda(boost::intrusive::compact_rbtree_node<void*>* const&)> > at /usr/include/boost/intrusive/bstree_algorithms.hpp:1978
 (inlined by) clone<boost::intrusive::rbtree_node_cloner<boost::intrusive::rbtree_node_traits<void*, true>, intrusive_set_external_comparator<Elem, PtrToMember>::clone_from(const intrusive_set_external_comparator<Elem, PtrToMember>&, Cloner, Disposer) [with Cloner = mutation_partition::mutation_partition(const schema&, const mutation_partition&)::<lambda(const auto:147&)>; Disposer = current_deleter() [with T = rows_entry]::<lambda(rows_entry*)>; Elem = rows_entry; intrusive_set_external_comparator_member_hook Elem::* PtrToMember = &rows_entry::_link]::<lambda(boost::intrusive::compact_rbtree_node<void*>* const&)> >, intrusive_set_external_comparator<Elem, PtrToMember>::clone_from(const intrusive_set_external_comparator<Elem, PtrToMember>&, Cloner, Disposer) [with Cloner = mutation_partition::mutation_partition(const schema&, const mutation_partition&)::<lambda(const auto:147&)>; Disposer = current_deleter() [with T = rows_entry]::<lambda(rows_entry*)>; Elem = rows_entry; intrusive_set_external_comparator_member_hook Elem::* PtrToMember = &rows_entry::_link]::<lambda(boost::intrusive::compact_rbtree_node<void*>* const&)> > at /usr/include/boost/intrusive/bstree_algorithms.hpp:1303
 (inlined by) clone<intrusive_set_external_comparator<Elem, PtrToMember>::clone_from(const intrusive_set_external_comparator<Elem, PtrToMember>&, Cloner, Disposer) [with Cloner = mutation_partition::mutation_partition(const schema&, const mutation_partition&)::<lambda(const auto:147&)>; Disposer = current_deleter() [with T = rows_entry]::<lambda(rows_entry*)>; Elem = rows_entry; intrusive_set_external_comparator_member_hook Elem::* PtrToMember = &rows_entry::_link]::<lambda(boost::intrusive::compact_rbtree_node<void*>* const&)>, intrusive_set_external_comparator<Elem, PtrToMember>::clone_from(const intrusive_set_external_comparator<Elem, PtrToMember>&, Cloner, Disposer) [with Cloner = mutation_partition::mutation_partition(const schema&, const mutation_partition&)::<lambda(const auto:147&)>; Disposer = current_deleter() [with T = rows_entry]::<lambda(rows_entry*)>; Elem = rows_entry; intrusive_set_external_comparator_member_hook Elem::* PtrToMember = &rows_entry::_link]::<lambda(boost::intrusive::compact_rbtree_node<void*>* const&)> > at /usr/include/boost/intrusive/rbtree_algorithms.hpp:322
 (inlined by) clone_from<mutation_partition::mutation_partition(const schema&, const mutation_partition&)::<lambda(const auto:147&)>, current_deleter() [with T = rows_entry]::<lambda(rows_entry*)> > at ./intrusive_set_external_comparator.hh:226
 (inlined by) mutation_partition::mutation_partition(schema const&, mutation_partition const&) at ./mutation_partition.cc:163
partition_entry::squashed(seastar::lw_shared_ptr<schema const>, seastar::lw_shared_ptr<schema const>) at /usr/include/fmt/format.h:1158
partition_entry::upgrade(seastar::lw_shared_ptr<schema const>, seastar::lw_shared_ptr<schema const>, mutation_cleaner&, cache_tracker*) at /usr/include/fmt/format.h:1158
operator() at /usr/include/fmt/format.h:1158
 (inlined by) with_linearized_managed_bytes<row_cache::upgrade_entry(cache_entry&)::<lambda()>::<lambda()> > at ./utils/managed_bytes.hh:428
 (inlined by) operator() at ./row_cache.cc:1296
 (inlined by) with_allocator<row_cache::upgrade_entry(cache_entry&)::<lambda()> > at ././utils/allocation_strategy.hh:307
 (inlined by) row_cache::upgrade_entry(cache_entry&) at ./row_cache.cc:1295
operator() at /usr/include/fmt/format.h:1158
 (inlined by) operator() at ./row_cache.cc:961
 (inlined by) with_reclaiming_disabled<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()>::<lambda()>::<lambda()>&> at ././utils/logalloc.hh:745
 (inlined by) operator() at ././utils/logalloc.hh:767
 (inlined by) with_reserve<logalloc::allocating_section::operator()(logalloc::region&, Func&&) [with Func = row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()>::<lambda()>::<lambda()>]::<lambda()> > at ././utils/logalloc.hh:717
 (inlined by) operator()<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()>::<lambda()>::<lambda()> > at ././utils/logalloc.hh:768
 (inlined by) operator() at ./row_cache.cc:957
 (inlined by) with_linearized_managed_bytes<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()>::<lambda()> > at ./utils/managed_bytes.hh:428
 (inlined by) operator() at ./row_cache.cc:955
 (inlined by) with_allocator<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()> > at ././utils/allocation_strategy.hh:307
 (inlined by) operator() at ./row_cache.cc:944
apply at /usr/include/fmt/format.h:1158
 (inlined by) apply<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> > at ././seastar/include/seastar/core/apply.hh:44
 (inlined by) apply_tuple<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> > at ././seastar/include/seastar/core/future.hh:1618
 (inlined by) apply<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> > at ././seastar/include/seastar/core/future.hh:1652
 (inlined by) operator() at ././seastar/include/seastar/core/thread.hh:253
 (inlined by) call at ././seastar/include/seastar/util/noncopyable_function.hh:101
seastar::noncopyable_function<void ()>::operator()() const at ./build/release/seastar/./seastar/include/seastar/util/noncopyable_function.hh:184
 (inlined by) seastar::thread_context::main() at ./build/release/seastar/./seastar/src/core/thread.cc:286
```

```
2020-03-26T13:48:59+00:00  longevity-cdc-100gb-4h-master-db-node-77890b52-2 !INFO    | scylla: Reactor stalled for 17334 ms on shard 2.

void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/fmt/format.h:1158
seastar::backtrace_buffer::append_backtrace() at /usr/include/fmt/format.h:1158
 (inlined by) print_with_backtrace at ./build/release/seastar/./seastar/src/core/reactor.cc:755
seastar::internal::cpu_stall_detector::generate_trace() at /usr/include/fmt/format.h:1158
seastar::internal::cpu_stall_detector::maybe_report() at /usr/include/fmt/format.h:1158
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1062
 (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1185
?? ??:0
?? ??:0
std::_Hash_impl::hash(void const*, unsigned long, unsigned long) at /usr/include/fmt/format.h:1158
 (inlined by) std::hash<std::basic_string_view<char, std::char_traits<char> > >::operator()(std::basic_string_view<char, std::char_traits<char> > const&) const at /usr/include/c++/9/string_view:610
 (inlined by) std::hash<std::basic_string_view<signed char, std::char_traits<signed char> > >::operator()(std::basic_string_view<signed char, std::char_traits<signed char> >) const at ././bytes.hh:47
 (inlined by) std::hash<seastar::basic_sstring<signed char, unsigned int, 31u, false> >::operator()(seastar::basic_sstring<signed char, unsigned int, 31u, false> const&) const at ././seastar/include/seastar/core/sstring.hh:664
 (inlined by) std::__detail::_Hash_code_base<seastar::basic_sstring<signed char, unsigned int, 31u, false>, std::pair<seastar::basic_sstring<signed char, unsigned int, 31u, false> const, column_definition const*>, std::__detail::_Select1st, std::hash<seastar::basic_sstring<signed char, unsigned int, 31u, false> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, true>::_M_hash_code(seastar::basic_sstring<signed char, unsigned int, 31u, false> const&) const at /usr/include/c++/9/bits/hashtable_policy.h:1384
 (inlined by) std::_Hashtable<seastar::basic_sstring<signed char, unsigned int, 31u, false>, std::pair<seastar::basic_sstring<signed char, unsigned int, 31u, false> const, column_definition const*>, std::allocator<std::pair<seastar::basic_sstring<signed char, unsigned int, 31u, false> const, column_definition const*> >, std::__detail::_Select1st, std::equal_to<seastar::basic_sstring<signed char, unsigned int, 31u, false> >, std::hash<seastar::basic_sstring<signed char, unsigned int, 31u, false> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::find(seastar::basic_sstring<signed char, unsigned int, 31u, false> const&) const at /usr/include/c++/9/bits/hashtable.h:1433
 (inlined by) std::unordered_map<seastar::basic_sstring<signed char, unsigned int, 31u, false>, column_definition const*, std::hash<seastar::basic_sstring<signed char, unsigned int, 31u, false> >, std::equal_to<seastar::basic_sstring<signed char, unsigned int, 31u, false> >, std::allocator<std::pair<seastar::basic_sstring<signed char, unsigned int, 31u, false> const, column_definition const*> > >::find(seastar::basic_sstring<signed char, unsigned int, 31u, false> const&) const at /usr/include/c++/9/bits/unordered_map.h:925
 (inlined by) schema::get_column_definition(seastar::basic_sstring<signed char, unsigned int, 31u, false> const&) const at ./schema.cc:569
converting_mutation_partition_applier::accept_row_cell(unsigned int, atomic_cell_view) at /usr/include/fmt/format.h:1158
operator() at /usr/include/boost/intrusive/pointer_plus_bits.hpp:89
 (inlined by) maybe_invoke_with_hash<mutation_partition::accept(const schema&, mutation_partition_visitor&) const::<lambda(column_id, const atomic_cell_or_collection&)>, const cell_and_hash> at ./mutation_partition.hh:255
 (inlined by) for_each_cell<mutation_partition::accept(const schema&, mutation_partition_visitor&) const::<lambda(column_id, const atomic_cell_or_collection&)> > at ./mutation_partition.hh:280
 (inlined by) mutation_partition::accept(schema const&, mutation_partition_visitor&) const at ./mutation_partition.cc:1949
mutation_partition::upgrade(schema const&, schema const&) at /usr/include/boost/intrusive/pointer_plus_bits.hpp:89
partition_entry::squashed(seastar::lw_shared_ptr<schema const>, seastar::lw_shared_ptr<schema const>) at /usr/include/fmt/format.h:1158
partition_entry::upgrade(seastar::lw_shared_ptr<schema const>, seastar::lw_shared_ptr<schema const>, mutation_cleaner&, cache_tracker*) at /usr/include/fmt/format.h:1158
operator() at /usr/include/fmt/format.h:1158
 (inlined by) with_linearized_managed_bytes<row_cache::upgrade_entry(cache_entry&)::<lambda()>::<lambda()> > at ./utils/managed_bytes.hh:428
 (inlined by) operator() at ./row_cache.cc:1296
 (inlined by) with_allocator<row_cache::upgrade_entry(cache_entry&)::<lambda()> > at ././utils/allocation_strategy.hh:307
 (inlined by) row_cache::upgrade_entry(cache_entry&) at ./row_cache.cc:1295
operator() at /usr/include/fmt/format.h:1158
 (inlined by) operator() at ./row_cache.cc:961
 (inlined by) with_reclaiming_disabled<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()>::<lambda()>::<lambda()>&> at ././utils/logalloc.hh:745
 (inlined by) operator() at ././utils/logalloc.hh:767
 (inlined by) with_reserve<logalloc::allocating_section::operator()(logalloc::region&, Func&&) [with Func = row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()>::<lambda()>::<lambda()>]::<lambda()> > at ././utils/logalloc.hh:717
 (inlined by) operator()<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()>::<lambda()>::<lambda()> > at ././utils/logalloc.hh:768
 (inlined by) operator() at ./row_cache.cc:957
 (inlined by) with_linearized_managed_bytes<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()>::<lambda()> > at ./utils/managed_bytes.hh:428
 (inlined by) operator() at ./row_cache.cc:955
 (inlined by) with_allocator<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()> > at ././utils/allocation_strategy.hh:307
 (inlined by) operator() at ./row_cache.cc:944
apply at /usr/include/fmt/format.h:1158
 (inlined by) apply<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> > at ././seastar/include/seastar/core/apply.hh:44
 (inlined by) apply_tuple<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> > at ././seastar/include/seastar/core/future.hh:1618
 (inlined by) apply<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> > at ././seastar/include/seastar/core/future.hh:1652
 (inlined by) operator() at ././seastar/include/seastar/core/thread.hh:253
 (inlined by) call at ././seastar/include/seastar/util/noncopyable_function.hh:101
seastar::noncopyable_function<void ()>::operator()() const at ./build/release/seastar/./seastar/include/seastar/util/noncopyable_function.hh:184
 (inlined by) seastar::thread_context::main() at ./build/release/seastar/./seastar/src/core/thread.cc:286
```

```
2020-03-26T13:49:37+00:00  longevity-cdc-100gb-4h-master-db-node-77890b52-5 !INFO    | scylla: Reactor stalled for 17097 ms on shard 3.

void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/fmt/format.h:1158
seastar::backtrace_buffer::append_backtrace() at /usr/include/fmt/format.h:1158
 (inlined by) print_with_backtrace at ./build/release/seastar/./seastar/src/core/reactor.cc:755
seastar::internal::cpu_stall_detector::generate_trace() at /usr/include/fmt/format.h:1158
seastar::internal::cpu_stall_detector::maybe_report() at /usr/include/fmt/format.h:1158
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1062
 (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1185
?? ??:0
logalloc::region_impl::compaction_lock::compaction_lock(logalloc::region_impl&) at ./utils/logalloc.cc:1145
 (inlined by) logalloc::region_impl::free(void*, unsigned long) at ./utils/logalloc.cc:1421
logalloc::region_impl::free(void*) at ./utils/logalloc.cc:1417
imr::utils::object<imr::structure<imr::member<data::cell::tags::flags, imr::flags<data::cell::tags::collection, data::cell::tags::live, data::cell::tags::expiring, data::cell::tags::counter_update, data::cell::tags::empty, data::cell::tags::external_data> >, imr::member<data::cell::tags::cell, imr::variant<data::cell::tags::cell, imr::member<data::cell::tags::atomic_cell, imr::structure<imr::member<data::cell::tags::timestamp, imr::pod<long> >, imr::member<data::cell::tags::expiring, imr::optional<data::cell::tags::expiring, imr::structure<imr::member<data::cell::tags::ttl, imr::pod<int> >, imr::member<data::cell::tags::expiry, imr::pod<long> > > > >, imr::member<data::cell::tags::value, imr::variant<data::cell::tags::value, imr::member<data::cell::tags::dead, imr::pod<long> >, imr::member<data::cell::tags::counter_update, imr::pod<long> >, imr::member<data::cell::tags::fixed_value, imr::buffer<data::cell::tags::fixed_value> >, imr::member<data::cell::tags::variable_value, imr::structure<imr::member<data::cell::tags::value_size, imr::pod<unsigned int> >, imr::member<data::cell::tags::value_data, imr::variant<data::cell::tags::value_data, imr::member<data::cell::tags::pointer, imr::tagged_type<data::cell::tags::pointer, imr::pod<unsigned char*> > >, imr::member<data::cell::tags::data, imr::buffer<data::cell::tags::data> > > > > > > > > >, imr::member<data::cell::tags::collection, imr::structure<imr::member<data::cell::tags::value_size, imr::pod<unsigned int> >, imr::member<data::cell::tags::value_data, imr::variant<data::cell::tags::value_data, imr::member<data::cell::tags::pointer, imr::tagged_type<data::cell::tags::pointer, imr::pod<unsigned char*> > >, imr::member<data::cell::tags::data, imr::buffer<data::cell::tags::data> > > > > > > > > >::~object() at /usr/include/boost/intrusive/pointer_plus_bits.hpp:89
 (inlined by) atomic_cell_or_collection::~atomic_cell_or_collection() at ./atomic_cell_or_collection.hh:33
 (inlined by) cell_and_hash::~cell_and_hash() at ./mutation_partition.hh:76
 (inlined by) managed_vector<cell_and_hash, 5u, unsigned int>::pop_back() at ./utils/managed_vector.hh:221
 (inlined by) managed_vector<cell_and_hash, 5u, unsigned int>::clear() at ./utils/managed_vector.hh:177
 (inlined by) managed_vector<cell_and_hash, 5u, unsigned int>::clear_and_release() at ./utils/managed_vector.hh:84
 (inlined by) managed_vector<cell_and_hash, 5u, unsigned int>::~managed_vector() at ./utils/managed_vector.hh:134
 (inlined by) row::vector_storage::~vector_storage() at ./mutation_partition.hh:160
 (inlined by) row::~row() at ./mutation_partition.cc:1564
deletable_row::~deletable_row() at /usr/include/boost/intrusive/pointer_plus_bits.hpp:89
 (inlined by) rows_entry::~rows_entry() at ./mutation_partition.hh:1001
 (inlined by) void allocation_strategy::destroy<rows_entry>(rows_entry*) at ././utils/allocation_strategy.hh:164
 (inlined by) auto current_deleter<rows_entry>()::{lambda(rows_entry*)#1}::operator()(rows_entry*) const at ././utils/allocation_strategy.hh:238
 (inlined by) void intrusive_set_external_comparator<rows_entry, &rows_entry::_link>::clear_and_dispose<auto current_deleter<rows_entry>()::{lambda(rows_entry*)#1}>(auto current_deleter<rows_entry>()::{lambda(rows_entry*)#1})::{lambda(boost::intrusive::compact_rbtree_node<void*>* const&)#1}::operator()(boost::intrusive::compact_rbtree_node<void*>* const) const at ./intrusive_set_external_comparator.hh:185
 (inlined by) void boost::intrusive::bstree_algorithms<boost::intrusive::rbtree_node_traits<void*, true> >::dispose_subtree<void intrusive_set_external_comparator<rows_entry, &rows_entry::_link>::clear_and_dispose<auto current_deleter<rows_entry>()::{lambda(rows_entry*)#1}>(auto current_deleter<rows_entry>()::{lambda(rows_entry*)#1})::{lambda(boost::intrusive::compact_rbtree_node<void*>* const&)#1}>(boost::intrusive::compact_rbtree_node<void*>, auto current_deleter<rows_entry>()::{lambda(rows_entry*)#1}) at /usr/include/boost/intrusive/bstree_algorithms.hpp:2017
 (inlined by) void boost::intrusive::bstree_algorithms<boost::intrusive::rbtree_node_traits<void*, true> >::clear_and_dispose<void intrusive_set_external_comparator<rows_entry, &rows_entry::_link>::clear_and_dispose<auto current_deleter<rows_entry>()::{lambda(rows_entry*)#1}>(auto current_deleter<rows_entry>()::{lambda(rows_entry*)#1})::{lambda(boost::intrusive::compact_rbtree_node<void*>* const&)#1}>(boost::intrusive::compact_rbtree_node<void*>* const, auto current_deleter<rows_entry>()::{lambda(rows_entry*)#1}) at /usr/include/boost/intrusive/bstree_algorithms.hpp:615
 (inlined by) void intrusive_set_external_comparator<rows_entry, &rows_entry::_link>::clear_and_dispose<auto current_deleter<rows_entry>()::{lambda(rows_entry*)#1}>(auto current_deleter<rows_entry>()::{lambda(rows_entry*)#1}) at ./intrusive_set_external_comparator.hh:183
 (inlined by) mutation_partition::~mutation_partition() at ./mutation_partition.cc:235
partition_entry::squashed(seastar::lw_shared_ptr<schema const>, seastar::lw_shared_ptr<schema const>) at /usr/include/fmt/format.h:1158
partition_entry::upgrade(seastar::lw_shared_ptr<schema const>, seastar::lw_shared_ptr<schema const>, mutation_cleaner&, cache_tracker*) at /usr/include/fmt/format.h:1158
operator() at /usr/include/fmt/format.h:1158
 (inlined by) with_linearized_managed_bytes<row_cache::upgrade_entry(cache_entry&)::<lambda()>::<lambda()> > at ./utils/managed_bytes.hh:428
 (inlined by) operator() at ./row_cache.cc:1296
 (inlined by) with_allocator<row_cache::upgrade_entry(cache_entry&)::<lambda()> > at ././utils/allocation_strategy.hh:307
 (inlined by) row_cache::upgrade_entry(cache_entry&) at ./row_cache.cc:1295
operator() at /usr/include/fmt/format.h:1158
 (inlined by) operator() at ./row_cache.cc:961
 (inlined by) with_reclaiming_disabled<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()>::<lambda()>::<lambda()>&> at ././utils/logalloc.hh:745
 (inlined by) operator() at ././utils/logalloc.hh:767
 (inlined by) with_reserve<logalloc::allocating_section::operator()(logalloc::region&, Func&&) [with Func = row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()>::<lambda()>::<lambda()>]::<lambda()> > at ././utils/logalloc.hh:717
 (inlined by) operator()<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()>::<lambda()>::<lambda()> > at ././utils/logalloc.hh:768
 (inlined by) operator() at ./row_cache.cc:957
 (inlined by) with_linearized_managed_bytes<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()>::<lambda()> > at ./utils/managed_bytes.hh:428
 (inlined by) operator() at ./row_cache.cc:955
 (inlined by) with_allocator<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()> > at ././utils/allocation_strategy.hh:307
 (inlined by) operator() at ./row_cache.cc:944
apply at /usr/include/fmt/format.h:1158
 (inlined by) apply<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> > at ././seastar/include/seastar/core/apply.hh:44
 (inlined by) apply_tuple<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> > at ././seastar/include/seastar/core/future.hh:1618
 (inlined by) apply<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> > at ././seastar/include/seastar/core/future.hh:1652
 (inlined by) operator() at ././seastar/include/seastar/core/thread.hh:253
 (inlined by) call at ././seastar/include/seastar/util/noncopyable_function.hh:101
seastar::noncopyable_function<void ()>::operator()() const at ./build/release/seastar/./seastar/include/seastar/util/noncopyable_function.hh:184
 (inlined by) seastar::thread_context::main() at ./build/release/seastar/./seastar/src/core/thread.cc:286
```

DB nodes log link:
 https://cloudius-jenkins-test.s3.amazonaws.com/77890b52-9030-4a13-95d8-42764428086a/20200326_174910/db-cluster-77890b52.zip

### LINKED ISSUE #6146: Bad_alloc after alter table (add column)
*Installation details*
Scylla version (or git commit hash): 666.development-0.20200401.dee0b68347 with build-id fad26a9d18b8b394f2ed3e73aa18aee26a8806d5
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-024fdfe78273cb36b (Ireland)
instance type: i3.4xlarge

Node list: 
```
longevity-cdc-100gb-4h-master-db-node-4f421b08-1 [54.171.106.0 | 10.0.197.30]
longevity-cdc-100gb-4h-master-db-node-4f421b08-2 [34.251.17.73 | 10.0.71.90]
longevity-cdc-100gb-4h-master-db-node-4f421b08-3 [34.245.102.7 | 10.0.137.67]
longevity-cdc-100gb-4h-master-db-node-4f421b08-4 [34.249.178.182 | 10.0.32.50]
longevity-cdc-100gb-4h-master-db-node-4f421b08-5 [34.242.198.209 | 10.0.139.111]
longevity-cdc-100gb-4h-master-db-node-4f421b08-6 [52.49.87.29 | 10.0.169.211]
longevity-cdc-100gb-4h-master-db-node-4f421b08-7 [34.246.186.186 | 10.0.85.114]
longevity-cdc-100gb-4h-master-db-node-4f421b08-8 [34.243.10.106 | 10.0.166.245]
longevity-cdc-100gb-4h-master-db-node-4f421b08-9 [52.213.80.1 | 10.0.172.202]
longevity-cdc-100gb-4h-master-db-node-4f421b08-10 [18.202.241.182 | 10.0.94.201]
```

At `2020-04-02 04:55:49,405` another add_drop_column nemesis started with node#6 as the target.
The "add_drop_column" nemesis consists of repeatedly adding and removing a column from a table. 
The last query that was executed before the coredump was the following:
```'ALTER TABLE test_table ADD ( VA9DET09V2 map<frozen<set<frozen<list<inet>>>>,frozen<set<text>>> );'```
at `2020-04-02 04:57:28.000` node#1 experienced a coredump:
backtrace:
```
[shard 12] lsa - Aborting due to allocation failure
Aborting on shard 12.
0x0000000002e30642
0x0000000002dd83f4
0x0000000002dd86f5
0x0000000002dd8790
0x00007ff43bc4bb1f
/opt/scylladb/libreloc/libc.so.6+0x000000000003c624
/opt/scylladb/libreloc/libc.so.6+0x00000000000258d8
0x0000000000fa600c
0x0000000000fa3c3c
0x0000000000f26101
0x0000000000f1ea56
0x0000000003093b1c
```

decoded backtrace:
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/fmt/format.h:1158
seastar::backtrace_buffer::append_backtrace() at /usr/include/fmt/format.h:1158
 (inlined by) print_with_backtrace at ./build/release/seastar/./seastar/src/core/reactor.cc:756
seastar::print_with_backtrace(char const*) at /usr/include/fmt/format.h:1158
sigabrt_action at /usr/include/fmt/format.h:1158
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3423
 (inlined by) _FUN at ./build/release/seastar/./seastar/src/core/reactor.cc:3419
?? ??:0
?? ??:0
?? ??:0
logalloc::allocating_section::reserve() at /usr/include/fmt/format.h:1158
logalloc::allocating_section::on_alloc_failure(logalloc::region&) at /usr/include/fmt/format.h:1158
with_reclaiming_disabled<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()>::<lambda()>::<lambda()>&> at /usr/include/fmt/format.h:1158
 (inlined by) operator() at ././utils/logalloc.hh:767
 (inlined by) with_reserve<logalloc::allocating_section::operator()(logalloc::region&, Func&&) [with Func = row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()>::<lambda()>::<lambda()>]::<lambda()> > at ././utils/logalloc.hh:717
 (inlined by) operator()<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()>::<lambda()>::<lambda()> > at ././utils/logalloc.hh:768
 (inlined by) operator() at ./row_cache.cc:957
 (inlined by) with_linearized_managed_bytes<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()>::<lambda()> > at ./utils/managed_bytes.hh:428
 (inlined by) operator() at ./row_cache.cc:955
 (inlined by) with_allocator<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()> > at ././utils/allocation_strategy.hh:307
 (inlined by) operator() at ./row_cache.cc:944
apply at /usr/include/fmt/format.h:1158
 (inlined by) apply<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> > at ././seastar/include/seastar/core/apply.hh:44
 (inlined by) apply<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> > at ././seastar/include/seastar/core/future.hh:1634
 (inlined by) operator() at ././seastar/include/seastar/core/thread.hh:253
 (inlined by) call at ././seastar/include/seastar/util/noncopyable_function.hh:101
```

```
2020-04-02 04:57:28.000: (CoreDumpEvent Severity.ERROR): node=Node longevity-cdc-100gb-4h-master-db-node-4f421b08-1 [54.171.106.0 | 10.0.197.30] (seed: True)
corefile_url=
https://storage.cloud.google.com/upload.scylladb.com/core.scylla.996.a65f609114c54f0d9daca99b6921ca65.3343.1585803448000000/core.scylla.996.a65f609114c54f0d9daca99b6921ca65.3343.1585803448000000.gz
backtrace=           PID: 3343 (scylla)
           UID: 996 (scylla)
           GID: 1001 (scylla)
        Signal: 6 (ABRT)
     Timestamp: Thu 2020-04-02 04:57:28 UTC (2min 1s ago)
  Command Line: /usr/bin/scylla --blocked-reactor-notify-ms 500 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --abort-on-ebadf 1 --experimental-features cdc --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 1-7,9-15
    Executable: /opt/scylladb/libexec/scylla
 Control Group: /
       Boot ID: a65f609114c54f0d9daca99b6921ca65
    Machine ID: df877a200226bc47d06f26dae0736ec9
      Hostname: longevity-cdc-100gb-4h-master-db-node-4f421b08-1
      Coredump: /var/lib/systemd/coredump/core.scylla.996.a65f609114c54f0d9daca99b6921ca65.3343.1585803448000000
       Message: Process 3343 (scylla) of user 996 dumped core.
...

download_instructions=
gsutil cp gs://upload.scylladb.com/core.scylla.996.a65f609114c54f0d9daca99b6921ca65.3343.1585803448000000/core.scylla.996.a65f609114c54f0d9daca99b6921ca65.3343.1585803448000000.gz .
gunzip /var/lib/systemd/coredump/core.scylla.996.a65f609114c54f0d9daca99b6921ca65.3343.1585803448000000.gz
```
and at `2020-04-02 05:01:41.000` node#5 experienced a coredump as well:
The last query that was executed before this coredump was the following:
```'ALTER TABLE test_table ADD ( FJFRP7KBLF set<frozen<list<frozen<list<ascii>>>>>, XR729P6ILW map<frozen<map<decimal,ascii>>,frozen<map<text,bigint>>> );'```
stack trace:
```
[shard 9] lsa - Aborting due to allocation failure
Aborting on shard 9.
Backtrace:
0x0000000002e30642
0x0000000002dd83f4
0x0000000002dd86f5
0x0000000002dd8790
0x00007fd455ad0b1f
/opt/scylladb/libreloc/libc.so.6+0x000000000003c624
/opt/scylladb/libreloc/libc.so.6+0x00000000000258d8
0x0000000000fa600c
0x0000000000fa3c3c
0x0000000000f26101
0x0000000000f1ea56
0x0000000003093b1c
```
decoded backtrace:
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/fmt/format.h:1158
seastar::backtrace_buffer::append_backtrace() at /usr/include/fmt/format.h:1158
 (inlined by) print_with_backtrace at ./build/release/seastar/./seastar/src/core/reactor.cc:756
seastar::print_with_backtrace(char const*) at /usr/include/fmt/format.h:1158
sigabrt_action at /usr/include/fmt/format.h:1158
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3423
 (inlined by) _FUN at ./build/release/seastar/./seastar/src/core/reactor.cc:3419
?? ??:0
?? ??:0
?? ??:0
logalloc::allocating_section::reserve() at /usr/include/fmt/format.h:1158
logalloc::allocating_section::on_alloc_failure(logalloc::region&) at /usr/include/fmt/format.h:1158
with_reclaiming_disabled<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()>::<lambda()>::<lambda()>&> at /usr/include/fmt/format.h:1158
 (inlined by) operator() at ././utils/logalloc.hh:767
 (inlined by) with_reserve<logalloc::allocating_section::operator()(logalloc::region&, Func&&) [with Func = row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()>::<lambda()>::<lambda()>]::<lambda()> > at ././utils/logalloc.hh:717
 (inlined by) operator()<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()>::<lambda()>::<lambda()> > at ././utils/logalloc.hh:768
 (inlined by) operator() at ./row_cache.cc:957
 (inlined by) with_linearized_managed_bytes<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()>::<lambda()> > at ./utils/managed_bytes.hh:428
 (inlined by) operator() at ./row_cache.cc:955
 (inlined by) with_allocator<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> mutable::<lambda()> > at ././utils/allocation_strategy.hh:307
 (inlined by) operator() at ./row_cache.cc:944
apply at /usr/include/fmt/format.h:1158
 (inlined by) apply<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> > at ././seastar/include/seastar/core/apply.hh:44
 (inlined by) apply<row_cache::do_update(row_cache::external_updater, memtable&, Updater) [with Updater = row_cache::update(row_cache::external_updater, memtable&)::<lambda(logalloc::allocating_section&, boost::intrusive::set<cache_entry, boost::intrusive::member_hook<cache_entry, boost::intrusive::set_member_hook<boost::intrusive::link_mode<(boost::intrusive::link_mode_type)2> >, &cache_entry::_cache_link>, boost::intrusive::constant_time_size<false>, boost::intrusive::compare<cache_entry::compare> >::iterator, memtable_entry&, partition_presence_checker&, real_dirty_memory_accounter&)>]::<lambda()>::<lambda()> > at ././seastar/include/seastar/core/future.hh:1634
 (inlined by) operator() at ././seastar/include/seastar/core/thread.hh:253
 (inlined by) call at ././seastar/include/seastar/util/noncopyable_function.hh:101
seastar::noncopyable_function<void ()>::operator()() const at ./build/release/seastar/./seastar/include/seastar/util/noncopyable_function.hh:184
 (inlined by) seastar::thread_context::main() at ./build/release/seastar/./seastar/src/core/thread.cc:286
```

```
2020-04-02 05:01:41.000: (CoreDumpEvent Severity.ERROR): node=Node longevity-cdc-100gb-4h-master-db-node-4f421b08-5 [34.242.198.209 | 10.0.139.111] (seed: False)
corefile_url=
https://storage.cloud.google.com/upload.scylladb.com/core.scylla.996.076adb5856a04c098411cc6b0b6c3ff3.4289.1585803701000000/core.scylla.996.076adb5856a04c098411cc6b0b6c3ff3.4289.1585803701000000.gz
backtrace=           PID: 4289 (scylla)
           UID: 996 (scylla)
           GID: 1001 (scylla)
        Signal: 6 (ABRT)
     Timestamp: Thu 2020-04-02 05:01:41 UTC (2min 16s ago)
  Command Line: /usr/bin/scylla --blocked-reactor-notify-ms 500 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --abort-on-ebadf 1 --experimental-features cdc --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 1-7,9-15
    Executable: /opt/scylladb/libexec/scylla
 Control Group: /
       Boot ID: 076adb5856a04c098411cc6b0b6c3ff3
    Machine ID: df877a200226bc47d06f26dae0736ec9
      Hostname: longevity-cdc-100gb-4h-master-db-node-4f421b08-5
      Coredump: /var/lib/systemd/coredump/core.scylla.996.076adb5856a04c098411cc6b0b6c3ff3.4289.1585803701000000
       Message: Process 4289 (scylla) of user 996 dumped core.
...

download_instructions=
gsutil cp gs://upload.scylladb.com/core.scylla.996.076adb5856a04c098411cc6b0b6c3ff3.4289.1585803701000000/core.scylla.996.076adb5856a04c098411cc6b0b6c3ff3.4289.1585803701000000.gz .
gunzip /var/lib/systemd/coredump/core.scylla.996.076adb5856a04c098411cc6b0b6c3ff3.4289.1585803701000000.gz
```

The complete list of queries that were executed in the nemesis:
```
ALTER TABLE test_table DROP ( TSM93U4FAP, GEVSCN3HUF, DQKWVEX9O8, RMRO44977D, TV80O38D1U );
ALTER TABLE test_table ADD ( YM596SNBY2 map<frozen<list<varint>>,frozen<map<ascii,timestamp>>>, PI739QFOWF list<timestamp>, VCP28OZFI6 set<text> );
ALTER TABLE test_table DROP ( VCP28OZFI6 );
ALTER TABLE test_table ADD ( G8IN7R23YQ set<int> );
ALTER TABLE test_table DROP ( YM596SNBY2, XLTIVSTWVY, U7KVEM0N3U );
ALTER TABLE test_table ADD ( YMZSAFHQUH list<frozen<map<varint,blob>>>, L43L9SM00D set<ascii> );
ALTER TABLE test_table DROP ( DF5NY4BJ53, YMZSAFHQUH, PRPOPXQUOS, D4NBEN36U6 );
ALTER TABLE test_table ADD ( UMIUSDAAP8 list<text>, U8SB6BTEMN list<bigint>, B8Q03929DW list<blob>, OD7IOGDO47 map<frozen<list<int>>,frozen<set<timestamp>>> );
ALTER TABLE test_table DROP ( L43L9SM00D, UMIUSDAAP8 );
ALTER TABLE test_table ADD ( HS06CWWFEQ set<float>, FFREO1KGUS list<frozen<set<smallint>>> );
ALTER TABLE test_table DROP ( U8SB6BTEMN, VG9Y35WMLV, B8Q03929DW );
ALTER TABLE test_table ADD ( VA9DET09V2 map<frozen<set<frozen<list<inet>>>>,frozen<set<text>>> );
ALTER TABLE test_table ADD ( VA9DET09V2 map<frozen<set<frozen<list<inet>>>>,frozen<set<text>>> );   
ALTER TABLE test_table DROP ( FFREO1KGUS, G8IN7R23YQ, EIGGUUJ1ZM );
ALTER TABLE test_table ADD ( KZ6616R4P0 set<frozen<set<time>>>, BHCZQE946V set<smallint> );
ALTER TABLE test_table DROP ( OD7IOGDO47, HS06CWWFEQ );
ALTER TABLE test_table ADD ( H9281WJQNG set<frozen<set<frozen<set<blob>>>>> );
ALTER TABLE test_table DROP ( H9281WJQNG );
ALTER TABLE test_table ADD ( YFA4T6JWZ4 map<frozen<map<varchar,inet>>,boolean>, S62T4123JX list<varint> );
ALTER TABLE test_table DROP ( YFA4T6JWZ4, BHCZQE946V, UZ4HVFG1LZ );
ALTER TABLE test_table ADD ( WKAD3VSS4I list<boolean>, USTVNQ9GVR list<uuid>, JFNA153CDF map<date,frozen<list<boolean>>>, WXAI8SUUCV map<frozen<set<ascii>>,frozen<map<timeuuid,ascii>>> );
ALTER TABLE test_table DROP ( DPVTIKHXDH, PI739QFOWF, JFNA153CDF, S62T4123JX, WXAI8SUUCV );
ALTER TABLE test_table ADD ( C17LDKO23F map<frozen<set<varint>>,frozen<map<date,blob>>>, AH0M6E8N0F map<frozen<list<date>>,frozen<list<time>>>, KNY4NUIEZ4 list<date>, I5DOJSQT1X list<frozen<map<date,frozen<map<decimal,frozen<map<smallint,inet>>>>>>> );
ALTER TABLE test_table DROP ( WKAD3VSS4I );
ALTER TABLE test_table ADD ( SI80HGPP4C map<boolean,frozen<map<frozen<list<date>>,double>>>, NR9IQIZSFZ map<boolean,frozen<set<time>>>, RV6PR4V9XE map<frozen<list<frozen<set<frozen<set<timeuuid>>>>>>,frozen<list<timeuuid>>>, UUEJOJATD2 map<boolean,varint> );
ALTER TABLE test_table DROP ( USTVNQ9GVR, KZ6616R4P0, I5DOJSQT1X, SI80HGPP4C );
ALTER TABLE test_table ADD ( IGX5X2MGHU set<frozen<map<uuid,boolean>>>, K8WNQ3EKCI list<frozen<map<double,decimal>>>, E0PFQQ8PJU set<frozen<set<timeuuid>>> );
ALTER TABLE test_table DROP ( K8WNQ3EKCI );
ALTER TABLE test_table ADD ( VVSG3YSFI6 set<frozen<map<int,varchar>>>, Z81P4GQJFG list<frozen<map<text,uuid>>>, J6BZ4TAD5C map<frozen<list<uuid>>,frozen<set<smallint>>> );
ALTER TABLE test_table DROP ( E0PFQQ8PJU, UUEJOJATD2, J6BZ4TAD5C );
ALTER TABLE test_table ADD ( IF8VPQ30R3 set<frozen<set<boolean>>>, DI9TMPHA7A list<smallint>, ZHIONYI6Q5 list<ascii>, ZW8EZFM2TC list<ascii> );
ALTER TABLE test_table DROP ( ZHIONYI6Q5, IF8VPQ30R3, AH0M6E8N0F, VVSG3YSFI6 );
ALTER TABLE test_table ADD ( IDFAJNAOBG map<frozen<map<uuid,double>>,int>, I6DR389LUQ set<frozen<set<frozen<map<uuid,decimal>>>>> );
ALTER TABLE test_table DROP ( NR9IQIZSFZ, ZW8EZFM2TC, Z81P4GQJFG, KNY4NUIEZ4, I6DR389LUQ );
ALTER TABLE test_table ADD ( I0JYR3MPKK list<frozen<map<boolean,varint>>>, SPU5BS3YLA set<frozen<map<float,text>>> );
ALTER TABLE test_table DROP ( IGX5X2MGHU, DI9TMPHA7A, SPU5BS3YLA, C17LDKO23F, IDFAJNAOBG );
ALTER TABLE test_table ADD ( T96GQ7OZ74 list<frozen<set<time>>>, XX2ENP4DWT set<frozen<map<date,frozen<map<varchar,varint>>>>> );
ALTER TABLE test_table DROP ( RV6PR4V9XE );
ALTER TABLE test_table ADD ( FJFRP7KBLF set<frozen<list<frozen<list<ascii>>>>>, XR729P6ILW map<frozen<map<decimal,ascii>>,frozen<map<text,bigint>>> );
ALTER TABLE test_table DROP ( FJFRP7KBLF, I0JYR3MPKK );
ALTER TABLE test_table ADD ( B8XIYPWP6A set<frozen<map<double,bigint>>>, VPQGVO62PD set<frozen<list<boolean>>>, AHWSD32DWW set<frozen<set<uuid>>> );
ALTER TABLE test_table DROP ( XX2ENP4DWT, AHWSD32DWW );
ALTER TABLE test_table ADD ( ISUPDGFD48 set<frozen<set<smallint>>>, F8PI6DJAQ0 map<frozen<list<bigint>>,frozen<list<text>>>, TRG1ZL12LL set<frozen<list<int>>> );
ALTER TABLE test_table DROP ( F8PI6DJAQ0, XR729P6ILW );
ALTER TABLE test_table ADD ( Y2UN8VU97P list<frozen<set<int>>> );
ALTER TABLE test_table DROP ( Y2UN8VU97P, ISUPDGFD48 );
ALTER TABLE test_table ADD ( VBFJFYBIGM set<frozen<map<ascii,frozen<set<float>>>>>, K53IS2A6UV map<frozen<list<varchar>>,frozen<map<timestamp,inet>>>, HVRYPXLW78 set<frozen<set<bigint>>> );
ALTER TABLE test_table DROP ( TRG1ZL12LL, HVRYPXLW78, VPQGVO62PD, VBFJFYBIGM );
ALTER TABLE test_table ADD ( Q5YFZWTNW6 set<frozen<map<blob,timeuuid>>> );
ALTER TABLE test_table DROP ( B8XIYPWP6A, T96GQ7OZ74, Q5YFZWTNW6 );
ALTER TABLE test_table ADD ( BQ2LBWML82 list<frozen<list<smallint>>>, HH42QD00ZY list<frozen<set<blob>>>, IGCO3NBYA7 map<frozen<set<decimal>>,uuid> );
ALTER TABLE test_table DROP ( K53IS2A6UV, HH42QD00ZY, IGCO3NBYA7, BQ2LBWML82 );
ALTER TABLE test_table ADD ( ZW0JK18ZIH map<frozen<list<frozen<set<date>>>>,frozen<list<inet>>>, ACSYQ33PLJ set<frozen<list<frozen<set<timeuuid>>>>> );
ALTER TABLE test_table DROP ( ZW0JK18ZIH, ACSYQ33PLJ );
ALTER TABLE test_table ADD ( D7XZIJ0EEZ set<frozen<map<timeuuid,ascii>>>, ANCE5C265M map<frozen<list<ascii>>,frozen<set<bigint>>>, SELAN9WBXX map<frozen<map<time,varchar>>,frozen<map<frozen<set<frozen<map<text,frozen<list<uuid>>>>>>,frozen<list<boolean>>>>>, P5D2WP7LSO map<frozen<set<inet>>,frozen<list<frozen<map<blob,ascii>>>>> );
ALTER TABLE test_table DROP ( P5D2WP7LSO, D7XZIJ0EEZ, ANCE5C265M, SELAN9WBXX );
ALTER TABLE test_table ADD ( D72PE9HW5V map<frozen<list<timeuuid>>,frozen<map<boolean,decimal>>>, CG8PALO2WP map<frozen<map<text,tinyint>>,frozen<list<varint>>>, L9VIVCQHH6 map<frozen<list<frozen<list<ascii>>>>,frozen<map<blob,varchar>>>, Y57621OT0O set<frozen<set<ascii>>> );
ALTER TABLE test_table DROP ( D72PE9HW5V, CG8PALO2WP );
ALTER TABLE test_table ADD ( RG1Z94DHCB set<frozen<list<inet>>> );
ALTER TABLE test_table DROP ( L9VIVCQHH6, Y57621OT0O, RG1Z94DHCB );
ALTER TABLE test_table ADD ( KQAO49O6XJ set<frozen<list<frozen<map<frozen<list<timeuuid>>,varint>>>>>, KLNX2HFPGP list<frozen<set<frozen<list<int>>>>> );
ALTER TABLE test_table DROP ( KQAO49O6XJ, KLNX2HFPGP );
ALTER TABLE test_table ADD ( WK3FIPEP0B map<frozen<set<tinyint>>,frozen<map<bigint,frozen<list<decimal>>>>>, XJ0JZYNOE1 map<frozen<set<time>>,frozen<map<uuid,frozen<set<float>>>>>, QIFJP1E0GV set<frozen<map<timestamp,timestamp>>>, XLKFY8O9CJ list<frozen<list<int>>> );
ALTER TABLE test_table DROP ( WK3FIPEP0B, XLKFY8O9CJ, QIFJP1E0GV );
ALTER TABLE test_table ADD ( V5GGORG09I map<frozen<map<bigint,bigint>>,frozen<map<frozen<list<varchar>>,time>>>, UP7YGK88AW map<frozen<map<frozen<map<tinyint,timestamp>>,uuid>>,frozen<list<double>>>, V0EWQC1NKG map<frozen<list<boolean>>,frozen<list<float>>>, AZ37PNNA8N set<frozen<set<frozen<map<boolean,timestamp>>>>> );
ALTER TABLE test_table DROP ( AZ37PNNA8N, V5GGORG09I, UP7YGK88AW, V0EWQC1NKG );
ALTER TABLE test_table ADD ( DKOC9FP07Z set<frozen<set<tinyint>>>, YLE3H445FS set<frozen<map<varint,double>>>, Q79Q71GC51 map<frozen<map<frozen<list<int>>,text>>,frozen<list<frozen<list<smallint>>>>>, WVJV3OZYUF list<frozen<set<tinyint>>> );
ALTER TABLE test_table DROP ( DKOC9FP07Z, YLE3H445FS, Q79Q71GC51, XJ0JZYNOE1, WVJV3OZYUF );
ALTER TABLE test_table ADD ( VSVDRQSQP9 list<frozen<set<inet>>>, Z2M1MJW4J5 list<frozen<map<ascii,bigint>>> );
ALTER TABLE test_table DROP ( Z2M1MJW4J5 );
ALTER TABLE test_table ADD ( UTLNR26VOK map<frozen<map<boolean,varint>>,frozen<map<int,uuid>>>, T6MDR1FKWK list<frozen<set<timestamp>>>, COQAXN4JLN map<frozen<list<timestamp>>,frozen<list<frozen<set<frozen<map<varint,smallint>>>>>>>, XSSRG3L7BJ map<frozen<list<frozen<list<blob>>>>,frozen<map<decimal,boolean>>> );
ALTER TABLE test_table DROP ( XSSRG3L7BJ, UTLNR26VOK );
ALTER TABLE test_table ADD ( V2X6X4AH8V list<frozen<map<int,varchar>>>, FIG6IQDEZ9 map<frozen<set<blob>>,frozen<map<inet,float>>>, W0XASOTVTZ map<frozen<set<float>>,frozen<list<decimal>>>, R6FM1MUEPG map<frozen<set<timestamp>>,frozen<map<varint,frozen<set<date>>>>> );
ALTER TABLE test_table DROP ( COQAXN4JLN );
ALTER TABLE test_table ADD ( DMEZLY8T9R set<frozen<set<frozen<map<timeuuid,tinyint>>>>>, JLETAAMLX4 map<frozen<list<frozen<map<double,decimal>>>>,frozen<set<uuid>>>, FLQ35F13AP set<frozen<map<text,inet>>>, RUDBEPVWLH set<frozen<list<blob>>> );
ALTER TABLE test_table DROP ( FIG6IQDEZ9, JLETAAMLX4 );
ALTER TABLE test_table ADD ( GPJ7BQUFRO map<frozen<set<frozen<list<timestamp>>>>,frozen<set<frozen<map<varchar,decimal>>>>>, T1ERLG0AKT set<frozen<set<frozen<map<tinyint,ascii>>>>>, CECS4D0S5O list<frozen<set<frozen<map<tinyint,smallint>>>>> );
ALTER TABLE test_table DROP ( T1ERLG0AKT, CECS4D0S5O, FLQ35F13AP );
ALTER TABLE test_table ADD ( EX5O93X7BT list<frozen<set<decimal>>>, N7J5V038E3 set<frozen<map<frozen<set<decimal>>,int>>>, NI7W05WFRQ set<frozen<set<timestamp>>> );
ALTER TABLE test_table DROP ( NI7W05WFRQ );
ALTER TABLE test_table ADD ( AVNIGOZ8UX list<frozen<set<uuid>>>, F2SWA7GC0E map<frozen<list<text>>,frozen<set<text>>> );
ALTER TABLE test_table DROP ( W0XASOTVTZ );
ALTER TABLE test_table ADD ( MLG2O912YE map<frozen<map<date,frozen<map<double,float>>>>,frozen<map<varchar,varint>>>, W3HYNSSBN9 map<frozen<set<frozen<map<smallint,double>>>>,frozen<set<frozen<set<time>>>>>, X9ZKYB7IIM set<frozen<list<timeuuid>>>, N6H9PGX7W4 map<frozen<list<time>>,frozen<map<frozen<list<blob>>,tinyint>>> );
ALTER TABLE test_table DROP ( MLG2O912YE, T6MDR1FKWK, W3HYNSSBN9, V2X6X4AH8V );
ALTER TABLE test_table ADD ( LRPHUR7O9P map<frozen<set<uuid>>,frozen<map<double,frozen<map<frozen<set<ascii>>,smallint>>>>>, L9BRXOVIUB set<frozen<set<varint>>>, HZHLRTXIHD set<frozen<set<float>>> );
ALTER TABLE test_table DROP ( AVNIGOZ8UX, LRPHUR7O9P, VSVDRQSQP9 );
ALTER TABLE test_table ADD ( Q42WK76P7W list<frozen<list<uuid>>> );
ALTER TABLE test_table DROP ( EX5O93X7BT );
ALTER TABLE test_table ADD ( WBOSLQ1K63 set<frozen<set<date>>>, IERZYNHMMA map<frozen<map<timeuuid,blob>>,frozen<map<frozen<list<decimal>>,frozen<set<blob>>>>>, TU8F0S27MD set<frozen<map<frozen<set<bigint>>,frozen<map<inet,frozen<list<tinyint>>>>>>> );
ALTER TABLE test_table DROP ( RUDBEPVWLH, HZHLRTXIHD );
ALTER TABLE test_table ADD ( VFEONR07HP map<frozen<set<frozen<map<inet,bigint>>>>,frozen<list<uuid>>>, W2I5S0SLXQ set<frozen<set<frozen<list<text>>>>>, GBJY6Y482E map<frozen<set<frozen<list<tinyint>>>>,frozen<set<timeuuid>>> );
ALTER TABLE test_table DROP ( X9ZKYB7IIM, W2I5S0SLXQ, WBOSLQ1K63, VFEONR07HP );
ALTER TABLE test_table ADD ( OQRCQX15BA set<frozen<map<time,frozen<list<ascii>>>>>, AT00V25ZS9 list<frozen<list<float>>>, RCH1WYQJQ5 map<frozen<list<inet>>,frozen<set<frozen<map<bigint,frozen<list<timeuuid>>>>>>>, VJ43STWM92 list<frozen<set<frozen<list<text>>>>> );
ALTER TABLE test_table DROP ( GPJ7BQUFRO );
ALTER TABLE test_table ADD ( X9IUSXVQS4 set<frozen<set<text>>>, ZIN2DZJIUP map<frozen<map<frozen<list<frozen<set<smallint>>>>,frozen<map<frozen<set<blob>>,decimal>>>>,frozen<map<frozen<list<frozen<map<ascii,tinyint>>>>,frozen<list<int>>>>>, L76S293LLN map<frozen<list<double>>,frozen<list<blob>>>, X2OY979ZEO list<frozen<list<double>>> );
ALTER TABLE test_table DROP ( N7J5V038E3, Q42WK76P7W, VJ43STWM92 );
ALTER TABLE test_table ADD ( GM3EME8F6V set<frozen<set<int>>>, NE5MFWHO4N list<frozen<set<double>>> );
ALTER TABLE test_table DROP ( AT00V25ZS9 );
ALTER TABLE test_table ADD ( OFXBHZ9K0B set<frozen<list<ascii>>>, T45CFY8D22 set<frozen<set<blob>>>, P811SPSMNE set<frozen<map<frozen<map<double,varint>>,decimal>>> );
ALTER TABLE test_table DROP ( L76S293LLN );
ALTER TABLE test_table ADD ( L89RY3QUIU list<frozen<list<timeuuid>>> );
ALTER TABLE test_table DROP ( RCH1WYQJQ5, GM3EME8F6V );
ALTER TABLE test_table ADD ( LX9DVHA4WY map<frozen<set<text>>,frozen<list<timestamp>>>, LLS4ZXF0F4 set<frozen<list<float>>>, Z1YJWCISJV list<frozen<map<frozen<list<double>>,frozen<set<frozen<set<frozen<map<boolean,bigint>>>>>>>>> );
ALTER TABLE test_table DROP ( OQRCQX15BA );
ALTER TABLE test_table ADD ( LME9FGURT5 set<frozen<set<frozen<list<float>>>>>, MD3BLF34TO set<frozen<set<varchar>>>, CPWN9RJTYW map<frozen<map<float,date>>,frozen<map<frozen<list<timeuuid>>,frozen<list<varchar>>>>> );
ALTER TABLE test_table DROP ( X9IUSXVQS4, L9BRXOVIUB );
ALTER TABLE test_table ADD ( UYKIM1LG20 map<frozen<map<frozen<list<date>>,frozen<map<varchar,frozen<map<int,date>>>>>>,frozen<list<frozen<set<uuid>>>>>, SFJLERFW52 map<frozen<map<tinyint,frozen<list<uuid>>>>,frozen<list<int>>>, WZF40XN64O map<frozen<set<bigint>>,frozen<set<frozen<map<blob,blob>>>>> );
ALTER TABLE test_table DROP ( GBJY6Y482E, X2OY979ZEO, T45CFY8D22, ZIN2DZJIUP, P811SPSMNE );
ALTER TABLE test_table ADD ( GFILD2ZW6T map<frozen<set<frozen<map<frozen<list<smallint>>,timeuuid>>>>,frozen<map<smallint,frozen<list<frozen<map<date,frozen<list<uuid>>>>>>>>> );
ALTER TABLE test_table DROP ( IERZYNHMMA, WZF40XN64O, NE5MFWHO4N, L89RY3QUIU, MD3BLF34TO );
ALTER TABLE test_table ADD ( VIHKN2KX7D set<frozen<set<frozen<set<time>>>>>, SR4CS3ECAN map<frozen<set<boolean>>,frozen<set<frozen<map<text,varint>>>>> );
ALTER TABLE test_table DROP ( R6FM1MUEPG, OFXBHZ9K0B, CPWN9RJTYW, LME9FGURT5, SR4CS3ECAN );
ALTER TABLE test_table ADD ( CGYBEEDHPZ list<frozen<map<frozen<list<varint>>,frozen<set<ascii>>>>>, AXYMC0J9TI set<frozen<list<double>>> );
ALTER TABLE test_table DROP ( DMEZLY8T9R, UYKIM1LG20, F2SWA7GC0E, LLS4ZXF0F4, CGYBEEDHPZ );
ALTER TABLE test_table ADD ( XENI5ZHVVF set<frozen<list<smallint>>>, HXO7S538IH list<frozen<list<frozen<set<smallint>>>>>, DHRAXYWRDU map<frozen<map<blob,frozen<list<inet>>>>,frozen<list<frozen<map<text,int>>>>> );
ALTER TABLE test_table DROP ( TU8F0S27MD );
ALTER TABLE test_table ADD ( QQWSUQKGFR set<frozen<set<frozen<map<date,blob>>>>>, ALW2EDPUXR map<frozen<list<tinyint>>,frozen<map<frozen<map<boolean,frozen<map<timeuuid,float>>>>,int>>>, EY4S1S32Z3 map<frozen<list<smallint>>,frozen<map<frozen<set<smallint>>,frozen<list<tinyint>>>>>, Q96ADOL8IM list<frozen<set<float>>> );
ALTER TABLE test_table DROP ( Z1YJWCISJV, DHRAXYWRDU, HXO7S538IH );
ALTER TABLE test_table ADD ( W6N1RU0HJL map<frozen<set<frozen<set<varint>>>>,frozen<list<frozen<map<date,bigint>>>>>, ECNC3I553J set<frozen<list<decimal>>>, MWQPKR1XHG map<frozen<set<double>>,frozen<list<frozen<set<bigint>>>>>, YM5M8IJFGM set<frozen<set<frozen<map<decimal,varint>>>>> );
ALTER TABLE test_table DROP ( GFILD2ZW6T, YM5M8IJFGM, VIHKN2KX7D, MWQPKR1XHG );
ALTER TABLE test_table ADD ( QN4OAG98H0 list<frozen<map<uuid,ascii>>>, KIWOLFE5IR map<frozen<map<timestamp,time>>,frozen<list<date>>> );
ALTER TABLE test_table DROP ( QN4OAG98H0, EY4S1S32Z3, SFJLERFW52, XENI5ZHVVF );
ALTER TABLE test_table ADD ( S003XM1EGD set<frozen<set<frozen<list<boolean>>>>>, ULC2WWHNSM map<frozen<set<date>>,frozen<map<frozen<list<uuid>>,text>>> );
ALTER TABLE test_table DROP ( AXYMC0J9TI, ALW2EDPUXR, ECNC3I553J );
ALTER TABLE test_table ADD ( I4AMMEIY6X list<frozen<set<boolean>>>, FWCMFIYP14 list<frozen<set<ascii>>> );
ALTER TABLE test_table DROP ( ULC2WWHNSM, W6N1RU0HJL );
ALTER TABLE test_table ADD ( GMOLI4K987 list<frozen<list<time>>>, AHN6S7BD6F list<frozen<set<varint>>> );

```

It's also worth noting that the whole situation caused hundreds of failures of c-s, like so:
```
java.io.IOException: Operation x10 on key(s) [QA!RRF[P]: Error executing: (UnavailableException): Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)
2020-04-02 05:02:22.906: (CassandraStressLogEvent Severity.ERROR): type=IOException regex=java\.io\.IOException line_number=35912 node=Node longevity-cdc-100gb-4h-master-loader-node-4f421b08-1 [63.35.203.50 | 10.0.158.149] (seed: False)
```
The test that discovered the issue was longevity cdc 4h

Test id: 4f421b08-fe7a-4d2e-b4ed-d2518462c8f1
logs:
```
+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                           Log links for testrun with test id 4f421b08-fe7a-4d2e-b4ed-d2518462c8f1                                            |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type    | Link                                                                                                                         |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------+
| 20200402_082410 | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/4f421b08-fe7a-4d2e-b4ed-d2518462c8f1/20200402_082410/db-cluster-4f421b08.zip  |
| 20200402_082410 | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/4f421b08-fe7a-4d2e-b4ed-d2518462c8f1/20200402_082410/loader-set-4f421b08.zip  |
| 20200402_082410 | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/4f421b08-fe7a-4d2e-b4ed-d2518462c8f1/20200402_082410/monitor-set-4f421b08.zip |
| 20200402_082410 | sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/4f421b08-fe7a-4d2e-b4ed-d2518462c8f1/20200402_082410/sct-runner-4f421b08.zip  |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by haaawk**
We inherited from Origin a `caching` table parameter. It's a map of named caching parameters. Before this PR two caching parameters were expected: `keys` and `rows_per_partition`. So far we have been ignoring them. This PR adds a new caching parameter called `enabled` which can be set to `true` or `false` and controls the usage of the cache for the table. By default, it's set to `true` which reflects Scylla behavior before this PR.

This new capability is used to disable caching for CDC Log table. It is desirable because CDC Log entries are not expected to be read often. They also put much more pressure on memory than entries in Base Table. This is caused by the fact that some writes to Base Table can override previous writes. Every write to CDC Log is unique and does not invalidate any previous entry.

Fixes #6098
Fixes #6146

Tests: unit(dev, release), manual

### CODE REVIEW

File: caching_options.hh [hunk 1]
```diff
@@ -59,8 +62,17 @@ class caching_options {
...
+    bool enabled() const {
+        return _enabled;
+    }
+
     std::map<sstring, sstring> to_map() const {
-        return {{ "keys", _key_cache }, { "rows_per_partition", _row_cache }};
+        std::map<sstring, sstring> res = {{ "keys", _key_cache },
+                { "rows_per_partition", _row_cache }};
+        if (!_enabled) {
+            res.insert({"enabled", "false"});
```
Comment (denesb) [inline caching_options.hh:73]: Why is this conditional?

Comment (haaawk) [reply caching_options.hh:73]: Because missing parameter means enabled == true. That's just to keep it more backward compatible.

Comment (denesb) [reply caching_options.hh:73]: I think we should add it unconditionally, otherwise all code wishing to use this map has to learn about what a missing `enabled` means.

Comment (haaawk) [reply caching_options.hh:73]: The code will have to do it anyway because the parameter is missing on older nodes and then it means enabled == true.

Comment (denesb) [reply caching_options.hh:73]: Still, why complicate this method for no gain? We don't need this to be backward compatible as older nodes will not see this option anyway, will they?

Comment (haaawk) [reply caching_options.hh:73]: Well they shouldn't see it because of the feature but I think it's safer for rollback or stuff like this. This is not big complication and actually gives us more safety. For example if no table has disabled cache, it is like the feature does not exist at all. zero-overhead feature ;)

Comment (denesb) [reply caching_options.hh:73]: Ok.

File: table.cc [hunk 2]
```diff
@@ -723,8 +723,7 @@ table::update_cache(lw_shared_ptr<memtable> m, sstables::shared_sstable sst) {
     if (_config.enable_cache) {
         return _cache.update(adder, *m);
     } else {
-        adder();
-        return m->clear_gently();
+        return _cache.invalidate(adder).then([m] { return m->clear_gently(); });
```
Comment (avikivity) [inline table.cc:726]: Why do we need the clear_gently?

File: caching_options.hh (hunk 1 above)
Comment (avikivity) [reply caching_options.hh:73]: Agree it's safer. It also allows a DESCRIBE TABLE on a new cluster to be replayed on an old cluster with fewer surprises.

File: table.cc (hunk 2 above)
Comment (haaawk) [reply table.cc:726]: I'm not sure. I just left what was there before. @tgrabiec probably knows best.

File: database.cc [hunk 3]
```diff
@@ -906,7 +906,7 @@ keyspace::make_column_family_config(const schema& s, const database& db) const {
     cfg.enable_disk_reads = _config.enable_disk_reads;
     cfg.enable_disk_writes = _config.enable_disk_writes;
     cfg.enable_commitlog = _config.enable_commitlog;
-    cfg.enable_cache = _config.enable_cache;
+    cfg.enable_cache = _config.enable_cache && s.caching_options().enabled();
```
Comment (avikivity) [inline database.cc:909]: What about ALTER TABLE? We need to be able to change this dynamically.

File: table.cc (hunk 2 above)
Comment (avikivity) [reply table.cc:726]: Ah, of course you need it, to remove stuff from the memtable. I didn't look at the code thoroughly and thought it was about the cache.

File: database.cc (hunk 3 above)
Comment (haaawk) [reply database.cc:909]: Alter table works as well. I checked.

**Comment by avikivity** [comment]
Looks good, but need to handle ALTER TABLE.

File: database.cc (hunk 3 above)
Comment (haaawk) [reply database.cc:909]: Well - I checked that the property was set, I will double-check that new operations on the table start/stop using cache.

Comment (haaawk) [reply database.cc:909]: You're right. The alter table does not change the behavior dynamically. Only after a restart. I will fix that.

**Comment by haaawk** [comment]
I added support for ALTER TABLE @avikivity and tested it both enable -> disable and disable -> enable.

**Comment by denesb** [comment]
@haaawk what about `schema::describe()`?

**Comment by haaawk** [comment]
> @haaawk what about `schema::describe()`?

It just works @denesb - WITH CACHING was there before. I just added new param inside the map.

**Comment by denesb** [comment]
> > @haaawk what about `schema::describe()`?
> 
> It just works @denesb - WITH CACHING was there before. I just added new param inside the map.

Ok, LGTM then. We should also check how cqlsh et. al. handles the new param, but that is different repo anyway.

**Comment by haaawk** [comment]
> > > @haaawk what about `schema::describe()`?
> > 
> > 
> > It just works @denesb - WITH CACHING was there before. I just added new param inside the map.
> 
> Ok, LGTM then. We should also check how cqlsh et. al. handles the new param, but that is different repo anyway.

I tried it and it just prints it alright. It is simple because this is a standard param map used everywhere (compaction, network strategy, ...)

**Comment by denesb** [comment]
On Thu, 2020-04-30 at 08:19 -0700, Piotr Jastrzębski wrote:
> 
> 
> > > > @haaawk what about schema::describe()?
> > > 
> > > It just works @denesb - WITH CACHING was there before. I just
> > > added new param inside the map.
> > 
> > Ok, LGTM then. We should also check how cqlsh et. al. handles the
> > new param, but that is different repo anyway.
> 
> I tried it and it just prints it alright. It is simple because this
> is a standard param map used everywhere (compaction, network
> strategy, ...)

Awesome!



—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/scylladb/scylla/pull/6312#issuecomment-621920932",
"url": "https://github.com/scylladb/scylla/pull/6312#issuecomment-621920932",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by haaawk** [comment]
ping @avikivity @tgrabiec

File: caching_options.hh (hunk 1 above)
Comment (avikivity) [reply caching_options.hh:73]: It's also better to preserve the schema digest.

Comment (avikivity) [reply caching_options.hh:73]: But, something is missing here. If the user specifed enabled: true explicitly, then when we call to_map() we get it back without the option.

You can fix by making _enabled an optional<boo> (and return value_or(true) from enabled()).

Comment (avikivity) [reply caching_options.hh:73]: And this can lead to schema digest mismatch. Please add a test that fails on the current patch and succeeds on the fixed patch.

Comment (haaawk) [reply caching_options.hh:73]: Could you explain more how this can create a schema digest mismatch @avikivity? I don't see it. No matter whether enabled was set explicitly or wasn't set at all, exchanged schema will have no 'enabled' element in the map. Or am I missing something?

Comment (haaawk) [reply caching_options.hh:73]: > But, something is missing here. If the user specifed enabled: true explicitly, then when we call to_map() we get it back without the option.
> 
> You can fix by making _enabled an optional (and return value_or(true) from enabled()).

Setting 'enabled' to true and not setting means the same. Is it really a problem?

File: cql3/statements/cf_prop_defs.hh [hunk 4]
```diff
@@ -95,6 +95,7 @@ public:
     std::map<sstring, sstring> get_compaction_options() const;
     std::optional<std::map<sstring, sstring>> get_compression_options() const;
     const cdc::options* get_cdc_options(const schema::extensions_map&) const;
+    std::optional<caching_options> get_caching_options() const;
```
Comment (avikivity) [inline cql3/statements/cf_prop_defs.hh:98]: Maybe it's simpler not to return optional here, a map can be empty. Returning an optional means everyone has to check if it exists or not.

File: table.cc [hunk 5]
```diff
@@ -2008,6 +2008,10 @@ void table::set_schema(schema_ptr s) {
         _counter_cell_locks->set_schema(s);
     }
     _schema = std::move(s);
+    _config.enable_cache = ks.get_config().enable_cache && _schema->caching_options().enabled();
+    if (!_config.enable_cache) {
+        _cache.invalidate([] {}).get();
+    }
```
Comment (avikivity) [inline table.cc:2012]: Reads that are in-progress while this is happening can still populate the cache after invalidate() completes.

That's not a huge problem since the cache will still be coherent, and when we enable it again the data from those reads will be valid.

Maybe it's better to drop the invalidate() call. The data in the cache will age out naturally, and this allows ALTER TABLE to complete more quickly.

Comment (haaawk) [reply table.cc:2012]: I see no problem in removing this. Will do.

**Comment by avikivity** [comment]
Looks good. I think I found a minor problem in to_map().

**Comment by haaawk** [comment]
> Looks good. I think I found a minor problem in to_map().

Is it really a problem that to_map always returns missing 'enabled' when it's set to true? It's safer regarding backward compatibility this way.

File: caching_options.hh (hunk 1 above)
Comment (avikivity) [reply caching_options.hh:73]: I think you are correct. I thought the map could get into schema_tables directly, but it always goes through to_map(), so enabled: true will always be filtered out.

File: cql3/statements/cf_prop_defs.hh (hunk 4 above)
Comment (haaawk) [reply cql3/statements/cf_prop_defs.hh:98]: If I remember correctly, this function is used in both create table and alter table. In alter table, an empty map is different than not present at all. The empty map clears out the setting while the missing map leaves the setting unchanged.

Comment (avikivity) [reply cql3/statements/cf_prop_defs.hh:98]: Makes sense!

**Comment by haaawk** [comment]
I removed cache invalidation in alter table. @avikivity @tgrabiec please have a look

File: table.cc [hunk 6]
```diff
@@ -1951,7 +1951,7 @@ std::chrono::steady_clock::duration table::enable_sstable_write(int64_t new_gene
     return std::chrono::steady_clock::now() - _sstable_writes_disabled_at;
 }
 
-void table::set_schema(schema_ptr s) {
+void table::set_schema(const keyspace& ks, schema_ptr s) {
```
[the remark this answers is not in the document]
Comment (haaawk) [reply table.cc:1952]: Sure. I will give it a try and let you know if it worked out well.

[the remark this answers is not in the document]
Comment (haaawk) [reply table.cc:1952]: done.

**Comment by haaawk** [comment]
I addressed @tgrabiec comment and added table::cache_enabled(). @avikivity @tgrabiec Do you have any more comments or are we good to merge?

**Comment by tgrabiec** [comment]
@haaawk I don't see `cache_enabled()` in the branch.

**Comment by haaawk** [comment]
> @haaawk I don't see `cache_enabled()` in the branch.

I pushed the wrong branch. Sorry about that @tgrabiec. I'm pushing the correct one right now.

**Comment by haaawk** [comment]
@avikivity Tomek and Botond already approved. Would you do the honors?

**Comment by avikivity** [comment]
Queued.

**Comment by haaawk** [comment]
> Queued.

Thank you.

**Comment by avikivity** [comment]
Dequeued per @bhalevy's request, fails next-gating dtests.

**Comment by haaawk** [comment]
I had to add property_definitions::get which returns variant and allows checking whether the parameter has a map or a string value and use it to handle legacy representation of caching parameter. @avikivity please have a look.

**Comment by haaawk** [comment]
@avikivity for your convenience here's the diff on the change since last version that was approved:
```
diff --git a/cql3/statements/property_definitions.hh b/cql3/statements/property_definitions.hh
index 5cfe01450..0b51d9de6 100644
--- a/cql3/statements/property_definitions.hh
+++ b/cql3/statements/property_definitions.hh
@@ -86,6 +86,8 @@ class property_definitions {
 public:
     bool has_property(const sstring& name) const;
 
+    std::optional<value_type> get(const sstring& name) const;
+
     sstring get_string(sstring key, sstring default_value) const;
 
     // Return a property value, typed as a Boolean
diff --git a/cql3/statements/cf_prop_defs.cc b/cql3/statements/cf_prop_defs.cc
index 5fffd399c..8c38f15e0 100644
--- a/cql3/statements/cf_prop_defs.cc
+++ b/cql3/statements/cf_prop_defs.cc
@@ -205,11 +205,18 @@ std::optional<utils::UUID> cf_prop_defs::get_id() const {
 }
 
 std::optional<caching_options> cf_prop_defs::get_caching_options() const {
-    auto caching_options_map = get_map(KW_CACHING);
-    if (!caching_options_map || caching_options_map->empty()) {
+    auto value = get(KW_CACHING);
+    if (!value) {
         return {};
     }
-    return caching_options::from_map(*caching_options_map);
+    return std::visit(make_visitor(
+        [] (const property_definitions::map_type& map) {
+            return map.empty() ? std::nullopt : std::optional<caching_options>(caching_options::from_map(map));
+        },
+        [] (const sstring& str) {
+            return std::optional<caching_options>(caching_options::from_sstring(str));
+        }
+    ), *value);
 }
 
 const cdc::options* cf_prop_defs::get_cdc_options(const schema::extensions_map& schema_exts) const {
diff --git a/cql3/statements/property_definitions.cc b/cql3/statements/property_definitions.cc
index 39f605fee..9cbdce86f 100644
--- a/cql3/statements/property_definitions.cc
+++ b/cql3/statements/property_definitions.cc
@@ -109,6 +109,13 @@ bool property_definitions::has_property(const sstring& name) const {
     return _properties.find(name) != _properties.end();
 }
 
+std::optional<property_definitions::value_type> property_definitions::get(const sstring& name) const {
+    if (auto it = _properties.find(name); it != _properties.end()) {
+        return it->second;
+    }
+    return std::nullopt;
+}
+
 sstring property_definitions::get_string(sstring key, sstring default_value) const {
     auto value = get_simple(key);
     if (value) {
```

**Comment by haaawk** [comment]
Do you have any more comments @avikivity?

**Comment by avikivity** [comment]
Looks good, merging.
