### PR TITLE
Exorcise assertions from Alternator, using a new throwing_assert() macro

### LINKED ISSUE #28308: Add assert-like version of on_internal_error
Despite all the horrors of `assert()` (sadly renamed in aa1270a00c40af8dddb71b8b8d80d10957d92798 to `SCYLLA_ASSERT()` and not to `DANGEROUS_ASSERT()`), documented in https://github.com/scylladb/scylladb/issues/7871, Scylla developers keep sending patches using it.

This is while we have a good alternative, `on_internal_error()`, that:

1. In test runs, on_internal_error() crashes just like assert(), making it impossible to overlook and some possibly easier to debug().
2. In real deployments, on_internal_error() doesn't crash but also unlike old-time assert() doesn't get compiled out - it throws an exception aborting the affected operation. This feature is super-important - if we want to assert an important pre-condition, we can't allow the affected code to continue with this pre-condition violated, but we can allow other code, in other types of code, etc., to continue. on_internal_error() also logs to our real logger, not to the "standard error" which often gets lost.

I suspect that people avoid `on_internal_error()` because it's **inconvenient**, not because they really prefer `assert()`.

Until commit 259811b6ec8b03bcb37adb04c645522d2d0dc6d4, using Seastar's on_internal_error() required having a logger, which was inconvenient. This is no longer a problem - we have `utils::on_internal_error()` in Scylla, which uses a fixed logger.

But it's still longer and more verbose to use on_internal_error, because it requires you to put the tested expression on a different line and to put work into inventing an error message - for example
```c++
        if (!_vec_lock.locked()) {
            utils::on_internal_error("thread_for_each_nested called without holding the vector lock");
        }
```
instead of just
```c++
      assert(_vec_lock.locked());
```

I want to propose adding a new `utils::assert(expression, optional_string)` which:

1. Checks expression, calling utils::on_internal_error() if it is false.
2. If optional_string is given, use it as the error message (remember that this error message is logged and also ends up in an exception). If not, assert() will compose the error message from the expression's text (this might need a macro to pull off :-(), and/or the call site's file name and line number. It will mark the if as unlikely, and the code in it will be cold code moved out of the way.

### PR DESCRIPTION
**Pull request by nyh**
assert(), and SCYLLA_ASSERT() are evil (Refs #7871) because they can cause the entire Scylla cluster to crash mysteriously instead of cleanly failing the specific request that encountered a serious problem of failed pre-requisite.

In this two-patch series, in the first patch we introduce a new macro throwing_assert(), a convenient drop-in replacement for SCYLLA_ASSERT() but which has all the benefits of on_internal_error() instead of the dangers of SCYLLA_ASSERT().
In the second patch we use the new function to replace every call to SCYLLA_ASSERT() in Alternator by the new throwing_assert(). 

Here is an example from the second patch to demonstrate the power of this approach: The Alternator code uses the attrs_column() function to retrieve the ":attrs" column of a schema. Since every Alternator table always has an ":attrs" column in its schema, we felt safe to SCYLLA_ASSERT() that this column exists. However, imagine that one day because of a bug, one Alternator table is missing this column. Or maybe not a bug - maybe a malicious user on a shared cluster found a way to deliberately delete this column (e.g, with a CQL command!) and this check fails. Before this patch, the entire Scylla node will crash. If the same request is sent to all nodes - the entire cluster will crash. The user might not even know which request caused this crash. In contrast, after this patch, the specific operation - e.g., PutItem - will get an exception. Only this operation, and nothing else, will be aborted, and the user who sent this request will even get an "Internal Server Error" with the assertion-failure message, alerting them that this specific query is causing problems, while other queries might work normally.

There's no need to backport this patch - unless it becomes annoying that other branches don't have the throwing_assert() function and we want it to ease other backports.

Fixes #28308.

### CODE REVIEW

**Comment by nyh** [comment]
Note to reviewers: I'm not married to the name "REQUIRE". I thought long about it and changed my mind several times, and at the end came up with the name REQUIRE. Let me know if you have a better suggestion.

Another more outlandish option is to call the new function... SCYLLA_ASSERT()! We'll finally have a good SCYLLA_ASSERT() instead of the dangerous one we have now. Does this seem like a good idea to you?
I'm a bit worried that if someone used SCYLLA_ASSERT() inside a noexcept code, perhaps the result won't be pretty if we throw an exception and crash because of the noexcept context. But will it be less pretty than SCYLLA_ASSERT() that also crashes? I'm not sure.

**Comment by nyh** [comment]
‎ֹTurns out we have one test that uses the name "REQUIRE" internally as a wrapper for BOOST_REQUIRE, so I guess if I want to use the name REQUIRE I'll need to rename it in that test.

File: utils/on_internal_error.hh [hunk 1]
```diff
@@ -38,4 +39,23 @@ namespace utils {
...
 [[noreturn]] void on_fatal_internal_error(std::string_view reason) noexcept;
 
-}
+/// REQUIRE(expression) is a safe replacement for assert() that uses
+/// on_internal_error() to report failures. It aims to bring the best of both
+/// worlds: like assert() it easy and concise to use - taking care of both
+/// the checking and error reporting on a single line. But like
+/// on_internal_error(), it doesn't crash the program in production,
+/// but it still checks the condition and if not fullfilled, it throws an
+/// an exception the code's flow can't continue past the unfulfilled
```
[the remark this answers is not in the document]
Comment (nyh) [reply utils/on_internal_error.hh]: Good fixes.

File: utils/on_internal_error.cc [hunk 2]
```diff
@@ -23,4 +23,12 @@ namespace utils {
     seastar::on_fatal_internal_error(on_internal_error_logger, reason);
 }
```
Comment (avikivity) [inline utils/on_internal_error.cc:25]: >     REQUIRE(p != nullptr);

REQUIRE is a bad name, because it give no indication about what happens if the requirement is not fulfilled. It's also a C macro.

I suggest to add on_internal_error_if() instead.

File: utils/on_internal_error.hh [hunk 3]
```diff
@@ -38,4 +39,23 @@ namespace utils {
...
+/// requirement.
+/// REQUIRE is a macro to allow it to capture the expression as a string,
+/// so the caller doesn't need to write a special string.
+namespace internal {
+[[noreturn]] [[gnu::cold]] void require_failed(const char* expr_str, const std::source_location& loc);
```
Comment (avikivity) [inline utils/on_internal_error.hh]: noreturn is enough, it's assumed unlikely.

File: utils/on_internal_error.hh [hunk 4]
```diff
@@ -38,4 +39,23 @@ namespace utils {
...
+} // namespace internal
+#define REQUIRE(expr) \
+    do { \
+        if (!(expr)) [[unlikely]] \
```
Comment (avikivity) [inline utils/on_internal_error.hh]: unlikely is unnecessary due to noreturn.

File: utils/on_internal_error.cc (hunk 2 above)
Comment (nyh) [reply utils/on_internal_error.cc:25]: I wanted the new function to be a drop-in replacement for assert(), or at least not require a lot of re-learning to use, and on_internal_error_if() reverse's asserts boolean - it suggests an error is generated if, not if-not.
So maybe a name `on_internal_error_if_not` would be fine. But it's too long.

I wonder, would you be willing to call the new function... SCYLLA_ASSERT()? I mean I can provide a patch that replaces the existing SCYLLA_ASSERT, which crashes on failure, with this implementation that solves #7871 for good (well, almost).

Finally, it unfortunately needs to be a macro, for just one reason - the same reason that made SCYLLA_ASSERT and the original assert() macros: The reason is that I wanted the expression to be captured as a string instead of the user needing to come up with an error string. I don't know how to do this without a macro.

File: utils/on_internal_error.hh (hunk 4 above)
Comment (nyh) [reply utils/on_internal_error.hh]: Are you sure about that?

While I guess it makes sense to assume that non-returning code is unlikely, it's also conceivable that certain code paths never return (e.g., their whole purpose is to throw an exception) and yet they include an if() that is actually very likely. For example consider the silly example:

```c++
/// usually_throw_error() throws an exception, except in the rare condition where no_exceptions==true
void usually_throw_error() {
    if (!no_exceptions) { // this if() is very likely! Be it calls a no-return function really_throw_error()
          really_throw_error();
    }
}
```

I'm not saying my example is useful in any way. But I'm saying that unless you can find a place in the standard which claims that "an if() is considered unlikely if the code block calls a no-return function", I propose that I don't skimp on these hints and just use all of them, even if some compilers will not need all of them.

Comment (avikivity) [reply utils/on_internal_error.hh]: Here's clang's assessment: https://godbolt.org/z/fbGesfv8E

The example you gave is not a noreturn function itself.

Comment (nyh) [reply utils/on_internal_error.hh]: I don't know what you're showing me in this assembly output - that the call to not_returning is put out of line? I don't understand what it proves. I do agree that if you had to **guess** if some non-returning function is the common case or not, you would guess it is not the common case. However, 1. I am not sure it's guaranteed by the standard, so what have we got to lose by also specifying unlikely? and 2. Even in rarely used code, some specific branch might be **likely**, not unlikely. I agree that since the code is a-priory rarely used, it doesn't matter if we correctly correctly guess that branch or not. But what does it hurt if we give the correct hint?

And I don't understand the second sentence - a function calling REQUIRE is also not a noreturn function itself.

**Comment by nyh** [comment]
Pushed new version fixing copilot's suggestions and also hopefully making the test pass. Did not yet implement Avi's suggestions (I'm still discussing them with him above).

**Comment by nyh** [comment]
I've converted this patch to a draft, and want to try a different approach - change the existing SCYLLA_ASSERT() instead of inventing a new function! Let's see how this works.

**Comment by nyh** [comment]
I created a different solution to replace this one: https://github.com/scylladb/scylladb/pull/28480

**Comment by nyh** [comment]
> Note to reviewers: I'm not married to the name "REQUIRE". I thought long about it and changed my mind several times, and at the end came up with the name REQUIRE. Let me know if you have a better suggestion.

@avikivity, @denesb, do you have a better idea for the new function name? I called it "REQUIRE" but Avi didn't like it. I can call it "ASSERT" - would that be better? That's how people are used to calling this concept, "assert", anyway.

I think the self-explanatory name `on_internal_error_if_not()` is just too ugly and too long. 

> Another more outlandish option is to call the new function... SCYLLA_ASSERT()! We'll finally have a good SCYLLA_ASSERT() instead of the dangerous one we have now. Does this seem like a good idea to you? I'm a bit worried that if someone used SCYLLA_ASSERT() inside a noexcept code, perhaps the result won't be pretty if we throw an exception and crash because of the noexcept context. But will it be less pretty than SCYLLA_ASSERT() that also crashes? I'm not sure.

I guess this "more outlandish option" (https://github.com/scylladb/scylladb/pull/28480) was rejected. So I'm back to the more gradual change.

**Comment by nyh** [comment]
> I think the self-explanatory name `on_internal_error_if_not()` is just too ugly and too long.

How about `oie_assert()`? It's ugly too (an acronym...) but at least shorter...
Anybody has a better idea?

**Comment by ScyllaPiotr** [comment]
What I would welcome is sth like this:
1. Rename the impl (the definition) of `SCYLLA_ASSERT(x)` to `SCYLLA_ASSERT_IMPL(x, mode)`
2. Add to `SCYLLA_ASSERT_IMPL(x, mode)` the code to act conditionally, based on `mode`
3. `#define SCYLLA_ASSERT(x) SCYLLA_ASSERT_IMPL(x, ALLOW_ABORT)`
4. `#define SCYLLA_ASSERT(x, mode) SCYLLA_ASSERT_IMPL(x, mode)`
5. Make Alternator use `SCYLLA_ASSERT(x, FORBID_ABORT)`

This will enable gradual shift, in Alternator and elsewhere.

**Comment by nyh** [comment]
Pushed a new version renaming the new macro oie_assert() - on-internal-error based assert - to make it more evident that it 1. uses on_internal_error on failure, 2. it behaves like assert() and not perhaps the negation of assert as Avi suggested is one of the comments.

Also moved the declarations around so code that already include "utils/assert.hh" to use SCYLLA_ASSERT don't need to include anything else (the previous version of this patch required adding "utils/on_internal_error.hh", it no longer does).

**Comment by nyh** [comment]
> What I would welcome is sth like this:
> 
>     1. Rename the impl (the definition) of `SCYLLA_ASSERT(x)` to `SCYLLA_ASSERT_IMPL(x, mode)`
> 
>     2. Add to `SCYLLA_ASSERT_IMPL(x, mode)` the code to act conditionally, based on `mode`
> 
>     3. `#define SCYLLA_ASSERT(x) SCYLLA_ASSERT_IMPL(x, ALLOW_ABORT)`
> 
>     4. `#define SCYLLA_ASSERT(x, mode) SCYLLA_ASSERT_IMPL(x, mode)`

It's not possible to define two SCYLLA_ASSERT macros that differ only in their numbers of parameters.
It's possible to do something similar using variadic macros but it's quite difficult (but copilot will know how to do it ;-)).

>     5. Make Alternator use `SCYLLA_ASSERT(x, FORBID_ABORT)`

While this works, I think this is just too long and too ugly, and has no benefit over just choosing a new name - perhaps SCYLLA_ASSERT_FORBID_ABORT or like I called it now oie_assert().
I don't see any benefit for the two versions of the assert being "variants" of each other.

> This will enable gradual shift, in Alternator and elsewhere.

I don't have big hopes for this gradual shift seeing there are almost 900 (!) of SCYLLA_ASSERT calls in our source code and they are being added faster than I remove them, but since my immediate shift (https://github.com/scylladb/scylladb/pull/28480) got rejected, I don't have much choice.

**Comment by avikivity** [comment]
oie?

**Comment by ScyllaPiotr** [comment]
I actually like `SCYLLA_ASSERT_NO_ABORT` (the earlier `FORBID` was chosen only for compatibility with `ALLOW`).
I don't know what `ioe` means - so for me it's not immediately obvious, and the editor will never hint you with this, while if you start typing `SCYLLA_ASSERT` you'd get hinted, with either of the versions: `SCYLLA_ASSERT_NO_ABORT(x)` and `SCYLLA_ASSERT(x, mode)`.

**Comment by nyh** [comment]
> oie?

It was you who said you didn't like my previous suggestion ("REQUIRE") because it's not explicit enough to the user what happens if the assertion fails. The only way to be explicit is to use "on_internal_error" in the function's name. Since `on_internal_error_assert()` is ridiculously long, I wanted to abbreviate it to `ioe_assert()`. I'm not saying it is perfect, but I didn't yet hear a better suggestion. The name SCYLLA_ASSERT is already taken, unfortunately.

**Comment by avikivity** [comment]
I'll dislike "oie" even more. Why be so hostile to readers of the code?

**Comment by nyh** [comment]
> I actually like `SCYLLA_ASSERT_NO_ABORT`

I guess it's a possibility, but I'm not thrilled because "no abort" says what it doesn't do, not what it does do, and adding a suffix to SCYLLA_ASSERT makes it sound like it's the less important variant of SCYLLA_ASSERT, while it isn't.

> (the earlier `FORBID` was chosen only for compatibility with `ALLOW`). I don't know what `ioe` means - so for me it's not immediately obvious,

Was it ever obvious to you why we use "SCYLLA_ASSERT" instead of just "assert"? Probably not. It's just a convention.

> and the editor will never hint you with this, while if you start typing `SCYLLA_ASSERT` you'd get hinted, with either of the versions: `SCYLLA_ASSERT_NO_ABORT(x)` and `SCYLLA_ASSERT(x, mode)`.

Why would anyone start to type "SCYLLA_ASSERT"?
If anything, this suggests maybe I should call this function assert_oie (or similar), so when someone starts to type "assert" you get assert_oie recommended.

To be honest, I don't want anyone to start typing SCYLLA_ASSERT and then maybe, or maybe not, pick the NO_ABORT one. I really don't want anyone to continue using SCYLLA_ASSERT at all. Despite of all the FUD raised about maybe some places in the code really need SCYLLA_ASSERT to abort, I couldn't find even **a single place** where aborting is important (can you find one?). That is while I can give you a long list of examples where aborting on SCYLLA_ASSERT is terrible and lead in the past, and can lead in the future, to user frustration.

**Comment by nyh** [comment]
> I'll dislike "oie" even more. Why be so hostile to readers of the code?

Absolute newbies to Scylla will see "oie_assert" will immediately know it is a kind of assert, which presumably behaves similar to assert() - without knowing what the "oie" means. Just like when they see today SCYLLA_ASSERT these newbies have no idea how a "SCYLLA" assert differs from the normal one - they just guess it's similar to assert() with some unknown improvements. In this sense, the words "oie", "SCYLLA" and "dog" are all just as good (or just as bad).

Old-time Scylla developers know what "on_internal_error" is, so once they are told once that "oie" refers to it, will know exactly what it means every time they see it.

But if you really really hate `oie_assert()`, and I personally think `on_internal_error_assert()` is too long, another option maybe we can consider is this:
... drum roll...

**`throwing_assert()`**

Basically it's a type of assert which, well, throws. Or at least can throw (instead of abort), if the parameters are configured appropriately. Unlike "oie" this doesn't give you the whole story - "throwing" doesn't tell you the assertion message is logged to the log instead of stderr, or that a backtrace is logged as well, or which kind of exception is throw. But it's at least a good indication of the most important feature of this variant of assert.

**Comment by nyh** [comment]
By the way, I had a chat about this with copilot and it suggested the name `throw_if_false`. It suggested not to use the word "assert" in the name, because "many teams avoid calling that “assert” to prevent semantic confusion (asserts are often assumed “can be compiled out” and “not recoverable”).". Which is a good point, but on the other hand seeing that we have almost 900 (!) calls to SCYLLA_ASSERT in our code, it doesn't seem that anyone is really bothered by this "semantic confusion", and they **want** to call something called assert, not really giving too much though of how its behavior differs between release and test builds.

When I grilled copilot a bit more, it told me that: _"in most mainstream C++ libraries, the default “assertion” idiom is intentionally non-recoverable (terminate/abort or “fail fast”), and exception-throwing is treated as a different category: precondition checking / validation / enforcement."_ and then suggested that if I really want throwing "precondition checking / validation /enformenet", I can use the names `require()`, `ensure()` or `expect()`. I actually suggested `REQUIRE()` earlier but Avi didn't like it. It also suggested names `check()`, `check_or_throw()`, `verify()`, `verify_or_throw()`, `enforce()`, `enforce_if_throw()`, or just `throw_if_not()` or `throw_unless()`. Other names it suggested: `assert_or_throw()`, `validate_or_throw()`, `precondition()`/`postcondition()`/`invariant()` (I guess @regevran will like that?)

File: utils/on_internal_error.hh (hunk 3 above)
Comment (nyh) [reply utils/on_internal_error.hh]: Got rid of most of the attributes in the new version.

File: utils/assert.hh [hunk 5]
```diff
@@ -7,3 +7,34 @@
...
+///    log a backtrace.
+/// Notes:
+/// * when throwing_assert() is used in a noexcept context, the exception
+///   thrown by utils::on_internal_error() will still cause std::terminate()
+///   to be called - so it behaves like SCYLLA_ASSERT() but with better
+///   logging but also an uglier backtrace in the debugger.
+/// * The type of exception thrown by throwing_assert() is determined by
+///   seastar::on_internal_error. It is currently std::runtime_error, but this
+///   is not guaranteed and should not be relied on.
+#define throwing_assert(x) do { if (!(x)) { ::utils::__assert_fail_on_internal_error(#x, __FILE__, __LINE__, __PRETTY_FUNCTION__); } } while (0)
```
[the remark this answers is not in the document]
Comment (nyh) [reply utils/assert.hh:34]: I already renamed the PR title and modified the description, I guess I did it after copilot started the review?

File: utils/assert.hh [hunk 6]
```diff
@@ -7,3 +7,34 @@
...
+
+/// Used by the throwing_assert() macro to report assertion failures using
+/// utils::on_internal_error().
+namespace utils {
+[[noreturn]] void __assert_fail_on_internal_error(const char* expr, const char* file, int line, const char* function);
+}
```
[the remark this answers is not in the document]
Comment (nyh) [reply utils/assert.hh:40]: I thought about it... I really wanted this function name to be an exact parallel of the standard __assert_fail used by SCYLLA_ASSERT, which is why I chose this name. I really think this is a non-issue. If this name ever bothers us, we can always change it, it's not exposed to users, it's just used internally by the implementation of `throwing_assert()`.

**Comment by nyh** [comment]
> #### Failed Tests (1/105339):
> 
>     * [test_multi_column_lwt_during_split_merge.dev.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/25721/testReport/junit/cluster.lwt/test_lwt_during_tablets_resize/dev___test_py___dev___test_multi_column_lwt_during_split_merge_dev_1) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_multi_column_lwt_during_split_merge.dev.1)

This is just lovely. Not only do I need to worry now while developing my own code about fixing **other people's bugs** or my own code won't get in, now I also need to do it through two different bug-tracking systems to report this bug, with the "newer" system having its search engine's quality one notch below Altavista. Good times here in ScyllaDB.
