### PR TITLE
cql: Add proper validation for null and unset inside collections send as bound values

### LINKED ISSUE #10580: cql: Add proper validation for nulls inside collections send as bound values
Let's say we have a query like:
```cql
INSERT INTO ks.t (list_column) VALUES (?);
```
And the driver sends a list with null inside as the bound value, something like `[1, 2, null, 4]`.

In such case we should throw `invalid_request_exception` because `nulls` are not allowed inside collections.

Currently when a query like this gets executed Scylla throws an ugly error like this:
```
Error: DbError(Invalid, "Exception while binding value of type org.apache.cassandra.db.marshal.ListType(org.apache.cassandra.db.marshal.Int32Type): marshaling error: read_simple_bytes - not enough bytes (requested 18446744073709551615, got 8) Backtrace: 0x4161c3e 0x4162130 0x4162438 0x119407c 0x1193d14 0x2049411 0x2046c76 0x1c69189 0x1ca6d01 0x1c68d48 0x1c3a241 0x1dc5b92 0x1dc63ca 0x1d9c3a6 0x1d990e5 0x1da1c51 0x1d9e96e 0x1dac377 0x1dac3bc 0x1da96d4 0x3d86635 0x3dd0cc4 0x3dd20b7 0x3dd12fc 0x3d7aaae 0x3d79e26 0xf41135 /opt/scylladb/libreloc/libc.so.6+0x27b74 0xf3e2ed\n   --------\n   seastar::lambda_task<seastar::execution_stage::flush()::$_5>")
```

This is because [validation code](https://github.com/scylladb/scylla/blob/a2b9a17927d851b368d3ef8e869a295c8bd2e86b/types.cc#L1423) reads size of the next element, interprets it as an unsigned integer and tries to read this much.
In case of `null` element the size is `-1`, which when converted to unsigned `size_t` gives 18446744073709551615 and it fails to read this much.

To fix this null checks could be added to `validate_aux`.

There might be some exception for lists of IN values, but support for nulls there might get removed (see #10579)

### PR DESCRIPTION
**Pull request by cvybhu**
Let's say we have a query like:
```cql
INSERT INTO ks.t (list_column) VALUES (?);
```
And the driver sends a list with null inside as the bound value, something like `[1, 2, null, 4]`.

In such case we should throw `invalid_request_exception` because `nulls` are not allowed inside collections.

Currently when a query like this gets executed Scylla throws an ugly marshalling error.
This is because the validation code reads size of the next element, interprets it as an unsigned integer and tries to read this much.
In case of `null` element the size is `-1`, which when converted to unsigned `size_t` gives 18446744073709551615 and it fails to read this much.

This PR adds proper validation checks to make the error message better.

I also added some tests.
I originally tried to write them in python, but python driver really doesn't like sending invalid values.
Trying to send `[1, None, 2]` results in a list with empty value instead of null.
Trying to send `[1, UNSET_VALUE, 2]` Fails before query even leaves the driver.

Fixes #10580

### CODE REVIEW

File: types/listlike_partial_deserializing_iterator.hh [hunk 1]
```diff
@@ -29,6 +29,12 @@ int read_collection_size(View& in, cql_serialization_format sf) {
 template <FragmentedView View>
 View read_collection_value(View& in, cql_serialization_format sf) {
     auto size = sf.using_32_bits_for_collections() ? read_simple<int32_t>(in) : read_simple<uint16_t>(in);
+    if (size == -2) {
+        throw exceptions::invalid_request_exception("unset value is not supported inside collections");
+    }
+    if (size < 0) {
```
Comment (psarna) [inline types/listlike_partial_deserializing_iterator.hh:35]: ditto, `== -1` sounds more correct

File: types.cc [hunk 2]
```diff
@@ -734,6 +734,14 @@ void write_collection_value(managed_bytes_mutable_view& out, cql_serialization_f
     write_fragmented(out, val);
 }
 
+void write_int32(bytes::iterator& out, int32_t value) {
+    return serialize_int32(out, value);
```
Comment (psarna) [inline types.cc:738]: why not use serialize_int32() directly in your code? That would make this commit less intrusive, easier to backport, and so on. Especially that the new function is only useful for tests

**Comment by avikivity** [comment]
Looks good.

File: types.cc [hunk 3]
```diff
@@ -624,7 +624,13 @@ void write_collection_size(bytes::iterator& out, int size, cql_serialization_for
 }
 
 bytes_view read_collection_value(bytes_view& in, cql_serialization_format sf) {
-    auto size = sf.using_32_bits_for_collections() ? read_simple<int32_t>(in) : read_simple<uint16_t>(in);
+    int32_t size = sf.using_32_bits_for_collections() ? read_simple<int32_t>(in) : read_simple<uint16_t>(in);
```
Comment (nyh) [inline types.cc:627]: For the v2 protocol (!using_32_bits_for_collections()) I think the sign extension of the uint16_t case is wrong. I think size=65535 meant a null, but your size < 0 check below will not catch it.

File: cql3/values.cc [hunk 4]
```diff
@@ -58,4 +58,42 @@ raw_value_view::raw_value_view(managed_bytes&& tmp) {
     _data = managed_bytes_view(*_temporary_storage);
 }
 
+raw_value make_collection_raw_value(size_t size_to_write, const std::vector<raw_value>& elements_to_write, cql_serialization_format sf) {
```
[the remark this answers is not in the document]
Comment (nyh) [reply cql3/values.cc:61]: An even better option is to move this function to the test source file. It doesn't need to be a general utility function, and putting it in values.cc won't mean it is magically maintained by anyone.

Personally, I wouldn't have done this in C++ at all, and do it in cql-pytest (but I didn't check - it is possible that the Python driver "protects" you from sending garbage, so it's not possible).

File: test/boost/cql_query_test.cc [hunk 5]
```diff
@@ -5063,3 +5063,188 @@ SEASTAR_TEST_CASE(test_parallelized_select_count) {
...
+        BOOST_REQUIRE_EXCEPTION(e.execute_prepared(add_list_with_marker, {unset_value}).get(),
+                                exceptions::invalid_request_exception, check_unset_msg());
+        BOOST_REQUIRE_EXCEPTION(e.execute_prepared(add_set_with_marker, {unset_value}).get(),
+                                exceptions::invalid_request_exception, check_unset_msg());
+        BOOST_REQUIRE_EXCEPTION(e.execute_prepared(add_map_with_key_marker, {unset_value}).get(),
+                                exceptions::invalid_request_exception, check_unset_msg());
+        BOOST_REQUIRE_EXCEPTION(e.execute_prepared(add_map_with_value_marker, {unset_value}).get(),
+                                exceptions::invalid_request_exception, check_unset_msg());
+
+        // Udate adding a collection value with bad bind marker
```
Comment (nyh) [inline test/boost/cql_query_test.cc:5227]: Update

**Review by nyh — CHANGES_REQUESTED** [review]

File: types.cc [hunk 6]
```diff
@@ -624,7 +624,13 @@ void write_collection_size(bytes::iterator& out, int size, cql_serialization_for
...
+    if (size == -2) {
+        throw exceptions::invalid_request_exception("unset value is not supported inside collections");
+    }
+    if (size < 0) {
```
[the remark this answers is not in the document]
Comment (cvybhu) [reply types.cc:631]:
```
[bytes]        A [int] n, followed by n bytes if n >= 0. If n < 0,
               no byte should follow and the value represented is `null`.

[value]        A [int] n, followed by n bytes if n >= 0.
               If n == -1 no byte should follow and the value represented is `null`.
               If n == -2 no byte should follow and the value represented is
               `not set` not resulting in any change to the existing value.
               n < -2 is an invalid value and results in an 

6.11 list
  A [int] n indicating the number of elements in the list, followed by n
  elements.  Each element is [bytes] representing the serialized value.
```

Technically a list consists of many [bytes], so everything < 0 is a null no matter whether it is -1, -2 or -1000.
I could check only for nulls but the user could make a mistake where they send send unset value and it would be confusing for them to receive message about a null, so I think it's good to also recognize this case even if it isn't technically correct.

File: cql3/values.cc (hunk 4 above)
[the remark this answers is not in the document]
Comment (cvybhu) [reply cql3/values.cc:61]: I originally put in the test source, but it's very generic so I thought that maybe it's better to put it somewhere global so that it can be used in other places in the future.
I don't have any strong opinion either way, I will move it to the test file.

[the remark this answers is not in the document]
Comment (cvybhu) [reply cql3/values.cc:61]: > Personally, I wouldn't have done this in C++ at all, and do it in cql-pytest (but I didn't check - it is possible that the Python driver "protects" you from sending garbage, so it's not possible).

It prevents me from sending invalid values
Trying to send `[1, None, 2]` results in a list with empty value instead of null.
Trying to send `[1, UNSET_VALUE, 2]` Fails before query even leaves the driver.

This test looks good when written using the rust driver. It allows to create collections easily just like python, but doesn't have any protections and obediently serializes whatever it's given. Alas we can't write tests using rust yet.

**Comment by cvybhu** [comment]
v2:
- Moved `make_collection_raw_value` to the test file
- Fixed `Udate` type

File: types.cc (hunk 6 above)
[the remark this answers is not in the document]
Comment (psarna) [reply types.cc:631]: ok, makes sense, thanks for clarification

File: types.cc (hunk 2 above)
Comment (psarna) [reply types.cc:738]: got it, thx

**Comment by cvybhu** [comment]
v3:
- simplified `make_collection_raw_value` to work only with the latest cql serialization format. It was wrong for the old one, and it's now hidden in the test file so no one will ever use it anywhere else anyway.

File: types.cc (hunk 3 above)
Comment (nyh) [reply types.cc:627]: This text looks like it contains a blatant contradiction. The `[short bytes]` explicitly has the text "if n >= 0", which means there is a possibility that `n < 0` - but this contradicts the definition of `[short]` being an _unsigned_ integer.

So I can only guess (I didn't check) that their actual code was different. Perhaps it was a signed int (but that would limit the value size to 32KB, people would have noticed that), or maybe it was an unsigned int and explicitly compared to 65535 (-1) and not n < 0?

**Review by nyh — APPROVED** [review]
Looks good, thanks, I'll commit.
I still think the cql v2 code is wrong (or at least, wasn't convinced it is correct), but since this is pre-existing code there is no reason to withhold this patch just because I noticed it now. We can fix it later, or not at all - because cql v2 is many years obsolete (as you noted, even its documentation is long gone) and nobody will ever use it. Maybe we should consider officially dropping support for it.
