### PR TITLE
Fix object storage lister entries walking loop

### LINKED ISSUE #29058: Object storage lister bug in internal loop over entries
The code in sstables/object_storage_client.cc:

```c++
                do {
                    if (_pos == _info.size()) {
                        _info.clear();
                        _info = co_await _client->list_objects(_bucket, _prefix, _paging);
                    }
                    if (_info.empty()) {
                        break;
                    }
                    auto& item = _info[_pos++];
                    directory_entry ent{item.name.substr(_prefix.size())};
                    if (_filter && !_filter(dir, ent)) {
                        continue;
                    }
                    co_return ent;
                } while (false);
```

if filter is set and asks to skip a entry the `continue` makes while(false) to stop early

### PR DESCRIPTION
**Pull request by xemul**
Two issues found in the lister returned by gs_client_wrapper::make_object_lister()
Lister can report EOF too early in case filter is active, another one is potential vector out-of-bounds access

Fixes #29058

The code appeared in 2026.1, worth fixing it there as well

### CODE REVIEW

File: sstables/object_storage_client.cc [hunk 1]
```diff
@@ -189,7 +189,7 @@ class gs_client_wrapper : public sstables::object_storage_client {
             {}
             future<std::optional<directory_entry>> get() override {
                 std::filesystem::path dir(_prefix);
-                do {
+                while (true) {
                     if (_pos == _info.size()) {
                         _info.clear();
                         _info = co_await _client->list_objects(_bucket, _prefix, _paging);
```
Comment (elcallio) [inline sstables/object_storage_client.cc:195]: Uhm, while one can argue the shape of the loop, the real error here is that somehow the `_pos = 0` fell away somewhere in this code. 
Resetting the _pos member after reading _info will fix the problem.

**Review by elcallio — CHANGES_REQUESTED** [review]

File: sstables/object_storage_client.cc (hunk 1 above)
Comment (xemul) [reply sstables/object_storage_client.cc:195]: Isn't it _another_ problem? I mean -- even if _pos is reset to 0, the fvery first filter-out breaks the loop, return std::nullopt and the caller reads it as EOF and stops iterating

Comment (elcallio) [reply sstables/object_storage_client.cc:195]: True. It should be a while(true) / for(;;)

**Review by elcallio — APPROVED** [review]

**Comment by xemul** [comment]
https://scylladb.atlassian.net/browse/SCYLLADB-1082 ~~again~~ still

**Review by denesb — APPROVED** [review]
