### PR TITLE
Fix command line parsing and add logging.

### LINKED ISSUE #4203: Log the command line args scylla is passed at boot
We are seeing cases in which its not clear why Scylla fails to boot - and it seems its related to arguments that are passed in the command line. 

To solve this lets simply print the args so we can easily analyze such issues.

### PR DESCRIPTION
**Pull request by kbr-**
Fixes #4203 and #4141.

### CODE REVIEW

**Comment by kbr-** [comment]
@haaawk @avikivity could you please review?

**Comment by nyh** [comment]
Before I review the actual code, two general comments on process:
1. If these two patches are unrelated (each solves a different issue), they don't need to be in one pull request, you can have two separate pull requests, which will make it clearer they are not related, and make it easier to accept one but delay the other, for example.
2. The magic phrase "Fixes #bugnumber" will cause the patch, once committed, to automatically close the issue. There are other words you can use instead of "Fixes" - see https://help.github.com/en/articles/closing-issues-using-keywords - but unfortunately the word "Solves" (which you used in one of the patches) is not one of them. So you should change it to one of the other words, otherwise you'll need to remember to close the issue manually when the patch is committed.

File: main.cc [hunk 1]
```diff
@@ -357,12 +357,39 @@ int main(int ac, char** av) {
...
     bpo::variables_map vm;
-    bpo::store(bpo::command_line_parser(ac, av).options(app.get_options_description()).allow_unregistered().run(), vm);
+    auto parsed_opts = bpo::command_line_parser(ac, av).options(app.get_options_description()).allow_unregistered().run();
+    bpo::store(parsed_opts, vm);
     if (vm["version"].as<bool>()) {
         fmt::print("{}\n", scylla_version());
         return 0;
     }
 
+    if (ac) {
```
Comment (nyh) [inline main.cc]: How can argc possibly be zero? It's always >= 1, and argv[0] is the program's name.

File: main.cc [hunk 2]
```diff
@@ -357,12 +357,39 @@ int main(int ac, char** av) {
...
+        fmt::print("Scylla executed using: \"{}", av[0]);
+        for (int i = 1; i < ac; ++i) {
+            fmt::print(" {}", av[i]);
+        }
+        fmt::print("\"\n");
+    }
+
+    fmt::print("Parsed command line options:\n");
```
Comment (nyh) [inline main.cc]: I wonder if this parsed view is helpful (does it say anything the user can't just see in the original command line you printed above?), but I guess it can't hurt.

Comment (haaawk) [reply main.cc]: It's useful in a sense that it could help catch problems like the one in #4141 when some arguments are not parsed as expected.

File: main.cc [hunk 3]
```diff
@@ -357,12 +357,39 @@ int main(int ac, char** av) {
...
+    for (auto const& opt: parsed_opts.options) {
+        if (opt.value.empty()) {
```
Comment (avikivity) [inline main.cc]: Please follow the coding style: west const, spaces around `:`

File: main.cc [hunk 4]
```diff
@@ -357,12 +357,39 @@ int main(int ac, char** av) {
...
+            } else {
+                fmt::print("{}:", opt.string_key);
+            }
+
+            for (auto const& val: opt.value) {
+                fmt::print(" {}", val);
+            }
+        }
+        fmt::print("\n");
+    }
```
Comment (avikivity) [inline main.cc]: That's very verbose, better to append all the parameters to the initial log message ("Scylla version {} starting"). You can use the argc/argv, no need to mess with the parsed options.

File: main.cc (hunk 1 above)
Comment (kbr-) [reply main.cc]: It could be zero theoretically, in which case argv[0] is the NULL pointer. The standard only says that if argc > 0, then argv[0] is some string representing the program.
https://en.cppreference.com/w/cpp/language/main_function
https://stackoverflow.com/a/49817618

**Comment by kbr-** [comment]
Thanks @nyh for the comments.
1. Those two patches are related I think: the first commit proposed is the result of me implementing cmdline logging (proposed in the second commit) and observing strange behavior. But next time I'm gonna do separate pull requests in such cases --- I don't think it does any harm.
2. I'm gonna remember that :)

File: main.cc (hunk 4 above)
Comment (kbr-) [reply main.cc]: I wanted to log how exactly the options were parsed --- if I understand correctly, that was the point of issue #4203. Indeed, issue #4203 references issue #4141, in which a user provides the command used to run Scylla, but that information doesn't entirely help with debugging the problem; the issue arises from incorrect parsing of the command's arguments. So I think it's useful to know this.
However I agree that it's verbose. I will change it so that the parsed arguments are printed in a readable format in a single line.

File: main.cc (hunk 2 above)
Comment (kbr-) [reply main.cc]: As @haaawk said. See also conversation with Avi below.

File: main.cc (hunk 4 above)
Comment (kbr-) [reply main.cc]: Done.

File: main.cc (hunk 3 above)
Comment (kbr-) [reply main.cc]: Done.

File: main.cc [hunk 5]
```diff
@@ -420,12 +420,33 @@ int main(int ac, char** av) {
...
+        fmt::print("command used: \"{}", av[0]);
+        for (int i = 1; i < ac; ++i) {
+            fmt::print(" {}", av[i]);
+        }
+        fmt::print("\"\n");
+    }
+
+    fmt::print("Parsed command line options: [{}]\n",
+        boost::algorithm::join(parsed_opts.options | boost::adaptors::transformed([] (const auto& opt) {
+            if (opt.value.empty()) {
```
Comment (avikivity) [inline main.cc]: Please avoid using generic lambdas when not needed, generic lambdas makes the types not accessible to IDEs and make error messages worse.

File: main.cc [hunk 6]
```diff
@@ -420,12 +420,33 @@ int main(int ac, char** av) {
...
+                return opt.string_key;
+            }
+
+            return (opt.string_key.empty() ?  "(positional) " : fmt::format("{}: ", opt.string_key)) +
+                        boost::algorithm::join(opt.value, " ");
+        }), ", ")
+    );
+
```
Comment (avikivity) [inline main.cc]: Please extract the whole thing into some function.

File: main.cc (hunk 5 above)
Comment (kbr-) [reply main.cc]: Done.

File: main.cc (hunk 6 above)
Comment (kbr-) [reply main.cc]: Done.

Comment (kbr-) [reply main.cc]: I looked at the diff again and it seems that you meant everything from the "starting..." message to the parsed options. I misunderstood previously. Fixed now.

**Comment by kbr-** [comment]
@nyh @avikivity is there anything else? Or is it ready to be merged?

**Comment by slivne** [comment]
@nyh - since you approved the pull requets can you please merge

File: main.cc (hunk 6 above)
Comment (avikivity) [reply main.cc]: Actually I meant just the option formatting, but what you did is good too.

**Comment by avikivity** [comment]
queued
