### PR TITLE
qos: make sure to wait for service level updates on shutdown

### LINKED ISSUE #8468: service level controller is used after stop
Seen e.g. in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/767/artifact/logs-all.debug.2/1618273635169_sstableloader_test.TestMigration_with_2_2_x.migrate_sstable_with_wrong_partitioner_test/node1.log
```
INFO  2021-04-13 00:27:11,188 [shard 0] init - Shutting down service level controller
INFO  2021-04-13 00:27:11,189 [shard 0] init - Shutting down service level controller was successful
...
INFO  2021-04-13 00:27:11,386 [shard 0] init - Shutting down messaging service
=================================================================
==95521==ERROR: AddressSanitizer: heap-use-after-free on address 0x61100000db38 at pc 0x000013c2e723 bp 0x7fdeaebbd7a0 sp 0x7fdeaebbd798
READ of size 8 at 0x61100000db38 thread T0
    #0 0x13c2e722  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x13c2e722)
    #1 0x17fbf6cd  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x17fbf6cd)
    #2 0x17fbf014  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x17fbf014)
    #3 0x17fa7509  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x17fa7509)
    #4 0x17fa7258  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x17fa7258)
    #5 0x17fa7238  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x17fa7238)
    #6 0x17fa7218  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x17fa7218)
    #7 0x17fa71ec  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x17fa71ec)
    #8 0x17fa7170  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x17fa7170)
    #9 0x17fa704e  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x17fa704e)
    #10 0x17fa6f12  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x17fa6f12)
    #11 0x13fe2caa  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x13fe2caa)
    #12 0x1a265e16  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x1a265e16)

std::_Hashtable<seastar::basic_sstring<char, unsigned int, 15u, true>, std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, qos::service_level>, std::allocator<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, qos::service_level> >, std::__detail::_Select1st, std::equal_to<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::hash<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_begin() const at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/hashtable.h:421
std::_Hashtable<seastar::basic_sstring<char, unsigned int, 15u, true>, std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, qos::service_level>, std::allocator<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, qos::service_level> >, std::__detail::_Select1st, std::equal_to<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::hash<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::begin() at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/hashtable.h:543
std::unordered_map<seastar::basic_sstring<char, unsigned int, 15u, true>, qos::service_level, std::hash<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::equal_to<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::allocator<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, qos::service_level> > >::begin() at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/unordered_map.h:325
operator() at ./service/qos/service_level_controller.cc:113
void std::__invoke_impl<void, qos::service_level_controller::update_service_levels_from_distributed_data()::$_3::operator()(qos::service_level_controller&) const::{lambda()#1}::operator()() const::{lambda()#1}>(std::__invoke_other, qos::service_level_controller::update_service_levels_from_distributed_data()::$_3::operator()(qos::service_level_controller&) const::{lambda()#1}::operator()() const::{lambda()#1}&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
std::__invoke_result<qos::service_level_controller::update_service_levels_from_distributed_data()::$_3::operator()(qos::service_level_controller&) const::{lambda()#1}::operator()() const::{lambda()#1}>::type std::__invoke<qos::service_level_controller::update_service_levels_from_distributed_data()::$_3::operator()(qos::service_level_controller&) const::{lambda()#1}::operator()() const::{lambda()#1}>(qos::service_level_controller::update_service_levels_from_distributed_data()::$_3::operator()(qos::service_level_controller&) const::{lambda()#1}::operator()() const::{lambda()#1}&&, (std::__invoke_result&&)...) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:95
decltype(auto) std::__apply_impl<qos::service_level_controller::update_service_levels_from_distributed_data()::$_3::operator()(qos::service_level_controller&) const::{lambda()#1}::operator()() const::{lambda()#1}, std::tuple<>>(qos::service_level_controller::update_service_levels_from_distributed_data()::$_3::operator()(qos::service_level_controller&) const::{lambda()#1}::operator()() const::{lambda()#1}&&, std::tuple<>&&, std::integer_sequence<unsigned long>) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/tuple:1723
decltype(auto) std::apply<qos::service_level_controller::update_service_levels_from_distributed_data()::$_3::operator()(qos::service_level_controller&) const::{lambda()#1}::operator()() const::{lambda()#1}, std::tuple<> >(qos::service_level_controller::update_service_levels_from_distributed_data()::$_3::operator()(qos::service_level_controller&) const::{lambda()#1}::operator()() const::{lambda()#1}&&, std::tuple<>&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/tuple:1734
seastar::future<void> seastar::futurize<void>::apply<qos::service_level_controller::update_service_levels_from_distributed_data()::$_3::operator()(qos::service_level_controller&) const::{lambda()#1}::operator()() const::{lambda()#1}>(qos::service_level_controller::update_service_levels_from_distributed_data()::$_3::operator()(qos::service_level_controller&) const::{lambda()#1}::operator()() const::{lambda()#1}&&, std::tuple<>&&) at ././seastar/include/seastar/core/future.hh:2099
operator() at ././seastar/include/seastar/core/thread.hh:258
seastar::noncopyable_function<void ()>::direct_vtable_for<seastar::async<qos::service_level_controller::update_service_levels_from_distributed_data()::$_3::operator()(qos::service_level_controller&) const::{lambda()#1}::operator()() const::{lambda()#1}>(seastar::thread_attributes, std::result_of&&, (std::decay<qos::service_level_controller::update_service_levels_from_distributed_data()::$_3::operator()(qos::service_level_controller&) const::{lambda()#1}::operator()() const::{lambda()#1}>&&)...)::{lambda()#1}>::call(seastar::noncopyable_function<void ()> const*) at ././seastar/include/seastar/util/noncopyable_function.hh:124
seastar::noncopyable_function<void ()>::operator()() const at ././seastar/include/seastar/util/noncopyable_function.hh:209
seastar::thread_context::main() at ./build/debug/seastar/./seastar/src/core/thread.cc:299

0x61100000db38 is located 56 bytes inside of 200-byte region [0x61100000db00,0x61100000dbc8)
freed by thread T0 here:
    #0 0x139f65b7  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x139f65b7)
    #1 0x13c2e132  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x13c2e132)
    #2 0x13c39439  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x13c39439)
    #3 0x13c385a4  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x13c385a4)
    #4 0x13c38416  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x13c38416)
    #5 0x13c382d3  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x13c382d3)
    #6 0x1a19c0aa  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x1a19c0aa)
    #7 0x1a19bf52  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x1a19bf52)
    #8 0x1a19b7cb  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x1a19b7cb)
    #9 0x1a19b064  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x1a19b064)
    #10 0x1a19c6cd  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x1a19c6cd)
    #11 0x1a19b2a5  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x1a19b2a5)
    #12 0x1a19ac66  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x1a19ac66)
    #13 0x1a19a7c2  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x1a19a7c2)
    #14 0x13c2a33f  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x13c2a33f)
    #15 0x13c37a36  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x13c37a36)
    #16 0x13c3787e  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x13c3787e)
    #17 0x13c37732  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x13c37732)
    #18 0x13b622f2  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x13b622f2)
    #19 0x13b6211a  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x13b6211a)
    #20 0x13b61d7d  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x13b61d7d)
    #21 0x19d1d7e6  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x19d1d7e6)
    #22 0x19d2241b  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x19d2241b)
    #23 0x19a5f34a  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x19a5f34a)
    #24 0x19a5d45c  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x19a5d45c)
    #25 0x139fa47f  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x139fa47f)
    #26 0x7fdfbf6e91e1  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libreloc/libc.so.6+0x281e1)

operator delete(void*) at ??:?
~shared_ptr_count_for at ././seastar/include/seastar/core/shared_ptr.hh:464
operator() at ././seastar/include/seastar/core/sharded.hh:690
seastar::futurize<std::result_of<seastar::sharded<qos::service_level_controller>::stop()::{lambda(seastar::future<void>)#1}::operator()(seastar::future<void>) const::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1} ()>::type>::type seastar::smp::submit_to<seastar::sharded<qos::service_level_controller>::stop()::{lambda(seastar::future<void>)#1}::operator()(seastar::future<void>) const::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>(unsigned int, seastar::sharded<qos::service_level_controller>::stop()::{lambda(seastar::future<void>)#1}::operator()(seastar::future<void>) const::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&&) at ././seastar/include/seastar/core/smp.hh:366
operator() at ././seastar/include/seastar/core/sharded.hh:686
seastar::future<void> std::__invoke_impl<seastar::future<void>, seastar::sharded<qos::service_level_controller>::stop()::{lambda(seastar::future<void>)#1}::operator()(seastar::future<void>) const::{lambda(unsigned int)#1}&, unsigned int>(std::__invoke_other, seastar::sharded<qos::service_level_controller>::stop()::{lambda(seastar::future<void>)#1}::operator()(seastar::future<void>) const::{lambda(unsigned int)#1}&, unsigned int&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
seastar::future<void> seastar::futurize<seastar::future<void> >::invoke<std::function<seastar::future<void> (unsigned int)>, unsigned int>(std::function<seastar::future<void> (unsigned int)>&&, unsigned int&&) at ./build/debug/seastar/./seastar/include/seastar/core/future.hh:2135
auto seastar::futurize_invoke<std::function<seastar::future<void> (unsigned int)>, unsigned int>(std::function<seastar::future<void> (unsigned int)>&&, unsigned int&&) at ./build/debug/seastar/./seastar/include/seastar/core/future.hh:2166
seastar::future<void> seastar::parallel_for_each<boost::range_detail::integer_iterator<unsigned int>, std::function<seastar::future<void> (unsigned int)> >(boost::range_detail::integer_iterator<unsigned int>, boost::range_detail::integer_iterator<unsigned int>, std::function<seastar::future<void> (unsigned int)>&&) at ./build/debug/seastar/./seastar/include/seastar/core/loop.hh:554
seastar::future<void> seastar::internal::parallel_for_each_impl<boost::integer_range<unsigned int>, std::function<seastar::future<void> (unsigned int)> >(boost::integer_range<unsigned int>&&, std::function<seastar::future<void> (unsigned int)>&&) at ./build/debug/seastar/./seastar/include/seastar/core/loop.hh:598
seastar::future<void> seastar::futurize<seastar::future<void> >::invoke<seastar::future<void> (*&)(boost::integer_range<unsigned int>&&, std::function<seastar::future<void> (unsigned int)>&&), boost::integer_range<unsigned int>, std::function<seastar::future<void> (unsigned int)> >(seastar::future<void> (*&)(boost::integer_range<unsigned int>&&, std::function<seastar::future<void> (unsigned int)>&&), boost::integer_range<unsigned int>&&, std::function<seastar::future<void> (unsigned int)>&&) at ./build/debug/seastar/./seastar/include/seastar/core/future.hh:2135
auto seastar::futurize_invoke<seastar::future<void> (*&)(boost::integer_range<unsigned int>&&, std::function<seastar::future<void> (unsigned int)>&&), boost::integer_range<unsigned int>, std::function<seastar::future<void> (unsigned int)> >(seastar::future<void> (*&)(boost::integer_range<unsigned int>&&, std::function<seastar::future<void> (unsigned int)>&&), boost::integer_range<unsigned int>&&, std::function<seastar::future<void> (unsigned int)>&&) at ./build/debug/seastar/./seastar/include/seastar/core/future.hh:2166
seastar::future<void> seastar::parallel_for_each<boost::integer_range<unsigned int>, std::function<seastar::future<void> (unsigned int)> >(boost::integer_range<unsigned int>&&, std::function<seastar::future<void> (unsigned int)>&&) at ./build/debug/seastar/./seastar/include/seastar/core/loop.hh:610
seastar::internal::sharded_parallel_for_each(unsigned int, std::function<seastar::future<void> (unsigned int)>) at ./build/debug/seastar/./seastar/src/core/sharded.cc:33
seastar::sharded<qos::service_level_controller>::sharded_parallel_for_each(std::function<seastar::future<void> (unsigned int)>) at ././seastar/include/seastar/core/sharded.hh:160
operator() at ././seastar/include/seastar/core/sharded.hh:685
seastar::future<void> seastar::futurize<seastar::future<void> >::invoke<seastar::sharded<qos::service_level_controller>::stop()::{lambda(seastar::future<void>)#1}&, seastar::future<void> >(seastar::sharded<qos::service_level_controller>::stop()::{lambda(seastar::future<void>)#1}&, seastar::future<void>&&) at ././seastar/include/seastar/core/future.hh:2135
operator() at ././seastar/include/seastar/core/future.hh:1652
void seastar::futurize<seastar::future<void> >::satisfy_with_result_of<seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)> >(seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&, seastar::future_state<seastar::internal::monostate>&&)#1}::operator()(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&, seastar::future_state<seastar::internal::monostate>&&) const::{lambda()#1}>(seastar::internal::promise_base_with_type<void>&&, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)> >(seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&, seastar::future_state<seastar::internal::monostate>&&)#1}::operator()(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&, seastar::future_state<seastar::internal::monostate>&&) const::{lambda()#1}&&) at ././seastar/include/seastar/core/future.hh:2120
operator() at ././seastar/include/seastar/core/future.hh:1667
seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)> >(seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>::run_and_dispose() at ././seastar/include/seastar/core/future.hh:767
seastar::reactor::run_some_tasks() at ./build/debug/seastar/./seastar/src/core/reactor.cc:2672
seastar::reactor::run() at ./build/debug/seastar/./seastar/src/core/reactor.cc:2831
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at ./build/debug/seastar/./seastar/src/core/app-template.cc:207
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at ./build/debug/seastar/./seastar/src/core/app-template.cc:115
main at ./main.cc:495
?? ??:0

previously allocated by thread T0 here:
    #0 0x139f5be7  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x139f5be7)
    #1 0x13c2dde3  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x13c2dde3)
    #2 0x13c2d79a  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x13c2d79a)
    #3 0x13c2d63a  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x13c2d63a)
    #4 0x13c2cdb3  (/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/fcc17d43a6ba8113c8eecc2a630da89ec61c7246/scylla/libexec/scylla+0x13c2cdb3)

operator new(unsigned long) at ??:?
seastar::shared_ptr<qos::service_level_controller> seastar::shared_ptr_make_helper<qos::service_level_controller, false>::make<seastar::internal::either_sharded_or_local<auth::service>, qos::service_level_options&>(seastar::internal::either_sharded_or_local<auth::service>&&, qos::service_level_options&) at ././seastar/include/seastar/core/shared_ptr.hh:631
seastar::shared_ptr<qos::service_level_controller> std::__invoke_impl<seastar::shared_ptr<qos::service_level_controller>, seastar::sharded<qos::service_level_controller>::start<std::reference_wrapper<seastar::sharded<auth::service> >, qos::service_level_options&>(std::reference_wrapper<seastar::sharded<auth::service> >&&, qos::service_level_options&)::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}::operator()()::{lambda(std::reference_wrapper<seastar::sharded<auth::service> >, qos::service_level_options&)#1}, seastar::sharded<auth::service>&, qos::service_level_options&>(std::__invoke_other, seastar::sharded<qos::service_level_controller>::start<std::reference_wrapper<seastar::sharded<auth::service> >, qos::service_level_options&>(std::reference_wrapper<seastar::sharded<auth::service> >&&, qos::service_level_options&)::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}::operator()()::{lambda(std::reference_wrapper<seastar::sharded<auth::service> >, qos::service_level_options&)#1}&&, seastar::sharded<auth::service>&, qos::service_level_options&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
std::__invoke_result<seastar::sharded<qos::service_level_controller>::start<std::reference_wrapper<seastar::sharded<auth::service> >, qos::service_level_options&>(std::reference_wrapper<seastar::sharded<auth::service> >&&, qos::service_level_options&)::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}::operator()()::{lambda(std::reference_wrapper<seastar::sharded<auth::service> >, qos::service_level_options&)#1}, seastar::sharded<auth::service>&, qos::service_level_options&>::type std::__invoke<seastar::sharded<qos::service_level_controller>::start<std::reference_wrapper<seastar::sharded<auth::service> >, qos::service_level_options&>(std::reference_wrapper<seastar::sharded<auth::service> >&&, qos::service_level_options&)::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}::operator()()::{lambda(std::reference_wrapper<seastar::sharded<auth::service> >, qos::service_level_options&)#1}, seastar::sharded<auth::service>&, qos::service_level_options&>(seastar::sharded<qos::service_level_controller>::start<std::reference_wrapper<seastar::sharded<auth::service> >, qos::service_level_options&>(std::reference_wrapper<seastar::sharded<auth::service> >&&, qos::service_level_options&)::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}::operator()()::{lambda(std::reference_wrapper<seastar::sharded<auth::service> >, qos::service_level_options&)#1}&&, (seastar::sharded<auth::service>&)...) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:95
seastar::future<void> seastar::futurize<void>::invoke<seastar::sharded<qos::service_level_controller>::start<std::reference_wrapper<seastar::sharded<auth::service> >, qos::service_level_options&>(std::reference_wrapper<seastar::sharded<auth::service> >&&, qos::service_level_options&)::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}>(seastar::sharded<qos::service_level_controller>::start<std::reference_wrapper<seastar::sharded<auth::service> >, qos::service_level_options&>(std::reference_wrapper<seastar::sharded<auth::service> >&&, qos::service_level_options&)::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}&&) at ././seastar/include/seastar/core/future.hh:2132
```

The controller was introduced in e3db889057468c0812c7638c28eecbfe54b830c7
Cc @psarna

### PR DESCRIPTION
**Pull request by psarna**
The service level controller spawns an updating thread,
which wasn't properly waited for during shutdown.
This behavior is now fixed.

Tests: manual

Fixes #8468

### CODE REVIEW

File: service/qos/service_level_controller.cc [hunk 1]
```diff
@@ -87,14 +88,21 @@ void service_level_controller::set_distributed_data_accessor(service_level_distr
...
+        _sl_data_accessor = nullptr;
+        if (this_shard_id() == global_controller) {
+            // abort the loop of the distributed data checking if it is running
+            _global_controller_db->dist_data_update_aborter.request_abort();
+            _global_controller_db->notifications_serializer.broken();
+            co_await std::exchange(_global_controller_db->distributed_data_update, make_ready_future<>());
+        }
+        co_await std::exchange(_distributed_data_updater, make_ready_future<>());
+    } catch (const broken_semaphore&) {
+        // semaphore errors are expected
```
Comment (nyh) [inline service/qos/service_level_controller.cc:102]: A question:
If the first co_await throws, the second co_await is not done at all. Is this fine or impossible (i.e. the first one doesn't throw)?
If it isn't fine, you need to use one of the idioms that waits for multiple futures, and probably not coroutines :-(

Comment (psarna) [reply service/qos/service_level_controller.cc:102]: If the first co_await throws, then the second one is already ready in this specific situation, so it's safe to discard. And if the second one failed, the first one would never be assigned to, so it will be a ready future and it will not throw.

Comment (nyh) [reply service/qos/service_level_controller.cc:102]: Ok, I'll take your word for it - I don't understand when are these broken semaphore et al. exceptions are expected, and why it's enough to only wait for one of these futures in that case, but you obviously know the flow and are correct.

**Review by nyh — APPROVED** [review]

**Comment by nyh** [comment]
I see you specifically asked Benny for a review, so I won't commit yet.

File: service/qos/service_level_controller.cc (hunk 1 above)
Comment (bhalevy) [reply service/qos/service_level_controller.cc:102]: For the sake of being future-proof, I tend to agree with @nyh that we better `co_await when_all_succeed()`
on both, if `_distributed_data_updater` should be ready in case `_global_controller_db->distributed_data_update` failed.

Comment (psarna) [reply service/qos/service_level_controller.cc:102]: sure, I'll rework and send v2

**Comment by bhalevy** [comment]
> I see you specifically asked Benny for a review, so I won't commit yet.

I don't have any clear objection, but I agree with you it's safer on the long run to always wait on both futures in the `this_shard_id() == global_controller` case, even if in the current state of affairs we don't have to.  It's just the the starts alignment might change over time and the proposed change is quite fragile in this sense.

**Comment by psarna** [comment]
v2:
 - reversed the order of waiting to make it clearer - we first ensure that initialization of the data updater is finished, and only then wait for the actual updates to end
 - made the steps more robust wrt. exceptions - whatever happens, both routines will always be tried

**Review by bhalevy — APPROVED** [review]
LGTM, thanks.

File: service/qos/service_level_controller.cc [hunk 2]
```diff
@@ -89,12 +90,21 @@ void service_level_controller::set_distributed_data_accessor(service_level_distr
...
+    }
     if (this_shard_id() == global_controller) {
         // abort the loop of the distributed data checking if it is running
         _global_controller_db->dist_data_update_aborter.request_abort();
         _global_controller_db->notifications_serializer.broken();
+        try {
+            co_await std::exchange(_global_controller_db->distributed_data_update, make_ready_future<>());
+        } catch (const broken_semaphore& ignored) {
+        } catch (const sleep_aborted& ignored) {
+        }
```
Comment (avikivity) [inline service/qos/service_level_controller.cc:106]: There's no point in having stop() functions pass an exception. So better to catch ... and log it here rather than confusing the caller.

**Comment by avikivity** [comment]
Looks good, I'll let @nyh commit.

File: service/qos/service_level_controller.cc (hunk 2 above)
Comment (psarna) [reply service/qos/service_level_controller.cc:106]: Yeah, but unexpected exceptions in stop() are caught in main.cc and printed - here I just explicitly ignore the boring ones.

**Comment by nyh** [comment]
> Looks good, I'll let @nyh commit.

I already did. It hasn't yet reached master, so this PR is not closed yet.

**Comment by psarna** [comment]
Dequeued due to dtests failures (unexpected error logs). The cause is known so I'll push an updated version in a few minutes.

**Comment by psarna** [comment]
Fixed by no bothering to catch only certain types of exceptions after all - not worth all the failed dtests. Please rereview.

File: service/qos/service_level_controller.cc [hunk 3]
```diff
@@ -89,12 +90,21 @@ void service_level_controller::set_distributed_data_accessor(service_level_distr
 future<> service_level_controller::stop() {
     // unregister from the service level distributed data accessor.
     _sl_data_accessor = nullptr;
+    try {
+        co_await std::exchange(_distributed_data_updater, make_ready_future<>());
+    } catch (...) {
+        // ignore all exceptions from distributed updater initialization
```
Comment (avikivity) [inline service/qos/service_level_controller.cc:96]: Maybe log at least? we could have something broken and not know about it.

Comment (bhalevy) [reply service/qos/service_level_controller.cc:96]: Yeah, I had the same thing in my mind, though I don't how helpful it will be...
For example: https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/3405/artifact/logs-gating.release.2/1618393293064_deletion_test.RangeDeletionTester.delete_by_1ck_range_less_more_test/node4.log
```
ERROR 2021-04-14 09:41:32,078 [shard 0] init - Unexpected error shutting down service level controller: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
```
It won't hurt to WARN about it though.

Comment (psarna) [reply service/qos/service_level_controller.cc:96]: In that case I'd rather go back to catching specific exception types - `exceptions::unavailable_exception` was the one that got detected in dtests. Listing all expected exception types is the best way to ensure that we don't ignore something genuinely broken, even though it might involve a couple of failed dtest runs to recognize all the expected failures.

I'll restore catching specific types in v3 and add the newly detected error.

**Comment by psarna** [comment]
Actually, I think it's also possible to race between setting the `_sl_data_accessor` to nullptr and accessing it, because they happen between preemption points. So I'll include both fixes in v3.

**Comment by psarna** [comment]
v3:
 - instead of ignoring all exceptions (v2), let's just ignore the one that caused the regression
 - moved setting `_sl_data_accessor` to nullptr only after the updates are done - otherwise it's possible to nullify the pointer before it's being dereferenced by an already ongoing update process

File: service/qos/service_level_controller.cc (hunk 2 above)
Comment (bhalevy) [reply service/qos/service_level_controller.cc:109]: You can still catch the unexpected ones and log an error or warning about them.
An ERROR would help catch it in dtest and decide what do about it since we fail all dtests on any unexpected ERROR that is not explicitly marked to be ignored by the test, while it won't cause a coredump when shutting down in production.

File: service/qos/service_level_controller.cc (hunk 3 above)
Comment (bhalevy) [reply service/qos/service_level_controller.cc:98]: why not log a warning about ignoring the exception here?

**Comment by nyh** [comment]
> Fixed by not bothering to catch only certain types of exceptions after all - not worth all the failed dtests. Please rereview.

Can you give an example what kind of error this was?
Maybe we should consider changing the dtests to be more forgiving for this kind of error? It's very frustrating when dtests enshrine some behavior that we never intended to enshrine.

**Comment by psarna** [comment]
@nyh It was an unavailable exception (a CQL one) coming from the fact that the updater service tried to issue a CQL request and failed to perform it, because the cluster is shutting down. It's definitely one of the expected errors here.

**Review by nyh — APPROVED** [review]
I'll commit because you clearly have given this a lot of thought, but I have to be honest - I don't understand the logic where for one future you ignore all exceptions, but for another future you ignore only specific kinds of exceptions. I don't know how to check if this list is comprehensive or not. Though I guess we can incrementally improve it later....

Regarding whether stop() should sometimes throw or just low internal exceptions, see also https://github.com/scylladb/seastar/issues/724 where I debated myself whether a close() should throw, or should catch all internal exceptions and just log them.

File: service/qos/service_level_controller.cc (hunk 3 above)
Comment (psarna) [reply service/qos/service_level_controller.cc:98]: If the intent is that we want to know if an unexpected exception happens due to a bug, then it's best to just use the existing mechanism - report an unexpected exception on shutdown as an error and investigate. I don't remember how dtests react to warnings, but I think it's not a good idea either way:
 - if warnings also fail the test, then there's no point in having a separate mechanism for reporting it, main.cc already does that
 - if warnings don't fail the test, then we actually wouldn't know when a bug happens, because nobody reads logs from successful dtests

**Comment by bhalevy** [comment]
Regarding the dtests, by default they want to fail on any unexpected ERROR.  Expected errors can be explicitly added to `ignore_log_pattern` that filters the logs for expected error upon exit.

We can even tolerate expected core dumps when we know the test may crash scylla (like when running the scrub compaction tests that may cause crashes with random sstable injected corruption), but in general I'd rater dtests always fail if a core dump is detected.

File: service/qos/service_level_controller.cc (hunk 3 above)
Comment (bhalevy) [reply service/qos/service_level_controller.cc:98]: > If the intent is that we want to know if an unexpected exception happens due to a bug

But this hunk swallows *all* exceptions, with no indication whatsoever that they happen.
I proposed a warning here since it doesn't cause tests to fail but could come handy in postmortem analysis as extra evidence to something else that went bad.

Comment (psarna) [reply service/qos/service_level_controller.cc:98]: Ooh we're talking about the first one. Sorry, sure, I forgot it existed. Warning makes perfect sense here.

**Comment by nyh** [comment]
> Regarding the dtests, by default they want to fail on any unexpected ERROR. Expected errors can be explicitly added to `ignore_log_pattern` that filters the logs for expected error upon exit.

Yes, I know this is the case, but I wonder about the wisdom of doing this.
Some tests are clearly about testing **functionality** of something. You test some query and see if you get the expected result. If you get the expected result, and **also** some error is logged, well, it's a shame, but it's not really related to what was being tested. This is doubly true if it's not really a new error but just some old error that was previously ignored but the message changed. It is triply true when the error happens during the shutdown of Scylla - not during the main part of the test.

The most important question in this regard of these error-message-failures, how many were real bugs detected, and how many were false positives that caused any hours of wasted developer work. I'm not saying I expected 100% real bugs - maybe even 10% real bugs is worth the hassle. But is it 10%, or 0%? I'm not familiar enough with the statistics which is why I'm asking.

> 
> We can even tolerate expected core dumps when we know the test may crash scylla (like when running the scrub compaction tests that may cause crashes with random sstable injected corruption), but in general I'd rater dtests always fail if a core dump is detected.

Crashes are a bit different from error logs. We expect to **never** have crashes, but we do expect error logs of various types, and have often debated whether a certain "normal" event (e.g., one of the nodes being down, or in the present cases - problems during shutdown) should be reported as an error or warning. This is why it's not obvious that tests need to care exactly what error messages appear in the log - just like they don't care which warning messages appear in the log.

**Comment by psarna** [comment]
v4:
 - added logging exceptions from the distributed updater initialization during shutdown, which is otherwise ignored

**Comment by psarna** [comment]
Oh, queued already. If it gets through, I'll add the last logging part as a follow-up.

**Comment by bhalevy** [comment]
@nyh
> The most important question in this regard of these error-message-failures, how many were real bugs detected, and how many were false positives that caused any hours of wasted developer work. I'm not saying I expected 100% real bugs - maybe even 10% real bugs is worth the hassle. But is it 10%, or 0%? I'm not familiar enough with the statistics which is why I'm asking.

I don't keep up statistics on that.
It happens rarely nowdays that we see new dtest failures due to unexpected errors in the log.
I don't feel it's a waste of my time or anybody elses to examine any such error and vet what to do about it.
If it's benign under the specific test scenario that it can be easily added to the ignore list, and if it indicates a real issue, I bless the day we decided to fail the test on unexpected errors :)

I think that the bottom line here is the dtests function both a regression tests, that we want to pass (and then focusing solely on the functionality will be sufficient), but also as exploration tests in which we piggyback testing the general well being of the system on the regression tests.  That's the reason I also added mandatory cluster shutdown after the test, otherwise we'd never hit issues on shutdown (like this one), that might or might not be directly related to the workload the dtest inflected on the nodes.

**Comment by nyh** [comment]
> @nyh
> 
> > The most important question in this regard of these error-message-failures, how many were real bugs detected, and how many were false positives that caused any hours of wasted developer work. I'm not saying I expected 100% real bugs - maybe even 10% real bugs is worth the hassle. But is it 10%, or 0%? I'm not familiar enough with the statistics which is why I'm asking.
> 
> I don't keep up statistics on that.

But is it more than zero times? :-)
Did we ever catch a real bug this way, or was the solution always to change the test to allow another error or "downgrade" the error to a warning?

**Comment by psarna** [comment]
The next keeps failing, and the longer I look at the shutdown routine for service levels, the less sense it makes. I'm going to dequeue this fix in hopes to unblock next (although the code in master looks broken too), and instead simplify the shutdown procedure as much as possible.

**Comment by psarna** [comment]
v4:
 - got rid of nullifying the `_sl_data_accessor` pointer, since there's no point in doing so on shutdown and there's a potential risk of dereferencing it in a stray continuation
 - got rid of `_distributed_data_updater` future altogether by ensuring that the updates are always initiated on shard0 - before, the function could be called on any shard, but it always invoked a lambda on shard0, but at the same time the function signature did not return a future, which was why the future was kept in an additional attribute (`_distributed_data_updater`). Once we just ensure that this updates can only be initiated on shard0, no additional futures need to be kept and waited for, which simplifies the shutdown procedure.

I'm still not able to reproduce this failure (neither on next nor master), but I still suspect that the master branch is also affected by this, which also makes /next flaky.

File: service/qos/service_level_controller.cc [hunk 4]
```diff
@@ -103,63 +107,65 @@ future<> service_level_controller::update_service_levels_from_distributed_data()
         return make_ready_future();
     }
 
-    return container().invoke_on(global_controller, [] (service_level_controller& sl_controller) {
-        return with_semaphore(sl_controller._global_controller_db->notifications_serializer, 1, [&sl_controller] () {
-            return async([&sl_controller] () {
```
Comment (psarna) [inline service/qos/service_level_controller.cc:108]: Note to self: this thread is created every time an update is needed (in a seastar::repeat loop), so perhaps it's better off as a coroutine. Alternatively, the whole loop can be moved to a thread/coroutine

**Comment by psarna** [comment]
@scylladb/scylla-maint I'm pretty sure that this pull request has a chance of unblocking next (which is in fact a blocked master which luckily passed gating)

**Comment by psarna** [comment]
I also tested in debug mode just in case, but no problems were detected

File: service/qos/service_level_controller.cc (hunk 4 above)
Comment (psarna) [reply service/qos/service_level_controller.cc:108]: 2c4979fb59197fd175bec054eafe505c45f62335, but I'll only post it after this PR (or some future iteration of it) gets merged and next is fixed

**Review by nyh — APPROVED** [review]
I see Avi has already approved this version. I'll commit it, yet again, hoping that this time it won't fail...

**Comment by psarna** [comment]
Still fails... I need to somehow find a way to reliably reproduce this one locally, I'm out of ideas what goes wrong and the core dumps weren't helpful last time. Maybe these new ones at least have some useful context

**Comment by psarna** [comment]
And I also hope it's not a coroutine issue again... Maybe I'll also try reproducing the issue with higher inline threshold and coding this one without coroutines if it's that again

**Comment by psarna** [comment]
meanwhile, dequeued

**Comment by bhalevy** [comment]
what happened to the simple version of the fix?
Was it dequeued too?

**Comment by psarna** [comment]
> what happened to the simple version of the fix?
> Was it dequeued too?

Which simple version? No version made it through /next so far, but all of them were also flawed (discovered by closer code inspection later). I hoped the last one is correct because I spent much more time on analyzing it, but I still wasn't able to see this failure locally even once, which makes it harder to reliably check if the fix works or not.

**Comment by bhalevy** [comment]
Can we start with something simple like https://github.com/scylladb/scylla/commit/baa91dc07acb4a61c27951c0e706e4d5f9da6cf0
plus warnings about exceptions from _distributed_data_updater that are caught and ignored?

**Comment by psarna** [comment]
> Can we start with something simple like [baa91dc](https://github.com/scylladb/scylla/commit/baa91dc07acb4a61c27951c0e706e4d5f9da6cf0)
> plus warnings about exceptions from _distributed_data_updater that are caught and ignored?
We did - and the tests still sometimes segfault with "Stopping service level controller" as the last entry in logs, 
 but at the same time the core dump doesn't have any meaningful backtrace - no segfault or assert, all threads look like idle scylla polling for more work.

**Comment by psarna** [comment]
I'm also unable to locally verify my theory about coroutine problems with elevaled inline threshold, because with the original inline threshold setting (2500) row_level.cc never finishes compiling for me.

**Comment by bhalevy** [comment]
`service_level_controller::stop` doesn't have to be a coroutine, does it?

**Comment by psarna** [comment]
Yes, after the simplification it doesn't anymore. That will be my next attempt, if my current efforts with gdb fail to pinpoint the problem

**Comment by bhalevy** [comment]
I tried this:
```
SEASTAR_TEST_CASE(test_exchange_preemption) {
    bool x = false;
    unsigned preempted = 0;
    auto f = later().then([&x] {
            x = true;
        });

    // try to preempt 1000 times. 1 should be enough if not for
    // task queue shaffling in debug mode which may cause co-routine
    // continuation to run first.
    while(preempted < 1000 && !x) {
        preempted += need_preempt(); 
        co_await make_ready_future<>();
    }
    auto save_x = x;
    // wait for later() to complete
    co_await std::exchange(f, make_ready_future<>());
    BOOST_REQUIRE(save_x);
    co_return;
}
```

```
bhalevy@dt seastar$ mode=debug; ninja -C build/$mode test_unit_coroutines && build/$mode/tests/unit/coroutines_test -l all -t test_exchange_preemption
ninja: Entering directory `build/debug'
[91/91] Linking CXX executable tests/unit/coroutines_test
WARNING: debug mode. Not for benchmarking or production
random-seed=4131432382
Running 1 test case...
Entering test module "../../tests/unit/coroutines_test.cc"
../../tests/unit/coroutines_test.cc(0): Test case "test_simple_coroutines" is skipped because disabled
../../tests/unit/coroutines_test.cc(0): Test case "test_abandond_coroutine" is skipped because disabled
../../tests/unit/coroutines_test.cc(0): Test case "test_scheduling_group" is skipped because disabled
../../tests/unit/coroutines_test.cc(0): Test case "test_preemption" is skipped because disabled
../../tests/unit/coroutines_test.cc(0): Entering test case "test_exchange_preemption"
../../src/testing/seastar_test.cc(43): info: check true has passed
../../tests/unit/coroutines_test.cc(191): info: check save_x has passed
=================================================================
==142224==ERROR: AddressSanitizer: stack-buffer-underflow on address 0x7fa286d8d888 at pc 0x0000004482e4 bp 0x7fa286d8d5c0 sp 0x7fa286d8d5b8
READ of size 8 at 0x7fa286d8d888 thread T1
    #0 0x4482e3 in seastar::future_state_base::any::has_result() const ../../include/seastar/core/future.hh:503
    #1 0x453703 in seastar::future_state<seastar::internal::monostate>::clear() ../../include/seastar/core/future.hh:606
    #2 0x4496ed in seastar::future_state<seastar::internal::monostate>::~future_state() ../../include/seastar/core/future.hh:614
    #3 0x4496ed in seastar::future<void>::~future() ../../include/seastar/core/future.hh:1337
    #4 0x43f25b in test_exchange_preemption::run_test_case() [clone .actor] ../../tests/unit/coroutines_test.cc:192
    #5 0x44a3cd in std::__n4861::coroutine_handle<void>::resume() const (/home/bhalevy/dev/seastar/build/debug/tests/unit/coroutines_test+0x44a3cd)
    #6 0x44a7b7 in seastar::internal::coroutine_traits_base<void>::promise_type::run_and_dispose() (/home/bhalevy/dev/seastar/build/debug/tests/unit/coroutines_test+0x44a7b7)
    #7 0x6ae815 in seastar::reactor::run_tasks(seastar::reactor::task_queue&) ../../src/core/reactor.cc:2260
    #8 0x6b2ce3 in seastar::reactor::run_some_tasks() ../../src/core/reactor.cc:2669
    #9 0x6b822e in seastar::reactor::run() ../../src/core/reactor.cc:2828
    #10 0x4f076c in seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) ../../src/core/app-template.cc:207
    #11 0x4ee7ca in seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) ../../src/core/app-template.cc:115
    #12 0x47c131 in operator() ../../src/testing/test_runner.cc:70
    #13 0x487403 in __invoke_impl<void, seastar::testing::test_runner::start(int, char**)::<lambda()>&> /usr/include/c++/10/bits/invoke.h:60
    #14 0x485757 in __invoke_r<void, seastar::testing::test_runner::start(int, char**)::<lambda()>&> /usr/include/c++/10/bits/invoke.h:110
    #15 0x483a1f in _M_invoke /usr/include/c++/10/bits/std_function.h:291
    #16 0x50fe7c in std::function<void ()>::operator()() const /usr/include/c++/10/bits/std_function.h:622
    #17 0x657bf6 in seastar::posix_thread::start_routine(void*) ../../src/core/posix.cc:60
    #18 0x7fa28b5163f8 in start_thread (/lib64/libpthread.so.0+0x93f8)
    #19 0x7fa28a73bb52 in __GI___clone (/lib64/libc.so.6+0x101b52)

Address 0x7fa286d8d888 is located in stack of thread T1 at offset 8 in frame
    #0 0x44a6f5 in seastar::internal::coroutine_traits_base<void>::promise_type::run_and_dispose() (/home/bhalevy/dev/seastar/build/debug/tests/unit/coroutines_test+0x44a6f5)

  This frame has 1 object(s):
    [32, 40) 'handle' (line 110)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
Thread T1 created by T0 here:
    #0 0x7fa28bb22f46 in __interceptor_pthread_create (/lib64/libasan.so.6+0x55f46)
    #1 0x658193 in seastar::posix_thread::posix_thread(seastar::posix_thread::attr, std::function<void ()>) ../../src/core/posix.cc:95
    #2 0x657d72 in seastar::posix_thread::posix_thread(std::function<void ()>) ../../src/core/posix.cc:65
    #3 0x4801ce in make_unique<seastar::posix_thread, seastar::testing::test_runner::start(int, char**)::<lambda()> > /usr/include/c++/10/bits/unique_ptr.h:962
    #4 0x47cb64 in seastar::testing::test_runner::start(int, char**) ../../src/testing/test_runner.cc:105
    #5 0x46c296 in init_unit_test_suite ../../src/testing/entry_point.cc:47
    #6 0x7fa28ba6305c  (/lib64/libboost_unit_test_framework.so.1.73.0+0x2605c)

SUMMARY: AddressSanitizer: stack-buffer-underflow ../../include/seastar/core/future.hh:503 in seastar::future_state_base::any::has_result() const
Shadow bytes around the buggy address:
  0x0ff4d0da9ac0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff4d0da9ad0: f1 f1 f1 f1 00 f2 f2 f2 00 f2 f2 f2 00 00 f2 f2
  0x0ff4d0da9ae0: f8 f8 f2 f2 f8 f8 f2 f2 f8 f8 f2 f2 f8 f8 f2 f2
  0x0ff4d0da9af0: f8 f8 f8 f2 f2 f2 f2 f2 f8 f8 f8 f8 f3 f3 f3 f3
  0x0ff4d0da9b00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0ff4d0da9b10: f1[f1]f1 f1 00 f3 f3 f3 00 00 00 00 00 00 00 00
  0x0ff4d0da9b20: 00 00 00 00 f1 f1 f1 f1 f8 f3 f3 f3 00 00 00 00
  0x0ff4d0da9b30: 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1 01 f2
  0x0ff4d0da9b40: 04 f2 00 f2 f2 f2 00 f2 f2 f2 f8 f2 f2 f2 00 f2
  0x0ff4d0da9b50: f2 f2 00 f2 f2 f2 00 f2 f2 f2 00 f2 f2 f2 00 f3
  0x0ff4d0da9b60: f3 f3 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==142224==ABORTING
```

**Comment by bhalevy** [comment]
I think that the compiler release the std::exchange'd future as if it was a temporary.

**Comment by bhalevy** [comment]
Edit: the `stack-buffer-underflow` problem above happens in debug mode for me also with the existing `test_preemption` case in seastar's coroutines_test

**Comment by psarna** [comment]
I'm shipping a decoroutinized patch in a minute, after I verify locally that it doesn't crash

**Comment by psarna** [comment]
v5:
 - got rid of the (now rather unnecessary) coroutine in ::stop()

**Comment by psarna** [comment]
Maintainers: please consider shipping along with #8506 in order to make it easier to debug core dumps from Jenkins, if they keep happening

**Comment by bhalevy** [comment]
LGTM

**Comment by nyh** [comment]
I don't know how to review this patch any more (I didn't see any problems in any of the other 7 versions...), but I guess I'll continue to commit it as long as you continue to take care of the fallout (dequeuing and debugging). So, here we go again...

**Comment by psarna** [comment]
Looks like next is failing again, no coroutines :( but at least there will be more debug info to look into.

**Comment by nyh** [comment]
Oh my god, I'm going to submit this PR to the Guinness Book of World Records as the "unluckiest PR of all time" :-(
I assume you'll do the honor of dequeuing it? Thanks.

**Comment by psarna** [comment]
Customary daily dequeue is done. I'll continue investigating tomorrow, here's a message from Benny that I'm going to leverage:
> FWIW, it looks like the service_level_controller::stop hang on shutdown was just reproduced for me locally with scylla in debug mode with topology_test:TestTopology.crash_during_decommission_test

**Comment by psarna** [comment]
Good call, tomorrow I'll split the service level controller shutdown procedure into two: stop the updates early (before drain), because they depend on cql, and stop the rest of the controller later.

**Comment by psarna** [comment]
And at the same time I'll try to reproduce the problem with the dtest that Benny found

**Comment by psarna** [comment]
Found it! It hangs due to the fact that we have an infinite timeout config set up for internal queries, and the service level updater uses an internal query for updates. Once the cluster starts shutting down, the service level updating thread can hang on this infinite timeout.

**Comment by bhalevy** [comment]
> Found it! It hangs due to the fact that we have an infinite timeout config set up for internal queries, and the service level updater uses an internal query for updates. Once the cluster starts shutting down, the service level updating thread can hang on this infinite timeout.

Awesome.  That makes sense.

> Good call, tomorrow I'll split the service level controller shutdown procedure into two: stop the updates early (before drain), because they depend on cql, and stop the rest of the controller later.

Let's call the first stage "drain" and the final stage "stop", as the [design doc](https://docs.google.com/document/d/1GHJqHQHAhr1uJtzDaYjmvCy6eAYyLvnzHCyh5NODMRU/edit?usp=sharing) calls.

**Comment by psarna** [comment]
v6:
 - fixed the root cause of all previous hangs (which were disguised as core dumps - does Jenkins do that?) : the internal statements for service level updates used infinite timeouts, which caused them to never finish, which prevented proper shutdown
 - split the original stopping routine to separate drain and stop phases - draining is done while cql is still operable, because the service level updater uses the cql layer underneath

**Comment by psarna** [comment]
Tests: `topology_test.py:TestTopology.crash_during_decommission_test` - used to hang before the series, succeeds now

File: main.cc [hunk 5]
```diff
@@ -1460,6 +1460,10 @@ int main(int ac, char** av) {
                 service::get_local_storage_service().drain_on_shutdown().get();
             });
 
+            auto stop_sl_updates = defer_verbose_shutdown("service level controller updates", [] {
+                sl_controller.local().drain().get();
+            });
+
```
Comment (xemul) [inline main.cc:1466]: If someone does `nodetool drain` and then stops scylla, this deferred action will be called in the condition where commitlog is down and migration manager is stoped, i.e. as if it was called _after_ `drain_on_shutdown`. Is that OK?

File: service/qos/service_level_controller.cc [hunk 6]
```diff
@@ -86,15 +86,26 @@ void service_level_controller::set_distributed_data_accessor(service_level_distr
...
+        } catch (const broken_semaphore& ignored) {
+        } catch (const sleep_aborted& ignored) {
+        } catch (const exceptions::unavailable_exception& ignored) {
+        } catch (const exceptions::read_timeout_exception& ignored) {
+        }
+    });
+}
+
+future<> service_level_controller::stop() {
+    return make_ready_future<>();
```
Comment (xemul) [inline service/qos/service_level_controller.cc:108]: If start aborts due to an exception before `service_level_controller::drain` is deferred, then the whole stop becomes a no-op.

File: main.cc (hunk 5 above)
Comment (psarna) [reply main.cc:1466]: It is now, because the updater only reads from Scylla, it doesn't need to write anything.

Comment (xemul) [reply main.cc:1466]: OK, but why is `s_l_controller::drain` put to be run before `storage_service::drain_on_shutdown`?

File: service/qos/service_level_controller.cc (hunk 6 above)
Comment (psarna) [reply service/qos/service_level_controller.cc:108]: Right, that's no good

Comment (psarna) [reply service/qos/service_level_controller.cc:108]: I guess I should either make draining idempotent and call it in stop() or move the updater initialization right before deferring the drain. I'll go with making it idempotent.

**Comment by bhalevy** [comment]
> fixed the root cause of all previous hangs (which were disguised as core dumps - does Jenkins do that?)

ccm forces the core dump is the node does not shut itself down in a timely manner and times out.
In production systemd will do that.

File: main.cc (hunk 5 above)
Comment (psarna) [reply main.cc:1466]: Actually there's no reason now. I'll put it after, to match the behavior if somebody runs `nodetool drain`

**Comment by nyh** [comment]
> > fixed the root cause of all previous hangs (which were disguised as core dumps - does Jenkins do that?)
> 
> ccm forces the core dump is the node does not shut itself down in a timely manner and times out.
> In production systemd will do that.

I didn't know that... That's confusing. Could it at least write something to the log saying that it's doing that?

File: main.cc [hunk 7]
```diff
@@ -1452,6 +1452,10 @@ int main(int ac, char** av) {
                 sl_controller.stop().get();
             });
 
+            auto stop_sl_updates = defer_verbose_shutdown("service level controller updates", [] {
+                sl_controller.local().drain().get();
+            });
+
```
Comment (xemul) [inline main.cc:1458]: Does it make sense to have separate action for `s_l_controller::drain` now? It's immediately followed by `sharded<s_l_controller>::stop`, so if you remove this draining defer, seastar will call `s_l_controller::stop` automagically and this `stop` already calls `s_l_controller::drain` inside.

Comment (psarna) [reply main.cc:1458]: Yeah, this deferrer can be reduced now

**Comment by bhalevy** [comment]
> > > fixed the root cause of all previous hangs (which were disguised as core dumps - does Jenkins do that?)
> > 
> > 
> > ccm forces the core dump is the node does not shut itself down in a timely manner and times out.
> > In production systemd will do that.
> 
> I didn't know that... That's confusing. Could it at least write something to the log saying that it's doing that?

It does, though it's hard to find.
It should be written to dtest.log, but it doesn't have the test name prefix since it comes from the ccm layer rather than the dtest layer.  They can be matched together using the PID column that is the same for both dtest and log ccm messages in the same nosetests process.

**Comment by psarna** [comment]
v7:
 - made drain() idempotent
 - ensured that drain is always called before stop
 - removed the (now redundant) separate deferred action for draining the service level controller

**Comment by psarna** [comment]
ping

File: service/qos/service_level_controller.cc [hunk 8]
```diff
@@ -86,15 +86,30 @@ void service_level_controller::set_distributed_data_accessor(service_level_distr
...
-        _global_controller_db->notifications_serializer.broken();
+future<> service_level_controller::drain() {
+    if (this_shard_id() != global_controller) {
+        return make_ready_future();
+    }
+    if (_drained) {
+        return make_ready_future<>();
     }
-    return std::exchange(_distributed_data_updater, make_ready_future<>());
+    _drained = true;
```
Comment (avikivity) [inline service/qos/service_level_controller.cc:96]: Could two drains be called in parallel? In that case the second will return early.

If that's a problem, we can use a shared_future to indicate when draining is complete to all callers.

Comment (psarna) [reply service/qos/service_level_controller.cc:96]: Currently the only user of `service_level_controller::drain` is `service_level_controller::stop`, which is only called once on shutdown, so two drains would not be called in parallel.

Comment (avikivity) [reply service/qos/service_level_controller.cc:96]: Ok. So I don't see why you needed to extract drain().

Comment (psarna) [reply service/qos/service_level_controller.cc:96]: It turned out I didn't. It's a byproduct of earlier iterations, but it's good practice anyway (because the update process can have virtual executors and depend on multiple services), so I let it stay. I can also remove it from this series if requested.

Comment (psarna) [reply service/qos/service_level_controller.cc:96]: (please let me know if it *is* requested)

Comment (avikivity) [reply service/qos/service_level_controller.cc:96]: No, it's fine as is.

**Comment by avikivity** [comment]
@bhalevy @nyh are you okay with this?

File: service/qos/service_level_controller.cc (hunk 8 above)
Comment (bhalevy) [reply service/qos/service_level_controller.cc:96]: I don't think that can happen, yet it looks like if it will `std::exchange(_global_controller_db->distributed_data_update, make_ready_future<>())` it would be idempotent and won't need to add the `_drained` flag at all.

Comment (psarna) [reply service/qos/service_level_controller.cc:96]: As long as `abort_source::request_abort()` and `semaphore::broken()` are also idempotent, but it looks like they are. I'll get rid of the flag.

Comment (psarna) [reply service/qos/service_level_controller.cc:96]: Oh wait - semaphore::broken might be, but request_abort isn't, it would have to be wrapped in a check. Still, it's easy.

Comment (bhalevy) [reply service/qos/service_level_controller.cc:96]: You're right about `request_abort`, sorry.  And indeed `abort_requested()` can come to the rescue.

**Comment by psarna** [comment]
v8:
 - got rid of the explicit `_drained` variable by ensuring that the whole drain operation is idempotent anyway

**Review by bhalevy — APPROVED** [review]
LGTM

**Comment by nyh** [comment]
Committed. Hopefully 10th time's a charm :-)

**Comment by psarna** [comment]
Sighhhhhhhhhhhhhhhhhhhhhhh....

**Comment by psarna** [comment]
I'll dequeue - everything is fine this time, except that a test which tries unrealistic allocation sizes messed with the address sanitizer from debug mode. I'll provide fixed version 10000000 soon, and meanwhile also dequeue.

**Comment by psarna** [comment]
Oh wait!!! It's not this series. It's the one with rapidjson allocators.
