### PR TITLE
sstable: reader: preempt after every fragment

### LINKED ISSUE #7883: data_consumer::continuous_data_consumer<sstables::data_consume_rows_context_m>::process: Reactor stalled for 7 ms during "Steady State"
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.4.dev-0.20201231.93a2c5233 with build-id 63738ab215ea91209c7488bf63b0556f6adf6c15
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-047c88faadef0dbc6

comparing with other stalls issues (opened and closed), related to latency during management operations, i couldn't find any of the reported functions in there, so reporting this one.

`Reactor stalled for 7 ms on shard 1.`

here is the backtrace:
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:731
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&) at ./build/release/seastar/./seastar/src/core/reactor.cc:752
 (inlined by) seastar::internal::cpu_stall_detector::generate_trace() at ./build/release/seastar/./seastar/src/core/reactor.cc:1210
seastar::internal::cpu_stall_detector::maybe_report() at ./build/release/seastar/./seastar/src/core/reactor.cc:1056
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1070
 (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1193
?? ??:0
unsigned char* std::__copy_move<false, true, std::random_access_iterator_tag>::__copy_m<unsigned char>(unsigned char const*, unsigned char const*, unsigned char*) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/stl_algobase.h:426
 (inlined by) unsigned char* std::__copy_move_a2<false, unsigned char const*, unsigned char*>(unsigned char const*, unsigned char const*, unsigned char*) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/stl_algobase.h:471
 (inlined by) unsigned char* std::__copy_move_a1<false, unsigned char const*, unsigned char*>(unsigned char const*, unsigned char const*, unsigned char*) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/stl_algobase.h:506
 (inlined by) unsigned char* std::__copy_move_a<false, unsigned char const*, unsigned char*>(unsigned char const*, unsigned char const*, unsigned char*) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/stl_algobase.h:514
 (inlined by) unsigned char* std::copy<unsigned char const*, unsigned char*>(unsigned char const*, unsigned char const*, unsigned char*) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/stl_algobase.h:568
 (inlined by) unsigned char* std::__copy_n<unsigned char const*, unsigned long, unsigned char*>(unsigned char const*, unsigned long, unsigned char*, std::random_access_iterator_tag) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/stl_algo.h:750
 (inlined by) unsigned char* std::copy_n<unsigned char const*, unsigned long, unsigned char*>(unsigned char const*, unsigned long, unsigned char*) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/stl_algo.h:777
 (inlined by) void imr::internal::write_pod<unsigned int, unsigned char>(unsigned int, unsigned char*) at ././imr/fundamental.hh:49
 (inlined by) imr::pod<unsigned int>::serialize(unsigned char*, unsigned int const&) at ././imr/fundamental.hh:211
 (inlined by) imr::internal::structure_serializer<imr::no_op_continuation, imr::member<data::cell::tags::value_data, imr::variant<data::cell::tags::value_data, imr::member<data::cell::tags::pointer, imr::tagged_type<data::cell::tags::pointer, imr::pod<unsigned char*> > >, imr::member<data::cell::tags::data, imr::buffer<data::cell::tags::data> > > > > imr::internal::basic_structure_serializer<imr::no_op_continuation, imr::member<data::cell::tags::value_size, imr::pod<unsigned int> >, imr::member<data::cell::tags::value_data, imr::variant<data::cell::tags::value_data, imr::member<data::cell::tags::pointer, imr::tagged_type<data::cell::tags::pointer, imr::pod<unsigned char*> > >, imr::member<data::cell::tags::data, imr::buffer<data::cell::tags::data> > > > >::serialize<unsigned long&>(unsigned long&) at ././imr/compound.hh:413
 (inlined by) auto data::cell::value_writer<single_fragment_range<(mutable_view)0> >::operator()<imr::internal::structure_serializer<imr::no_op_continuation, imr::member<data::cell::tags::value_size, imr::pod<unsigned int> >, imr::member<data::cell::tags::value_data, imr::variant<data::cell::tags::value_data, imr::member<data::cell::tags::pointer, imr::tagged_type<data::cell::tags::pointer, imr::pod<unsigned char*> > >, imr::member<data::cell::tags::data, imr::buffer<data::cell::tags::data> > > > >, imr::alloc::object_allocator::serializer>(imr::internal::structure_serializer<imr::no_op_continuation, imr::member<data::cell::tags::value_size, imr::pod<unsigned int> >, imr::member<data::cell::tags::value_data, imr::variant<data::cell::tags::value_data, imr::member<data::cell::tags::pointer, imr::tagged_type<data::cell::tags::pointer, imr::pod<unsigned char*> > >, imr::member<data::cell::tags::data, imr::buffer<data::cell::tags::data> > > > >, imr::alloc::object_allocator::serializer) at ././data/cell.hh:185
 (inlined by) unsigned long imr::structure<imr::member<data::cell::tags::value_size, imr::pod<unsigned int> >, imr::member<data::cell::tags::value_data, imr::variant<data::cell::tags::value_data, imr::member<data::cell::tags::pointer, imr::tagged_type<data::cell::tags::pointer, imr::pod<unsigned char*> > >, imr::member<data::cell::tags::data, imr::buffer<data::cell::tags::data> > > > >::serialize<data::cell::value_writer<single_fragment_range<(mutable_view)0> >, imr::alloc::object_allocator::serializer&>(unsigned char*, data::cell::value_writer<single_fragment_range<(mutable_view)0> >&&, imr::alloc::object_allocator::serializer&) at ././imr/compound.hh:556
 (inlined by) unsigned long imr::variant<data::cell::tags::value, imr::member<data::cell::tags::dead, imr::pod<long> >, imr::member<data::cell::tags::counter_update, imr::pod<long> >, imr::member<data::cell::tags::fixed_value, imr::buffer<data::cell::tags::fixed_value> >, imr::member<data::cell::tags::variable_value, imr::structure<imr::member<data::cell::tags::value_size, imr::pod<unsigned int> >, imr::member<data::cell::tags::value_data, imr::variant<data::cell::tags::value_data, imr::member<data::cell::tags::pointer, imr::tagged_type<data::cell::tags::pointer, imr::pod<unsigned char*> > >, imr::member<data::cell::tags::data, imr::buffer<data::cell::tags::data> > > > > > >::serialize<data::cell::tags::variable_value, data::cell::value_writer<single_fragment_range<(mutable_view)0> >, imr::alloc::object_allocator::serializer&>(unsigned char*, data::cell::value_writer<single_fragment_range<(mutable_view)0> >&&, imr::alloc::object_allocator::serializer&) at ././imr/compound.hh:258
 (inlined by) imr::internal::structure_serializer<imr::internal::structure_serializer_continuation<imr::internal::structure_serializer_continuation<imr::no_op_continuation>>> imr::internal::structure_serializer<imr::internal::structure_serializer_continuation<imr::internal::structure_serializer_continuation<imr::no_op_continuation>>, imr::member<data::cell::tags::value, imr::variant<data::cell::tags::value, imr::member<data::cell::tags::dead, imr::pod<long> >, imr::member<data::cell::tags::counter_update, imr::pod<long> >, imr::member<data::cell::tags::fixed_value, imr::buffer<data::cell::tags::fixed_value> >, imr::member<data::cell::tags::variable_value, imr::structure<imr::member<data::cell::tags::value_size, imr::pod<unsigned int> >, imr::member<data::cell::tags::value_data, imr::variant<data::cell::tags::value_data, imr::member<data::cell::tags::pointer, imr::tagged_type<data::cell::tags::pointer, imr::pod<unsigned char*> > >, imr::member<data::cell::tags::data, imr::buffer<data::cell::tags::data> > > > > > > > >::serialize_as<data::cell::tags::variable_value, data::cell::value_writer<single_fragment_range<(mutable_view)0> >, imr::alloc::object_allocator::serializer&>(data::cell::value_writer<single_fragment_range<(mutable_view)0> >&&, imr::alloc::object_allocator::serializer&) at ././imr/compound.hh:458
 (inlined by) operator() at ././data/cell.hh:484
 (inlined by) operator()<imr::internal::structure_serializer<imr::internal::structure_serializer_continuation<imr::no_op_continuation>, imr::member<data::cell::tags::flags, imr::flags<data::cell::tags::collection, data::cell::tags::live, data::cell::tags::expiring, data::cell::tags::counter_update, data::cell::tags::empty, data::cell::tags::external_data> >, imr::member<data::cell::tags::cell, imr::variant<data::cell::tags::cell, imr::member<data::cell::tags::atomic_cell, imr::structure<imr::member<data::cell::tags::timestamp, imr::pod<long> >, imr::member<data::cell::tags::expiring, imr::optional<data::cell::tags::expiring, imr::structure<imr::member<data::cell::tags::ttl, imr::pod<int> >, imr::member<data::cell::tags::expiry, imr::pod<long> > > > >, imr::member<data::cell::tags::value, imr::variant<data::cell::tags::value, imr::member<data::cell::tags::dead, imr::pod<long> >, imr::member<data::cell::tags::counter_update, imr::pod<long> >, imr::member<data::cell::tags::fixed_value, imr::buffer<data::cell::tags::fixed_value> >, imr::member<data::cell::tags::variable_value, imr::structure<imr::member<data::cell::tags::value_size, imr::pod<unsigned int> >, imr::member<data::cell::tags::value_data, imr::variant<data::cell::tags::value_data, imr::member<data::cell::tags::pointer, imr::tagged_type<data::cell::tags::pointer, imr::pod<unsigned char *> > >, imr::member<data::cell::tags::data, imr::buffer<data::cell::tags::data> > > > > > > > > >, imr::member<data::cell::tags::collection, imr::structure<imr::member<data::cell::tags::value_size, imr::pod<unsigned int> >, imr::member<data::cell::tags::value_data, imr::variant<data::cell::tags::value_data, imr::member<data::cell::tags::pointer, imr::tagged_type<data::cell::tags::pointer, imr::pod<unsigned char *> > >, imr::member<data::cell::tags::data, imr::buffer<data::cell::tags::data> > > > > > > > >, imr::alloc::object_allocator::serializer &> at ././data/cell.hh:479
 (inlined by) operator()<imr::internal::structure_serializer<imr::no_op_continuation, imr::member<imr::utils::basic_object::tags::back_pointer, imr::tagged_type<imr::utils::basic_object::tags::back_pointer, imr::pod<imr::utils::basic_object *> > >, imr::member<imr::utils::basic_object::tags::object, imr::structure<imr::member<data::cell::tags::flags, imr::flags<data::cell::tags::collection, data::cell::tags::live, data::cell::tags::expiring, data::cell::tags::counter_update, data::cell::tags::empty, data::cell::tags::external_data> >, imr::member<data::cell::tags::cell, imr::variant<data::cell::tags::cell, imr::member<data::cell::tags::atomic_cell, imr::structure<imr::member<data::cell::tags::timestamp, imr::pod<long> >, imr::member<data::cell::tags::expiring, imr::optional<data::cell::tags::expiring, imr::structure<imr::member<data::cell::tags::ttl, imr::pod<int> >, imr::member<data::cell::tags::expiry, imr::pod<long> > > > >, imr::member<data::cell::tags::value, imr::variant<data::cell::tags::value, imr::member<data::cell::tags::dead, imr::pod<long> >, imr::member<data::cell::tags::counter_update, imr::pod<long> >, imr::member<data::cell::tags::fixed_value, imr::buffer<data::cell::tags::fixed_value> >, imr::member<data::cell::tags::variable_value, imr::structure<imr::member<data::cell::tags::value_size, imr::pod<unsigned int> >, imr::member<data::cell::tags::value_data, imr::variant<data::cell::tags::value_data, imr::member<data::cell::tags::pointer, imr::tagged_type<data::cell::tags::pointer, imr::pod<unsigned char *> > >, imr::member<data::cell::tags::data, imr::buffer<data::cell::tags::data> > > > > > > > > >, imr::member<data::cell::tags::collection, imr::structure<imr::member<data::cell::tags::value_size, imr::pod<unsigned int> >, imr::member<data::cell::tags::value_data, imr::variant<data::cell::tags::value_data, imr::member<data::cell::tags::pointer, imr::tagged_type<data::cell::tags::pointer, imr::pod<unsigned char *> > >, imr::member<data::cell::tags::data, imr::buffer<data::cell::tags::data> > > > > > > > > > >, imr::alloc::object_allocator::serializer> at ././imr/utils.hh:186
 (inlined by) _ZN3imr9structureIJNS_6memberINS_5utils12basic_object4tags12back_pointerENS_11tagged_typeIS5_NS_3podIPS3_EEEEEENS1_INS4_6objectENS0_IJNS1_IN4data4cell4tags5flagsENS_5flagsIJNSF_10collectionENSF_4liveENSF_8expiringENSF_14counter_updateENSF_5emptyENSF_13external_dataEEEEEENS1_INSF_4cellENS_7variantISQ_JNS1_INSF_11atomic_cellENS0_IJNS1_INSF_9timestampENS7_IlEEEENS1_ISK_NS_8optionalISK_NS0_IJNS1_INSF_3ttlENS7_IiEEEENS1_INSF_6expiryESU_EEEEEEEEENS1_INSF_5valueENSR_IS15_JNS1_INSF_4deadESU_EENS1_ISL_SU_EENS1_INSF_11fixed_valueENS_6bufferIS19_EEEENS1_INSF_14variable_valueENS0_IJNS1_INSF_10value_sizeENS7_IjEEEENS1_INSF_10value_dataENSR_IS1H_JNS1_INSF_7pointerENS6_IS1I_NS7_IPhEEEEEENS1_INSF_4dataENS1A_IS1N_EEEEEEEEEEEEEEEEEEEEEEEENS1_ISI_S1S_EEEEEEEEEEEEEE9serializeIRZNS2_6objectIS21_E7do_makeIZNSE_9make_liveI21single_fragment_rangeIL12mutable_view0EEvEEDaRKNSD_9type_infoElOT_bEUlS2G_OT0_E_EES26_S2G_PK15migrate_fn_typeEUlS2G_S2I_E_JNS_5alloc16object_allocator10serializerEEEEmS1J_S2G_DpOT0_ at ././imr/compound.hh:556
 (inlined by) _ZN3imr5utils6objectINS_9structureIJNS_6memberIN4data4cell4tags5flagsENS_5flagsIJNS6_10collectionENS6_4liveENS6_8expiringENS6_14counter_updateENS6_5emptyENS6_13external_dataEEEEEENS3_INS6_4cellENS_7variantISH_JNS3_INS6_11atomic_cellENS2_IJNS3_INS6_9timestampENS_3podIlEEEENS3_ISB_NS_8optionalISB_NS2_IJNS3_INS6_3ttlENSL_IiEEEENS3_INS6_6expiryESM_EEEEEEEEENS3_INS6_5valueENSI_ISX_JNS3_INS6_4deadESM_EENS3_ISC_SM_EENS3_INS6_11fixed_valueENS_6bufferIS11_EEEENS3_INS6_14variable_valueENS2_IJNS3_INS6_10value_sizeENSL_IjEEEENS3_INS6_10value_dataENSI_IS19_JNS3_INS6_7pointerENS_11tagged_typeIS1A_NSL_IPhEEEEEENS3_INS6_4dataENS12_IS1G_EEEEEEEEEEEEEEEEEEEEEEEENS3_IS9_S1L_EEEEEEEEEEE7do_makeIZNS5_9make_liveI21single_fragment_rangeIL12mutable_view0EEvEEDaRKNS4_9type_infoElOT_bEUlS25_OT0_E_EES1V_S25_PK15migrate_fn_type at ././imr/utils.hh:194
 (inlined by) _ZN3imr5utils6objectINS_9structureIJNS_6memberIN4data4cell4tags5flagsENS_5flagsIJNS6_10collectionENS6_4liveENS6_8expiringENS6_14counter_updateENS6_5emptyENS6_13external_dataEEEEEENS3_INS6_4cellENS_7variantISH_JNS3_INS6_11atomic_cellENS2_IJNS3_INS6_9timestampENS_3podIlEEEENS3_ISB_NS_8optionalISB_NS2_IJNS3_INS6_3ttlENSL_IiEEEENS3_INS6_6expiryESM_EEEEEEEEENS3_INS6_5valueENSI_ISX_JNS3_INS6_4deadESM_EENS3_ISC_SM_EENS3_INS6_11fixed_valueENS_6bufferIS11_EEEENS3_INS6_14variable_valueENS2_IJNS3_INS6_10value_sizeENSL_IjEEEENS3_INS6_10value_dataENSI_IS19_JNS3_INS6_7pointerENS_11tagged_typeIS1A_NSL_IPhEEEEEENS3_INS6_4dataENS12_IS1G_EEEEEEEEEEEEEEEEEEEEEEEENS3_IS9_S1L_EEEEEEEEEEE4makeIZNS5_9make_liveI21single_fragment_rangeIL12mutable_view0EEvEEDaRKNS4_9type_infoElOT_bEUlS25_OT0_E_KNS_5alloc14lsa_migrate_fnINS2_IJNS3_INS0_12basic_object4tags12back_pointerENS1B_IS2D_NSL_IPS2B_EEEEEENS3_INS2C_6objectES1U_EEEEENS29_15context_factoryINS0_14object_contextINS5_7contextEJS21_EEEJS21_EEEEEEES1V_S25_PS26_ at ././imr/utils.hh:170
 (inlined by) atomic_cell::make_live(abstract_type const&, long, std::basic_string_view<signed char, std::char_traits<signed char> >, seastar::bool_class<atomic_cell::collection_member_tag>) at ./atomic_cell.cc:47
sstables::make_atomic_cell(abstract_type const&, long, std::basic_string_view<signed char, std::char_traits<signed char> >, std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >, seastar::bool_class<atomic_cell::collection_member_tag>) at ./sstables/mp_row_consumer.hh:102
 (inlined by) sstables::mp_row_consumer_m::consume_column(sstables::column_translation::column_info const&, std::basic_string_view<signed char, std::char_traits<signed char> >, std::basic_string_view<signed char, std::char_traits<signed char> >, long, std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >, bool) at ./sstables/mp_row_consumer.hh:1281
sstables::data_consume_rows_context_m::do_process_state(seastar::temporary_buffer<char>&) at ./sstables/row.hh:1148
sstables::data_consume_rows_context_m::process_state(seastar::temporary_buffer<char>&) at ./sstables/row.hh:781
 (inlined by) data_consumer::continuous_data_consumer<sstables::data_consume_rows_context_m>::process(seastar::temporary_buffer<char>&) at ././sstables/consumer.hh:447
 (inlined by) data_consumer::continuous_data_consumer<sstables::data_consume_rows_context_m>::operator()(seastar::temporary_buffer<char>) at ././sstables/consumer.hh:480
seastar::future<seastar::consumption_result<char> > std::__invoke_impl<seastar::future<seastar::consumption_result<char> >, sstables::data_consume_rows_context_m&, seastar::temporary_buffer<char> >(std::__invoke_other, sstables::data_consume_rows_context_m&, seastar::temporary_buffer<char>&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
 (inlined by) std::__invoke_result<sstables::data_consume_rows_context_m&, seastar::temporary_buffer<char> >::type std::__invoke<sstables::data_consume_rows_context_m&, seastar::temporary_buffer<char> >(sstables::data_consume_rows_context_m&, seastar::temporary_buffer<char>&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:95
 (inlined by) std::result_of<sstables::data_consume_rows_context_m& (seastar::temporary_buffer<char>&&)>::type std::reference_wrapper<sstables::data_consume_rows_context_m>::operator()<seastar::temporary_buffer<char> >(seastar::temporary_buffer<char>&&) const at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/refwrap.h:349
 (inlined by) operator() at ././seastar/include/seastar/core/iostream-impl.hh:208
 (inlined by) seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > seastar::futurize<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > >::invoke<seastar::future<void> seastar::input_stream<char>::consume<std::reference_wrapper<sstables::data_consume_rows_context_m> >(std::reference_wrapper<sstables::data_consume_rows_context_m>&&)::{lambda()#1}&>(std::reference_wrapper<sstables::data_consume_rows_context_m>&&) at ././seastar/include/seastar/core/future.hh:2135
seastar::future<void> seastar::repeat<seastar::future<void> seastar::input_stream<char>::consume<std::reference_wrapper<sstables::data_consume_rows_context_m> >(std::reference_wrapper<sstables::data_consume_rows_context_m>&&)::{lambda()#1}>(std::reference_wrapper<sstables::data_consume_rows_context_m>&&) at ././seastar/include/seastar/core/loop.hh:118
 (inlined by) seastar::future<void> seastar::input_stream<char>::consume<std::reference_wrapper<sstables::data_consume_rows_context_m> >(std::reference_wrapper<sstables::data_consume_rows_context_m>&&) at ././seastar/include/seastar/core/iostream-impl.hh:200
 (inlined by) seastar::future<void> seastar::input_stream<char>::consume<sstables::data_consume_rows_context_m>(sstables::data_consume_rows_context_m&) at ././seastar/include/seastar/core/iostream-impl.hh:236
 (inlined by) data_consumer::continuous_data_consumer<sstables::data_consume_rows_context_m>::consume_input() at ././sstables/consumer.hh:411
 (inlined by) sstables::data_consume_context<sstables::data_consume_rows_context_m>::read() at ./sstables/data_consume_context.hh:95
 (inlined by) operator() at ./sstables/partition.cc:437
 (inlined by) seastar::future<void> seastar::futurize<seastar::future<void> >::invoke<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#2}::operator()() const::{lambda()#1}>(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#2}::operator()() const::{lambda()#1}&&) at ././seastar/include/seastar/core/future.hh:2135
 (inlined by) seastar::future<void> seastar::futurize<seastar::future<void> >::invoke<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#2}::operator()() const::{lambda()#1}>(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#2}::operator()() const::{lambda()#1}&&, seastar::internal::monostate) at ././seastar/include/seastar/core/future.hh:1979
 (inlined by) seastar::future<void> seastar::future<void>::then_impl<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#2}::operator()() const::{lambda()#1}, seastar::future<void> >(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#2}::operator()() const::{lambda()#1}&&) at ././seastar/include/seastar/core/future.hh:1601
 (inlined by) seastar::internal::future_result<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#2}::operator()() const::{lambda()#1}, void>::future_type seastar::internal::call_then_impl<seastar::future<void> >::run<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#2}::operator()() const::{lambda()#1}>(seastar::future<void>&, {lambda()#1}&&) at ././seastar/include/seastar/core/future.hh:1234
 (inlined by) seastar::future<void> seastar::future<void>::then<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#2}::operator()() const::{lambda()#1}, seastar::future<void> >(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#2}::operator()() const::{lambda()#1}&&) at ././seastar/include/seastar/core/future.hh:1520
 (inlined by) operator() at ./sstables/partition.cc:436
 (inlined by) seastar::future<void> seastar::futurize<seastar::future<void> >::invoke<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#2}&>(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#2}&) at ././seastar/include/seastar/core/future.hh:2135
 (inlined by) auto seastar::futurize_invoke<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#2}&>(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#2}&) at ././seastar/include/seastar/core/future.hh:2166
 (inlined by) seastar::future<void> seastar::do_until<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#2}, sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#1}>(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#1}, sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}::operator()() const::{lambda()#2}) at ././seastar/include/seastar/core/loop.hh:336
operator() at ./sstables/partition.cc:431
 (inlined by) seastar::future<void> seastar::futurize<seastar::future<void> >::invoke<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}&>(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}&) at ././seastar/include/seastar/core/future.hh:2135
 (inlined by) auto seastar::futurize_invoke<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}&>(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}&) at ././seastar/include/seastar/core/future.hh:2166
 (inlined by) seastar::future<void> seastar::do_until<sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}, sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#2}>(sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#2}, sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#3}) at ././seastar/include/seastar/core/loop.hh:336
sstables::sstable_mutation_reader<sstables::data_consume_rows_context_m, sstables::mp_row_consumer_m>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ./sstables/partition.cc:423
flat_mutation_reader::impl::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ././flat_mutation_reader.hh:146
 (inlined by) flat_mutation_reader::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ././flat_mutation_reader.hh:320
 (inlined by) mutation_reader_merger::prepare_one(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, mutation_reader_merger::reader_and_last_fragment_kind, seastar::bool_class<mutation_reader_merger::reader_galloping_tag>) at ./mutation_reader.cc:376
operator() at ./mutation_reader.cc:367
 (inlined by) seastar::future<void> seastar::futurize<seastar::future<void> >::invoke<mutation_reader_merger::prepare_next(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_2, mutation_reader_merger::reader_and_last_fragment_kind&>(mutation_reader_merger::prepare_next(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_2&&, mutation_reader_merger::reader_and_last_fragment_kind&) at ././seastar/include/seastar/core/future.hh:2135
 (inlined by) auto seastar::futurize_invoke<mutation_reader_merger::prepare_next(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_2, mutation_reader_merger::reader_and_last_fragment_kind&>(mutation_reader_merger::prepare_next(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_2&&, mutation_reader_merger::reader_and_last_fragment_kind&) at ././seastar/include/seastar/core/future.hh:2166
 (inlined by) seastar::future<void> seastar::parallel_for_each<mutation_reader_merger::reader_and_last_fragment_kind*, mutation_reader_merger::prepare_next(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_2>(mutation_reader_merger::reader_and_last_fragment_kind*, mutation_reader_merger::reader_and_last_fragment_kind*, mutation_reader_merger::prepare_next(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_2&&) at ././seastar/include/seastar/core/loop.hh:549
 (inlined by) seastar::future<void> seastar::internal::parallel_for_each_impl<utils::small_vector<mutation_reader_merger::reader_and_last_fragment_kind, 4ul>&, mutation_reader_merger::prepare_next(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_2>(utils::small_vector<mutation_reader_merger::reader_and_last_fragment_kind, 4ul>&, mutation_reader_merger::prepare_next(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_2&&) at ././seastar/include/seastar/core/loop.hh:593
 (inlined by) seastar::future<void> seastar::futurize<seastar::future<void> >::invoke<seastar::future<void> (*&)(utils::small_vector<mutation_reader_merger::reader_and_last_fragment_kind, 4ul>&, mutation_reader_merger::prepare_next(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_2&&), utils::small_vector<mutation_reader_merger::reader_and_last_fragment_kind, 4ul>&, mutation_reader_merger::prepare_next(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_2>(seastar::future<void> (*&)(utils::small_vector<mutation_reader_merger::reader_and_last_fragment_kind, 4ul>&, mutation_reader_merger::prepare_next(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_2&&), utils::small_vector<mutation_reader_merger::reader_and_last_fragment_kind, 4ul>&, mutation_reader_merger::prepare_next(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_2&&) at ././seastar/include/seastar/core/future.hh:2135
 (inlined by) auto seastar::futurize_invoke<seastar::future<void> (*&)(utils::small_vector<mutation_reader_merger::reader_and_last_fragment_kind, 4ul>&, mutation_reader_merger::prepare_next(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_2&&), utils::small_vector<mutation_reader_merger::reader_and_last_fragment_kind, 4ul>&, mutation_reader_merger::prepare_next(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_2>(seastar::future<void> (*&)(utils::small_vector<mutation_reader_merger::reader_and_last_fragment_kind, 4ul>&, mutation_reader_merger::prepare_next(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_2&&), utils::small_vector<mutation_reader_merger::reader_and_last_fragment_kind, 4ul>&, mutation_reader_merger::prepare_next(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_2&&) at ././seastar/include/seastar/core/future.hh:2166
 (inlined by) seastar::future<void> seastar::parallel_for_each<utils::small_vector<mutation_reader_merger::reader_and_last_fragment_kind, 4ul>&, mutation_reader_merger::prepare_next(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_2>(utils::small_vector<mutation_reader_merger::reader_and_last_fragment_kind, 4ul>&, mutation_reader_merger::prepare_next(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::$_2&&) at ././seastar/include/seastar/core/loop.hh:605
 (inlined by) mutation_reader_merger::prepare_next(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ./mutation_reader.cc:366
mutation_reader_merger::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ./mutation_reader.cc:487
mutation_fragment_merger<mutation_reader_merger>::fetch(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ./mutation_reader.cc:97
 (inlined by) mutation_fragment_merger<mutation_reader_merger>::operator()(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ./mutation_reader.cc:122
 (inlined by) operator() at ./mutation_reader.cc:593
seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > seastar::futurize<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > >::invoke<merging_reader<mutation_reader_merger>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}&>(merging_reader<mutation_reader_merger>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}&) at ././seastar/include/seastar/core/future.hh:2135
 (inlined by) seastar::future<void> seastar::repeat<merging_reader<mutation_reader_merger>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}>(merging_reader<mutation_reader_merger>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}&&) at ././seastar/include/seastar/core/loop.hh:118
 (inlined by) merging_reader<mutation_reader_merger>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ./mutation_reader.cc:592
flat_mutation_reader::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ././flat_mutation_reader.hh:410
 (inlined by) operator() at ././mutation_reader.hh:89
 (inlined by) seastar::future<void> seastar::futurize<seastar::future<void> >::invoke<filtering_reader<flat_mutation_reader::filter>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#2}&>(filtering_reader<flat_mutation_reader::filter>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#2}&) at ././seastar/include/seastar/core/future.hh:2135
 (inlined by) auto seastar::futurize_invoke<filtering_reader<flat_mutation_reader::filter>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#2}&>(filtering_reader<flat_mutation_reader::filter>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#2}&) at ././seastar/include/seastar/core/future.hh:2166
 (inlined by) seastar::future<void> seastar::do_until<filtering_reader<flat_mutation_reader::filter>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#2}, filtering_reader<flat_mutation_reader::filter>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}>(filtering_reader<flat_mutation_reader::filter>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#1}, filtering_reader<flat_mutation_reader::filter>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >)::{lambda()#2}) at ././seastar/include/seastar/core/loop.hh:336
 (inlined by) filtering_reader<flat_mutation_reader::filter>::fill_buffer(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ././mutation_reader.hh:88
void flat_mutation_reader::impl::consume_pausable_in_thread<std::reference_wrapper<flat_mutation_reader::impl::consumer_adapter<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> > > >, flat_mutation_reader::no_filter>(std::reference_wrapper<flat_mutation_reader::impl::consumer_adapter<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> > > >, flat_mutation_reader::no_filter, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ././flat_mutation_reader.hh:185
 (inlined by) auto flat_mutation_reader::impl::consume_in_thread<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> >, flat_mutation_reader::no_filter>(stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> >, flat_mutation_reader::no_filter, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ././flat_mutation_reader.hh:273
auto flat_mutation_reader::consume_in_thread<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> >, flat_mutation_reader::no_filter>(stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> >, flat_mutation_reader::no_filter, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ././flat_mutation_reader.hh:383
auto flat_mutation_reader::consume_in_thread<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> > >(stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer, noop_compacted_fragments_consumer> >, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ././flat_mutation_reader.hh:389
operator() at ./sstables/compaction.cc:614
void std::__invoke_impl<void, seastar::future<void> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>(std::__invoke_other, seastar::future<void> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
 (inlined by) std::__invoke_result<seastar::future<void> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>::type std::__invoke<seastar::future<void> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>(seastar::future<void> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}&&, (seastar::future<void> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}&&)...) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:95
 (inlined by) _ZSt12__apply_implIZZN8sstables10compaction5setupI33noop_compacted_fragments_consumerEEN7seastar6futureIvEET_ENUl20flat_mutation_readerE_clES8_EUlvE_St5tupleIJEEJEEDcOS7_OT0_St16integer_sequenceImJXspT1_EEE at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/tuple:1723
 (inlined by) _ZSt5applyIZZN8sstables10compaction5setupI33noop_compacted_fragments_consumerEEN7seastar6futureIvEET_ENUl20flat_mutation_readerE_clES8_EUlvE_St5tupleIJEEEDcOS7_OT0_ at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/tuple:1734
 (inlined by) seastar::future<void> seastar::futurize<void>::apply<seastar::future<void> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>(seastar::future<void> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}&&, std::tuple<>&&) at ././seastar/include/seastar/core/future.hh:2099
 (inlined by) operator() at ././seastar/include/seastar/core/thread.hh:258
 (inlined by) seastar::noncopyable_function<void ()>::direct_vtable_for<seastar::futurize<std::result_of<std::decay<seastar::future<void> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>::type ()>::type>::type seastar::async<seastar::future<void> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>(seastar::thread_attributes, seastar::future<void> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}&&, (std::decay<seastar::future<void> sstables::compaction::setup<noop_compacted_fragments_consumer>(noop_compacted_fragments_consumer)::{lambda(flat_mutation_reader)#1}::operator()(flat_mutation_reader)::{lambda()#1}>&&)...)::{lambda()#1}>::call(seastar::noncopyable_function<void ()> const*) at ././seastar/include/seastar/util/noncopyable_function.hh:124
seastar::noncopyable_function<void ()>::operator()() const at ./build/release/seastar/./seastar/include/seastar/util/noncopyable_function.hh:209
 (inlined by) seastar::thread_context::main() at ./build/release/seastar/./seastar/src/core/thread.cc:297
```

all the nodes logs can be found [here](https://cloudius-jenkins-test.s3.amazonaws.com/236aac08-9e84-45d6-a707-35c201bbae18/20210101_111802/db-cluster-236aac08.zip)

### PR DESCRIPTION
**Pull request by avikivity**
Whenever we push a fragment, we check whether the buffer is
full and return proceed::no if so, so that the state machine pauses
and lets the consumer continue. This patch adds an additional
condition - if preemption is needed, we also return proceed::no.
This drops us back to the outer loop
(in sstable_mutation_reader::fill_buffer), which will yield to
the reactor as part of seastar::do_until().

Two cases (partition_start and partition_end) did not have the
check for is_buffer_full(); it is added now. This can trigger
is the partition has no rows.

Unlike the previous attempt, push_ready_fragments() is not touched.

The extra preemption opportunities triggered a preexisting bug in
clustering_ranges_walker; it is fixed in the first patch of the series.

I tested this by reading from a large partition with a simple
schema (pk int, ck int, primary key(pk, ck)) with BYPASS CACHE.
However, even without the patch I only got sporadic stalls
with the detector set to 1ms, so it's possible I'm not testing
correctly.

Test: unit (dev, debug, release)

Fixes #7883.

### CODE REVIEW

**Review by nyh — APPROVED** [review]

**Comment by avikivity** [comment]
Changes from v1:
 - added a new patch (patch 1) to address sstable_mutation_test failure in debug mode
 - retested in debug and release modes too (still in progress, but looking good)

File: sstables/mp_row_consumer.hh [hunk 1]
```diff
@@ -82,6 +82,10 @@ public:
     // to the next partition.
     virtual void on_out_of_clustering_range() = 0;
 
+    // Called when a clustering range is exhausted, but more clustering ranges
+    // remain (so a promoted index seek is needed).
+    virtual void on_clustering_range_change() = 0;
```
Comment (tgrabiec) [inline sstables/mp_row_consumer.hh:87]: It seems that you never call it from the ka/la parser.

Comment (tgrabiec) [reply sstables/mp_row_consumer.hh:87]: An omission like this would manifest in lower performance, since it's always ok to not call advance_context(), we have filtering in place.

May be worthwhile to compare perf_fast_forward diff for blatant regressions.

File: sstables/mp_row_consumer.hh [hunk 2]
```diff
@@ -974,6 +978,7 @@ class mp_row_consumer_m : public consumer_m {
                 return proceed::no;
             }
             if (_mf_filter->is_current_range_changed()) {
+                _reader->on_clustering_range_change();
```
Comment (tgrabiec) [inline sstables/mp_row_consumer.hh:981]: I think we're missing `on_clustering_range_change()` calls in some cases. E.g. when slicing a partition without a static row we want to immediately skip without reading the front of the partition. Currently, advance_context() will be called before reading from the data file, which will skip.

File: sstables/partition.cc [hunk 3]
```diff
@@ -433,7 +437,15 @@ class sstable_mutation_reader : public mp_row_consumer_reader {
                     if (is_buffer_full() || _partition_finished || _end_of_stream) {
                         return make_ready_future<>();
                     }
-                    return advance_context(_consumer.maybe_skip()).then([this] {
```
Comment (tgrabiec) [inline sstables/partition.cc:436]: I don't understand why you need this patch. The old code called `maybe_skip()`, which should tell advance_context() to do nothing if skipping wasn't really needed. Maybe the bug was in maybe_skip?

**Review by tgrabiec — CHANGES_REQUESTED** [review]

File: sstables/mp_row_consumer.hh (hunk 1 above)
Comment (avikivity) [reply sstables/mp_row_consumer.hh:87]: I meant to, somehow I missed it. I'll check with p_f_f.

File: sstables/partition.cc (hunk 3 above)
Comment (avikivity) [reply sstables/partition.cc:436]: Possible, I'll check. My understanding of the code is quite weak.

**Comment by avikivity** [comment]
The tests do pass.

File: sstables/partition.cc (hunk 3 above)
Comment (avikivity) [reply sstables/partition.cc:436]: advance_context calls index_reader::advance_to unconditionally:

```c++
    future<> advance_context(std::optional<position_in_partition_view> pos) {
        if (!pos || pos->is_before_all_fragments(*_schema)) {
            return make_ready_future<>();
        }
        assert (_current_partition_key);
        return [this] {
            if (!_index_in_current_partition) {
                _index_in_current_partition = true;
                return get_index_reader().advance_to(*_current_partition_key);
            }
            return make_ready_future();
        }().then([this, pos] {
            return get_index_reader().advance_to(*pos).then([this] {
                index_reader& idx = *_index_reader;
                auto index_position = idx.data_file_positions();
                if (!_context->need_skip(index_position.start)) {
                    return make_ready_future<>();
                }
                return _context->skip_to(idx.element_kind(), index_position.start).then([this, &idx] {
                    _sst->get_stats().on_partition_seek();
                    set_range_tombstone_start_from_end_open_marker(_consumer, *_schema, idx);
                });
            });
        });
    }
```

The first call to advance_to() is conditional, but the second is not.

**Comment by avikivity** [comment]
perf_fast_forward does show an increase in aio in some cases:

(even lines are before, odd lines are after):

```
running: large-partition-forwarding on dataset large-part-ds1
Testing forwarding with clustering restriction in a large partition:
pk-scan   time (s)   iterations     frags     frag/s    mad f/s    max f/s    min f/s    avg aio    aio      (KiB) blocked dropped  idx hit idx miss  idx blk    c hit   c miss    c blk    cpu 
yes       0.000581         1003         2       3441         35       3950        486        4.0      4        133       3       1        0        1        1        0        0        0  14.5% 
yes       0.000693          688         2       2887          9       2930       1368        6.0      6        197       4       2        0        1        1        0        0        0  13.7% 
no        0.000574         1713         2       3482         74       3922        497        4.0      4        133       3       1        0        1        1        0        0        0  14.4% 
no        0.000692         1420         2       2888         15       2960        483        6.0      6        197       4       2        0        1        1        0        0        0  12.9% 
```

and

```
running: large-partition-slicing-clustering-keys on dataset large-part-ds1
Testing slicing of large partition using clustering keys:
offset  read      time (s)   iterations     frags     frag/s    mad f/s    max f/s    min f/s    avg aio    aio      (KiB) blocked dropped  idx hit idx miss  idx blk    c hit   c miss    c blk    cpu 
500000  1         0.000520         1696         1       1924          3       2071        255        4.0      4        133       3       1        0        1        1        0        0        0  13.0% 
500000  1         0.000690         1142         1       1450          4       1509        239        6.0      6        197       4       2        0        1        1        0        0        0  11.4% 
500000  32        0.000523         1854        32      61197        194      61851       8206        4.0      4        133       3       1        0        1        1        0        0        0  14.9% 
500000  32        0.000692         1189        32      46256        101      46584       7666        6.0      6        197       4       2        0        1        1        0        0        0  12.7% 
500000  256       0.000709         1380       256     361134       1250     364805      61262        5.0      5        165       4       1        0        1        1        0        0        0  20.6% 
500000  256       0.000885          827       256     289160        717     290734     221382        7.0      7        229       5       2        0        1        1        0        0        0  18.3% 
500000  4096      0.002823          424      4096    1451059      85137    2222133     748942       15.2     18        581      17       1        0        1        1        0        0        0  44.7% 
500000  4096      0.003066          329      4096    1335927      43031    2125532     659387       19.6     20        645      18       2        0        1        1        0        0        0  41.0% 

```

File: sstables/partition.cc (hunk 3 above)
Comment (avikivity) [reply sstables/partition.cc:436]: Actually, there's an early return up front. So maybe_skip() should have been enough.

Comment (avikivity) [reply sstables/partition.cc:436]: > I don't understand why you need this patch. The old code called `maybe_skip()`, which should tell advance_context() to do nothing if skipping wasn't really needed. Maybe the bug was in maybe_skip?

You were right, the regressions in perf_fast_forward disappear with patch 1 removed. But I get a failure in sstable_mutation_tests's test_no_index_reads_when_rows_fall_into_range_boundaries. Maybe it's a false positive?

Comment (avikivity) [reply sstables/partition.cc:436]: (the regression only appears in debug mode, presumably due to higher chances of preemption)

Comment (avikivity) [reply sstables/partition.cc:436]: Also appears in release mode with task quota set to 5us. But, it looks to me like a true positive, which I can't explain if maybe_skip() is correct.

Comment (tgrabiec) [reply sstables/partition.cc:436]: If you share the test log with the failure maybe I can guess something.

Comment (avikivity) [reply sstables/partition.cc:436]:
```c++
            auto before = index_accesses();

            {
                assert_that(ms.make_reader(s, tests::make_permit()))
                    .produces(m1)
                    .produces(m2)
                    .produces_end_of_stream();

                BOOST_REQUIRE_EQUAL(index_accesses(), before);
            }
```

index_accesses() = 2, before == 0

Later I'll generate a trace-level log, see if I find anything, and post it here.

**Comment by avikivity** [comment]
```TRACE 2021-01-26 12:26:27,040 [shard 0] sstable - index 0x601000141a40: index_reader for /tmp/scylla-fc9fdc0b-6a2a-4fd4-87a4-bf67d33d3b20/mc-1-big-Data.db
TRACE 2021-01-26 12:26:27,040 [shard 0] sstable - index 0x601000141a40: advance_to_end() bound 0x601000141b08
TRACE 2021-01-26 12:26:27,040 [shard 0] sstable - reader 0x6010001edf00: reading partition
TRACE 2021-01-26 12:26:27,040 [shard 0] sstable - reader 0x6010001edf00: read from data file
TRACE 2021-01-26 12:26:27,040 [shard 0] io - dev 0 : req 0x6010001f1500 queue  len 4096 ticket 128:1024
TRACE 2021-01-26 12:26:27,040 [shard 0] io - dev 0 : req 0x6010001f1500 submit
TRACE 2021-01-26 12:26:27,040 [shard 0] io - dev 0 : req 0x6010001f1500 complete
TRACE 2021-01-26 12:26:27,040 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_partition_start(deltime=(2147483647, -9223372036854775808)), _is_mutation_end=true
TRACE 2021-01-26 12:26:27,040 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: setup_for_partition(pk{000401000000})
TRACE 2021-01-26 12:26:27,040 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_static_row_start()
TRACE 2021-01-26 12:26:27,040 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_row_end(_in_progress_static_row={static_row: {row: }})
TRACE 2021-01-26 12:26:27,040 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_row_start(ckp{000c636b30303030303030303031})
TRACE 2021-01-26 12:26:27,040 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: emit
TRACE 2021-01-26 12:26:27,040 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_row_marker_and_tombstone({row_marker: }, {tombstone: none}, {tombstone: none}), key={position: clustered,ckp{000c636b30303030303030303031},0}
TRACE 2021-01-26 12:26:27,040 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_column(id={0}, path=, value=76, ts=-9223372036854775807, ttl=0, del_time=9223372036854775807, deleted=false)
TRACE 2021-01-26 12:26:27,040 [shard 0] sstable - index 0x601000141a40: advance_to({position: clustered,ckp{},-1}), current data_file_pos=0
TRACE 2021-01-26 12:26:27,040 [shard 0] sstable - index 0x601000141a40: advance_to_page(0), bound 0x601000141aa0
TRACE 2021-01-26 12:26:27,041 [shard 0] io - dev 0 : req 0x6010001f1500 queue  len 4096 ticket 128:1024
TRACE 2021-01-26 12:26:27,041 [shard 0] io - dev 0 : req 0x6010001f1500 submit
TRACE 2021-01-26 12:26:27,041 [shard 0] io - dev 0 : req 0x6010001f1500 complete
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - 0x601000306e38: pos 0 state START
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - 0x601000306e38: exit pos 0 state KEY_SIZE
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - 0x601000306e38: pos 0 state KEY_SIZE
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - 0x601000306e38: pos 2 state KEY_BYTES
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - 0x601000306e38: pos 6 state POSITION
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - 0x601000306e38: pos 7 state PROMOTED_SIZE
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - 0x601000306e38: pos 8 state PARTITION_HEADER_LENGTH_1
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - 0x601000306e38: pos 8 state CONSUME_ENTRY size 0
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - 0x601000306e38: exit pos 8 state START
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - 0x601000306e38: pos 8 state START
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - 0x601000306e38: exit pos 8 state KEY_SIZE
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - 0x601000306e38: pos 8 state KEY_SIZE
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - 0x601000306e38: pos 10 state KEY_BYTES
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - 0x601000306e38: pos 14 state POSITION
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - 0x601000306e38: pos 15 state PROMOTED_SIZE
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - 0x601000306e38: pos 16 state PARTITION_HEADER_LENGTH_1
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - 0x601000306e38: pos 16 state CONSUME_ENTRY size 0
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - 0x601000306e38: exit pos 16 state START
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - 0x601000306e38: pos 16 state START
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - 0x601000306e38: exit pos 16 state KEY_SIZE
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - index 0x601000141a40 bound 0x601000141aa0: page:
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable -   {key: pk{000401000000}, token:-8604791237420463362} -> 0
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable -   {key: pk{000400000000}, token:-3485513579396041028} -> 108
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - index 0x601000141a40: page done
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - index 0x601000141a40: advance_to({position: clustered,ckp{},-1}), current data_file_pos=0
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - index 0x601000141a40: no promoted index
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_row_start(ckp{000c636b30303030303030303032})
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: emit
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_row_marker_and_tombstone({row_marker: }, {tombstone: none}, {tombstone: none}), key={position: clustered,ckp{000c636b30303030303030303032},0}
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_column(id={0}, path=, value=76, ts=-9223372036854775806, ttl=0, del_time=9223372036854775807, deleted=false)
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_row_start(ckp{000c636b30303030303030303035})
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: emit
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_row_marker_and_tombstone({row_marker: }, {tombstone: none}, {tombstone: none}), key={position: clustered,ckp{000c636b30303030303030303035},0}
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_column(id={0}, path=, value=76, ts=-9223372036854775805, ttl=0, del_time=9223372036854775807, deleted=false)
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_row_start(ckp{000c636b30303030303030303036})
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: emit
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_row_marker_and_tombstone({row_marker: }, {tombstone: none}, {tombstone: none}), key={position: clustered,ckp{000c636b30303030303030303036},0}
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_column(id={0}, path=, value=76, ts=-9223372036854775804, ttl=0, del_time=9223372036854775807, deleted=false)
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_partition_end()
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_partition_start(deltime=(2147483647, -9223372036854775808)), _is_mutation_end=true
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: setup_for_partition(pk{000400000000})
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_static_row_start()
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_column(id={0}, path=, value=7376616c7565, ts=-9223372036854775803, ttl=0, del_time=9223372036854775807, deleted=false)
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_row_end(_in_progress_static_row={static_row: {row: 
      {s1, { atomic_cell{svalue,ts=-9223372036854775803,expiry=-1,ttl=0} }}}})
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_row_start(ckp{000c636b30303030303030303032})
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: emit
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_row_marker_and_tombstone({row_marker: }, {tombstone: none}, {tombstone: none}), key={position: clustered,ckp{000c636b30303030303030303032},0}
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_column(id={0}, path=, value=76, ts=-9223372036854775802, ttl=0, del_time=9223372036854775807, deleted=false)
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_row_start(ckp{000c636b30303030303030303035})
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: emit
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_row_marker_and_tombstone({row_marker: }, {tombstone: none}, {tombstone: none}), key={position: clustered,ckp{000c636b30303030303030303035},0}
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_column(id={0}, path=, value=76, ts=-9223372036854775801, ttl=0, del_time=9223372036854775807, deleted=false)
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_row_start(ckp{000c636b30303030303030303036})
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: emit
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_row_marker_and_tombstone({row_marker: }, {tombstone: none}, {tombstone: none}), key={position: clustered,ckp{000c636b30303030303030303036},0}
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_column(id={0}, path=, value=76, ts=-9223372036854775800, ttl=0, del_time=9223372036854775807, deleted=false)
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_partition_end()
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - reader 0x6010001edf00: reading partition
TRACE 2021-01-26 12:26:27,041 [shard 0] sstable - reader 0x6010001edf00: read from data file
TRACE 2021-01-26 12:26:27,041 [shard 0] testlog - Expecting end of stream
test/boost/sstable_mutation_test.cc(1372): fatal error: in "test_no_index_reads_when_rows_fall_into_range_boundaries": critical check index_accesses() == before has failed [2 != 0]
```

**Comment by avikivity** [comment]
I added trace messages to mutation_fragment_filter::maybe_skip:

```
RACE 2021-01-26 12:37:28,493 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_row_start(ckp{000c636b30303030303030303032})
TRACE 2021-01-26 12:37:28,493 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: emit
TRACE 2021-01-26 12:37:28,493 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_row_marker_and_tombstone({row_marker: }, {tombstone: none}, {tombstone: none}), key={position: clustered,ckp{000c636b30303030303030303032},0}
TRACE 2021-01-26 12:37:28,493 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_column(id={0}, path=, value=76, ts=-9223372036854775806, ttl=0, del_time=9223372036854775807, deleted=false)
TRACE 2021-01-26 12:37:28,493 [shard 0] sstable - maybe_skip: current range unchanged, no skip
TRACE 2021-01-26 12:37:28,493 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_row_start(ckp{000c636b30303030303030303035})
TRACE 2021-01-26 12:37:28,493 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: emit
TRACE 2021-01-26 12:37:28,493 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_row_marker_and_tombstone({row_marker: }, {tombstone: none}, {tombstone: none}), key={position: clustered,ckp{000c636b30303030303030303035},0}
TRACE 2021-01-26 12:37:28,493 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_column(id={0}, path=, value=76, ts=-9223372036854775805, ttl=0, del_time=9223372036854775807, deleted=false)
TRACE 2021-01-26 12:37:28,493 [shard 0] sstable - maybe_skip: current range unchanged, no skip
TRACE 2021-01-26 12:37:28,493 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_row_start(ckp{000c636b30303030303030303036})
TRACE 2021-01-26 12:37:28,493 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: emit
TRACE 2021-01-26 12:37:28,493 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_row_marker_and_tombstone({row_marker: }, {tombstone: none}, {tombstone: none}), key={position: clustered,ckp{000c636b30303030303030303036},0}
TRACE 2021-01-26 12:37:28,493 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_column(id={0}, path=, value=76, ts=-9223372036854775804, ttl=0, del_time=9223372036854775807, deleted=false)
TRACE 2021-01-26 12:37:28,493 [shard 0] sstable - maybe_skip: current range unchanged, no skip
TRACE 2021-01-26 12:37:28,493 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_partition_end()
TRACE 2021-01-26 12:37:28,493 [shard 0] sstable - reader 0x6010001edf00: reading partition
TRACE 2021-01-26 12:37:28,493 [shard 0] sstable - reader 0x6010001edf00: read from data file
TRACE 2021-01-26 12:37:28,493 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: consume_partition_start(deltime=(2147483647, -9223372036854775808)), _is_mutation_end=true
TRACE 2021-01-26 12:37:28,493 [shard 0] sstable - mp_row_consumer_m 0x6010001edfb0: setup_for_partition(pk{000400000000})
TRACE 2021-01-26 12:37:28,493 [shard 0] sstable - maybe_skip: {position: static_row,null,0}
```

**Comment by avikivity** [comment]
It is odd that maybe_skip() returned a positive immediately after setup_for_partition(), which initializes _mf_filter and the associated clustering_range_walker.

**Comment by avikivity** [comment]
I added more logging. Diff between a bad and a good run:

```
+sstable - is_current_range_changed: 0 1
+sstable - maybe_skip: {position: static_row,null,0}
```

We got preempted, and maybe_skip told us to skip in the bad run, but we didn't go to the index (likely since this is the beginning of the partition).

```
 sstable - mp_row_consumer_m 0x6010001edfb0: consume_static_row_start()
 sstable - mp_row_consumer_m 0x6010001edfb0: consume_row_end(_in_progress_static_row={static_row: {row: }})
+sstable - is_current_range_changed: 1 1
+sstable - maybe_skip: current range unchanged, no skip
```

Preempted after the static row, correctly told not to skip.

```
 sstable - mp_row_consumer_m 0x6010001edfb0: consume_row_start(ckp{000c636b30303030303030303031})
 sstable - clustering_range_walker: advance_to (entry)
 sstable - clustering_range_walker: advance_to_next_range (entry)
@@ -598,215 +602,75 @@
 sstable - mp_row_consumer_m 0x6010001edfb0: emit
 sstable - mp_row_consumer_m 0x6010001edfb0: consume_row_marker_and_tombstone({row_marker: }, {tombstone: none}, {tombstone: none}), key={position: clustered,ckp{000c636b30303030303030303031},0}
 sstable - mp_row_consumer_m 0x6010001edfb0: consume_column(id={0}, path=, value=76, ts=-9223372036854775807, ttl=0, del_time=9223372036854775807, deleted=false)
+sstable - is_current_range_changed: 1 2
+sstable - maybe_skip: {position: clustered,ckp{},-1}
```

Preempted after the first clustering row, told to skip.

```
+sstable - index 0x601000141a40: advance_to({position: clustered,ckp{},-1}), current data_file_pos=0
+sstable - index 0x601000141a40: advance_to_page(0), bound 0x601000141aa0
```

That's the skip.

**Comment by avikivity** [comment]
This is the culprit:

```c++
            , _current_start(position_in_partition_view::for_static_row())
            , _current_end(position_in_partition_view::before_all_clustered_rows()) {
```

current_end needlessly splits the infinite clustering range into two.

**Comment by avikivity** [comment]
Victory! (unless I caused 82,112 new regressions)

**Comment by avikivity** [comment]
Updated:
 - dropped patch to communicate skips from parser to sstable_mutation_reader, since mutation_fragment_filter::maybe_skip() already does that
 -  fixed bug in clustering_ranges_walker, where a static row and a clustering interval with -inf as its left bound were processed as two separate ranges (new patch 1)

**Comment by avikivity** [comment]
The new tests failed in debug mode, since clustering_ranges_walker accepts its ranges argument by reference, and I supplied it by value. I dequeued it. The fix is trivial, but will retest everything to avoid more embarrassment.

**Comment by avikivity** [comment]
Updated:
 - rebased
 - changed clustering_ranges_walker ranges parameter to not be a temporary
 - retested (debug, dev, release)
