### PR TITLE
Handle termination signals during streaming

### LINKED ISSUE #4167: Failed to smoothly upgrade old trusty scylla packages after OS upgrade (ubuntu 14.04 to 16.04)
*Installation details*
Scylla version (or git commit hash): 3.0.1-0.20190129.9ba608cae-0ubuntu1~trusty
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 14.04/Ubuntu16.04

* Description:
  Failed to smoothly upgrade old trusty scylla packages after OS upgrade.
  Scylla was installed on Ubuntu 14.04, after upgraded OS to 16.04. I tried to upgrade scylla packages by `apt-get dist-upgrade scylla`, failed.

```
scylla-test@amos-ubuntu14-upgrade-16-test3:~$ sudo curl https://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/ubuntu/9ba608cae494bf343c337bfd665343299bd37e35-be11c2d920059618128ed8b4de9c19a01c6012ed-8c41fdbf164d6ce30ec00f48053c69d6fd66c89b/93/scylladb-3.0/scylla.list -L -o /etc/apt/sources.list.d/scylla.list
scylla-test@amos-ubuntu14-upgrade-16-test3:~$ sudo apt-get update
Hit:1 http://us-east1.gce.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://us-east1.gce.archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]                                                                        
Get:3 http://us-east1.gce.archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]                                                                      
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]                                                                                                                                         
Hit:5 http://archive.canonical.com/ubuntu xenial InRelease                                
Get:6 http://ppa.launchpad.net/scylladb/ppa/ubuntu xenial InRelease [24.3 kB]             
Get:7 http://us-east1.gce.archive.ubuntu.com/ubuntu xenial-updates/main Sources [329 kB]                                                   
Get:8 http://downloads.scylladb.com/deb/unstable/xenial/9ba608cae494bf343c337bfd665343299bd37e35-be11c2d920059618128ed8b4de9c19a01c6012ed-8c41fdbf164d6ce30ec00f48053c69d6fd66c89b/91/scylladb-3.0 xenial InRelease [3,278 B]
Get:9 http://us-east1.gce.archive.ubuntu.com/ubuntu xenial-updates/universe Sources [242 kB]                          
Get:10 http://us-east1.gce.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [902 kB]                 
Get:11 http://us-east1.gce.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [722 kB]               
Get:12 http://us-east1.gce.archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [297 kB]               
Ign:8 http://downloads.scylladb.com/deb/unstable/xenial/9ba608cae494bf343c337bfd665343299bd37e35-be11c2d920059618128ed8b4de9c19a01c6012ed-8c41fdbf164d6ce30ec00f48053c69d6fd66c89b/91/scylladb-3.0 xenial InRelease
Get:13 http://downloads.scylladb.com/deb/unstable/xenial/9ba608cae494bf343c337bfd665343299bd37e35-be11c2d920059618128ed8b4de9c19a01c6012ed-8c41fdbf164d6ce30ec00f48053c69d6fd66c89b/91/scylladb-3.0 xenial/multiverse amd64 Packages [2,832 B]
Get:14 http://ppa.launchpad.net/scylladb/ppa/ubuntu xenial/main amd64 Packages [25.0 kB]             
Get:15 http://security.ubuntu.com/ubuntu xenial-security/universe Sources [95.5 kB]
Get:16 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [416 kB]           
Get:17 http://ppa.launchpad.net/scylladb/ppa/ubuntu xenial/main Translation-en [14.0 kB]
Get:18 http://security.ubuntu.com/ubuntu xenial-security/universe Translation-en [165 kB]
Fetched 3,562 kB in 1s (2,462 kB/s)      
Reading package lists... Done
W: GPG error: http://downloads.scylladb.com/deb/unstable/xenial/9ba608cae494bf343c337bfd665343299bd37e35-be11c2d920059618128ed8b4de9c19a01c6012ed-8c41fdbf164d6ce30ec00f48053c69d6fd66c89b/91/scylladb-3.0 xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 17723034C56D4B19
W: The repository 'http://downloads.scylladb.com/deb/unstable/xenial/9ba608cae494bf343c337bfd665343299bd37e35-be11c2d920059618128ed8b4de9c19a01c6012ed-8c41fdbf164d6ce30ec00f48053c69d6fd66c89b/91/scylladb-3.0 xenial InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

```
scylla-test@amos-ubuntu14-upgrade-16-test3:~$ sudo apt-get dist-upgrade scylla
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt-get -f install' to correct these.
The following packages have unmet dependencies:
 scylla-gcc73-libatomic1 : Depends: scylla-gcc73-gcc-7-base (= 7.3.0-3ubuntu2~trustyppa1) but 7.3.0-3ubuntu2~xenialppa1 is installed
 scylla-gcc73-libgcc1 : Depends: scylla-gcc73-gcc-7-base (= 7.3.0-3ubuntu2~trustyppa1) but 7.3.0-3ubuntu2~xenialppa1 is installed
E: Unmet dependencies. Try using -f.
scylla-test@amos-ubuntu14-upgrade-16-test3:~$ 
```

Solve the conflict by remove scylla-gcc73* packages first, then execite `apt-get dist-upgrade scylla`

```
scylla-test@amos-ubuntu14-upgrade-16-test3:~$ dpkg -l |grep scylla
ii  scylla-conf                         3.0.1-0.20190129.9ba608cae-0ubuntu1~trusty amd64        Scylla database main configuration file
ii  scylla-env                          1.3-ubuntu1~trustyppa1                     all          language tool for constructing recognizers, compilers etc
ii  scylla-gcc73-gcc-7-base:amd64       7.3.0-3ubuntu2~xenialppa1                  amd64        GCC, the GNU Compiler Collection (base package)
ii  scylla-gcc73-libatomic1             7.3.0-3ubuntu2~trustyppa1                  amd64        support library providing __atomic built-in functions
ii  scylla-gcc73-libgcc1                1:7.3.0-3ubuntu2~trustyppa1                amd64        GCC support library
ii  scylla-gcc73-libstdc++6             7.3.0-3ubuntu2~xenialppa1                  amd64        GNU Standard C++ Library v3
rc  scylla-jmx                          3.0.1-20190129.be11c2d-0ubuntu1~trusty     all          Scylla JMX server binaries
ii  scylla-kernel-conf                  3.0.1-0.20190129.9ba608cae-0ubuntu1~trusty amd64        Scylla kernel tuning configuration
rc  scylla-server                       3.0.1-0.20190129.9ba608cae-0ubuntu1~trusty amd64        Scylla database server binaries
ii  scylla-tools                        3.0.1-20190129.8c41fdbf16-0ubuntu1~trusty  all          Scylla database tools
ii  scylla-tools-core                   3.0.1-20190129.8c41fdbf16-0ubuntu1~trusty  all          Scylla database tools core files
scylla-test@amos-ubuntu14-upgrade-16-test3:~$ sudo apt-get remove scylla-gcc73\*
Removing scylla-gcc73-libatomic1 (7.3.0-3ubuntu2~trustyppa1) ...
Removing scylla-gcc73-libstdc++6 (7.3.0-3ubuntu2~xenialppa1) ...
Removing scylla-gcc73-libgcc1 (1:7.3.0-3ubuntu2~trustyppa1) ...
Removing scylla-gcc73-gcc-7-base:amd64 (7.3.0-3ubuntu2~xenialppa1) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
scylla-test@amos-ubuntu14-upgrade-16-test3:~$ dpkg -l |grep scylla
ii  scylla-conf                         3.0.1-0.20190129.9ba608cae-0ubuntu1~trusty amd64        Scylla database main configuration file
ii  scylla-env                          1.3-ubuntu1~trustyppa1                     all          language tool for constructing recognizers, compilers etc
rc  scylla-gcc73-libatomic1             7.3.0-3ubuntu2~trustyppa1                  amd64        support library providing __atomic built-in functions
rc  scylla-gcc73-libgcc1                1:7.3.0-3ubuntu2~trustyppa1                amd64        GCC support library
rc  scylla-jmx                          3.0.1-20190129.be11c2d-0ubuntu1~trusty     all          Scylla JMX server binaries
ii  scylla-kernel-conf                  3.0.1-0.20190129.9ba608cae-0ubuntu1~trusty amd64        Scylla kernel tuning configuration
rc  scylla-server                       3.0.1-0.20190129.9ba608cae-0ubuntu1~trusty amd64        Scylla database server binaries
ii  scylla-tools                        3.0.1-20190129.8c41fdbf16-0ubuntu1~trusty  all          Scylla database tools
ii  scylla-tools-core                   3.0.1-20190129.8c41fdbf16-0ubuntu1~trusty  all          Scylla database tools core files
scylla-test@amos-ubuntu14-upgrade-16-test3:~$ sudo apt-get dist-upgrade scylla
```

### LINKED ISSUE #4501: Impossible to gracefully stop scylla in the middle of bootstrapping
*Installation details*
HEAD: 285ada503557c367ae32aa4111091c01edaefb00
Cluster size: 4 = 3 + 1 (bootstrapping)

*Description*
scylla doesn't react to any signal when node is in the middle of bootstrapping.
The only way to stop scylla in this case is `kill -9`.

Reproducible with a 3 nodes `ccm` cluster when you add a new node to it and try to issue a `ccm node4 stop` command before the bootstrapping node finished joining.

This is a regression introduced but this patch.

```
commit b19792405faee91ed9410357dc41b7cda648690f
Author: Avi Kivity <avi@scylladb.com>
Date:   Sat Apr 20 20:57:33 2019 +0300

    main: RAII-ify shutdown
    
    Instead of app-template::run_deprecated() and at_exit() hooks, use
    app_template::run() and RAII (via defer()) to stop services. This makes it
    easier to add services that do support shutdown correctly.
    
    Ref #2737
    Message-Id: <20190420175733.29454-1-avi@scylladb.com>
```

### LINKED ISSUE #4674: SIGTERM handler runs only after the init process finishes
In dtest update_cluster_layout_tests.py:TestUpdateClusterLayout.remove_node_from_gossip_test,

start n1, n2, n3
start n4
when n4 starts to stream stop n4

n1, n2, n3 are supposed to see n4 aborts the bootstrap process

However, n4 will not abort the bootstrap after receiving the SIGTERM signal . n4 will run the SIGTERM singal handler (shutdown process) until the init process finishes. 

Suspected commit:
```
commit b19792405faee91ed9410357dc41b7cda648690f (issue.4333.second)
Author: Avi Kivity <avi@scylladb.com>
Date:   Sat Apr 20 20:57:33 2019 +0300

    main: RAII-ify shutdown
    
    Instead of app-template::run_deprecated() and at_exit() hooks, use
    app_template::run() and RAII (via defer()) to stop services. This makes it
    easier to add services that do support shutdown correctly.
    
    Ref #2737
    Message-Id: <20190420175733.29454-1-avi@scylladb.com>
```

Log shows signal handler is called after init is done:
```
3847 INFO  2019-07-09 12:52:33,595 [shard 0] init - serving
3848 INFO  2019-07-09 12:52:33,595 [shard 0] init - Scylla version 666.development-0.20190709.b80306cbef initialization completed.
3849 INFO  2019-07-09 12:52:33,595 [shard 0] init - Signal received; shutting down
3850 INFO  2019-07-09 12:52:33,595 [shard 0] init - stopping compaction manager
3851 INFO  2019-07-09 12:52:33,595 [shard 0] compaction_manager - Asked to stop
3852 INFO  2019-07-09 12:52:33,595 [shard 0] compaction_manager - Stopped
3853 INFO  2019-07-09 12:52:33,595 [shard 0] init - stopping view builder
3854 INFO  2019-07-09 12:52:33,595 [shard 0] view - Stopping view builder
3855 INFO  2019-07-09 12:52:33,595 [shard 0] init - draining local storage
3856 INFO  2019-07-09 12:52:33,595 [shard 0] storage_service - Drain on shutdown: starts
3857 INFO  2019-07-09 12:52:33,595 [shard 0] storage_service - Stop transport: starts
3858 INFO  2019-07-09 12:52:33,595 [shard 0] storage_service - Thrift server stopped
3859 INFO  2019-07-09 12:52:33,596 [shard 0] storage_service - CQL server stopped
3860 INFO  2019-07-09 12:52:33,596 [shard 0] storage_service - Stop transport: shutdown rpc and cql server done
3861 INFO  2019-07-09 12:52:33,596 [shard 0] gossip - My status = NORMAL
3862 INFO  2019-07-09 12:52:33,596 [shard 0] gossip - Announcing shutdown
3863 INFO  2019-07-09 12:52:33,596 [shard 0] storage_service - Node 127.0.0.4 state jump to normal
3864 INFO  2019-07-09 12:52:35,617 [shard 0] storage_service - Stop transport: stop_gossiping done
3865 INFO  2019-07-09 12:52:35,618 [shard 0] storage_service - messaging_service stopped
3866 INFO  2019-07-09 12:52:35,618 [shard 0] storage_service - Stop transport: shutdown messaging_service done
3867 INFO  2019-07-09 12:52:35,618 [shard 0] storage_service - stream_manager stopped
3868 INFO  2019-07-09 12:52:35,618 [shard 0] storage_service - Stop transport: shutdown stream_manager done
3869 INFO  2019-07-09 12:52:35,618 [shard 0] storage_service - Stop transport: auth shutdown
3870 INFO  2019-07-09 12:52:35,618 [shard 0] storage_service - Stop transport: done
3871 INFO  2019-07-09 12:52:35,618 [shard 0] storage_service - Drain on shutdown: stop_transport done
3872 INFO  2019-07-09 12:52:35,618 [shard 0] tracing - Asked to shut down
3873 INFO  2019-07-09 12:52:35,618 [shard 0] tracing - Tracing is down
3874 INFO  2019-07-09 12:52:35,618 [shard 0] storage_service - Drain on shutdown: tracing is stopped
3875 INFO  2019-07-09 12:52:35,618 [shard 0] storage_service - Drain on shutdown: system distributed keyspace stopped
3876 INFO  2019-07-09 12:52:35,618 [shard 0] hints_manager - Asked to stop
3877 INFO  2019-07-09 12:52:35,618 [shard 0] hints_manager - Stopped
3878 INFO  2019-07-09 12:52:35,618 [shard 0] storage_service - Drain on shutdown: hints manager is stopped
3879 INFO  2019-07-09 12:52:35,650 [shard 0] storage_service - Drain on shutdown: flush column_families done
3880 INFO  2019-07-09 12:52:35,652 [shard 0] storage_service - Drain on shutdown: shutdown commitlog done
3881 INFO  2019-07-09 12:52:35,652 [shard 0] storage_service - Drain on shutdown: done
3882 INFO  2019-07-09 12:52:35,652 [shard 0] init - stopping view update generator
3883 INFO  2019-07-09 12:52:35,652 [shard 0] init - stopping repair
3884 INFO  2019-07-09 12:52:35,652 [shard 0] repair - Starting shutdown of repair
3885 INFO  2019-07-09 12:52:35,652 [shard 0] repair - Completed shutdown of repair
3886 INFO  2019-07-09 12:52:35,652 [shard 0] init - stopping view update backlog broker
3887 INFO  2019-07-09 12:52:35,652 [shard 0] init - stopping cf cache hit rate calculator
3888 INFO  2019-07-09 12:52:35,652 [shard 0] init - stopping load broadcaster
3889 INFO  2019-07-09 12:52:35,652 [shard 0] init - Shutdown database started
3890 INFO  2019-07-09 12:52:35,652 [shard 0] init - Shutdown database finished
3891 INFO  2019-07-09 12:52:35,652 [shard 0] init - stopping prometheus API server
3892 INFO  2019-07-09 12:52:35,652 [shard 0] init - Scylla version 666.development-0.20190709.b80306cbef shutdown complete.

```

### PR DESCRIPTION
**Pull request by avikivity**
In b19792405faee91e, we changed the shutdown process not to rely on the global reactor-defined exit, but instead added a local variable to hold the shutdown state. However, we did not propagate that state everywhere, and now streaming processes are not able to abort.

Fix that by enhancing stop_signal with a sharded<abort_source> member that can be propagated to services. Propagate it to storage_service and thence to boot_strapper and range_streamer so that streaming processes can be aborted.

Fixes #4674
Fixes #4501 

Tests: unit (dev), manual bootstrap test

### CODE REVIEW

File: dht/range_streamer.cc [hunk 1]
```diff
@@ -269,7 +269,8 @@ future<> range_streamer::stream_async() {
                 break;
             } catch (...) {
                 logger.warn("{} failed to stream. Will retry in {} seconds ...", _description, sleep_time);
-                sleep_abortable(std::chrono::seconds(sleep_time)).get();
+                _abort_source.check();
```
Comment (tgrabiec) [inline dht/range_streamer.cc]: doesn't sleep_abortable() already check this?

**Comment by asias** [comment]
FYI, https://github.com/scylladb/scylla/issues/4674.

**Comment by asias** [comment]
How does this series fix the "upgrade" issue #4167?

File: main.cc [hunk 2]
```diff
@@ -84,30 +84,47 @@ void register_tracing_keyspace_backend(backend_registry& br);
...
+        });
     }
 public:
     stop_signal() {
+        _abort_sources.start().get();
         engine().handle_signal(SIGINT, [this] { signaled(); });
         engine().handle_signal(SIGTERM, [this] { signaled(); });
     }
     ~stop_signal() {
+        _cond.broadcast();
```
[the remark this answers is not in the document]
Comment (avikivity) [reply main.cc]: Not needed. It is a remnant of a different mechanism to stop the loop that broadcasted aborts to all shards (in the end, I found that I had if (!_caught) { return } instead of if (_caught) { return }, and that the original broadcast mechanism was fine.

I'll remove this bit.

File: main.cc [hunk 3]
```diff
@@ -84,30 +84,47 @@ void register_tracing_keyspace_backend(backend_registry& br);
 
 }
 
+// Must live in a seastar::thread
 class stop_signal {
     bool _caught = false;
     condition_variable _cond;
+    sharded<abort_source, plain_sharded_traits<abort_source>> _abort_sources;
+    //future<> _broadcasts_to_abort_sources_done = broadcast_loop();
```
[the remark this answers is not in the document]
Comment (avikivity) [reply main.cc]: yes (in fact the one I described earlier), will remove

File: dht/range_streamer.cc (hunk 1 above)
Comment (avikivity) [reply dht/range_streamer.cc]: It does not, AFAICT.

**Comment by avikivity** [comment]
I meant #4674, don't know how I typo'ed it so badly.

**Comment by avikivity** [comment]
Updated. Changes
 - removed remnants of older cross-shard broadcast that was only partially removed during development
 - removed chatty log message leftover from development
 - corrected issue number in cover letter

**Comment by bhalevy** [comment]
@espindola please review as well (remotely related to #4384)

**Comment by avikivity** [comment]
Added reference to #4501 too

File: dht/range_streamer.cc (hunk 1 above)
Comment (tgrabiec) [reply dht/range_streamer.cc]: `sleep_abortable()` constructs a `sleeper` object which calls `as.subscribe()` and if that returns a disengaged optional then it won't arm the timer but resolve with an exception instead. `abort_source::subscribe()` checks for `abort_requested()` and if so returns a disengaged optional.

So it seems that `sleep_abortable()` already aborts immediately when the abort_source is aborted, so calling `check()` before it seems not necessary.

Comment (avikivity) [reply dht/range_streamer.cc]: Yes. I looked at it but misread it (and the behavior is expected). I'll remove the checks.

**Comment by avikivity** [comment]
Updated:
 - remove redundant abort_source::check() when calling sleep_abortable() right after.

**Comment by gleb-cloudius** [comment]
On Tue, Jul 09, 2019 at 11:27:10AM -0700, Avi Kivity wrote:
> Fix that by enhancing stop_signal with a sharded<abort_source> member that can be propagated to services. Propagate it to storage_proxy and thence to boot_strapper and range_streamer so that streaming processes can be aborted.
You mean storage_service, not storage_proxy, no?

--
			Gleb.

**Comment by avikivity** [comment]
> On Tue, Jul 09, 2019 at 11:27:10AM -0700, Avi Kivity wrote: Fix that by enhancing stop_signal with a sharded<abort_source> member that can be propagated to services. Propagate it to storage_proxy and thence to boot_strapper and range_streamer so that streaming processes can be aborted.
> You mean storage_service, not storage_proxy, no?


Yes, updated.

**Comment by espindola** [comment]
Benny Halevy <notifications@github.com> writes:

> @espindola please review as well (remotely related to #4384)

The general idea LGTM, I don't know the codebase well enough to say what
the best lines for adding calls to check() are.

Tests would be nice, if they are not too hard to do. Sending a signal to
self via a callback might do the trick, but if there is no handy
callback already, no need to add one just for testing.

Cheers,
Rafael

**Comment by slivne** [comment]
@avikivity - is anything left ? if not @tgrabiec can you merge

**Comment by tgrabiec** [comment]
I cannot merge it because it has this note:

> Note: do not merge, depends on unreviewed/unmerged seastar patch for plain_sharded_traits.

**Comment by avikivity** [comment]
Updated. Changes:
 - rebased around seastar commit to accept sharded services without stop()
 - adjusted code to account for that (was using a version with plain_sharded_traits<>)
 - added missing std::ref() around sharded<abort_source> in tests/gossip.cc (not caught by tests since is isn't in test.py)
