### PR TITLE
tests: logalloc_test: scale down test_region_groups

### LINKED ISSUE #4669: logalloc_test is flaky
Not sure exactly when this started happening.

FWIW, the signature of this issue looks like this, in [next/960](https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/960/consoleText):
```
[2019-07-08T12:30:47.842Z] Output of the failed tests:
[2019-07-08T12:30:47.842Z] Test build/debug/tests/logalloc_test --report_level=no --logger=HRF,test_suite:XML,test_suite,jenkins_test.debug.logalloc_test.boost.xml -- -c2 -m2G --overprovisioned --unsafe-bypass-fsync 1 --blocked-reactor-notify-ms 2000000 --collectd 0 failed:
[2019-07-08T12:30:47.842Z]   with error code -9
[2019-07-08T12:30:47.842Z] 
[2019-07-08T12:30:47.842Z] === stdout START ===
[2019-07-08T12:30:47.842Z] Running 23 test cases...
[2019-07-08T12:30:47.842Z] Entering test module "tests/logalloc_test.cc"
[2019-07-08T12:30:47.842Z] tests/logalloc_test.cc(0): Entering test case "test_prime_logalloc"
[2019-07-08T12:30:47.842Z] WARNING: debug mode. Not for benchmarking or production
[2019-07-08T12:30:47.842Z] WARN  2019-07-08 13:32:41,204 seastar - Seastar compiled with default allocator, heap profiler not supported
[2019-07-08T12:30:47.842Z] WARN  2019-07-08 13:32:41,209 seastar - Seastar compiled with default allocator, heap profiler not supported
[2019-07-08T12:30:47.842Z] WARN  2019-07-08 13:32:41,233 [shard 0] seastar - Unable to set SCHED_FIFO scheduling policy for timer thread; latency impact possible. Try adding CAP_SYS_NICE
[2019-07-08T12:30:47.842Z] random-seed=3616292396
[2019-07-08T12:30:47.842Z] tests/logalloc_test.cc(0): Leaving test case "test_prime_logalloc"; testing time: 2759407us
[2019-07-08T12:30:47.842Z] tests/logalloc_test.cc(0): Entering test case "test_compaction"
[2019-07-08T12:30:47.842Z] ==249==WARNING: ASan doesn't fully support makecontext/swapcontext functions and may produce false positives in some cases!
[2019-07-08T12:30:47.842Z] tests/logalloc_test.cc(0): Leaving test case "test_compaction"; testing time: 6493861us
[2019-07-08T12:30:47.842Z] tests/logalloc_test.cc(0): Entering test case "test_occupancy"
[2019-07-08T12:30:47.842Z] tests/logalloc_test.cc(0): Leaving test case "test_occupancy"; testing time: 494us
[2019-07-08T12:30:47.842Z] tests/logalloc_test.cc(0): Entering test case "test_compaction_with_multiple_regions"
[2019-07-08T12:30:47.842Z] tests/logalloc_test.cc(0): Leaving test case "test_compaction_with_multiple_regions"; testing time: 21538860us
[2019-07-08T12:30:47.842Z] tests/logalloc_test.cc(0): Entering test case "test_mixed_type_compaction"
[2019-07-08T12:30:47.842Z] tests/logalloc_test.cc(0): Leaving test case "test_mixed_type_compaction"; testing time: 2954us
[2019-07-08T12:30:47.842Z] tests/logalloc_test.cc(0): Entering test case "test_blob"
[2019-07-08T12:30:47.842Z] tests/logalloc_test.cc(0): Leaving test case "test_blob"; testing time: 957us
[2019-07-08T12:30:47.842Z] tests/logalloc_test.cc(0): Entering test case "test_merging"
[2019-07-08T12:30:47.842Z] tests/logalloc_test.cc(0): Leaving test case "test_merging"; testing time: 401008us
[2019-07-08T12:30:47.842Z] tests/logalloc_test.cc(0): Entering test case "test_region_groups"
[2019-07-08T12:30:47.842Z] 
[2019-07-08T12:30:47.842Z] === stdout END ===
```

Note that `test_region_groups` is the last test case started (but not finished)

### PR DESCRIPTION
**Pull request by bhalevy**
Post commit d8dbacc7f65386642297606e410350bd35ff1e3d
(More precise poisoning in logalloc)
logalloc_test's memory footprint has grown, in particula
in test_region_groups, and it triggers the oom killer on
our test automation machines.

This patch scales down the test so it requires less memory
(Seen ~2.5 GB vs. ~4.4 GB based on ps/RSS)

Fixes #4669

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>

Test: logalloc_test(debug)

### CODE REVIEW

**Comment by espindola** [comment]
I have measured memory usage with

/usr/bin/time -v ./build/debug/tests/logalloc_test_g -- -c2 -m2G --overprovisioned --unsafe-bypass-fsync 1 --blocked-reactor-notify-ms 2000000 --collectd 0

That prints the ru_maxrss returned by wait3. I got

2d3e3640df34df4cc086f976262994c9bf5d563e.time: Maximum resident set size (kbytes): 7400480
62aa0ea3fa3f9c7be1881d68e1395396589504cf.time: Maximum resident set size (kbytes): 7390696
6a2accb4838fb5a135f1b7626f06cacf93dc381b.time: Maximum resident set size (kbytes): 7378568
95bab04cf9ad37fe9f7a6ce3a331f7631cfd4a82.time: Maximum resident set size (kbytes): 6988116
b3adabda2d74533f4359c09cecb2d2ed5cdac90b.time: Maximum resident set size (kbytes): 7383732
bf87b7e1df96439b6e65190305aec13d2566b05b.time: Maximum resident set size (kbytes): 7370848
c5184b3dd06878e7306b29cac557dc1c643e412f.time: Maximum resident set size (kbytes): 7382276
d8dbacc7f65386642297606e410350bd35ff1e3d.time: Maximum resident set size (kbytes): 7383620
f7e79b07d12521562d0fc9a064e96bf5fce41424.time: Maximum resident set size (kbytes): 7382384

So it looks like the RSS increased since b3adabda2d74533f4359c09cecb2d2ed5cdac90b. Maybe the OOM killer uses some other indicator?

In any case, this LGTM as an experiment, but update the commit message.

File: tests/logalloc_test.cc [hunk 1]
```diff
@@ -523,7 +525,7 @@ SEASTAR_TEST_CASE(test_region_groups) {
         BOOST_REQUIRE_GE(ssize_t(three->occupancy().total_space()), ssize_t(three->occupancy().used_space()));
         BOOST_REQUIRE_EQUAL(all.memory_used(), one_and_two.memory_used() + three->occupancy().total_space());
 
-        constexpr size_t four_count = 256 * 1024;
+        constexpr size_t four_count = 8 * base_count;
```
Comment (tgrabiec) [inline tests/logalloc_test.cc]: shouldn't that be `4 * base_count`,  so that fout_count is still half the two_count? That said, I don't know what's the significance of relative counts in this test.

**Comment by bhalevy** [comment]
@espindola, @tgrabiec  thanks. I force-pushed 360ad86be7e7926120605c05e08c990141f00463 with the updated commit message and reduced `four_count`.  I don't think the ratios matter much in this test case but there is no reason to change them either...
