### PR TITLE
select_statement: Fix aggregate results on indexed selects

### LINKED ISSUE #7355: Invalid aggregation result on table with index
When using aggregates (`COUNT(*)`) on table with index on clustering key and filtering on clustering key, wrong results are returned - returned count does not match number of rows that match `WHERE`.

```
cqlsh> CREATE KEYSPACE ks WITH REPLICATION = {'class': 'SimpleStrategy', 'replication_factor': 1};
cqlsh> CREATE TABLE ks.t(a int, b int, c int, PRIMARY KEY ((a, b), c));
cqlsh> INSERT INTO ks.t(a, b, c) VALUES (1, 2, 3);

cqlsh> SELECT * FROM ks.t WHERE c = 3 ALLOW FILTERING;

 a | b | c
---+---+---
 1 | 2 | 3

(1 rows)
cqlsh> SELECT COUNT(*) FROM ks.t WHERE c = 3 ALLOW FILTERING;

 count
-------
     1

(1 rows)

cqlsh> CREATE INDEX kst_index ON ks.t(c);
cqlsh> SELECT * FROM ks.t WHERE c = 3;

 a | b | c
---+---+---
 1 | 2 | 3

(1 rows)
cqlsh> SELECT COUNT(*) FROM ks.t WHERE c = 3;

 count
-------
     0
```
(↑ wrong! - should be 1)
```
(1 rows)
cqlsh> INSERT INTO ks.t(a, b, c) VALUES (1, 2, 4);
cqlsh> INSERT INTO ks.t(a, b, c) VALUES (1, 2, 5);
cqlsh> SELECT * FROM ks.t WHERE c = 3;

 a | b | c
---+---+---
 1 | 2 | 3

(1 rows)
cqlsh> SELECT COUNT(*) FROM ks.t WHERE c = 3;

 count
-------
     2

(1 rows)
```
(↑ wrong! - should be 1)

This bug is the root cause of this issue: https://github.com/scylladb/scylla/issues/7043 (at least one of causes...)

### Preliminary analysis on the bug

- It was introduced in some version of Scylla between `3.1.0` and `3.2.0` (doing bisect now to determine the specific commit).
- It seems that wrong base table `read_command` is created for the `COUNT(*)` query:

`read_command` for `SELECT *`:
```
TRACE 2020-10-06 17:15:01,769 [shard 2] storage_proxy - query ks.t cmd=read_command{cf_id=083b3280-07e3-11eb-bbac-000000000006, version=4f1ed180-28ab-3979-8ad8-d91aba6f0378, slice={regular_cols=[], static_cols=[], rows=[{ckp{000400000003}}], options=103, cql_format=4, partition_row_limit=4294967295}, limit=18446744073709551615, timestamp=1601997301}, partition_limit=4294967295}, ranges={{{4881097376275569167, pk{000400000001000400000002}}}}, id=21
```

`read_command` for `SELECT COUNT(*)`: (`(ckp{000400000003}, +inf)` seems wrong)
```
TRACE 2020-10-06 17:15:07,683 [shard 2] storage_proxy - query ks.t cmd=read_command{cf_id=083b3280-07e3-11eb-bbac-000000000006, version=4f1ed180-28ab-3979-8ad8-d91aba6f0378, slice={regular_cols=[], static_cols=[], rows=[{ckp{000400000003}}], specific=[{pk{000400000001000400000002} : (ckp{000400000003}, +inf)}], options=103, cql_format=4, partition_row_limit=4294967295}, limit=18446744073709551615, timestamp=1601997307}, partition_limit=4294967295}, ranges={{{4881097376275569167, pk{000400000001000400000002}}}}, id=23
```

*Installation details*
Scylla version (or git commit hash): 92e78da2d6bb1e7c61cbc8019e692e0f1fe8268f
Cluster size: 1 node
OS (RHEL/CentOS/Ubuntu/AWS AMI): Fedora 32

### PR DESCRIPTION
**Pull request by avelanarius**
### Overview
Fixes #7355.

Before this changes, there were a few invalid results of aggregates/GROUP BY on tables with secondary indexes (see below).

Unfortunately, it still does NOT fix the problem in issue #7043. Although this PR moves forward fixing of that issue, there is still a bug with `TOKEN(...)` in `WHERE` clauses of indexed selects that is not addressed in this PR. It will be fixed in my next PR.

It does NOT fix the problems in issues #7432, #7431 as those are out-of-scope of this PR and do not affect the correctness of results (only return a too large page).

### GROUP BY (first commit)
Before the change, `GROUP BY` `SELECT`s with some `WHERE` restrictions on an indexed column would return invalid results (same grouped column values appearing multiple times):
```
CREATE TABLE ks.t(pk int, ck int, v int, PRIMARY KEY(pk, ck));
CREATE INDEX ks_t on ks.t(v);
INSERT INTO ks.t(pk, ck, v) VALUES (1, 2, 3);
INSERT INTO ks.t(pk, ck, v) VALUES (1, 4, 3);
SELECT pk FROM ks.t WHERE v=3 GROUP BY pk;
 pk
----
  1
  1
```
This is fixed by correctly passing `_group_by_cell_indices` to `result_set_builder`. Fixes the third failing example from issue #7355.

### Paging (second commit)
Fixes two issues related to improper paging on indexed `SELECT`s. As those two issues are closely related (fixing one without fixing the other causes invalid results of queries), they are in a single commit (second commit). 

The first issue is that when using `slice.set_range`, the existing `_row_ranges` (which specify clustering key prefixes) are not taken into account. This caused the wrong rows to be included in the result, as the clustering key bound was set to a half-open range:
```
CREATE TABLE ks.t(a int, b int, c int, PRIMARY KEY ((a, b), c));
CREATE INDEX kst_index ON ks.t(c);
INSERT INTO ks.t(a, b, c) VALUES (1, 2, 3);
INSERT INTO ks.t(a, b, c) VALUES (1, 2, 4);
INSERT INTO ks.t(a, b, c) VALUES (1, 2, 5);
SELECT COUNT(*) FROM ks.t WHERE c = 3;
 count
-------
     2
```
The second commit fixes this issue by properly trimming `row_ranges`.

The second fixed problem is related to setting the `paging_state` to `internal_options`. It was improperly set to the value just after reading from index, making the base query start from invalid `paging_state`.

The second commit fixes this issue by setting the `paging_state` after both index and base table queries are done. Moreover, the `paging_state` is now set based on `paging_state` of index query and the results of base table query (as base query can return more rows than index query).

The second commit fixes the first two failing examples from issue #7355.

### Tests (third commit)
Extensively tests queries on tables with secondary indices with  aggregates and `GROUP BY`s. 

Tests three cases that are implemented in `indexed_table_select_statement::do_execute` - `partition_slices`,
`whole_partitions` and (non-`partition_slices` and non-`whole_partitions`). As some of the issues found were related to paging, the tests check scenarios where the inserted data is smaller than a page, larger than a page and larger than two pages (and some in-between page boundaries scenarios).

I found all those parameters (case of `do_execute`, number of inserted rows) to have an impact of those fixed bugs, therefore the tests validate a large number of those scenarios.

### CODE REVIEW

File: test/boost/secondary_index_test.cc [hunk 1]
```diff
@@ -1208,6 +1208,279 @@ SEASTAR_TEST_CASE(test_indexing_paging_and_aggregation) {
...
 }
 
+// Verifies that both "SELECT * [rest_of_query]" and "SELECT count(*) [rest_of_query]" 
+// return expected count of rows.
+void assert_select_count_and_select_rows_has_size(cql_test_env& e, const sstring& rest_of_query, int64_t expected_count) {
+    eventually([&] { 
+        auto res = e.execute_cql("SELECT count(*) " + rest_of_query).get0();
+        assert_that(res).is_rows().with_rows({
+            { long_type->decompose(expected_count) }
+        });
```
Comment (dekimir) [inline test/boost/secondary_index_test.cc:1218]: Why not use `require_rows`?

File: test/boost/secondary_index_test.cc [hunk 2]
```diff
@@ -1208,6 +1208,279 @@ SEASTAR_TEST_CASE(test_indexing_paging_and_aggregation) {
...
+        res = e.execute_cql("SELECT * " + rest_of_query).get0();
```
Comment (dekimir) [inline test/boost/secondary_index_test.cc:1219]: `cquery_nofail` would be better here, for improved diagnostic in case of failure.

File: test/boost/secondary_index_test.cc [hunk 3]
```diff
@@ -1208,6 +1208,279 @@ SEASTAR_TEST_CASE(test_indexing_paging_and_aggregation) {
     });
 }
 
+// Verifies that both "SELECT * [rest_of_query]" and "SELECT count(*) [rest_of_query]" 
+// return expected count of rows.
+void assert_select_count_and_select_rows_has_size(cql_test_env& e, const sstring& rest_of_query, int64_t expected_count) {
```
Comment (dekimir) [inline test/boost/secondary_index_test.cc:1213]: Making this `void` will diminish the value of diagnostic messages in future failures.  Consider returning results from this function and asserting on them in the caller OR passing a `source_location` parameter like `require_rows` does.

File: test/boost/secondary_index_test.cc [hunk 4]
```diff
@@ -1208,6 +1208,279 @@ SEASTAR_TEST_CASE(test_indexing_paging_and_aggregation) {
...
+        cquery_nofail(e, "INSERT INTO t2(pk, ck) VALUES (0, -2)");
+        cquery_nofail(e, "INSERT INTO t2(pk, ck) VALUES (0, 3)");
+        cquery_nofail(e, format("INSERT INTO t2(pk, ck) VALUES ({}, 3)", page_scenarios_just_after_first_page).c_str());
+
+        test_with_different_page_scenarios([&](int64_t current_row) {
+            cquery_nofail(e, format("INSERT INTO t2(pk, ck) VALUES ({}, 1)", current_row).c_str());
+        }, [&](int64_t rows_inserted) {
+            assert_select_count_and_select_rows_has_size(e, "FROM t2 WHERE ck = 1", rows_inserted);
+          eventually([&] { 
+            auto res = e.execute_cql("SELECT pk FROM t2 WHERE ck = 1 GROUP BY pk").get0();
```
Comment (dekimir) [inline test/boost/secondary_index_test.cc:1317]: I'd really like to see `cquery_nofail` here and throughout.  It's both shorter and much more valuable when the query fails (for whatever reason).

File: test/boost/secondary_index_test.cc [hunk 5]
```diff
@@ -1208,6 +1208,279 @@ SEASTAR_TEST_CASE(test_indexing_paging_and_aggregation) {
...
+        auto res = e.execute_cql("SELECT count(*) " + rest_of_query).get0();
+        assert_that(res).is_rows().with_rows({
+            { long_type->decompose(expected_count) }
+        });
+        res = e.execute_cql("SELECT * " + rest_of_query).get0();
+        assert_that(res).is_rows().with_size(expected_count);
+    });
+}
+
+static constexpr int page_scenarios_row_count = 2 * cql3::statements::select_statement::DEFAULT_COUNT_PAGE_SIZE + 120;
```
Comment (dekimir) [inline test/boost/secondary_index_test.cc:1224]: Referencing fully qualified `DEFAULT_COUNT_PAGE_SIZE` makes lines long and less readable.  There should be a way to use a shorter name.

File: test/boost/secondary_index_test.cc [hunk 6]
```diff
@@ -1208,6 +1208,279 @@ SEASTAR_TEST_CASE(test_indexing_paging_and_aggregation) {
...
+
+static_assert(page_scenarios_initial_count < page_scenarios_row_count);
+static_assert(page_scenarios_window_size < cql3::statements::select_statement::DEFAULT_COUNT_PAGE_SIZE);
+static_assert(page_scenarios_just_after_second_page < page_scenarios_row_count);
+
+// Executes `insert` lambda page_scenarios_row_count times. 
+// Runs `validate` lambda in a few scenarios:
+//
+// 1. After a small number of `insert`s
+// 2. In a window from just before and just after `insert`s where executed
```
Comment (dekimir) [inline test/boost/secondary_index_test.cc:1240]: Is "where" a typo?

File: test/boost/secondary_index_test.cc [hunk 7]
```diff
@@ -1208,6 +1208,279 @@ SEASTAR_TEST_CASE(test_indexing_paging_and_aggregation) {
...
+//    DEFAULT_COUNT_PAGE_SIZE times
+// 3. In a window from just before and just after `insert`s where executed
+//    2 * DEFAULT_COUNT_PAGE_SIZE times
+// 4. After all `insert`s
+void test_with_different_page_scenarios(
+    noncopyable_function<void (int64_t)> insert, noncopyable_function<void (int64_t)> validate) {
+
+    int64_t current_row = 0;
```
Comment (dekimir) [inline test/boost/secondary_index_test.cc:1248]: Why `int64_t`?  Can it be negative?  Can it exceed 32 bits?  Perhaps an explaining comment is needed.

File: test/boost/secondary_index_test.cc [hunk 8]
```diff
@@ -1208,6 +1208,279 @@ SEASTAR_TEST_CASE(test_indexing_paging_and_aggregation) {
...
+    for (; current_row < page_scenarios_just_after_second_page; current_row++) {
+        insert(current_row);
+        validate(current_row + 1);
+    }   
+
+    for (; current_row < page_scenarios_row_count; current_row++) {
+        insert(current_row);
+    }
+
+    validate(current_row);
```
Comment (dekimir) [inline test/boost/secondary_index_test.cc:1276]: Why not `current_row + 1`, like everywhere else?  Add a comment.

File: cql3/statements/select_statement.cc [hunk 9]
```diff
@@ -542,10 +542,14 @@ indexed_table_select_statement::do_execute_base_query(
...
-                    command->slice.set_range(*_schema, base_pk,
-                            std::vector<query::clustering_range>{query::clustering_range::make_starting_with(range_bound<clustering_key>(base_ck, false))});
+
+                    auto row_ranges = command->slice.default_row_ranges();
+                    query::trim_clustering_row_ranges_to(*_schema, row_ranges, base_ck, false);
+                    command->slice.set_range(*_schema, base_pk, row_ranges);
                 } else {
-                    command->slice.set_range(*_schema, base_pk, std::vector<query::clustering_range>{query::clustering_range::make_open_ended_both_sides()});
+                    // If there are none _specific_ranges, the entire partition range
+                    // will be read.
```
Comment (dekimir) [inline cql3/statements/select_statement.cc:551]: I'm confused by this comment.  Why, specifically, do we not need to set_range on command->slice when CK is involved in paging?  Does some other code set it for us?  What do specific_ranges have to do with anything?

File: test/boost/secondary_index_test.cc [hunk 10]
```diff
@@ -1208,6 +1208,279 @@ SEASTAR_TEST_CASE(test_indexing_paging_and_aggregation) {
...
+}
+
+SEASTAR_TEST_CASE(test_secondary_index_on_ck_first_column_and_aggregation) {
```
Comment (dekimir) [inline test/boost/secondary_index_test.cc:1279]: I don't like the tests in a separate commit.  It complicates bisection and backporting: `git bisect` will think that the code commit is OK because of no failures; a maintainer may backport the code but not the tests into a branch that will then lack coverage.

**Review by dekimir — CHANGES_REQUESTED** [review]
This is a good start.  I left a few comments.

File: cql3/statements/select_statement.cc (hunk 9 above)
Comment (haaawk) [reply cql3/statements/select_statement.cc:551]: This base_ck is computed from old_paging_state, @dekimir. As far as I understand, paging state for index has a clustering key of a base table encoded inside it. This code extracts last returned base table ck and uses it to return only stuff after this last already returned ck.

File: cql3/statements/select_statement.cc [hunk 11]
```diff
@@ -992,31 +996,40 @@ indexed_table_select_statement::do_execute(service::storage_proxy& proxy,
...
+                    }
+                    internal_options.reset(new cql3::query_options(std::move(internal_options), paging_state ? make_lw_shared<service::pager::paging_state>(*paging_state) : nullptr));
                     if (restrictions_need_filtering) {
                         _stats.filtered_rows_read_total += *results->row_count();
                         query::result_view::consume(*results, cmd->slice, cql3::selection::result_set_builder::visitor(builder, *_schema, *_selection,
                                 cql3::selection::result_set_builder::restrictions_filter(_restrictions, options, cmd->get_row_limit(), _schema, cmd->slice.partition_row_limit())));
                     } else {
                         query::result_view::consume(*results, cmd->slice, cql3::selection::result_set_builder::visitor(builder, *_schema, *_selection));
                     }
+                    return paging_state;
```
Comment (haaawk) [inline cql3/statements/select_statement.cc:1011]: Can we just return `has_more_pages` boolean from this lambda? or even stop_iteration::yes/no?

Comment (haaawk) [reply cql3/statements/select_statement.cc:1011]: It would remove some code duplication and would also be cheaper.

File: cql3/statements/select_statement.cc [hunk 12]
```diff
@@ -992,31 +996,40 @@ indexed_table_select_statement::do_execute(service::storage_proxy& proxy,
             // page size is set to the internal count page size, regardless of the user-provided value
             internal_options.reset(new cql3::query_options(std::move(internal_options), options.get_paging_state(), DEFAULT_COUNT_PAGE_SIZE));
             return repeat([this, &builder, &options, &internal_options, &proxy, &state, now, whole_partitions, partition_slices, restrictions_need_filtering] () {
-                auto consume_results = [this, &builder, &options, &internal_options, restrictions_need_filtering] (foreign_ptr<lw_shared_ptr<query::result>> results, lw_shared_ptr<query::read_command> cmd) {
+                auto consume_results = [this, &builder, &options, &internal_options, &proxy, &state, restrictions_need_filtering] (foreign_ptr<lw_shared_ptr<query::result>> results, lw_shared_ptr<query::read_command> cmd, lw_shared_ptr<const service::pager::paging_state> paging_state) {
+                    if (paging_state) {
+                        paging_state = generate_view_paging_state_from_base_query_results(paging_state, results, proxy, state, options);
```
Comment (haaawk) [inline cql3/statements/select_statement.cc:1001]: @avelanarius do I understand correctly that this is the heart of this fix (apart from set_ranges issue)? We use paging state computed based on base table paging state instead of index paging state.

What is not 100% clear to me yet is why base table select can return more results than index select?

File: cql3/statements/select_statement.cc (hunk 9 above)
Comment (dekimir) [reply cql3/statements/select_statement.cc:551]: But the comment doesn't say that.  It doesn't mention CK at all.

The reader will be wondering why we're asserting here instead of calling `clear_ranges()`; this comment should explain that.

File: test/boost/secondary_index_test.cc (hunk 10 above)
Comment (psarna) [reply test/boost/secondary_index_test.cc:1279]: Maintainers should not generally backport single commits belonging to a larger series, but rather the whole series, so I'm personally fine with this being in a separate commit. No strong opinion either way though.

Comment (haaawk) [reply test/boost/secondary_index_test.cc:1279]: I like the separation. The smaller the commits the easier it is to review them.

**Comment by psarna** [comment]
Looks good. Let's apply/address Dejan's commits (especially `cquery_nofail`) and we can proceed with this one. I have another series which translates some code from `select_statement.cc` to coroutines and I'd like to see this one merged first in order to avoid merge conflicts.

File: cql3/statements/select_statement.cc (hunk 12 above)
Comment (avelanarius) [reply cql3/statements/select_statement.cc:1001]: The fix for paging has two parts:
1. Setting `paging_state` on `internal_options` after base query - not before (here we do it in `consume_results`).
2. Computing next `paging_state` based on base table select and index paging state. 

Base select always reads an entire partition, so in case of table:
```
pk | ck1 | ck2
 1 |   1 |   1
 1 |   1 |   2
 1 |   1 |   3
 1 |   1 |   4
...
 1 |   1 |   100000
```
First, the index query (on indexed column `ck1 = 1`), will return a page of results (for example up to `ck2 = 10000`). However, when executing base query we will read an entire partition (`pk = 1`) - more than index. This is why we need to adjust the paging state to avoid reading the rows again (we would read from `ck2 = 10001`).

`generate_view_paging_state_from_base_query_results` was also already used on non-aggregate code path.

I described this paging behaviour in second example in https://github.com/scylladb/scylla/issues/7432.

File: test/boost/secondary_index_test.cc (hunk 10 above)
Comment (avelanarius) [reply test/boost/secondary_index_test.cc:1279]: When reading some older @psarna commits, I noticed that he separated tests into a separate commit: https://github.com/scylladb/scylla/commit/3d9a37f28fe413bb310059eb4d8d401e032d24b1. I thought this was some convention that should be followed.

File: cql3/statements/select_statement.cc (hunk 9 above)
Comment (avelanarius) [reply cql3/statements/select_statement.cc:551]: So the explanation of this is quite complex to succinctly describe:

Before the change, the code was: 
```cpp
command->slice.set_range(*_schema, base_pk, 
   std::vector<query::clustering_range>{query::clustering_range::make_open_ended_both_sides()});
```
To fix the bug I found, we would have to intersect this range with `_row_ranges`, the same way as in non-else branch. However, intersection of `_row_ranges` and `clustering_range::make_open_ended_both_sides` is just `_row_ranges`. This would result in such code:
```cpp
command->slice.set_range(*_schema, base_pk, command->slice.default_row_ranges());
```
But because `_specific_ranges` (those are set by `set_range`) are `nullptr` as created in `prepare_command_for_base_query`, this `set_range` is unnecessary, because if no `_specific_ranges` are set, `_row_ranges` are used (returned by `default_row_ranges()`, more info: https://github.com/scylladb/scylla/issues/7362). 

I added this assert to make sure that if someone changes `prepare_command_for_base_query` to add `_specific_ranges`, they will get assert failure in unit tests, because the necessary precondition is not true anymore.

File: test/boost/secondary_index_test.cc (hunk 10 above)
Comment (psarna) [reply test/boost/secondary_index_test.cc:1279]: Yup, I tend to do that, because splitting to more commits makes rebasing easier.

Comment (haaawk) [reply test/boost/secondary_index_test.cc:1279]: I do that as well as I recommend doing it.

File: test/boost/secondary_index_test.cc (hunk 7 above)
Comment (avelanarius) [reply test/boost/secondary_index_test.cc]: There was no particular reason to use `int64_t` (probably as I was writing this I was influenced by the fact that `COUNT(*)` returns `long` - `int64`). 

Changed the type to `int` to indicate to the readers of the code that this is just a "normal number" - a counter that will not exceed a few tens of thousands in this case.

**Comment by avelanarius** [comment]
@dekimir Fixed all your issues related to the tests.

File: cql3/statements/select_statement.cc (hunk 9 above)
Comment (avelanarius) [reply cql3/statements/select_statement.cc]: @dekimir In the amended commit, I changed this comment to more thoroughly explain this and overarching context.

**Comment by avelanarius** [comment]
@dekimir @haaawk @psarna Also fixed all other suggestions.

File: cql3/statements/select_statement.cc (hunk 9 above)
Comment (dekimir) [reply cql3/statements/select_statement.cc]: > To fix the bug I found, we would have to intersect this range with `_row_ranges`, the same way as in non-else branch

Then why don't we do precisely that?  It doesn't matter that it currently happens to amount to a no-op, it's future-proof correct code.

> I added this assert to make sure that if someone changes `prepare_command_for_base_query`

Wouldn't it be better if the new code still worked even in this scenario?  Why burden the future developer with a complicated explanation they'll likely struggle with, instead of performing the logically expected operation?

File: test/boost/secondary_index_test.cc (hunk 10 above)
Comment (dekimir) [reply test/boost/secondary_index_test.cc:1288]: OK, OK. :)

File: cql3/statements/select_statement.cc (hunk 9 above)
Comment (avelanarius) [reply cql3/statements/select_statement.cc]: @dekimir Fixed it the way you described (explicitly setting the `_row_ranges`) in the amended commit. 

I think I have now addressed all the comments?

**Review by dekimir — APPROVED** [review]

**Review by haaawk — APPROVED** [review]
LGTM @psarna would you mind merging?

**Comment by haaawk** [comment]
@psarna do you have any other comments or are we good to merge this?

**Comment by avikivity** [comment]
Dequeued - causes secondary_index_test in debug mode to fail. Bisect pointed at 

```
8ce1cc5267445b5153128670de6d9049750dc894 is the first bad commit
commit 8ce1cc5267445b5153128670de6d9049750dc894
Author: Piotr Grabowski <piotr.grabowski@scylladb.com>
Date:   Mon Oct 12 18:18:27 2020 +0200

    select_statement: Fix GROUP BY on indexed select
    
    Before the change, GROUP BY SELECTs with some WHERE restrictions on an
    indexed column would return invalid results (same grouped column values
    appearing multiple times):
    
    CREATE TABLE ks.t(pk int, ck int, v int, PRIMARY KEY(pk, ck));
    CREATE INDEX ks_t on ks.t(v);
    INSERT INTO ks.t(pk, ck, v) VALUES (1, 2, 3);
    INSERT INTO ks.t(pk, ck, v) VALUES (1, 4, 3);
    SELECT pk FROM ks.t WHERE v=3 GROUP BY pk;
     pk
    ----
      1
      1
    
    This is fixed by correctly passing _group_by_cell_indices to
    result_set_builder. Fixes the third failing example from issue #7355.

 cql3/statements/select_statement.cc | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

```

(although it pointed at a build failure, so maybe a different patch in the series was broken; please keep patches bisectable).
