### PR TITLE
Fix reading whole requests during shedding

### LINKED ISSUE #8193: Request are not entirely read during shedding
Through code inspection, it looks like when requests are shed (e.g. due to being too large or exceeding the max number of concurrent requests per shard), they are erroneously ignored right after parsing their headers - while their body still waits in the socket and will be read by the server, which expects to find a CQL header in there.

It's quite late so I don't have any automatic tests that support this claim, but manual tests suggest that that's what indeed happens. The fix is simple - seastar streams are capable of skipping bytes, so before the error is returned, the body of the shed request should be skipped.

### PR DESCRIPTION
**Pull request by psarna**
When shedding requests (e.g. due to their size or number exceeding the limits), errors were returned right after parsing their headers, which resulted in their bodies lingering in the socket. The server always expects a correct request header when reading from the socket after the processing of a single request is finished, so shedding the requests should also take care of draining their bodies from the socket.

Fixes #8193

### CODE REVIEW

**Comment by psarna** [comment]
I'm in the middle of writing a test and I already found a bug - it's not enough to skip straight from the stream, since some of the data might have already been loaded into the fragmented buffer. I'll post a working version along with a test soon.

**Comment by psarna** [comment]
Oh wait, no, it should work fine, there's no way something was read upfront. That means that either there's another bug or my test is wrong.

**Comment by psarna** [comment]
I'm having hard time pushing a cql pytest which sends a request larger than the allowed maximum (25MiB for current test/cql-pytest/run configuration), so for now I resorted to manually testing the `max_concurrent_requests_per_shard` config value by consulting the metrics and it works fine.

**Comment by psarna** [comment]
Double success!!! Turns out there are two independent bugs in the shedding code. The second one is about sending the response with the correct stream id (which we know after receiving the frame). Patches are being cooked.

**Comment by psarna** [comment]
Also, the fix would reduce one try-catch in favor of constructing an error reply in-place.

**Comment by psarna** [comment]
@avikivity I dequeued the original series from /next and just posted a new, more complete version along with a test that verifies that it works.
v2:
 - added sending the errors to correct stream ids
 - added a cql-pytest test which used to expose the problem and now passes fine

**Comment by psarna** [comment]
@avikivity I dequeued due to the new test failing, but the test itself is useful for manual runs and serves as an additional documentation for the problem, so I just marked it as skipped.

**Comment by psarna** [comment]
v3:
 - excluded the test from Jenkins due to it being dependent on configuration, which causes it to fail /next; the test is still useful for local verification

File: transport/server.cc [hunk 1]
```diff
@@ -713,8 +713,10 @@ future<> cql_server::connection::process_request() {
         auto mem_estimate = f.length * 2 + 8000; // Allow for extra copies and bookkeeping
 
         if (mem_estimate > _server._max_request_size) {
-            return make_exception_future<>(exceptions::invalid_request_exception(format("request size too large (frame size {:d}; estimate {:d}; allowed {:d}",
-                    f.length, mem_estimate, _server._max_request_size)));
+            return _read_buf.skip(f.length).then([length = f.length, mem_estimate, this] {
```
Comment (nyh) [inline transport/server.cc]: Looks good. The need to duplicate this skip() part twice made me think if perhaps the caller, upon getting any exception (including these two, but perhaps others), should be the one who skips the full request. But it will require knowing where the request will end (we may even get an exception in the middle of reading a request), so it might not be easy. So we can start with this code and rethink this later if we want.

File: test/cql-pytest/test_shedding.py [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+# Tests for the shedding mechanisms in the CQL layer
+#############################################################################
+
+import pytest
+import re
+from cassandra.protocol import InvalidRequest
+from util import unique_name, random_string
+
+
+@pytest.fixture(scope="session")
```
Comment (nyh) [inline test/cql-pytest/test_shedding.py:28]: Two thoughts for the future (no need to do it now):
1. We should have one or several text fixtures that all tests can use if they don't really care about the schema, like is the case here, instead of every test file needing to add test fixtures.
2. We should change "session" scope fixtures to "module" scope. So the tables created by a test file get deleted after the test file - not just when all the test suite is done.

**Review by nyh — APPROVED** [review]

**Comment by nyh** [comment]
> v3:
> 
>     * excluded the test from Jenkins due to it being dependent on configuration, which causes it to fail /next; the test is still useful for local verification

I agree with what you did (and committed the new series to next), but I wonder why it failed in Jenkins, since it should be running the same test/cql-pytest/run which you do (?) and this always creates a Scylla with the same amount of memory etc. Or maybe you didn't use test/cql-pytest/run yourself, and ran Scylla on your own? (that's definitely allowed, and maybe makes debugging easier?)

**Comment by psarna** [comment]
> > v3:
> > ```
> > * excluded the test from Jenkins due to it being dependent on configuration, which causes it to fail /next; the test is still useful for local verification
> > ```
> 
> I agree with what you did (and committed the new series to next), but I wonder why it failed in Jenkins, since it should be running the same test/cql-pytest/run which you do (?) and this always creates a Scylla with the same amount of memory etc. Or maybe you didn't use test/cql-pytest/run yourself, and ran Scylla on your own? (that's definitely allowed, and maybe makes debugging easier?)

@nyh I started with running manually for convenience (with identical smp & memory parameters), but I also verified the regular test/cql-pytest/run. All jenkins failures happened, as is customary for cql-pytest, in debug mode, so it's probably some timing issue again and I judged it not worth it to investigate, since the test is easily verifiable on release/dev modes.
