### PR TITLE
RFC: Add `experimental_features` option

### LINKED ISSUE #5338: Change experimental flag granularity to per feature
The current experimental flag has a granularity of all features. This means that if one of the features is broken it might force the user to turn off the experimental flag altogether, preventing him from using the features that do work.
An example for this situation is #5288 where this solution is suggested, where CDC breaks rolling upgrade from 3.1 to 3.2 forcing turning off the experimental flag and not using LWT since it is also experimental.
The solution suggested in #5288 needs to be implemented, it is roughly outlined in https://github.com/scylladb/scylla/issues/5288#issuecomment-557110306

### PR DESCRIPTION
**Pull request by dekimir**
Add `--experimental-features` -- a vector of features to unlock.  Make corresponding changes in the YAML parser.

Fixes #5338

### CODE REVIEW

**Comment by tzach** [comment]
@dekimir 
Any way to extract the experimental feature available in each release (3 in this case) ?

**Comment by dekimir** [comment]
> @dekimir
> Any way to extract the experimental feature available in each release (3 in this case) ?

Yes: the `--help` flag and the sample `scylla.yaml` file both list them.  That currently has to be maintained by hand, though it's possible to make it automatic in the future with some effort.

File: utils/enum_option.hh [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+///   return *inst;
+/// }
+/// int main(int ac, char* av[]) {
+///   namespace po = boost::program_options;
+///   po::options_description desc("Allowed options");
+///   desc.add_options()
+///     ("val", po::value<enum_option<Type>>(), "Single Type")
+///     ("vec", po::value<vector<enum_option<Type>>>()->multitoken(), "Type vector");
+/// }
+template<typename Mapper>
```
Comment (avikivity) [inline utils/enum_option.hh]: Please document the Mapper type. The best way to do that is with a GCC6_CONCEPT().

File: conf/scylla.yaml [hunk 2]
```diff
@@ -245,7 +245,10 @@ batch_size_fail_threshold_in_kb: 50
 # broadcast_rpc_address: 1.2.3.4
 
 # Uncomment to enable experimental features
-# experimental: true
+# experimental:
+#     - cdc
+#     - lwt
+#     - udf
```
Comment (avikivity) [inline conf/scylla.yaml]: Is there a way to keep supporting `experimental: true` to avoid breaking scripts?

Comment (avikivity) [reply conf/scylla.yaml]: (it should just enable the entire set)

File: db/config.cc [hunk 3]
```diff
@@ -153,6 +157,24 @@ struct convert<db::config::seed_provider_type> {
     }
 };
 
+template <>
+class convert<enum_option<db::experimental_features>> {
+  public:
```
Comment (avikivity) [inline db/config.cc]: Our coding style doesn't use half indents for access specifiers.

File: db/config.cc [hunk 4]
```diff
@@ -876,6 +896,13 @@ const db::extensions& db::config::extensions() const {
     return *_extensions;
 }
 
+std::unordered_map<sstring, db::experimental_features::feature>& db::experimental_features::map() {
+    static const auto inst = new std::unordered_map<sstring, db::experimental_features::feature>{
```
Comment (avikivity) [inline db/config.cc]: Why `new`?

File: dist/docker/redhat/commandlineparser.py [hunk 5]
```diff
@@ -4,7 +4,7 @@
 def parse():
     parser = argparse.ArgumentParser()
     parser.add_argument('--developer-mode', default='1', choices=['0', '1'], dest='developerMode')
```
Comment (avikivity) [inline dist/docker/redhat/commandlineparser.py]: Should be folded with previous patch, to avoid bisect breakage (unless we manage to make experimental: true work)

File: conf/scylla.yaml (hunk 2 above)
Comment (dekimir) [reply conf/scylla.yaml]: In YAML that might prove difficult, because our YAML parser expects a sequence for `vector`-typed properties.  At best, we can support `experimental:\n  - true` (which would still break scripts).  Or we can have two properties: a binary `experimental` and a vector `experimental_foo`.

In CLI we have a bit more flexibility in implementation, so we could support things like `--experimental=all` or any of the backward-compatible boolean tokens (`on`, `yes`, `1`, and `true`).

File: db/config.cc (hunk 4 above)
Comment (dekimir) [reply db/config.cc]: To avoid the destruction-order problem: https://isocpp.org/wiki/faq/ctors#construct-on-first-use-v2

File: conf/scylla.yaml (hunk 2 above)
Comment (nyh) [reply conf/scylla.yaml]: We could have two different options: "experimental: true" enables everything, while "experimental_feature: ..." enables just a list of specific features.
This will also allow us to keep the "--experimental" with no options.

File: db/config.cc (hunk 4 above)
Comment (nyh) [reply db/config.cc]: What destruction-order? If it's a static variable it will only be destructed when the program shuts down, if at all. How can the order of this cause us trouble? And of course, with "new", it will never be destructed at all...

Comment (avikivity) [reply db/config.cc]: It only applies if you have a user in some static destructor, which isn't the case.

Comment (dekimir) [reply db/config.cc]: I don't currently have any static constructors or destructors using this, so technically I don't need the function at all -- I could get away with just a static member.  But this is an established best practice, to avoid future bugs and problems.  We like those, don't we? ;)

File: tests/enum_option_test.cc [hunk 6]
```diff
@@ -0,0 +1,183 @@
...
+    BOOST_CHECK_EQUAL(parse<cities>("YYZ"), cities::TO);
+    BOOST_CHECK_EQUAL(parse<cities>("TheSix"), cities::TO);
+    BOOST_CHECK_EQUAL(parse<cities>("NewYork"), cities::NY);
+    BOOST_CHECK_EQUAL(parse<cities>("NY"), cities::NY);
+    BOOST_CHECK_EQUAL(parse<cities>("NYC"), cities::NY);
+    BOOST_CHECK_EQUAL(parse<cities>("BigApple"), cities::NY);
+}
+
+BOOST_AUTO_TEST_CASE(test_multiple_format) {
+    BOOST_CHECK((std::set<std::string>{"SanFrancisco", "SF", "SFO", "Frisco"}).count(format<cities>(cities::SF)));
```
[the remark this answers is not in the document]
Comment (dekimir) [reply tests/enum_option_test.cc]: Yes.  This is because, in an unordered map, we cannot guarantee which reverse-match we'll get.

File: tests/enum_option_test.cc [hunk 7]
```diff
@@ -0,0 +1,183 @@
...
+
+namespace {
+
+struct days {
+    enum enumeration { Mo, Tu, We, Th, Fr, Sa, Su };
+    static const std::unordered_map<std::string, enumeration>& map() {
+        static const auto inst = new std::unordered_map<std::string, enumeration>{
+            {"Mon", Mo}, {"Tue", Tu}, {"Wed", We}, {"Thu", Th}, {"Fri", Fr}, {"Sat", Sa}, {"Sun", Su}
+        };
+        return *inst;
```
[the remark this answers is not in the document]
Comment (dekimir) [reply tests/enum_option_test.cc]: It will, until it doesn't.  And then we'll be chasing a shifty bug.  See discussion above.

File: utils/enum_option.hh [hunk 8]
```diff
@@ -0,0 +1,106 @@
...
+    // For program_options parser:
+    friend std::istream& operator>>(std::istream& s, enum_option<Mapper>& opt) {
+        typename map_t::key_type key;
+        s >> key;
+        const auto found = Mapper::map().find(key);
+        if (found == Mapper::map().end()) {
+            std::string text;
+            if (s.rdstate() & s.failbit) {
+                // key wasn't read successfully.
+                s >> text;
```
[the remark this answers is not in the document]
Comment (dekimir) [reply utils/enum_option.hh]: Because it makes for a better error message! :laughing: 

This read is into a string, while the failed one was into `map_t::key_type`.  For instance, maybe the key type is `int`, and `s` holds "abc", so the first read will fail.  But I still want the user to see an error saying "'abc' is not a valid option value here.

I hope I understood correctly that the `invalid_option_value` constructor takes the problem text as the argument.  I'll double-check...

File: conf/scylla.yaml (hunk 2 above)
Comment (dekimir) [reply conf/scylla.yaml]: That's what I was saying above, except with "foo" instead of "feature".

File: utils/enum_option.hh [hunk 9]
```diff
@@ -0,0 +1,106 @@
...
+///
+/// Mapper must have a static method `map()` that returns a map from a streamable key type (eg, string) to the
+/// enum in question.
+///
+/// Example:
+///
+/// struct Type {
+///   enum ty { a1, a2, b1 };
+///   const static unordered_map<string, ty>& map();
+/// };
```
[the remark this answers is not in the document]
Comment (dekimir) [reply utils/enum_option.hh]: You're right, it's not strictly necessary.  If enough people prefer passing the map directly as the `enum_option` template argument, I'm happy to do that.

File: utils/enum_option.hh [hunk 10]
```diff
@@ -0,0 +1,106 @@
...
+///   static const auto inst =
+///     new unordered_map<string, Type::ty>{{"a1", Type::a1}, {"a2", Type::a2}, {"b1", Type::b1}};
+///   return *inst;
+/// }
+/// int main(int ac, char* av[]) {
+///   namespace po = boost::program_options;
+///   po::options_description desc("Allowed options");
+///   desc.add_options()
+///     ("val", po::value<enum_option<Type>>(), "Single Type")
+///     ("vec", po::value<vector<enum_option<Type>>>()->multitoken(), "Type vector");
```
[the remark this answers is not in the document]
Comment (dekimir) [reply utils/enum_option.hh]: >     1. Is it possible to make it a set instead of a vector, to avoid duplicates and to allow the code to easily find out which option was enabled?

No, because `set` here doesn't compile.  It violates some static assert deep in Boost.

>     2. What is multitoken()?

It's what allows multiple option values: https://theboostcpplibraries.com/boost.program_options

[the remark this answers is not in the document]
Comment (dekimir) [reply utils/enum_option.hh]: I actually might remove even `vector` here, because it's an unnecessary complication.  I'll explain in the blurb that this holds a single value (just like `po::value<int>` holds just a single `int`, not a list of them).

**Comment by dekimir** [comment]
All feedback addressed, PTAL.

Note that this will still break some dtests, because `enable_user_defined_functions` is deleted.

File: db/config.cc (hunk 4 above)
Comment (avikivity) [reply db/config.cc]: You can find best practices for anything. Another best practice is not to use naked new, and another is not to leak. Yet another (my favorite) is not to use statics. You can avoid violating all best practices here by returning a temporary rather than a reference to a global. If parsing --experimental starts to dominate execution time, we can consider which best practice to violate in order to make it a static.

btw C++20 will avoid these problems with `constinit`.

Comment (dekimir) [reply db/config.cc]: > You can avoid violating all best practices here by returning a temporary 

OK, done.

**Comment by dekimir** [comment]
Addressed feedback and rebased on top of latest `next`.  PTAL.

**Comment by dekimir** [comment]
Actually, wait.  I botched the rebase, so now it shows ~2,000 files changed. :scream: I'm fixing it now...

**Comment by avikivity** [comment]
The note on the top is outdated, yes? Since --experimental is still supported.

**Comment by dekimir** [comment]
K, fixed the rebase.

**Comment by dekimir** [comment]
> The note on the top is outdated, yes? Since --experimental is still supported.

Yes, fixed now.  Thx.

**Comment by avikivity** [comment]
> Delete `--enable-user-defined-functions`.


Er, this is wrong, since it is present in Cassandra and wasn't added to gate an experimental feature.

(Cassandra needs this because their UDF are/were insecure)

**Comment by dekimir** [comment]
> > Delete `--enable-user-defined-functions`.
> 
> Er, this is wrong, since it is present in Cassandra and wasn't added to gate an experimental feature.
> 
> (Cassandra needs this because their UDF are/were insecure)

Do we currently consider UDF experimental in Scylla?  If so, should UDF be a valid value for `--experimental-features`?

**Comment by avikivity** [comment]
Yes, UDF is experimental. In general any new feature that hasn't been blessed by QA is experimental, as a sort of CYA. It also allows us to change storage formats.

**Comment by dekimir** [comment]
> Yes, UDF is experimental. In general any new feature that hasn't been blessed by QA is experimental, as a sort of CYA. It also allows us to change storage formats.

Again, should I allow `--experimental-feature=UDF`?  And if so, how should that interact with `--enable-user-defined-functions`?

**Comment by avikivity** [comment]
Yes please, and both should be set for it to work.

**Comment by avikivity** [comment]
But don't add it to this patch set, let's leave it for later.

**Comment by dekimir** [comment]
If I don't change this patchset, `--enable-user-defined-functions` will disappear, dtests will fail, and we'll stop accepting a valid Cassandra option.  If I do change this patchset _not_ to remove `--enable-user-defined-functions`, then I must also add some reasonable interaction between that and `--experimental-features=UDF`.

**Comment by avikivity** [comment]
I see. We have to un-disappear it. And the interaction is AND: both must be set for the feature to work.

**Comment by dekimir** [comment]
> I see. We have to un-disappear it. And the interaction is AND: both must be set for the feature to work.

K, done.

**Comment by avikivity** [comment]
Is the "NOTE: merging must be coordinated with changes to https://github.com/scylladb/scylla-dtest" still applicable? Since we kept --experimental.

File: conf/scylla.yaml [hunk 11]
```diff
@@ -245,7 +245,10 @@ batch_size_fail_threshold_in_kb: 50
 # broadcast_rpc_address: 1.2.3.4
```
Comment (avikivity) [inline conf/scylla.yaml]: Is "Remove the enable_user_defined_functions option, which is now redundant." still correct? I think it's not.

File: utils/enum_option.hh [hunk 12]
```diff
@@ -0,0 +1,106 @@
...
+/// Example:
+///
+/// struct Type {
+///   enum ty { a1, a2, b1 };
+///   const static unordered_map<string, ty>& map();
+/// };
+/// const unordered_map<string, Type::ty>& Type::map() {
+///   static const auto inst =
+///     new unordered_map<string, Type::ty>{{"a1", Type::a1}, {"a2", Type::a2}, {"b1", Type::b1}};
+///   return *inst;
```
[the remark this answers is not in the document]
Comment (nyh) [reply utils/enum_option.hh]: Sorry, I still don't understand why there's a "new" here...

File: utils/enum_option.hh (hunk 8 above)
[the remark this answers is not in the document]
Comment (nyh) [reply utils/enum_option.hh]: I don't want to continue bikeshedding on this relatively unimportant issue, and it appears you did test this. But I'm still curious whether it is guaranteed to work... Does a failed read guarantee that the position of the stream does not move?

File: conf/scylla.yaml (hunk 11 above)
Comment (dekimir) [reply conf/scylla.yaml]: No, it's incorrect now.  Thanks for catching this.  Fixed.

File: utils/enum_option.hh (hunk 12 above)
[the remark this answers is not in the document]
Comment (dekimir) [reply utils/enum_option.hh]: Fixed.

File: utils/enum_option.hh (hunk 8 above)
[the remark this answers is not in the document]
Comment (dekimir) [reply utils/enum_option.hh]: > I don't want to continue bikeshedding on this relatively unimportant issue, and it appears you did test this. But I'm still curious whether it is guaranteed to work... Does a failed read guarantee that the position of the stream does not move?

That's my reading of the [official word](https://en.cppreference.com/w/cpp/locale/num_get/get).  In practice, when `key_type` is `int`, this works exactly as expected (and without it, the offending option value is not included in the error message).

**Comment by avikivity** [comment]
I dequeued this:

 - doesn't show up in --help for some reason:

```
$ ./build/release/scylla --help | grep experimental
  --experimental arg                    Set to true to unlock experimental 
```

 - misleading error message:

```
11:01:29      assert e.code == 0000 and e.message == "Not implemented: LWT", e
11:01:29  AssertionError: <Error from server: code=0000 [Server error] message="Paxos is currently disabled. Start Scylla with --experimental_features=lwt to enable.">
```

should be --experimental-features (the command line options auto-translate _ to -)

 - breaks dtest:

```
11:01:29      assert e.code == 0000 and e.message == "Not implemented: LWT", e
11:01:29  AssertionError: <Error from server: code=0000 [Server error] message="Paxos is currently disabled. Start Scylla with --experimental_features=lwt to enable.">
```

This might be fixed by a coordinated change to dtest.

**Comment by nyh** [comment]
That this patch will necessitate dtest changes was obvious (and IIRC, predicted by the patch author). But how can we "coordinate" this change? Should we change the dtest code to support both pre-patch and post-patch scylla (perhaps by using "--help" or something to figure out what option dtest should use)? Is this complication worth it?

**Comment by nyh** [comment]
By the way, how do we mark this pull request "not really merged after all"? :-(

**Comment by avikivity** [comment]
I usually write "I dequeued this".

**Comment by nyh** [comment]
Writing "I dequeued this" doesn't help when someone is using https://github.com/scylladb/scylla/pulls to list the pull requests that need attention. Never mind, yet another annoying github feature...

**Comment by avikivity** [comment]
> That this patch will necessitate dtest changes was obvious (and IIRC, predicted by the patch author).

After the change that brought back --experimental, I thought changes to dtest wouldn't be needed. What broke dtest was a change to the error message. 

> But how can we "coordinate" this change?

Send pull requests to dtest and scylla simultaneously, and coordinate with maintainers to merge simultaneously.

> Should we change the dtest code to support both pre-patch and post-patch scylla (perhaps by using "--help" or something to figure out what option dtest should use)? Is this complication worth it?

No need to fly through such hoops, just prepare changes to both. These things happen from time to time, it's no big deal.

**Comment by glommer** [comment]
On Tue, Dec 10, 2019 at 5:59 AM nyh <notifications@github.com> wrote:

> Writing "I dequeued this" doesn't help when someone is using
> https://github.com/scylladb/scylla/pulls to list the pull requests that
> need attention. Never mind, yet another annoying github feature...
>

We can use tags for that, and reopen the PR.

**Comment by avikivity** [comment]
There's no "reopen" button for pull requests.

**Comment by glommer** [comment]
On Tue, Dec 10, 2019 at 10:01 AM Avi Kivity <notifications@github.com>
wrote:

> There's no "reopen" button for pull requests.
>

How nice!

In this case we can use tags. I will scan for such tags.
(Please tell me we can add a tag to a closed PR)

**Comment by avikivity** [comment]
@glommer you can add a tag to a closed PR

**Comment by glommer** [comment]
Ok, so if we standardize on a "dequeued" tag (or whatever you want) being added, I can change the scripts I am writing to recognize it.

**Comment by dekimir** [comment]
>  doesn't show up in --help for some reason:
> 
> 
> ```
> $ ./build/release/scylla --help | grep experimental
>   --experimental arg                    Set to true to unlock experimental 
> ```

Weird, it shows up for me:
```bash
localhost>./scylla --help|grep experimental
  --experimental arg                    Set to true to unlock all experimental 
  --experimental-features arg           Unlock experimental features provided 
                                        also set experimental-features=udf
```

**Comment by avikivity** [comment]
User error, I built dev and ran release.

**Comment by dekimir** [comment]
I cannot update this PR anymore, so I put my fixes in #5456.

**Comment by nyh** [comment]
By the way, all the problems we had with this pull-request being prematurely closed, before the patch actually was promoted to master, would have been solved if the branch was marked for **master**, not **next**, so the pull request will only be finally closed when it reaches master.

Note that to do this, we need pull request targets to be "master", not "next", and we need to merge them using manual git commands - not with the github GUI buttons because the latter will need to have the target being marked "next". But that (manual git commands) is what I'm usually doing anyway.
