### PR TITLE
Fix type checking in index paging

### LINKED ISSUE #8666: Mismatched types for base and view columns id: timeuuid and timeuuid
- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.3
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI

I have a global secondary index and it returns back 1020 results and if I try to retrieve anymore it throws this error ('Unable to complete the operation against any hosts', {<Host: 10.0.21.10:9042 us-east>: <Error from server: code=0000 [Server error] message="Mismatched types for base and view columns id: timeuuid and timeuuid">})

### PR DESCRIPTION
**Pull request by psarna**
When recreating the paging state from an indexed query,
a bunch of panic checks were introduced to make sure that
the code is correct. However, one of the checks is too eager -
namely, it throws an error if the base column type is not equal
to the view column type. It usually works correctly, unless the
base column type is a clustering key with DESC clustering order,
in which case the type is actually "reversed". From the point of view
of the paging state generation it's not important, because both
types deserialize in the same way, so the check should be less
strict and allow the base type to be reversed.

Tests: unit(release), along with the additional test case
       introduced in this series; the test also passes
       on Cassandra

Fixes #8666

### CODE REVIEW

File: cql3/statements/select_statement.cc [hunk 1]
```diff
@@ -461,7 +461,7 @@ generate_base_key_from_index_pk(const partition_key& index_pk, const std::option
         if (!view_col) {
             throw std::runtime_error(format("Base key column not found in the view: {}", base_col.name_as_text()));
         }
-        if (base_col.type != view_col->type) {
+        if (base_col.type->without_reversed() != *view_col->type) {
```
Comment (avikivity) [inline cql3/statements/select_statement.cc:464]: Is it possible for view_col->type to be reversed too?

Comment (avikivity) [reply cql3/statements/select_statement.cc:464]: btw, I think it's a mistake to keep the reversed attribute in the type. We move it outside, to some attributes around the clustering key. It's really a marker, not a change to the type itself. Of course this is a lot of work for small payoff, I'm not suggesting we do it.

Comment (psarna) [reply cql3/statements/select_statement.cc:464]: Yesterday I thought it can't be reversed, because during index creation the index column becomes the partition key, but the matter might be more complicated for local indexes. There, we keep the original partition key and the indexed column becomes the first clustering key. For now we don't care much, because we always ask for a specific value of the indexed column, so it doesn't matter if it's reversed or not. However, if we ever decide to implement https://github.com/scylladb/scylla/issues/5547 , it will start to matter. Then we'd also have to introduce a way of determining what kind of clustering order the user is interested in. `CREATE INDEX ON t((p),v desc)`?

But, anyway, it's not particularly costly to also call `without_reversed` on the view_col type to be double sure, so I'll send a follow-up patch. Even if it's not reproducible now, it will make the code more future-proof.
