### PR TITLE
install.sh: show warning when systemd does not support user mode

### LINKED ISSUE #7071: offline-install: Failed to get D-Bus connection: No such file or directory on CentOS 7
*Installation details*
Scylla version (or git commit hash):  scylla-unified-package-0.20200819.2e1499ee93f.tar.gz / 666.development-0.20200819.2e1499ee93f
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

### Description

The offline installation failed for a dbus connection error.

#### prepare

- curl http://downloads.scylladb.com.s3.amazonaws.com/relocatable/unstable/master/latest/scylla-unified-package-0.20200819.2e1499ee93f.tar.gz -o scylla-unified-package-0.20200819.2e1499ee93f.tar.gz
- tar xvfz scylla-unified-package-0.20200819.2e1499ee93f.tar.gz

#### install error

```
[scylla-test@amos-centos7-offline-installer offline_install]$ time ./install.sh --nonroot --prefix `pwd`/install_root
Failed to get D-Bus connection: No such file or directory

real	1m56.806s
user	0m0.978s
sys	0m7.878s
[scylla-test@amos-centos7-offline-installer offline_install]$ echo $?
1
```

```
[scylla-test@amos-centos7-offline-installer offline_install]$ ls
install_root  offline-install.sh  scylla-jmx      scylla-tools
install.sh    scylla              scylla-python3  scylla-unified-package-0.20200819.2e1499ee93f.tar.gz

[scylla-test@amos-centos7-offline-installer offline_install]$ cat /etc/redhat-release 
CentOS Linux release 7.8.2003 (Core)

[scylla-test@amos-centos7-offline-installer offline_install]$ rpm -qa |grep dbus
dbus-glib-0.100-7.el7.x86_64
python-slip-dbus-0.4.0-4.el7.noarch
dbus-libs-1.10.24-14.el7_8.x86_64
dbus-1.10.24-14.el7_8.x86_64
dbus-python-1.1.1-9.el7.x86_64
[scylla-test@amos-centos7-offline-installer offline_install]$ ps aux|grep dbus
dbus       463  0.0  0.0  66472  2196 ?        Ssl  23:31   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
```

```
[scylla-test@amos-centos7-offline-installer install_root]$ ./bin/scylla --version
666.development-0.20200819.2e1499ee93f
```

/CC @penberg @roydahan @slivne

### PR DESCRIPTION
**Pull request by syuu1228**
On older distribution such as CentOS7, it does not support systemd user mode.
On such distribution nonroot mode does not work, show error message and
reject installing before copying files.

Fixes #7071

### CODE REVIEW

**Comment by avikivity** [comment]
It is too much to reject. We can install, but not install the systemd support parts. Users can still run directly.

@eyalgutkind please provide your input - should we partially support nonroot install on CentOS 7 (with full support on CentOS 8), or drop support for CentOS 7 nonroot installs completely.

**Comment by eyalgutkind** [comment]
It might delay some users, But, in general I do not want to drag it. any more.
We can place a restriction supporting non-root installation on CentOS 8+ distros.

**Comment by penberg** [comment]
@avikivity So let's merge this now and relax the check for CentOS 7 later if needed?

**Comment by avikivity** [comment]
We're sure to have CentOS 7 users (nonroot users tend to be late adopters). The check shouldn't be complicated.

**Comment by syuu1228** [comment]
Pushed v2, not reject setup just print warning and skip running systemctl --user instead.

File: unified/install.sh [hunk 1]
```diff
@@ -80,6 +85,12 @@ while [ $# -gt 0 ]; do
     esac
 done
 
+if $nonroot && ! check_usermode_support; then
+    echo "WARNING: This distribution does not support systemd user mode, need to configure & launch Scylla manually."
```
Comment (penberg) [inline unified/install.sh:89]: Minor nit:

```WARNING: This distribution does not support systemd user mode, please configure and launch Scylla manually```

Comment (syuu1228) [reply unified/install.sh]: @penberg Fixed the message.

**Comment by avikivity** [comment]
Dequeued, breaks next. Maybe it fails in a container without systemd because it waits for keypress, or maybe something else.
