### PR TITLE
compaction/twcs: fix use after free issues

### LINKED ISSUE #25913: Scylla node coredumped after "table - Memtable flush failed due to: std::runtime_error (Timestamp resolution invalid for TWCS)"
## Packages

Scylla version: `2025.4.0~dev-20250905.b26816f80d71` with build-id `a0b2210cec9c5813ae6b104783db8f1846705a2c`

Kernel Version: `6.14.0-1012-aws`

## Issue description

Nemesis that was running before coredump **disrupt_add_drop_column**. Node logs:
```
2025-09-06T19:57:04.560 longevity-twcs-48h-master-db-node-3089674e-8  !INFO | scylla[14587]  [shard 0: gms] migration_manager - Gossiping my schema version a91478f0-8b5b-11f0-0b54-e5c19039daeb
2025-09-06T19:57:04.561 longevity-twcs-48h-master-db-node-3089674e-8  !INFO | scylla[14587]  [shard 0: gms] schema_tables - Schema version changed to a91478f0-8b5b-11f0-0b54-e5c19039daeb
2025-09-06T19:57:04.804 longevity-twcs-48h-master-db-node-3089674e-8  !ERR | scylla[14587]  [shard 3:main] table - Memtable flush failed due to: std::runtime_error (Timestamp resolution invalid for TWCS). Aborting, at 0x2389b59 0x2389710 0x23896e8 0x2793463 0x1570d39 0x5347a77 0x530d42a /opt/scylladb/libreloc/libc.so.6+0x711d3 /opt/scylladb/libreloc/libc.so.6+0xf3d2b
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   N7seastar12continuationINS_8internal22promise_base_with_typeIvEEZNS_6futureIvE16handle_exceptionIZN7replica20dirty_memory_manager9flush_oneERNS7_13memtable_listEONS7_12flush_permitEE3$_0Qoooooosr3stdE16is_invocable_r_vINS4_IT_EETL0__NSt15__exception_ptr13exception_ptrEEaaeqsr3stdE12tuple_size_vINSt11conditionalIXsr3stdE9is_same_vINS1_18future_stored_typeIJSE_EE4typeENS1_9monostateEEESt5tupleIJEESP_IJSN_EEE4typeEELi0Esr3stdE16is_invocable_r_vIvSH_SJ_Eaaeqsr3stdE12tuple_size_vIST_ELi1Esr3stdE16is_invocable_r_vISE_SH_SJ_Eaagtsr3stdE12tuple_size_vIST_ELi1Esr3stdE16is_invocable_r_vIST_SH_SJ_EEES5_OSE_EUlSU_E_ZNS5_17then_wrapped_nrvoIS5_SV_EENS_8futurizeISE_E4typeEOT0_EUlOS3_RSV_ONS_12future_stateISO_EEE_vEE
   --------
   N7seastar12continuationINS_8internal22promise_base_with_typeIvEEZNS_6futureIvE16handle_exceptionIZZZZN7replica20dirty_memory_manager17flush_when_neededEvENK3$_0clEvENKUlvE0_clEvENKUlT_E_clINS7_12flush_permitEEEDaSB_EUlNSt15__exception_ptr13exception_ptrEE_Qoooooosr3stdE16is_invocable_r_vINS4_ISB_EETL0__SG_Eaaeqsr3stdE12tuple_size_vINSt11conditionalIXsr3stdE9is_same_vINS1_18future_stored_typeIJSB_EE4typeENS1_9monostateEEESt5tupleIJEESQ_IJSO_EEE4typeEELi0Esr3stdE16is_invocable_r_vIvSK_SG_Eaaeqsr3stdE12tuple_size_vISU_ELi1Esr3stdE16is_invocable_r_vISB_SK_SG_Eaagtsr3stdE12tuple_size_vISU_ELi1Esr3stdE16is_invocable_r_vISU_SK_SG_EEES5_OSB_EUlSV_E_ZNS5_17then_wrapped_nrvoIS5_SW_EENS_8futurizeISB_E4typeEOT0_EUlOS3_RSW_ONS_12future_stateISP_EEE_vEE
2025-09-06T19:57:04.908 longevity-twcs-48h-master-db-node-3089674e-8  !INFO | systemd[1] Created slice system-systemd\x2dcoredump.slice - Slice /system/systemd-coredump.
2025-09-06T19:57:04.919 longevity-twcs-48h-master-db-node-3089674e-8  !INFO | systemd[1] Started systemd-coredump@0-20436-0.service - Process Core Dump (PID 20436/UID 0).
2025-09-06T19:57:08.749 longevity-twcs-48h-master-db-node-3089674e-8  !INFO | scylla-manager-agent[7029] {"L":"INFO","T":"2025-09-06T19:57:08.749Z","M":"http: proxy error: context canceled"}
2025-09-06T19:57:08.749 longevity-twcs-48h-master-db-node-3089674e-8  !INFO | scylla-manager-agent[7029] {"L":"ERROR","T":"2025-09-06T19:57:08.749Z","N":"http","M":"GET /gossiper/endpoint/live/","from":"10.4.8.195:38960","status":502,"bytes":0,"duration":"9ms","S":"github.com/scylladb/go-log.Logger.log\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\ngithub.com/scylladb/go-log.Logger.Error\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\nmain.(*logEntry).Write\n\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/log.go:53\nmain.newRouter.RequestLogger.RequestLogger.func5.1.1\n\tgithub.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:52\nmain.newRouter.RequestLogger.RequestLogger.func5.1\n\tgithub.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:56\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2220\ngithub.com/go-chi/chi/v5.(*Mux).ServeHTTP\n\tgithub.com/go-chi/chi/v5@v5.1.0/mux.go:90\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:3210\nnet/http.(*conn).serve\n\tnet/http/server.go:2092"}
2025-09-06T19:57:14.006 longevity-twcs-48h-master-db-node-3089674e-8  !INFO | scylla-manager-agent[7029] {"L":"INFO","T":"2025-09-06T19:57:14.006Z","M":"http: proxy error: context canceled"}
2025-09-06T19:57:14.007 longevity-twcs-48h-master-db-node-3089674e-8  !INFO | scylla-manager-agent[7029] {"L":"ERROR","T":"2025-09-06T19:57:14.006Z","N":"http","M":"GET /storage_service/scylla_release_version","from":"10.4.8.195:59112","status":502,"bytes":0,"duration":"1001ms","S":"github.com/scylladb/go-log.Logger.log\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\ngithub.com/scylladb/go-log.Logger.Error\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\nmain.(*logEntry).Write\n\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/log.go:53\nmain.newRouter.RequestLogger.RequestLogger.func5.1.1\n\tgithub.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:52\nmain.newRouter.RequestLogger.RequestLogger.func5.1\n\tgithub.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:56\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2220\ngithub.com/go-chi/chi/v5.(*Mux).ServeHTTP\n\tgithub.com/go-chi/chi/v5@v5.1.0/mux.go:90\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:3210\nnet/http.(*conn).serve\n\tnet/http/server.go:2092"}
2025-09-06T19:57:38.751 longevity-twcs-48h-master-db-node-3089674e-8  !INFO | scylla-manager-agent[7029] {"L":"ERROR","T":"2025-09-06T19:57:38.751Z","N":"http","M":"GET /agent/node_info","from":"10.4.8.195:38972","status":500,"bytes":220,"duration":"29997ms","S":"github.com/scylladb/go-log.Logger.log\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\ngithub.com/scylladb/go-log.Logger.Error\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\nmain.(*logEntry).Write\n\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/log.go:53\nmain.newRouter.RequestLogger.RequestLogger.func5.1.1\n\tgithub.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:52\nmain.newRouter.RequestLogger.RequestLogger.func5.1\n\tgithub.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:56\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2220\ngithub.com/go-chi/chi/v5.(*Mux).ServeHTTP\n\tgithub.com/go-chi/chi/v5@v5.1.0/mux.go:90\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:3210\nnet/http.(*conn).serve\n\tnet/http/server.go:2092"}
2025-09-06T19:57:38.765 longevity-twcs-48h-master-db-node-3089674e-8  !INFO | scylla-manager-agent[7029] {"L":"INFO","T":"2025-09-06T19:57:38.765Z","M":"http: proxy error: context canceled"}
2025-09-06T19:57:38.765 longevity-twcs-48h-master-db-node-3089674e-8  !INFO | scylla-manager-agent[7029] {"L":"ERROR","T":"2025-09-06T19:57:38.765Z","N":"http","M":"GET /snitch/rack?host=10.4.9.252","from":"10.4.8.195:38974","status":502,"bytes":0,"duration":"29998ms","S":"github.com/scylladb/go-log.Logger.log\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\ngithub.com/scylladb/go-log.Logger.Error\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\nmain.(*logEntry).Write\n\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/log.go:53\nmain.newRouter.RequestLogger.RequestLogger.func5.1.1\n\tgithub.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:52\nmain.newRouter.RequestLogger.RequestLogger.func5.1\n\tgithub.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:56\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2220\ngithub.com/go-chi/chi/v5.(*Mux).ServeHTTP\n\tgithub.com/go-chi/chi/v5@v5.1.0/mux.go:90\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:3210\nnet/http.(*conn).serve\n\tnet/http/server.go:2092"}
2025-09-06T19:58:09.864 longevity-twcs-48h-master-db-node-3089674e-8  !INFO | scylla-manager-agent[7029] {"L":"ERROR","T":"2025-09-06T19:58:09.864Z","N":"http","M":"GET /agent/node_info","from":"10.4.8.195:41118","status":500,"bytes":279,"duration":"30001ms","S":"github.com/scylladb/go-log.Logger.log\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\ngithub.com/scylladb/go-log.Logger.Error\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\nmain.(*logEntry).Write\n\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/log.go:53\nmain.newRouter.RequestLogger.RequestLogger.func5.1.1\n\tgithub.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:52\nmain.newRouter.RequestLogger.RequestLogger.func5.1\n\tgithub.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:56\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2220\ngithub.com/go-chi/chi/v5.(*Mux).ServeHTTP\n\tgithub.com/go-chi/chi/v5@v5.1.0/mux.go:90\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:3210\nnet/http.(*conn).serve\n\tnet/http/server.go:2092"}
2025-09-06T19:58:41.535 longevity-twcs-48h-master-db-node-3089674e-8  !INFO | scylla-manager-agent[7029] {"L":"ERROR","T":"2025-09-06T19:58:41.535Z","N":"http","M":"GET /agent/node_info","from":"10.4.8.195:41118","status":500,"bytes":279,"duration":"30003ms","S":"github.com/scylladb/go-log.Logger.log\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\ngithub.com/scylladb/go-log.Logger.Error\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\nmain.(*logEntry).Write\n\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/log.go:53\nmain.newRouter.RequestLogger.RequestLogger.func5.1.1\n\tgithub.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:52\nmain.newRouter.RequestLogger.RequestLogger.func5.1\n\tgithub.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:56\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2220\ngithub.com/go-chi/chi/v5.(*Mux).ServeHTTP\n\tgithub.com/go-chi/chi/v5@v5.1.0/mux.go:90\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:3210\nnet/http.(*conn).serve\n\tnet/http/server.go:2092"}
2025-09-06T19:58:43.004 longevity-twcs-48h-master-db-node-3089674e-8  !INFO | scylla-manager-agent[7029] {"L":"INFO","T":"2025-09-06T19:58:43.004Z","M":"http: proxy error: context canceled"}
2025-09-06T19:58:43.004 longevity-twcs-48h-master-db-node-3089674e-8  !INFO | scylla-manager-agent[7029] {"L":"ERROR","T":"2025-09-06T19:58:43.004Z","N":"http","M":"GET /storage_service/host_id","from":"10.4.8.195:36472","status":502,"bytes":0,"duration":"29997ms","S":"github.com/scylladb/go-log.Logger.log\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\ngithub.com/scylladb/go-log.Logger.Error\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\nmain.(*logEntry).Write\n\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/log.go:53\nmain.newRouter.RequestLogger.RequestLogger.func5.1.1\n\tgithub.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:52\nmain.newRouter.RequestLogger.RequestLogger.func5.1\n\tgithub.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:56\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2220\ngithub.com/go-chi/chi/v5.(*Mux).ServeHTTP\n\tgithub.com/go-chi/chi/v5@v5.1.0/mux.go:90\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:3210\nnet/http.(*conn).serve\n\tnet/http/server.go:2092"}
2025-09-06T19:58:44.022 longevity-twcs-48h-master-db-node-3089674e-8  !INFO | scylla-manager-agent[7029] {"L":"INFO","T":"2025-09-06T19:58:44.022Z","M":"http: proxy error: context canceled"}
2025-09-06T19:58:44.022 longevity-twcs-48h-master-db-node-3089674e-8  !INFO | scylla-manager-agent[7029] {"L":"ERROR","T":"2025-09-06T19:58:44.022Z","N":"http","M":"GET /storage_service/scylla_release_version","from":"10.4.8.195:39296","status":502,"bytes":0,"duration":"998ms","S":"github.com/scylladb/go-log.Logger.log\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\ngithub.com/scylladb/go-log.Logger.Error\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\nmain.(*logEntry).Write\n\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/log.go:53\nmain.newRouter.RequestLogger.RequestLogger.func5.1.1\n\tgithub.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:52\nmain.newRouter.RequestLogger.RequestLogger.func5.1\n\tgithub.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:56\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2220\ngithub.com/go-chi/chi/v5.(*Mux).ServeHTTP\n\tgithub.com/go-chi/chi/v5@v5.1.0/mux.go:90\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:3210\nnet/http.(*conn).serve\n\tnet/http/server.go:2092"}
2025-09-06T19:59:14.010 longevity-twcs-48h-master-db-node-3089674e-8  !INFO | scylla-manager-agent[7029] {"L":"INFO","T":"2025-09-06T19:59:14.009Z","M":"http: proxy error: context canceled"}
2025-09-06T19:59:14.010 longevity-twcs-48h-master-db-node-3089674e-8  !INFO | scylla-manager-agent[7029] {"L":"ERROR","T":"2025-09-06T19:59:14.009Z","N":"http","M":"GET /storage_service/scylla_release_version","from":"10.4.8.195:49616","status":502,"bytes":0,"duration":"998ms","S":"github.com/scylladb/go-log.Logger.log\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\ngithub.com/scylladb/go-log.Logger.Error\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\nmain.(*logEntry).Write\n\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/log.go:53\nmain.newRouter.RequestLogger.RequestLogger.func5.1.1\n\tgithub.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:52\nmain.newRouter.RequestLogger.RequestLogger.func5.1\n\tgithub.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:56\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2220\ngithub.com/go-chi/chi/v5.(*Mux).ServeHTTP\n\tgithub.com/go-chi/chi/v5@v5.1.0/mux.go:90\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:3210\nnet/http.(*conn).serve\n\tnet/http/server.go:2092"}
2025-09-06T19:59:15.574 longevity-twcs-48h-master-db-node-3089674e-8  !INFO | scylla-manager-agent[7029] {"L":"ERROR","T":"2025-09-06T19:59:15.574Z","N":"http","M":"GET /agent/node_info","from":"10.4.8.195:41118","status":500,"bytes":279,"duration":"30000ms","S":"github.com/scylladb/go-log.Logger.log\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\ngithub.com/scylladb/go-log.Logger.Error\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\nmain.(*logEntry).Write\n\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/log.go:53\nmain.newRouter.RequestLogger.RequestLogger.func5.1.1\n\tgithub.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:52\nmain.newRouter.RequestLogger.RequestLogger.func5.1\n\tgithub.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:56\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2220\ngithub.com/go-chi/chi/v5.(*Mux).ServeHTTP\n\tgithub.com/go-chi/chi/v5@v5.1.0/mux.go:90\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:3210\nnet/http.(*conn).serve\n\tnet/http/server.go:2092"}
2025-09-06T19:59:52.091 longevity-twcs-48h-master-db-node-3089674e-8  !INFO | scylla-manager-agent[7029] {"L":"ERROR","T":"2025-09-06T19:59:52.091Z","N":"http","M":"GET /agent/node_info","from":"10.4.8.195:41118","status":500,"bytes":279,"duration":"30003ms","S":"github.com/scylladb/go-log.Logger.log\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\ngithub.com/scylladb/go-log.Logger.Error\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\nmain.(*logEntry).Write\n\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/log.go:53\nmain.newRouter.RequestLogger.RequestLogger.func5.1.1\n\tgithub.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:52\nmain.newRouter.RequestLogger.RequestLogger.func5.1\n\tgithub.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:56\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2220\ngithub.com/go-chi/chi/v5.(*Mux).ServeHTTP\n\tgithub.com/go-chi/chi/v5@v5.1.0/mux.go:90\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:3210\nnet/http.(*conn).serve\n\tnet/http/server.go:2092"}
2025-09-06T20:00:14.029 longevity-twcs-48h-master-db-node-3089674e-8  !INFO | scylla-manager-agent[7029] {"L":"INFO","T":"2025-09-06T20:00:14.029Z","M":"http: proxy error: context canceled"}
2025-09-06T20:00:14.029 longevity-twcs-48h-master-db-node-3089674e-8  !INFO | scylla-manager-agent[7029] {"L":"ERROR","T":"2025-09-06T20:00:14.029Z","N":"http","M":"GET /storage_service/scylla_release_version","from":"10.4.8.195:53708","status":502,"bytes":0,"duration":"998ms","S":"github.com/scylladb/go-log.Logger.log\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\ngithub.com/scylladb/go-log.Logger.Error\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\nmain.(*logEntry).Write\n\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/log.go:53\nmain.newRouter.RequestLogger.RequestLogger.func5.1.1\n\tgithub.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:52\nmain.newRouter.RequestLogger.RequestLogger.func5.1\n\tgithub.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:56\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2220\ngithub.com/go-chi/chi/v5.(*Mux).ServeHTTP\n\tgithub.com/go-chi/chi/v5@v5.1.0/mux.go:90\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:3210\nnet/http.(*conn).serve\n\tnet/http/server.go:2092"}
2025-09-06T20:00:36.019 longevity-twcs-48h-master-db-node-3089674e-8  !INFO | scylla-manager-agent[7029] {"L":"ERROR","T":"2025-09-06T20:00:36.019Z","N":"http","M":"GET /agent/node_info","from":"10.4.8.195:41118","status":500,"bytes":278,"duration":"30006ms","S":"github.com/scylladb/go-log.Logger.log\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\ngithub.com/scylladb/go-log.Logger.Error\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\nmain.(*logEntry).Write\n\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/log.go:53\nmain.newRouter.RequestLogger.RequestLogger.func5.1.1\n\tgithub.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:52\nmain.newRouter.RequestLogger.RequestLogger.func5.1\n\tgithub.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:56\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2220\ngithub.com/go-chi/chi/v5.(*Mux).ServeHTTP\n\tgithub.com/go-chi/chi/v5@v5.1.0/mux.go:90\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:3210\nnet/http.(*conn).serve\n\tnet/http/server.go:2092"}
2025-09-06T20:00:36.721 longevity-twcs-48h-master-db-node-3089674e-8  !CRIT | systemd-coredump[20437] Process 14587 (scylla) of user 106 dumped core.

Module p11-kit-trust.so from rpm p11-kit-0.25.5-5.fc42.x86_64
Module libicudata.so.76 from rpm icu-76.1-4.fc42.x86_64
Module libssl.so.3 from rpm openssl-3.2.4-4.fc42.x86_64
Module libsasl2.so.3 from rpm cyrus-sasl-2.1.28-30.fc42.x86_64
Module libevent-2.1.so.7 from rpm libevent-2.1.12-15.fc42.x86_64
Module libcap.so.2 from rpm libcap-2.73-2.fc42.x86_64
Module libffi.so.8 from rpm libffi-3.4.6-5.fc42.x86_64
Module libboost_unit_test_framework.so.1.83.0 from rpm boost-1.83.0-12.fc42.x86_64
Module liblua-5.4.so from rpm lua-5.4.8-1.fc42.x86_64
Module libjsoncpp.so.26 from rpm jsoncpp-1.9.6-1.fc42.x86_64
Module libsystemd.so.0 from rpm systemd-257.7-1.fc42.x86_64
Module libdeflate.so.0 from rpm libdeflate-1.24-1.fc42.x86_64
Module libxxhash.so.0 from rpm xxhash-0.8.3-2.fc42.x86_64
Module libicui18n.so.76 from rpm icu-76.1-4.fc42.x86_64
Module libicuuc.so.76 from rpm icu-76.1-4.fc42.x86_64
Module libboost_regex.so.1.83.0 from rpm boost-1.83.0-12.fc42.x86_64
Module libboost_date_time.so.1.83.0 from rpm boost-1.83.0-12.fc42.x86_64
Module libcryptopp.so.8 from rpm cryptopp-8.8.0-10.fc42.x86_64
Module libcrypt.so.2 from rpm libxcrypt-4.4.38-7.fc42.x86_64
Module libcrypto.so.3 from rpm openssl-3.2.4-4.fc42.x86_64
Module libsnappy.so.1 from rpm snappy-1.2.1-4.fc42.x86_64
Module libyaml-cpp.so.0.8 from rpm yaml-cpp-0.8.0-2.fc42.x86_64
Module libudev.so.1 from rpm systemd-257.7-1.fc42.x86_64
Module libhwloc.so.15 from rpm hwloc-2.12.0-1.fc42.x86_64
Module libz.so.1 from rpm zlib-ng-2.2.4-3.fc42.x86_64
Module libprotobuf.so.30 from rpm protobuf-3.19.6-11.fc42.x86_64
Module libp11-kit.so.0 from rpm p11-kit-0.25.5-5.fc42.x86_64
Module libidn2.so.0 from rpm libidn2-2.3.8-1.fc42.x86_64
Module libtasn1.so.6 from rpm libtasn1-4.20.0-1.fc42.x86_64
Module libnettle.so.8 from rpm nettle-3.10.1-1.fc42.x86_64
Module libhogweed.so.6 from rpm nettle-3.10.1-1.fc42.x86_64
Module libunistring.so.5 from rpm libunistring-1.1-9.fc42.x86_64
Module libgmp.so.10 from rpm gmp-6.3.0-4.fc42.x86_64
Module libgnutls.so.30 from rpm gnutls-3.8.10-1.fc42.x86_64
Module liblz4.so.1 from rpm lz4-1.10.0-2.fc42.x86_64
Module liburing.so.2 from rpm liburing-2.9-1.fc42.x86_64
Module libsctp.so.1 from rpm lksctp-tools-1.0.20-2.fc42.x86_64
Module libfmt.so.11 from rpm fmt-11.1.4-1.fc42.x86_64
Module libcares.so.2 from rpm c-ares-1.34.5-1.fc42.x86_64
Module libboost_program_options.so.1.83.0 from rpm boost-1.83.0-12.fc42.x86_64
Stack trace of thread 14593:
#0  0x0000000042e04735 abort (libc.so.6 + 0x1735)
#1  0x00000000027934ab _ZZN7replica5table20seal_active_memtableERNS_16compaction_groupEONS_12flush_permitEENK3$_0clESt8functionIFN7seastar6futureIvEEvEE.resume (scylla + 0x25934ab)
#2  0x0000000001570d3a _ZN7seastar7reactor6do_runEv (scylla + 0x1370d3a)
#3  0x0000000005347a78 _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureERKNS1_11smp_optionsERKNS1_15reactor_optionsEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x5147a78)
#4  0x000000000530d42b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x510d42b)
#5  0x0000000042e741d4 start_thread (libc.so.6 + 0x711d4)
#6  0x0000000042ef6d2c __clone3 (libc.so.6 + 0xf3d2c)

Stack trace of thread 14591:
#0  0x0000000001563188 _ZN8logalloc11region_impl11alloc_smallERKNS0_17object_descriptorEjm (scylla + 0x1363188)
#1  0x000000000308f52d _ZN19allocation_strategy9constructI10rows_entryJRK6schemaS4_RS1_EEEPT_DpOT0_ (scylla + 0x2e8f52d)
#2  0x000000000184dffe _ZN21mutation_partition_v219apply_monotonicallyERK6schemaS2_OS_P13cache_trackerR26mutation_application_statsN7seastar20noncopyable_functionIDoFbvEEER12apply_resumeNS8_10bool_classI13evictable_tagEE (scylla + 0x164dffe)
#3  0x0000000001847216 _ZN18partition_snapshot24merge_partition_versionsER26mutation_application_stats (scylla + 0x1647216)
#4  0x0000000001ddcccd _ZN7seastar11lambda_taskIZNS_21with_scheduling_groupIZZN21mutation_cleaner_impl12start_workerEvEN3$_0clEvEUlvE_JEQsr3stdE31is_nothrow_move_constructible_vIT_EEEDaNS_16scheduling_groupES5_DpOT0_EUlvE_E15run_and_disposeEv (scylla + 0x1bdcccd)
#5  0x0000000001570da9 _ZN7seastar7reactor6do_runEv (scylla + 0x1370da9)
#6  0x0000000005347a78 _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureERKNS1_11smp_optionsERKNS1_15reactor_optionsEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x5147a78)
#7  0x000000000530d42b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x510d42b)
#8  0x0000000042e741d4 start_thread (libc.so.6 + 0x711d4)
#9  0x0000000042ef6d2c __clone3 (libc.so.6 + 0xf3d2c)

Stack trace of thread 14587:
#0  0x000000000184b193 _ZN21mutation_partition_v219apply_monotonicallyERK6schemaS2_OS_P13cache_trackerR26mutation_application_statsN7seastar20noncopyable_functionIDoFbvEEER12apply_resumeNS8_10bool_classI13evictable_tagEE (scylla + 0x164b193)
#1  0x0000000001847216 _ZN18partition_snapshot24merge_partition_versionsER26mutation_application_stats (scylla + 0x1647216)
#2  0x0000000001ddcccd _ZN7seastar11lambda_taskIZNS_21with_scheduling_groupIZZN21mutation_cleaner_impl12start_workerEvEN3$_0clEvEUlvE_JEQsr3stdE31is_nothrow_move_constructible_vIT_EEEDaNS_16scheduling_groupES5_DpOT0_EUlvE_E15run_and_disposeEv (scylla + 0x1bdcccd)
#3  0x0000000001570da9 _ZN7seastar7reactor6do_runEv (scylla + 0x1370da9)
#4  0x0000000002c1c0f9 _ZN7seastar7reactor3runEv (scylla + 0x2a1c0f9)
#5  0x0000000002c1b90a _ZN7seastar12app_template14run_deprecatedEiPPcOSt8functionIFvvEE (scylla + 0x2a1b90a)
#6  0x0000000002c1b363 _ZN7seastar12app_template3runEiPPcOSt8functionIFNS_6futureIiEEvEE (scylla + 0x2a1b363)
#7  0x00000000026e9d4f _ZL11scylla_mainiPPc (scylla + 0x24e9d4f)
#8  0x0000000002c1e213 main (scylla + 0x2a1e213)
#9  0x0000000042e065f5 __libc_start_call_main (libc.so.6 + 0x35f5)
#10 0x0000000042e066a8 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x36a8)
#11 0x0000000003207f75 _start (scylla + 0x3007f75)

Stack trace of thread 14594:
#0  0x0000000042e7c6c2 __syscall_cancel_arch (libc.so.6 + 0x796c2)
#1  0x0000000042e709da __internal_syscall_cancel (libc.so.6 + 0x6d9da)
#2  0x0000000042e70a24 __syscall_cancel (libc.so.6 + 0x6da24)
#3  0x0000000042eea1ee read (libc.so.6 + 0xe71ee)
#4  0x000000000535ffa7 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1ENS1_13basic_sstringIcjLj15ELb1EEERNS1_9file_descEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x515ffa7)
#5  0x000000000530d42b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x510d42b)
#6  0x0000000042e741d4 start_thread (libc.so.6 + 0x711d4)
#7  0x0000000042ef6d2c __clone3 (libc.so.6 + 0xf3d2c)

Stack trace of thread 14595:
#0  0x0000000042e7c6c2 __syscall_cancel_arch (libc.so.6 + 0x796c2)
#1  0x0000000042e709da __internal_syscall_cancel (libc.so.6 + 0x6d9da)
#2  0x0000000042e70a24 __syscall_cancel (libc.so.6 + 0x6da24)
#3  0x0000000042eea1ee read (libc.so.6 + 0xe71ee)
#4  0x000000000535ffa7 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1ENS1_13basic_sstringIcjLj15ELb1EEERNS1_9file_descEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x515ffa7)
#5  0x000000000530d42b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x510d42b)
#6  0x0000000042e741d4 start_thread (libc.so.6 + 0x711d4)
#7  0x0000000042ef6d2c __clone3 (libc.so.6 + 0xf3d2c)

Stack trace of thread 14597:
#0  0x0000000042e7c6c2 __syscall_cancel_arch (libc.so.6 + 0x796c2)
#1  0x0000000042e709da __internal_syscall_cancel (libc.so.6 + 0x6d9da)
#2  0x0000000042e70a24 __syscall_cancel (libc.so.6 + 0x6da24)
#3  0x0000000042eea1ee read (libc.so.6 + 0xe71ee)
#4  0x000000000535ffa7 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1ENS1_13basic_sstringIcjLj15ELb1EEERNS1_9file_descEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x515ffa7)
#5  0x000000000530d42b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x510d42b)
#6  0x0000000042e741d4 start_thread (libc.so.6 + 0x711d4)
#7  0x0000000042ef6d2c __clone3 (libc.so.6 + 0xf3d2c)

Stack trace of thread 14590:
#0  0x0000000042e7c6c2 __syscall_cancel_arch (libc.so.6 + 0x796c2)
#1  0x0000000042e709da __internal_syscall_cancel (libc.so.6 + 0x6d9da)
#2  0x0000000042e7104c __futex_abstimed_wait_common (libc.so.6 + 0x6e04c)
#3  0x0000000042e7371e pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x7071e)
#4  0x0000000043444b20 _ZNSt18condition_variable4waitERSt11unique_lockISt5mutexE (libstdc++.so.6 + 0x44b20)
#5  0x0000000002e14836 _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN5utils12alien_worker5spawnERN7seastar6loggerEiRKNS5_13basic_sstringIcjLj15ELb1EEEE3$_0EEEEE6_M_runEv (scylla + 0x2c14836)
#6  0x000000004344e164 execute_native_thread_routine (libstdc++.so.6 + 0x4e164)
#7  0x0000000042e741d4 start_thread (libc.so.6 + 0x711d4)
#8  0x0000000042ef6d2c __clone3 (libc.so.6 + 0xf3d2c)

Stack trace of thread 14589:
#0  0x0000000042e7c6c2 __syscall_cancel_arch (libc.so.6 + 0x796c2)
#1  0x0000000042e709da __internal_syscall_cancel (libc.so.6 + 0x6d9da)
#2  0x0000000042e7104c __futex_abstimed_wait_common (libc.so.6 + 0x6e04c)
#3  0x0000000042e7371e pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x7071e)
#4  0x0000000043444b20 _ZNSt18condition_variable4waitERSt11unique_lockISt5mutexE (libstdc++.so.6 + 0x44b20)
#5  0x0000000002e14836 _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN5utils12alien_worker5spawnERN7seastar6loggerEiRKNS5_13basic_sstringIcjLj15ELb1EEEE3$_0EEEEE6_M_runEv (scylla + 0x2c14836)
#6  0x000000004344e164 execute_native_thread_routine (libstdc++.so.6 + 0x4e164)
#7  0x0000000042e741d4 start_thread (libc.so.6 + 0x711d4)
#8  0x0000000042ef6d2c __clone3 (libc.so.6 + 0xf3d2c)

Stack trace of thread 14596:
#0  0x0000000042e7c6c2 __syscall_cancel_arch (libc.so.6 + 0x796c2)
#1  0x0000000042e709da __internal_syscall_cancel (libc.so.6 + 0x6d9da)
#2  0x0000000042e70a24 __syscall_cancel (libc.so.6 + 0x6da24)
#3  0x0000000042eea1ee read (libc.so.6 + 0xe71ee)
#4  0x000000000535ffa7 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1ENS1_13basic_sstringIcjLj15ELb1EEERNS1_9file_descEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x515ffa7)
#5  0x000000000530d42b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x510d42b)
#6  0x0000000042e741d4 start_thread (libc.so.6 + 0x711d4)
#7  0x0000000042ef6d2c __clone3 (libc.so.6 + 0xf3d2c)

Stack trace of thread 14592:
#0  0x0000000001b20a1a _ZZN7seastar3rpc11send_helperIN4netw10serializerENS2_14messaging_verbENS0_12no_wait_typeEJ15frozen_mutationN5utils12small_vectorIN3gms12inet_addressELm3EEESA_jmSt8optionalIN7tracing10trace_infoEESt7variantIJSt9monostateN2db24per_partition_rate_limit12account_onlyENSJ_19account_and_enforceEEEN7service13fencing_tokenENS8_INS7_11tagged_uuidIN7locator11host_id_tagEEELm3EEESS_EEEDaT0_NS0_9signatureIFT1_DpT2_EEEEN7shelper4sendERNS0_6clientESC_INSt6chrono10time_pointINS_12lowres_clockENS14_8durationIlSt5ratioILl1ELl1000000000EEEEEEEPNS0_11cancellableERKS6_RKSB_RKSA_RKjRKmRKSF_RKSM_RKSO_RKST_RKSS_ (scylla + 0x1920a1a)
#1  0x0000000001b11fde _ZN7service13storage_proxy22send_to_live_endpointsEmNSt6chrono10time_pointIN7seastar12lowres_clockENS1_8durationIlSt5ratioILl1ELl1000000000EEEEEE (scylla + 0x1911fde)
#2  0x0000000001b0ce38 _ZN7service13storage_proxy12mutate_beginEN5utils12small_vectorINS0_23unique_response_handlerELm1EEEN2db17consistency_levelEN7tracing15trace_state_ptrESt8optionalINSt6chrono10time_pointIN7seastar12lowres_clockENSA_8durationIlSt5ratioILl1ELl1000000000EEEEEEE (scylla + 0x190ce38)
#3  0x0000000001afd830 _ZN7service13storage_proxy9do_mutateEN5utils14chunked_vectorI8mutationLm131072EEEN2db17consistency_levelENSt6chrono10time_pointIN7seastar12lowres_clockENS7_8durationIlSt5ratioILl1ELl1000000000EEEEEEN7tracing15trace_state_ptrE14service_permitbNS9_10bool_classINS5_34allow_per_partition_rate_limit_tagEEENS9_13lw_shared_ptrIN3cdc24operation_result_trackerEEENS_40storage_proxy_coordinator_mutate_optionsE (scylla + 0x18fd830)
#4  0x0000000001afc144 _ZZN7seastar35inheriting_concrete_execution_stageINS_6futureIN5boost10outcome_v212basic_resultIvN5utils19exception_containerIJN10exceptions32mutation_write_timeout_exceptionENS7_22read_timeout_exceptionENS7_22read_failure_exceptionENS7_20rate_limit_exceptionENS7_20overloaded_exceptionENS7_35read_failure_exception_with_timeoutEEEENS5_32exception_container_throw_policyEEEEEJPN7service13storage_proxyENS5_14chunked_vectorI8mutationLm131072EEEN2db17consistency_levelENSt6chrono10time_pointINS_12lowres_clockENSQ_8durationIlSt5ratioILl1ELl1000000000EEEEEEN7tracing15trace_state_ptrE14service_permitbNS_10bool_classINSO_34allow_per_partition_rate_limit_tagEEENS_13lw_shared_ptrIN3cdc24operation_result_trackerEEENSI_40storage_proxy_coordinator_mutate_optionsEEE20make_stage_for_groupENS_16scheduling_groupEENKUlSK_SN_SP_SX_SZ_S10_bS13_S17_S18_E_clESK_SN_SP_SX_SZ_S10_bS13_S17_S18_ (scylla + 0x18fc144)
#5  0x0000000001afa060 _ZN7seastar24concrete_execution_stageINS_6futureIN5boost10outcome_v212basic_resultIvN5utils19exception_containerIJN10exceptions32mutation_write_timeout_exceptionENS7_22read_timeout_exceptionENS7_22read_failure_exceptionENS7_20rate_limit_exceptionENS7_20overloaded_exceptionENS7_35read_failure_exception_with_timeoutEEEENS5_32exception_container_throw_policyEEEEEJPN7service13storage_proxyENS5_14chunked_vectorI8mutationLm131072EEEN2db17consistency_levelENSt6chrono10time_pointINS_12lowres_clockENSQ_8durationIlSt5ratioILl1ELl1000000000EEEEEEN7tracing15trace_state_ptrE14service_permitbNS_10bool_classINSO_34allow_per_partition_rate_limit_tagEEENS_13lw_shared_ptrIN3cdc24operation_result_trackerEEENSI_40storage_proxy_coordinator_mutate_optionsEEE8do_flushEv (scylla + 0x18fa060)
#6  0x000000000530208a _ZN7seastar11lambda_taskIZNS_15execution_stage5flushEvE3$_0E15run_and_disposeEv.llvm.17749545816119437506 (scylla + 0x510208a)
#7  0x0000000001570da9 _ZN7seastar7reactor6do_runEv (scylla + 0x1370da9)
#8  0x0000000005347a78 _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureERKNS1_11smp_optionsERKNS1_15reactor_optionsEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x5147a78)
#9  0x000000000530d42b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x510d42b)
#10 0x0000000042e741d4 start_thread (libc.so.6 + 0x711d4)
#11 0x0000000042ef6d2c __clone3 (libc.so.6 + 0xf3d2c)
ELF object binary architecture: AMD x86-64

2025-09-06T20:00:36.848 longevity-twcs-48h-master-db-node-3089674e-8  !INFO | systemd[1] systemd-coredump@0-20436-0.service: Deactivated successfully.
2025-09-06T20:00:36.849 longevity-twcs-48h-master-db-node-3089674e-8  !INFO | systemd[1] systemd-coredump@0-20436-0.service: Consumed 2min 23.401s CPU time.
```

There is no usual backtrace, just stack traces for threads

## Impact

Node coredumped

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 6 nodes (i3en.xlarge)

Scylla Nodes used in this run:

    - longevity-twcs-48h-master-db-node-3089674e-9 (34.242.163.114 | 10.4.9.252) (shards: 4)

    - longevity-twcs-48h-master-db-node-3089674e-8 (34.242.152.139 | 10.4.8.42) (shards: 4)

    - longevity-twcs-48h-master-db-node-3089674e-7 (34.241.242.18 | 10.4.11.48) (shards: 4)

    - longevity-twcs-48h-master-db-node-3089674e-6 (34.245.226.33 | 10.4.9.18) (shards: 4)

    - longevity-twcs-48h-master-db-node-3089674e-5 (176.34.207.222 | 10.4.9.80) (shards: 4)

    - longevity-twcs-48h-master-db-node-3089674e-4 (34.245.219.54 | 10.4.11.47) (shards: 4)

    - longevity-twcs-48h-master-db-node-3089674e-3 (18.200.234.128 | 10.4.9.251) (shards: 4)

    - longevity-twcs-48h-master-db-node-3089674e-2 (3.254.55.39 | 10.4.11.64) (shards: 4)

    - longevity-twcs-48h-master-db-node-3089674e-10 (54.74.141.188 | 10.4.8.66) (shards: 4)

    - longevity-twcs-48h-master-db-node-3089674e-1 (54.78.193.56 | 10.4.9.244) (shards: 4)

OS / Image: `ami-0e209d17d844f6dad` (aws: N/A)

Test: `longevity-twcs-48h-test`
Test id: `3089674e-5a66-41e4-9f27-333e8c306b8b`
Test name: `scylla-master/tier1/longevity-twcs-48h-test`

    Test method: `longevity_twcs_test.TWCSLongevityTest.test_custom_time`

Test config file(s):

- [longevity-twcs-48h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/6b878721d50995175e6135d5661b25925585695d/test-cases/longevity/longevity-twcs-48h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 3089674e-5a66-41e4-9f27-333e8c306b8b`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=3089674e-5a66-41e4-9f27-333e8c306b8b)
- Show all stored logs command: `$ hydra investigate show-logs 3089674e-5a66-41e4-9f27-333e8c306b8b`

## Logs:

    - **[longevity-twcs-48h-master-db-node-3089674e-4](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/3089674e-5a66-41e4-9f27-333e8c306b8b/log/longevity-twcs-48h-master-db-node-3089674e-4/download)**

    - **[longevity-twcs-48h-master-db-node-3089674e-1](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/3089674e-5a66-41e4-9f27-333e8c306b8b/log/longevity-twcs-48h-master-db-node-3089674e-1/download)**

    - **[longevity-twcs-48h-master-db-node-3089674e-3](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/3089674e-5a66-41e4-9f27-333e8c306b8b/log/longevity-twcs-48h-master-db-node-3089674e-3/download)**

    - **[longevity-twcs-48h-master-db-node-3089674e-10](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/3089674e-5a66-41e4-9f27-333e8c306b8b/log/longevity-twcs-48h-master-db-node-3089674e-10/download)**

    - **[core.scylla-longevity-twcs-48h-master-db-node-3089674e-8-2025-09-06_20-03-33.gz](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/3089674e-5a66-41e4-9f27-333e8c306b8b/log/core.scylla-longevity-twcs-48h-master-db-node-3089674e-8-2025-09-06_20-03-33.gz/download)**

    - **[db-cluster-3089674e.tar.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/3089674e-5a66-41e4-9f27-333e8c306b8b/log/db-cluster-3089674e.tar.zst/download)**

    - **[schema-logs-3089674e.tar.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/3089674e-5a66-41e4-9f27-333e8c306b8b/log/schema-logs-3089674e.tar.zst/download)**

    - **[sct-runner-events-3089674e.tar.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/3089674e-5a66-41e4-9f27-333e8c306b8b/log/sct-runner-events-3089674e.tar.zst/download)**

    - **[sct-3089674e.log.tar.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/3089674e-5a66-41e4-9f27-333e8c306b8b/log/sct-3089674e.log.tar.zst/download)**

    - **[loader-set-3089674e.tar.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/3089674e-5a66-41e4-9f27-333e8c306b8b/log/loader-set-3089674e.tar.zst/download)**

    - **[monitor-set-3089674e.tar.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/3089674e-5a66-41e4-9f27-333e8c306b8b/log/monitor-set-3089674e.tar.zst/download)**

    - **[builder-3089674e.log.tar.gz](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/3089674e-5a66-41e4-9f27-333e8c306b8b/log/builder-3089674e.log.tar.gz/download)**

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tier1/job/longevity-twcs-48h-test/87/)
[Argus](https://argus.scylladb.com/test/ecd497c0-82d6-4269-b053-f5c2157e04ae/runs?additionalRuns[]=3089674e-5a66-41e4-9f27-333e8c306b8b)
</details>

### PR DESCRIPTION
**Pull request by lkshminarayanan**
The `compaction_strategy_state` class holds strategy specific state via
a `std::variant` containing different state types. When a compaction
strategy performs compaction, it retrieves a reference to its state from
the `compaction_strategy_state` object. If the table's compaction
strategy is ALTERed while a compaction is in progress, the
`compaction_strategy_state` object gets replaced, destroying the old
state. This leaves the ongoing compaction holding a dangling reference,
resulting in a use after free.

Fix this by using `seastar::shared_ptr` for the state variant
alternatives(`leveled_compaction_strategy_state_ptr` and
`time_window_compaction_strategy_state_ptr`). The compaction strategies
now hold a copy of the shared_ptr, ensuring the state remains valid for
the duration of the compaction even if the strategy is altered.

The `compaction_strategy_state` itself is still passed by reference and
only the variant alternatives use shared_ptrs. This allows ongoing
compactions to retain ownership of the state independently of the
wrapper's lifetime.
 
The method `maybe_wait_for_sstable_count_reduction()`, when retrieving
the list of sstables for a possible compaction, holds a reference to the
compaction strategy. If the strategy is updated during execution, it can
cause a use after free issue. To prevent this, hold a copy of the
compaction strategy so it isn’t yanked away during the method’s
execution.

Fixes #25913

Issue probably started after 9d3755f276135, so backport to 2025.4

### CODE REVIEW

**Comment by lkshminarayanan** [comment]
@raphaelsc copying the strategy locally and passing it down to lower methods fixed the issue. Let me know if this is sufficient.

File: compaction/time_window_compaction_strategy.cc [hunk 1]
```diff
@@ -335,7 +336,7 @@ time_window_compaction_strategy::get_reshaping_job(std::vector<sstables::shared_
 
 future<compaction_descriptor>
 time_window_compaction_strategy::get_sstables_for_compaction(compaction_group_view& table_s, strategy_control& control) {
-    auto& state = get_state(table_s);
+    auto state = get_state(table_s);
     auto compaction_time = gc_clock::now();
```
Comment (raphaelsc) [inline compaction/time_window_compaction_strategy.cc:340]: don't we have to patch table_state::get_compaction_strategy_state() to return shared ptr? otherwise, state is not preserved across calls to get_sstables_for_compaction().

Comment (lkshminarayanan) [reply compaction/time_window_compaction_strategy.cc:340]: okay. I misunderstood how a state is being used. I'll update the PR to hold shared pointer to a state.

Comment (lkshminarayanan) [reply compaction/time_window_compaction_strategy.cc:340]: I have updated TWCS and LCS to hold shared_ptr to the state when executing `get_sstables_for_compaction`.

**Comment by lkshminarayanan** [comment]
Changelog V2 :
 - Updated the compaction strategies to hold shared_ptrs to the state to prevent the state from being dropped during compaction.

File: compaction/time_window_compaction_strategy.cc [hunk 2]
```diff
@@ -361,7 +361,7 @@ time_window_compaction_strategy::get_sstables_for_compaction(compaction_group_vi
         clogger.debug("[{}] TWCS skipping check for fully expired SSTables", fmt::ptr(this));
     }
 
-    auto compaction_candidates = get_next_non_expired_sstables(table_s, control, std::move(candidates), compaction_time);
+    auto compaction_candidates = get_next_non_expired_sstables(table_s, control, std::move(candidates), compaction_time, state);
```
Comment (raphaelsc) [inline compaction/time_window_compaction_strategy.cc]: alternatively manager could have fed compaction_strategy_state_ptr into get_sstables_for_compaction() and the strategy is responsible for performing the conversion on a stable ptr. But I think this is good enough for now.
