### PR TITLE
schema_tables: notify table deletions before creations

### LINKED ISSUE #4382: mv_populating_from_existing_data_during_node_stop_test failed: View ks.tm_table_mv_2 not built
Scylla version 77a0d5c5da46521d70a29df62338ee27f6b5a518
scylladb/scylla-dtest@3d5f8781ba2ce9cd9053cc7d615a8aef695a1972

Seen in [next/668/testReport/materialized_views_test/TestMaterializedViews/mv_populating_from_existing_data_during_node_stop_test](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/next/668/testReport/materialized_views_test/TestMaterializedViews/mv_populating_from_existing_data_during_node_stop_test/):
```
Error Message
View ks.tm_table_mv_2 not built

Stacktrace
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/next/scylla-dtest/materialized_views_test.py", line 587, in mv_populating_from_existing_data_during_node_stop_test
    self._mv_populating_from_existing_data_during_changes_test('stop node', nodes=4, rf=3, mvs=10, prefill=40000, fail=False)
  File "/jenkins/workspace/scylla-master/next/scylla-dtest/materialized_views_test.py", line 653, in _mv_populating_from_existing_data_during_changes_test
    wait_for_view(cluster=self.cluster, session=session, ks=tm.keyspace, view=mv_name)
  File "/jenkins/workspace/scylla-master/next/scylla-dtest/scylla_tools.py", line 905, in wait_for_view
    raise Exception(error_msg)
```

Node logs are [here](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/next/668/artifact/logs-release.2/1554102223280_materialized_views_test.TestMaterializedViews.mv_populating_from_existing_data_during_node_stop_test/)

### PR DESCRIPTION
**Pull request by psarna**
schema_tables: notify table deletions before creations
    
    If a set of mutations contains both an entry that deletes a table
    and an entry that adds a table with the same name, it's expected
    to be a replacement operation (delete old + create new),
    rather than a useless "try to create a table even though it exists
    already and then immediately delete the original one" operation.
    As such, notifications about the deletions should be performed
    before notifications about the creations. The place that originally
    suffered from this wrong order is view building - which in this case
    created an incorrect duplicated entry in the view building bookkeeping,
    and then immediately deleted it, resulting in having old, deprecated
    entries with stale UUIDS lying in the build queue and never proceeding,
    because the underlying table is long gone.
    The issue is fixed by ensuring the order of notifications:
     - drops are announced first, view drops are announced before table drops;
     - creations follow, table creations are announced before views;
     - finally, changes to tables and views are announced;
    
    Fixes #4382
    
    Tests: unit(dev), mv_populating_from_existing_data_during_node_stop_test

### CODE REVIEW

**Comment by psarna** [comment]
@bhalevy I expect this patch to address multiple issues with `mv_populating_from_existing_data_during_node_stop_test` test.

/cc @eliransin @nyh

**Comment by psarna** [comment]
Tests: unit(dev), mv_populating_from_existing_data_during_node_stop_test

**Comment by psarna** [comment]
ping! @bhalevy @avikivity @nyh - it fixes problems in multiple dtests - pretty much all related to restarting nodes while building views.

File: db/schema_tables.cc [hunk 1]
```diff
@@ -1053,12 +1053,12 @@ static void merge_tables_and_views(distributed<service::storage_proxy>& proxy,
             std::vector<future<>> notifications;
             notifications.reserve(tables_diff.size() + views_diff.size());
             auto notify = [&] (auto& r, auto&& f) { boost::range::transform(r, std::back_inserter(notifications), f); };
+            notify(tables_diff.dropped, [&] (auto&& dt) { return mm.notify_drop_column_family(dt.schema); });
```
Comment (tgrabiec) [inline db/schema_tables.cc]: I think the order is still not enforced. 

notify() only collects futures, doesn't wait for them to complete and `notify_drop_column_family()` is an async operation that spawns a new seastar thread. So all notifications run in parallel and drop notification may still be reordered against the matching create notifications.

Comment (psarna) [reply db/schema_tables.cc]: If I launch several `seastar::thread` instances that otherwise do not have preemption points, can they be reordered in their execution? I thought that in seastar case it would be a plain queue if all threads have the same scheduling group. In that case it will still work fine, because the first and most important preemption point in `drop_view` is taking a semaphore inside `view_builder`, which ensures serialization of bookkeeping requests, so I'd expect all drops to be queued on that semaphore before all creations (and the semaphore itself ensures ordering as well, being a fifo).

But, if my assumptions are incorrect or use too much internal details, I can just split this `when_all` into two (or, for symmetry, three) `when_alls` and ensure ordering. Would you prefer it this way?

Comment (psarna) [reply db/schema_tables.cc]: Actually, I can't see any huge benefit in running these in a `when_all`, it doesn't look like a super hot performance-sensitive place, and things like `drop_view` end up serialized by the view builder anyway. Perhaps I'll just drop `when_all` and wait for the futures in order, one by one?

Comment (psarna) [reply db/schema_tables.cc]: Ok, nevermind my previous comment, I need to at least group all table drops, view drops, etc. in a `when_all`, otherwise the concurrency will likely be too small for a large number of tables.

Comment (psarna) [reply db/schema_tables.cc]: I know see that I omitted the fact that the previous implementation uses reverse iterators (`rbegin` and `rend`)... I'll rework this so that the order is ensured and retest.

Comment (tgrabiec) [reply db/schema_tables.cc]: I think it's safer to put an explicit barrier by waiting for the drop listeners.

The abstract `migration_listener` interface specifies that listeners run in a thread, so presumably, some listeners could defer.

`notify_drop_view()` runs `on_drop_view()` listeners in a loop. If any of the listeners defers, later `on_drop_view()` may be deferred until after some `on_create_view()`.

Comment (psarna) [reply db/schema_tables.cc]: I'm resolving this conversation, because after the force push the code it applied to is no longer here. @tgrabiec can you take a look now? I explicitly set the order of when deletions, creations and changes are notified, with a synchronization point after each one, it also allowed me to get rid of the additional vector.

Verified via running `materialized_views_test.TestMaterializedViews.mv_populating_from_existing_data_during_node_stop_test` multiple times in `release` mode, both with and without additional debug logs to see what the order is.

**Comment by psarna** [comment]
@tgrabiec I pushed the requested changes

**Comment by eliransin** [comment]
@psarna it turns out that there is a button for re requesting a review, I pushed it on your behalf :)
