### PR TITLE
sstables: replace the sstable_set with a versioned one

### LINKED ISSUE #2622: Versioned sstable_set
Right now any time we modify an `sstable_set` (add an sstable after a memtable flush, or replace one set of sstables by another due to compaction), we create a copy of the `sstable_set`. For large `sstable_set`s this is expensive.

What we can do instead is create a multiversioned `sstable_set`; each add/remove operation creates a new version; each sstable within the set has is associated with a range of versions where it is valid.

```c++
class versioned_sstable_set {
public:
    void update(sstable_list removed, sstable_list added); // creates a version; strong exception guarantee
    sstable_set get() const; // captures a version and returns a pointer to a version within the set
};
```
as soon as all `sstable_set` handles that point to a specific version dies, that version is removed and any sstables that can be freed are released.

Internally, we can replace sstables in `bag_sstable_set` and `partitioned_sstable_set` with something like

```c++
struct versioned_sstable_data {
    version _version_added;
    optional<version> _version_removed;
    shared_sstable sst;
};

using version_sstable = lw_shared_ptr<versioned_sstable_data>;

std::unordered_multimap<version, versioned_sstable> _added_at;
std::unordered_multimap<version, versioned_sstable> _removed_at;
std::unordered_map<version, unsigned> _reference_count;
```

`sstable_set` functions such as `select()` would skip over sstables not in the captured version.

### PR DESCRIPTION
**Pull request by wmitros**
Currently, the sstable_set in a table is copied before every change
to allow accessing the unchanged version by existing sstable readers.
This patch changes the sstable_set to a structure that keeps all its
versions that are referenced somewhere and provides a way of getting
a reference to an immutable version of the set.
Each sstable in the set is associated with the versions it is alive in,
and is removed when all such versions don't have references anymore.
To avoid copying, the object holding all sstables in the set version is
changed to a new structure, sstable_list, which was previously an alias
for std::unordered_set<shared_sstable>, and which implements most of the
methods of an unordered_set, but its iterator uses the actual set with
all sstables from all referenced versions and iterates over those
sstables that belong to the captured version.
The methods that modify the sets contents give strong exception guarantee
by trying to insert new sstables to its containers, and erasing them in
the case of an caught exception.
To release shared_sstables as soon as possible (i.e. when all references
to versions that contain them die), each time a version is removed, all
sstables that were referenced exclusively by this version are erased. We
are able to find these sstables efficiently by storing, for each version,
all sstables that were added and erased in it, and, when a version is
removed, merging it with the next one. When a version that adds an sstable
gets merged with a version that removes it, this sstable is erased.

Fixes #2622

Signed-off-by: Wojciech Mitros <wojciech.mitros@scylladb.com>

### CODE REVIEW

**Comment by nyh** [comment]
The fixed issue was heavily discussed by Avi, Botond and Raphael. Adding them as potential reviewers, instead of the semi-random list.

**Review by nyh — COMMENTED** [review]
I really like the algorithm as described in the commit message, I'm less confident in my understanding of how the actual code changes - which are very big - matches this description. I left a few comments behind, but it's possible that some of them are just my misunderstandings.
With such large changes with a large number of corner cases, it's very important to have unit tests. For example, a test with an sstable_set where we add sstable A, then B, then C, and then drop the reference to B, and check that B is destroyed as expected. And of course this is just one example. It should be a unit test - not part of the middle of some bigger compaction test or whatever. I don't know if we already have unit tests for these things - if we don't I think we should add them now.

File: sstables/compaction_descriptor.hh [hunk 1]
```diff
@@ -127,7 +127,7 @@ struct compaction_descriptor {
     std::vector<sstables::shared_sstable> sstables;
     // This is a snapshot of the table's sstable set, used only for the purpose of expiring tombstones.
     // If this sstable set cannot be provided, expiration will be disabled to prevent data from being resurrected.
-    std::optional<sstables::sstable_set> all_sstables_snapshot;
+    lw_shared_ptr<sstables::sstable_set> all_sstables_snapshot;
```
Comment (denesb) [inline sstables/compaction_descriptor.hh:130]: Its confusing that the name says snapshot but the type is `sstable_set` even though there is an `sstable_set_snapshot` type now.

Comment (denesb) [reply sstables/compaction_descriptor.hh:130]: It makes me doubt the correctness of this change.

**Review by denesb — CHANGES_REQUESTED** [review]
This commit is a huge mudball and is very hard to review as we have to review the new infrastructure ad the churn of using it in the same patch. The usual way we deal with this is to split this into several commits:
* Preparatory commits
* Introduce the infrastructure
* Use the infrastructure

**Review by denesb — COMMENTED** [review]
I find this all very complex and confusing. I expected something as simple as this:
```c++
struct version {
    uint64_t references = 0;
    std::vector<shared_sstable> added;
    std::vector<shared_sstable> removed;
};

class versioned_sstable_set {
    sstable_list _base;
    // for stable references
    std::list<version> _versions;

public:
    void insert(shared_sstable sst) {
        _versions.emplace_back(version{0, {sst}, {}});
    }
    void erase(shared_sstable sst) {
        _versions.emplace_back(version{0, {}, {sst}});
    }
};

class sstable_set_snapshot {
    sstable_list& _base;
    std::list<version>& _versions;
    version* _this_version = nullptr;

public:
    explicit sstable_set_snapshot(sstable_list& base, std::list<version>& versions) : _base(base), _versions(versions) {
        if (!_versions.empty()) {
            _this_version = &_versions.back();
            ++_this_version->references;
        }
    }
    ~sstable_set_snapshot() {
        if (!_this_version) {
            return;
        }
        --_this_version->references;
        if (_this_version->references) {
            return;
        }
        // merge version with previous version, or if it is the oldest one, merge into _base
    }
};

using sstable_set = sstable_set_snapshot; // to avoid all the unnecessary renames
```

**Comment by denesb** [comment]
Actually we have to merge versions left to right (older into newer) as references to older versions cease.

File: sstables/sstable_set.hh [hunk 2]
```diff
@@ -24,84 +24,207 @@
...
+        uint64_t _version;
+    public:
+        const_iterator(std::unordered_set<versioned_sstable>::const_iterator it,
+                       std::unordered_set<versioned_sstable>::const_iterator versioned_end,
+                       std::unordered_set<shared_sstable>::const_iterator unversioned_it,
+                       uint64_t version);
+        const_iterator& operator++();
+        const_iterator operator++(int);
+        const shared_sstable& operator*() const;
+        bool operator==(const_iterator it) const;
```
Comment (psarna) [inline sstables/sstable_set.hh:98]: Is there a reason for taking this iterator by value? It's quite heavy, a const reference should suffice

File: database.hh [hunk 3]
```diff
@@ -595,7 +595,7 @@ private:
     // Mutations returned by the reader will all have given schema.
     flat_mutation_reader make_sstable_reader(schema_ptr schema,
                                         reader_permit permit,
-                                        lw_shared_ptr<sstables::sstable_set> sstables,
+                                        lw_shared_ptr<sstables::sstable_set_snapshot> sstables,
```
[the remark this answers is not in the document]
Comment (avikivity) [reply database.hh:598]: Yes. Will cause less churn. Also in people's mind.

**Comment by avikivity** [comment]
Please separate the algorithm change from the API change.

The API change can be done without any algorithm change - introduce a versioned_sstable_set and start using in the clients (or, if you convince us that sstable_set_snapshot is a better naming convention, do that). Underneath, sstable_sets are still copied using the old data structure. We just moved the copying from the client to the implementation.

Afterwards, we can add the algorithm+new data structure.

This lets the reviewer concentrate on the API change first, making sure it is a logical no-op, and on the algorithm second.

File: sstables/sstable_set.cc [hunk 4]
```diff
@@ -0,0 +1,526 @@
...
+ * GNU General Public License for more details.
+ *
+ * You should have received a copy of the GNU General Public License
+ * along with Scylla.  If not, see <http://www.gnu.org/licenses/>.
+ */
+
+/*
+ * Licensed to the Apache Software Foundation (ASF) under one
+ * or more contributor license agreements.  See the NOTICE file
+ * distributed with this work for additional information
```
Comment (avikivity) [inline sstables/sstable_set.cc:25]: This code is not Apache derived so it need not be dual licensed.

File: sstables/sstable_set.cc [hunk 5]
```diff
@@ -0,0 +1,526 @@
...
+#include "schema.hh"
+#include "sstable_set.hh"
+#include "compatible_ring_position.hh"
+#include <boost/range/adaptors.hpp>
+
+namespace sstables {
+
+sstable_run::sstable_run(std::unordered_set<shared_sstable>&& sstables)
+    : _all(sstables) {
+}
```
Comment (avikivity) [inline sstables/sstable_set.cc:52]: This change looks unrelated.

File: sstables/sstable_set.cc [hunk 6]
```diff
@@ -0,0 +1,526 @@
...
+    }
+    os << "  }\n}\n";
+    return os;
+}
+
+
+sstable_list::sstable_list() = default;
+sstable_list::sstable_list(lw_shared_ptr<const std::unordered_set<versioned_sstable>> versioned_sstables, uint64_t size, uint64_t version)
+    : _versioned_sstables(std::move(versioned_sstables))
+    , _unversioned_sstables(make_lw_shared<std::unordered_set<shared_sstable>>())
```
Comment (avikivity) [inline sstables/sstable_set.cc:89]: Why are you changing sstable_list?

File: sstables/sstable_set.cc [hunk 7]
```diff
@@ -0,0 +1,526 @@
...
+sstable_set::incremental_selector
+sstable_set::make_incremental_selector(uint64_t version) const {
+    return incremental_selector(_impl->make_incremental_selector(), *_schema, version);
+}
+
+sstable_set::incremental_selector
+sstable_set::make_incremental_selector() const {
+    return incremental_selector(_impl->make_incremental_selector(), *_schema, _current_version);
+}
+
```
Comment (avikivity) [inline sstables/sstable_set.cc:493]: This mixes code movement with changes. It's very hard to review. If you want to move code, move it either before or after this patch.

You can also send a separate pull request for code reorganization to get it out of the way.

File: test/boost/sstable_datafile_test.cc [hunk 8]
```diff
@@ -2968,7 +2968,7 @@ SEASTAR_TEST_CASE(compaction_with_fully_expired_table) {
         expired = get_fully_expired_sstables(*cf, ssts, gc_clock::now());
         BOOST_REQUIRE(expired.size() == 0);
 
-        auto ret = compact_sstables(sstables::compaction_descriptor(ssts, cf->get_sstable_set(), default_priority_class()), *cf, sst_gen).get0();
+        auto ret = compact_sstables(sstables::compaction_descriptor(ssts, cf->get_sstable_set_copy(), default_priority_class()), *cf, sst_gen).get0();
```
Comment (avikivity) [inline test/boost/sstable_datafile_test.cc:2971]: Really, the code churn is unwarranted. get_sstable_set() should maintain its name and semantics. Only the implementation should be made more efficient.

File: test/boost/sstable_datafile_test.cc [hunk 9]
```diff
@@ -4577,55 +4577,193 @@ SEASTAR_TEST_CASE(sstable_set_erase) {
...
-        BOOST_REQUIRE(set.all()->contains(sst));
+        set->erase(sst2);
+        BOOST_REQUIRE(set->all()->size() == 1);
+        BOOST_REQUIRE(set->all()->contains(sst));
     }
 
     return make_ready_future<>();
 }
 
+SEASTAR_TEST_CASE(versioned_sstable_set_test) {
```
Comment (avikivity) [inline test/boost/sstable_datafile_test.cc:4629]: We can split off sstable_set tests into their own file (but either before or after).

File: database.hh [hunk 10]
```diff
@@ -845,7 +845,8 @@ public:
      */
     future<std::unordered_set<sstring>> get_sstables_by_partition_key(const sstring& key) const;
 
-    const sstables::sstable_set& get_sstable_set() const;
+    sstables::sstable_set& get_sstable_set() const;
+    lw_shared_ptr<sstables::sstable_set> get_sstable_set_copy() const;
```
[the remark this answers is not in the document]
Comment (wmitros) [reply database.hh:849]: Considering it caused confusion, it probably does need a comment. 
This method is needed for cases where we want to read the state of the sstable_set but also do modifications that don't affect the sstable_set in the table (there are two such cases: a copy is used for expiration purposes in compaction, and in table::make_reader_excluding_sstables() we give a modified sstable_set to an sstable_reader). This can't be solved without copying, because in our approach all versions are linear.
Also, it doesn't create a copy of all versions, just of the last one(all sstables that are alive in it)

File: database.hh [hunk 11]
```diff
@@ -845,7 +845,8 @@ public:
      */
     future<std::unordered_set<sstring>> get_sstables_by_partition_key(const sstring& key) const;
 
-    const sstables::sstable_set& get_sstable_set() const;
+    sstables::sstable_set& get_sstable_set() const;
```
[the remark this answers is not in the document]
Comment (wmitros) [reply database.hh:848]: I should have changed the methods "constness" too. The change was made because we want to be able to capture a version of the returned set (call get() on it) and capturing a version can't be const because the set is counting references to its versions (in the current version the lw_shared_ptr does the counting and the set only knows if the count is not 0, but still, the set makes changes in its contents when the counter changes between 0 and 1)

File: db/view/view.cc [hunk 12]
```diff
@@ -1364,7 +1364,7 @@ void view_builder::initialize_reader_at_current_token(build_step& step) {
     step.reader = make_local_shard_sstable_reader(
             step.base->schema(),
             std::move(permit),
-            make_lw_shared<sstables::sstable_set>(step.base->get_sstable_set()),
+            step.base->get_sstable_set().get(),
```
[the remark this answers is not in the document]
Comment (wmitros) [reply db/view/view.cc:1367]: I'll change it to get_snapshot in the next version, especially because the sstable_set is mostly owned by a lw_shared_ptr in the current version. I've used the initial idea from the suggestion in the issue, but I probably shouldn't expect everyone to read that as well.

File: database.hh (hunk 10 above)
[the remark this answers is not in the document]
Comment (avikivity) [reply database.hh:849]: We might use copy-on-write (create-version-on-write) for this. 

What's the difficulty with non-linear versions?

File: db/view/view_update_generator.cc [hunk 13]
```diff
@@ -74,7 +74,7 @@ future<> view_update_generator::start() {
                                 tracing::trace_state_ptr ts,
                                 streamed_mutation::forwarding fwd_ms,
                                 mutation_reader::forwarding fwd_mr) {
-                        return ::make_restricted_range_sstable_reader(s, std::move(permit), std::move(ssts), pr, ps, pc, std::move(ts), fwd_ms, fwd_mr);
+                        return ::make_restricted_range_sstable_reader(s, std::move(permit), ssts->get(), pr, ps, pc, std::move(ts), fwd_ms, fwd_mr);
```
[the remark this answers is not in the document]
Comment (wmitros) [reply db/view/view_update_generator.cc:77]: The changes here (view_update_generator::start()) don't really modify the logic of the function, they were needed because the types of the objects we are working on changed. We are still creating a new sstable_set based on the list, but the sstable reader expects an sstable_set_snapshot, which we get by calling get().

File: sstables/compaction.cc [hunk 14]
```diff
@@ -440,7 +440,7 @@ class compaction {
     utils::UUID _run_identifier;
     ::io_priority_class _io_priority;
     // optional clone of sstable set to be used for expiration purposes, so it will be set if expiration is enabled.
-    std::optional<sstable_set> _sstable_set;
+    lw_shared_ptr<sstable_set> _sstable_set;
```
[the remark this answers is not in the document]
Comment (wmitros) [reply sstables/compaction.cc:443]: We want the sstable_set to be wrapped by a shared pointer because all the snapshots of it also need to own it. We aren't actually creating snapshots of the _sstable_set in compaction, so in this case we could leave the lw_shared_ptr but I'm still not sure if that's the best solution

File: sstables/compaction.cc [hunk 15]
```diff
@@ -813,7 +813,7 @@ class reshape_compaction : public compaction {
     flat_mutation_reader make_sstable_reader() const override {
         return ::make_local_shard_sstable_reader(_schema,
                 _permit,
-                _compacting,
+                _compacting->get(),
```
[the remark this answers is not in the document]
Comment (wmitros) [reply sstables/compaction.cc:816]: As mentioned before, I'll change it.

File: sstables/compaction.cc [hunk 16]
```diff
@@ -965,7 +965,7 @@ class regular_compaction : public compaction {
             std::for_each(exhausted, _sstables.end(), [this] (shared_sstable& sst) {
                 _compacting_for_max_purgeable_func.erase(sst);
                 // Fully expired sstable is not actually compacted, therefore it's not present in the compacting set.
-                _compacting->erase(sst);
+                _compacting->erase(sst, false);
```
[the remark this answers is not in the document]
Comment (wmitros) [reply sstables/compaction.cc:968]: This change was needed because we're dealing with an exceptional case here. This is the only place where we're modifying an sstable_set even though there might be some sstable readers that are using it. The false signals just that - modify the last version even if it has already been captured.

File: sstables/compaction_strategy.cc [hunk 17]
```diff
@@ -66,158 +66,18 @@ namespace sstables {
 
 extern logging::logger clogger;
 
-void sstable_run::insert(shared_sstable sst) {
```
[the remark this answers is not in the document]
Comment (wmitros) [reply sstables/compaction_strategy.cc:69]: After the changes there is a lot of code concerning specifically the sstable_set class, so I've moved it to a new sstable_set.cc file. I'll move this change to a separate commit.

File: sstables/compaction_strategy.cc [hunk 18]
```diff
@@ -295,8 +155,8 @@ class partitioned_sstable_set : public sstable_set_impl {
         }
     }
     // SSTables are stored separately to avoid interval map's fragmentation issue when level 0 falls behind.
-    bool store_as_unleveled(const shared_sstable& sst) const {
-        return _use_level_metadata && sst->get_sstable_level() == 0;
+    bool store_as_unleveled(const versioned_sstable& sst) const {
+        return _use_level_metadata && sst->sst->get_sstable_level() == 0;
```
[the remark this answers is not in the document]
Comment (wmitros) [reply sstables/compaction_strategy.cc:159]: That might be problematic because the versioned_sstable is just lw_shared_ptr<versioned_sstable_data> where versioned_sstable_data is a struct with: shared_sstable sst; uint64_t version_added; std::optional<uint64_t> ersion_erased;
Maybe it isn't as bad as it sounds though, the "->sst->" only happens in 5 places and the similarly confusing "*sst->sst" in 2 places.

File: sstables/sstable_set.hh [hunk 19]
```diff
@@ -24,84 +24,207 @@
...
     uint64_t data_size() const;
-    const sstable_list& all() const { return _all; }
+    const std::unordered_set<shared_sstable>& all() const { return _all; }
 };
 
-class sstable_set {
+class sstable_set_snapshot;
+class version_reference;
+
+class sstable_list {
```
[the remark this answers is not in the document]
Comment (wmitros) [reply sstables/sstable_set.hh:71]: Actually, the sstable_list name isn't new - it was the return type of sstable_set::all() before the change too, but it was just an unordered_set then. I tried to explain it somewhat in the commit message, but I wasn't sure if something like it would be suitable for putting in the source code.

File: sstables/sstable_set.hh [hunk 20]
```diff
@@ -24,84 +24,207 @@
...
+
+// should be owned by a lw_shared_ptr
+class sstable_set : public enable_lw_shared_from_this<sstable_set> {
     std::unique_ptr<sstable_set_impl> _impl;
     schema_ptr _schema;
     // used to support column_family::get_sstable(), which wants to return an sstable_list
     // that has a reference somewhere
-    lw_shared_ptr<sstable_list> _all;
-    std::unordered_map<utils::UUID, sstable_run> _all_runs;
+    lw_shared_ptr<std::unordered_set<versioned_sstable>> _all;
```
[the remark this answers is not in the document]
Comment (wmitros) [reply sstables/sstable_set.hh:117]: Before the changes we could simply return _all in get_sstables() because for every version we had a separate copy of _all. We are avoiding copying so now we return the new struct sstable_list (which was also the name of the return type of get_sstables()) which iterates only over sstables belonging to the current version, instead of copying the set.

File: database.hh (hunk 3 above)
[the remark this answers is not in the document]
Comment (wmitros) [reply database.hh:598]: I had an impression that either way, we are creating a single new class and changing a portion of sstable_sets to it. If it's preferable to change the versioned one, I'll do just that

File: sstables/compaction.cc (hunk 14 above)
[the remark this answers is not in the document]
Comment (avikivity) [reply sstables/compaction.cc:443]: Can't it be done internally in sstable_set?

File: sstables/compaction_descriptor.hh (hunk 1 above)
Comment (wmitros) [reply sstables/compaction_descriptor.hh:130]: In the previous version the "snapshot" in this name actually meant a full copy, so it wouldn't be a snapshot as in sstable_set_snapshot right now, but I see that it may be very confusing now, so I'll adjust this name in the next version.

File: database.hh (hunk 3 above)
[the remark this answers is not in the document]
Comment (avikivity) [reply database.hh:598]: The problem with your approach (if I understand it correctly) is that sstable_set changes meaning. Before, it was a set of sstables. Afterwards, it's the history of sstable_sets, from which you can derive snapshots. sstable_set_snapshot takes the meaning of the old sstable_set. That confuses everyone, because any time they see sstable_set they have to attach it to either the old or the new meaning.

File: sstables/sstable_set.hh [hunk 21]
```diff
@@ -24,84 +24,207 @@
...
+class version_reference : public weakly_referencable<version_reference>, public enable_lw_shared_from_this<version_reference> {
+    lw_shared_ptr<sstable_set> _versioned_ssts;
+    uint64_t _version;
+public:
+    version_reference(lw_shared_ptr<sstable_set> versioned_ssts, uint64_t version);
+    ~version_reference();
+    uint64_t get() const;
+};
+
+class sstable_set::incremental_selector {
```
[the remark this answers is not in the document]
Comment (wmitros) [reply sstables/sstable_set.hh:171]: I think I needed to move it when I was still working on it to avoid working on incomplete types (it had a version_reference which had a lw_shared to the sstable_set). Looks like in the final version I can move it back

File: sstables/sstable_set.hh [hunk 22]
```diff
@@ -24,84 +24,207 @@
...
+    const std::unordered_set<shared_sstable>& all() const { return _all; }
 };
 
-class sstable_set {
+class sstable_set_snapshot;
+class version_reference;
+
+class sstable_list {
+    lw_shared_ptr<const std::unordered_set<versioned_sstable>> _versioned_sstables;
+    lw_shared_ptr<std::unordered_set<shared_sstable>> _unversioned_sstables;
```
[the remark this answers is not in the document]
Comment (wmitros) [reply sstables/sstable_set.hh:73]: _versioned_sstables is the set of all sstables from all versions that are stored in the versioned sstable_set. 
In all but one cases the sstable_list is used as a reference to the set of all sstables in an sstable_set_snapshot - we have _version to be able to iterate only over the sstables that are alive in the corresponding version. The sstable_list returned by table::get_sstables_including_compacted_undeleted() may not be such a reference though - it may be a reference to a new set of sstables that includes all sstables from a snapshot and some others, that weren't added or erased in any version - _unversioned_sstables. 
Before the changes, the exceptional case was handled by copying the entire set of sstables from the sstable_set and adding new sstables to the copy. We could do a similar thing here, but considering we would still want to handle the case where sstable_list is just a reference to the set of sstables from a snapshot, we would need to keep the _versioned_sstables field, but in the exceptional case it could point to the copy of the original set, and we could add new sstables with artificial versions to the copy.
I think the other solution is equally confusing though, and has a worse complexity.

File: sstables/sstable_set.hh [hunk 23]
```diff
@@ -24,84 +24,207 @@
...
+    uint64_t _size;
```
[the remark this answers is not in the document]
Comment (wmitros) [reply sstables/sstable_set.hh:74]: The size of an sstable_list is the number of sstables that it represents. The sstable_list represents only tables from a certain version, and _versioned_sstables contain sstables from various versions, so we can't just use _versioned_sstables->size() to count the size of the sstable_list. In order not to count the sstables one by one every time we call size(), we remember this number.

File: sstables/sstable_set.hh (hunk 2 above)
Comment (wmitros) [reply sstables/sstable_set.hh:98]: that is my mistake, wil fix

File: sstables/sstable_set.cc (hunk 4 above)
Comment (wmitros) [reply sstables/sstable_set.cc:25]: I've moved quite some code from sstabes/compaction_strategy.cc (everything concerning sstable_set, excluding bag_sstable_set and partitioned_sstable_set), so I thought the licenses might be the same. I'll fix it in the next version

File: sstables/sstable_set.cc (hunk 5 above)
Comment (wmitros) [reply sstables/sstable_set.cc:52]: sstable_run is only used in the sstable_set, so I've decided to move it together with the other sstable_set code

File: sstables/sstable_set.cc (hunk 6 above)
Comment (wmitros) [reply sstables/sstable_set.cc:89]: The sstable_list is the return type of sstable_set::all(). It used to be an lw_shared_ptr<unordered_set<shared_sstable>> but it can't be any more because we don't have a separate unordered_set of all sstables for every version.

File: sstables/sstable_set.cc (hunk 7 above)
Comment (wmitros) [reply sstables/sstable_set.cc:493]: Ok, I'll add the code movement to a separate commit

File: database.hh (hunk 10 above)
[the remark this answers is not in the document]
Comment (wmitros) [reply database.hh:849]: The biggest issues with keeping non-linear versions in the versioned sstable_set are that it would be harder to decide if a version is between two other versions - the versions now form a tree, so they can't really be represented by integers, and it would also be harder to decide when all references to an sstable die - the sstable might have been erased multiple times on different branches. We would also need to allow modifying all versions that are alive - not only the last one like we currently do.

[the remark this answers is not in the document]
Comment (avikivity) [reply database.hh:849]: Suppose an entry in the data structure contains a `vector<version_status>` where `version_status` is `struct { version* v, bool included }`.

To copy a set, create a new version object and mark it as a descendent of the version object you copied from.
To add or remove an sstable, append a version_status with included set to true/false.

To check if an sstable is in the set, walk the vector backwards until you find a version that is equal to your version, or is an ancestor.

To delete a version, iterate over all related entries (you'll have to keep pointers to those entries) and replace them with pointers to the deleted version's descendants.

But I feel like we're reinventing a wheel here. Check purely functional data structures, they have to accomplish the same thing since they cannot mutate the data structure.

Another alternative is to check if every place we use sstable_set is strictly necessary. Of course, converting to sstable_list is also O(n), so we should only use sstable_list if we're sure n is small. Maybe we can remove enough users so that linear versions become workable.

[the remark this answers is not in the document]
Comment (wmitros) [reply database.hh:849]: I realize that writing a purely functional data structure would basically solve all our problems, but I was under an impression that we are trying to use a simpler solution here.

In your example, am I missing something or do we still have to walk over all ancestors of a version to check if the vector has a pointer to one of them (there are ways to check it in log(n) but that would need additional solutions)? And what is the complexity of deleting a version here, won't we potentially iterate over all sstables in the set? I had a solution that doesn't need to iterate over all sstables related to the deleted version, but only if there was only one following version.

File: database.hh (hunk 3 above)
[the remark this answers is not in the document]
Comment (wmitros) [reply database.hh:598]: It is true that the sstable_set changed meaning. But it wouldn't be exactly true to say that the sstable_set_snapshot is a set of sstables either. After all, it doesn't contain any sstables on its own, it's just an interface for asking the versioned sstable_set for the sstables. You can't erase or insert any sstables to it too, so it would be closer to a const set.

As I said though, the approach with a versioned_sstable_set is good, so I'll change to it, especially because it may help reviewers.

File: database.hh (hunk 10 above)
[the remark this answers is not in the document]
Comment (avikivity) [reply database.hh:849]: > I realize that writing a purely functional data structure would basically solve all our problems, but I was under an impression that we are trying to use a simpler solution here.

Simpler is better! But if we end up just moving the expensive operations from one place to another, ore eliminating just half the expensive operations, it doesn't help

If the expensive operations become very rare, it's okay.

> 
> In your example, am I missing something or do we still have to walk over all ancestors of a version to check if the vector has a pointer to one of them (there are ways to check it in log(n) but that would need additional solutions)? And what is the complexity of deleting a version here, won't we potentially iterate over all sstables in the set?

If a version changed only a few sstables (quite common), and if the version has a list of those sstables, then it becomes a cheap operation (but indeed the complexity keep increasing). We might say that a version has a link to the parent version, plus a delta compared to the previous version.

> I had a solution that doesn't need to iterate over all sstables related to the deleted version, but only if there was only one following version.

It may still be possible. If we understand the case in compaction well enough, maybe we can fit it into the solution. 

I don't want this to grow into a huge research problem, but I also don't want to solve just half of it.

It's worth looking at the functional data structure literature. Maybe there is something that is easy to adapt. I expect most rely on garbage collection, but perhaps it can be replaced by reference counts or just intrusive lists.

File: sstables/sstable_set.hh (hunk 23 above)
[the remark this answers is not in the document]
Comment (denesb) [reply sstables/sstable_set.hh:74]: I see.

File: sstables/sstable_set.hh (hunk 22 above)
[the remark this answers is not in the document]
Comment (denesb) [reply sstables/sstable_set.hh:73]: So, `_unversioned_sstables` are those sstables that are in *all* currently live versions, and `_versioned_sstables` are those that are added/removed in a certain version. Makes sense, however the naming is very misleading, it makes one think that we have different version of the same sstable.

Also, why are all these containers `lw_shared_ptr`? This observation applies to the entire patch -- in general I have a feeling that we have way more shared pointers than necessary. I'd like to emphasize that this is just a gut feeling, in the current form I have a hard time forming a big picture of all the changes and therefore can't rely on understanding of the code.

File: database.hh (hunk 10 above)
[the remark this answers is not in the document]
Comment (wmitros) [reply database.hh:849]: It looks like the only cases where we need to use non-linear versions (table::make_reader_excluding_sstables() and regular_compaction::update_pending_ranges()) don't need to create any more versions, because after each change they need only the state with all changes.
So what we can do is keep local changes on the non-linear version, and merge its results with the snapshots when selecting, similarly to the local changes in the sstable_list. 
With this we could completely avoid copying the sstable_set, but we would need to additionally remember the sstables that were erased in the non-linear version and filter them out while selecting. On the other hand, we would still need to do something similar, even if we were using a purely functional data structure for this. 
Actually, if we were erasing a large number of sstables, maybe it would be better to just copy the set?

File: sstables/sstable_set.hh (hunk 22 above)
[the remark this answers is not in the document]
Comment (wmitros) [reply sstables/sstable_set.hh:73]: I'll change the naming in the next patch, but I think I should clarify what these members mean before that. You are right about the meaning of _versioned_sstables, but it seems I didn't explain the _unversioned_sstables clearly. The unversioned sstables are sstables that were added to the sstable_list but don't appear in any of the versions of the sstable_set. It looks like you're right about not needing to keep a lw_shared_ptr to them. 
We're keeping lw_shared_ptrs to sstable_lists because that's basically what we were doing before the change and I didn't want to make too many unnecessary changes

File: database.hh (hunk 10 above)
[the remark this answers is not in the document]
Comment (avikivity) [reply database.hh:849]: If I understand correctly, you are suggesting to replace

     s1 = main_set
     s1.remove(some_sstables)

with 

    s1 = main_set   # create a snapshot, but do not mutate it
    s1_delta = some_sstables

and follow by looking up both s1 and s1_delta?

but could be not remember some_sstables in the data structure directly?


Typically, sstable_set evolution does not affect many sstables. With Leveled Compaction Strategy we typically change ~22 sstables (1 sstable promoted, 11 sstables intersecting it, 10-11 new sstables).

With Incremental Compaction Strategy it's just a few each time.

@nyh / @psarna  can you comment on the expected size of excluded_sstables in view_updating_consumer?

[the remark this answers is not in the document]
Comment (denesb) [reply database.hh:849]: If versions were a single linked list, we could create a new version based on a snapshot, without adding nonlinear version support:
```
s1 = sst_set();
//.. modifications to s1
s2 = sst_set(s1.snapshot());
// modification to s2 just add versions on top of s1's snapshot, but those are not visible to s1
```

File: sstables/sstable_set.cc (hunk 6 above)
Comment (avikivity) [reply sstables/sstable_set.cc:89]: Makes sense. I did not review the new sstable_list, so the following may be completely wrong, but shouldn't it be just a pair of iterators into a version? That is, now that taking a snapshot is very cheap, an sstable_list can hold a reference to a version, and begin()/end() can call the sstable_set's implementations.

Comment (wmitros) [reply sstables/sstable_set.cc:89]: Ideally, that should be it, but in one case the sstable_list was not a reference to sstable_sets all(), but a modified copy of it, so in order not to copy everything in that case, I've added a modifications list to it.
When we solve the non-linear version issue, the local modifications list will not be needed any more, because instead of keeping a modified copy of all sstables from a snapshot, we will be able to simply keep a reference to a modified snapshot.

Comment (wmitros) [reply sstables/sstable_set.cc:89]: If we want a fast size() method, we will still need to cache it though, but it could be stored in the version, not the sstable_list

File: database.hh (hunk 10 above)
[the remark this answers is not in the document]
Comment (wmitros) [reply database.hh:849]: Considering all arguments, I think versions with pointers to one another are a good idea. Assuming we have very few concurrently alive versions at any time, we can even drop the "versioned_sstables" that were stored in a single container and later filtered, and merge results from containers from only the relevant versions instead. 

With linked snapshots, we can quite easily support non-linear versions, at least in a way that isn't very efficientwhen there are too many of them, but I think that's not a big problem (still not close to copying everything). Actually, if we have all those pointers, we could probably also remove the versioned_sstable_set altogether. 

I'll also ask ahead because I often get this comment in review, would it be fine to have lw_shared_ptrs to parent versions? We need some shared owning because we may have a version that doesn't belong to any versioned_sstable_set, and I don't think we want to do the mallocing ourselves.

[the remark this answers is not in the document]
Comment (denesb) [reply database.hh:849]: We don't actually have anything against using `lw_shared_ptr<>` when its justified. It's only when they can be seen everywhere in a patchset that it starts to raise eyebrows and people start to question whether they are really necessary.

[the remark this answers is not in the document]
Comment (avikivity) [reply database.hh:849]: Ah, so sstable_set's copy constructor will create a live snapshot.

There's no problem with lw_shared_ptr (apart that it's better not to use them when a value is fine). When changing a widely used API like this, they should be hidden in the implementation, not exposed.

**Comment by bhalevy** [comment]
ping.  what's the status of this PR?

**Comment by psarna** [comment]
@bhalevy the current status is "the author is on vacation" :)

**Comment by slivne** [comment]
@wmitros I guess you are back from vacation looking forward for an updated version

**Comment by wmitros** [comment]
I'm back from vacation and I've finally finished the updated version. Its quite considerably different than the previous one, should I create a new PR for it? If it's fine to review it here, please read the commit messages beforehand, particularly to the commit that actually changes the sstable_set implementation.

**Comment by bhalevy** [comment]
> I'm back from vacation and I've finally finished the updated version. Its quite considerably different than the previous one, should I create a new PR for it? If it's fine to review it here, please read the commit messages beforehand, particularly to the commit that actually changes the sstable_set implementation.

Hi @wmitros, it's ok to keep it under the same PR.

Overall, this loosely reminds me of the my versioned `token_metadata` project.
See https://github.com/bhalevy/scylla/commits/versioned-shared-token-metadata

It is based on keeping a lw_shared_ptr that is a snapshot of the shared data structure.  Either a const one for read-only access, or a mutable copy that is cloned from the shared object.  Writers acquire a shared lock (seastar::semaphore), clone the object, modify it, apply the changes back, and then release the lock.  I wonder if a similar model is applicable here too.  I'll look at the new series...

File: sstables/sstable_set.cc [hunk 24]
```diff
@@ -61,94 +61,422 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
...
+}
 
-std::vector<shared_sstable>
-sstable_set::select(const dht::partition_range& range) const {
-    return _impl->select(range);
+// version operations
+sstable_set_version_reference::~sstable_set_version_reference() {
+    if (_p) {
+        _p->_reference_count--;
+        if (_p->_reference_count == 1 && _p->_next.size() == 1) {
```
Comment (denesb) [inline sstables/sstable_set.cc:118]: Why can we only merge if `size()` == 1?

File: sstables/sstable_set.hh [hunk 25]
```diff
@@ -47,24 +47,86 @@ public:
...
+    std::vector<shared_sstable> select(const dht::partition_range& range) const;
+    std::unordered_set<shared_sstable> select_by_run_id(utils::UUID run_id) const;
+    const std::set<shared_sstable>& all() const;
+    void remove(shared_sstable sst);
+    std::unique_ptr<incremental_selector_impl> make_incremental_selector();
+};
+
+class sstable_set_version;
+
+class sstable_set_version_reference {
```
Comment (denesb) [inline sstables/sstable_set.hh:78]: Can't this class be folded into `sstable_list` or replaced with an `lw_shared_ptr<>`?

File: sstables/sstable_set.cc [hunk 26]
```diff
@@ -61,94 +61,422 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
...
+
+bool sstable_set_version::contains(shared_sstable sst) const { 
+    return _added.contains(sst) || (!_erased.contains(sst) && _prev && _prev->contains(sst));
+}
+
+size_t sstable_set_version::size() const {
+    return _added.size() - _erased.size() + (_prev ? _prev->size() : 0);
+}
+
+void sstable_set_version::insert(shared_sstable sst) {
```
Comment (denesb) [inline sstables/sstable_set.cc:433]: I thought that versions are immutable and mutating creates a new version?

File: sstables/sstable_set.cc [hunk 27]
```diff
@@ -61,94 +61,422 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
...
+            // we may be able to release the sstable
+            for (auto ver : _prev->get_next_versions()) {
+                ver->unerase(sst);
+            }
+            _prev->erase(sst);
+        }
+    }
+}
+
+void sstable_set_version::unerase(shared_sstable sst) {
```
Comment (denesb) [inline sstables/sstable_set.cc:474]: Isn't this equivalent to `insert()`?

**Review by denesb — CHANGES_REQUESTED** [review]
I still find the object graph somewhat hard to piece together and follow. Comments or maybe better names would help that.

Also have some comments in the code.

File: sstables/sstable_set.cc [hunk 28]
```diff
@@ -61,10 +61,11 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
     return os;
 }
 
-sstable_set::sstable_set(std::unique_ptr<sstable_set_impl> impl, schema_ptr s, lw_shared_ptr<sstable_list> all)
+sstable_set::sstable_set(std::unique_ptr<sstable_set_impl> impl, schema_ptr s)
         : _impl(std::move(impl))
         , _schema(std::move(s))
-        , _all(std::move(all)) {
+        , _all(make_lw_shared<sstable_list>()) {
+    // assumes impl contains no sstables
```
[the remark this answers is not in the document]
Comment (wmitros) [reply sstables/sstable_set.cc]: Currently, there is no simple way of checking if impl is empty other than trying to select everything from it, but I guess it is not a problem to add such a method, so I'll do that.

File: sstables/sstable_set.cc [hunk 29]
```diff
@@ -61,94 +61,422 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
...
 }
 
-sstable_set::sstable_set(const sstable_set& x)
-        : _impl(x._impl->clone())
-        , _schema(x._schema)
-        , _all(make_lw_shared<sstable_list>(*x._all))
-        , _all_runs(x._all_runs) {
+void versioned_sstable_set_data::insert(shared_sstable sst) {
+    if (_times_added.contains(sst)) {
+        _times_added.at(sst)++;
```
[the remark this answers is not in the document]
Comment (wmitros) [reply sstables/sstable_set.cc:70]: Ok

File: sstables/sstable_set.cc [hunk 30]
```diff
@@ -61,94 +61,422 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
...
+        return;
+    }
+    try {
+        _impl->insert(sst);
+        _all_runs[sst->run_identifier()].insert(sst);
+        _all.insert(sst);
+        _times_added[sst] = 1;
```
[the remark this answers is not in the document]
Comment (wmitros) [reply sstables/sstable_set.cc:77]: Ok

File: sstables/sstable_set.cc [hunk 31]
```diff
@@ -61,94 +61,422 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
...
+    } catch (...) {
+        _impl->erase(sst);
+        if (_all_runs.contains(sst->run_identifier())) {
+            _all_runs.at(sst->run_identifier()).erase(sst);
```
[the remark this answers is not in the document]
Comment (wmitros) [reply sstables/sstable_set.cc:81]: Ok

File: sstables/sstable_set.hh [hunk 32]
```diff
@@ -47,24 +47,86 @@ public:
...
-    const sstable_list& all() const { return _all; }
+    const std::unordered_set<shared_sstable>& all() const { return _all; }
 };
 
-class sstable_set {
+class versioned_sstable_set_data {
     std::unique_ptr<sstable_set_impl> _impl;
-    schema_ptr _schema;
+    std::unordered_map<utils::UUID, std::unordered_set<shared_sstable>> _all_runs;
+    std::unordered_map<shared_sstable, unsigned> _times_added;
```
[the remark this answers is not in the document]
Comment (wmitros) [reply sstables/sstable_set.hh:63]: We can, but they are not relevant when deciding if all occurrences of the sstable have been removed, I tried to explain that a bit in the commit message

File: sstables/sstable_set.hh [hunk 33]
```diff
@@ -114,6 +177,42 @@ public:
     incremental_selector make_incremental_selector() const;
 };
 
+class sstable_set_version {
+    lw_shared_ptr<versioned_sstable_set_data> _versioned_data;
+    schema_ptr _schema;
+    sstable_set_version_reference _prev;
+    mutable std::unordered_set<sstable_set_version*> _next;
+    std::unordered_set<shared_sstable> _added;
+    std::unordered_set<shared_sstable> _erased;
```
[the remark this answers is not in the document]
Comment (wmitros) [reply sstables/sstable_set.hh:186]: The answer to all your questions is yes. In particular, we are performing lookups each time we want to check if an sstable is a part of a version

File: sstables/sstable_set.hh [hunk 34]
```diff
@@ -114,6 +177,42 @@ public:
     incremental_selector make_incremental_selector() const;
 };
 
+class sstable_set_version {
+    lw_shared_ptr<versioned_sstable_set_data> _versioned_data;
+    schema_ptr _schema;
+    sstable_set_version_reference _prev;
+    mutable std::unordered_set<sstable_set_version*> _next;
```
[the remark this answers is not in the document]
Comment (wmitros) [reply sstables/sstable_set.hh:184]: This _next variable is a set of pointers to versions that were derived directly from this version(by copying or modifying). It's mutable because we're adding a new version to it when copying(so in copy constructor and copy assignment, when we're working on a const reference)

File: sstables/sstable_set.hh [hunk 35]
```diff
@@ -47,24 +47,86 @@ public:
...
     void insert(shared_sstable sst);
     void erase(shared_sstable sst);
     // Data size of the whole run, meaning it's a sum of the data size of all its fragments.
     uint64_t data_size() const;
-    const sstable_list& all() const { return _all; }
+    const std::unordered_set<shared_sstable>& all() const { return _all; }
 };
 
-class sstable_set {
+class versioned_sstable_set_data {
```
[the remark this answers is not in the document]
Comment (wmitros) [reply sstables/sstable_set.hh:60]: I think you can call it that. All members of this class contain all sstables from all versions that are currently alive

File: sstables/sstable_set.cc (hunk 24 above)
Comment (wmitros) [reply sstables/sstable_set.cc:118]: We need to merge into all of the child versions, but we don't want to merge into more than one, because that would greatly increase our complexity, and we don't want to merge with one of the next versions if there are more than one, because that would change the results given by the other child versions. 
What might be misleading is that when we're merging into the next version, we aren't necessarily copying all our content into it - avoiding it is actually the whole point of this PR. What we're actually doing is merge into the next version, or merge the next into us, depending on which version has more changes - with this approach we are copying each change on average at most log(number of versions) instead of copying each change with each new version.

File: sstables/sstable_set.hh (hunk 35 above)
[the remark this answers is not in the document]
Comment (denesb) [reply sstables/sstable_set.hh:60]: I thought it only includes the sstables that all versions include, later additions being only found in those later versions.

Doesn't this mean that if we have two versions, each adding 1 sstable, then they both contain N-1 and N-2 sstables respectively?

File: sstables/sstable_set.hh (hunk 25 above)
Comment (wmitros) [reply sstables/sstable_set.hh:78]: It can't be lw_shared_ptr because it is a reference to a sstable_set_version, and a sstable_set_version has a member of this type and lw_shared_ptrs don't work on incomplete (so recursive too) types(at least I couldn't make them work), it could be an std::shared_ptr though, but it would still require more additional work than writing own pointer class. It could be folded into sstable_list but it would have to be folded into sstable_set_version at the same time, because both have a member of this type, and what is being done in its destructor would have to be copied to both of these classes' destructors too.

File: sstables/sstable_set.cc (hunk 27 above)
Comment (wmitros) [reply sstables/sstable_set.cc:474]: Looks like it is the same in practice, I'll remove this one

File: sstables/sstable_set.cc (hunk 26 above)
Comment (wmitros) [reply sstables/sstable_set.cc:433]: It should give the same results in practice, but I think I could change it. One thing is that there is no reason to actually create a new version if it's going to be instantly merged with the next one, and we are actually creating the new versions in sstable_list, but we could make it so that the insert and erase methods return a reference to a version and if there is no use in actually creating a new version they could simply return references to themselves. Do you think that would be a better solution?

File: sstables/sstable_set.hh (hunk 35 above)
[the remark this answers is not in the document]
Comment (wmitros) [reply sstables/sstable_set.hh:60]: This versioned_sstable_set_data is shared across all versions, so every addition is still kept in its respective version. The shared data is mostly needed for two things: 
- the iterator given by sstable_list - we want to iterate over a single container because if we were iterating over containers from different versions, some versions could be merged and that would invalidate our iterators
- incremental selectors - currently each incremental_selector has references to members of an sstable_set, and we had different sstable_subsets for all versions, the incremental_selector would have to have references to all of them, and they could be merged too. These selectors also remember the last selected position, which would change during merging as well

File: sstables/sstable_set.cc [hunk 36]
```diff
@@ -61,10 +61,11 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
     return os;
 }
 
-sstable_set::sstable_set(std::unique_ptr<sstable_set_impl> impl, schema_ptr s, lw_shared_ptr<sstable_list> all)
+sstable_set::sstable_set(std::unique_ptr<sstable_set_impl> impl, schema_ptr s)
         : _impl(std::move(impl))
         , _schema(std::move(s))
-        , _all(std::move(all)) {
+        , _all(make_lw_shared<sstable_list>()) {
```
Comment (bhalevy) [inline sstables/sstable_set.cc]: why the explicit initializer?
the implicit default constructor is just what you need.

**Review by bhalevy — CHANGES_REQUESTED** [review]

**Comment by avikivity** [comment]
Administrative note: base your branches on master and rebase on master. next can have patches added and removed from it, and when a patch is removed from next, it is left in your branch. There's also no need to point the target branch to next.

Please drop the unrelated patches from this branch.

File: sstables/sstable_set.cc [hunk 37]
```diff
@@ -61,94 +61,422 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
...
+    return _all;
+}
 
-sstable_set&
-sstable_set::operator=(const sstable_set& x) {
-    if (this != &x) {
-        auto tmp = sstable_set(x);
-        *this = std::move(tmp);
+void versioned_sstable_set_data::remove(shared_sstable sst) {
+    if (--_times_added[sst] == 0) {
```
Comment (bhalevy) [inline sstables/sstable_set.cc:102]: look for `sst` in `_times_added` first and assert it's there, otherwise
you'd create an entry and decrement it to be -1.

**Review by bhalevy — CHANGES_REQUESTED** [review]
This patch is too complicated.
Can you please break it and introduce the new mechanisms gradually?

File: sstables/sstable_set.hh [hunk 38]
```diff
@@ -28,8 +28,21 @@
...
+
+class sstable_set_impl {
+public:
+    virtual ~sstable_set_impl() {}
+    virtual std::unique_ptr<sstable_set_impl> clone() const = 0;
+    virtual std::vector<shared_sstable> select(const dht::partition_range& range) const = 0;
+    virtual void insert(shared_sstable sst) = 0;
+    virtual void erase(shared_sstable sst) = 0;
+    virtual std::unique_ptr<incremental_selector_impl> make_incremental_selector() const = 0;
+};
```
Comment (avikivity) [inline sstables/sstable_set.hh:45]: Why move sstable_set_impl to the header? I don't mind if there's a good reason, it will rarely change so it won't trigger recompilation. But if it's just an accident, let's keep it in .cc.

File: sstables/sstable_set.cc (hunk 36 above)
Comment (avikivity) [reply sstables/sstable_set.cc]: No, the default constructor creates a null pointer. This creates a pointer looking at a unique, empty list.

File: api/storage_service.cc [hunk 39]
```diff
@@ -953,8 +953,8 @@ void set_storage_service(http_context& ctx, routes& r) {
                         ss::table_sstables tst;
                         tst.keyspace = schema->ks_name();
                         tst.table = schema->cf_name();
-
-                        for (auto sstable : *t->get_sstables_including_compacted_undeleted()) {
+                        auto sstables = t->get_sstables_including_compacted_undeleted();
+                        for (auto sstable : *sstables) {
```
Comment (avikivity) [inline api/storage_service.cc:957]: Good catch. Please mark this with a Fixes #nnnn tag (and file issue nnnn) so it can be backported.

**Comment by avikivity** [comment]
If you like, you can extract the first few patches that lay the groundwork and fix random issues into a separate branch that can be merged quickly in order to get it out of the way.

File: sstables/sstable_set.hh (hunk 32 above)
[the remark this answers is not in the document]
Comment (avikivity) [reply sstables/sstable_set.hh:63]: I have an intuition (but no proof) that you'll need to keep track of which versions an sstable was added to, not just the number of times it was added. But this is based on incomplete review and incomplete understanding, I'll read on.

File: sstables/sstable_set.hh [hunk 40]
```diff
@@ -47,24 +47,86 @@ public:
...
+    const std::unordered_set<shared_sstable>& all() const { return _all; }
 };
 
-class sstable_set {
+class versioned_sstable_set_data {
     std::unique_ptr<sstable_set_impl> _impl;
-    schema_ptr _schema;
+    std::unordered_map<utils::UUID, std::unordered_set<shared_sstable>> _all_runs;
+    std::unordered_map<shared_sstable, unsigned> _times_added;
+    std::set<shared_sstable> _all;
```
Comment (avikivity) [inline sstables/sstable_set.hh:64]: Can we merge _all and _times_added? Using std::map<shared_sstable, unsigned>. I'm more concerned about exception safety and complexity than performance. I did not review the implementation yet to see if there's a problem.

File: sstables/sstable_set.hh [hunk 41]
```diff
@@ -47,24 +47,86 @@ public:
...
+public:
+    versioned_sstable_set_data(std::unique_ptr<sstable_set_impl> impl);
+    void insert(shared_sstable sst);
+    void erase(shared_sstable sst);
+    std::vector<shared_sstable> select(const dht::partition_range& range) const;
```
Comment (avikivity) [inline sstables/sstable_set.hh:69]: So, the way this works is that it gives a superset of the result (including sstables from versions other than the one we're interested in), and the caller then filters out sstables that don't belong in the version of interest?

File: sstables/sstable_set.hh [hunk 42]
```diff
@@ -47,24 +47,86 @@ public:
...
+class sstable_set_version;
+
+class sstable_set_version_reference {
+    mutable sstable_set_version* _p = nullptr;
+public:
+    ~sstable_set_version_reference();
+    sstable_set_version_reference() = default;
+    sstable_set_version_reference(sstable_set_version* p);
+    sstable_set_version_reference(const sstable_set_version_reference& ref);
+    sstable_set_version_reference(sstable_set_version_reference&&);
```
Comment (avikivity) [inline sstables/sstable_set.hh:85]: This (and the assignment operator) should be noexcept, many algorithms and containers rely on it.

File: sstables/sstable_set.hh (hunk 25 above)
Comment (avikivity) [reply sstables/sstable_set.hh:78]: There is some support for incomplete classes with lw_shared_ptr, see shared_sstable.hh, lw_shared_ptr_deleted<shared_sstable> for an example.

If we can keep sstable_set and lw_shared_ptr<sstable_set> naming (but now they refer to a version) that may eliminate a large amount of churn. But don't go overboard trying to make it work, if it doesn't, then it doesn't.

File: sstables/sstable_set.hh [hunk 43]
```diff
@@ -47,24 +47,86 @@ public:
...
+};
+
+class sstable_set_version;
+
+class sstable_set_version_reference {
+    mutable sstable_set_version* _p = nullptr;
+public:
+    ~sstable_set_version_reference();
+    sstable_set_version_reference() = default;
+    sstable_set_version_reference(sstable_set_version* p);
```
Comment (avikivity) [inline sstables/sstable_set.hh:83]: This should be private if possible. I'm guessing this makes some assumptions about reference counting, so if it's used accidentally it can cause damage.

Comment (avikivity) [reply sstables/sstable_set.hh:83]: (and explicit)

File: sstables/sstable_set.hh [hunk 44]
```diff
@@ -47,24 +47,86 @@ public:
...
+class sstable_list {
+    sstable_set_version_reference _version;
+public:
+    sstable_list(std::unique_ptr<sstable_set_impl> impl, schema_ptr s);
+    sstable_list(const sstable_list& sstl);
+    sstable_list(sstable_list&& sstl) noexcept;
+    sstable_list& operator=(const sstable_list& sstl);
+    sstable_list& operator=(sstable_list&& sstl) noexcept;
+public:
+    class const_iterator : public std::iterator<std::forward_iterator_tag, const shared_sstable> {
```
Comment (avikivity) [inline sstables/sstable_set.hh:103]: Minor: std::iterator was deprecated in C++17.

File: test/boost/sstable_set_test.cc [hunk 45]
```diff
@@ -0,0 +1,269 @@
...
+static shared_sstable sstable_for_overlapping_test(test_env& env, const schema_ptr& schema, int64_t gen, sstring first_key, sstring last_key, uint32_t level = 0) {
+    auto sst = env.make_sstable(schema, "", gen, la, big);
+    sstables::test(sst).set_values_for_leveled_strategy(0, level, 0, std::move(first_key), std::move(last_key));
+    return sst;
+}
+
+using sstable_set_opt = std::optional<sstable_set>;
+using sstable_list_opt = std::optional<sstable_list>;
+
+SEASTAR_TEST_CASE(test_versioned_sstable_set_test) {
```
Comment (avikivity) [inline test/boost/sstable_set_test.cc:50]: This is almost a palindrome.

File: test/boost/sstable_set_test.cc [hunk 46]
```diff
@@ -0,0 +1,269 @@
...
+        list4 = std::nullopt;
+        // set' -> list5
+        //      -> list2
+        BOOST_REQUIRE_EQUAL(list2->version().get_previous_version(), list5->version().get_previous_version());
+        list2 = std::nullopt;
+        // list5
+        BOOST_REQUIRE_EQUAL(nullptr, list5->version().get_previous_version());
+        return make_ready_future<>();
+    });
+}
```
Comment (avikivity) [inline test/boost/sstable_set_test.cc:269]: I'd like to see a random walk test where the test generates random operations (add sstable, remove sstable, create version, delete version, get all, select, etc) and applies the random operations to both the new code, and to simpler code that uses copies to create versions, comparing the results for read operations. See chunked_vector_test for an example.

File: sstables/sstable_set.cc [hunk 47]
```diff
@@ -61,94 +61,422 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
...
+        _all_runs[sst->run_identifier()].insert(sst);
+        _all.insert(sst);
+        _times_added[sst] = 1;
+    } catch (...) {
+        _impl->erase(sst);
+        if (_all_runs.contains(sst->run_identifier())) {
+            _all_runs.at(sst->run_identifier()).erase(sst);
+        }
+        _all.erase(sst);
+        _times_added.erase(sst);
```
Comment (avikivity) [inline sstables/sstable_set.cc:84]: This is unneeded (if you use emplace), since there is no code following the emplace that can throw, and emplace is atomic.

File: sstables/sstable_set.cc [hunk 48]
```diff
@@ -61,94 +61,422 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
...
-        , _schema(x._schema)
-        , _all(make_lw_shared<sstable_list>(*x._all))
-        , _all_runs(x._all_runs) {
+void versioned_sstable_set_data::insert(shared_sstable sst) {
+    if (_times_added.contains(sst)) {
+        _times_added.at(sst)++;
+        return;
+    }
+    try {
+        _impl->insert(sst);
```
Comment (avikivity) [inline sstables/sstable_set.cc:74]: Unfortunately, this is also an O(n log n) operation in some cases. Those cases are for a partitioned_sstable_set, when a level 1 sstable is inserted or removed. A level 1 sstable covers 10% of the the token space managed the the node, and intersects with 10 L2 sstables and 100 L3 sstables. n log n for 100 is 700, so we need around 700 binary search tree operations for these cases.

Let's see the impact. If each operation takes 100ns (around 200 instructions, probably an over-estimate) then 700 operations take 70 usec. That's considerably lower than our 500 usec limit. If we extend it to L4 then we are at 10,000 operations or 1000 usec.

A table with a full-populated L3 overs 1000*160MB = 160GB per shard. An AWS i3 has 200GB per shard, so that's safe. I3en has 600 GB per shard, so it will spill into L4 (not fully populating it). I think we're safe though somewhat on the edge.

File: sstables/sstable_set.cc (hunk 29 above)
[the remark this answers is not in the document]
Comment (avikivity) [reply sstables/sstable_set.cc:70]: You can use try_emplace to cover both sides: get an iterator if the item exists, and insert it (and get an iterator) if it does not.

File: sstables/sstable_set.cc (hunk 24 above)
Comment (avikivity) [inline sstables/sstable_set.cc:118]: Shouldn't you compare with zero? You already decremented _reference_count.

File: sstables/sstable_set.cc [hunk 49]
```diff
@@ -61,94 +61,422 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
...
-    _impl->insert(sst);
-    try {
-        _all->insert(sst);
-        try {
-            _all_runs[sst->run_identifier()].insert(sst);
-        } catch (...) {
-            _all->erase(sst);
-            throw;
+sstable_set_version_reference::sstable_set_version_reference(const sstable_set_version_reference& ref) 
+    : _p(ref._p ? new sstable_set_version(ref._p) : nullptr) {
```
Comment (avikivity) [inline sstables/sstable_set.cc:134]: Why isn't this increasing the reference count only?

It's inconsistent that copying a reference creates a logical clone.

File: sstables/sstable_set.cc [hunk 50]
```diff
@@ -61,94 +61,422 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
...
-void
-sstable_set::erase(shared_sstable sst) {
-    _impl->erase(sst);
-    _all->erase(sst);
-    _all_runs[sst->run_identifier()].erase(sst);
+sstable_set_version_reference& sstable_set_version_reference::operator=(sstable_set_version_reference&& ref) {
+    if (this != &ref) {
+        this->~sstable_set_version_reference();
+        new (this) sstable_set_version_reference(std::move(ref));
+    }
```
Comment (avikivity) [inline sstables/sstable_set.cc:155]: Please avoid those placement-new tricks. I know the code is littered with them, but they're not completely legal, so I'd like to avoid introducing more.

File: sstables/sstable_set.cc [hunk 51]
```diff
@@ -61,94 +61,422 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
...
+    : _it(std::move(it))
+    , _ver(ver)
+{
+    while (_it != _ver->all().end() && !_ver->contains(*_it)) {
+        _it++;
+    }
+}
+
+sstable_list::const_iterator& sstable_list::const_iterator::operator++() {
+    if (_it != _ver->all().end()) {
```
Comment (avikivity) [inline sstables/sstable_set.cc:194]: It's illegal to advance past the end, you can assert that.

File: sstables/sstable_set.cc [hunk 52]
```diff
@@ -61,94 +61,422 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
...
+        _it++;
+    }
+    while (_it != _ver->all().end() && !_ver->contains(*_it)) {
+        _it++;
+    }
```
Comment (avikivity) [inline sstables/sstable_set.cc:199]: Recommend to extract to an advance() helper;

File: sstables/sstable_set.cc [hunk 53]
```diff
@@ -61,94 +61,422 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
...
+    operator++();
+    return it;
+}
+
+const shared_sstable& sstable_list::const_iterator::operator*() const {
+    return *_it;
+}
+
+bool sstable_list::const_iterator::operator==(const const_iterator& it) const {
+    return _it == it._it && _ver == it._ver;
```
Comment (avikivity) [inline sstables/sstable_set.cc:214]: In theory it is illegal to compare iterators that come from different containers (and here different versions are logically equivalent to different containers).

File: sstables/sstable_set.cc [hunk 54]
```diff
@@ -61,94 +61,422 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
...
+        *this = sstable_set(ssts);
+    }
+    return *this;
+}
+
+sstable_set& sstable_set::operator=(sstable_set&& ssts) noexcept {
+    if (this != &ssts) {
+        this->~sstable_set();
+        new (this) sstable_set(std::move(ssts));
+    }
```
Comment (avikivity) [inline sstables/sstable_set.cc:277]: Again, please avoid this trick.

File: sstables/sstable_set.cc [hunk 55]
```diff
@@ -61,94 +61,422 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
...
+sstable_set::incremental_selector::incremental_selector(std::unique_ptr<incremental_selector_impl> impl, const schema& s, lw_shared_ptr<sstable_list> sstl)
+    : _impl(std::move(impl))
+    , _cmp(s)
+    , _sstl(std::move(sstl)) {
+}
+
+sstable_set::incremental_selector::selection sstable_set::incremental_selector::select(const dht::ring_position_view& pos) const {
     if (!_current_range_view || !_current_range_view->contains(pos, _cmp)) {
-        std::tie(_current_range, _current_sstables, _current_next_position) = _impl->select(pos);
+        std::vector<shared_sstable> _current_versioned_sstables;
```
Comment (avikivity) [inline sstables/sstable_set.cc:315]: _ prefix is for data members, not locals.

File: sstables/sstable_set.cc [hunk 56]
```diff
@@ -61,94 +61,422 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
...
+        _versioned_data->remove(added_sst);
+    }
+    if (_prev) {
+        _prev->_next.erase(this);
+    }
+}
+
+sstable_set_version::sstable_set_version(std::unique_ptr<sstable_set_impl> impl, schema_ptr schema) 
+    : _versioned_data(make_lw_shared<versioned_sstable_set_data>(std::move(impl))) 
+    , _schema(std::move(schema)) {
```
Comment (avikivity) [inline sstables/sstable_set.cc:340]: Shouldn't we populate _times_added too? Why is this constructor different than calling insert() on every sstable?

File: sstables/sstable_set.cc [hunk 57]
```diff
@@ -61,94 +61,422 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
...
+}
+
+sstable_set_version::sstable_set_version(sstable_set_version* ver)
```
Comment (avikivity) [inline sstables/sstable_set.cc:343]: This is an odd constructor, usually the parameter is a const& or a &&. Why take a pointer?

Comment (avikivity) [reply sstables/sstable_set.cc:343]: Maybe add a tag to make it clear: sstable_set_version(sstable_set_version::create_child_tag, sstable_set_version* parent).

File: sstables/sstable_set.cc [hunk 58]
```diff
@@ -61,94 +61,422 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
...
+    , _schema(ver->_schema)
+    , _prev(ver) {
+        _prev->_next.insert(this);
+}
+
+size_t sstable_set_version::sstables_changed() const {
+    return _added.size() + _erased.size();
+}
+
+void sstable_set_version::merge_with_next() {
```
Comment (avikivity) [inline sstables/sstable_set.cc:354]: This is constrained on there being only one next, yes?

File: sstables/sstable_set.cc [hunk 59]
```diff
@@ -61,94 +61,422 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
...
+    auto next_version = *_next.begin();
+    if (sstables_changed() > next_version->sstables_changed()) {
+        std::swap(_added, next_version->_added);
+        std::swap(_erased, next_version->_erased);
+    }
+    for (auto&& sst : _added) {
+        if (!next_version->_erased.contains(sst)) {
+            next_version->_added.insert(sst);
+            _versioned_data->insert(sst);
+        } else {
```
Comment (avikivity) [inline sstables/sstable_set.cc:364]: This is called from a destructor, when a version is destroyed, yes? So it has to be noexcept and exception safe.

Maybe use container node operations (e.g. map::extract/map::merge)

File: sstables/sstable_set.cc [hunk 60]
```diff
@@ -61,94 +61,422 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
...
+            next_version->_erased.insert(sst);
+        } else {
+            next_version->_added.erase(sst);
+            _versioned_data->remove(sst);
+        }
+    }
+    if (_prev) {
+        _prev->_next.insert(*_next.begin());
+    }
+    (*_next.begin())->_prev = sstable_set_version_reference(_prev.get()); // destroys this by overwriting the last reference
```
Comment (avikivity) [inline sstables/sstable_set.cc:380]: Ah, now I understand the "references == 1" thing earlier.

First, such a thing should be documented.

Second, I think that only external references should be counted. This avoids the potential for cycles. Since you every internal reference to `this`  (_next->_prev) you also have a back reference, you know that as long as you have _next then you cannot release the content (but you can propagate it into the children).

File: sstables/sstable_set.cc (hunk 26 above)
Comment (avikivity) [reply sstables/sstable_set.cc:433]: I think it's fine to think of a copy operation as creating a new version.

File: sstables/sstable_set.cc [hunk 61]
```diff
@@ -61,94 +61,422 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
...
+    return _added.contains(sst) || (!_erased.contains(sst) && _prev && _prev->contains(sst));
+}
+
+size_t sstable_set_version::size() const {
+    return _added.size() - _erased.size() + (_prev ? _prev->size() : 0);
+}
+
+void sstable_set_version::insert(shared_sstable sst) {
+    if (this->contains(sst)) {
+        return;
```
Comment (avikivity) [inline sstables/sstable_set.cc:435]: Suppose this sequence happens:

a = sstable_set()
b = a; // create a child
a.insert(x);  // changes a._versioned_data
b.insert(x);  // does nothing, since b.contains(sst)
a.remove(x); // changes _versioned_data back

Does b still contain x?

File: sstables/sstable_set.cc [hunk 62]
```diff
@@ -61,94 +61,422 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
...
+void sstable_set_version::erase(shared_sstable sst) {
+    if (!this->contains(sst)) {
+        return;
+    }
+    if (_added.contains(sst)) {
+        _added.erase(sst);
+        _versioned_data->remove(sst);
+    } else {
+        _erased.insert(sst);
+        if (_prev->get_reference_count() == _prev->get_next_versions().size()) {
```
Comment (avikivity) [inline sstables/sstable_set.cc:459]: This confirms my understanding that internal references are counted. I think the code would be simpler if they weren't.

File: sstables/sstable_set.cc (hunk 61 above)
Comment (avikivity) [reply sstables/sstable_set.cc:435]: I think I see the answer below.

File: sstables/sstable_set.cc [hunk 63]
```diff
@@ -61,94 +61,422 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
...
+            for (auto ver : _prev->get_next_versions()) {
```
Comment (avikivity) [inline sstables/sstable_set.cc:460]: This looks at siblings. But what about sibling's children?

File: sstables/sstable_set.cc [hunk 64]
```diff
@@ -61,94 +61,422 @@ std::ostream& operator<<(std::ostream& os, const sstables::sstable_run& run) {
...
+                    return;
+                }
+            }
+            // we may be able to release the sstable
+            for (auto ver : _prev->get_next_versions()) {
+                ver->unerase(sst);
+            }
+            _prev->erase(sst);
+        }
+    }
```
Comment (avikivity) [inline sstables/sstable_set.cc:471]: Please document the logic behind the function. It looks like it's trying to see if an sstable is removed from all siblings and propagate it to the parent, which makes sense. But does this happen when a sibling is removed? A sibling destruction should have the same effect as removing all its members first.

**Comment by avikivity** [comment]
Looks good. Unfortunately I'm worried that although copy/insertion/removal/iteration from sstable_set is now O(1), insertion into partitioned_sstable_set is still O(n log n), albeit with smaller n.

We have three options to address it:
1. verify that the reduction in n is sufficient to prevent stalls
2. continue this work into partitioned_sstable_set. this is likely to be much harder since partitioned_sstable_set relies on boost interval_map
3. convert the atomic copy O(n) copy we have now (it's really an O(n log n) copy since each token range has O(log n) sstables) into a yielding copy, and add a lock to prevent concurrent copy and modification (like @bhalevy 's token_metadata changes)

The last option is much less satisfying, but guarantees results in bounded development time. Unfortunately the complication in interval_map is quite hard, if we don't manage to convince ourselves it isn't needed.

File: sstables/sstable_set.cc (hunk 37 above)
Comment (wmitros) [reply sstables/sstable_set.cc:102]: I think I should have used `at()` instead of brackets here. `sst` must be in `_times_added` because we're only calling `remove` on sstables from `_added` and `_erased` and we're assuring that `sst` is in `_times_added` when inserting to those two sets.

File: sstables/sstable_set.hh (hunk 38 above)
Comment (wmitros) [reply sstables/sstable_set.hh:45]: I moved it because as of right now, we need to see the member specification in both sstable_set.cc and compaction_strategy.cc: in sstable_set.cc we are using sstable_set_impl's methods when selecting or modifying the sstable_set, and in compaction_strategy.cc we're implementing `bag_sstable_set` and `partitioned_sstable_set` and we're using its constructor in `leveled_compaction_strategy::make_sstable_set`. I think I could move the bag- and partitioned- implementations but `make_sstable_set` should probably stay where it is

File: sstables/sstable_set.hh (hunk 40 above)
Comment (wmitros) [reply sstables/sstable_set.hh:64]: We can, I was thinking that I might be better to separate these two for easier understanding. In particular, I couldn't come up with a name that conveys the meanings of both these containers, I might end up with something like "_all_sstables_and_times_they_were_added"

File: sstables/sstable_set.hh (hunk 41 above)
Comment (wmitros) [reply sstables/sstable_set.hh:69]: Correct. 
It's similar to the approach from https://github.com/scylladb/scylla/pull/7272#discussion_r494367643 - when checking if an sstable is in a certain version, we're looking for an ancestor version that added or erased that sstable, but instead of checking if the ancestor version in in the vector of versions that add or erase this sstable (`vector<version_status>` from the referenced comment), we're checking if the sstable is in the set of changed sstables in the ancestor version.
This allows us to have just shared_sstables in the base version, and this makes it easier (and more efficient) to merge versions.
On another note, we could filter the sstables before creating the entire superset by passing the version as an argument. It would take the same time, but use less memory, but I'm not sure if that's needed

File: sstables/sstable_set.hh (hunk 42 above)
Comment (wmitros) [reply sstables/sstable_set.hh:85]: Ok

File: sstables/sstable_set.hh (hunk 44 above)
Comment (wmitros) [reply sstables/sstable_set.hh:103]: Ok, it's simple change, so I'll fix it even if it's minor

File: sstables/sstable_set.cc (hunk 47 above)
Comment (wmitros) [reply sstables/sstable_set.cc:84]: Ok

File: sstables/sstable_set.cc (hunk 52 above)
Comment (wmitros) [reply sstables/sstable_set.cc:199]: Ok

File: sstables/sstable_set.cc (hunk 51 above)
Comment (wmitros) [reply sstables/sstable_set.cc:194]: Ok

File: sstables/sstable_set.cc (hunk 53 above)
Comment (wmitros) [reply sstables/sstable_set.cc:214]: Should we assert that then? Or could we allow that and check first if versions match  (`_ver == it._ver && _it == it._it`) so that we don't compare `_it` if they come from different containers?

File: sstables/sstable_set.cc (hunk 54 above)
Comment (wmitros) [reply sstables/sstable_set.cc:277]: Ok

File: sstables/sstable_set.cc (hunk 55 above)
Comment (wmitros) [reply sstables/sstable_set.cc:315]: Ok

File: sstables/sstable_set.cc (hunk 58 above)
Comment (wmitros) [reply sstables/sstable_set.cc:354]: Yes

File: sstables/sstable_set.cc (hunk 63 above)
Comment (wmitros) [reply sstables/sstable_set.cc:460]: If the check succeeded for all sibling's children, the change would have been propagated to the sibling, so if the check fails for the sibling, it will also fail for one of its children

File: sstables/sstable_set.cc (hunk 64 above)
Comment (wmitros) [reply sstables/sstable_set.cc:471]: You're right, there's also a third option which may trigger this propagation - the parent gets removed (more precisely, its external reference). I'm adding it right now

File: sstables/sstable_set.cc (hunk 60 above)
Comment (wmitros) [reply sstables/sstable_set.cc:380]: I'm not sure what does counting only external references help with. If I'm not mistaken, if we were still using the emptiness of `_next` as a condition for releasing a version, we could still in theory have a the same potential cycles. 
I don't see how it could simplify the code either: we would have to add some kind of marker which tells whether a reference is external or not, and some ifs that check whether we should modify the `_reference_count` or not. 
I guess another solution would be to remove sstable_set_version_references from sstable_set_versions altogether and replace them with pointers - in this case we would need to have to do the work of `sstable_set_version_reference`'s destructor in each method that would destroy `_prev` - so in the merge method and in `sstable_set_versions`'s destructor.
We could also remove the class altogether, but that would require adding the same code as in the second option, and in every place where we destroy/reassign `sstable_list`'s `_version`

File: sstables/sstable_set.cc (hunk 56 above)
Comment (wmitros) [reply sstables/sstable_set.cc:340]: We're assuming that an sstable_set is constructed from an empty sstable_set_impl. We were assuming that before the whole patchset too but it wasn't specified anywhere - I've added checks for it in the second patch of the series.
Considering I'm modifying the entire sstable_set I could probably change this constructor to work on any sstable_set_impl, but I'm not sure if that may ever be needed

File: sstables/sstable_set.cc (hunk 50 above)
Comment (wmitros) [reply sstables/sstable_set.cc:155]: Ok

File: sstables/sstable_set.cc (hunk 49 above)
Comment (wmitros) [reply sstables/sstable_set.cc:134]: We don't actually ever want to copy an `sstable_set_version_reference`, but when we copy a class that has a sstable_set_version_reference (i.e. an sstable_list or sstable_set), we want to have a reference to a new version in it, so I used the copy constructor for it.
I can see though that it's not really consistent, so I can change the copy constructor to be marked deleted and use a custom constructor instead, if that was simpler

File: sstables/sstable_set.hh (hunk 40 above)
Comment (denesb) [reply sstables/sstable_set.hh:64]: I would also favour consolidating the different containers into one. `_all` is a good name, as long as the value's type name tells us what it is.

Comment (denesb) [reply sstables/sstable_set.hh:64]: Maybe we can even add `_removed` here and have a value be a:
```
struct sstable_meta {
     shared_sstable sst;
     unsigned times_added;
     bool removed;
};
```

File: sstables/sstable_set.cc (hunk 60 above)
Comment (avikivity) [reply sstables/sstable_set.cc:380]: > I'm not sure what does counting only external references help with. 

It's just an intuition. Maybe it's wrong. However, whichever way we choose it must be explained, since there are two ways to understand it.

> If I'm not mistaken, if we were still using the emptiness of `_next` as a condition for releasing a version, we could still in theory have a the same potential cycles.
> I don't see how it could simplify the code either: we would have to add some kind of marker which tells whether a reference is external or not, and some ifs that check whether we should modify the `_reference_count` or not.

The code always knows whether a reference is internal or external. If it's from an sstable_set object, it's external, if it's from an sstable_set_version object, it's internal.

> I guess another solution would be to remove sstable_set_version_references from sstable_set_versions altogether and replace them with pointers - in this case we would need to have to do the work of `sstable_set_version_reference`'s destructor in each method that would destroy `_prev` - so in the merge method and in `sstable_set_versions`'s destructor.

Yes.

> We could also remove the class altogether, but that would require adding the same code as in the second option, and in every place where we destroy/reassign `sstable_list`'s `_version`

**Comment by wmitros** [comment]
I've added another new version of the sstable_set. The main changes from the previous version are:

- changing the approach with merging - the sstables are now merged to the parent version as soon as it's possible - so when the parent has no external references and all its children have the same change. Because of that, actual version merging is now just reassigning some variables.
- making all methods used in destructors noexcept with the help of node handles
- comments
- adding a random walk test

**Comment by avikivity** [comment]
@wmitros I'd like to see a benchmark to see where we stand with latency.

The worst case I can see is an LCS, an L0->L1 promotion creating an L1 sstable, when L2 and L3 also exist. Hopefully it can be done artificially, without inserting 160GB of data.

**Comment by wmitros** [comment]
I'm not sure if that's what you wanted @avikivity, but I've modified @raphaelsc unit test to #7758 so that it measures how long does it take to replace 10 sstables of the same LCS level with new ones, when all levels 1-3 are full (if I'm not mistaken, in LSC we're replacing 1 sstable of level i with ~10 sstables of level i+1 with ~11 sstables of level i+1, so the scenario should not be too different).
For reference, on my machine the times on levels L1, L2, L3 were 71ms, 11ms, 5ms compared to 195ms, 239ms, 222ms on the previous version. 
I've also solved some merge conflicts that arose because of #7655

**Comment by avikivity** [comment]
Well, 71ms is still terrible. So the patch was successful in reducing the amount of compute work, but latency changed from unacceptable to still unacceptable.

Note that L1 replacements are the most common ones, after L0.

btw, it looks excessive. The interval tree is O(n log n), and with full L3, n =~ 1000, so n log n =~ 10,000. Updating L1 touches 100 nodes, so we have 1,000,000 operations. That translates to 71ns per op - actually not that excessive, considering many ops have to reallocate an internal vector, and that this is quite complicated and many instructions need to run. The fact that we use ring_position instead of token makes it worse (but is still needed since partitions can collide, and we need to preserve the order).

So we'll need to follow up with inserting yields in strategic places. This means that insert() and erase() will need to return futures, and that the callers will need to lock the sstable_set to prevent concurrent operations. Pretty sad.

/cc @bhalevy @raphaelsc

File: sstables/sstable_set.cc (hunk 50 above)
Comment (avikivity) [reply sstables/sstable_set.cc:159]: @wmitros ^

File: sstables/sstable_set.cc (hunk 56 above)
Comment (avikivity) [reply sstables/sstable_set.cc:339]: Just add a comment.

File: sstables/sstable_set.cc (hunk 7 above)
Comment (avikivity) [reply sstables/sstable_set.cc:499]: Was that done?

File: sstables/sstable_set.cc (hunk 64 above)
Comment (avikivity) [reply sstables/sstable_set.cc:551]: Was the documentation added?

Comment (avikivity) [reply sstables/sstable_set.cc:551]: I see there is something below.

File: test/perf/perf_sstable_set.cc [hunk 65]
```diff
@@ -0,0 +1,111 @@
...
+        for (auto i = 0; i < 30; i++) {
+            auto [min, max] = min_max_keys(1 + i / 10, i % 10);
+            auto sst = sstable_for_overlapping_test(env, s, i, min, max, 1 + i / 10);
+            outputs[i / 10].push_back(sst);
+            seastar::thread::maybe_yield();
+        }
+        for (auto i = 0; i < 3; i++) {
+            auto t1 = high_resolution_clock::now();
+            column_family_test(cf).rebuild_sstable_list(outputs[i], inputs[i]);
+            auto t2 = high_resolution_clock::now();
```
Comment (avikivity) [inline test/perf/perf_sstable_set.cc:105]: We're interested in two things: the time it takes, and the latency it imposes on other work. This is defined as the maximum time a single atomic continuation takes. We reduced the compute time it takes, but the latency is still high.

This is my fault, the whole idea could only reduce the latency by a constant factor, not reduce the computational complexity.

File: sstables/sstable_set.cc (hunk 50 above)
Comment (wmitros) [reply sstables/sstable_set.cc:159]: I'm not sure what happened, but it looks like this comment refers to a commit that isn't in the PR anymore, all placement-new constructions have been already removed

File: sstables/sstable_set.cc (hunk 56 above)
Comment (wmitros) [reply sstables/sstable_set.cc:339]: This also refers to an older commit, but in the newest version there is no indication that the set must be empty in this constructor(sstable_set_version). Instead, I've added a logic_error that checks it in the sstable_set constructor. Do you think a comment would be useful here too?

File: sstables/sstable_set.cc (hunk 7 above)
Comment (wmitros) [reply sstables/sstable_set.cc:499]: It was done in the meantime in another patch that had already been merged: #7655

File: sstables/sstable_set.cc (hunk 56 above)
Comment (avikivity) [reply sstables/sstable_set.cc:339]: I'm lost in the details, but a comment can't hurt [1], whereas the lack of a comment can.

[1] a wrong comment can hurt

Comment (wmitros) [reply sstables/sstable_set.cc:341]: Ok, I'm adding comments in both places then

**Comment by wmitros** [comment]
@avikivity there hasn't been any significant changes since the last comments and all requested changes have been already addressed, so if there's still something preventing this PR from merging, please let me know.

**Comment by avikivity** [comment]
I see there several questions with no answers. Or were they answered elsewhere?

**Comment by avikivity** [comment]
btw, 8dd7280107706084f4d65489c6aa59fed3998e33 should improve things (orthogonally to this series)

File: sstables/compaction.cc (hunk 14 above)
[the remark this answers is not in the document]
Comment (wmitros) [reply sstables/compaction.cc]: It is now

File: test/boost/sstable_datafile_test.cc (hunk 8 above)
Comment (wmitros) [reply test/boost/sstable_datafile_test.cc]: There shouldn't be problems with code churn now, almost all names and semantics changes have been removed in later versions

File: test/boost/sstable_datafile_test.cc (hunk 9 above)
Comment (wmitros) [reply test/boost/sstable_datafile_test.cc]: They have been moved in following versions

File: sstables/sstable_set.hh (hunk 40 above)
Comment (wmitros) [reply sstables/sstable_set.hh]: I've combined them to a single std::map

File: sstables/sstable_set.hh (hunk 43 above)
Comment (wmitros) [reply sstables/sstable_set.hh]: I've changed it to private and explicit

File: test/boost/sstable_set_test.cc (hunk 45 above)
Comment (wmitros) [reply test/boost/sstable_set_test.cc]: I'm simply using the full type in the next versions

File: test/boost/sstable_set_test.cc (hunk 46 above)
Comment (wmitros) [reply test/boost/sstable_set_test.cc]: You can see it in the case `sstable_set_random_walk_test`

File: api/storage_service.cc (hunk 39 above)
Comment (wmitros) [reply api/storage_service.cc:982]: I've added it as issue #7605

File: sstables/sstable_set.cc (hunk 24 above)
Comment (wmitros) [reply sstables/sstable_set.cc]: We're checking here if there is exactly one reference to this version and it's from another version (not from a sstable_list) because it's the only scenario where we're merging versions

File: sstables/sstable_set.cc (hunk 57 above)
Comment (wmitros) [reply sstables/sstable_set.cc]: I've added a comment and changed the constructor to private and explicit, it shouldn't be used by mistake now, and if used intentionally, it should be also clear what it does

File: sstables/sstable_set.cc (hunk 59 above)
Comment (wmitros) [reply sstables/sstable_set.cc]: I've changed this and all other methods that are called from destructors to noexcept and exception safe using your advice (the node operations)

File: sstables/sstable_set.cc (hunk 62 above)
Comment (wmitros) [reply sstables/sstable_set.cc]: I couldn't find a way to make the code simpler with counting only external references (there is at most 1 at all times), but I've added a comment explaining what is counted

**Comment by wmitros** [comment]
> btw, [8dd7280](https://github.com/scylladb/scylla/commit/8dd7280107706084f4d65489c6aa59fed3998e33) should improve things (orthogonally to this series)

Actually, this code is already slightly modifying that change because of the merge conflict that we've had in `table::build_new_sstable_list()`

As for the unanswered questions, I've added replies to the older comments that weren't answered here yet (but the code has been already changed in previous rebases). The comments since the change that adds the benchmark have been already answered in-code (except https://github.com/scylladb/scylla/pull/7272#discussion_r541906789, but if I'm not mistaken, the latency has been improved in [8dd7280](https://github.com/scylladb/scylla/commit/8dd7280107706084f4d65489c6aa59fed3998e33), so we don't need to add anything concerning it here)

**Comment by avikivity** [comment]
@wmitros answers in code are hard for the reviewer to associate with questions. In the future, please acknowledge each comment and explain how you addressed it (or why nothing needs to be done). Consider the reviewer as a stateless, reloading their state from the questions each time. Telling them to re-read the series to see answers is piling more work for them.

**Comment by avikivity** [comment]
Dequeued, does not build.

**Comment by wmitros** [comment]
Looks like it's conflicting with another patch that is being merged right now (sstables: consolidate reader factory methods), so I'll wait with the fixes until that patch gets merged successfully

**Comment by denesb** [comment]
> Looks like it's conflicting with another patch that is being merged right now (sstables: consolidate reader factory methods), so I'll wait with the fixes until that patch gets merged successfully

The above mentioned patchset was dequeued due to dtest failures. As it is a side project of mine, it can take a while for me to find the cycles to send a new version. All this is to say that you shouldn't wait on it, just go ahead and I'll sort out the conflicts later.

**Comment by avikivity** [comment]
I requeued, let's see.

**Comment by bhalevy** [comment]
Crashed in https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/3050/artifact/logs-release.2/1610625409553_bootstrap_test.TestBootstrap.start_stop_test_node/node2.log
```
INFO  2021-01-14 11:47:12,255 [shard 0] stream_session - [Stream #3d6f21e0-565e-11eb-abfb-000000000000] Executing streaming plan for Bootstrap-system_distributed-index-3 with peers=127.0.53.3, slave
INFO  2021-01-14 11:47:12,255 [shard 1] stream_session - [Stream #3d6f21e0-565e-11eb-abfb-000000000000] Skip sending ks=system_distributed, cf=cdc_streams_descriptions, reader contains no data, with new rpc streaming
Segmentation fault on shard 0.
Backtrace:
  0x0000000003911994
  0x000000000391bdf9
  0x00007f17628e01df
  0x000000000149b516
  0x000000000149ca67
  0x0000000002b50757
  0x0000000002b4f93c
  0x0000000002b6075a
  0x00000000038fcacf
  0x00000000038fdcb7
  0x000000000389bb85
  0x000000000389afa6
  0x0000000000e083fc
  /jenkins/workspace/scylla-master/next/scylla/.ccm/scylla-repository/24ef2e4d39f0533ac602bcaed279e31ca198cbde/scylla/libreloc/libc.so.6+0x00000000000281e1
  0x0000000000e052ed
```

I reproduced locally and got the following stack trace:
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:731
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&) at ./build/release/seastar/./seastar/src/core/reactor.cc:752
 (inlined by) seastar::print_with_backtrace(char const*) at ./build/release/seastar/./seastar/src/core/reactor.cc:759
seastar::sigsegv_action() at ./build/release/seastar/./seastar/src/core/reactor.cc:3546
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3532
 (inlined by) __invoke at ./build/release/seastar/./seastar/src/core/reactor.cc:3528
?? ??:0
sstables::sstable::get_index_pages_for_range(nonwrapping_interval<dht::token> const&) at ./sstables/sstables.cc:2517
sstables::sstable::estimated_keys_for_range(nonwrapping_interval<dht::token> const&) at ./sstables/sstables.cc:2575
operator()<nonwrapping_interval<dht::token> > at ./streaming/stream_transfer_task.cc:127
 (inlined by) seastar::future<void> seastar::futurize<void>::invoke<streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}::operator()<seastar::lw_shared_ptr<sstables::sstable_list const> >(seastar::lw_shared_ptr<sstables::sstable_list const>&, unsigned long&) const::{lambda(auto:1&)#1}::operator()<{lambda(auto:1&, unsigned long&)#1}::operator()<seastar::lw_shared_ptr::sstable> const>(seastar::lw_shared_ptr<sstables::sstable_list const>&) const::{lambda(auto:1&)#1}&, nonwrapping_interval<dht::token>&>(seastar::lw_shared_ptr<sstables::sstable_list const>&&, nonwrapping_interval<dht::token>&) at ././seastar/include/seastar/core/future.hh:2132
 (inlined by) auto seastar::futurize_invoke<streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}::operator()<seastar::lw_shared_ptr<sstables::sstable_list const> >(seastar::lw_shared_ptr<sstables::sstable_list const>&, unsigned long&) const::{lambda(auto:1&)#1}::operator()<{lambda(auto:1&, unsigned long&)#1}::operator()<seastar::lw_shared_ptr::sstable> const>(seastar::lw_shared_ptr<sstables::sstable_list const>&) const::{lambda(auto:1&)#1}&, nonwrapping_interval<dht::token>&>(seastar::lw_shared_ptr<sstables::sstable_list const>&&, nonwrapping_interval<dht::token>&) at ././seastar/include/seastar/core/future.hh:2166
 (inlined by) seastar::future<void> seastar::internal::do_for_each_impl<__gnu_cxx::__normal_iterator<nonwrapping_interval<dht::token>*, std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > >, streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}::operator()<seastar::lw_shared_ptr<sstables::sstable_list const> >(seastar::lw_shared_ptr<sstables::sstable_list const>&, unsigned long&) const::{lambda(auto:1&)#1}::operator()<{lambda(auto:1&, unsigned long&)#1}::operator()<seastar::lw_shared_ptr::sstable> const>(seastar::lw_shared_ptr<sstables::sstable_list const>&) const::{lambda(auto:1&)#1}>(__gnu_cxx::__normal_iterator<nonwrapping_interval<dht::token>*, std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > >, __gnu_cxx::__normal_iterator<nonwrapping_interval<dht::token>*, std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > >, streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}::operator()<seastar::lw_shared_ptr<sstables::sstable_list const> >(seastar::lw_shared_ptr<sstables::sstable_list const>&, unsigned long&) const::{lambda(auto:1&)#1}::operator()<{lambda(auto:1&, unsigned long&)#1}::operator()<seastar::lw_shared_ptr::sstable> const>(seastar::lw_shared_ptr<sstables::sstable_list const>&) const::{lambda(auto:1&)#1}) at ././seastar/include/seastar/core/loop.hh:421
 (inlined by) seastar::future<void> seastar::do_for_each<std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > >, streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}::operator()<seastar::lw_shared_ptr<sstables::sstable_list const> >(seastar::lw_shared_ptr<sstables::sstable_list const>&, unsigned long&) const::{lambda(auto:1&)#1}::operator()<{lambda(auto:1&, unsigned long&)#1}::operator()<seastar::lw_shared_ptr::sstable> const>(seastar::lw_shared_ptr<sstables::sstable_list const>&) const::{lambda(auto:1&)#1}>(seastar::lw_shared_ptr<sstables::sstable_list const>&, streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}::operator()<seastar::lw_shared_ptr<sstables::sstable_list const> >(seastar::lw_shared_ptr<sstables::sstable_list const>&, unsigned long&) const::{lambda(auto:1&)#1}::operator()<{lambda(auto:1&, unsigned long&)#1}::operator()<seastar::lw_shared_ptr::sstable> const>(seastar::lw_shared_ptr<sstables::sstable_list const>&) const::{lambda(auto:1&)#1}) at ././seastar/include/seastar/core/loop.hh:480
 (inlined by) operator()<const seastar::lw_shared_ptr<sstables::sstable> > at ./streaming/stream_transfer_task.cc:126
 (inlined by) seastar::future<void> seastar::futurize<seastar::future<void> >::invoke<streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}::operator()<seastar::lw_shared_ptr<sstables::sstable_list const> >(seastar::lw_shared_ptr<sstables::sstable_list const>&, unsigned long&) const::{lambda(auto:1&)#1}&, {lambda(auto:1&, unsigned long&)#1}::operator()<seastar::lw_shared_ptr::sstable> const&>(seastar::lw_shared_ptr<sstables::sstable_list const>&&, {lambda(auto:1&, unsigned long&)#1}::operator()<seastar::lw_shared_ptr::sstable> const&) at ././seastar/include/seastar/core/future.hh:2135
 (inlined by) auto seastar::futurize_invoke<streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}::operator()<seastar::lw_shared_ptr<sstables::sstable_list const> >(seastar::lw_shared_ptr<sstables::sstable_list const>&, unsigned long&) const::{lambda(auto:1&)#1}&, {lambda(auto:1&, unsigned long&)#1}::operator()<seastar::lw_shared_ptr::sstable> const&>(seastar::lw_shared_ptr<sstables::sstable_list const>&&, {lambda(auto:1&, unsigned long&)#1}::operator()<seastar::lw_shared_ptr::sstable> const&) at ././seastar/include/seastar/core/future.hh:2166
 (inlined by) seastar::future<void> seastar::internal::do_for_each_impl<sstables::sstable_list::const_iterator, streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}::operator()<seastar::lw_shared_ptr<sstables::sstable_list const> >(seastar::lw_shared_ptr<sstables::sstable_list const>&, unsigned long&) const::{lambda(auto:1&)#1}>(sstables::sstable_list::const_iterator, sstables::sstable_list::const_iterator, streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}::operator()<seastar::lw_shared_ptr<sstables::sstable_list const> >(seastar::lw_shared_ptr<sstables::sstable_list const>&, unsigned long&) const::{lambda(auto:1&)#1}) at ././seastar/include/seastar/core/loop.hh:421
 (inlined by) seastar::future<void> seastar::do_for_each<sstables::sstable_list const, streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}::operator()<seastar::lw_shared_ptr<sstables::sstable_list const> >(seastar::lw_shared_ptr<sstables::sstable_list const>&, unsigned long&) const::{lambda(auto:1&)#1}>(seastar::lw_shared_ptr<sstables::sstable_list const>&, streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}::operator()<seastar::lw_shared_ptr<sstables::sstable_list const> >(seastar::lw_shared_ptr<sstables::sstable_list const>&, unsigned long&) const::{lambda(auto:1&)#1}) at ././seastar/include/seastar/core/loop.hh:480
 (inlined by) operator()<seastar::lw_shared_ptr<const sstables::sstable_list> > at ./streaming/stream_transfer_task.cc:125
 (inlined by) seastar::future<unsigned long> std::__invoke_impl<seastar::future<unsigned long>, streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}&, seastar::lw_shared_ptr<sstables::sstable_list const>&, unsigned long&>(std::__invoke_other, streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}&, seastar::lw_shared_ptr<sstables::sstable_list const>&, unsigned long&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
 (inlined by) std::__invoke_result<streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}&, seastar::lw_shared_ptr<sstables::sstable_list const>&, unsigned long&>::type std::__invoke<streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}&, seastar::lw_shared_ptr<sstables::sstable_list const>&, unsigned long&>(streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}&, (std::__invoke_result&&)...) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:95
 (inlined by) decltype(auto) std::__apply_impl<streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}&, std::tuple<seastar::lw_shared_ptr<sstables::sstable_list const>, unsigned long>&, 0ul, 1ul>(streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}&, std::tuple<seastar::lw_shared_ptr<sstables::sstable_list const>, unsigned long>&, std::integer_sequence<unsigned long, 0ul, 1ul>) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/tuple:1723
 (inlined by) decltype(auto) std::apply<streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}&, std::tuple<seastar::lw_shared_ptr<sstables::sstable_list const>, unsigned long>&>(streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}&, std::tuple<seastar::lw_shared_ptr<sstables::sstable_list const>, unsigned long>&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/tuple:1734
 (inlined by) auto seastar::internal::do_with_impl<seastar::lw_shared_ptr<sstables::sstable_list const>, unsigned long, streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}>(seastar::lw_shared_ptr<sstables::sstable_list const>&&, unsigned long&&, streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}&&) at ././seastar/include/seastar/core/do_with.hh:96
 (inlined by) seastar::future<unsigned long> seastar::futurize<seastar::future<unsigned long> >::invoke<seastar::future<unsigned long> (*&)(seastar::lw_shared_ptr<sstables::sstable_list const>&&, unsigned long&&, streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}&&), seastar::lw_shared_ptr<sstables::sstable_list const>, unsigned long, {lambda(auto:1&, unsigned long&)#1}>(seastar::future<unsigned long> (*&)(seastar::lw_shared_ptr<sstables::sstable_list const>&&, unsigned long&&, streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}&&), seastar::lw_shared_ptr<sstables::sstable_list const>&&, unsigned long&&, {lambda(auto:1&, unsigned long&)#1}&&) at ././seastar/include/seastar/core/future.hh:2135
 (inlined by) auto seastar::futurize_invoke<seastar::future<unsigned long> (*&)(seastar::lw_shared_ptr<sstables::sstable_list const>&&, unsigned long&&, streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}&&), seastar::lw_shared_ptr<sstables::sstable_list const>, unsigned long, {lambda(auto:1&, unsigned long&)#1}>(seastar::future<unsigned long> (*&)(seastar::lw_shared_ptr<sstables::sstable_list const>&&, unsigned long&&, streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}&&), seastar::lw_shared_ptr<sstables::sstable_list const>&&, unsigned long&&, {lambda(auto:1&, unsigned long&)#1}&&) at ././seastar/include/seastar/core/future.hh:2166
 (inlined by) auto seastar::do_with<seastar::lw_shared_ptr<sstables::sstable_list const>, unsigned long, streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}>(seastar::lw_shared_ptr<sstables::sstable_list const>&&, unsigned long&&, streaming::send_info::estimate_partitions()::{lambda(auto:1&, unsigned long&)#1}&&) at ././seastar/include/seastar/core/do_with.hh:131
streaming::send_info::estimate_partitions() at ./streaming/stream_transfer_task.cc:124
 (inlined by) operator() at ./streaming/stream_transfer_task.cc:144
seastar::future<void> std::__invoke_impl<seastar::future<void>, streaming::send_mutation_fragments(seastar::lw_shared_ptr<streaming::send_info>)::$_0&, mutation_fragment*>(std::__invoke_other, streaming::send_mutation_fragments(seastar::lw_shared_ptr<streaming::send_info>)::$_0&, mutation_fragment*&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
 (inlined by) std::__invoke_result<streaming::send_mutation_fragments(seastar::lw_shared_ptr<streaming::send_info>)::$_0&, mutation_fragment*>::type std::__invoke<streaming::send_mutation_fragments(seastar::lw_shared_ptr<streaming::send_info>)::$_0&, mutation_fragment*>(streaming::send_mutation_fragments(seastar::lw_shared_ptr<streaming::send_info>)::$_0&, mutation_fragment*&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:95
 (inlined by) std::invoke_result<streaming::send_mutation_fragments(seastar::lw_shared_ptr<streaming::send_info>)::$_0&, mutation_fragment*>::type std::invoke<streaming::send_mutation_fragments(seastar::lw_shared_ptr<streaming::send_info>)::$_0&, mutation_fragment*>(streaming::send_mutation_fragments(seastar::lw_shared_ptr<streaming::send_info>)::$_0&, mutation_fragment*&&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/functional:88
 (inlined by) auto seastar::internal::future_invoke<streaming::send_mutation_fragments(seastar::lw_shared_ptr<streaming::send_info>)::$_0&, mutation_fragment*>(streaming::send_mutation_fragments(seastar::lw_shared_ptr<streaming::send_info>)::$_0&, mutation_fragment*&&) at ././seastar/include/seastar/core/future.hh:1211
 (inlined by) operator() at ././seastar/include/seastar/core/future.hh:1582
 (inlined by) void seastar::futurize<seastar::future<void> >::satisfy_with_result_of<seastar::future<mutation_fragment*>::then_impl_nrvo<streaming::send_mutation_fragments(seastar::lw_shared_ptr<streaming::send_info>)::$_0, seastar::future<void> >(streaming::send_mutation_fragments(seastar::lw_shared_ptr<streaming::send_info>)::$_0&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, streaming::send_mutation_fragments(seastar::lw_shared_ptr<streaming::send_info>)::$_0&, seastar::future_state<mutation_fragment*>&&)#1}::operator()(seastar::internal::promise_base_with_type<void>&&, streaming::send_mutation_fragments(seastar::lw_shared_ptr<streaming::send_info>)::$_0&, seastar::future_state<mutation_fragment*>&&) const::{lambda()#1}>(seastar::internal::promise_base_with_type<void>&&, streaming::send_mutation_fragments(seastar::lw_shared_ptr<streaming::send_info>)::$_0&&) at ././seastar/include/seastar/core/future.hh:2120
 (inlined by) operator() at ././seastar/include/seastar/core/future.hh:1575
 (inlined by) seastar::continuation<seastar::internal::promise_base_with_type<void>, streaming::send_mutation_fragments(seastar::lw_shared_ptr<streaming::send_info>)::$_0, seastar::future<mutation_fragment*>::then_impl_nrvo<streaming::send_mutation_fragments(seastar::lw_shared_ptr<streaming::send_info>)::$_0, seastar::future<void> >(streaming::send_mutation_fragments(seastar::lw_shared_ptr<streaming::send_info>)::$_0&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, streaming::send_mutation_fragments(seastar::lw_shared_ptr<streaming::send_info>)::$_0&, seastar::future_state<mutation_fragment*>&&)#1}, mutation_fragment*>::run_and_dispose() at ././seastar/include/seastar/core/future.hh:767
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2220
 (inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:2629
seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2788
operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3979
 (inlined by) void std::__invoke_impl<void, seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&>(std::__invoke_other, seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60
 (inlined by) std::enable_if<is_invocable_r_v<void, seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&>, void>::type std::__invoke_r<void, seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&>(seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:110
 (inlined by) std::_Function_handler<void (), seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::$_97>::_M_invoke(std::_Any_data const&) at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:291
std::function<void ()>::operator()() const at /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:622
 (inlined by) seastar::posix_thread::start_routine(void*) at ./build/release/seastar/./seastar/src/core/posix.cc:60
```

**Comment by raphaelsc** [comment]
On Thu, Jan 14, 2021 at 7:13 AM Avi Kivity <notifications@github.com> wrote:

> I requeued, let's see.
>
Are we changing partitioned_sstable_set in this series to fix insert
complexity of O( (~10^(Lmax - L)) * 1.111..)? where Lmax is the maximum
level and L is the level being inserted.

Looks like after this series we're no longer rebuilding the sstable set
from scratch on compaction completion, because if we were still doing so,
we could fix this insert issue by inserting the sstables from the lowest
level towards the highest one.

**Comment by wmitros** [comment]
You're right that after this series we're no longer rebuilding the sstable set on compaction completion, so we can't fix this by changing the order of insertions anymore.
The complexity of a single random insertion is still big though, so we should improve it in the future

**Comment by avikivity** [comment]
One thing we can try is to change the sstable fragment size from 160MB to 1GB. Need to think about any effects, including transitioning an existing workload.

**Comment by raphaelsc** [comment]
On Fri, Jan 15, 2021 at 6:26 AM Avi Kivity <notifications@github.com> wrote:

> One thing we can try is to change the sstable fragment size from 160MB to
> 1GB. Need to think about any effects, including transitioning an existing
> workload.
>
I thought of two things to consider here (maybe there are more):

increasing size to 1TB means the capacity of each level is 6.25x higher,
so...

1) how will LCS currently handle demotion? do we need any fix in that area
to prevent transition from being troublesome? as the # of levels required
to store data is potentially decreased
2) what's the effect on WA? as L1 is 6.25x bigger, L0->L1 compaction (which
happens quite often) can have its efficiency decreased as the size ratio of
L1 and L0 will be higher. however, with the # of levels decreasing, perhaps
the effects cancel each other out. the increase in space requirement isn't
something to worry about as incremental compaction can release exhausted
fragments earlier.

both of these concerns need to be carefully studied before we can proceed
with the change. perhaps it's worth a simulation. i can work on this once i
am back from vacation at jan 29th.

**Comment by wmitros** [comment]
I had just finished my exams, so I could finally fix this, sorry for the delay. The reason for the crash was the postfix ++ operator of the sstable_list iterator, which, as it turns out, isn't used in 'for' loops but is in seastar's 'do_for_each' - that's why it crashed in https://github.com/scylladb/scylla/blob/9cbbf40710f0b46056cac18d256e0886d1d62dfc/streaming/stream_transfer_task.cc#L124-L128. Considering that we might want to use asynchronous iteration, like in the case above, I've also found and fixed a potential issue with the iterator - it kept a sstable_set_version* which could change when modifying the sstable_list before, now it has a pointer to the sstable_list's member (of type sstable_set_version_reference).

I've checked unit tests, the crashing dtest and some other dtests concerning sstables, so the most recent version should work now.

**Comment by wmitros** [comment]
@avikivity can we try to merge it again? It's marked as merged but it has been dequeued

**Comment by raphaelsc** [comment]
> @avikivity can we try to merge it again? It's marked as merged but it has been dequeued

Now that the stalls are gone, I'd like to understand the value that versioned sstable set is really bringing us. Is it improving performance when updating the sstable set on compaction completion (which used to rebuild set from scratch)? Versioned sstable set adds lots of complex code that will be hard to maintain and we need a good justification for merging it. From what I remember, after versioned set, we'll still a high cost when inserting a sstable in the interval map, and that could be fixed without the versioned set. If it does improve performance significantly when updating set, that's a very good reason already for merging this work.

**Comment by avikivity** [comment]
In any case, it doesn't build any more as many things changed.

**Comment by wmitros** [comment]
> > @avikivity can we try to merge it again? It's marked as merged but it has been dequeued
> 
> Now that the stalls are gone, I'd like to understand the value that versioned sstable set is really bringing us. Is it improving performance when updating the sstable set on compaction completion (which used to rebuild set from scratch)? Versioned sstable set adds lots of complex code that will be hard to maintain and we need a good justification for merging it. From what I remember, after versioned set, we'll still have a high cost when inserting a sstable in the interval map (inversely proportional to the level the sstable belongs to), and that could be fixed without the versioned set. If it does improve performance significantly when updating set, that's a very good reason already for merging this work.

The main aim for this patch was to stop rebuilding the sstable set after adding or replacing sstables in the set. It also allowed to avoid copying the set for compaction descriptors and for the mutation reader from `make_reader_excluding_sstables`. As far as I know, when this change was proposed, there weren't any stalls it was supposed to fix, it was just supposed to reduce computational complexity. I've run the performance test again and the time it takes to replace 10 L1 sstables drops from ~20ms to ~6ms with the change (did any of the recent changes improve the complexity of replacing sstables? I'm aware that the problems with latencies have been fixed, but the test measures the total runtime and it's 10x less than what I've measured before). We can expect similar improvements for copying and adding new sstables into the set.


> In any case, it doesn't build any more as many things changed.

It looks like it's a problem with github again. I've updated the branch, but the PR doesn't show the new commits (probably because it's marked as merged - can we 'unmark' it?)

**Comment by raphaelsc** [comment]
> > > @avikivity can we try to merge it again? It's marked as merged but it has been dequeued
> > 
> > 
> > Now that the stalls are gone, I'd like to understand the value that versioned sstable set is really bringing us. Is it improving performance when updating the sstable set on compaction completion (which used to rebuild set from scratch)? Versioned sstable set adds lots of complex code that will be hard to maintain and we need a good justification for merging it. From what I remember, after versioned set, we'll still have a high cost when inserting a sstable in the interval map (inversely proportional to the level the sstable belongs to), and that could be fixed without the versioned set. If it does improve performance significantly when updating set, that's a very good reason already for merging this work.
> 
> The main aim for this patch was to stop rebuilding the sstable set after adding or replacing sstables in the set. It also allowed to avoid copying the set for compaction descriptors and for the mutation reader from `make_reader_excluding_sstables`. As far as I know, when this change was proposed, there weren't any stalls it was supposed to fix, it was just supposed to reduce computational complexity.

Actually stall was the primary concern. Rebuilding the set from scratch is bad but it happens in a background process, so the major consequence was stalling the reactor.

> I've run the performance test again and the time it takes to replace 10 L1 sstables drops from ~20ms to ~6ms with the change (did any of the recent changes improve the complexity of replacing sstables? I'm aware that the problems with latencies have been fixed, but the test measures the total runtime and it's 10x less than what I've measured before). We can expect similar improvements for copying and adding new sstables into the set.

That's good. It will be even faster after we deal with the bad case of inserting a sstable at low level.

> 
> > In any case, it doesn't build any more as many things changed.
> 
> It looks like it's a problem with github again. I've updated the branch, but the PR doesn't show the new commits (probably because it's marked as merged - can we 'unmark' it?)

AFAIK no. you'll probably have to open a new pull request.

**Comment by psarna** [comment]
> It looks like it's a problem with github again. I've updated the branch, but the PR doesn't show the new commits (probably because it's marked as merged - can we 'unmark' it?)

@wmitros nope, closed pull requests are broken. It's best to just create a new pull request and mention this one (Refs #xxxx) as its predecessor.
