### PR TITLE
tracing: Fix error on slow batches v2

### LINKED ISSUE #5843: "No query parameter set for a session requesting a slow_query_log record" error while tracing slow batch queries
*Installation details*
Scylla version (or git commit hash): 6c7aa1823826817b38268871a0633a818cd98495
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

`trace_keyspace_helper::make_slow_query_mutation_data()` assumes there is `query` parameter, but for batch there are `query[0], query[1]...`. See `trace_keyspace_helper::make_slow_query_mutation_data()`

### PR DESCRIPTION
**Pull request by jul-stas**
`trace_keyspace_helper::make_slow_query_mutation_data` expected a
"query" key in its parameters, which does not appear in case of
e.g. batches of prepared statements. This is example of failing
`record.parameters`:
```
...{"query[0]" : "INSERT INTO ks.tbl (pk, i) values (?, ?);"},
{"query[1]" : "INSERT INTO ks.tbl (pk, i) values (?, ?);"}...
```

In such case Scylla recorded no trace and said:
```
ERROR 2020-09-28 10:09:36,696 [shard 3] trace_keyspace_helper - No
"query" parameter set for a session requesting a slow_query_log record
```

Fix here is to leave query empty if not found. The users can still
retrieve the query contents from existing info in `system_traces.node_slow_log`.

Fixes #5843

### CODE REVIEW

File: tracing/trace_keyspace_helper.cc [hunk 1]
```diff
@@ -289,10 +289,10 @@ cql3::query_options trace_keyspace_helper::make_slow_query_mutation_data(const o
     const session_record& record = session_records.session_rec;
     auto millis_since_epoch = std::chrono::duration_cast<std::chrono::milliseconds>(record.started_at.time_since_epoch()).count();
 
+    sstring query_str;
     // query command is stored on a parameters map with a 'query' key
-    auto query_str_it = record.parameters.find("query");
-    if (query_str_it == record.parameters.end()) {
-        throw std::logic_error("No \"query\" parameter set for a session requesting a slow_query_log record");
+    if (auto query_str_it = record.parameters.find("query"); query_str_it != record.parameters.end()) {
+        query_str = query_str_it->second;
```
Comment (haaawk) [inline tracing/trace_keyspace_helper.cc:295]: maybe just sstring query_str = record.parameters["query"]; ?

**Review by haaawk — APPROVED** [review]
LGTM

File: tracing/trace_keyspace_helper.cc (hunk 1 above)
Comment (jul-stas) [reply tracing/trace_keyspace_helper.cc:295]: I didn't try this, but it's a `const map`..? And `operator[]` always creates the key..?

Comment (haaawk) [reply tracing/trace_keyspace_helper.cc:295]: If it's const then it won't work

Comment (vladzcloudius) [reply tracing/trace_keyspace_helper.cc:295]: This check makes sense for non-batch queries.
If it's not a batch query - then not having a `query` string is a bug.
If it's a batch query then we should probably see what Cassandra does in this case and do the same.

For instance I see that node_slow_log has a set<text> for tables names which is clearly defined with a batch in mind.

**Review by vladzcloudius — CHANGES_REQUESTED** [review]

File: tracing/trace_keyspace_helper.cc (hunk 1 above)
Comment (psarna) [reply tracing/trace_keyspace_helper.cc:295]: Even if not having a `query` string is a bug, tracing this entry still makes sense in my opinion. `std::logic_error("No \"query\" parameter set for a session requesting a slow_query_log record")` absolutely lacks context by itself, so it's much better to still trace the queryless request, and perhaps also log a warning which says that the `query` parameter was missing.

File: tracing/trace_keyspace_helper.cc [hunk 2]
```diff
@@ -313,7 +313,7 @@ cql3::query_options trace_keyspace_helper::make_slow_query_mutation_data(const o
         cql3::raw_value::make_value(uuid_type->decompose(session_records.session_id)),
         cql3::raw_value::make_value(timestamp_type->decompose(millis_since_epoch)),
         cql3::raw_value::make_value(timeuuid_type->decompose(start_time_id)),
-        cql3::raw_value::make_value(utf8_type->decompose(query_str_it->second)),
+        cql3::raw_value::make_value(utf8_type->decompose(std::move(query_str))),
```
Comment (psarna) [inline tracing/trace_keyspace_helper.cc:316]: and I agree with Vlad's comment from v1, that not storing any value (a.k.a. null created with `cql3::raw_value::make_null()`) would be better than an empty string in case we don't have a `query` string to copy.

**Comment by jul-stas** [comment]
Ping.

**Review by psarna — APPROVED** [review]

**Review by haaawk — APPROVED** [review]
LGTM

File: tracing/trace_keyspace_helper.cc [hunk 3]
```diff
@@ -290,9 +290,9 @@ cql3::query_options trace_keyspace_helper::make_slow_query_mutation_data(const o
     auto millis_since_epoch = std::chrono::duration_cast<std::chrono::milliseconds>(record.started_at.time_since_epoch()).count();
 
     // query command is stored on a parameters map with a 'query' key
-    auto query_str_it = record.parameters.find("query");
+    const auto query_str_it = record.parameters.find("query");
     if (query_str_it == record.parameters.end()) {
-        throw std::logic_error("No \"query\" parameter set for a session requesting a slow_query_log record");
+        tlogger.warn("No \"query\" parameter set for a session requesting a slow_query_log record");
```
Comment (psarna) [inline tracing/trace_keyspace_helper.cc:295]: Do I understand correctly that this warning will also be printed for correct batch statements? In that case it's redundant, so perhaps it's better to remove it altogether or degrade to debug/trace

File: tracing/trace_keyspace_helper.cc (hunk 1 above)
Comment (vladzcloudius) [reply tracing/trace_keyspace_helper.cc]: @psarna I guess you would agree that tracing a query without knowing what the query was is absolutely pointless. 

Note that the node_slow_log has a special column for a query string: "command".
The whole point of having this table (`node_slow_log`) is to be able to see which query has been slow by only looking at it and not at anything else.

When you think about the implementation for this GH issue you should imagine that there is no extra tracing data except for what's written in node_slow_log. That's how it is in Cassandra and that's how it should have been all alone.

I want to implement it properly at some point: https://github.com/scylladb/scylla/issues/2572

**Review by vladzcloudius — CHANGES_REQUESTED** [review]
There is no point saving an entry in the node_slow_log if you don't know what the query was.

**Comment by haaawk** [comment]
> There is no point saving an entry in the node_slow_log if you don't know what the query was.

I think it's better to have such entry and know there was a slow query than have no entry and think that there was no slow query when there was one. Even when we don't know the query itself. IMO Not logging it at all can create confusion while debugging a production cluster.

**Comment by vladzcloudius** [comment]
> > There is no point saving an entry in the node_slow_log if you don't know what the query was.
> 
> I think it's better to have such entry and know there was a slow query than have no entry and think that there was no slow query when there was one. Even when we don't know the query itself. IMO Not logging it at all can create confusion while debugging a production cluster.

@haaawk It's better same this entry and store the query string as it's intended to.

File: tracing/trace_keyspace_helper.cc (hunk 1 above)
Comment (psarna) [reply tracing/trace_keyspace_helper.cc]: I agree that tracing a query without knowing what it is is pointless, but it's not the case here - after this patch, we'll just sometimes trace a query which doesn't have a `query` entry in its parameters, which is not the same as not knowing what it is. For instance, with batches we know perfectly fine what the queries are, because this information can be extracted from other fields. I think that throwing this generic `std::logic_error("No \"query\" parameter set for a session requesting a slow_query_log record"` gives us very little context on what actually happened, while a trace entry without the `query` field provides every bit of information we need. Throwing this exception in this particular case is literally throwing away context which could help us pinpoint the issue, so I think that this patch is a clear improvement.

**Comment by jul-stas** [comment]
But does this watchdog ever catch bugs, really? I see that what it does is catching correct batches.
And even if so, is tracing slow queries the right place to catch malformed commands?
Even if it is, I can still catch a malformed command: by finding the rows with no `query` key and inspecting `query[N]`. I wouldn't be able to do that before.

File: tracing/trace_keyspace_helper.cc (hunk 1 above)
Comment (vladzcloudius) [reply tracing/trace_keyspace_helper.cc]: @psarna You have missed my point: this issue (and PR) is not about `system_traces.sessions` table which has (today) the query in the parameters.
This issue is about the `system_traces.node_slow_log` which can only have the query string in the `command` column and it is intended to be used stand alone.

The fact that we today have entries in `sessions` and `events` tables for each entry in `node_slow_log` is design bug and has to be fixed ASAP.

Because of that Node Slow Log is an almost-dead feature because it's intended to be always-on. But because of that design bug it can't be because it introduces a heavy overhead via `sessions` and `events` tables.

Once we implement #2572 it will become operational and there won't be any entries is `sessions` and `events`.

**Comment by vladzcloudius** [comment]
> But does this watchdog ever catch bugs, really? 

Yup - you are fixing the issue it have caught.

> I see that what it does is catching correct batches.
> And even if so, is tracing slow queries the right place to catch malformed commands?
> Even if it is, I can still catch a malformed command: by finding the rows with no `query` key and inspecting `query[N]`. I wouldn't be able to do that before.

The bug is not in the batch implementation of course - the bug is in the tracing. We need to be able to construct the query line in order to store it in the `node_slow_log` and for this type of requests we were not. Hence the error and this github issue that needs to be fixed.

The error message was completely at place.

File: tracing/trace_keyspace_helper.cc (hunk 1 above)
Comment (haaawk) [reply tracing/trace_keyspace_helper.cc]: You've got me confused @vladzcloudius. First, you said we shouldn't concatenate batch queries and put them into a node_slow_log because these queries can be obtained in a different way and now you say that the can't. If that's true and Node Slow Log is meant to be a standalone feature then the initial version of the PR was correct to use a concatenation of all batch elements as a query field.

Comment (vladzcloudius) [reply tracing/trace_keyspace_helper.cc]: Well, I'm a person, @haaawk . I make mistakes too.
The best way to move forward is to look what C* does.
Printing the whole batch query which may be VERY long doesn't sound like an obvious solution to me either.

I'd suggest to use some length limited string - similar to what we do for prepared statements values.

However, again, there is no need to invent a bicycle here - better follow C* on this.

Comment (haaawk) [reply tracing/trace_keyspace_helper.cc]: Limiting the size sounds like a good idea. @jul-stas please check what C* is doing and let us know. Thank you!

**Comment by vladzcloudius** [comment]
@psarna Please, consider reverting this commit. The fix in the patch in question is not acceptable as I mentioned here: https://github.com/scylladb/scylla/pull/7293#discussion_r496993207

**Comment by vladzcloudius** [comment]
@psarna Please, consider reverting this commit. The fix in the patch in question is not acceptable as I mentioned here: https://github.com/scylladb/scylla/pull/7293#discussion_r496993207

**Comment by psarna** [comment]
If a fix can be cooked within one day, I'd rather just apply a fix instead of reverting -- @jul-stas is it feasible?

I can't judge, because I'm quite lost at what is being fixed here. Right now, after this patch is merged, when a batched request which doesn't have a `"query"` parameter arrives, it will still be logged, but its details will be encoded in the `parameters` map. I understand that this is bad from the point of view of potential reactor stalls if we need to serialize a huge map (e.g. with 50k entries in it), but I don't follow why it's bad that the `command` column does not hold anything. It's a batch, so not really a single command, so what's the difference if the person who investigates a slow log needs to look at the parameters or the command? The algorithm would be "if `command` is null, it's probably a batch, so look at the `parameters` column for details".

So, can somebody explain to me what is getting fixed here after all? At first I was under the impression that the problem is that we don't log certain kinds of batches and that's why I enqueued this patch, but it looks like the problem is supposedly somewhere else and I don't understand it.

That said, there's a separate issue that serializing this map of `parameters` can be potentially problematic for batches, since I'm pretty sure that the serializing code does not yield. Perhaps we should only serialize a small prefix of it and mark somewhere else what was the original size of the params? But perhaps even 50k elements get serialized fast enough and it's a non issue, I guess we should verify that via some tests.

**Comment by psarna** [comment]
Ok, I see that now the issue **is** that printing the whole batch can get long. I get that, and we should address the issue of serializing the `parameters` map first - that's the current offender, it's a big map and Scylla can stall while serializing it. I guess we should truncate it in a smart way? In case of batches I suppose we should just ignore keys in the form of `query[N]` for N > something. Still, maybe as a first step, the person implementing this fix should run a test and see how big the stall is for a map of, say, 50k elements in a batch. Then we'll be able to judge how serious this issue is.

Then, after the problem with serializing a huge `parameters` map is fixed, we can go back to figuring out what to do with an empty `command` column in certain batch requests. Since for batches, the information in this column is completely redundant (due to being duplicated in `parameters`), we can just copy the first query param `query[0]`? `query[1]` and be done with it. Or just insert a (also quite redundant) `"batch"` string in the command, which will hint that the context can be found in `parameters`.

**Comment by haaawk** [comment]
I think it's still a good idea to do truncation and yield in a followup patch instead of revert and remerge. @jul-stas please cook up something today.

**Comment by avikivity** [comment]
Truncation is bad for a debug facility. Usually it will truncate exactly where the important infomation is.

So we should yield while serializing.

**Comment by jul-stas** [comment]
Below is how DSE logs a big slow batch. Untruncated, concatenated statements. No params.
IMHO not very helpful.

```
> DESC dse_perf.node_slow_log;

CREATE TABLE dse_perf.node_slow_log (
    node_ip inet,
    date timestamp,
    start_time timeuuid,
    commands list<text>,
    duration bigint,
    parameters map<text, text>,
    source_ip inet,
    table_names set<text>,
    tracing_session_id uuid,
    username text,
    PRIMARY KEY ((node_ip, date), start_time)
) WITH CLUSTERING ORDER BY (start_time DESC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 60
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 3600000
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';

> SELECT * FROM dse_perf.node_slow_log;

 127.0.0.1 | 2020-09-30 00:00:00.000000+0000 | 7131cc10-0309-11eb-962a-7178010e62c0 | ['\n    INSERT INTO ks.tbl2 (pk, i1, i2, i3, i4, i5, i6, i7, i8) values (?, ?, ?, ?, ?, ?, ?, ?, ?);', '\n    INSERT INTO ks.tbl2 (pk, i1, i2, i3, i4, i5, i6, i7, i8) values (?, ?, ?, ?, ?, ?, ?, ?, ?);', '\n    INSERT INTO ks.tbl2 (pk, i1, i2, i3, i4, i5, i6, i7, i8) values (?, ?, ?, ?, ?, ?, ?, ?, ?);', '\n    INSERT INTO ks.tbl2 (pk, i1, i2, i3, i4, i5, i6, i7, i8) values (?, ?, ?, ?, ?, ?, ?, ?, ?);', '\n    INSERT INTO ks.tbl2 (pk, i1, i2, i3, i4, i5, i6, i7, i8) values (?, ?, ?, ?, ?, ?, ?, ?, ?);', '\n    INSERT INTO ks.tbl2 (pk, i1, i2, i3, i4, i5, i6, i7, i8) values (?, ?, ?, ?, ?, ?, ?, ?, ?);', '\n    INSERT INTO ks.tbl2 (pk, i1, i2, i3, i4, i5, i6, i7, i8) values (?, ?, ?, ?, ?, ?, ?, ?, ?);', '\n    INSERT INTO ks.tbl2 (pk, i1, i2, i3, i4, i5, i6, i7, i8) values (?, ?, ?, ?, ?, ?, ?, ?, ?);', '\n    INSERT INTO ks.tbl2 (pk, i1, i2, i3, i4, i5, i6, i7, i8) values (?, ?, ?, ?, ?, ?, ?, ?, ?);', '\n    INSERT INTO ks.tbl2 (pk, i1, i2, i3, i4, i5, i6, i7, i8) values (?, ?, ?, ?, ?, ?, ?, ?, ?);'] |        1 |       null | 127.0.0.1 | {'ks.tbl2'} |               null | anonymous
```

**Comment by vladzcloudius** [comment]
> Truncation is bad for a debug facility. Usually it will truncate exactly where the important infomation is.
> 
> So we should yield while serializing.

@avikivity serializing is outside the scope of this patch - the code that serializes whatever needs to be serialized is there for years (with all its problems).
That being said I agree that there are a few potential stall sources in the tracing/cql_serializer code today that need to be addressed but that should be a separate GH issue.

@psarna The scope of this GH is a watchdog that got hit by the prepared batches tracing flow.
The watchdog catches the situation when there is no value set that would need to go into the `command` column of scylla_traces.node_slow_log table.

Following the call we had today it's been decided to put some meaningful string in the `command` column for batches: something like "Batch command". The actual queries are already stored in the `parameters` column which has the same content as the same column in the `system_traces.sessions` table.

So, all the info needed to debug was and is there, @avikivity.
The only issue that needs to be fixed here is the ensure the consistency of the `command` column content for all batches: whether it comes via BATCH or QUERY CQL opcode.

As of now for the former case we you hit the watchdog check in question and for the later we would have the whole batch string.

**Comment by vladzcloudius** [comment]
@avikivity This patch is not good as it is now.
Please, don't merge it.
