### PR TITLE
Materialized Views: drop materialized views before it's table

### LINKED ISSUE #5614: secondary_indexes_test: test_insert_data_after_recreating_ks_with_local_index: Failed writing schema file in snapshot
Seen in:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/373/testReport/secondary_indexes_test/TestLocalIndexes/test_insert_data_after_recreating_ks_with_local_index/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/373/testReport/secondary_indexes_test/TestSecondaryIndexes/test_insert_data_after_recreating_cf/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/373/testReport/secondary_indexes_test/TestSecondaryIndexes/test_insert_data_after_recreating_ks/

Introduced in 028525daebf30fff302352148e4a10b0a6addaee (database: add schema.cql file when creating a snapshot)

[node1.log](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/373/artifact/logs-release.2/1579504814133_secondary_indexes_test.TestSecondaryIndexes.test_insert_data_after_recreating_ks/node1.log)
```
ERROR 2020-01-20 07:13:15,502 [shard 1] table - Failed writing schema file in snapshot in /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-gbpzpt5s/test/node1/data/ks/col1_key_index-4e4249013b5411eabc83000000000001/snapshots/1579504395466-col1_key_index with exception std::_Nested_exception<no_such_column_family> (Can't find a column family with UUID 4cfd45e0-3b54-11ea-8271-000000000000): std::out_of_range (_Map_base::at)
```

### PR DESCRIPTION
**Pull request by eliransin**
When dropping a table, the table and its views are dropped
in parallel, this is not a problem as for itself but we
have mechanism to snapshot a deleted table before the
actual delete. When a secondary index is removed, in the
snapshot process it looks for it's schema for creating the
schema part of the snapshot but if the main table is already
gone it will not find it.
This commit serializes views and main table removals and
removes the views prior to the tables.

See discussion on https://github.com/scylladb/scylla/pull/5713

Tests:
Unit tests (dev)
dtest - A test that failed on "can't find schema" error

Fixes #5614

### CODE REVIEW

File: db/schema_tables.cc [hunk 1]
```diff
@@ -1073,7 +1073,14 @@ static void merge_tables_and_views(distributed<service::storage_proxy>& proxy,
 
     proxy.local().get_db().invoke_on_all([&] (database& db) {
         return seastar::async([&] {
-            parallel_for_each(boost::range::join(tables_diff.dropped, views_diff.dropped), [&] (schema_diff::dropped_schema& dt) {
+            // First drop views and *only then* the tables, if interleaved it can lead
+            // to a mv not finding it's schema when snapshoting since the main table
```
Comment (psarna) [inline db/schema_tables.cc]: nitpick: s/it's/its

**Comment by psarna** [comment]
Thanks, looks good, I'll verify locally and queue.
