### PR TITLE
database: Add error message with mutation info on commit log apply failure

### LINKED ISSUE #9408: Database::apply commitlog write failures should add more verbose info on mutation that failed
While it is rare, some customer issues have shown that we can run into cases where commit log apply (writing mutations to it) fails badly. In the known cases, due to oversized mutations. While these should have been caught earlier in the call chain really, it would probably help both end users and us (trying to figure out how they got so big and how they got so far) iff we actually added some info on which mutation actually was in play (ks, cf, mutation content). 

Note that this needs to be done in database, since at lower levels, we don't really know any of this.

### PR DESCRIPTION
**Pull request by elcallio**
Fixes #9408
    
While it is rare, some customer issues have shown that we can run into cases where commit log apply (writing mutations to it) fails badly. In the known cases, due to oversized mutations. While these should have been caught earlier in the call chain really, it would probably help both end users and us (trying to figure out how they got so big and how they got so far) iff we added info to the errors thrown (and printed), such as ks, cf, and mutation content.

Somewhat controversial, this makes the apply with CL decision path coroutinized, mainly to be able to do the error handling    for the more informative wrapper exception easier/less ugly. Could perhaps do with futurize_invoke + then_wrapper also. But future is coroutines...
    
This is as stated somewhat problematic, it adds an allocation to perf_simple_query::write path (because of crap clang cr frame folding?). However, tasks/op remain constant and actual tps (though unstable) remain more or less the same (on my crappy measurements).
    
Counter path is unaffected, as coroutine frame alloc replaces with(...)

dtest for the wrapped exception on separate pr.

### CODE REVIEW

File: database.cc [hunk 1]
```diff
@@ -1805,39 +1805,19 @@ future<mutation> database::apply_counter_update(schema_ptr s, const frozen_mutat
...
     } catch (mutation_reordered_with_truncate_exception&) {
         // This mutation raced with a truncate, so we can just drop it.
         dblog.debug("replay_position reordering detected");
-        return make_ready_future<>();
-    }
-}
-
-future<> database::apply_with_commitlog(column_family& cf, const mutation& m, db::timeout_clock::time_point timeout) {
-    if (cf.commitlog() != nullptr && cf.durable_writes()) {
-        return do_with(freeze(m), [this, &m, &cf, timeout] (frozen_mutation& fm) {
```
Comment (denesb) [inline database.cc:1821]: A method with `do_with()` is a natural convert to coroutines without perf regression. Since the non-alloc case here is basically only used for tests AFAIK I don't think converting this method is a problem.

File: database.cc [hunk 2]
```diff
@@ -1847,25 +1827,34 @@ future<> database::do_apply(schema_ptr s, const frozen_mutation& m, tracing::tra
...
-                [lock = std::move(lock), op = std::move(op)] { });
-    });
+
+    row_locker::lock_holder lock;
+    if (!cf.views().empty()) {
+        lock = co_await cf.push_view_replica_updates(s, m, timeout, std::move(tr_state), get_reader_concurrency_semaphore());
+    }
+
+    // purposefully manually "inlined" apply_with_commitlog call here to reduce # coroutine
+    // frames.
```
Comment (denesb) [inline database.cc:1858]: Does calling `apply_with_commitlog()` here add another allocation?

Comment (elcallio) [reply database.cc]: Yes. Very carefully tweaked to minimise coroutine frame allocations.

**Review by denesb — APPROVED** [review]
LGTM
I think the additional allocation is a price we can pay for moving forward.
I'll merge once next is unclogged.

**Comment by denesb** [comment]
@elcallio `database.cc` doesn't compile, please rebase.

**Comment by elcallio** [comment]
Bitrot is real. Rebased and updated.
