### PR TITLE
commitlog: Fix race and edge condition in delete_segments

### LINKED ISSUE #8363: Commitlog can get stuck after reaching disk size limit, causing writes to time out
## Problem

Scylla commit used to reproduce: c1daf2bb24a43d398a5f209e052102afea6eb7de

Recently, the commitlog disk limit became a hard limit (4082f57edc3e7764e11e9e858a0a8059981c6309). After that change, a race became possible which would prevent the commitlog from accepting any further writes. The shard on which the commitlog gets stuck becomes unresponsive to writes.

## Description of the race

The race is as follows:

1. The commitlog goes over disk space limit (`totals.totals.total_size_on_disk > max_disk_size`). Both "recycled" and "reserve" pools are empty.
1. Reserve replenisher (an asynchronous process in the commitlog) wakes up because the reserve segments pool is empty. It calls `allocate_segment`, and decides to wait until there are some `_recycled_segments`:

    https://github.com/scylladb/scylla/blob/ef06a939c4f51e6f01f0de44f5572f3aeab089c5/db/commitlog/commitlog.cc#L1511-L1517

1. A different commitlog background process (`on_timer`) is run, it sees that disk usage is over limit and decides to "flush" some segments so that the disk usage goes below half of the disk limit (`disk_usage_threshold`):

	https://github.com/scylladb/scylla/blob/ef06a939c4f51e6f01f0de44f5572f3aeab089c5/db/commitlog/commitlog.cc#L1832-L1841

	This causes some memtables to be saved as sstables (`flush_segments`), in turn this causes those commitlog segments whose all mutations are backed by sstables to be moved from `_segments` to `_segments_to_delete`. Those segments are then handled by `delete_segments` (called indirectly by `do_pending_deletes`), and each of them can either be deleted from disk, or moved to `_recycled_segments`:

	https://github.com/scylladb/scylla/blob/ef06a939c4f51e6f01f0de44f5572f3aeab089c5/db/commitlog/commitlog.cc#L1747-L1778

	Now here is a problem: even if there are multiple segments to delete and we don't need to delete all of them to go below disk size limit, it might still happen that __all__ segments are deleted by that function. It's because segments are handled in parallel. For each segment, we:

	1. Decide if we should delete the file, or rename and move to reserve - the decision is based on the `totals.total_size_on_disk` metric,
	2. Proceed with deletion or rename/movement,
	3. Update the `totals.total_size_on_disk` metric.
	
	Because there is a defer point during 2), it might happen that we do the step 1) for all segments in the list before we do step 3) for any of the segments. Because of that, it is probable that commitlog will decide to delete all segments from the list. As a result, `_recycled_segments` is still empty.

	The fact that segments are deleted can clearly be seen in metrics:

	8301-commitlog-used-bytes-on-disk

1. Now, commitlog becomes stuck:

	- New writes will get stuck because they will be waiting for segments to appear in the reserve,
	- Reserve replenisher is stuck because it waits for recycled segments to appear,
	- No more segments will be freed - the last `do_pending_deletes` reduced disk usage below `disk_usage_threshold`, so no more flushes will be issued and no segments will be recycled.

	This will cause all attempts to write anything to the commitlog to time out.

	Curiously, `nodetool flush` can cause the node to become unstuck. If there are some unflushed memtables, then there are also some commitlog segments which will be moved to the recycled pool after memtables are flushed.

## How to reproduce

1. Start a single-node cluster with a single shard and a small commitlog disk limit (I used 257MB - for some reason it's important that the limit isn't a multiple of segment size),
1. Start writing with cassandra-stress or scylla-bench,
1. Wait some time until the commitlog fills up, commitlog triggers memtable flush and the race described here reproduces,
1. Observe that suddenly all writes from c-s or s-b start to time out.

----

/cc: @elcallio

### LINKED ISSUE #8376: handle commitlog recycle errors
When recycling a segment in commitlog, we do not really handle a potential error very well. While any exception is caught, and we do instead delete the segment file, to avoid leaking disk data, we could end up starving any waiters for recycled segments. 

We need to signal any waiters that things went wrong, and they should probably revert to try allocating new segments instead.

### PR DESCRIPTION
**Pull request by elcallio**
Fixes #8363
Fixes #8376

Delete segements has two issues when running with size-limited
commit log and strict adherence to said limit.

1.) It uses parallel processing, with deferral. This means that
    the disk usage variables it looks at might not be fully valid
    - i.e. we might have already issued a file delete that will
    reduce disk footprint such that a segment could instead be
    recycled, but since vars are (and should) only updated
    _post_ delete, we don't know.
2.) It does not take into account edge conditions, when we only
    delete a single segment, and this segment is the border segment
    - i.e. the one pushing us over the limit, yet allocation is
    desperately waiting for recycling. In this case we should
    allow it to live on, and assume that next delete will reduce
    footprint. Note: to ensure exact size limit, make sure
    total size is a multiple of segment size.

if we had an error in recycling (disk rename?), and no elements
are available, we could have waiters hoping they will get segements.
abort the queue (not permanent, but wakes up waiters), and let them
retry. Since we did deletions instead, disk footprint should allow
for new allocs at least. Or more likely, everything is broken, but
we will at least make more noise.

### CODE REVIEW

File: db/commitlog/commitlog.cc [hunk 1]
```diff
@@ -1741,41 +1741,64 @@ future<> db::commitlog::segment_manager::delete_file(const sstring& filename) {
...
+                if (recycle) {
+                    descriptor d(next_id(), "Recycled-" + cfg.fname_prefix);
+                    auto dst = this->filename(d);
+
+                    clogger.debug("Recycling segment file {}", filename);
+                    // must rename the file since we must ensure the
+                    // data is not replayed. Changing the name will
+                    // cause header ID to be invalid in the file -> ignored
+                    try {
+                        co_await rename_file(filename, dst);
```
Comment (piodul) [inline db/commitlog/commitlog.cc:1788]: Not sure how probable this is, but what if renaming of _every_ segment from `files` fails? No segments will be sent to recycling and we will get stuck just like before?

Comment (elcallio) [reply db/commitlog/commitlog.cc:1788]: It is a problem. The allocate waiter should wait for either of delete/recycle. But I could not find a `wait-for-either` primitive any longer, so not part of this.

Comment (piodul) [reply db/commitlog/commitlog.cc:1788]: I'm OK with fixing it in another PR, but I think we should do it soon. Please create an issue/send a followup so that we don't lose track of the problem.

**Review by piodul — APPROVED** [review]

File: db/commitlog/commitlog.cc (hunk 1 above)
Comment (elcallio) [reply db/commitlog/commitlog.cc:1793]: I added both a second issue, and a fix patch to this PR. Two for one. Please re-review.

File: db/commitlog/commitlog.cc [hunk 2]
```diff
@@ -1799,6 +1805,16 @@ future<> db::commitlog::segment_manager::delete_segments(std::vector<sstring> fi
...
     }
+
+    // #8376 - if we had an error in recycling (disk rename?), and no elements
+    // are available, we could have waiters hoping they will get segements.
+    // abort the queue (not permanent, but wakes up waiters), and let them
+    // retry. Since we did deletions instead, disk footprint should allow
+    // for new allocs at least. Or more likely, everything is broken, but
+    // we will at least make more noise.
+    if (recycle_error && _recycled_segments.empty()) {
+        _recycled_segments.abort(recycle_error);
```
Comment (piodul) [inline db/commitlog/commitlog.cc:1816]: I'm afraid that [`seastar::queue<T>::abort()`](https://github.com/scylladb/seastar/blob/72e3baed9c3657d49d9f1b82045831e72b3dc2a4/include/seastar/core/queue.hh#L119) doesn't work in the way you described. It not only sends the error to the current waiters, but prevents further read/write operations on that queue. Notice the comment above the definition of abort:

```c++
/// Destroy any items in the queue, and pass the provided exception to any
/// waiting readers or writers - or to any later read or write attempts.
```

Looking at the code, this seems to be enforced in some of methods of the queue that the commitlog uses, e.g. `not_empty` and `consume`.

**Review by piodul — CHANGES_REQUESTED** [review]

File: db/commitlog/commitlog.cc (hunk 2 above)
Comment (elcallio) [reply db/commitlog/commitlog.cc:1816]: Right, sorry. Forgot the reset of queue. Updated.

File: db/commitlog/commitlog.cc [hunk 3]
```diff
@@ -1747,6 +1750,8 @@ future<> db::commitlog::segment_manager::delete_segments(std::vector<sstring> fi
 
     clogger.debug("Delete segments {}", files);
 
+    std::exception_ptr recycle_error;;
```
[the remark this answers is not in the document]
Comment (elcallio) [reply db/commitlog/commitlog.cc]: fixed.

File: db/commitlog/commitlog.cc [hunk 4]
```diff
@@ -1513,6 +1513,9 @@ future<db::commitlog::segment_manager::sseg_ptr> db::commitlog::segment_manager:
         auto f = cfg.reuse_segments ? _recycled_segments.not_empty() :  _disk_deletions.get_shared_future();
         return f.then([this] {
             return allocate_segment();
+        }).handle_exception([this](auto ep) {
+            clogger.warn("Exception while waiting for segments {}. Will retry allocation...", ep);
```
[the remark this answers is not in the document]
Comment (elcallio) [reply db/commitlog/commitlog.cc:1515]: Very good point. Updated.

**Review by piodul — APPROVED** [review]
LGTM

File: db/commitlog/commitlog.cc [hunk 5]
```diff
@@ -1741,41 +1741,64 @@ future<> db::commitlog::segment_manager::delete_file(const sstring& filename) {
 }
```
Comment (avikivity) [inline db/commitlog/commitlog.cc:1744]: Please add a description of the fix to the changelog, so I don't have to reverse-engineer it.

File: db/commitlog/commitlog.cc [hunk 6]
```diff
@@ -1741,41 +1741,64 @@ future<> db::commitlog::segment_manager::delete_file(const sstring& filename) {
...
-            return delete_file(filename);
-        }).handle_exception([&filename](auto ep) {
-            clogger.error("Could not delete segment {}: {}", filename, ep);
-        });
-    }).finally([files = std::move(files)] {});
+            co_await delete_file(filename);
+        } catch (...) {
+            clogger.error("Could not delete segment {}: {}", filename, std::current_exception());
+        }
+    }
```
Comment (avikivity) [inline db/commitlog/commitlog.cc:1806]: Is this mixing coroutinization and fixization? That makes it hard to review. Please split.

File: db/commitlog/commitlog.cc (hunk 5 above)
Comment (elcallio) [reply db/commitlog/commitlog.cc:1744]: Ok.

File: db/commitlog/commitlog.cc (hunk 6 above)
Comment (elcallio) [reply db/commitlog/commitlog.cc:1806]: Sure. Done.

**Comment by kbr-** [comment]
No regression test?
According to description in #8363 it reproduces quickly. If still too slow for a unit test, could be made into a dtest.

**Comment by slivne** [comment]
@avikivity ping ...

**Comment by avikivity** [comment]
@slivne @kbr- left a comment

File: db/commitlog/commitlog.cc [hunk 7]
```diff
@@ -1744,15 +1744,14 @@ future<> db::commitlog::segment_manager::delete_segments(std::vector<sstring> fi
...
-        auto f = make_ready_future();
+    co_await parallel_for_each(i, e, [this](auto& filename) -> future<> {
         auto exts = cfg.extensions;
         if (exts && !exts->commitlog_file_extensions().empty()) {
-            f = parallel_for_each(exts->commitlog_file_extensions(), [&](auto& ext) {
-                return ext->before_delete(filename);
-            });
+            for (auto& ext : exts->commitlog_file_extensions()) {
+                co_await ext->before_delete(filename);
+            }
```
Comment (avikivity) [inline db/commitlog/commitlog.cc]: This is not a pure translation, as the callbacks are now sequential. Though it's likely more correct (or maybe less wrong).

Comment (elcallio) [reply db/commitlog/commitlog.cc]: The `before_delete` is only defined as exactly that, before delete (no ordering guarantee), but the above does not break it. And in fact should make any errors easier to pinpoint at least.

File: db/commitlog/commitlog.cc [hunk 8]
```diff
@@ -1741,41 +1741,64 @@ future<> db::commitlog::segment_manager::delete_file(const sstring& filename) {
...
+
+                // if total size is not a multiple of segment size, we need
+                // to check if we are the overlap segment, and noone else
+                // can be recycled. If so, let this one live so allocation
+                // can proceed. We assume/hope a future delete will kill
+                // files down to under the threshold, but we should expect
+                // to stomp around nearest multiple of segment size, not 
+                // the actual limit.
+                if (!recycle && _recycled_segments.empty() && files.empty()) {
+                    auto size = co_await seastar::file_size(filename);
```
Comment (avikivity) [inline db/commitlog/commitlog.cc:1779]: Do we not track the size of a segment?

**Comment by elcallio** [comment]
> 
> 
> No regression test?
> According to description in #8363 it reproduces quickly. If still too slow for a unit test, could be made into a dtest.

Problem is more reproducing the timing of releasing the appropriately small number of segments at the wrong time. Not sure it is easily reproducible as a unit test. But I guess I can try.

File: db/commitlog/commitlog.cc (hunk 1 above)
Comment (avikivity) [reply db/commitlog/commitlog.cc:1792]: Usually we wrap file operations with commit_error_handler which shuts down operations. Why is this not done here?

@piodul if things like renaming files stop working, the node is cooked.

File: db/commitlog/commitlog.cc [hunk 9]
```diff
@@ -1511,7 +1511,9 @@ future<db::commitlog::segment_manager::sseg_ptr> db::commitlog::segment_manager:
     if (!cfg.allow_going_over_size_limit && max_disk_size != 0 && totals.total_size_on_disk >= max_disk_size) {
         clogger.debug("Disk usage ({} MB) exceeds maximum ({} MB) - allocation will wait...", totals.total_size_on_disk/(1024*1024), max_disk_size/(1024*1024));
         auto f = cfg.reuse_segments ? _recycled_segments.not_empty() :  _disk_deletions.get_shared_future();
-        return f.then([this] {
+        return f.handle_exception([this](auto ep) {
+            clogger.warn("Exception while waiting for segments {}. Will retry allocation...", ep);
+        }).then([this] {
             return allocate_segment();
         });
```
Comment (avikivity) [inline db/commitlog/commitlog.cc:1518]: If the same error happens, won't we spin in this function?

**Comment by kbr-** [comment]
The test wouldn't necessarily reproduce the problem every time, but when it would (and it would on some runs), it would catch it. Probably most problematic thing is checking that there is a deadlock without false positives; the test could e.g. wait for operations to end with a timeout, and with a timeout is reached, report a deadlock. If the timeout is large enough then no false-positives should occur. It may be very large - it doesn't matter if it causes the test to run longer in the deadlock scenario, since this would only happen when the problem is catched.

File: db/commitlog/commitlog.cc (hunk 9 above)
Comment (elcallio) [reply db/commitlog/commitlog.cc:1518]: Assuming a segment eventually is made available, we will resolve at that time. If disk errors just keep happening, we will indeed deadlock again, just like before.
I guess we could add a retry-counter or something. Not sure about adding it now though. Technically, we should try to adhere to any timeouts specified on higher levels, but our waiting with timeout tends to abandon the timed out future, which is not great either...

File: db/commitlog/commitlog.cc (hunk 8 above)
Comment (elcallio) [reply db/commitlog/commitlog.cc:1779]: Only when it is active. When we get here, the segment object is deleted, and only the file name is kept in the lists.

File: db/commitlog/commitlog.cc (hunk 1 above)
Comment (elcallio) [reply db/commitlog/commitlog.cc:1792]: The code here was never error handled before. Probably an oversight. Though I guess we could add it now.

**Comment by elcallio** [comment]
Rebased and added unit test.

File: db/commitlog/commitlog.cc (hunk 1 above)
Comment (elcallio) [reply db/commitlog/commitlog.cc:1792]: Speak if you want me to add wrapping in this patch set. But it seems slightly unrelated.

**Comment by elcallio** [comment]
Ping? If reviewers want further changes, please be explicit about it.

**Comment by kbr-** [comment]
The test LGTM, didn't review the rest since I don't understand commitlog code yet.
Did you check that the test manages to reproduce the issue (in some runs at least) if you run it without the fixing patches?

**Comment by elcallio** [comment]
On my machine, it repros every time, debug and release. And works every time with the fix.

**Comment by kbr-** [comment]
Nice. I don't understand then why you said in the commit msg that it's not a very good test. To me it seems that it serves its purpose perfectly. If it catches the bug on your machine 100% of the time, then we can probably be confident that the Jenkins machines or some other developers' machines will also catch it at least some of the time.

**Comment by elcallio** [comment]
It is not a very good test because it relies on timeout and assuming "if I do it 10 times without fail it is ok". Could maybe be fixed to do more assumption-eager detection of success, _or_ add more whiteboxing. But for now it does the trick.

**Comment by kbr-** [comment]
> it relies on timeout 

I don't see why that's a problem. This is the only way to check liveness properties AFAIK (except for static analysis).

> and assuming "if I do it 10 times without fail it is ok"

If the purpose of the test was to prove that the code is correct then yes, that's what we would assume here. But the purpose of the test is not to prove correctness but to catch bugs (as Dijkstra said: "Program testing can be used to show the presence of bugs, but never to show their absence"); and that the test does perfectly. So if the test succeeds we don't say "there is no bug", we only can say "we did not catch a bug" (and that is true probably for 99% of the tests we have).

File: db/commitlog/commitlog.cc (hunk 1 above)
Comment (piodul) [reply db/commitlog/commitlog.cc:1792]: I think wrapping the rename operation in commit_error_handler falls under "handle commitlog recycle errors", and this PR is already marked as a fix for that issue. Therefore I think it is in the current scope of this PR.

Comment (elcallio) [reply db/commitlog/commitlog.cc:1792]: Actually, I just realize that both rename_file and delete_file both use the error handler wrapping. So it is already handled.

Comment (piodul) [reply db/commitlog/commitlog.cc:1792]: Oh, I see - rename_file is a method of the segment_manager, which is named in the same way as the seastar function.

**Review by piodul — APPROVED** [review]
LGTM
