### PR TITLE
flat_mutation_reader: downgrade_to_v1 - reset state of rt_assembler

### LINKED ISSUE #9022: flat_mutation_reader: downgrade_to_v1 doesn't reset the range tombstone assembler state
*Installation details*
Scylla version (or git commit hash): 1ff1c3735b2694d44b7f6641db1ef6e8e9d80927 (master)

`downgrade_to_v1` buffers encountered `range_tombstone_change`s, so that they are paired-up. If however the remaining input buffer in the partition is cleared (either by `next_partition` or `fast_forward_to`), after the output buffer has been filled up, this may result in discrepancy in what the reader knows and what the range tombstone assembler knows about active range tombstones.

This may result in an exception thrown from the assembler:
```cpp
    void on_end_of_stream() {
        if (has_active_tombstone()) {
            throw std::logic_error(format("Stream ends with an active range tombstone: {}", *_prev_rt));
        }
    }
```

The following test triggers the error:
```cpp
    const size_t row_count = 100; // Enough to trigger is_buffer_full.

    std::vector<mutation> mutations {{s.schema(), pkey}};
    mutation &m = mutations.front();

    s.delete_range(m, s.make_ckey_range(0, row_count));
    for (size_t i = 0; i < row_count; ++i) {
        s.add_row(m, s.make_ckey(i), "v");
    }

    auto ms = populate(s.schema(), mutations, gc_clock::now());
    auto pr = dht::partition_range::make_singular(pkey);

    assert_that(downgrade_to_v1(ms.make_reader_v2(s.schema(), semaphore.make_permit())))
            .produces_partition_start(pkey) // Read something.
            .next_partition()               // Next partition clears buffer.
            .produces_end_of_stream();      // Expect no active range tombstone change at this point.
```

### PR DESCRIPTION
**Pull request by enedil**
The downgrade_to_v1 didn't reset the state of range tombstone assembler
in case of the calls to next_partition or fast_forward_to, which caused
a situation where the closing range tombstone change is cleared from the
buffer before being emitted, without notifying the assembler. This patch
fixes the behaviour in fast_forward_to as well.

Fixes #9022

### CODE REVIEW

File: flat_mutation_reader.cc [hunk 1]
```diff
@@ -1344,6 +1345,8 @@ flat_mutation_reader downgrade_to_v1(flat_mutation_reader_v2 r) {
         }
         virtual future<> next_partition() override {
             clear_buffer_to_next_partition();
+            // The client didn't receive the paired-up range tombstone change and isn't interested.
```
Comment (kbr-) [inline flat_mutation_reader.cc:1348]: Someone coming to this code without any knowledge about what problem was solved will have trouble understanding what you mean here.

The comment lacks context: range tombstone change paired-up to what?
Also, the client does not receive range tombstone _changes_, they receive range tombstones (in v1 format). It's best to be accurate with terminology.
Also, there may have been no range tombstone change at all so there's no pairing up to be done.
Let's say it's understood why the client isn't interested the range tombstone - but why do we need to reset the assembler in this case? It's not obvious.

It would be best to explain what the problem is and when it happens. It happens conditionally: *If* we have an active range tombstone - which means we "started" a range tombstone but didn't finish it yet, and the client calls next_partition at this point, *then* it means we don't need to push the range tombstone so we can discard any information about an active range. And we need to explicitly discard it because the assembler requires there to not be any active range tombstone when it finishes.

File: test/lib/mutation_source_test.cc [hunk 2]
```diff
@@ -1419,6 +1419,28 @@ void test_slicing_with_overlapping_range_tombstones(tests::reader_concurrency_se
     }
 }
 
+void test_downgrade_to_v1_clear_buffer(tests::reader_concurrency_semaphore_wrapper& semaphore, populate_fn_ex populate) {
+    simple_schema s;
+    auto pkey = s.make_pkey();
+    const size_t row_count = 100; // Enough to trigger is_buffer_full.
```
Comment (haaawk) [inline test/lib/mutation_source_test.cc:1425]: Could we calculate this based on buffer size so that changing the buffer size in the future wouldn't break this test?

File: flat_mutation_reader.cc (hunk 1 above)
Comment (haaawk) [reply flat_mutation_reader.cc:1348]: I would also change the comment a bit as this is not definitive that there is any range tombstone change at all so 'may have not received' might be more appropriate.

File: flat_mutation_reader.cc [hunk 3]
```diff
@@ -1352,11 +1355,17 @@ flat_mutation_reader downgrade_to_v1(flat_mutation_reader_v2 r) {
...
         virtual future<> fast_forward_to(const dht::partition_range& pr, db::timeout_clock::time_point timeout) override {
             clear_buffer();
+            // The client didn't receive the paired-up range tombstone change and isn't interested.
+            _rt_assembler.reset();
             _end_of_stream = false;
             return _reader.fast_forward_to(pr, timeout);
         }
         virtual future<> fast_forward_to(position_range pr, db::timeout_clock::time_point timeout) override {
             clear_buffer();
+            if (_rt_assembler.needs_flush()) {
```
Comment (kbr-) [inline flat_mutation_reader.cc:1365]: Judging from the content of the error you're throwing, what you really want to check it is `has_active_tombstone()`, not `needs_flush()`. (the error mentions active range tombstones).

But you're calling `needs_flush()` here because you know the implementation of `needs_flush()`, i.e. you know that `needs_flush() == has_active_tombstone()`.

However, you should not use knowledge about internal implementation of an abstraction when using the abstraction. You should rely only on the interface .

I think it would be better to expose the notion of "active tombstone" to the user of assembler. In other words, make `range_tombstone_assembler::has_active_tombstone()` public and use it here.

OR keep using `needs_flush()`, but modify the content of the message below.

---

It would be also nice to explain here in a comment why is it bad when the client calls `fast_forward_to` in these circumstances?
I'm guessing that this means that the client didn't consume the range till the end before fast_forwarding to another range which is perhaps problematic. Although I'm not sure whether it's really wrong. Does `fast_forward_to` documentation specify that this is not allowed?

**Review by haaawk — APPROVED** [review]
LGTM - I left few comments

File: test/lib/mutation_source_test.cc (hunk 2 above)
Comment (enedil) [reply test/lib/mutation_source_test.cc:1425]: It would probably be nice, but this kind of tests requires to prepare all the mutations, in order to construct the reader. I could not use `run_mutation_reader_tests` and prepare a completely separate test, or I could increase the row_count by some amount (perhaps to the default value). The first solution also requires modifying the interface of flat_mutation_reader (and flat_mutation_reader_v2), since currently the variable controlling the maximum size of the buffer is marked private.

File: flat_mutation_reader.cc (hunk 3 above)
Comment (enedil) [reply flat_mutation_reader.cc:1365]: In documentation it is underspecified:
```
// For any range, all range tombstones relevant for that range which are
// present in the original stream will be emitted. Range tombstones
// emitted before forwarding which overlap with the new range are not
// necessarily re-emitted.
```

If however I don't take this assumption, I don't think it's ever possible to implement `fast_forward_to` for the downgrade_to_v1 correctly, since there are two cases, depending on whether the range tombstones emitted before forwarding which overlap with the new range have been re-emitted.

If there is the re-emission, we need to make sure that the assembler has a reset state. Otherwise it shouldn't.

File: flat_mutation_reader.cc (hunk 1 above)
Comment (enedil) [reply flat_mutation_reader.cc]: I elaborated in the comments.

File: test/lib/mutation_source_test.cc (hunk 2 above)
Comment (denesb) [reply test/lib/mutation_source_test.cc:1425]: Aren't you preparing the mutations yourself below?

Comment (enedil) [reply test/lib/mutation_source_test.cc:1425]: @denesb I am, however the reader is created by a function, based on the mutations I made:
```cpp
std::vector<mutation> mutations {{s.schema(), pkey}};
// ...
auto ms = populate(s.schema(), mutations, gc_clock::now());
assert_that(downgrade_to_v1(ms.make_reader_v2(s.schema(), semaphore.make_permit())))
// ...
```
I'm not sure what is the best solution here.

Comment (denesb) [reply test/lib/mutation_source_test.cc:1425]: You don't need to control the creation of the reader to pull this off. You can create your data such that it has more rows that what can fit into the default max buffer size.

Comment (enedil) [reply test/lib/mutation_source_test.cc]: Done

File: flat_mutation_reader.cc (hunk 3 above)
Comment (kbr-) [reply flat_mutation_reader.cc]: cc @tgrabiec @denesb 

Is it legal for the user of a reader to call `fast_forward_to(pr2)` before fully consuming an earlier fast-forwarded-to range?

**Comment by denesb** [comment]
On 7/14/2021 11:46 AM, Kamil Braun wrote:
>
> ***@***.**** commented on this pull request.
>
> ------------------------------------------------------------------------
>
> In flat_mutation_reader.cc 
> <https://github.com/scylladb/scylla/pull/9023#discussion_r669416096>:
>
> >              _end_of_stream = false;
>               return _reader.fast_forward_to(pr, timeout);
>           }
>           virtual future<> fast_forward_to(position_range pr, db::timeout_clock::time_point timeout) override {
>               clear_buffer();
> +            if (_rt_assembler.needs_flush()) {
>
> cc @tgrabiec <https://github.com/tgrabiec> @denesb 
> <https://github.com/denesb>
>
> Is it legal for the user of a reader to call |fast_forward_to(pr2)| 
> before fully consuming an earlier fast-forwarded-to range?
>

Github doesn't allow me to reply to the comment for some reason, so I'll 
answer here. Yes, you can fast-forward at any point, just like you can 
call next_partition() at any point. I don't think anybody is doing that 
but it is not forbidden.

File: test/lib/mutation_source_test.cc [hunk 4]
```diff
@@ -1419,6 +1419,29 @@ void test_slicing_with_overlapping_range_tombstones(tests::reader_concurrency_se
     }
 }
 
+void test_downgrade_to_v1_clear_buffer(tests::reader_concurrency_semaphore_wrapper& semaphore, populate_fn_ex populate) {
+    simple_schema s;
+    auto pkey = s.make_pkey();
+
+    // Enough to trigger is_buffer_full. This is the default max buffer size in bytes.
+    const size_t row_count = 8 * 1024;
```
[the remark this answers is not in the document]
Comment (haaawk) [reply test/lib/mutation_source_test.cc:1427]: Yes. That's more what I thought of.

[the remark this answers is not in the document]
Comment (enedil) [reply test/lib/mutation_source_test.cc]: Now there is a method `default_max_buffer_size_in_bytes()`.

File: flat_mutation_reader.cc (hunk 3 above)
Comment (kbr-) [reply flat_mutation_reader.cc]: @tgrabiec @denesb there's one matter which troubles me.
Suppose we have two ranges inside a partition `pr1` and `pr2`, and `start(pr2) > end(pr1)`.
Suppose we have a range tombstone `(x, y)` where `start(pr1) < x < end(pr1)` and `start(pr2) < y < end(pr2)`.
We have a v2 reader.

The v2 flat_mutation_reader documentation states:
```
///
///    4) The sub-stream will not end with a non-neutral active clustered tombstone. All range tombstones are closed.
```
(in the "Intra-partition fast-forwarding mode" section)

Which basically means that the reader will return a `range_tombstone_change` before `end_of_stream` when we read the `pr1` range, closing the `(x, y)` range tombstone.

However, I didn't find anything in the documentation that would state whether it will return another `range_tombstone_change` at the beginning of `pr2` which will re-open the `(x, y)` range tombstone.

I think such a guarantee would be necessary for the users to work correctly, in particular for `downgrade_to_v1`.

Comment (denesb) [reply flat_mutation_reader.cc]: I think this guarantee already exists, at the beginning of reading a range (even if arrived-to via fast forwarding) we emit all range tombstones the range intersects with, trimmed to said range.

**Review by denesb — APPROVED** [review]

File: flat_mutation_reader.cc (hunk 3 above)
Comment (kbr-) [reply flat_mutation_reader.cc]: Ok, then this guarantee needs to be documented.

In any case, I think the throw in `fast_forward_to` is therefore unnecessary. We should instead reset the assembler.

**Comment by enedil** [comment]
New version: fix the behaviour regarding fast_forward_to to position range. Revert setting `has_active_tombstone` to public in range_tombstone_assembler (it is no longer used).

**Review by haaawk — APPROVED** [review]
LGTM

**Comment by tgrabiec** [comment]
On Wed, Jul 14, 2021 at 2:07 PM Kamil Braun ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In flat_mutation_reader.cc
> <https://github.com/scylladb/scylla/pull/9023#discussion_r669551462>:
>
> >              _end_of_stream = false;
>              return _reader.fast_forward_to(pr, timeout);
>          }
>          virtual future<> fast_forward_to(position_range pr, db::timeout_clock::time_point timeout) override {
>              clear_buffer();
> +            if (_rt_assembler.needs_flush()) {
>
> Ok, then this guarantee needs to be documented.
>

This guarantee is implied by:

///    3) The position_range passed to fast_forward_to() is a clustering
key restriction.
///       Same rules apply as with clustering restrictions described above.

and:

///   0) The stream must contain fragments corresponding to all writes
///      which are relevant to the requested ranges.

If the stream did not reopen the range tombstone then it would not contain
fragments representing all relevant writes.

>

File: flat_mutation_reader.cc [hunk 5]
```diff
@@ -1344,6 +1345,13 @@ flat_mutation_reader downgrade_to_v1(flat_mutation_reader_v2 r) {
         }
         virtual future<> next_partition() override {
             clear_buffer_to_next_partition();
+
+            // If there is an active tombstone at the moment of doing next_partition(), simply clearing the buffer
+            // means that the closing range_tombstone_change will not be processed by the assembler. This violates
+            // an assumption of the assembler. Since the client executed next_partition(), they aren't interested
+            // in currently active tombstone_change (if any). Therefore in both cases, next partition should start
+            // with the assembler state reset.
+            _rt_assembler.reset();
```
Comment (tgrabiec) [inline flat_mutation_reader.cc:1354]: I think it's wrong to reset the assembler here. _rt_assembler is part of the producer's state, and producer may be ahead of the consumer. For example, the producer may be inside partition P2 now, and the consumer which calls next_partition() may be inside P1, skipping into P2. In such case, resetting _rt_assembler will corrupt the assembler.

We should reset it only if `is_buffer_empty()`.

**Review by tgrabiec — CHANGES_REQUESTED** [review]

File: flat_mutation_reader.cc (hunk 5 above)
Comment (enedil) [reply flat_mutation_reader.cc]: Agreed. I made the requested change.

**Comment by enedil** [comment]
Last force push included reseting the state only if the buffer is empty.

**Comment by tgrabiec** [comment]
Merge conflicts present, please rebase.

**Review by tgrabiec — APPROVED** [review]

**Comment by enedil** [comment]
Thanks. I just rebased.
