### PR TITLE
repair: Switch to btree_set for repair_hash.

### LINKED ISSUE #6190: reactor stalled for 1304 ms during abort repair nemesis
Installation details
Scylla version (or git commit hash): 4.0.rc0-0.20200405.511773d4662 with build-id de88161d63d02e10ad1b3f2a761cb15aee71d8c9
Cluster size: 4 DB nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-02ffbefa17e58c217

job running is 1TB 7 days longevity.

node that experienced issue is node-3
```
Reactor stalled for 1304 ms on shard 4.
Backtrace:
0x0000000002ed97f2
0x0000000002e7f34b
0x0000000002e7f872
0x0000000002e7fba7
0x00007f7dc8cbdb1f
0x0000000000faaa12
0x0000000000fa1763
0x0000000000fa31ae
0x0000000002e37368
0x0000000002e37bb7
0x0000000002e3bc53
0x000000000211649f
0x00000000024eef86
0x00000000024ef0d3
0x00000000024ef5fa
0x00000000024ef890
0x0000000002e7b840
0x0000000002e7ba4f
0x0000000002eb39f5
0x0000000002ec201c
0x0000000002e4d70d
/opt/scylladb/libreloc/libpthread.so.0+0x00000000000094e1
/opt/scylladb/libreloc/libc.so.6+0x00000000001016d2
```

decoded:
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/fmt/format.h:1158
seastar::backtrace_buffer::append_backtrace() at /usr/include/fmt/format.h:1158
 (inlined by) print_with_backtrace at ./build/release/seastar/./seastar/src/core/reactor.cc:755
seastar::internal::cpu_stall_detector::generate_trace() at /usr/include/fmt/format.h:1158
seastar::internal::cpu_stall_detector::maybe_report() at /usr/include/fmt/format.h:1158
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1062
 (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1185
?? ??:0
logalloc::region_impl::object_descriptor::migrator() const at ./utils/logalloc.cc:1005
 (inlined by) logalloc::region_impl::object_descriptor::live_size(void const*) const at ./utils/logalloc.cc:1014
 (inlined by) void logalloc::region_impl::for_each_live<logalloc::region_impl::compact(logalloc::segment*, logalloc::segment_descriptor&)::{lambda(logalloc::region_impl::object_descriptor const*, void*)#1}>(logalloc::segment*, logalloc::region_impl::compact(logalloc::segment*, logalloc::segment_descriptor&)::{lambda(logalloc::region_impl::object_descriptor const*, void*)#1}&&) at ./utils/logalloc.cc:1191
 (inlined by) logalloc::region_impl::compact(logalloc::segment*, logalloc::segment_descriptor&) at ./utils/logalloc.cc:1245
 (inlined by) logalloc::region_impl::compact_single_segment_locked() at ./utils/logalloc.cc:1534
logalloc::region_impl::compact() at /usr/include/fmt/format.h:1158
 (inlined by) logalloc::tracker::impl::compact_and_evict_locked(unsigned long, unsigned long) at ./utils/logalloc.cc:2016
logalloc::tracker::impl::reclaim(unsigned long) at /usr/include/fmt/format.h:1158
 (inlined by) logalloc::tracker::reclaim(unsigned long) at ./utils/logalloc.cc:418
 (inlined by) logalloc::tracker::reclaim(seastar::memory::reclaimer::request) at ./utils/logalloc.cc:1679
 (inlined by) operator() at ./utils/logalloc.cc:411
 (inlined by) _M_invoke at /usr/include/c++/9/bits/std_function.h:285
std::function<seastar::memory::reclaiming_result (seastar::memory::reclaimer::request)>::operator()(seastar::memory::reclaimer::request) const at /usr/include/c++/9/ostream:221
 (inlined by) seastar::memory::reclaimer::do_reclaim(unsigned long) at ./build/release/seastar/./seastar/include/seastar/core/memory.hh:129
 (inlined by) seastar::memory::cpu_pages::run_reclaimers(seastar::memory::reclaimer_scope, unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:1034
seastar::memory::cpu_pages::find_and_unlink_span_reclaiming(unsigned int) at /usr/include/c++/9/ostream:221
 (inlined by) seastar::memory::cpu_pages::allocate_large_and_trim(unsigned int) at ./build/release/seastar/./seastar/src/core/memory.cc:632
seastar::memory::cpu_pages::allocate_large(unsigned int) at /usr/include/c++/9/ostream:221
 (inlined by) seastar::memory::allocate_large(unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:1216
 (inlined by) seastar::memory::allocate(unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:1268
 (inlined by) operator new(unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:1694
__gnu_cxx::new_allocator<std::__detail::_Hash_node_base*>::allocate(unsigned long, void const*) at /usr/include/c++/9/bits/stl_vector.h:1756
 (inlined by) std::allocator_traits<std::allocator<std::__detail::_Hash_node_base*> >::allocate(std::allocator<std::__detail::_Hash_node_base*>&, unsigned long) at /usr/include/c++/9/bits/alloc_traits.h:444
 (inlined by) std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<gms::inet_address const, gms::inet_address>, true> > >::_M_allocate_buckets(unsigned long) at /usr/include/c++/9/bits/hashtable_policy.h:2134
 (inlined by) std::_Hashtable<repair_hash, repair_hash, std::allocator<repair_hash>, std::__detail::_Identity, std::equal_to<repair_hash>, std::hash<repair_hash>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >::_M_allocate_buckets(unsigned long) at /usr/include/c++/9/bits/hashtable.h:361
 (inlined by) std::_Hashtable<repair_hash, repair_hash, std::allocator<repair_hash>, std::__detail::_Identity, std::equal_to<repair_hash>, std::hash<repair_hash>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >::_M_rehash_aux(unsigned long, std::integral_constant<bool, true>) at /usr/include/c++/9/bits/hashtable.h:2088
 (inlined by) std::_Hashtable<repair_hash, repair_hash, std::allocator<repair_hash>, std::__detail::_Identity, std::equal_to<repair_hash>, std::hash<repair_hash>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >::_M_rehash(unsigned long, unsigned long const&) at /usr/include/c++/9/bits/hashtable.h:2067
std::_Hashtable<repair_hash, repair_hash, std::allocator<repair_hash>, std::__detail::_Identity, std::equal_to<repair_hash>, std::hash<repair_hash>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >::_M_insert_unique_node(unsigned long, unsigned long, std::__detail::_Hash_node<repair_hash, true>*, unsigned long) at /usr/include/fmt/format.h:1158
std::pair<std::__detail::_Node_iterator<repair_hash, true, true>, bool> std::_Hashtable<repair_hash, repair_hash, std::allocator<repair_hash>, std::__detail::_Identity, std::equal_to<repair_hash>, std::hash<repair_hash>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >::_M_insert<repair_hash const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<repair_hash, true> > > >(repair_hash const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<repair_hash, true> > > const&, std::integral_constant<bool, true>, unsigned long) at /usr/include/fmt/format.h:1158
std::__detail::_Insert_base<repair_hash, repair_hash, std::allocator<repair_hash>, std::__detail::_Identity, std::equal_to<repair_hash>, std::hash<repair_hash>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >::insert(repair_hash const&) at /usr/include/fmt/format.h:1158
 (inlined by) std::unordered_set<repair_hash, std::hash<repair_hash>, std::equal_to<repair_hash>, std::allocator<repair_hash> >::insert(repair_hash const&) at /usr/include/c++/9/bits/unordered_set.h:421
 (inlined by) repair_meta::get_full_row_hashes_source_op(seastar::lw_shared_ptr<std::unordered_set<repair_hash, std::hash<repair_hash>, std::equal_to<repair_hash>, std::allocator<repair_hash> > >, gms::inet_address, unsigned int, seastar::rpc::source<repair_hash_with_cmd>&)::{lambda()#1}::operator()()::{lambda(std::optional<std::tuple<repair_hash_with_cmd> >)#1}::operator()(std::tuple<repair_hash_with_cmd>) at ./repair/row_level.cc:1331
 (inlined by) seastar::apply_helper<repair_meta::get_full_row_hashes_source_op(seastar::lw_shared_ptr<std::unordered_set<repair_hash, std::hash<repair_hash>, std::equal_to<repair_hash>, std::allocator<repair_hash> > >, gms::inet_address, unsigned int, seastar::rpc::source<repair_hash_with_cmd>&)::{lambda()#1}::operator()()::{lambda(std::optional<std::tuple<repair_hash_with_cmd> >)#1}, std::optional<std::tuple<repair_hash_with_cmd> >&&, std::integer_sequence<unsigned long, 0ul> >::apply(std::optional<std::tuple<repair_hash_with_cmd> >&&, repair_meta::get_full_row_hashes_source_op(seastar::lw_shared_ptr<std::unordered_set<repair_hash, std::hash<repair_hash>, std::equal_to<repair_hash>, std::allocator<repair_hash> > >, gms::inet_address, unsigned int, seastar::rpc::source<repair_hash_with_cmd>&)::{lambda()#1}::operator()()::{lambda(std::optional<std::tuple<repair_hash_with_cmd> >)#1}) at ././seastar/include/seastar/core/apply.hh:36
 (inlined by) auto seastar::apply<repair_meta::get_full_row_hashes_source_op(seastar::lw_shared_ptr<std::unordered_set<repair_hash, std::hash<repair_hash>, std::equal_to<repair_hash>, std::allocator<repair_hash> > >, gms::inet_address, unsigned int, seastar::rpc::source<repair_hash_with_cmd>&)::{lambda()#1}::operator()()::{lambda(std::optional<std::tuple<repair_hash_with_cmd> >)#1}, std::tuple<repair_hash_with_cmd> >(repair_meta::get_full_row_hashes_source_op(seastar::lw_shared_ptr<std::unordered_set<repair_hash, std::hash<repair_hash>, std::equal_to<repair_hash>, std::allocator<repair_hash> > >, gms::inet_address, unsigned int, seastar::rpc::source<repair_hash_with_cmd>&)::{lambda()#1}::operator()()::{lambda(std::optional<std::tuple<repair_hash_with_cmd> >)#1}&&, std::optional<std::tuple<repair_hash_with_cmd> >&&) at ././seastar/include/seastar/core/apply.hh:44
 (inlined by) seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > seastar::futurize<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > >::apply<repair_meta::get_full_row_hashes_source_op(seastar::lw_shared_ptr<std::unordered_set<repair_hash, std::hash<repair_hash>, std::equal_to<repair_hash>, std::allocator<repair_hash> > >, gms::inet_address, unsigned int, seastar::rpc::source<repair_hash_with_cmd>&)::{lambda()#1}::operator()()::{lambda(std::optional<std::tuple<repair_hash_with_cmd> >)#1}, std::tuple<repair_hash_with_cmd> >(repair_meta::get_full_row_hashes_source_op(seastar::lw_shared_ptr<std::unordered_set<repair_hash, std::hash<repair_hash>, std::equal_to<repair_hash>, std::allocator<repair_hash> > >, gms::inet_address, unsigned int, seastar::rpc::source<repair_hash_with_cmd>&)::{lambda()#1}::operator()()::{lambda(std::optional<std::tuple<repair_hash_with_cmd> >)#1}&&, std::optional<std::tuple<repair_hash_with_cmd> >&&) at ././seastar/include/seastar/core/future.hh:1664
 (inlined by) seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > seastar::future<std::optional<std::tuple<repair_hash_with_cmd> > >::then_impl<repair_meta::get_full_row_hashes_source_op(seastar::lw_shared_ptr<std::unordered_set<repair_hash, std::hash<repair_hash>, std::equal_to<repair_hash>, std::allocator<repair_hash> > >, gms::inet_address, unsigned int, seastar::rpc::source<repair_hash_with_cmd>&)::{lambda()#1}::operator()()::{lambda(std::optional<std::tuple<repair_hash_with_cmd> >)#1}, seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > >(repair_meta::get_full_row_hashes_source_op(seastar::lw_shared_ptr<std::unordered_set<repair_hash, std::hash<repair_hash>, std::equal_to<repair_hash>, std::allocator<repair_hash> > >, gms::inet_address, unsigned int, seastar::rpc::source<repair_hash_with_cmd>&)::{lambda()#1}::operator()()::{lambda(std::optional<std::tuple<repair_hash_with_cmd> >)#1}&&) at ././seastar/include/seastar/core/future.hh:1194
 (inlined by) seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > seastar::future<std::optional<std::tuple<repair_hash_with_cmd> > >::then<repair_meta::get_full_row_hashes_source_op(seastar::lw_shared_ptr<std::unordered_set<repair_hash, std::hash<repair_hash>, std::equal_to<repair_hash>, std::allocator<repair_hash> > >, gms::inet_address, unsigned int, seastar::rpc::source<repair_hash_with_cmd>&)::{lambda()#1}::operator()()::{lambda(std::optional<std::tuple<repair_hash_with_cmd> >)#1}, seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > >(repair_meta::get_full_row_hashes_source_op(seastar::lw_shared_ptr<std::unordered_set<repair_hash, std::hash<repair_hash>, std::equal_to<repair_hash>, std::allocator<repair_hash> > >, gms::inet_address, unsigned int, seastar::rpc::source<repair_hash_with_cmd>&)::{lambda()#1}::operator()()::{lambda(std::optional<std::tuple<repair_hash_with_cmd> >)#1}&&) at ././seastar/include/seastar/core/future.hh:1175
 (inlined by) repair_meta::get_full_row_hashes_source_op(seastar::lw_shared_ptr<std::unordered_set<repair_hash, std::hash<repair_hash>, std::equal_to<repair_hash>, std::allocator<repair_hash> > >, gms::inet_address, unsigned int, seastar::rpc::source<repair_hash_with_cmd>&)::{lambda()#1}::operator()() at ./repair/row_level.cc:1344
 (inlined by) seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > seastar::futurize<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > >::apply<repair_meta::get_full_row_hashes_source_op(seastar::lw_shared_ptr<std::unordered_set<repair_hash, std::hash<repair_hash>, std::equal_to<repair_hash>, std::allocator<repair_hash> > >, gms::inet_address, unsigned int, seastar::rpc::source<repair_hash_with_cmd>&)::{lambda()#1}&>(repair_meta::get_full_row_hashes_source_op(seastar::lw_shared_ptr<std::unordered_set<repair_hash, std::hash<repair_hash>, std::equal_to<repair_hash>, std::allocator<repair_hash> > >, gms::inet_address, unsigned int, seastar::rpc::source<repair_hash_with_cmd>&)::{lambda()#1}&) at ././seastar/include/seastar/core/future.hh:1674
seastar::internal::repeater<repair_meta::get_full_row_hashes_source_op(seastar::lw_shared_ptr<std::unordered_set<repair_hash, std::hash<repair_hash>, std::equal_to<repair_hash>, std::allocator<repair_hash> > >, gms::inet_address, unsigned int, seastar::rpc::source<repair_hash_with_cmd>&)::{lambda()#1}>::run_and_dispose() at /usr/include/fmt/format.h:1158
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /usr/include/fmt/format.h:1158
seastar::reactor::run_some_tasks() at /usr/include/fmt/format.h:1158
seastar::reactor::run_some_tasks() at /usr/include/fmt/format.h:1158
 (inlined by) seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2693
seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::{lambda()#3}::operator()() const at /usr/include/fmt/format.h:1158
std::function<void ()>::operator()() const at /usr/include/c++/9/bits/std_function.h:690
 (inlined by) seastar::posix_thread::start_routine(void*) at ./build/release/seastar/./seastar/src/core/posix.cc:52
```

full logs here:
```
+--------------------------------------------------------------------------------------------------------------------------------------------+
|                                      Collected logs by test-id: bbc128f5-0097-4db4-9327-d46c7d8e73a2                                       |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
| Cluster set | Link                                                                                                                         |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
| db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/bbc128f5-0097-4db4-9327-d46c7d8e73a2/20200412_105848/db-cluster-bbc128f5.zip  |
| monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/bbc128f5-0097-4db4-9327-d46c7d8e73a2/20200412_105848/monitor-set-bbc128f5.zip |
| loader-set  | None                                                                                                                         |
| sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/bbc128f5-0097-4db4-9327-d46c7d8e73a2/20200412_105848/sct-runner-bbc128f5.zip  |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by asias**
In one of the longevity tests, we observed 1.3s reactor stall which came from
repair_meta::get_full_row_hashes_source_op. It traced back to a call to
std::unordered_set::insert() which triggered big memory allocation and
reclaim.

I measured std::unordered_set, absl::flat_hash_set, absl::node_hash_set
and absl::btree_set. The absl::btree_set was the only one that seastar
oversized allocation checker did not warn in my tests where around 300K
repair hashes were inserted into the container.

- unordered_set:
hash_sets=295634, time=333029199 ns

- flat_hash_set:
hash_sets=295634, time=312484711 ns

- node_hash_set:
hash_sets=295634, time=346195835 ns

- btree_set:
hash_sets=295634, time=341379801 ns

The btree_set is a bit slower than unordered_set but it does not have
huge memory allocation. I do not measure real difference of total time
to finish repair of the same dataset with unordered_set and btree_set.

To fix, switch to absl btree_set container.

Fixes #6190

### CODE REVIEW

File: repair/row_level.cc [hunk 1]
```diff
@@ -47,6 +47,7 @@
 #include "gms/gossiper.hh"
 #include "repair/row_level.hh"
 #include "mutation_source_metadata.hh"
+#include <absl/container/flat_hash_set.h>
```
Comment (avikivity) [inline repair/row_level.cc:50]: Looks unrelated.

Comment (asias) [reply repair/row_level.cc]: Fixed. It was an leftover when playing with flat_hash_set.

**Comment by slivne** [comment]
@asias are we transferring this data between nodes - I saw you updated searializer_impl.

If we do transfer this between ndoes - will this work in a cluster that has mixed nodes - one using the old impl and another with the new ?

Do we have any test for this ?

**Comment by asias** [comment]
> @asias are we transferring this data between nodes - I saw you updated searializer_impl.
> 
> If we do transfer this between ndoes - will this work in a cluster that has mixed nodes - one using the old impl and another with the new ?
> 
> Do we have any test for this ?

It is fine because the on wire format is the same with/without this patch. So a mixed cluster will work.

**Comment by avikivity** [comment]
Please eliminate the compile-time bloat by hiding the btree in a unique_ptr (inside a new class repair_hash_set) and removing all includes of btree_map from header filess.

**Comment by asias** [comment]
> Please eliminate the compile-time bloat by hiding the btree in a unique_ptr (inside a new class repair_hash_set) and removing all includes of btree_map from header filess.

OK. I will do a follow up.
