### PR TITLE
table: fix race and exception handling in on_compaction_completion()

### LINKED ISSUE #7331: Shutting down database hangs in dtest-debug
Seen consistently since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/604/testReport
Scylla version f1fcf4f13915c2d3ed532a3a32fc51a8ce7c08ac

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/604/artifact/logs-debug.2/1601137898758_repair_additional_test.RepairAdditionalTest.repair_option_pr_dc_host_test/node1.log
```
INFO  2020-09-26 16:14:03,637 [shard 0] init - Shutting down database
Scylla version 666.development-0.20200924.f1fcf4f13 with build-id 1b71d370bdf7e15b911b8e16e18b291737d79b35 starting ...
...
INFO  2020-09-26 16:25:46,848 [shard 0] init - Shutting down database
Scylla version 666.development-0.20200924.f1fcf4f13 with build-id 1b71d370bdf7e15b911b8e16e18b291737d79b35 starting ...
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/604/artifact/logs-debug.2/1601139448436_repair_additional_test.RepairAdditionalTest.repair_option_pr_multi_dc_test/node1.log
```
INFO  2020-09-26 16:32:42,395 [shard 0] init - Shutting down database
Scylla version 666.development-0.20200924.f1fcf4f13 with build-id 1b71d370bdf7e15b911b8e16e18b291737d79b35 starting ...
```

But not only in those dtests, for example:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/610/artifact/logs-debug.2/1601850222686_bootstrap_test.TestBootstrap.start_stop_test/node1.log
```
INFO  2020-10-04 22:21:36,140 [shard 0] init - Shutting down database
<EOF>
```

Note that this looks similar, but different than https://github.com/scylladb/scylla/issues/7183

### PR DESCRIPTION
**Pull request by avikivity**
Fix a race condition in on_compaction_completion() that can prevent shutdown, as well as an exception handling error. See individual patches for details.

Fixes #7331.

### CODE REVIEW

File: table.cc [hunk 1]
```diff
@@ -1022,15 +1030,6 @@ table::on_compaction_completion(sstables::compaction_completion_desc& desc) {
...
-    // unconditionally remove compacted sstables from _sstables_compacted_but_not_deleted,
-    // or they could stay forever in the set, resulting in deleted files remaining
-    // opened and disk space not being released until shutdown.
-    std::unordered_set<sstables::shared_sstable> s(
-           desc.old_sstables.begin(), desc.old_sstables.end());
-    auto e = boost::range::remove_if(_sstables_compacted_but_not_deleted, [&] (sstables::shared_sstable sst) {
-        return s.contains(sst);
-    });
-    _sstables_compacted_but_not_deleted.erase(e, _sstables_compacted_but_not_deleted.end());
     rebuild_statistics();
```
Comment (bhalevy) [inline table.cc:1033]: The call here to rebuild_statistics expects `_sstables_compacted_but_not_deleted` to be already updated so it should also go into the deferred action.

By the way, on the gate closed error path, these sstables aren't really deleted.  I'm not sure they are being tracked correctly, but since this happening on the shutdown path it doesn't matter.

**Review by bhalevy — CHANGES_REQUESTED** [review]

**Comment by bhalevy** [comment]
I tested `repair_additional_test:RepairAdditionalTest.repair_option_pr_multi_dc_test` with this change in debug mode and it indeed fixes https://github.com/scylladb/scylla/issues/7331

File: table.cc (hunk 1 above)
Comment (avikivity) [reply table.cc:1033]: Good catch, will update.

Probably, we should delete those sstables unconditionally. The time to delete isn't worth the extra special case. But I won't do that in this series.

**Comment by avikivity** [comment]
> I tested `repair_additional_test:RepairAdditionalTest.repair_option_pr_multi_dc_test` with this change in debug mode and it indeed fixes #7331

I will add a Fixes tag.

**Comment by avikivity** [comment]
Updated:
 - added Fixes: #7331 (thanks @bhalevy for testing)
 - made final rebuild_statistics) happen after we update the sstable list

**Review by bhalevy — APPROVED** [review]
LGTM

**Comment by eliransin** [comment]
LGTM also (not that anyone asked me :slightly_smiling_face: )
