### PR TITLE
Fix index name conflicts with regular tables

### LINKED ISSUE #8620: Creating a table which looks like a secondary index breaks the secondary idnex creation mechanism
When testing an unrelated change, I came across a way to ;eave the secondary index creation mechanism in Scylla in a broken state.

Reproducer:
```cql
CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
use ks;
CREATE TABLE t (id int primary key, v int);
CREATE TABLE t_v_idx_index (id int primary key);
CREATE INDEX ON t(v);
DROP TABLE t_v_idx_index;
```

The snippet exploits the fact that the internal table created for the secondary index is named after a pattern - in this case, an index on `t(v)` is going to be named `t_v_idx`, and its table is going to be `t_v_idx_index`.

Since we happened to create a regular table with an identical name, creating an index fails. The first minor bug is that the error message says `ServerError: Column family t3_v_idx_index exists`, which is not strictly true - such index does not exist, there just happens to be a table named identically. It gets worse:
1. Trying to remove the table results in a cryptic error which makes little sense: `ServerError: Can't find a column family with UUID 1027b711-b18f-11eb-bcd4-ab78603bce8b`. The table was just created, so why can't we drop it?
2. Dropping an index also doesn't work (that's expected), but the index **is** listed in the local schema tables:
```cql
 keyspace_name | table_name | index_name | kind       | options
---------------+------------+------------+------------+-----------------
            ks |          t |    t_v_idx | COMPOSITES | {'target': 'v'}
```
3. What's even more weird, our `t_v_idx_index` table seems to **not** exist in the schema tables, so its removal was actually successful, even though it returned an error:
```cql
cassandra@cqlsh:ks> select table_name from system_schema. tables where keyspace_name = 'ks';

 table_name
------------
          t
```

This bug is not particularly dangerous, since it requires creating a maliciously named table, but it's nonetheless a bug. Also, a trivial workaround is to created a named index - `CREATE INDEX hello ON t(v)` works just fine.

### PR DESCRIPTION
**Pull request by psarna**
When an index is created without an explicit name, a default name
is chosen. However, there was no check if a table with conflicting
name already exists. The check is now in place and if any conflicts
are found, a new index name is chosen instead.
When an index is created *with* an explicit name and a conflicting
regular table is found, index creation should simply fail.

This series comes with a test.

Fixes #8620
Tests: unit(release)

### CODE REVIEW

**Comment by nyh** [comment]
> When an index is created without an explicit name, a default name
> is chosen. However, there was no check if a table with conflicting
> name already exists. The check is now in place and if any conflicts
> are found, a new index name is chosen instead.

This is fine when an index name is not explicitly used, but when an index name is explicitly given, we have no choice on how to name it and its materialized view - and need to generate an error and can't just work around the problem... Please make sure that your test covers this case as well (and this test will xfail if your fix doesn't fix it), and don't "Fixes" the issue if there's a remaining problem.

File: database.cc [hunk 1]
```diff
@@ -1955,7 +1955,12 @@ sstring database::get_available_index_name(const sstring &ks_name, const sstring
     auto base_name = index_metadata::get_default_index_name(cf_name, index_name_root);
     sstring accepted_name = base_name;
     int i = 0;
-    while (existing_names.contains(accepted_name)) {
+    auto name_accepted = [&] {
+        auto index_table_name = secondary_index::index_table_name(accepted_name);
+        const bool table_exists = _ks_cf_to_uuid.find(std::make_pair(ks_name, index_table_name)) != _ks_cf_to_uuid.end();
```
Comment (nyh) [inline database.cc:1960]: We have a function `database::has_schema(std::string_view ks_name, std::string_view cf_name)` which does **exactly** this _ks_cf_to_uuid thing, so you should probably use it for shorter and clearer code. It will be so short you won't even need a variable "table_exists" ;-)

Comment (nyh) [reply database.cc:1960]: I just noticed you use has_schema() in the next patch :-)

File: test/cql-pytest/test_secondary_index.py [hunk 2]
```diff
@@ -100,3 +100,36 @@ def index_used(query, index_name):
         # Local indexes are still preferred over global ones, if they can be used
         index_used(f"SELECT * FROM {table} WHERE p = 1 and v1 = 1 and v3 = 2 and v2 = 2 allow filtering", "my_v2_idx")
         index_used(f"SELECT * FROM {table} WHERE p = 1 and v2 = 1 and v1 = 2 allow filtering", "my_v2_idx")
+
+# Indexes can be created without an explicit name, in which case a default name is chosen.
+# However, due to #8620 it was possible to break the index creation mechanism by creating
+# a properly named regular table, which conflicts with the generated index name.
+# A similar issue still exists for named indexes, so both cases are checked in this scenario.
```
Comment (nyh) [inline test/cql-pytest/test_secondary_index.py:107]: If you had split this into two tests, at least one of them (the one where the index creation is expected to succeed) would not need to be scylla_only.

File: test/cql-pytest/test_secondary_index.py [hunk 3]
```diff
@@ -100,3 +100,36 @@ def index_used(query, index_name):
...
+    with new_test_table(cql, test_keyspace, schema) as table:
+        # In case of default names, a proper name can always eventually be picked
+        index_created = False
+        try:
+            cql.execute(f"CREATE TABLE {table}_v_idx_index (i_do_not_exist_in_the_base_table int primary key)")
+            # Creating an index should succeed, even though its default name is taken
+            # by the table above
+            cql.execute(f"CREATE INDEX ON {table}(v)")
+            index_created = True
+            cql.execute(f"DROP INDEX {table}_v_idx_1")
```
Comment (nyh) [inline test/cql-pytest/test_secondary_index.py:119]: Note that you don't really need to drop the index manually - it will be dropped in the end of the test automatically. 
The only reason to have this DROP command is if you want to insist that the automatically chosen table name is table_v_idx_1. But I don't know why we want to insist that. Also this test would fail on Cassnadra (which would use the name table_v_idx, not table_v_idx_1, in this case).

File: test/cql-pytest/test_secondary_index.py [hunk 4]
```diff
@@ -100,3 +100,36 @@ def index_used(query, index_name):
...
+        finally:
+            cql.execute(f"DROP TABLE {table}_v_idx_index")
+        assert index_created
```
Comment (nyh) [inline test/cql-pytest/test_secondary_index.py:122]: I don't think you need this assert or the "index_created" variable. The only way for index_created to remain false is if the above code threw an exception and didn't run all the way. But if it did, the whole function will be exited with this exception! (the finally is guaranteed to run, but the function doesn't continue after it).

File: test/cql-pytest/test_secondary_index.py [hunk 5]
```diff
@@ -100,3 +100,36 @@ def index_used(query, index_name):
...
+        # In case of chosen names, a conflicting request should fail
+        index_name = unique_name()
+        invalid_request_caught = False
+        try:
+            cql.execute(f"CREATE TABLE {test_keyspace}.{index_name}_index (i_do_not_exist_in_the_base_table int primary key)")
+            # Creating an index should fail, because it's impossible to create
+            # its underlying materialized view, because its name is taken by a regular table
+            cql.execute(f"CREATE INDEX {index_name} ON {table}(v)")
```
Comment (nyh) [inline test/cql-pytest/test_secondary_index.py:130]: Please use pytest.raises() to say that a certain code (cql.execute()) is expected to throw an exception.
It's much shorter and clearer than running something that is expected to throw with a bare command and catching this exception later and remember that we did in a variable...

**Review by nyh — CHANGES_REQUESTED** [review]
Looks mostly good, but I do have some requests for small changes.
Thanks.

File: database.cc (hunk 1 above)
Comment (psarna) [reply database.cc:1960]: Right, I found it when coding the second patch and forgot that I used the ugly workaround in the first one. Will fix

**Review by nyh — APPROVED** [review]
Looks good. My only nitpick that I think the first test doesn't need a scylla_only.

File: test/cql-pytest/test_secondary_index.py [hunk 6]
```diff
@@ -100,3 +100,33 @@ def index_used(query, index_name):
         # Local indexes are still preferred over global ones, if they can be used
         index_used(f"SELECT * FROM {table} WHERE p = 1 and v1 = 1 and v3 = 2 and v2 = 2 allow filtering", "my_v2_idx")
         index_used(f"SELECT * FROM {table} WHERE p = 1 and v2 = 1 and v1 = 2 allow filtering", "my_v2_idx")
+
+# Indexes can be created without an explicit name, in which case a default name is chosen.
+# However, due to #8620 it was possible to break the index creation mechanism by creating
+# a properly named regular table, which conflicts with the generated index name.
+def test_create_unnamed_index_when_its_name_is_taken(scylla_only, cql, test_keyspace):
```
[the remark this answers is not in the document]
Comment (psarna) [reply test/cql-pytest/test_secondary_index.py:107]: Sure, ultimately I'm fine with both ways, so I'll push v4 without scylla_only in a minute
