### PR TITLE
Harden batchlog_manager stop and call from main in deferred action

### LINKED ISSUE #9009: batchlog manager is not stopped if scylla shuts down during startup
This issue stems off of #8995.

In addition to storage_proxy::drain_on_shutdown not synchronizing with on-going queries, the reason there is an on-going query after the storage_proxy is drained appears to be that the batchlog manager is not stopped if scylla gets a shutdown signal during startup (e.g. when waiting for gossip to settle).

I'm opening a separate issue for that since I think we should fix the storage_proxy draining synchronization as well, but this issue is orthogonal and fixing it will also fix the failures we see in several dtests, like the following one:

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/864/testReport/update_cluster_layout_tests/TestUpdateClusterLayout/simple_add_new_node_while_adding_info_1_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 648, in run
    self.tearDown()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1148, in tearDown
    self.cleanUpCluster()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1202, in cleanUpCluster
    raise AssertionError('Unexpected errors found: {}'.format(found_errors))
AssertionError: Unexpected errors found: [('node4', ['ERROR 2021-07-05 02:43:39,078 [shard 0] storage_proxy - Exception when communicating with 127.0.53.4, to read from system.batchlog: seastar::gate_closed_exception (gate closed)', 'ERROR 2021-07-05 02:43:39,079 [shard 0] batchlog_manager - Exception in batch replay: exceptions::read_failure_exception (Operation failed for system.batchlog - received 0 responses and 1 failures from 1 CL=ONE.)'])]
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/864/artifact/logs-all.release.2/1625453021390_update_cluster_layout_tests.TestUpdateClusterLayout.simple_add_new_node_while_adding_info_1_test/node4.log
```
INFO  2021-07-05 02:43:33,373 [shard 0] init - Shutting down drain storage proxy
INFO  2021-07-05 02:43:33,373 [shard 0] hints_manager - Asked to stop
INFO  2021-07-05 02:43:33,373 [shard 0] hints_manager - Stopped
INFO  2021-07-05 02:43:33,374 [shard 1] hints_manager - Asked to stop
INFO  2021-07-05 02:43:33,374 [shard 1] hints_manager - Stopped
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down drain storage proxy was successful
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down streaming service
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down streaming service was successful
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down Raft RPC
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down Raft RPC was successful
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down storage proxy RPC verbs
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down storage proxy RPC verbs was successful
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down sstables format selector
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down sstables format selector was successful
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down migration manager
INFO  2021-07-05 02:43:33,374 [shard 0] migration_manager - stopping migration service
INFO  2021-07-05 02:43:33,374 [shard 1] migration_manager - stopping migration service
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down migration manager was successful
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down database
INFO  2021-07-05 02:43:39,078 [shard 0] init - Shutting down database was successful
INFO  2021-07-05 02:43:39,078 [shard 0] init - Shutting down service_memory_limiter
INFO  2021-07-05 02:43:39,078 [shard 0] init - Shutting down service_memory_limiter was successful
INFO  2021-07-05 02:43:39,078 [shard 0] init - Shutting down sst_dir_semaphore
ERROR 2021-07-05 02:43:39,078 [shard 0] storage_proxy - Exception when communicating with 127.0.53.4, to read from system.batchlog: seastar::gate_closed_exception (gate closed)
ERROR 2021-07-05 02:43:39,079 [shard 0] batchlog_manager - Exception in batch replay: exceptions::read_failure_exception (Operation failed for system.batchlog - received 0 responses and 1 failures from 1 CL=ONE.)
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down sst_dir_semaphore was successful
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down Raft
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down Raft was successful
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down messaging service
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down messaging service was successful
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down API server
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down API server was successful
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down tracing instance
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down tracing instance was successful
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down migration manager notifier
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down migration manager notifier was successful
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down prometheus API server
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down prometheus API server was successful
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down sighup
INFO  2021-07-05 02:43:39,080 [shard 0] init - Shutting down sighup was successful
ERROR 2021-07-05 02:43:39,080 [shard 0] init - Startup failed: seastar::sleep_aborted (Sleep is aborted)
```

### PR DESCRIPTION
**Pull request by bhalevy**
This PR contains the parts relevant to batchlog_manager stop in #8998 without adding a gate to the storage_proxy for synchronization with on-going queries in storage_proxy::drain_on_shutdown.

As explained in #9009, we see that the batchlog_manager isn't stopped if scylla shuts down during startup, e.g. when waiting for gossip to settle, since currently the batchlog_manager is stopped only from `storage_service::do_drain`, while `storage_service::drain_on_shutdown` deferred shutdown is installed only later on:
https://github.com/scylladb/scylla/blob/222ef17305b07e8faabd5d921e2bad0d7f78e106/main.cc#L1419-L1421

Fixes #9009

Test: unit(dev)
DTest: compact_storage_tests.py:TestCompactStorage.wide_row_test paging_test:TestPagingDatasetChanges.test_cell_TTL_expiry_during_paging update_cluster_layout_tests:TestUpdateClusterLayout.simple_add_new_node_while_adding_info_{1,2}_test (dev)

### CODE REVIEW

File: db/batchlog_manager.cc [hunk 1]
```diff
@@ -123,7 +123,9 @@ future<> db::batchlog_manager::start() {
             (void)do_batch_log_replay().handle_exception([] (auto ep) {
```
Comment (avikivity) [inline db/batchlog_manager.cc:123]: I think there's still a problem here. do_batch_log_replay doesn't enter the gate, so it won't synchronize with stop().

**Comment by avikivity** [comment]
I think a better way than having a timer start itself again recursively is for start() to launch a coroutine (storing its returned future somewhere) and for stop() to tell the coroutine to stop. Right now we have a mix of semaphores, gates, and checks of _stop, together with cross-shard calls. It's unlikely to work reliably.

But let's fix it first and then rewrite it.

File: db/batchlog_manager.cc (hunk 1 above)
Comment (bhalevy) [reply db/batchlog_manager.cc:123]: That's exactly the reason I added `_sem.wait()` to stop() in https://github.com/scylladb/scylla/pull/9010/commits/19e026ca3b5e94eaa755f7a064f97a5b0f84ee19

**Comment by bhalevy** [comment]
> I think a better way than having a timer start itself again recursively is for start() to launch a coroutine (storing its returned future somewhere) and for stop() to tell the coroutine to stop. Right now we have a mix of semaphores, gates, and checks of _stop, together with cross-shard calls. It's unlikely to work reliably.

Sounds simpler indeed.

> 
> But let's fix it first and then rewrite it.

File: main.cc [hunk 2]
```diff
@@ -1277,6 +1277,11 @@ int main(int ac, char** av) {
             db::get_batchlog_manager().invoke_on_all([] (db::batchlog_manager& b) {
                 return b.start();
             }).get();
+            auto stop_batchlog_manager = defer_verbose_shutdown("batchlog manager", [] {
+                db::get_batchlog_manager().invoke_on_all([] (auto& bm) {
+                    return bm.stop();
+                }).get();
```
Comment (xemul) [inline main.cc:1283]: nit: Can be one-liner
```c++
db::get_batchlog_manager().invoke_on_all(&db::batchlog_manager::stop).get();
```

File: db/batchlog_manager.cc [hunk 3]
```diff
@@ -140,7 +140,13 @@ future<> db::batchlog_manager::stop() {
     }
     _stop = true;
     _timer.cancel();
+    // Synchronize with do_batch_log_replay.
+    // Although _sem might be held only on shard 0
+    // it is safe to wait for it on all shards.
+    return _sem.wait().then([this] {
```
Comment (xemul) [inline db/batchlog_manager.cc:146]: Maybe teach `do_batchlog_replay()` run inside the `_gate` instead? Thus the `_gate.close()` will capture those too.

**Comment by bhalevy** [comment]
In v2:
- Harden start/stop by using an abort_source to abort from the replay loop.
- Extract the loop into batchlog_replay_loop() coroutine, with the _stop abourt source as a stop condition,
    plus use it for sleep_abortable to be able to promptly stop while sleeping.
- start() stores its returned future in an optional _started member, which is waited on in stop() to synchronize with the start process at any stage.
- stop() was made idempotent by making sure each required step (request_abort, wait on _strated, and closing _gate) is done only once.
- simplified batchlog_manager stop using `invoke_on_all(&db::batchlog_manager::stop)`

File: db/batchlog_manager.cc (hunk 3 above)
Comment (bhalevy) [reply db/batchlog_manager.cc]: solved in a better way in v2 by waiting on _started future returned from the replay loop after requesting abort.

File: main.cc (hunk 2 above)
Comment (bhalevy) [reply main.cc]: fixed in v2.

**Comment by bhalevy** [comment]
In v3:
- updated the comment for batchlog_replay_loop (no _timer anymore)
- batchlog_manager: do_batch_log_replay: hold _gate
- batchlog_manager: make it peering_sharded_service
- batchlog_manager: stop: break _sem on shard 0

File: db/batchlog_manager.cc (hunk 1 above)
Comment (bhalevy) [reply db/batchlog_manager.cc]: @avikivity ping, please re-review.

**Comment by bhalevy** [comment]
ping review

File: db/batchlog_manager.cc [hunk 4]
```diff
@@ -110,35 +112,47 @@ future<> db::batchlog_manager::do_batch_log_replay() {
     });
 }
 
+// Since replay is a "node global" operation, we should not attempt to do
+// it in parallel on each shard. It will just overlap/interfere.  To
```
Comment (avikivity) [inline db/batchlog_manager.cc:120]: I don't agree with this moved comment.

File: db/batchlog_manager.hh [hunk 5]
```diff
@@ -89,12 +90,12 @@ private:
     cql3::query_processor& _qp;
     db_clock::duration _write_request_timeout;
     uint64_t _replay_rate;
-    timer<clock_type> _timer;
+    std::optional<future<>> _started;
```
Comment (avikivity) [inline db/batchlog_manager.hh:93]: A simpler way is to use a non-optional future intialized to the coroutine, or to a ready future. But this is fine too.

File: main.cc [hunk 6]
```diff
@@ -1277,6 +1277,9 @@ int main(int ac, char** av) {
             db::get_batchlog_manager().invoke_on_all([] (db::batchlog_manager& b) {
                 return b.start();
             }).get();
+            auto stop_batchlog_manager = defer_verbose_shutdown("batchlog manager", [] {
+                db::get_batchlog_manager().invoke_on_all(&db::batchlog_manager::stop).get();
+            });
```
Comment (avikivity) [inline main.cc:1282]: stop() is not idempotent due to the std::exchange(). The first stop() will wait, the second stop() will not.

If you want to make stop() idempotent, use a shared_future. The best is not to rely on stop() idempotency, it's just tricky. Call stop() exactly one time, and abort() to abort the loop.

File: db/batchlog_manager.cc [hunk 7]
```diff
@@ -94,22 +94,22 @@ db::batchlog_manager::batchlog_manager(cql3::query_processor& qp, batchlog_manag
 future<> db::batchlog_manager::do_batch_log_replay() {
     // Use with_semaphore is much simpler, but nested invoke_on can
     // cause deadlock.
-    return get_batchlog_manager().invoke_on(0, [] (auto& bm) {
```
Comment (avikivity) [inline db/batchlog_manager.cc:95]: Changelog lacks motivation.

Comment (bhalevy) [reply db/batchlog_manager.cc:95]: I'll send it separately as a followup.
It's immaterial to this fix...

File: main.cc (hunk 6 above)
Comment (bhalevy) [reply main.cc:1282]: okay, makes sense

File: db/batchlog_manager.hh (hunk 5 above)
Comment (bhalevy) [reply db/batchlog_manager.hh:93]: okay, will use a plain future<> initialized to a ready one.

File: db/batchlog_manager.cc (hunk 4 above)
Comment (bhalevy) [reply db/batchlog_manager.cc:120]: You don't agree with its contents or it being moved?
Changing this part is out of scope for this fix...

**Comment by bhalevy** [comment]
In v4:
- reordered the patches
- dropped "batchlog_manager: make it peering_sharded_service"
- refactored `drain` out of `stop` to abort the replay loop and wait on it.
  - it enters the batchlog manager `_gate` so it can be waited on by stop()
- existing calls to stop() changed to drain()
- stop() is called once using a deferred action in main.

File: main.cc (hunk 6 above)
Comment (bhalevy) [reply main.cc:1285]: fixed in v4
