### PR TITLE
Fix inconsistencies in MV and SI

### LINKED ISSUE #7709: MV/SI: View inconsistencies in base references
The materialized view fix in 4749c58068c063bbe90843e3fc6b712500062493 was not enough. It turns out that there is one more
way for a view to sneak into the schema registry which is a `schema_global_ptr`. Moreover,  there is still a caveat regarding 
an upgrade from versions prior to 4.0 where we didn't have computed columns and the view schemas weren't updated.
All of those circumstances open a room for two things:
1. Bad behaviour while in mixed cluster.
2. Race condition when a view (or a base table) is altered, where for a little while, until the merged schema is actually updated in the database object the view schema exists in the schema registry without any base reference - which leads to an internal error (which was previously segfault).

### PR DESCRIPTION
**Pull request by eliransin**
This series fixes some race conditions in MV/SI schema creation and load, we spotted some places where a schema without
a base table reference can sneak into the registry. This can cause to an unrecoverable error since write commands
with those schemas can't be issued from other nodes. Most of those cases can occur on 2 main and uncommon cases,
in a mixed cluster (during an upgrade) and in a small window after a view or base table altering.

Fixes #7709

### CODE REVIEW

File: database.cc [hunk 1]
```diff
@@ -852,6 +852,11 @@ future<> database::parse_system_tables(distributed<service::storage_proxy>& prox
         return do_parse_schema_tables(proxy, db::schema_tables::VIEWS, [this, &proxy, &mm] (schema_result_value_type &v) {
             return create_views_from_schema_partition(proxy, v.second).then([this, &mm] (std::vector<view_ptr> views) {
                 return parallel_for_each(views.begin(), views.end(), [this, &mm] (auto&& v) {
+                    // we fix here the schema in place in oreder to avoid races (write commands comming from other coordinators).
```
Comment (psarna) [inline database.cc:855]: s/oreder/order

File: database.cc [hunk 2]
```diff
@@ -852,6 +852,11 @@ future<> database::parse_system_tables(distributed<service::storage_proxy>& prox
...
+                    view_ptr fixed_v = maybe_fix_legacy_secondary_index_mv_schema(*this, v, nullptr, preserve_version::yes);
+                    if (fixed_v) {
+                        v = fixed_v;
+                    }
                     return this->add_column_family_and_make_directory(v).then([this, &mm, v] {
                         return maybe_update_legacy_secondary_index_mv_schema(mm.local(), *this, v);
```
Comment (psarna) [inline database.cc:861]: This second call to `maybe_update_legacy_secondary_index_mv_schema` is a little bit excessive now, right? Since it will internally call `maybe_fix_legacy_secondary_index_mv_schema()`, even though it was possibly just fixed above. I think that in here you just need to pass a simple boolean if the view was fixed or not, and if it was, then call:
```cpp
    if (some_variable_which_indicates_that_the_view_was_fixed_a_couple_of_lines_above) {
        return mm.announce_view_update(view_ptr(fixed_v), true);
    }
```

File: db/schema_tables.cc [hunk 3]
```diff
@@ -1208,7 +1208,41 @@ static void merge_tables_and_views(distributed<service::storage_proxy>& proxy,
...
+        if (!base_schema) {
+            for (auto&& s : tables_diff.created) {
+                if (s.get()->ks_name() == vp->ks_name() && s.get()->cf_name() == vp->view_info()->base_name() ) {
+                    base_schema = s;
+                    break;
+                }
+            }
+            if (!base_schema) {
+                base_schema = proxy.local().get_db().local().find_schema(vp->view_info()->base_id());
+            }
```
Comment (psarna) [inline db/schema_tables.cc:1235]: This check is redundant - `maybe_fix_legacy_secondary_index_mv_schema` has an identical check and is already capable of handling nullptr passed as the base schema.

File: db/schema_tables.cc [hunk 4]
```diff
@@ -3033,32 +3067,47 @@ std::vector<sstring> all_table_names(schema_features features) {
...
-        return mm.announce_view_update(view_ptr(builder.build()), true);
+        if (preserve_version) {
+            builder.with_version(v->version());
+        }
+        return view_ptr(builder.build());
+    }
+    return view_ptr(nullptr);
+}
+
+future<> maybe_update_legacy_secondary_index_mv_schema(service::migration_manager& mm, database& db, view_ptr v) {
```
Comment (psarna) [inline db/schema_tables.cc:3104]: Do we actually need this function at all? You seem to only need `maybe_fix_legacy_secondary_index_mv_schema` and `mm.announce_view_update` as I commented above, so this wrapper function can actually be removed.

File: schema_registry.cc [hunk 5]
```diff
@@ -274,39 +275,70 @@ global_schema_ptr::global_schema_ptr(global_schema_ptr&& o) noexcept {
...
     } else {
         // 'e' points to a foreign entry, but we know it won't be evicted
-        // because _ptr is preventing this.
-        const schema_registry_entry& e = *_ptr->registry_entry();
-        schema_ptr s = local_schema_registry().get_or_null(e.version());
-        if (!s) {
-            s = local_schema_registry().get_or_load(e.version(), [&e](table_schema_version) {
-                return e.frozen();
-            });
+        // because _ptr / _base_schema.
```
Comment (psarna) [inline schema_registry.cc:286]: I don't understand the new meaning of this comment - `but we know it won't be evicted because _ptr / _base_schema` seems to be an incomplete sentence. Could you elaborate on what happens here?

File: schema_registry.hh [hunk 6]
```diff
@@ -166,6 +166,7 @@ schema_registry& local_schema_registry();
 class global_schema_ptr {
     schema_ptr _ptr;
     unsigned _cpu_of_origin;
+    schema_ptr _base_schema;
```
Comment (psarna) [inline schema_registry.hh:169]: nitpick: if the order here isn't important (for the sake of some serialization or something like that), then it would look neater to have the two schema_ptr instances next to each other, and _cpu_of_origin as the last attribute.

File: db/schema_tables.cc [hunk 7]
```diff
@@ -1208,7 +1208,41 @@ static void merge_tables_and_views(distributed<service::storage_proxy>& proxy,
         return create_table_from_mutations(proxy, std::move(sm));
     });
     auto views_diff = diff_table_or_view(proxy, std::move(views_before), std::move(views_after), [&] (schema_mutations sm) {
-        return create_view_from_mutations(proxy, std::move(sm));
+        // The view schema mutation should be created with reference to the base table schema because we definetly know it by now.
```
Comment (psarna) [inline db/schema_tables.cc:1211]: s/definetly/definitely

File: db/schema_tables.cc [hunk 8]
```diff
@@ -1208,7 +1208,41 @@ static void merge_tables_and_views(distributed<service::storage_proxy>& proxy,
...
+                    break;
+                }
+            }
+            if (!base_schema) {
+                base_schema = proxy.local().get_db().local().find_schema(vp->view_info()->base_id());
+            }
+        }
+
+        // Now when we have a referenced base - just in case we are registering an old view (this can happen in a mixed cluster)
+        // lets make it write enabled by updateing it's compute columns.
```
Comment (psarna) [inline db/schema_tables.cc:1239]: s/updateing/updating

**Review by psarna — CHANGES_REQUESTED** [review]
I left some comments, but I also only skimmed through the changes related to `global_schema_ptr` - I have no deep understanding of how this thing works, so I hope somebody else is capable of reviewing it.

File: db/schema_tables.cc (hunk 4 above)
Comment (eliransin) [reply db/schema_tables.cc:3104]: I will get rid of the wrapper function, just note here that there will still be a second call to `maybe_fix_legacy_secondary_index_mv_schema` since the in place fix call uses this function with preserve_version::yes and the call in `maybe_update_legacy_secondary_index_mv_schema` calls it in
order to generate a new updated schema. I can still get rid of the wrapper though since it became very simple
now and only used in one place and this is what I will do.

File: db/schema_tables.cc (hunk 3 above)
Comment (eliransin) [reply db/schema_tables.cc:1235]: Will change - thanks.

File: db/schema_tables.cc (hunk 8 above)
Comment (eliransin) [reply db/schema_tables.cc:1239]: Will fix

File: schema_registry.cc (hunk 5 above)
Comment (eliransin) [reply schema_registry.cc:286]: I will change the comment to be more informative. The basic idea behind it is this - one can think that we have a race here. We have an `lw_shared_ptr` dereference (few lines below: `*_base_schema->registry_entry()`) but we 
dereference it from possibly another shard (the whole idea of `get()` is to return a localized schema as if the schema is actually global and can be used from any shard). The reason this specific case is not a race, is that we hold a pointer to the schema in the creating shard and this is valid as long as the global pointer object is alive, so if we got the global_pointer object we know that this dereference is guarantied to succeede.

File: schema_registry.hh (hunk 6 above)
Comment (eliransin) [reply schema_registry.hh:169]: I think it is safe to change it - no specific dependency in the order.

File: database.cc (hunk 2 above)
Comment (eliransin) [reply database.cc:861]: It is not excessive because it creates a different schema (with a new version and not a preserved version). We can still
use the previous call to determine if it is even necessary.
I will change the code to only do the second call if we know for sure the schema needs fixing.

Comment (psarna) [reply database.cc:861]: Isn't it the case that if view_ptr `v` was  eligible for fixing in `maybe_fix_legacy_secondary_index_mv_schema` a couple of lines above, it will also always need to be changed by `maybe_update_legacy_secondary_index_mv_schema`, but the only difference between `fixed_v` and the output of `maybe_update_legacy_secondary_index_mv_schema` would be a new schema version?

Also, could you remind me one more time why we need to preserve the schema version for this short moment, just to create a new one later?

Comment (eliransin) [reply database.cc]: It's not a short moment, this will eventually register in the schema_registry and the other nodes can issue read/write commands on this schema. The schema will be incomplete so we will assert that the base table is not initialized for it or
later on that this schema is not suitable for write.

Comment (psarna) [reply database.cc]: Ok, I think I get it, please confirm - will these two calls result in having two distinct versions of the view schema, one only for requests coming from old nodes, and the new, proper one, which should eventually be used by everyone after the upgrade procedure is over?

Comment (eliransin) [reply database.cc]: Yes - exactly :slightly_smiling_face:

**Comment by eliransin** [comment]
@tgrabiec can you have a look at 50866ac ? This touches `global_schema_ptr` which I believe is your realm :slightly_smiling_face:

File: schema_registry.cc [hunk 9]
```diff
@@ -274,39 +275,73 @@ global_schema_ptr::global_schema_ptr(global_schema_ptr&& o) noexcept {
...
+            return frozen_schema(ptr);
+        });
+    }
+    if (s->is_view()) {
+        if (s->view_info()->base_info()) {
+            _base_schema = global_schema_ptr(s->view_info()->base_info()->base_schema());
+        } else if (ptr->view_info()->base_info()) {
+            _base_schema = global_schema_ptr(ptr->view_info()->base_info()->base_schema());
+        } else {
+            on_internal_error(slogger,"Tried to build a global schema for view with an uninitialized base info");
```
Comment (tgrabiec) [inline schema_registry.cc:340]: The message should include table name. It would help tame production issues if we know this up front.

File: schema_registry.cc [hunk 10]
```diff
@@ -274,39 +275,73 @@ global_schema_ptr::global_schema_ptr(global_schema_ptr&& o) noexcept {
...
+    if (e) {
+        s = ptr;
+    } else {
+        s = local_schema_registry().get_or_load(ptr->version(), [&ptr] (table_schema_version) {
+            return frozen_schema(ptr);
+        });
+    }
+    if (s->is_view()) {
+        if (s->view_info()->base_info()) {
+            _base_schema = global_schema_ptr(s->view_info()->base_info()->base_schema());
```
Comment (tgrabiec) [inline schema_registry.cc:336]: The type of _base_schema is schema_ptr, why do you assign it via global_schema_ptr ?

File: schema_registry.cc [hunk 11]
```diff
@@ -274,39 +275,73 @@ global_schema_ptr::global_schema_ptr(global_schema_ptr&& o) noexcept {
...
+            on_internal_error(slogger,"Tried to build a global schema for view with an uninitialized base info");
         }
-        return local_schema_registry().get_or_load(ptr->version(), [&ptr] (table_schema_version) {
-                return frozen_schema(ptr);
-            });
-        }())
-    , _cpu_of_origin(this_shard_id())
-{ }
+        if (_base_schema) {
+            s->view_info()->set_base_info(s->view_info()->make_base_dependent_view_info(*_base_schema));
```
Comment (tgrabiec) [inline schema_registry.cc:343]: We should do this only in the `if (ptr->view_info()->base_info())` case, in other cases it's not necessary because s already has base info attached.

File: schema_registry.cc [hunk 12]
```diff
@@ -274,39 +275,73 @@ global_schema_ptr::global_schema_ptr(global_schema_ptr&& o) noexcept {
...
+        if (_base_schema) {
+            registered_bs = registered_schema(*_base_schema->registry_entry());
+            if (_base_schema->registry_entry()->is_synced()) {
+                registered_bs->registry_entry()->mark_synced();
+            }
         }
-        if (e.is_synced()) {
+        schema_ptr s = registered_schema(*_ptr->registry_entry());
+        if (s->is_view()) {
+            if (! s->view_info()->base_info()) {
```
Comment (tgrabiec) [inline schema_registry.cc:309]: nit: Superfluous space after !

**Review by tgrabiec — CHANGES_REQUESTED** [review]

File: schema_registry.cc (hunk 10 above)
Comment (eliransin) [reply schema_registry.cc:336]: This is kind of code deduplication, it will run the base schema through this constructor. One of this constructors jobs
is to make sure that the schema pointer has a registry entry, this is what makes it permanent. So instead of using the
same code from lines 322-332 I just ran it through the constructor. But now that you mention it, I will deduplicate it
differently using a lambda.

File: schema_registry.cc (hunk 9 above)
Comment (eliransin) [reply schema_registry.cc:340]: will fix.

File: schema_registry.cc (hunk 11 above)
Comment (eliransin) [reply schema_registry.cc:343]: I can (and will) refine the condition here but it is not exactly what you wrote. The info is always attached the real
question is if this info has registry entry or not. A global view table which has a non registered schema as its base is useless.
It is true that if all other code paths are covered your condition and what I wrote above converges since a view schema is in the registry iff its base table is in the registry.
To be honest I prefer have here the additional (refined) safety check because I am not confident that all other paths into the registry conform to this invariant.

**Comment by eliransin** [comment]
@tgrabiec ping

**Comment by eliransin** [comment]
@tgrabiec just making sure you didn't forget about me :slightly_smiling_face:

**Comment by eliransin** [comment]
@tgrabiec pinging here to get back into your backlog which I guess is pretty big right now :slightly_smiling_face:

**Comment by eliransin** [comment]
Rebased to latest master.
@tgrabiec can you please review commit c0e2690 ? This is a change to global ptr that will force globalization of a view base table along with the view itself and that way ensure consistency between the two.

File: schema_registry.cc [hunk 13]
```diff
@@ -274,39 +275,77 @@ global_schema_ptr::global_schema_ptr(global_schema_ptr&& o) noexcept {
...
+
+        schema_ptr registered_bs;
+        // the following code contains registry entry dereference of a foreign shard
+        // however, it is guarantied to succeed since we made sure in the constructor
+        // that _bs_schema and _ptr will have a registry on the foreign shard where this
+        // object originated so as long as this object lives the registry entries lives too
+        // and it is safe to reference them on foreign shards.
+        if (_base_schema) {
+            registered_bs = registered_schema(*_base_schema->registry_entry());
+            if (_base_schema->registry_entry()->is_synced()) {
```
Comment (tgrabiec) [inline schema_registry.cc:303]: You could move this is_synced() logic under registered_schema().

**Review by tgrabiec — APPROVED** [review]

File: schema_registry.cc (hunk 13 above)
Comment (eliransin) [reply schema_registry.cc:303]: Right, will do it on a follow up.
Thanks

**Comment by eliransin** [comment]
@psarna we need to put this on hold since it used announce locally which is now deprecated.
I will need to think of a better way to do it, the leading idea is to add a feature to the feature service that
will indicate a joining node if all other nodes supports it version (mixed cluster indication). Then I will be able to amend
this accordingly. Another option is to give up on this code completely until the oldest supported version has computed columns,
and then adding this code again which and than wait for another 3 versions to come out and loose it. I am not in favor of this of course but it is an option.

File: database.cc [hunk 14]
```diff
@@ -847,11 +847,17 @@ future<> database::parse_system_tables(distributed<service::storage_proxy>& prox
...
+                    view_ptr v_to_add = view_needs_fixing ? fixed_v : v;
+                    return this->add_column_family_and_make_directory(v_to_add).then([this, &mm, v, view_needs_fixing] {
                         // TODO: Remove once computed columns are guaranteed to be featured in the whole cluster.
-                        view_ptr fixed_v = maybe_fix_legacy_secondary_index_mv_schema(*this, v, nullptr, preserve_version::no);
-                        if (fixed_v) {
-                            return mm.local().announce_view_update(view_ptr(fixed_v), true);
+                        if (view_needs_fixing && _feat.cluster_schema_features().contains(schema_feature::COMPUTED_COLUMNS)) {
+                            // now really fix the view by creating a new and updated version.
+                            view_ptr fixed_v = maybe_fix_legacy_secondary_index_mv_schema(*this, v, nullptr, preserve_version::no);
+                            return mm.local().announce_view_update(view_ptr(fixed_v));
```
Comment (eliransin) [inline database.cc:860]: @psarna this is the main difference from the previous round of review

**Comment by eliransin** [comment]
OK @psarna we are good to go :slightly_smiling_face: 
The main difference from the previous version is that instead of using `announce` with the `locally` flag which was removed,
I used schema features to determine when we can announce it globally.
I pinged you on the relevant lines but this is a pretty short set. Also, we have tomek's blessing on the `global_shcema_ptr`
part.

**Review by psarna — APPROVED** [review]
