### PR TITLE
counters: Fix filtering of counters

### LINKED ISSUE #5635: Filtering on counter columns doesn't work (works in Cassandra 3.0)
A user reported on stack-overflow https://stackoverflow.com/questions/59859080/filter-condition-not-working-on-counter-columns-in-scylladb-where-it-works-in-ca:

> Filter condition not working on counter columns in ScyllaDB where it works in Cassandra 3.0
>
> I have a use case where I am using filters on counter columns in cassandra. Now I am migrating to Scylla, and I see that scylla won't support counter column filters.

### PR DESCRIPTION
**Pull request by jul-stas**
Queries with `ALLOW FILTERING` and constraints on counter values used to be rejected as "unimplemented". The reason was a missing tri-comparator, which is added in this patch.

Fixes #5635

### CODE REVIEW

File: types.cc [hunk 1]
```diff
@@ -1985,8 +1985,15 @@ struct compare_visitor {
     int32_t operator()(const empty_type_impl&) { return 0; }
     int32_t operator()(const tuple_type_impl& t) { return compare_aux(t, v1, v2); }
     int32_t operator()(const counter_type_impl&) {
-        fail(unimplemented::cause::COUNTERS);
-        return 0;
+        if (v1.empty()) {
```
Comment (haaawk) [inline types.cc:1988]: What does empty value mean? Is it deleted counter or is it counter before the first operation? The second would mean empty value == 0.

File: test/cql/counters_test.cql [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+UPDATE ks.tbl_cnt SET c = c+3 WHERE pk = 3;
+UPDATE ks.tbl_cnt SET c = c+4 WHERE pk = 4;
+
+-- test various filtering options on counter column
+SELECT pk, c FROM ks.tbl_cnt WHERE c < 3 ALLOW FILTERING;
+SELECT pk, c FROM ks.tbl_cnt WHERE c <= 3 ALLOW FILTERING;
+SELECT pk, c FROM ks.tbl_cnt WHERE c > 2 AND pk = 4 ALLOW FILTERING;
+SELECT pk, c FROM ks.tbl_cnt WHERE c >= 3 and pk = 3 ALLOW FILTERING;
+SELECT pk, c FROM ks.tbl_cnt WHERE c in (2,3) ALLOW FILTERING;
+SELECT pk, c FROM ks.tbl_cnt WHERE c = 0 ALLOW FILTERING;
```
Comment (haaawk) [inline test/cql/counters_test.cql:15]: This is an unsuccessful case for counter = <value>. Could you also add a successful case like c=1, please?
I think it would be also interesting to see:
SELECT pk, c FROM ks.tbl_cnt WHERE c in (-1,0,4,5) ALLOW FILTERING;
SELECT pk, c FROM ks.tbl_cnt WHERE c > 4 ALLOW FILTERING;
SELECT pk, c FROM ks.tbl_cnt WHERE c < 1 ALLOW FILTERING;

Comment (haaawk) [reply test/cql/counters_test.cql:15]: There are two special cases I would love to see in test as well:
1. Uninitialized counter so you probably need to INSERT INTO ks.tbl_cnt(pk) VALUES(5) I think a value of such counter should be 0 so SELECT pk, c FROM ks.tbl_cnt WHERE c = 0 ALLOW FILTERING; should return it and 
SELECT pk, c FROM ks.tbl_cnt WHERE c >= 1 ALLOW FILTERING; should not.
2. Deleted counter. It should not show up at all. This is probably handled by other code than restriction but let's have a test just to be sure.

**Comment by haaawk** [comment]
LGTM in general. I have just one question and request for some additional test cases. Thanks.

File: types.cc (hunk 1 above)
Comment (jul-stas) [reply types.cc:1988]: Good catch. Deleted counters do not get into this comparison (they are excluded on higher level). But uninitialized ones do - even for non-counter types. That's why e.g. ints also suffer from empty values:
```
cqlsh> CREATE TABLE ks.tbl_int2 (pk int primary key, i1 int, i2 int);
cqlsh> INSERT INTO ks.tbl_int2 (pk, i1) VALUES (0, 0);
cqlsh> SELECT * FROM ks.tbl_int2 WHERE i2 < -999 ALLOW FILTERING;

 pk | i1 | i2
----+----+------
  0 |  0 | null

(1 rows)
```
My thinking is that uninitialized values should never get that deep.

Comment (haaawk) [reply types.cc:1988]: You're probably right. For counters fix would be easy (uninitialized == 0) but for ints it's not that easy. We probably should fix this in the upper layer. But it might be easier to treat empty for counters as 0 in this PR and merge it and fix the null thing in separate PR.

Comment (avikivity) [reply types.cc:1988]: Uninitialized int is NULL, not zero. NULL doesn't equal anything.

For counters, it is reasonable to use 0 for an uninitialized counter (there is no way to initialize a counter).

Comment (avikivity) [reply types.cc:1988]: What does Cassanra do? e.g. for a table with two counter columns, perform an update that increments just one of them.

**Comment by haaawk** [comment]
@avikivity @psarna could any of you merge this in, please?

File: types.cc (hunk 1 above)
Comment (jul-stas) [reply types.cc]: @avikivity Tested on C* 3.11:
- untouched counter doesn't equal anything;
- deleted counter doesn't equal anything.

I just updated this patch so Scylla treats untouched counters as zeros (and deleted ones as NULLs). Such a compatibility breach makes sense to me too, but we need a definitive opinion if it's OK.

File: test/cql/counters_test.cql (hunk 2 above)
Comment (jul-stas) [reply test/cql/counters_test.cql]: Done!

**Comment by psarna** [comment]
Looks good. Also, looks like the effort of adding all these `if (counters) { throw unimplemented }` checks was bigger than providing an actual implementation (:

**Comment by psarna** [comment]
I queued it as c32faee657abddd2fef2057497a938885bbf80a8. It's debatable whether we should diverge from Cassandra's treatment of uninitialized counters, but our way seems to make more sense.
