### PR TITLE
Alternator: support nested attribute paths in all expressions

### LINKED ISSUE #5024: Alternator: support attribute paths (direct access inside nested attributes)
While Alternator does currently fully support nested documents as an attribute value - e.g., set an attribute `a` to an entire document and then retrieve this document (see `test_nested.py`) - we don't currently support direct access to specific **paths** inside these documents, e.g., `UpdateExpression` modifying just `a.b[3].c` without touching the other content of `a`, or `ProjectionExpression` in `GetItem` asking to return only the value of `a.b[3].c` and not the entire a.

We have many xfailing tests reproducing various aspects of this missing feature:
* In **test_update_expression.py**: `test_update_expression_multi_overlap_nested`, `test_update_expression_nested_attribute_dot`, `test_update_expression_nested_attribute_index`, `test_update_expression_nested_different_type`, `test_update_expression_nested_deep`, `test_update_expression_nested_remove`, `test_nested_attribute_update_array_out_of_bounds`, `test_nested_attribute_update_bad_path_dot`, `test_nested_attribute_update_bad_path_array`.
* In **test_projection_expression.py**: `test_projection_expression_path`, `test_projection_expression_path_references`, `test_projection_expression_path_dot`, `test_projection_expression_path_overlap`, `test_query_projection_expression_path`, `test_scan_projection_expression_path`, `test_batch_get_item_projection_expression_path`.
* In **test_returnvalues.py**: `test_update_item_returnvalues_nested`
* In **test_condition_expression.py**: `test_update_condition_nested_attributes`, `test_update_condition_nested_attribute_reference`
* In **test_filter_expression.py**, `test_filter_expression_nested_attribute`, `test_filter_expression_and_projection_expression_nested`.

There are no major hurdles expected to implement this feature. Because Alternator stores top-level attributes as blobs, a read request will need to read the full top-level attribute and then extract from it just the desired part, and a write request (e.g., "`SET a.b = :val`") needs to be implemented as a read-modify-write operation: It needs to read the entire top-level attribute `a`, modify just `a.b` in it, and then write back the entire `a`. We already know how to do such read-modify-write operations safely (via LWT) so this is fine.

### LINKED ISSUE #8043: Alternator: unexpected ValidationException in ConditionExpression and FilterExpression
The functions `check_compare()` and `check_BETWEEN()` (in `conditions.cc`) were originally written to implement the older syntax of conditional updates: `Expected`. In that syntax, a condition has two operands - the first operand is always the value of an item's attribute and the second is always comes from the query (from the `Expected` parameter). 

Because the second operand comes from the query, an error in this operand was considered by those functions a validation error (`ValidationException`, a.k.a. `api_error::validation`). For example if the second parameter of `check_compare()` is not a number, string or blob, then it cannot be compared and the function results in a validation exception, not simply a false comparison and no update. This is what `Expected` wants. For example, the call

```
        test_table_s.update_item(Key={'p': p},  AttributeUpdates={'z': {'Value': 17, 'Action': 'PUT'}},
            Expected={'a': {'ComparisonOperator': 'LE',  'AttributeValueList': [[1,2,3]]}}
``` 

should fail with a `ValidationException`, because the **query** is invalid - it tries to use a list as an operand to `LE`, and that is invalid, and indeed Alternator's implementation that calls `check_compare()`, does this correctly.

However, unfortunately, the same cannot be said for a the newer syntax of conditional updates - `ConditionExpression`. In a `ConditionExpression`, the condition may look like `a < b`, which compares two attributes from an item - neither side comes from the query. So if either side has the wrong type, it should be considered a false comparison (`ConditionalCheckFailedException`) - not an error in the query (`ValidationException`). However, the condition can also look like `a < :val` or `:val < b`, which does have a constant from the query - and in those cases we do need return a `ValidationException`!

Although the difference between a `ConditionalCheckFailedException` (false condition) and `ValidationException` (error in query) seems minor, it really isn't for client code. The difference is even more serious for a `FilterExpression` which uses the same comparison functions: In a `FilterExpression` an item which has (in the above example) a list value for an attribute can cause the entire scan to abort with a `ValidationException`, instead of simply skipping this item as a non-match as expected.

We should write tests for all the cases described above, and fix them.

We should probably move all the `ValidationException` errors out of `check_compare()` and `check_BETWEEN()` (returning false, instead), and instead do those checks in the caller of these functions, which knows which of the two arguments came from the query (should be checked and `ValidationException` thrown), and which came from the item (so should not).

The BEGINS_WITH operator has a similar problem which we knew about, but this caused us to duplicate the begins_with code. We should fix it the same way we will fix the other comparison operators - without code duplication.

### PR DESCRIPTION
**Pull request by nyh**
This series fixes #5024 - which is about adding support for nested attribute paths (e.g., a.b.c[2]) to Alternator.
The series adds complete support for this feature in ProjectionExpression, ConditionExpression, FilterExpression and UpdateExpression - and also its combination with ReturnValues. Many relevant tests - and also some new tests added in this series - now pass.

The first patch in the series fixes #8043 a bug in some error cases in conditions, which was discovered while working in this series, and is conceptually separate from the rest of the series.

### CODE REVIEW

**Comment by psarna** [comment]
Before diving into the actual review, I have a question about the description:

> After this series, just two small problems are known to remain with nested attribute path support, and should be fixed later:
> 
>     1. The combination of UpdateExpression and ReturnValues returns the wrong results when nested attributes are modified. So the test case `test_returnvalues.py::test_update_item_returnvalues_nested` still xfails.

Do I understand this sentence correctly that the test used to fail with an error returned to the client due to nested attributes being modified, but now it actually returns result which are wrong? If that's the case, then it's a bug and we should instead return an error saying that this combination is not implemented properly yet. Also, perhaps the xfail message in `test_update_item_returnvalues_nested` should be updated to specifically mention that only this part is not implemented, because right now it suggests that nested attributes are not implemented at all.

**Comment by psarna** [comment]
I ran the test on both source trees and it indeed looks like this combination used to return an error and now returns wrong results.

**Comment by nyh** [comment]
@psarna you're right, this scenario now returns wrong results (they are "wrong" in the sense that too much data is returned - not that the data is really wrong. But it differs from what DynamoDB says the results should be). There are two ways to fix this: One is indeed what you said - generate an error on the combination of UpdateExpression with nested attributes and ReturnValues. I can easily do it. Of course the other way is to just fix the wrong results :-) I just got tired of this series never ending :-)
Anyway, I'll wait for your other review comments (feel free to take your time), and then I'll do one of these two things. You're right that it's not a great idea to leave it with incorrect results - no matter how esoteric this use case is.

File: alternator/executor.hh [hunk 1]
```diff
@@ -70,6 +70,76 @@ public:
...
+    // doesn't work with incomplete types :-( We couldn't use lw_shared_ptr<>
+    // because it doesn't work for incomplete types either. We couldn't use
+    // std::unique_ptr<> because it makes the entire object uncopyable. We
+    // don't often need to copy such a map, but we do have some code that
+    // copies an attrs_to_get object, and is hard to find and remove.
+    // The shared_ptr should never be null.
+    using members_t =  std::unordered_map<std::string, seastar::shared_ptr<attribute_path_map_node<T>>>;
+    // The indexes list is sorted because DynamoDB requires handling writes
+    // beyond the end of a list in index order.
+    using indexes_t = std::map<unsigned, seastar::shared_ptr<attribute_path_map_node<T>>>;
```
Comment (psarna) [inline alternator/executor.hh:118]: Question: does DynamoDB allow arrays with holes - e.g. there's data at index 0, then nothing, and then data at index 99999999999? I'm just trying to understand why it's a map, and not a vector or deque - perhaps it was just easier to implement that way?

Comment (psarna) [reply alternator/executor.hh:118]: Or can we perhaps have really long arrays, in which case it's better to split it and avoid continuous allocations?

File: alternator/expressions.cc [hunk 2]
```diff
@@ -667,6 +666,55 @@ std::unordered_map<std::string_view, function_handler_type*> function_handlers {
...
+    const rjson::value* v = rjson::find(*item, p.root());
+    if (!v) {
+        return rjson::null_value();
+    }
+    for (const auto& op : p.operators()) {
+        if (!v->IsObject() || v->MemberCount() != 1) {
+            // This shouldn't happen. We shouldn't have stored malformed
+            // objects. But today Alternator does not validate the structure
+            // of nested documents before storing them, so this can happen on
+            // read.
```
Comment (psarna) [inline alternator/expressions.cc:690]: A workaround for the client would simply be to delete the item by its key once this error occurs, right?

File: alternator/executor.hh (hunk 1 above)
Comment (nyh) [reply alternator/executor.hh:118]: ‎Maybe my comments are not clear enough, but in attribute_path_map we don't store the actual items - we store an (hierarchical) list of attribute paths (and values - hence a "map") - which are listed on ProjectionExpression or UpdateExpression. You're right that the item itself has an actual list, with no holes, but someone can pass `ProjectionExpression="a[1], a[7]" and that's the information we store in that map - that the user asked just for items 1 and 7.

I don't expect these maps to be long - they just contain a parsed version of the UpdateExpression or ProjectionExpression. But even if they are long, they shouldn't be contiguous - I don't think std::map is contiguous.
By the way, if you're curious why I used std::map and not std::unordered_map for the indexes, well, it's because of a corner case of what we have to do if the indexes in the UpdateExpression are beyond the end of the array, in which commands like a[1000]=2 or a[2000]=3 just mean add to the end of the array - but in this order (first the 1000 then the 2000).

File: alternator/expressions.cc (hunk 2 above)
Comment (nyh) [reply alternator/expressions.cc:690]: Yes. What we really need to do at some point (unrelated to this issue) is to add some sort of validation that the JSON we insert into an attribute is valid. We do validate that it's legal JSON (we parse that JSON...) but not that it's legal DynamoDB-serialized format. If we do this during write, we won't need to do it during read.

File: alternator/executor.hh (hunk 1 above)
Comment (psarna) [reply alternator/executor.hh:118]: Ah, alright, makes sense

**Review by psarna — COMMENTED** [review]
The code looks good aside from my previous comment about the ReturnValues issue, I'm yet to review the test cases.

File: alternator/expressions.cc (hunk 2 above)
Comment (nyh) [reply alternator/expressions.cc:690]: Created https://github.com/scylladb/scylla/issues/8070 - but I'm not planning to do that right now.

File: test/alternator/test_update_expression.py [hunk 3]
```diff
@@ -265,16 +265,64 @@ def test_update_expression_multi_overlap(test_table_s):
...
-    with pytest.raises(ClientError, match='ValidationException.*overlap'):
-        test_table_s.update_item(Key={'p': p}, UpdateExpression='SET a = :val1, a.b = :val2',
-            ExpressionAttributeValues={':val1': {'b': 7}, ':val2': 'there'})
-    test_table_s.put_item(Item={'p': p, 'a': {'b': {'c': 2}}})
-    with pytest.raises(ClientError, match='ValidationException.*overlap'):
-        test_table_s.update_item(Key={'p': p}, UpdateExpression='SET a.b = :val1, a.b.c = :val2',
-            ExpressionAttributeValues={':val1': 'hi', ':val2': 'there'})
+    # Note that the overlap checks happen before checking the actual content
+    # of the item, so it doesn't matter that the item we want to modify
+    # doen't even exist or have the structure referenced by the paths below.
```
Comment (psarna) [inline test/alternator/test_update_expression.py:272]: micronitpick: s/doen't/doesn't

**Review by psarna — COMMENTED** [review]
Looks good.
