### PR TITLE
test: random_schema::make_ckeys: fix inifinte loop

### LINKED ISSUE #5161: test_compaction_data_stream_split: Reactor stalled for 2737328 ms on shard 0
Seen in [next/1236](https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/1236/consoleText)
Scylla version 64c2d28a7f8fa6ae3d591a57af8a656bcefcbdfc
```
[2019-10-09T12:45:34.336Z] Output of the failed tests:
[2019-10-09T12:45:34.336Z] Test build/debug/tests/mutation_test --report_level=no --logger=HRF,test_suite:XML,test_suite,jenkins_test.debug.mutation_test.boost.xml -- -c2 -m2G --overprovisioned --unsafe-bypass-fsync 1 --blocked-reactor-notify-ms 2000000 --collectd 0 failed:
[2019-10-09T12:45:34.336Z]   timed out
...
[2019-10-09T12:45:34.336Z] random-seed=238675597
...
[2019-10-09T12:45:34.371Z] ESC[0;39;49mESC[1;34;49mtests/mutation_test.cc(0): Entering test case "test_compaction_data_stream_split"
[2019-10-09T12:45:34.371Z] Reactor stalled for 2737328 ms on shard 0.
[2019-10-09T12:45:34.371Z] Backtrace:
[2019-10-09T12:45:34.371Z]   /lib64/libasan.so.5+0x000000000006ce7f
[2019-10-09T12:45:34.371Z]   0x0000000009300fbc
[2019-10-09T12:45:34.371Z]   0x00000000092d4e96
[2019-10-09T12:45:34.371Z]   0x000000000905f8ee
[2019-10-09T12:45:34.371Z]   0x0000000009072aba
[2019-10-09T12:45:34.371Z]   0x000000000906f42a
[2019-10-09T12:45:34.371Z]   0x000000000906f594
[2019-10-09T12:45:34.371Z]   0x0000000009072656
[2019-10-09T12:45:34.371Z]   0x00007fdad0122e7f
[2019-10-09T12:45:34.371Z]   0x000000000087ab89
[2019-10-09T12:45:34.371Z]   0x0000000000833ad2
[2019-10-09T12:45:34.371Z]   0x00000000087729c8
[2019-10-09T12:45:34.371Z]   0x00000000087665c8
[2019-10-09T12:45:34.371Z]   0x000000000870d57e
[2019-10-09T12:45:34.371Z]   0x00000000087808a1
[2019-10-09T12:45:34.371Z]   0x0000000008763b1d
[2019-10-09T12:45:34.371Z]   0x0000000008710787
[2019-10-09T12:45:34.371Z]   0x000000000872155a
[2019-10-09T12:45:34.371Z]   0x0000000008721bae
[2019-10-09T12:45:34.371Z]   0x000000000872506e
[2019-10-09T12:45:34.371Z]   0x0000000008729526
[2019-10-09T12:45:34.371Z]   0x0000000008745f04
[2019-10-09T12:45:34.371Z]   0x0000000008737243
[2019-10-09T12:45:34.371Z]   0x0000000008737f5a
[2019-10-09T12:45:34.371Z]   0x0000000008737bbe
[2019-10-09T12:45:34.371Z]   0x000000000874eb64
[2019-10-09T12:45:34.371Z]   0x000000000874ec43
[2019-10-09T12:45:34.371Z]   0x000000000874ed9c
[2019-10-09T12:45:34.371Z]   0x0000000008746147
[2019-10-09T12:45:34.371Z]   0x000000000875409b
[2019-10-09T12:45:34.371Z]   0x000000000084c5f1
[2019-10-09T12:45:34.371Z]   0x00000000008096b8
[2019-10-09T12:45:34.371Z]   0x0000000000809797
[2019-10-09T12:45:34.371Z]   0x00000000008098f0
[2019-10-09T12:45:34.371Z]   0x00000000007b0dab
[2019-10-09T12:45:34.371Z]   0x00000000009bcd56
[2019-10-09T12:45:34.371Z]   0x00000000090c43c4
[2019-10-09T12:45:34.371Z]   0x00000000090c84d9
[2019-10-09T12:45:34.371Z]   0x00000000090cd777
[2019-10-09T12:45:34.371Z]   0x0000000009ed141a
[2019-10-09T12:45:34.371Z]   0x0000000009eaa0f6
[2019-10-09T12:45:34.371Z]   0x0000000009eb3770
[2019-10-09T12:45:34.371Z]   0x0000000002a444b4
[2019-10-09T12:45:34.371Z]   0x0000000009de446e
[2019-10-09T12:45:34.371Z]   /lib64/libpthread.so.0+0x00000000000085a1
[2019-10-09T12:45:34.371Z]   /lib64/libc.so.6+0x00000000000fb302
```

```
ZSTD_compressBlock_fast_dictMatchState_generic at /local/home/bhalevy/dev/scylla/zstd/lib/compress/zstd_fast.c:315
 (inlined by) ZSTD_compressBlock_fast_dictMatchState at /local/home/bhalevy/dev/scylla/zstd/lib/compress/zstd_fast.c:360
std::tr1::_Tuple_impl<0, cassandra::CassandraAsyncProcessor*, std::tr1::function<void (bool)>, int, apache::thrift::protocol::TProtocol*, void*, std::tr1::_Placeholder<1> >::_Tuple_impl(std::tr1::_Tuple_impl<0, cassandra::CassandraAsyncProcessor*, std::tr1::function<void (bool)>, int, apache::thrift::protocol::TProtocol*, void*, std::tr1::_Placeholder<1> > const&) at /usr/include/c++/8/tr1/tuple:109
cassandra::CassandraClient::send_execute_cql3_query(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cassandra::Compression::type, cassandra::ConsistencyLevel::type) at /local/home/bhalevy/dev/scylla/build/debug/gen/Cassandra.cpp:15749
cassandra::CassandraProcessor::process_get(int, apache::thrift::protocol::TProtocol*, apache::thrift::protocol::TProtocol*, void*) at /local/home/bhalevy/dev/scylla/build/debug/gen/Cassandra.cpp:16324 (discriminator 1)
cassandra::CassandraProcessor::process_set_keyspace(int, apache::thrift::protocol::TProtocol*, apache::thrift::protocol::TProtocol*, void*) at /local/home/bhalevy/dev/scylla/build/debug/gen/Cassandra.cpp:16255
cassandra::CassandraProcessor::process_set_keyspace(int, apache::thrift::protocol::TProtocol*, apache::thrift::protocol::TProtocol*, void*) at /local/home/bhalevy/dev/scylla/build/debug/gen/Cassandra.cpp:16258 (discriminator 4)
cassandra::CassandraProcessor::process_get(int, apache::thrift::protocol::TProtocol*, apache::thrift::protocol::TProtocol*, void*) at /local/home/bhalevy/dev/scylla/build/debug/gen/Cassandra.cpp:16315
?? ??:0
std::_Rb_tree<int, std::pair<int const, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > >, std::_Select1st<std::pair<int const, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > >, std::less<int>, std::allocator<std::pair<int const, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > > >::begin() at /usr/include/c++/8/bits/stl_tree.h:976
seastar::future<>::then<seastar::async<test_row_size_is_immune_to_application_order::run_test_case()::{lambda()#1}>(seastar::thread_attributes, std::decay&&, (std::decay<test_row_size_is_immune_to_application_order::run_test_case()::{lambda()#1}>::type&&)...)::{lambda(seastar::async<{lambda()#1}>(seastar::futurize<std::result_of<std::decay<auto:1>::type ()>::type>::type, seastar::thread_attributes, std::decay<auto:1>::type&&)::work&)#1}::operator()(seastar::async<{lambda()#1}>(seastar::futurize<std::result_of<std::decay<{lambda()#1}>::type ()>::type>::type, seastar::thread_attributes, std::decay<{lambda()#1}>::type&&)::work)::{lambda()#2}, seastar::future<> >(seastar::thread_attributes)::{lambda()#1}::then({lambda()#2}&&) at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/future.hh:1052
std::unique_ptr<seastar::smp_message_queue::async_work_item<seastar::sharded<db::view::view_builder>::stop()::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}>, std::default_delete<{lambda()#1}> >::unique_ptr<seastar::smp_message_queue::async_work_item<seastar::sharded<db::view::view_builder>::stop()::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}>, void>({lambda()#1}*) at /usr/include/c++/8/bits/unique_ptr.h:205
seastar::smp_message_queue::async_work_item<seastar::sharded<cql3::query_processor>::stop()::{lambda()#2}::operator()() const::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::async_work_item(seastar::smp_message_queue&, seastar::smp_service_group, {lambda(unsigned int)#1}&&) at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/reactor.hh:287
seastar::smp_message_queue::async_work_item<seastar::sharded<gms::feature_service>::stop()::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}>::get_future() at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/reactor.hh:316
seastar::noncopyable_function<seastar::future<> (seastar::future<>)>::direct_vtable_for<seastar::future<>::then_wrapped<seastar::future<>::finally_body<seastar::smp::submit_to<seastar::sharded<seastar::abort_source>::stop()::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}>(unsigned int, seastar::smp_service_group, seastar::futurize&&)::{lambda()#1}, false>, seastar::future<> >(seastar::futurize<std::result_of<seastar::future<>::finally_body<seastar::smp::submit_to<seastar::sharded<seastar::abort_source>::stop()::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}>(unsigned int, seastar::smp_service_group, seastar::futurize&&)::{lambda()#1}, false> ()>::type>::type)::{lambda(seastar::future<>)#1}>::call(seastar::noncopyable_function<seastar::future<> (seastar::future<>)> const*, seastar::future<>) at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/future.hh:933
 (inlined by) seastar::noncopyable_function<seastar::future<> (seastar::future<>)>::direct_vtable_for<seastar::future<>::then_wrapped<seastar::future<>::finally_body<seastar::smp::submit_to<seastar::sharded<seastar::abort_source>::stop()::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}>(unsigned int, seastar::smp_service_group, seastar::futurize&&)::{lambda()#1}, false>, seastar::future<> >(seastar::futurize<std::result_of<seastar::future<>::finally_body<seastar::smp::submit_to<seastar::sharded<seastar::abort_source>::stop()::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}>(unsigned int, seastar::smp_service_group, seastar::futurize&&)::{lambda()#1}, false> ()>::type>::type)::{lambda(seastar::future<>)#1}>::call(seastar::noncopyable_function<seastar::future<> (seastar::future<>)> const*, seastar::future<>) at /local/home/bhalevy/dev/scylla/seastar/include/seastar/util/noncopyable_function.hh:71
seastar::smp_message_queue::async_work_item<seastar::sharded<cql3::query_processor>::start<std::reference_wrapper<seastar::sharded<service::storage_proxy> >, std::reference_wrapper<seastar::sharded<database> >, cql3::query_processor::memory_config&>(std::reference_wrapper<seastar::sharded<service::storage_proxy> >&&, std::reference_wrapper<seastar::sharded<database> >&&, cql3::query_processor::memory_config&)::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}>::async_work_item(seastar::smp_message_queue&, seastar::smp_service_group, {lambda(unsigned int)#1}&&) at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/reactor.hh:287
std::__uniq_ptr_impl<seastar::sharded<cql3::cql_config>::stop()::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}, std::default_delete<{lambda(unsigned int)#1}> >::_M_ptr() at /usr/include/c++/8/bits/unique_ptr.h:149
std::_Bind<std::_Mem_fn<void (seastar::sharded<service::migration_manager>::*)()> (seastar::sharded<service::migration_manager>*)>::_Bind(std::_Bind<std::_Mem_fn<void (seastar::sharded<service::migration_manager>::*)()> (seastar::sharded<service::migration_manager>*)>&&) at /usr/include/c++/8/functional:473
seastar::future<> seastar::do_void_futurize_helper<void>::apply<seastar::sharded<service::migration_manager>::start<>()::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}&>(seastar::sharded<service::migration_manager>::start<>()::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}&) at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/future.hh:1459
std::allocator_traits<std::allocator<seastar::sharded<cql3::query_processor>::entry> >::max_size(std::allocator<seastar::sharded<cql3::query_processor>::entry> const&) at /usr/include/c++/8/bits/alloc_traits.h:496
seastar::sharded<db::batchlog_manager>::entry* std::__uninitialized_copy_a<std::move_iterator<seastar::sharded<db::batchlog_manager>::entry*>, seastar::sharded<db::batchlog_manager>::entry*, seastar::sharded<db::batchlog_manager>::entry>(std::move_iterator<seastar::sharded<db::batchlog_manager>::entry*>, std::move_iterator<seastar::sharded<db::batchlog_manager>::entry*>, seastar::sharded<db::batchlog_manager>::entry*, std::allocator<seastar::sharded<db::batchlog_manager>::entry>&) at /usr/include/c++/8/bits/stl_uninitialized.h:287
seastar::future<>::finally_body<locator::i_endpoint_snitch::create_snitch<>(seastar::basic_sstring<char, unsigned int, 15u, true> const&)::{lambda()#1}::operator()() const::{lambda(std::__exception_ptr::exception_ptr)#2}::operator()(std::__exception_ptr) const::{lambda()#1}, true>::operator()(seastar::future<>&&)::{lambda(auto:1)#1}::finally_body(seastar::future<>::finally_body<locator::i_endpoint_snitch::create_snitch<>(seastar::basic_sstring<char, unsigned int, 15u, true> const&)::{lambda()#1}::operator()() const::{lambda(std::__exception_ptr::exception_ptr)#2}::operator()(std::__exception_ptr) const::{lambda()#1}, true>&&) at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/future.hh:327
 (inlined by) ?? at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/future.hh:933
 (inlined by) seastar::future<>::finally_body<locator::i_endpoint_snitch::create_snitch<>(seastar::basic_sstring<char, unsigned int, 15u, true> const&)::{lambda()#1}::operator()() const::{lambda(std::__exception_ptr::exception_ptr)#2}::operator()(std::__exception_ptr) const::{lambda()#1}, true>::operator()(seastar::future<>&&)::{lambda(auto:1)#1}::finally_body(seastar::future<>::finally_body<locator::i_endpoint_snitch::create_snitch<>(seastar::basic_sstring<char, unsigned int, 15u, true> const&)::{lambda()#1}::operator()() const::{lambda(std::__exception_ptr::exception_ptr)#2}::operator()(std::__exception_ptr) const::{lambda()#1}, true>&&) at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/future.hh:1218
std::_MakeUniq<seastar::smp_message_queue::async_work_item<seastar::sharded<db::view::view_builder>::stop()::{lambda()#2}::operator()() const::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}> >::__single_object std::make_unique<seastar::smp_message_queue::async_work_item<seastar::sharded<db::view::view_builder>::stop()::{lambda()#2}::operator()() const::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>, seastar::smp_message_queue&, seastar::smp_service_group&, {lambda(unsigned int)#1}>(seastar::smp_message_queue&, seastar::smp_service_group&, {lambda(unsigned int)#1}&&) at /usr/include/c++/8/bits/unique_ptr.h:830
seastar::noncopyable_function<seastar::future<> ()>::direct_vtable_for<seastar::future<>::then<seastar::sharded<db::view::view_builder>::stop()::{lambda()#3}, seastar::future<> >(seastar::sharded<db::view::view_builder>::stop()::{lambda()#3}&&)::{lambda()#1}>::access(seastar::noncopyable_function<seastar::future<> ()>*) at /local/home/bhalevy/dev/scylla/seastar/include/seastar/util/noncopyable_function.hh:68
std::_Vector_base<seastar::sharded<db::view::view_builder>::entry, std::allocator<seastar::sharded<db::view::view_builder>::entry> >::_Vector_base(std::allocator<seastar::sharded<db::view::view_builder>::entry> const&) at /usr/include/c++/8/bits/stl_vector.h:252
seastar::smp_message_queue::async_work_item<seastar::sharded<gms::feature_service>::stop()::{lambda()#2}::operator()() const::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::async_work_item(seastar::smp_message_queue&, seastar::smp_service_group, {lambda(unsigned int)#1}&&) at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/reactor.hh:287
seastar::smp_message_queue::async_work_item<seastar::sharded<gms::feature_service>::stop()::{lambda()#2}::operator()() const::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::async_work_item(seastar::smp_message_queue&, seastar::smp_service_group, {lambda(unsigned int)#1}&&) at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/reactor.hh:287
seastar::smp_message_queue::async_work_item<seastar::sharded<gms::feature_service>::stop()::{lambda()#2}::operator()() const::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::async_work_item(seastar::smp_message_queue&, seastar::smp_service_group, {lambda(unsigned int)#1}&&) at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/reactor.hh:287
seastar::future<> seastar::future<>::then_wrapped<seastar::future<>::finally_body<locator::i_endpoint_snitch::create_snitch<>(seastar::basic_sstring<char, unsigned int, 15u, true> const&)::{lambda()#1}::operator()() const::{lambda(std::__exception_ptr::exception_ptr)#2}::operator()(std::__exception_ptr) const::{lambda()#1}, true>::operator()(seastar::future<>&&)::{lambda(auto:1)#1}, seastar::future<> >(locator::i_endpoint_snitch::create_snitch<>(seastar::basic_sstring<char, unsigned int, 15u, true> const&)::{lambda()#1}::operator()() const::{lambda(std::__exception_ptr::exception_ptr)#2}::operator()(std::__exception_ptr) const::{lambda()#1}&&) at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/future.hh:1114
seastar::smp_message_queue::async_work_item<seastar::sharded<service::storage_service>::start<std::reference_wrapper<seastar::sharded<seastar::abort_source> >, std::reference_wrapper<seastar::sharded<database> >, std::reference_wrapper<seastar::sharded<gms::gossiper> >, std::reference_wrapper<seastar::sharded<auth::service> >, std::reference_wrapper<seastar::sharded<cql3::cql_config> >, std::reference_wrapper<seastar::sharded<db::system_distributed_keyspace> >, std::reference_wrapper<seastar::sharded<db::view::view_update_generator> >, std::reference_wrapper<seastar::sharded<gms::feature_service> >, service::storage_service_config&, bool, std::set<seastar::basic_sstring<char, unsigned int, 15u, true>, std::less<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::allocator<seastar::basic_sstring<char, unsigned int, 15u, true> > > const&>(std::reference_wrapper<seastar::sharded<seastar::abort_source> >&&, std::reference_wrapper<seastar::sharded<database> >&&, std::reference_wrapper<seastar::sharded<gms::gossiper> >&&, std::reference_wrapper<seastar::sharded<auth::service> >&&, std::reference_wrapper<seastar::sharded<cql3::cql_config> >&&, std::reference_wrapper<seastar::sharded<db::system_distributed_keyspace> >&&, std::reference_wrapper<seastar::sharded<db::view::view_update_generator> >&&, std::reference_wrapper<seastar::sharded<gms::feature_service> >&&, service::storage_service_config&, bool&&, std::set<seastar::basic_sstring<char, unsigned int, 15u, true>, std::less<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::allocator<seastar::basic_sstring<char, unsigned int, 15u, true> > > const&)::{lambda(unsigned int)#1}::operator()(unsigned int)::{lambda()#1}>::~async_work_item() at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/reactor.hh:278
std::__uniq_ptr_impl<seastar::continuation<seastar::future<>::then_impl<seastar::noncopyable_function<seastar::future<seastar::optimized_optional<mutation_fragment> > ()>, seastar::future<seastar::optimized_optional<mutation_fragment> > >(seastar::noncopyable_function<seastar::future<seastar::optimized_optional<mutation_fragment> > ()>&&)::{lambda()#1}::operator()() const::{lambda(seastar::future_state<>&&)#1}>, std::default_delete<{lambda(seastar::future_state<>&&)#1}> >::__uniq_ptr_impl({lambda(seastar::future_state<>&&)#1}*) at /usr/include/c++/8/bits/unique_ptr.h:143
std::enable_if<std::is_integral<bool>::value, std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> > >::type fmt::v5::internal::arg_formatter_base<fmt::v5::back_insert_range<fmt::v5::internal::basic_buffer<char> > >::operator()<bool>(bool) at /usr/include/fmt/format.h:1498
std::enable_if<std::is_integral<char>::value, std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> > >::type fmt::v5::internal::arg_formatter_base<fmt::v5::back_insert_range<fmt::v5::internal::basic_buffer<char> > >::operator()<char>(char) at /usr/include/fmt/format.h:1485
std::enable_if<std::is_integral<char>::value, std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> > >::type fmt::v5::internal::arg_formatter_base<fmt::v5::back_insert_range<fmt::v5::internal::basic_buffer<char> > >::operator()<char>(char) at /usr/include/fmt/format.h:1498
_ZN7seastar6threadC2IZZNS_5asyncIZN44test_row_size_is_immune_to_application_order13run_test_caseEvEUlvE_JEEENS_8futurizeINSt9result_ofIFNSt5decayIT_E4typeEDpNS7_IT0_E4typeEEE4typeEE4typeENS_17thread_attributesEOS8_DpOSB_ENUlRZNS2_IS4_JEEESJ_SK_SL_SN_E4workE_clESP_EUlvE_EESK_S8_ at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/thread.hh:210
database::apply_counter_update(seastar::lw_shared_ptr<schema const>, frozen_mutation const&, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, tracing::trace_state_ptr)::{lambda()#1}::operator()() const at /local/home/bhalevy/dev/scylla/database.cc:1441 (discriminator 3)
cassandra::CassandraProcessor::process_prepare_cql3_query(int, apache::thrift::protocol::TProtocol*, apache::thrift::protocol::TProtocol*, void*) at /local/home/bhalevy/dev/scylla/build/debug/gen/Cassandra.cpp:18618
cassandra::CassandraProcessor::process_execute_prepared_cql_query(int, apache::thrift::protocol::TProtocol*, apache::thrift::protocol::TProtocol*, void*) at /local/home/bhalevy/dev/scylla/build/debug/gen/Cassandra.cpp:18726 (discriminator 1)
cassandra::CassandraConcurrentClient::send_login(cassandra::AuthenticationRequest const&) at /local/home/bhalevy/dev/scylla/build/debug/gen/Cassandra.cpp:18883
seastar::rpc::connection::send_negotiation_frame(std::map<seastar::rpc::protocol_features, seastar::basic_sstring<char, unsigned int, 15u, true>, std::less<seastar::rpc::protocol_features>, std::allocator<std::pair<seastar::rpc::protocol_features const, seastar::basic_sstring<char, unsigned int, 15u, true> > > >) at /local/home/bhalevy/dev/scylla/seastar/src/rpc/rpc.cc:171 (discriminator 3)
std::unique_ptr<seastar::virtio::notifier_vhost, std::default_delete<seastar::virtio::notifier_vhost> >::release() at /usr/include/c++/8/bits/unique_ptr.h:365
std::__uniq_ptr_impl<seastar::task, std::default_delete<seastar::task> >::__uniq_ptr_impl<std::default_delete<seastar::internal::repeater<seastar::keep_doing<seastar::virtio::qp::rxq::run()::{lambda()#1}>(seastar::virtio::qp::rxq::run()::{lambda()#1})::{lambda()#1}> > >(seastar::task*, seastar::future<>&&) at /usr/include/c++/8/bits/unique_ptr.h:147
fmt::v5::buffer_context<char>::type::iterator fmt::v5::format_to<char const*, long, double, 500ul, char>(fmt::v5::basic_memory_buffer<char, 500ul, std::allocator<char> >&, char const* const&, long const&, double const&) at /usr/include/fmt/format.h:3470
seastar::internal::repeater<seastar::tls::session::do_put(seastar::net::fragment*, seastar::net::fragment*)::{lambda(seastar::net::fragment&)#1}::operator()(seastar::net::fragment&) const::{lambda()#1}>::get_future() at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/future-util.hh:281
```

This test cases was (relatively) recently added in 135c84c29ac401b57102113e92cc6116a2fa0774

The hang is reproducible at 64c2d28a7f8fa6ae3d591a57af8a656bcefcbdfc with this `random-seed=238675597`:
```
build/debug/tests/mutation_test --report_level=no --logger=HRF,test_suite:XML,test_suite,jenkins_test.debug.mutation_test.boost.xml -- -c2 -m2G --overprovisioned --unsafe-bypass-fsync 1 --blocked-reactor-notify-ms 2000000 --collectd 0 --random-seed 238675597
```

### PR DESCRIPTION
**Pull request by bhalevy**
Allow returning fewer random clustering keys than requested since
the schema may limit the total number we can generate, for example,
if there is only one boolean clustering column.

Fixes #5161

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>

Tests: unit(dev)
1000 runs of mutation_test in release mode.

### CODE REVIEW

File: tests/random_schema.cc [hunk 1]
```diff
@@ -959,14 +959,14 @@ data_model::mutation_description::key random_schema::make_ckey(uint32_t n) {
     return make_clustering_key(n, g);
 }
 
+// Return up to `n` random clustering keys.
+// Note: may return fewer than n keys if the schema limits the clustering keys space.
```
Comment (denesb) [inline tests/random_schema.cc]: This should be in the declaration site (in the header).

Comment (bhalevy) [reply tests/random_schema.cc]: right, done

**Comment by bhalevy** [comment]
@avikivity / @tgrabiec this test is failing quite frequently in next so I suggest we merge the fix asap.
