### PR TITLE
address_map: Use more efficient and reliable replication method

### LINKED ISSUE #26865: Address map can get stuck and not replicate updates to other shards
Version: 2025.1.6

Root cause still unknown, under investigation.

```
stream_session - [Stream #633c32f5-b694-11f0-a8bd-a9118de4f72c] stream_transfer_task: Fail to send to 058181e9-304f-4cbc-a52c-c4df2c705d5e: netw::unknown_address (no ip address mapping for 058181e9-304f-4cbc-a52c-c4df2c705d5e)
```

Symptom: Attempt to bootstrap or replace a node fails because streaming or repair peer is not able to translate the new host id to IP on non-zero shard. Situation is permanent on a given node, and is healed by restart.

Core dump analysis:

```
$1 = address_map* instance on shard 0
 
(gdb) p $1->_replication_fiber._M_payload._M_engaged 
$5 = true
(gdb) p $1->_replication_fiber._M_payload._M_payload 
$6 = {_M_empty = {<No data fields>}, _M_value = {<seastar::internal::future_base> = {_promise = 0x6000471ae0b8}, _state = {<seastar::future_state_base> = {_u = {st = seastar::future_state_base::state::future, ex = {
            _M_exception_object = 0x1}}}, <seastar::internal::uninitialized_wrapper<seastar::internal::monostate>> = {_v = {<No data fields>}}, }}}

(gdb) p &$1->_replication_fiber._M_payload._M_payload._M_value
$7 = (seastar::future<void> *) 0x6000034d3cd0

The _replication_fiber future is not ready, its promise is attached to a continuation:
 
(gdb) x/10a 0x6000471ae0b8 - 8*3
0x6000471ae0a0:	0x950070 <_ZTVN7seastar12continuationINS_8internal22promise_base_with_typeIvEEZN7service13address_map_tINS_12lowres_clockEE9replicateITkSt9invocableIRNS5_IT_EEEZNS7_25replicate_set_nonexpiringERKN5utils11tagged_uuidIN7locator11host_id_tagEEEEUlRS7_E_EEvSA_St15source_locationEUlvE_ZNS_6futureIvE14then_impl_nrvoISO_SQ_EET0_OSA_EUlOS3_RSO_ONS_12future_stateINS1_9monostateEEEE_vEE+16>	0xef4d0c4300000000
0x6000471ae0b0:	0x1	0x6000034d3cd0
0x6000471ae0c0:	0x6000034d3cd8	0x0
0x6000471ae0d0:	0x6000034d3c10	0x680d7d016f4a4873
0x6000471ae0e0:	0xa0fd7bb9f7c11870	0x94fdb0

That continuation is attached as a task of a promise in another continuation:

(gdb) find/g 0x600000000000, +8772386816, 0x6000471ae0a0
0x600030cb21e8
0x600031d99c38
2 patterns found.

(gdb) x/10a 0x600030cb21e8 - 8*10 
0x600030cb2198:	0x0	0x0
0x600030cb21a8:	0x0	0x0
0x600030cb21b8:	0x0	0x94fbb8 <_ZTVN7seastar12continuationINS_8internal22promise_base_with_typeIvEEZN7service13address_map_tINS_12lowres_clockEE9replicateITkSt9invocableIRNS5_IT_EEEZNS7_29replicate_add_or_update_entryERKN5utils11tagged_uuidIN7locator11host_id_tagEEENSE_21tagged_tagged_integerINSE_5finalEN3gms19generation_type_tagEiEERKNSN_12inet_addressEbEUlRS7_E_EEvSA_St15source_locationEUlvE_ZNS_6futureIvE14then_impl_nrvoISW_SY_EET0_OSA_EUlOS3_RSW_ONS_12future_stateINS1_9monostateEEEE_vEE+16>
0x600030cb21c8:	0x0	0x1
0x600030cb21d8:	0x0	0x6000471ae0b0

The chain is probably long:

(gdb) scylla task_histogram 
...
     3860 0x950070 _ZTVN7seastar12continuationINS_8internal22promise_base_with_typeIvEEZN7service13address_map_tINS_12lowres_clockEE9replicateITkSt9invocableIRNS5_IT_EEEZNS7_25replicate_set_nonexpiringERKN5utils11tagged_uuidIN7locator11host_id_tagEEEEUlRS7_E_EEvSA_St15source_locationEUlvE_ZNS_6futureIvE14then_impl_nrvoISO_SQ_EET0_OSA_EUlOS3_RSO_ONS_12future_stateINS1_9monostateEEEE_vEE + 16  
...
     3785 0x94fbb8 _ZTVN7seastar12continuationINS_8internal22promise_base_with_typeIvEEZN7service13address_map_tINS_12lowres_clockEE9replicateITkSt9invocableIRNS5_IT_EEEZNS7_29replicate_add_or_update_entryERKN5utils11tagged_uuidIN7locator11host_id_tagEEENSE_21tagged_tagged_integerINSE_5finalEN3gms19generation_type_tagEiEERKNSN_12inet_addressEbEUlRS7_E_EEvSA_St15source_locationEUlvE_ZNS_6futureIvE14then_impl_nrvoISW_SY_EET0_OSA_EUlOS3_RSW_ONS_12future_stateINS1_9monostateEEEE_vEE + 16  

```

The replication fiber is blocked with active tasks, and there seems to be a substantial queue of replication tasks (~3k). That explains why the new mapping doesn't reach other shards.

Need to find the root of the chain, which is going to be a parallel_for_each_state corresponding to invoke_on_others():
```
(gdb) info symbol 0xbe3e90
vtable for seastar::parallel_for_each_state + 16 in section .rodata of /opt/scylladb/libexec/scylla
(gdb) find/g 0x600000000000, +8772386816, 0xbe3e90
0x600037050f60
1 pattern found.
(gdb) x/10a 0x600037050f60
0x600037050f60:	0xbe3e90 <_ZTVN7seastar23parallel_for_each_stateE+16>	0x8021300000009
0x600037050f70:	0x1	0x600038a05b60
0x600037050f80:	0x600038a05b90	0x600038a05c30
0x600037050f90:	0x60001b84b430	0x60001b84b438
0x600037050fa0:	0x60001b84b400	0x0

(gdb) p (parallel_for_each_state*) 0x600037050f60
$1 = (seastar::parallel_for_each_state *) 0x600037050f60
(gdb) p $1->_result
$2 = {<seastar::internal::promise_base_with_type<void>> = {<seastar::internal::promise_base> = {_future = 0x60001b84b430, _state = 0x60001b84b438, _task = 0x60001b84b400}, }, _local_state = {<seastar::future_state_base> = {_u = {st = seastar::future_state_base::state::invalid, ex = {_M_exception_object = 0x0}}}, <seastar::internal::uninitialized_wrapper<seastar::internal::monostate>> = {_v = {<No data fields>}}, }}

(gdb) x/10a 0x60001b84b400
0x60001b84b400:	0x66e410 <_ZTVN7seastar8internal21coroutine_traits_baseIvE12promise_typeE+16>	0x600000000009
0x60001b84b410:	0x0	0x600034ff38d0
0x60001b84b420:	0x600034ff38c0	0x0
0x60001b84b430:	0x600037050f90	0x1
0x60001b84b440:	0x0	0x0
(gdb) p (seastar::internal::coroutine_traits_base<void>::promise_type*) 0x60001b84b400
$3 = (seastar::internal::coroutine_traits_base<void>::promise_type *) 0x60001b84b400

(gdb) p $3->_promise
$4 = {<seastar::internal::promise_base_with_type<void>> = {<seastar::internal::promise_base> = {_future = 0x0, _state = 0x600034ff38d0, _task = 0x600034ff38c0}, }, _local_state = {<seastar::future_state_base> = {_u = {st = seastar::future_state_base::state::invalid, ex = {_M_exception_object = 0x0}}}, <seastar::internal::uninitialized_wrapper<seastar::internal::monostate>> = {_v = {<No data fields>}}, }}

(gdb) x/a 0x600034ff38c0
0x600034ff38c0:	0x950070 <_ZTVN7seastar12continuationINS_8internal22promise_base_with_typeIvEEZN7service13address_map_tINS_12lowres_clockEE9replicateITkSt9invocableIRNS5_IT_EEEZNS7_25replicate_set_nonexpiringERKN5utils11tagged_uuidIN7locator11host_id_tagEEEEUlRS7_E_EEvSA_St15source_locationEUlvE_ZNS_6futureIvE14then_impl_nrvoISO_SQ_EET0_OSA_EUlOS3_RSO_ONS_12future_stateINS1_9monostateEEEE_vEE+16>
```

Yes, it's the start of the chain.

What is it blocked on:
```
(gdb) p $1->_incomplete 
$6 = {<std::_Vector_base<seastar::future<void>, std::allocator<seastar::future<void> > >> = {_M_impl = {<std::allocator<seastar::future<void> >> = {<std::__new_allocator<seastar::future<void> >> = {<No data fields>}, <No data fields>}, <std::_Vector_base<seastar::future<void>, std::allocator<seastar::future<void> > >::_Vector_impl_data> = {_M_start = 0x600038a05b60, _M_finish = 0x600038a05b90, _M_end_of_storage = 0x600038a05c30}, <No data fields>}}, <No data fields>}

(gdb) p $6._M_impl._M_finish - $6._M_impl._M_start
$7 = 3
```

So it must be shard 4 which we're blocked on (shard 0 is not in the vector, feature is ready immediately), as waiting starts from the back and pops resolved futures. We pop before resolution, so we're blocked on future [3].

```
(gdb) p $6._M_impl._M_start[0]
$10 = {<seastar::internal::future_base> = {_promise = 0x0}, _state = {<seastar::future_state_base> = {_u = {st = seastar::future_state_base::state::result, ex = {_M_exception_object = 0x3}}}, <seastar::internal::uninitialized_wrapper<seastar::internal::monostate>> = {_v = {<No data fields>}}, }}
(gdb) p $6._M_impl._M_start[1]
$11 = {<seastar::internal::future_base> = {_promise = 0x0}, _state = {<seastar::future_state_base> = {_u = {st = seastar::future_state_base::state::result, ex = {_M_exception_object = 0x3}}}, <seastar::internal::uninitialized_wrapper<seastar::internal::monostate>> = {_v = {<No data fields>}}, }}
(gdb) p $6._M_impl._M_start[2]
$12 = {<seastar::internal::future_base> = {_promise = 0x0}, _state = {<seastar::future_state_base> = {_u = {st = seastar::future_state_base::state::result, ex = {_M_exception_object = 0x3}}}, <seastar::internal::uninitialized_wrapper<seastar::internal::monostate>> = {_v = {<No data fields>}}, }}

Blocked future is popped back, and parallel_for_each_state is attached as the task of the promise:

(gdb) p $1
$14 = (seastar::parallel_for_each_state *) 0x600037050f60
(gdb) find/g 0x600000000000, +8772386816, 0x600037050f60
0x60001a1ae0d8
0x60001a1ae0f0
0x60001a1ae0f8
0x60001a1ae110
0x60001a1ae118
0x60001a1ae120
0x60001a1ae128
0x60001a1ae140
0x60001a1ae148
0x60001a1ae730
0x60001a1ae748
0x60001a1ae760
0x60001a1ae778
0x60001a1ae7b8
0x60001a1ae7c8
0x60003159a1b0
0x60003f6e11a8
0x60003f6e3ac8
18 patterns found.

(gdb) p &$1->_state
$16 = (seastar::continuation_base<void>::future_state *) 0x600037050f70
(gdb) find/g 0x600000000000, +8772386816, 0x600037050f70
0x60003159a1a8
0x60004aeb0e58
2 patterns found.

So it must be 0x60003159a1b0

(gdb) x/10a 0x60003159a1b0 - 8*10
0x60003159a160:	0x60020acc0000	0xae50218 <_ZZZZL11scylla_mainiPPcENK3$_0clEvENKUlvE0_clEvE18gossip_address_map>
0x60003159a170:	0x600004b811e0	0x0
0x60003159a180:	0x23be250 <_ZNSt17_Function_handlerIFN7seastar6futureIvEERN7service13address_map_tINS0_12lowres_clockEEEEZNS0_7shardedIS6_E13invoke_on_allIZNSA_16invoke_on_othersIZZNS6_9replicateITkSt9invocableIRNS4_IT_EEEZNS6_29replicate_add_or_update_entryERKN5utils11tagged_uuidIN7locator11host_id_tagEEENSJ_21tagged_tagged_integerINSJ_5finalEN3gms19generation_type_tagEiEERKNSS_12inet_addressEbEUlS7_E_EEvSF_St15source_locationENKUlvE_clEvEUlS7_E_JEQaasr3stdE9invocableITL0__RSF_DpTL0_0_Esr3stdE9is_same_vINS0_8futurizeINSt13invoke_resultIS12_JS13_S15_EE4typeEE4typeES2_EEES2_NS0_21smp_submit_to_optionsESF_DpT0_EUlS7_E_JEQaasr3stdE9invocableIS12_S13_DpNS0_8internal14sharded_unwrapIS14_E4typeEEsr3stdE9is_same_vINS16_INS17_IS12_JS13_S1K_EE4typeEE4typeES2_EEES2_S1C_SF_S1E_EUlS7_E_E10_M_managerERSt9_Any_dataRKS1R_St18_Manager_operation>	0x2e5a260 <_ZNSt17_Function_handlerIFN7seastar6futureIvEERN7service13address_map_tINS0_12lowres_clockEEEEZNS0_7shardedIS6_E13invoke_on_allIZNSA_16invoke_on_othersIZZNS6_9replicateITkSt9invocableIRNS4_IT_EEEZNS6_29replicate_add_or_update_entryERKN5utils11tagged_uuidIN7locator11host_id_tagEEENSJ_21tagged_tagged_integerINSJ_5finalEN3gms19generation_type_tagEiEERKNSS_12inet_addressEbEUlS7_E_EEvSF_St15source_locationENKUlvE_clEvEUlS7_E_JEQaasr3stdE9invocableITL0__RSF_DpTL0_0_Esr3stdE9is_same_vINS0_8futurizeINSt13invoke_resultIS12_JS13_S15_EE4typeEE4typeES2_EEES2_NS0_21smp_submit_to_optionsESF_DpT0_EUlS7_E_JEQaasr3stdE9invocableIS12_S13_DpNS0_8internal14sharded_unwrapIS14_E4typeEEsr3stdE9is_same_vINS16_INS17_IS12_JS13_S1K_EE4typeEE4typeES2_EEES2_S1C_SF_S1E_EUlS7_E_E9_M_invokeERKSt9_Any_dataS7_>
0x60003159a190:	0x0	0x0
0x60003159a1a0:	0x0	0x600037050f70


```

### PR DESCRIPTION
**Pull request by tgrabiec**
Primary issue with the old method is that each update is a separate
cross-shard call, and all later updates queue behind it. If one of the
shards has high latency for such calls, the queue may accumulate and
system will appear unresponsive for mapping changes on non-zero shards.

This happened in the field when one of the shards was overloaded with
sstables and compaction work, which caused frequent stalls which
delayed polling for ~100ms. A queue of 3k address updates
accumulated, because we update mapping on each change of gossip
states. This made bootstrap impossible because nodes couldn't
learn about the IP mapping for the bootstrapping node and streaming
failed.

To protect against that, use a more efficient method of replication
which requires a single cross-shard call to replicate all prior
updates.

It is also more reliable, if replication fails transiently for some
reason, we don't give up and fail all later updates.

Fixes #26865

### CODE REVIEW

File: utils/replicator.hh [hunk 1]
```diff
@@ -0,0 +1,153 @@
...
+#include "utils/assert.hh"
+
+#include <seastar/util/later.hh>
+#include <seastar/util/backtrace.hh>
+#include <seastar/core/condition-variable.hh>
+#include <seastar/core/sleep.hh>
+#include <seastar/core/coroutine.hh>
+
+/// Implements efficient and reliable replication of complex data structures
+/// from the owning shard to other shards.
```
Comment (avikivity) [inline utils/replicator.hh:122]: Smells like this should be part of seastar::sharded. I don't mind iterating for a bit in this repo and later contributing it.

**Comment by gleb-cloudius** [comment]
> This made bootstrap impossible because nodes couldn't learn about the IP mapping for the bootstrapping node and streaming failed.

Well the reason this happened is because `wait_for_ip` waits for the mapping to appear on one shard only. It should wait on all shards. In that case the bootstrap would have been a bit slow, but it wouldn't fail.

File: utils/replicator.hh [hunk 2]
```diff
@@ -0,0 +1,153 @@
...
+///    // Applies mf to m.
+///    // Must not throw if called immediately after prepare_apply(m, mf).
+///    static Container::apply(Mutation& m, const MutationFragment& mf)
+///
+///    // Reserves space in m for application of mf so that Container::apply(m, mf) doesn't throw.
+///    static Container::prepare_apply(Mutation& m, const MutationFragment& mf) -> void
+///
+/// Must call and await stop() before destruction.
+template<typename Mutation, typename Container>
+class replicator {
```
Comment (avikivity) [inline utils/replicator.hh:167]: We need some constraints to express the syntactical requirements above.

**Comment by gleb-cloudius** [comment]
> > This made bootstrap impossible because nodes couldn't learn about the IP mapping for the bootstrapping node and streaming failed.
> 
> Well the reason this happened is because `wait_for_ip` waits for the mapping to appear on one shard only. It should wait on all shards. In that case the bootstrap would have been a bit slow, but it wouldn't fail.

OTOH `wait_for_ip` does not wait forever, so there is a chance the bootsrap would fail with timeout even if we would wait on all shards. But we need to wait on all shards regardless.

File: utils/replicator.hh [hunk 3]
```diff
@@ -0,0 +1,153 @@
...
+
+    Mutation _to_replicate;
+    seastar::condition_variable _replicate_cv;
+    bool _stopping = false;
+    bool _stopped = false;
+
+private:
+    seastar::future<> start_replicating() {
+        co_await seastar::yield();
+
```
Comment (avikivity) [inline utils/replicator.hh:185]: Seems unnecessary.

File: utils/replicator.hh [hunk 4]
```diff
@@ -0,0 +1,153 @@
...
+                });
+                updates = {};
+            } catch (...) {
+                _container.on_replication_failed(std::current_exception());
+            }
+        }
+    }
+
+public:
+    replicator(Container& ctr)
```
Comment (avikivity) [inline utils/replicator.hh]: 1. explicit
2. better to accept `sharded<Container>`, no?

File: utils/replicator.hh [hunk 5]
```diff
@@ -0,0 +1,153 @@
...
+        while (!_stopping) {
+            if (updates.empty() && _to_replicate.empty()) {
+                co_await _replicate_cv.wait();
+            }
+
+            try {
+                if (!updates.empty()) {
+                    // Replication failed
+                    co_await seastar::sleep(std::chrono::seconds(1));
+                    Container::apply(updates, _to_replicate);
```
Comment (avikivity) [inline utils/replicator.hh]: Another approach is to require free functions, so that Container can be a third-party thing. Though I can't see something like std::set working, we can't express deletions well.

File: utils/replicator.hh [hunk 6]
```diff
@@ -0,0 +1,153 @@
...
+    // Changes are applied in the same order on all shards, so all shards
+    // should eventually converge.
+    // Call only from shard 0.
+    template<typename MutationFragment>
+    void apply_to_all(MutationFragment m) {
+        Container::prepare_apply(_to_replicate, m); // ensure [1] below does not fail.
+        _container.apply_locally(m); // Must not throw after this.
+        Container::apply(_to_replicate, std::move(m)); // [1]
+        _replicate_cv.signal();
+    }
```
Comment (avikivity) [inline utils/replicator.hh:237]: Should return a future that indicates when replication is complete.

Wouldn't the caller want to wait for it in the general case?

File: utils/replicator.hh [hunk 7]
```diff
@@ -0,0 +1,153 @@
...
+    seastar::future<> stop() {
+        if (_stopping) {
+            seastar::throw_with_backtrace<std::runtime_error>("replicator::stop() called twice");
+        }
+        _stopping = true;
+        _replicate_cv.signal();
+        co_await std::move(_replicate_fiber);
+        _stopped = true;
+    }
+};
```
Comment (avikivity) [inline utils/replicator.hh:259]: Should have a dedicated test.

File: utils/replicator.hh (hunk 6 above)
Comment (avikivity) [reply utils/replicator.hh:237]: Well, it would defeat the batching, unless we have concurrent callers.

But doesn't it solve the problem only if the overloaded shard is not shard 0?

File: utils/replicator.hh [hunk 8]
```diff
@@ -0,0 +1,153 @@
...
+    bool _stopped = false;
+
+private:
+    seastar::future<> start_replicating() {
+        co_await seastar::yield();
+
+        Mutation updates;
+        while (!_stopping) {
+            if (updates.empty() && _to_replicate.empty()) {
+                co_await _replicate_cv.wait();
```
Comment (gleb-cloudius) [inline utils/replicator.hh]: `cv::when()`?

File: utils/replicator.hh (hunk 6 above)
Comment (tgrabiec) [reply utils/replicator.hh:237]: address_map API doesn't give futures, I didn't want to change that.

If someone wants to wait, he can always call barrier() after the call.

> But doesn't it solve the problem only if the overloaded shard is not shard 0?

I think it does. Why not?

File: utils/replicator.hh [hunk 9]
```diff
@@ -0,0 +1,153 @@
...
+                _container.on_replication_failed(std::current_exception());
+            }
+        }
+    }
+
+public:
+    replicator(Container& ctr)
+        : _container(ctr)
+        , _replicate_fiber(start_replicating())
+    { }
```
Comment (gleb-cloudius) [inline utils/replicator.hh:216]: Shouldn't we check that we are on a shard 0?

File: service/address_map.hh [hunk 10]
```diff
@@ -181,102 +209,100 @@ class address_map_t : public peering_sharded_service<address_map_t<Clock>> {
...
     }
 
-    template <std::invocable<address_map_t&> F>
-    void replicate(F f, seastar::compat::source_location l = seastar::compat::source_location::current()) {
+    void apply_to_all(locator::host_id id, entry_mutation m) {
         if (this_shard_id() != 0) {
-            auto msg = format("address_map::{}() called on shard {} != 0",
-                l.function_name(), this_shard_id());
-            on_internal_error(rslog, msg);
+            on_internal_error(rslog, "apply_to_all() must be called on shard 0");
```
Comment (gleb-cloudius) [inline service/address_map.hh]: Why did you drop `source_location`?

File: utils/replicator.hh (hunk 6 above)
Comment (avikivity) [reply utils/replicator.hh:237]: > address_map API doesn't give futures, I didn't want to change that.
> 

Maybe it should. If we serialize those updates, the entire problem disappears, no?

> If someone wants to wait, he can always call barrier() after the call.
> 
> > But doesn't it solve the problem only if the overloaded shard is not shard 0?
> 
> I think it does. Why not?

If you have delayed polling for 100ms on shard 0, then the master updates are slowed down too.

I guess the problem is made worse by asynchronous replication, since the updates can be interspersed with stalls (but: wouldn't the updates be cleared quickly by gossip's 1000 shares?)

Why not update synchronously? Yes, we can have stalls from one to time, but gossip should be very responsive since it has little work and lots of shares.

Comment (gleb-cloudius) [reply utils/replicator.hh:237]: We add entry to the map from gossiper constructor. Make be it can be moved. We also add an entry during connection creation and making in synchronous will slow the connection creation down. And it is called during gossiper state application. We saw that when it is slow bad things start to happen since updates accumulate. But during gossiper state application we jump to all shards anyway, May we should move gossiper's state application to this thing.

File: service/address_map.hh [hunk 11]
```diff
@@ -360,7 +386,7 @@ public:
         if (addr == gms::inet_address{}) {
             on_internal_error(rslog, format("IP address missing for {}", id));
         }
-        handle_add_or_update_entry(id, gms::generation_type{}, addr, false);
+        apply_locally(std::make_pair(id, entry_mutation{ .addr = addr }), false);
```
Comment (gleb-cloudius) [inline service/address_map.hh:381]: So here we do not replica, so the sate on different shard may be different. Shouldn't this be a problem?

File: utils/replicator.hh (hunk 6 above)
Comment (tgrabiec) [reply utils/replicator.hh:237]: > > address_map API doesn't give futures, I didn't want to change that.
> 
> Maybe it should. If we serialize those updates, the entire problem disappears, no?

If we serialize them, we push the queue elsewhere, or make the system lag more. Topology updates and gossip handlers make multiple updates. If we serialize updates, we can expect the operation to take `100ms * number_of_nodes_in_the_cluster` instead of `100ms`.

> 
> > If someone wants to wait, he can always call barrier() after the call.
> > > But doesn't it solve the problem only if the overloaded shard is not shard 0?
> > 
> > 
> > I think it does. Why not?
> 
> If you have delayed polling for 100ms on shard 0, then the master updates are slowed down too.
> 
> I guess the problem is made worse by asynchronous replication, since the updates can be interspersed with stalls (but: wouldn't the updates be cleared quickly by gossip's 1000 shares?)

Not if you serialize them, each update takes 100ms due to cross-shard calls, regardless of shares.
With the new approach, even if shard 0 is stalled, we can handle the whole backlog in one task. So we're not latency bound anymore.

> 
> Why not update synchronously? Yes, we can have stalls from one to time, but gossip should be very responsive since it has little work and lots of shares.

File: utils/replicator.hh (hunk 9 above)
Comment (tgrabiec) [reply utils/replicator.hh:216]: replicator can run on any shard, which is the owning shard. It's up to address_map to choose shard 0 as the owning shard.

In theory you could have use cases where you shard the data to spread the load and have multiple replicators on different shards for different subsets.

File: utils/replicator.hh (hunk 6 above)
Comment (avikivity) [reply utils/replicator.hh:237]: > > > address_map API doesn't give futures, I didn't want to change that.
> > 
> > 
> > Maybe it should. If we serialize those updates, the entire problem disappears, no?
> 
> If we serialize them, we push the queue elsewhere, or make the system lag more. Topology updates and gossip handlers make multiple updates. If we serialize updates, we can expect the operation to take `100ms * number_of_nodes_in_the_cluster` instead of `100ms`.

But if it is shard 0 that is stalling, it will take 100ms * nr_nodes.

It's true that synchronous replication magnifies the problem. If you have 100 shards each with a 1% chance of a 100ms stall, with async replication it's amortized 1ms stall, with sync replication it's amortized 69ms stall.

> 
> > > If someone wants to wait, he can always call barrier() after the call.
> > > > But doesn't it solve the problem only if the overloaded shard is not shard 0?
> > > 
> > > 
> > > I think it does. Why not?
> > 
> > 
> > If you have delayed polling for 100ms on shard 0, then the master updates are slowed down too.
> > I guess the problem is made worse by asynchronous replication, since the updates can be interspersed with stalls (but: wouldn't the updates be cleared quickly by gossip's 1000 shares?)
> 
> Not if you serialize them, each update takes 100ms due to cross-shard calls, regardless of shares. With the new approach, even if shard 0 is stalled, we can handle the whole backlog in one task. So we're not latency bound anymore.

If shard 0 is stalled, the delays happen outside the new mechanism.


> 
> > Why not update synchronously? Yes, we can have stalls from one to time, but gossip should be very responsive since it has little work and lots of shares.

File: service/address_map.hh (hunk 10 above)
Comment (tgrabiec) [reply service/address_map.hh]: Accident due to incremental changes. Will bring it back.

File: utils/replicator.hh (hunk 9 above)
Comment (gleb-cloudius) [reply utils/replicator.hh:216]: You should amend the commit message then.

File: service/address_map.hh (hunk 11 above)
Comment (tgrabiec) [reply service/address_map.hh:381]: Only if it was a problem before. Behavior should be the same. More recent updates from shard 0 will still override it.

File: utils/replicator.hh (hunk 9 above)
Comment (tgrabiec) [reply utils/replicator.hh:216]: Right

File: utils/replicator.hh (hunk 6 above)
Comment (tgrabiec) [reply utils/replicator.hh:237]: > > > > address_map API doesn't give futures, I didn't want to change that.
> > > 
> > > 
> > > Maybe it should. If we serialize those updates, the entire problem disappears, no?
> > 
> > 
> > If we serialize them, we push the queue elsewhere, or make the system lag more. Topology updates and gossip handlers make multiple updates. If we serialize updates, we can expect the operation to take `100ms * number_of_nodes_in_the_cluster` instead of `100ms`.
> 
> But if it is shard 0 that is stalling, it will take 100ms * nr_nodes.

Why `* nr_nodes`? We process all nodes in one task and they replicate in the background together, so it takes 100ms.

File: utils/replicator.hh (hunk 4 above)
Comment (tgrabiec) [reply utils/replicator.hh]: 1. right
2. we don't have it yet in the address_map constructor, which initializes replicator.

File: utils/replicator.hh (hunk 8 above)
Comment (tgrabiec) [reply utils/replicator.hh]: Ok

File: utils/replicator.hh (hunk 4 above)
Comment (avikivity) [reply utils/replicator.hh]: Maybe both should be owned by a third party? Too much circular dependency here.

File: utils/replicator.hh (hunk 6 above)
Comment (avikivity) [reply utils/replicator.hh:237]: I assumed updates arrive independently.

If many updates arrive together, use a vector to replicate all of them at once. We don't need the complicated merging.

Comment (tgrabiec) [reply utils/replicator.hh:237]: They arrive together, but logic is not structured in a way which makes it easy to collect them. In gossip, these could be separate tasks which arrive together close in time. Pushing merging and concurrency management there makes things much harder in the upper layers. Hiding this in the replicator is a nice feature.

It's similar to a database which batches updates in a memtable before flushing them to disk. It automatically chooses optimal batching.

Comment (avikivity) [reply utils/replicator.hh:237]: Ok.

File: test/boost/replicator_test.cc [hunk 12]
```diff
@@ -0,0 +1,153 @@
...
+    map_type _m;
+    std::function<void()> _on_apply = [] {};
+    uint64_t _failures = 0;
+
+    void apply_locally(const map_type& m) {
+        _on_apply();
+        apply(_m, m);
+    }
+
+    void apply_locally(std::pair<int, int> kv) {
```
Comment (bhalevy) [inline test/boost/replicator_test.cc]: nit: why not reuse `key_setter` type?

File: test/boost/replicator_test.cc [hunk 13]
```diff
@@ -0,0 +1,153 @@
...
+    static void apply(map_type& dst, const map_type& src) {
+        for (auto&& e : src) {
+            if (e.second) {
+                dst[e.first] = *e.second;
+            }
+        }
+    }
+
+    static void apply(map_type& dst, const key_setter& src) {
+        apply(dst, map_type{std::make_pair(src.first, std::make_optional(src.second))});
```
Comment (bhalevy) [inline test/boost/replicator_test.cc:64]: I guess that would be optimized, but to me it makes more sense to reverse the calling structure and have apply(map_type, const map_type&) call this function for every pair in `src` that have its value engaged.

File: test/boost/replicator_test.cc [hunk 14]
```diff
@@ -0,0 +1,153 @@
...
+    }
+
+    static void prepare_apply(map_type& map, const key_setter& mf) {
+        map.try_emplace(mf.first, std::nullopt);
```
Comment (bhalevy) [inline test/boost/replicator_test.cc:68]: why not try_emplace(mf.first, mf.second)?

File: utils/replicator.hh [hunk 15]
```diff
@@ -0,0 +1,234 @@
...
+    requires(M m, const M& a, const M& b)
+{
+    // Neutral element
+    { M{} } -> std::same_as<M>;
+
+    // Checks if neutral element.
+    // M().empty() == true
+    { a.empty() } -> std::convertible_to<bool>;
+
+    { a == b } -> std::convertible_to<bool>;
```
Comment (bhalevy) [inline utils/replicator.hh:58]: How about operator+ and operator+=?

File: utils/replicator.hh [hunk 16]
```diff
@@ -0,0 +1,234 @@
...
+    }
+
+    // The change is applied locally immediately, and to other shards eventually.
+    // If throws, no change is applied anywhere.
+    // Changes are applied in the same order on all shards, so all shards
+    // should eventually converge.
+    template<MutationFragment<container_type, mutation_type> M>
+    void apply_to_all(M m) {
+        container_type::prepare_apply(_to_replicate, m); // ensure [1] below does not fail.
+        _container.apply_locally(m); // Must not throw after this.
```
Comment (bhalevy) [inline utils/replicator.hh:231]: If the following must not throw we better invoke it in a noexcept context.

File: utils/replicator.hh [hunk 17]
```diff
@@ -0,0 +1,234 @@
...
+        container_type::apply(_to_replicate, std::move(m)); // [1]
+        _replicate_cv.signal();
+    }
+
+    seastar::future<> stop() {
+        if (_stopping) {
+            seastar::throw_with_backtrace<std::runtime_error>("replicator::stop() called twice");
```
Comment (bhalevy) [inline utils/replicator.hh]: on_inernal_error_noexcept would be more appropriate IMO.
anything wrong in production to stop again?

File: utils/replicator.hh [hunk 18]
```diff
@@ -0,0 +1,234 @@
...
+        }
+        _stopping = true;
+        _replicate_cv.signal();
+        co_await std::move(_replicate_fiber);
```
Comment (bhalevy) [inline utils/replicator.hh:256]: using std::exchange(_replicate_fiber, make_ready_future()) instead of std::move would be more robust against double close (in production)

File: utils/replicator.hh [hunk 19]
```diff
@@ -0,0 +1,234 @@
...
+
+            if (_stopping) {
+                break;
+            }
+
+            try {
+                if (!updates.empty()) {
+                    // Replication failed
+                    co_await seastar::sleep(std::chrono::seconds(1));
+                    container_type::apply(updates, _to_replicate);
```
Comment (bhalevy) [inline utils/replicator.hh:194]: Why not `container_type::apply(updates, std::move(_to_replicate));` rather than resetting _to_replicate below (unconditionally, also after std::moving it to updates in the else branch)

File: test/boost/replicator_test.cc (hunk 12 above)
Comment (tgrabiec) [reply test/boost/replicator_test.cc]: We can.

File: test/boost/replicator_test.cc (hunk 14 above)
Comment (tgrabiec) [reply test/boost/replicator_test.cc:68]: prepare_apply() is not supposed to apply anything. "map" should not change value.

Comment (tgrabiec) [reply test/boost/replicator_test.cc:68]: nullopt in the value in this model is equivalent to no value being set.

File: utils/replicator.hh (hunk 15 above)
Comment (tgrabiec) [reply utils/replicator.hh:58]: Current design is to define algebra in the container. So that you can use standard types like std::map as mutations.

File: utils/replicator.hh (hunk 17 above)
Comment (tgrabiec) [reply utils/replicator.hh]: Handling concurrent stop()s would require a more a complex implementation, with a shared promise.

We could handle the case of already stopped.

File: utils/replicator.hh (hunk 18 above)
Comment (tgrabiec) [reply utils/replicator.hh:256]: Just putting a ready future before _stopped = true would be wrong since the second stop() would exit immediately, without waiting for the replicator to be stopped, which is a post-condition of stop().

File: utils/replicator.hh (hunk 19 above)
Comment (tgrabiec) [reply utils/replicator.hh:194]: If `container_type::apply()` throws, we want to retry applying _to_replicate. 

I didn't want to require complex exception-safety guarantees from apply(), the benefits don't outweigh the risk.

File: test/boost/replicator_test.cc (hunk 14 above)
Comment (bhalevy) [reply test/boost/replicator_test.cc:68]: ok, this is documented more thoroughly in the formal interface.

File: utils/replicator.hh (hunk 18 above)
Comment (bhalevy) [reply utils/replicator.hh:256]: isn't it better than throwing in stop()?

Comment (bhalevy) [reply utils/replicator.hh:256]: in testing we would crash and that's fine

Comment (tgrabiec) [reply utils/replicator.hh:256]: > isn't it better than throwing in stop()?

It depends on the bug, but it's undefined behavior in general. If you destroy the object after second stop() without waiting for the first stop(), you'll get use-after-free, and that manifest in all sorts of ways. Better to throw from the second stop() on attempt.

File: test/boost/replicator_test.cc (hunk 13 above)
Comment (tgrabiec) [reply test/boost/replicator_test.cc:64]: Yeah, that would also make sense. 

Here, the code follows directly from concept definition, which is built around Mutation, and says that applying an arbitrary fragment is like applying a mutation corresponding to that fragment.

File: service/address_map.hh [hunk 20]
```diff
@@ -60,12 +60,41 @@ class address_map_t : public peering_sharded_service<address_map_t<Clock>> {
...
+
+        // We rely on this to never throw for exception safety.
+        void apply(const entry_mutation& m) noexcept {
+            if (m.addr && (m.generation >= generation || !addr)) {
+                generation = m.generation;
+                addr = m.addr;
+            }
+            if (m.expiring) {
+                expiring = m.expiring;
+            }
```
Comment (bhalevy) [inline service/address_map.hh:84]: What if this->expiring && !m.expiring?
Does it make sense to keep the current `expiring` attribute after setting generation and addr?
Maybe in the block above we should set expiring = m.expiring unconditionally?

File: service/address_map.hh [hunk 21]
```diff
@@ -181,102 +213,82 @@ class address_map_t : public peering_sharded_service<address_map_t<Clock>> {
...
+    static void prepare_apply(cluster_mutation& map, const host_mutation& mf) {
+        map.try_emplace(mf.first, entry_mutation{});
     }
 
-    void replicate_set_expiring(const locator::host_id& id) {
-        replicate([id] (address_map_t& self) {
-            self.handle_set_expiring(id);
-        });
+    // Applies mf to map.
+    // Must not throw after prepare_apply(map, mf).
```
Comment (bhalevy) [inline service/address_map.hh]: There is no call to prepare_apply in the latest version

Comment (bhalevy) [reply service/address_map.hh]: So the comment doesn't apply anymore :)

File: service/address_map.hh [hunk 22]
```diff
@@ -181,102 +213,82 @@ class address_map_t : public peering_sharded_service<address_map_t<Clock>> {
...
 
-    void handle_set_nonexpiring(const locator::host_id& id) {
-        auto [it, _] = _map.try_emplace(id, timestamped_entry{gms::generation_type{}, std::nullopt});
-        auto& entry = it->second;
-
-        if (entry.expiring()) {
-            entry._lru_entry = nullptr;
-        }
+    void on_replication_failed(std::exception_ptr e) {
+        rslog.warn("address map replication failed: {}", e);
```
Comment (bhalevy) [inline service/address_map.hh:244]: Wouldn't it be better to print also the mapping that failed to replicate?

File: service/address_map.hh [hunk 23]
```diff
@@ -181,102 +213,82 @@ class address_map_t : public peering_sharded_service<address_map_t<Clock>> {
...
+            }
+            entry._m.apply(m);
             if (entry.expiring()) {
-                entry._lru_entry->touch(); // Re-insert in the front of _expiring_list
+                entry._lru_entry->touch();
             }
         }
     }
 
+    void apply_locally(const cluster_mutation& m) {
```
Comment (bhalevy) [inline service/address_map.hh:285]: I'd add a comment that this entry point doesn't provide strong exception guarantees so that
some host_mutations in `m` may be applied if an exception is thrown, and they are not rolled back.

File: utils/replicator.hh (hunk 3 above)
Comment (tgrabiec) [reply utils/replicator.hh:185]: Right

File: service/address_map.hh (hunk 22 above)
Comment (tgrabiec) [reply service/address_map.hh:244]: It wouldn't be useful because we refresh existing mappings. So this would report all mappings.

File: service/address_map.hh (hunk 21 above)
Comment (tgrabiec) [reply service/address_map.hh]: replicator::apply_to_all() calls container_type::prepare_apply()

Comment (tgrabiec) [reply service/address_map.hh]: The comment is about external calls (on the interface), not about the implementation.

File: service/address_map.hh (hunk 20 above)
Comment (tgrabiec) [reply service/address_map.hh:84]: > What if this->expiring && !m.expiring?

It means m doesn't set expiring, and this->expiring should stay.

generation only versions `addr` changes. `expiring` has assignment semantics, so last assignment wins.

Note that mutations are not commutative, only associative.

Comment (tgrabiec) [reply service/address_map.hh:84]: m->expiring is optional<>. If disengaged, it means the mutation doesn't set it.

File: utils/replicator.hh (hunk 16 above)
Comment (tgrabiec) [reply utils/replicator.hh:231]: Ok

File: service/address_map.hh (hunk 23 above)
Comment (tgrabiec) [reply service/address_map.hh:285]: Ok

File: service/address_map.hh (hunk 20 above)
Comment (bhalevy) [reply service/address_map.hh:84]: So it's sticky. I.e. once set, it cannot be unset, well until the state expires.
Worth a comment for future generations

File: service/address_map.hh (hunk 21 above)
Comment (bhalevy) [reply service/address_map.hh]: But this comment is for:
```c++
    static void apply(cluster_mutation& map, const host_mutation& mf) {
        auto [it, emplaced] = map.try_emplace(mf.first, mf.second);
        if (!emplaced) {
            it->second.apply(mf.second);
        }
    }
```

which doesn't call prepare_apply.
I'm confused.

File: service/address_map.hh (hunk 20 above)
Comment (tgrabiec) [reply service/address_map.hh:84]: > So it's sticky. I.e. once set, it cannot be unset, well until the state expires.

What would it mean to unset it? The entry is either expiring or not.


I'll add this:

>         // If engaged, indicates that this mutation changes the "expiring" status of the entry.
>         // If disengaged, the "expiring" status is not changed by the update.
>         // Updates of "expiring" status are always applied in order, last update wins, without considering generation numbers.
>         std::optional<bool> expiring;

File: service/address_map.hh (hunk 21 above)
Comment (tgrabiec) [reply service/address_map.hh]: "Must not throw after prepare_apply(map, mf)" means that apply() must not throw in this sequence:

```
prepare_apply(dst, mf); // can throw
apply(dst, mf); // cannot throw
```

The comment is on the declaration, so the context is in the caller of apply(). It's not for the implementation of apply().

Comment (tgrabiec) [reply service/address_map.hh]: I'll change to 

> // Must not throw when called after prepare_apply(map, mf).

Comment (bhalevy) [reply service/address_map.hh]: > I'll change to
> 
> > // Must not throw when called after prepare_apply(map, mf).

Thanks.  That's much clearer

**Comment by tgrabiec** [comment]
In V3:
  - Improved documentation of mutation fields, improved comments.
  - Introduced concepts for Mutation and Container
  - Because of concepts, needed to move definitions which use replicator in address_map.hh out of line
  - Added unit tests for replicator
  - use condition_variable::when() 
  - replicator::stop() tolerates `stopped == true` and aborts when `!stopped && stopping`
  - wrap code block which is not supposed to throw in a noexcept lambda, in replicator::apply_to_all() 
  - restore reporting of source_location when address_map_t::apply_to_all() is called on non-zero shard
