### PR TITLE
repair: Fix rwlock in compaction_state and lock holder lifecycle

### LINKED ISSUE #27365: Segmentation fault during repair
## Packages

Scylla version: `2026.1.0~dev-20251128.da5cc13e9776` with build-id `f19d21de082ce08b507a0649fadc7000b1245f09`

Kernel Version: `6.14.0-1017-aws`

## Issue description

Following error occurred during repair:
```
2025-11-29T14:13:55.128 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793]  [shard  0: gms] raft_topology - entered `tablet migration` transition state
2025-11-29T14:13:55.128 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793]  [shard  0: gms] raft_topology - Initiating tablet streaming (intranode_migration) of bec4de10-cce7-11f0-b79a-04b4dc9a6932:163 to 5208598c-84f0-4526-bb7f-573728592172:21
...
2025-11-29T14:13:55.130 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793]  [shard 27:strm] repair - Got repair_update_compaction_ctrl gid=ea2072d0-ccd9-11f0-8dba-c5ab01bffb77:41 session_id=a13a72d4-cd2d-11f0-8e9b-76d54580ab09 removed=0
2025-11-29T14:13:55.130 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793] Segmentation fault: si_code: 1, si_addr: 0000000000000023, ip: 0000000001e4f90b
2025-11-29T14:13:55.130 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793] Segmentation fault: resolved ip: 0x0000000001e4f90b in [0x0000000000000000+0x000000000606aa28]
2025-11-29T14:13:55.130 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793] Segmentation fault on shard 28, in scheduling group streaming.
2025-11-29T14:13:55.130 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793] Backtrace:
2025-11-29T14:13:55.130 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793]   0x6043427
2025-11-29T14:13:55.130 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793]   0x6037363
2025-11-29T14:13:55.130 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793]   0x603de0b
2025-11-29T14:13:55.130 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793]  [shard 27:strm] repair - Got repair_update_compaction_ctrl gid=ea2072d0-ccd9-11f0-8dba-c5ab01bffb77:134 session_id=a13a72cc-cd2d-11f0-8e9b-76d54580ab09 removed=0
2025-11-29T14:13:55.131 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793]   0x606070f
2025-11-29T14:13:55.131 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793]   /opt/scylladb/libreloc/libc.so.6+0x1a06f
2025-11-29T14:13:55.131 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793]   0x1e4f90a
2025-11-29T14:13:55.131 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793]   0x45abe44
2025-11-29T14:13:55.131 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793]   0x5446687
2025-11-29T14:13:55.131 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793]   0x54465ff
2025-11-29T14:13:55.131 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793]   0x5446423
2025-11-29T14:13:55.131 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793]   0x544613e
2025-11-29T14:13:55.131 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793]   0x30e4ca5
2025-11-29T14:13:55.131 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793]   0x160c9c9
2025-11-29T14:13:55.131 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793]   0x60613b9
2025-11-29T14:13:55.131 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793]   0x6011eea
2025-11-29T14:13:55.131 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793]   /opt/scylladb/libreloc/libc.so.6+0x71f53
2025-11-29T14:13:55.131 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793]   /opt/scylladb/libreloc/libc.so.6+0xf532b
2025-11-29T14:13:55.130 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793]  [shard 26:strm] repair - Got repair_update_compaction_ctrl gid=ea2072d0-ccd9-11f0-8dba-c5ab01bffb77:155 session_id=a13a72d6-cd2d-11f0-8e9b-76d54580ab09 removed=0
```
decoded:
```
2025-11-29T14:13:55.130 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793] Backtrace:
[Backtrace #0]
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::'lambda'(seastar::frame)>(seastar::backtrace_buffer::append_backtrace()::'lambda'(seastar::frame)&&, bool) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:77
seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:792
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:830
seastar::print_with_backtrace(char const*, bool, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:850

2025-11-29T14:13:55.130 longevity-mv-si-4d-master-db-node-e81d8998-6  !INFO | scylla[10793]  [shard 27:strm] repair - Got repair_update_compaction_ctrl gid=ea2072d0-ccd9-11f0-8dba-c5ab01bffb77:134 session_id=a13a72cc-cd2d-11f0-8e9b-76d54580ab09 removed=0
[Backtrace #1]
seastar::sigsegv_action(siginfo_t*, ucontext_t*) at ./build/release/seastar/./seastar/src/core/reactor.cc:4157
 (inlined by) void seastar::install_oneshot_signal_handler<11, (void (*)(siginfo_t*, ucontext_t*))(&seastar::sigsegv_action(siginfo_t*, ucontext_t*))>()::'lambda'(int, siginfo_t*, void*)::operator()(int, siginfo_t*, void*) const at ./build/release/seastar/./seastar/src/core/reactor.cc:4091
 (inlined by) void seastar::install_oneshot_signal_handler<11, (void (*)(siginfo_t*, ucontext_t*))(&seastar::sigsegv_action(siginfo_t*, ucontext_t*))>()::'lambda'(int, siginfo_t*, void*)::__invoke(int, siginfo_t*, void*) at ./build/release/seastar/./seastar/src/core/reactor.cc:4086
/cache/54445/scylla/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=48c4b9b1efb1df15da8e787f489128bf31893317, for GNU/Linux 3.2.0, not stripped

?? at ??:0
seastar::internal::abortable_fifo<seastar::basic_semaphore<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>::entry, seastar::basic_semaphore<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>::expiry_handler>::front() at ././seastar/include/seastar/core/abortable_fifo.hh:140
 (inlined by) seastar::basic_semaphore<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>::signal(unsigned long) at ././seastar/include/seastar/core/semaphore.hh:411
seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>::return_all() at ././seastar/include/seastar/core/semaphore.hh:559
 (inlined by) seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>::~semaphore_units() at ././seastar/include/seastar/core/semaphore.hh:539
 (inlined by) void std::destroy_at<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>>(seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>*) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/stl_construct.h:88
 (inlined by) void std::_Destroy<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>>(seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>*) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/stl_construct.h:164
 (inlined by) void std::_Destroy<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>*>(seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>*, seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>*) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/stl_construct.h:226
 (inlined by) void std::_Destroy<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>*, seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>>(seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>*, seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>*, std::allocator<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>>&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/alloc_traits.h:1045
 (inlined by) std::vector<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>, std::allocator<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>>>::~vector() at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/stl_vector.h:802
std::pair<utils::tagged_uuid<service::session_id_tag> const, std::vector<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>, std::allocator<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>>>>::~pair() at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/ranges_base.h:1093
 (inlined by) void std::destroy_at<std::pair<utils::tagged_uuid<service::session_id_tag> const, std::vector<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>, std::allocator<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>>>>>(std::pair<utils::tagged_uuid<service::session_id_tag> const, std::vector<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>, std::allocator<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>>>>*) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/stl_construct.h:88
 (inlined by) void std::allocator_traits<std::allocator<std::__detail::_Hash_node<std::pair<utils::tagged_uuid<service::session_id_tag> const, std::vector<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>, std::allocator<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>>>>, false>>>::destroy<std::pair<utils::tagged_uuid<service::session_id_tag> const, std::vector<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>, std::allocator<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>>>>>(std::allocator<std::__detail::_Hash_node<std::pair<utils::tagged_uuid<service::session_id_tag> const, std::vector<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>, std::allocator<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>>>>, false>>&, std::pair<utils::tagged_uuid<service::session_id_tag> const, std::vector<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>, std::allocator<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>>>>*) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/alloc_traits.h:698
 (inlined by) std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<utils::tagged_uuid<service::session_id_tag> const, std::vector<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>, std::allocator<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>>>>, false>>>::_M_deallocate_node(std::__detail::_Hash_node<std::pair<utils::tagged_uuid<service::session_id_tag> const, std::vector<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>, std::allocator<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>>>>, false>*) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/hashtable_policy.h:1572
 (inlined by) std::_Hashtable<utils::tagged_uuid<service::session_id_tag>, std::pair<utils::tagged_uuid<service::session_id_tag> const, std::vector<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>, std::allocator<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>>>>, std::allocator<std::pair<utils::tagged_uuid<service::session_id_tag> const, std::vector<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>, std::allocator<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>>>>>, std::__detail::_Select1st, std::equal_to<utils::tagged_uuid<service::session_id_tag>>, std::hash<utils::tagged_uuid<service::session_id_tag>>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>>::_M_erase(unsigned long, std::__detail::_Hash_node_base*, std::__detail::_Hash_node<std::pair<utils::tagged_uuid<service::session_id_tag> const, std::vector<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>, std::allocator<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>>>>, false>*) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/hashtable.h:2590
std::_Hashtable<utils::tagged_uuid<service::session_id_tag>, std::pair<utils::tagged_uuid<service::session_id_tag> const, std::vector<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>, std::allocator<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>>>>, std::allocator<std::pair<utils::tagged_uuid<service::session_id_tag> const, std::vector<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>, std::allocator<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>>>>>, std::__detail::_Select1st, std::equal_to<utils::tagged_uuid<service::session_id_tag>>, std::hash<utils::tagged_uuid<service::session_id_tag>>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>>::erase(utils::tagged_uuid<service::session_id_tag> const&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/hashtable.h:2620
std::unordered_map<utils::tagged_uuid<service::session_id_tag>, std::vector<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>, std::allocator<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>>>, std::hash<utils::tagged_uuid<service::session_id_tag>>, std::equal_to<utils::tagged_uuid<service::session_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<service::session_id_tag> const, std::vector<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>, std::allocator<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>>>>>>::erase(utils::tagged_uuid<service::session_id_tag> const&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/unordered_map.h:834
 (inlined by) repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)::operator()(repair_service&) at ./repair/row_level.cc:2837
seastar::future<void> std::__invoke_impl<seastar::future<void>, repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)&, repair_service&>(std::__invoke_other, repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)&, repair_service&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/invoke.h:63
 (inlined by) std::__invoke_result<repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)&, repair_service&>::type std::__invoke<repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)&, repair_service&>(repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)&, repair_service&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/invoke.h:98
 (inlined by) decltype(auto) std::__apply_impl<repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)&, std::tuple<repair_service&>, 0ul>(repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)&, std::tuple<repair_service&>&&, std::integer_sequence<unsigned long, 0ul>) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/tuple:2920
 (inlined by) decltype(auto) std::apply<repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)&, std::tuple<repair_service&>>(repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)&, std::tuple<repair_service&>&&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/tuple:2935
 (inlined by) seastar::future<void> seastar::futurize<seastar::future<void>>::apply<repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)&, repair_service&>(repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)&, std::tuple<repair_service&>&&) at ././seastar/include/seastar/core/future.hh:1958
 (inlined by) auto seastar::futurize_apply<repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)&, repair_service&>(repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)&, std::tuple<repair_service&>&&) at ././seastar/include/seastar/core/future.hh:2027
 (inlined by) seastar::future<void> seastar::sharded<repair_service>::invoke_on_all<repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)>(seastar::smp_submit_to_options, T)::'lambda'(repair_service&)::operator()(repair_service&)::'lambda'()::operator()() at ././seastar/include/seastar/core/sharded.hh:770
 (inlined by) T std::__invoke_impl<seastar::future<void>, seastar::future<void> seastar::sharded<repair_service>::invoke_on_all<repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)>(seastar::smp_submit_to_options, T)::'lambda'(repair_service&)::operator()(repair_service&)::'lambda'()>(std::__invoke_other, seastar::future<void> seastar::sharded<repair_service>::invoke_on_all<repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)>(seastar::smp_submit_to_options, T)::'lambda'(repair_service&)::operator()(repair_service&)::'lambda'()&&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/invoke.h:63
 (inlined by) std::__invoke_result<T>::type std::__invoke<seastar::future<void> seastar::sharded<repair_service>::invoke_on_all<repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)>(seastar::smp_submit_to_options, T)::'lambda'(repair_service&)::operator()(repair_service&)::'lambda'()>(T&&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/invoke.h:98
 (inlined by) decltype(auto) std::__apply_impl<seastar::future<void> seastar::sharded<repair_service>::invoke_on_all<repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)>(seastar::smp_submit_to_options, T)::'lambda'(repair_service&)::operator()(repair_service&)::'lambda'(), std::tuple<>>(T&&, std::tuple<>&&, std::integer_sequence<unsigned long, ...>) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/tuple:2920
 (inlined by) decltype(auto) std::apply<seastar::future<void> seastar::sharded<repair_service>::invoke_on_all<repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)>(seastar::smp_submit_to_options, T)::'lambda'(repair_service&)::operator()(repair_service&)::'lambda'(), std::tuple<>>(T&&, std::tuple<>&&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/tuple:2935
 (inlined by) seastar::future<void> seastar::sharded<repair_service>::invoke_on_all<repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)>(seastar::smp_submit_to_options, T)::'lambda'(repair_service&)::operator()(repair_service&) at ././seastar/include/seastar/core/sharded.hh:769
 (inlined by) T std::__invoke_impl<seastar::future<void>, seastar::future<void> seastar::sharded<repair_service>::invoke_on_all<repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)>(seastar::smp_submit_to_options, T)::'lambda'(repair_service&)&, repair_service&>(std::__invoke_other, seastar::future<void> seastar::sharded<repair_service>::invoke_on_all<repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)>(seastar::smp_submit_to_options, T)::'lambda'(repair_service&)&, repair_service&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/invoke.h:63
 (inlined by) std::enable_if<is_invocable_r_v<T, seastar::future<void> seastar::sharded<repair_service>::invoke_on_all<repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)>(seastar::smp_submit_to_options, T)::'lambda'(repair_service&)&, repair_service&>, T>::type std::__invoke_r<seastar::future<void>, seastar::future<void> seastar::sharded<repair_service>::invoke_on_all<repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)>(seastar::smp_submit_to_options, T)::'lambda'(repair_service&)&, repair_service&>(seastar::future<void> seastar::sharded<repair_service>::invoke_on_all<repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)>(seastar::smp_submit_to_options, T)::'lambda'(repair_service&)&, repair_service&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/invoke.h:116
 (inlined by) std::_Function_handler<seastar::future<void> (repair_service&), seastar::future<void> seastar::sharded<repair_service>::invoke_on_all<repair_service::init_ms_handlers()::$_15::operator()(seastar::rpc::client_info const&, locator::global_tablet_id, utils::tagged_uuid<service::session_id_tag>) const::'lambda'(repair_service&)>(seastar::smp_submit_to_options, T)::'lambda'(repair_service&)>::_M_invoke(std::_Any_data const&, repair_service&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/std_function.h:292
std::function<seastar::future<void> (repair_service&)>::operator()(repair_service&) const at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/std_function.h:593
 (inlined by) seastar::sharded<repair_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (repair_service&)>)::'lambda'(unsigned int)::operator()(unsigned int) const::'lambda'()::operator()() const at ././seastar/include/seastar/core/sharded.hh:743
 (inlined by) seastar::future<void> std::__invoke_impl<seastar::future<void>, seastar::sharded<repair_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (repair_service&)>)::'lambda'(unsigned int)::operator()(unsigned int) const::'lambda'()&>(std::__invoke_other, seastar::sharded<repair_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (repair_service&)>)::'lambda'(unsigned int)::operator()(unsigned int) const::'lambda'()&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/invoke.h:63
 (inlined by) std::__invoke_result<seastar::sharded<repair_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (repair_service&)>)::'lambda'(unsigned int)::operator()(unsigned int) const::'lambda'()&>::type std::__invoke<seastar::sharded<repair_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (repair_service&)>)::'lambda'(unsigned int)::operator()(unsigned int) const::'lambda'()&>(seastar::sharded<repair_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (repair_service&)>)::'lambda'(unsigned int)::operator()(unsigned int) const::'lambda'()&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/invoke.h:98
 (inlined by) std::invoke_result<seastar::sharded<repair_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (repair_service&)>)::'lambda'(unsigned int)::operator()(unsigned int) const::'lambda'()&>::type std::invoke<seastar::sharded<repair_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (repair_service&)>)::'lambda'(unsigned int)::operator()(unsigned int) const::'lambda'()&>(seastar::sharded<repair_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (repair_service&)>)::'lambda'(unsigned int)::operator()(unsigned int) const::'lambda'()&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/functional:122
 (inlined by) seastar::future<void> seastar::futurize<seastar::future<void>>::invoke<seastar::sharded<repair_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (repair_service&)>)::'lambda'(unsigned int)::operator()(unsigned int) const::'lambda'()&>(seastar::sharded<repair_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (repair_service&)>)::'lambda'(unsigned int)::operator()(unsigned int) const::'lambda'()&) at ././seastar/include/seastar/core/future.hh:1990
 (inlined by) seastar::smp_message_queue::async_work_item<seastar::sharded<repair_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (repair_service&)>)::'lambda'(unsigned int)::operator()(unsigned int) const::'lambda'()>::run_and_dispose() at ././seastar/include/seastar/core/smp.hh:240
seastar::reactor::task_queue::run_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:2667
 (inlined by) seastar::reactor::task_queue_group::run_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:3174
 (inlined by) seastar::reactor::task_queue_group::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:3158
 (inlined by) seastar::reactor::do_run() at ./build/release/seastar/./seastar/src/core/reactor.cc:3327
seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0::operator()() const at ./build/release/seastar/./seastar/src/core/reactor.cc:4629
 (inlined by) void std::__invoke_impl<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0&>(std::__invoke_other, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/invoke.h:63
 (inlined by) std::enable_if<is_invocable_r_v<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0&>, void>::type std::__invoke_r<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0&>(seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/invoke.h:113
 (inlined by) std::_Function_handler<void (), seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0>::_M_invoke(std::_Any_data const&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/std_function.h:292
std::function<void ()>::operator()() const at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/std_function.h:593
 (inlined by) seastar::posix_thread::start_routine(void*) at ./build/release/seastar/./seastar/src/core/posix.cc:90
start_thread at ??:0
__GI___clone3 at ??:0

```

Seems like fault happened there:
**seastar::internal::abortable_fifo<...>::front() called from basic_semaphore::signal().**

## Impact

Node coredumped

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 6 nodes (i4i.8xlarge)

Scylla Nodes used in this run:

- longevity-mv-si-4d-master-db-node-e81d8998-1 (3.252.80.185 | 10.4.9.191) (shards: 30)

- longevity-mv-si-4d-master-db-node-e81d8998-2 (34.254.203.166 | 10.4.10.35) (shards: 30)

- longevity-mv-si-4d-master-db-node-e81d8998-3 (3.250.134.88 | 10.4.9.95) (shards: 30)

- longevity-mv-si-4d-master-db-node-e81d8998-4 (3.253.81.46 | 10.4.8.181) (shards: 30)

- longevity-mv-si-4d-master-db-node-e81d8998-5 (54.154.92.178 | 10.4.8.225) (shards: 30)

- longevity-mv-si-4d-master-db-node-e81d8998-6 (54.220.167.255 | 10.4.9.241) (shards: 30)

- longevity-mv-si-4d-master-db-node-e81d8998-7 (52.210.93.156 | 10.4.8.86) (shards: -1)

- longevity-mv-si-4d-master-db-node-e81d8998-8 (34.247.49.13 | 10.4.9.12) (shards: 30)

- longevity-mv-si-4d-master-db-node-e81d8998-9 (18.201.249.238 | 10.4.9.103) (shards: 30)

- longevity-mv-si-4d-master-db-node-e81d8998-10 (3.254.119.67 | 10.4.8.209) (shards: 30)

OS / Image: `ami-0de459ce6cc8b8a98` (aws: N/A)

Test: `longevity-mv-si-4days-streaming-test`
Test id: `e81d8998-2491-4a65-b96c-64037d1c0e11`
Test name: `scylla-master/tier1/longevity-mv-si-4days-streaming-test`

Test method: `longevity_test.LongevityTest.test_custom_time`

Test config file(s):

- [longevity-mv-si-4days.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/9f5f001ba807a1d57ba007dadd4ce96108691d66/test-cases/longevity/longevity-mv-si-4days.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor e81d8998-2491-4a65-b96c-64037d1c0e11`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=e81d8998-2491-4a65-b96c-64037d1c0e11)
- Show all stored logs command: `$ hydra investigate show-logs e81d8998-2491-4a65-b96c-64037d1c0e11`

## Logs:

- **[longevity-mv-si-4d-master-db-node-e81d8998-7](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/e81d8998-2491-4a65-b96c-64037d1c0e11/log/longevity-mv-si-4d-master-db-node-e81d8998-7/download)**

- **[longevity-mv-si-4d-master-db-node-e81d8998-5](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/e81d8998-2491-4a65-b96c-64037d1c0e11/log/longevity-mv-si-4d-master-db-node-e81d8998-5/download)**

- **[longevity-mv-si-4d-master-db-node-e81d8998-3](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/e81d8998-2491-4a65-b96c-64037d1c0e11/log/longevity-mv-si-4d-master-db-node-e81d8998-3/download)**

- **[longevity-mv-si-4d-master-db-node-e81d8998-1](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/e81d8998-2491-4a65-b96c-64037d1c0e11/log/longevity-mv-si-4d-master-db-node-e81d8998-1/download)**

- **[longevity-mv-si-4d-master-db-node-e81d8998-10](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/e81d8998-2491-4a65-b96c-64037d1c0e11/log/longevity-mv-si-4d-master-db-node-e81d8998-10/download)**

- **[core.scylla-longevity-mv-si-4d-master-db-node-e81d8998-6-2025-11-29_14-33-27.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/e81d8998-2491-4a65-b96c-64037d1c0e11/log/core.scylla-longevity-mv-si-4d-master-db-node-e81d8998-6-2025-11-29_14-33-27.zst/download)**

- **[core.scylla-longevity-mv-si-4d-master-db-node-e81d8998-9-2025-11-29_15-53-30.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/e81d8998-2491-4a65-b96c-64037d1c0e11/log/core.scylla-longevity-mv-si-4d-master-db-node-e81d8998-9-2025-11-29_15-53-30.zst/download)**

- **[core.scylla-longevity-mv-si-4d-master-db-node-e81d8998-8-2025-11-29_15-54-16.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/e81d8998-2491-4a65-b96c-64037d1c0e11/log/core.scylla-longevity-mv-si-4d-master-db-node-e81d8998-8-2025-11-29_15-54-16.zst/download)**

- **[db-cluster-e81d8998.tar.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/e81d8998-2491-4a65-b96c-64037d1c0e11/log/db-cluster-e81d8998.tar.zst/download)**

- **[schema-logs-e81d8998.tar.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/e81d8998-2491-4a65-b96c-64037d1c0e11/log/schema-logs-e81d8998.tar.zst/download)**

- **[sct-runner-events-e81d8998.tar.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/e81d8998-2491-4a65-b96c-64037d1c0e11/log/sct-runner-events-e81d8998.tar.zst/download)**

- **[2025_11_29__04_07_53_643.sct-e81d8998.log.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/e81d8998-2491-4a65-b96c-64037d1c0e11/log/2025_11_29__04_07_53_643.sct-e81d8998.log.zst/download)**

- **[2025_11_29__14_08_53_811.sct-e81d8998.log.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/e81d8998-2491-4a65-b96c-64037d1c0e11/log/2025_11_29__14_08_53_811.sct-e81d8998.log.zst/download)**

- **[2025_11_29__14_43_50_443.sct-e81d8998.log.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/e81d8998-2491-4a65-b96c-64037d1c0e11/log/2025_11_29__14_43_50_443.sct-e81d8998.log.zst/download)**

- **[2025_11_29__15_03_34_039.sct-e81d8998.log.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/e81d8998-2491-4a65-b96c-64037d1c0e11/log/2025_11_29__15_03_34_039.sct-e81d8998.log.zst/download)**

- **[2025_11_29__15_05_45_246.sct-e81d8998.log.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/e81d8998-2491-4a65-b96c-64037d1c0e11/log/2025_11_29__15_05_45_246.sct-e81d8998.log.zst/download)**

- **[loader-set-e81d8998.tar.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/e81d8998-2491-4a65-b96c-64037d1c0e11/log/loader-set-e81d8998.tar.zst/download)**

- **[monitor-set-e81d8998.tar.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/e81d8998-2491-4a65-b96c-64037d1c0e11/log/monitor-set-e81d8998.tar.zst/download)**

- **[builder-e81d8998.log.tar.gz](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/e81d8998-2491-4a65-b96c-64037d1c0e11/log/builder-e81d8998.log.tar.gz/download)**

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tier1/job/longevity-mv-si-4days-streaming-test/78/)
[Argus](https://argus.scylladb.com/test/f1ff65fd-8324-4264-8d28-8c7122fca836/runs?additionalRuns[]=e81d8998-2491-4a65-b96c-64037d1c0e11)
</details>

### PR DESCRIPTION
**Pull request by raphaelsc**
Consider this:

- repair takes the lock holder
- tablet merge filber destories the compaction group and the compaction state
- repair fails
- repair destroy the lock holder

This is observed in the test:

```
repair - repair[5d73d094-72ee-4570-a3cc-1cd479b2a036] Repair 1 out of 1 tablets: table=sec_index.users range=(432345564227567615,504403158265495551] replicas=[0e9d51a5-9c99-4d6e-b9db-ad36a148b0ea:15, 498e354c-1254-4d8d-a565-2f5c6523845a:9, 5208598c-84f0-4526-bb7f-573728592172:28]

...

repair - repair[5d73d094-72ee-4570-a3cc-1cd479b2a036]: Started to repair 1 out of 1 tables in keyspace=sec_index, table=users, table_id=ea2072d0-ccd9-11f0-8dba-c5ab01bffb77, repair_reason=repair
repair - Enable incremental repair for table=sec_index.users range=(432345564227567615,504403158265495551]
table - Disabled compaction for range=(432345564227567615,504403158265495551] session_id=a13a72cc-cd2d-11f0-8e9b-76d54580ab09 for incremental repair
table - Got unrepaired compaction and repair lock for range=(432345564227567615,504403158265495551] session_id=a13a72cc-cd2d-11f0-8e9b-76d54580ab09 for incremental repair
table - Disabled compaction for range=(432345564227567615,504403158265495551] session_id=a13a72cc-cd2d-11f0-8e9b-76d54580ab09 for incremental repair
table - Got unrepaired compaction and repair lock for range=(432345564227567615,504403158265495551] session_id=a13a72cc-cd2d-11f0-8e9b-76d54580ab09 for incremental repair
repair - repair[5d73d094-72ee-4570-a3cc-1cd479b2a036]: get_sync_boundary: got error from node=0e9d51a5-9c99-4d6e-b9db-ad36a148b0ea, keyspace=sec_index, table=users, range=(432345564227567615,504403158265495551], error=seastar::rpc::remote_verb_error (Compaction state for table [0x60f008fa34c0] not found)
compaction_manager - Stopping 1 tasks for 1 ongoing compactions for table sec_index.users compaction_group=238 due to tablet merge
compaction_manager - Stopping 1 tasks for 1 ongoing compactions for table sec_index.users compaction_group=238 due to tablet merge

....

scylla[10793] Segmentation fault on shard 28, in scheduling group streaming
```

The rwlock in compaction_state could be destroyed before the lock holder
of the rwlock is destroyed. This causes user after free when the lock
the holder is destroyed.

To fix it, users of repair lock will now be waited when a compaction
group is being stopped.
That way, compaction group - which controls the lifetime of rwlock -
cannot be destroyed while the lock is held.
Additionally, the merge completion fiber - that might remove groups -
is properly serialized with incremental repair.

The issue can be reproduced using sanitize build consistently and can not
be reproduced after the fix.

Fixes #27365

### CODE REVIEW

File: compaction/compaction_group_view.hh [hunk 1]
```diff
@@ -56,7 +56,7 @@ public:
     virtual bool tombstone_gc_enabled() const noexcept = 0;
     virtual const tombstone_gc_state& get_tombstone_gc_state() const noexcept = 0;
     virtual compaction_backlog_tracker& get_backlog_tracker() = 0;
-    virtual const std::string get_group_id() const noexcept = 0;
+    virtual size_t get_group_id() const noexcept = 0;
```
Comment (denesb) [inline compaction/compaction_group_view.hh]: Commit log should explain they "why?" as well, not just the "what?".

Comment (raphaelsc) [reply compaction/compaction_group_view.hh]: done

File: compaction/compaction_manager.cc [hunk 2]
```diff
@@ -2434,7 +2434,7 @@ bool compaction_manager::compaction_disabled(compaction_group_view& t) const {
     if (auto it = _compaction_state.find(&t); it != _compaction_state.end()) {
         return it->second.compaction_disabled();
     } else {
-        cmlog.debug("compaction_disabled: {}:{} not in compaction_state", t.schema()->id(), t.get_group_id());
+        cmlog.debug("compaction_disabled: {}:{} not in compaction_state", t.schema()->id(), fmt::to_string(t.get_group_id()));
```
Comment (tgrabiec) [inline compaction/compaction_manager.cc]: nit: fmt::to_string() is not necessary here.

File: compaction/compaction_group_view.hh (hunk 1 above)
Comment (avikivity) [inline compaction/compaction_group_view.hh]: I feel like this is very easy to misuse. We can easily get a number from one API and feed it into another, but the two APIs are in different namespaces.

File: compaction/compaction_manager.cc (hunk 2 above)
Comment (avikivity) [inline compaction/compaction_manager.cc]: I'm sure fmt::to_string is unnecessary here.

File: replica/table.cc [hunk 3]
```diff
@@ -777,6 +777,21 @@ class tablet_storage_group_manager final : public storage_group_manager {
...
+    // potentially causing an ABBA deadlock.
+    utils::phased_barrier _merge_fiber_barrier;
+    std::optional<utils::phased_barrier::operation> _pending_merge_fiber_work;
+    // Compactions like major need to work on all sstables in the unrepaired
+    // set, no matter if the sstable is being repaired or not. The
+    // incremental repair lock is introduced to serialize repair and such
+    // compactions. This lock guarantees that no sstables are being repaired.
+    // Note that the minor compactions do not need to take this lock because
+    // they ignore sstables that are being repaired.
+    std::unordered_map<locator::global_tablet_id, seastar::rwlock> _repair_compaction_locks;
```
Comment (avikivity) [inline replica/table.cc]: I'm a worried here. How do we know that a tablet id from before a merge or a split isn't used after a merge or a split? It will lock completely different things.

Comment (raphaelsc) [reply replica/table.cc]: Incremental repair is serialized with split and merge. So write lock won't be taken.

It's true though the read lock can be taken for maintenance compaction, which can be ongoing during split and merge completion.

Perhaps we could move the rwlock to storage_group, which has 1:1 relationship with tablets.

The storage group will not be destroyed anyway, until all users are gone.

And split and merge gets handled naturally, since newer procedures will pick the rwlock of the new storage group set.

Comment (avikivity) [reply replica/table.cc]: How much can we trust this serialization? It happens on the topology change coordinator, while we're on another node. What if we get fenced off and reconnected?

Comment (raphaelsc) [reply replica/table.cc]: > How much can we trust this serialization? It happens on the topology change coordinator, while we're on another node. What if we get fenced off and reconnected?

If we don't provide this serialization, we might have a bug in the coordinator.

Note that merge, split, and repair will be serialized since they lock the coordinator.

What I am not sure is whether merge and split completion handling (the atomic part in update_effective_replication_map(), called when replica is called with changes to tablet metadata) can happen while repair started. We'd guarantee serialization here if we perform a barrier before transioning into repair stage, to ensure all replicas see the latest metadata.

repair_service currently relies on stability of global_tablet_id. There will be always stability on the tablet_id, AFAIU, since we cannot start repair while performing changes to metadata for split or merge.

If merge or split completion can be handled during repair (I will double check it), then storage groups can be destroyed while repair is taking the write lock. 

Split can indeed be a problem:

Major started on tablet 1 (tablets 0, 1)
Split happens (tablet 1 becomes tablet 2 and 3)
Repair starts on tablet 2

replica::compaction_group can be indeed the best place, since we just move them around on split and merge. storage_group is less stable in this regard.

I think a less intrusive change is to just serialize the taking of write lock with the 2nd part (non atomic) of merge completion handling that happens in background. Better for backporting. I am planning to keep the rwlock in compaction::compaction_state (as today), but don't make it a shared ptr since we won't have to, with the serialization aforementioned.

**Comment by asias** [comment]
> v2: simplified approach by: instead of moving the rwlock to a more stable place, provide stability (on compaction groups) by properly serializing merge completion (the part handled by merge fiber in background) with the preparation phase of incremental repair.

For the tablet merge path, I think v2 of this PR is enough. However, how about other paths that might drop the compaction_state which holds the rwlock, e.g, split of a tablet or drop of a table.

**Comment by raphaelsc** [comment]
@scylladbbot trigger-ci

File: repair/row_level.cc [hunk 4]
```diff
@@ -3953,3 +3956,19 @@ future<std::optional<repair_task_progress>> repair_service::get_tablet_repair_ta
             task_uuid, tid, requested, finished, progress.progress(), finished_nomerge);
     co_return progress;
 }
+
+void repair_service::on_cleanup_for_drop_table(const table_id& id) {
+    // Prevent repair lock from being leaked in repair_service when table is dropped midway.
+    // The RPC verb that removes the lock on success path will not be called by coordinator after table was dropped.
+    // We also cannot move the lock from repair_service to repair_meta, since the lock must outlive the latter.
+    // Since tablet metadata has been erased at this point, we can simply erase all instances for the dropped table.
+    rlogger.debug("Cleaning up state for dropped table {}", id);
```
Comment (asias) [inline repair/row_level.cc:3965]: The locator::tablet_transition_stage::end_repair stage of the tablet transition is designed to always call the rpc to remove the lock holder in _repair_compaction_locks. This brings another more general issue what happens if user drops table when tablets is a pending transition. @tgrabiec? If we have synchronization so that the drop waits for the pending transition to finish, we do not need this on_cleanup_for_drop_table call back. I hope we have the synchronization to make the model simpler, i.e., no extra handling for the drop table case and replying on the state machine alone.

File: compaction/compaction_manager.cc [hunk 5]
```diff
@@ -2387,6 +2389,8 @@ future<> compaction_manager::remove(compaction_group_view& t, sstring reason) no
     if (!c_state.gate.is_closed()) {
         auto close_gate = c_state.gate.close();
         co_await stop_ongoing_compactions(reason, &t);
+        // Wait for users of incremental repair lock (can be either repair itself or maintenance compactions).
+        co_await c_state.incremental_repair_lock.write_lock();
```
Comment (asias) [inline compaction/compaction_manager.cc:2393]: This brings a very strong dependence to compaction. We need to wait for repair to finish because we can stop a compaction group. I hope we can avoid this.

Comment (raphaelsc) [reply compaction/compaction_manager.cc:2393]: But if repair is operating on compaction group X, and group X needs to be stopped, it makes sense to wait for that repair. The dependence is between compaction group (and all its state which includes the lock) for tablet X and repair on tablet X. It makes sense to not allow repair to outlive the group it's operating on.

File: db/schema_applier.cc [hunk 6]
```diff
@@ -1139,14 +1139,17 @@ future<> schema_applier::finalize_tables_and_views() {
     // was already dropped (see https://github.com/scylladb/scylla/issues/5614)
     for (auto& dropped_view : diff.tables_and_views.local().views.dropped) {
```
Comment (avikivity) [inline db/schema_applier.cc:1140]: > The RPC verb that removes the lock on success path will not be called

Really, if local locks are held by remote nodes, we are doomed. A missed RPC (because the remote crashed) or a double RPC will wreak havoc.

I'll merge this, but local locks most only be held by local holders.

File: compaction/compaction_manager.cc (hunk 5 above)
Comment (avikivity) [reply compaction/compaction_manager.cc:2393]: Yes. We could change the lock's name to be more generic, and then compaction doesn't know about repair. But not needed.

File: db/schema_applier.cc (hunk 6 above)
Comment (raphaelsc) [reply db/schema_applier.cc:1140]: @asias why do we need the repair lock to outlive the repair_meta? is not it sufficient to clear the holder in repair_service::remove_repair_meta after sstables have been marked as repaired?

Comment (raphaelsc) [reply db/schema_applier.cc:1140]: @asias ping

**Comment by denesb** [comment]
> Queued, as this is good enough to avoid the crash for now. I will create a JIRA for follow-up work around this, clearly there is room for improvement here.

https://scylladb.atlassian.net/browse/SCYLLADB-927

File: db/schema_applier.cc (hunk 6 above)
Comment (asias) [reply db/schema_applier.cc:1140]: We need to release the lock after we update the sstables_repaired_at in the system.tablets table which happens only after all repair replicas have finished repair. Otherwise, compaction will get a wrong view regarding if a sstable is repaired or not.
