### PR TITLE
cdc: use a new internal table for exchanging generations

### LINKED ISSUE #7961: large allocation in untyped_result_set reading cdc generations (seastar_memory - oversized allocation: 2023424 bytes. This is non-fatal, but could lead to latency and/or fragmentation issues)
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version: 4.3
Cluster size: 10 nodes / 38 shards / 250GB usage
OS: CentOS 7 , kernel 5

Platform: physical
Hardware: cores=38 memory=125GB
Disks: 1 NVME of 3TB

Getting errors of during startup of:
```
-- Logs begin at Thu 2020-10-22 10:50:24 UTC, end at Mon 2021-01-25 10:33:05 UTC. --
Jan 25 10:26:45 r1.tab.com scylla[31756]:  [shard 0] seastar_memory - oversized allocation: 2023424 bytes. This is non-fatal, but could lead to latency and/or fragmentation issues. Please report: ...
```
Attached full backtrace to ticket.

Thank you, Yakir.

### PR DESCRIPTION
**Pull request by kbr-**
Reopening #8286 since the token metadata fix that allows `Everywhere` strategy tables to work with RBO (#8536) has been merged.

---
Currently when a node wants to create and broadcast a new CDC generation
it performs the following steps:
1. choose the generation's stream IDs and mapping (how this is done is
   irrelevant for the current discussion)
2. choose the generation's timestamp by taking the current time
   (according to its local clock) and adding 2 * ring_delay
3. insert the generation's data (mapping and stream IDs) into
   system_distributed.cdc_generation_descriptions, using the
   generation's timestamp as the partition key (we call this table
   the "old internal table" below)
4. insert the generation's timestamp into the "CDC_STREAMS_TIMESTAMP"
   application state.

The timestamp spreads epidemically through the gossip protocol. When
nodes see the timestamp, they retrieve the generation data from the
old internal table.

Unfortunately, due to the schema of the old internal table, where
the entire generation data is stored in a single cell, step 3 may fail for
sufficiently large generations (there is a size threshold for which step
3 will always fail - retrying the operation won't help). Also the old
internal table lies in the system_distributed keyspace that uses
SimpleStrategy with replication factor 3, which is also problematic; for
example, when nodes restart, they must reach at least 2 out of these 3
specific replicas in order to retrieve the current generation (we write
and read the generation data with QUORUM, unless we're a single-node
cluster, where we use ONE). Until this happens, a restarting
node can't coordinate writes to CDC-enabled tables. It would be better
if the node could access the last known generation locally.

The commit introduces a new table for broadcasting generation data with
the following properties:
-  it uses a better schema that stores the data in multiple rows, each
   of manageable size
-  it resides in a new keyspace that uses EverywhereStrategy so the
   data will be written to every node in the cluster that has a token in
   the token ring
-  the data will be written using CL=ALL and read using CL=ONE; thanks
   to this, restarting node won't have to communicate with other nodes
   to retrieve the data of the last known generation. Note that writing
   with CL=ALL does not reduce availability: creating a new generation
   *requires* all nodes to be available anyway, because they must learn
   about the generation before their clocks go past the generation's
   timestamp; if they don't, partitions won't be mapped to stream IDs
   consistently across the cluster
-  the partition key is no longer the generation's timestamp. Because it
   was that way in the old internal table, it forced the algorithm to
   choose the timestamp *before* the generation data was inserted into
   the table. What if the inserting took a long time? It increased the
   chance that nodes would learn about the generation too late (after
   their clocks moved past its timestamp). With the new schema we will
   first insert the generation data using a randomly generated UUID as
   the partition key, *then* choose the timestamp, then gossip both the
   timestamp and the UUID.
   Observe that after a node learns about a generation broadcasted using
   this new method through gossip it will retrieve its data very quickly
   since it's one of the replicas and it can use CL=ONE as it was
   written using CL=ALL.

The generation's timestamp and the UUID mentioned in the last point form
a "generation identifier" for this new generation. For passing these new
identifiers around, we introduce the cdc::generation_id_v2 type.

Fixes #7961.

---

For optimal review experience it is best to first read the updated design notes (you can read them rendered here: https://github.com/kbr-/scylla/blob/cdc-gen-table/docs/design-notes/cdc.md), specifically the ["Generation switching"](https://github.com/kbr-/scylla/blob/cdc-gen-table/docs/design-notes/cdc.md#generation-switching) section followed by the ["Internal generation descriptions table V1 and upgrade procedure"](https://github.com/kbr-/scylla/blob/cdc-gen-table/docs/design-notes/cdc.md#internal-generation-descriptions-table-v1-and-upgrade-procedure) section, then read the commits in topological order.

dtest gating run (dev): https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/1160/
unit tests (dev) passed locally

### CODE REVIEW

**Review by haaawk — APPROVED** [review]
LGTM. This was already reviewed multiple times and was reverted because of a bug in repair. The bug is fixed now so we can give the PR another try.

**Comment by kbr-** [comment]
Let's give the gating job https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/1160/console time to finish though

**Comment by kbr-** [comment]
The gating job has passed.

**Comment by kbr-** [comment]
@avikivity ping

**Comment by kbr-** [comment]
@avikivity ping

File: db/system_distributed_keyspace.cc [hunk 1]
```diff
@@ -92,6 +92,37 @@ schema_ptr cdc_generations() {
...
+                /* The set of streams mapped to in this range. */
+                .with_column("streams", cdc_streams_set_type)
+                /* The value of the `ignore_msb` sharding parameter of the node which was the owner of this token range
+                 * when the generation was first created. Together with the set of streams above it fully describes
+                 * the mapping for this particular range. */
+                .with_column("ignore_msb", byte_type)
+                /* Column used for sanity checking.
+                 * For a given generation it's equal to the number of ranges in this generation;
+                 * thus, after the generation is fully inserted, it must be equal to the number of rows in the partition. */
+                .with_column("num_ranges", int32_type, column_kind::static_column)
```
Comment (avikivity) [inline db/system_distributed_keyspace.cc:102]: Is this duplication necessary? The reader can get the same infomation by counting rows (or SELECT COUNT(...)). Having duplication in the data model can be okay, but has to be justified.

I see you say "sanity checking". Is it a way to "seal" the record?

File: db/system_distributed_keyspace.cc [hunk 2]
```diff
@@ -92,6 +92,37 @@ schema_ptr cdc_generations() {
...
+                /* The generation describes a mapping from all tokens in the token ring to a set of stream IDs.
+                 * This mapping is built from a bunch of smaller mappings, each describing how tokens in a subrange
+                 * of the token ring are mapped to stream IDs; these subranges together cover the entire token ring.
+                 * Each such range-local mapping is represented by a row of this table.
+                 * The clustering key of the row is the end of the range being described by this row.
+                 * The start of this range is the range_end of the previous row (in the clustering order, which is the integer order)
+                 * or of the last row of this partition if this is the first the first row. */
+                .with_column("range_end", long_type, column_kind::clustering_key)
+                /* The set of streams mapped to in this range. */
+                .with_column("streams", cdc_streams_set_type)
```
Comment (avikivity) [inline db/system_distributed_keyspace.cc:94]: How large can this set grow? Will we need v3 with the set spread out to clustering rows?

File: db/system_distributed_keyspace.cc (hunk 1 above)
Comment (kbr-) [reply db/system_distributed_keyspace.cc:102]: > I see you say "sanity checking". Is it a way to "seal" the record?

In a sense. I use it in `read_cdc_generation()`:
```
    // Paranoic sanity check. Partial reads should not happen since generations should be retrieved only after they
    // were written successfully with CL=ALL. But nobody uses EverywhereStrategy tables so they weren't ever properly
    // tested, so just in case...
    if (entries.size() != num_ranges) {
        throw std::runtime_error(format(
                "read_cdc_generation: wrong number of rows. The `num_ranges` column claimed {} rows,"
                " but reading the partition returned {}.", num_ranges, entries.size()));
    }
```
so this information is only used to increase confidence that the data is consistent. For example, suppose the creator of the data partially inserted the generation into the table due to a failure and then due to a bug started to gossip its ID (which it should not have because of the failure). Then we will detect that it's invalid and won't return it outside.

This actually already helped me catch one bug quickly where I accidentally performed a full-range-scan query in `read_cdc_generation` (so it retrieved all rows - of all generations) instead of selecting a particular generation; the sanity check catched the problem when there were 2 generations.

Previously the situation was simpler because we had one generation = one row.

File: db/system_distributed_keyspace.cc (hunk 2 above)
Comment (kbr-) [reply db/system_distributed_keyspace.cc:94]: It is O(number of shards on a single node).

Comment (kbr-) [reply db/system_distributed_keyspace.cc:94]: For example, 100 shards -> ~2KB.

File: cdc/generation.cc [hunk 3]
```diff
@@ -720,6 +726,14 @@ future<> generation_service::check_and_repair_cdc_streams() {
...
     }
 
+    if (!_feature_service.cluster_supports_cdc_generations_v2()) {
+        throw std::runtime_error(
+                "check_and_repair_cdc_streams: we've detected a partially upgraded cluster: the CDC_GENERATIONS_V2 feature is not enabled."
+                " Please finish the rolling upgrade procedure first and then try executing the command again."
+                " If you really must execute the command right now, execute it on one of the nodes that have not yet been upgraded"
+                " (the node trying to execute the command now is upgraded), but it is highly recommended to finish the upgrade first.");
+    }
+
```
Comment (avikivity) [inline cdc/generation.cc:692]: This introduces sad coupling. Consider a Kubernetes autoscaler that adds nodes autonomously. It doesn't know if an upgrade is in progress. We could require it to know, but that propagates internal constraints to the ecosystem.

Why is this necessary? We could support both the old and new ways for a while, no?

File: cdc/generation.cc [hunk 4]
```diff
@@ -342,18 +310,6 @@ future<cdc::generation_id_v2> make_new_cdc_generation(
...
-    // this will lead to a row that can be as big as 32MB. This is much more
-    // than the limit imposed by commitlog_segment_size_in_mb. If the size of
-    // the row that describes a new generation grows above
-    // commitlog_segment_size_in_mb, the write will fail and the new node won't
-    // be able to join. To avoid such problem we make sure that such row is
-    // always smaller than 4MB. We do that by removing some CDC streams from
-    // each vnode if the total number of streams is too large.
-    gen = limit_number_of_streams_if_needed(std::move(gen));
-
     auto uuid = utils::make_random_uuid();
```
Comment (avikivity) [inline cdc/generation.cc:313]: This should remain, but only be triggered if the cluster is not using v2 format.

Comment (kbr-) [reply cdc/generation.cc:313]: If the cluster is not using v2 format this code will never be executed.

File: db/system_distributed_keyspace.cc (hunk 1 above)
Comment (avikivity) [reply db/system_distributed_keyspace.cc:102]: Ok. Too bad we don't have interactive transactions.

Comment (avikivity) [reply db/system_distributed_keyspace.cc:102]: What does happen if this table is partially written, then a crash happens?

File: db/system_distributed_keyspace.cc (hunk 2 above)
Comment (avikivity) [reply db/system_distributed_keyspace.cc:94]: Ok, please enhance the comment.

File: cdc/generation.cc (hunk 4 above)
Comment (avikivity) [reply cdc/generation.cc:313]: Why not? isn't it used in v1 format?

Please explain.

File: cdc/generation.cc (hunk 3 above)
Comment (kbr-) [reply cdc/generation.cc:692]: I wasn't aware that we "officially" support scaling cluster in the middle of an upgrade - and I'm not talking about CDC here, I'm guessing many things could go wrong.

Anyway:
1. This command should be executed VERY rarily.
2. This command is not for scaling clusters. It's for exceptional situations: recovery from fatal errors. Thus it should generally be run in controlled environment manually by an admin. One exception where it would be "commonly" run is when users upgrade between experimental versions.
3. As the message says, you can still execute this command on a non-upgraded node.
4. Executing the command on an upgraded node would introduce a generation with the new ID format, causing old nodes to get confused and log a lot of errors. If the old node doesn't have the `generation_service` refactor, i.e. the generation handling code is still in `storage_service`, this would even cause the node to stop handling status changes of other nodes which would be very bad.
5. To fix 4. I could modify the code so that if you execute the command on an upgraded node but a partially upgraded cluster, it would introduce a generation with the old ID format (using the old tables). But this would require readding back a lot of code/keeping two versions of the same code which would be a waste, there really is no value here: the admin can always run the command on an old node (see 3.) and it should not be executed by an automatic process (see 2.).
6. This check doesn't block scaling, you can still add a node to a partially upgraded cluster (although due to the check in `bootstrap()` it would have to be an old node).

File: cdc/generation.cc (hunk 4 above)
Comment (kbr-) [reply cdc/generation.cc:313]:
```
//  * Precondition: the CDC_GENERATIONS_V2 feature is enabled in the cluster.
```
(in cdc/generation.hh where the function is declared)
I should probably add a check for this precondition inside the function as well for sanity.
But you can check in the code that after this PR nobody calls `make_new_cdc_generation` without checking if the feature is enabled first.

Comment (kbr-) [reply cdc/generation.cc:313]: There are two uses of this function:
1. `bootstrap()`: new nodes will refuse to bootstrap into a cluster without this feature
2. `check_and_repair_cdc_streams`
3. `join_token_ring` restarting node but no CDC generation exists case: there's a BIG comment there and an error message if we see that that the feature is not enabled and the generation is missing.

Comment (kbr-) [reply cdc/generation.cc:313]: There are three uses of this function:
1. `bootstrap()`: new nodes will refuse to bootstrap into a cluster without this feature
2. `check_and_repair_cdc_streams`
3. `join_token_ring` restarting node but no CDC generation exists case: there's a BIG comment there and an error message if we see that that the feature is not enabled and the generation is missing.

File: cdc/generation.cc (hunk 3 above)
Comment (avikivity) [reply cdc/generation.cc:692]: > I wasn't aware that we "officially" support scaling cluster in the middle of an upgrade - and I'm not talking about CDC here, I'm guessing many things could go wrong.

We don't support it "officiall", but the code is written to support it against the day we do. I believe it is inevitable.

> 
> Anyway:
> 
> 1. This command should be executed VERY rarily.
> 2. This command is not for scaling clusters. It's for exceptional situations: recovery from fatal errors. Thus it should generally be run in controlled environment manually by an admin. One exception where it would be "commonly" run is when users upgrade between experimental versions.
> 3. As the message says, you can still execute this command on a non-upgraded node.
> 4. Executing the command on an upgraded node would introduce a generation with the new ID format, causing old nodes to get confused and log a lot of errors. If the old node doesn't have the `generation_service` refactor, i.e. the generation handling code is still in `storage_service`, this would even cause the node to stop handling status changes of other nodes which would be very bad.
> 5. To fix 4. I could modify the code so that if you execute the command on an upgraded node but a partially upgraded cluster, it would introduce a generation with the old ID format (using the old tables). But this would require readding back a lot of code/keeping two versions of the same code which would be a waste, there really is no value here: the admin can always run the command on an old node (see 3.) and it should not be executed by an automatic process (see 2.).
> 6. This check doesn't block scaling, you can still add a node to a partially upgraded cluster (although due to the check in `bootstrap()` it would have to be an old node).

Ok, with such a list of caveats we can make an exception.

File: db/system_distributed_keyspace.cc (hunk 1 above)
Comment (kbr-) [reply db/system_distributed_keyspace.cc:102]: > What does happen if this table is partially written, then a crash happens?

It will contain a garbage partition that no node will ever try to retrieve, and if they do - due to some bug - they will most probably hit this sanity check.

The user is free to delete this garbage partition. We could potentially also introduce a background process that clears up such garbage generations (see e.g. #7300).

File: cdc/generation.cc (hunk 4 above)
Comment (avikivity) [reply cdc/generation.cc:313]: Not sure I understand 3, but I'd like to remove 1 if possible.

Comment (kbr-) [reply cdc/generation.cc:313]: Is it not enough that users can still bootstrap old nodes into a partially upgraded cluster?
I think new nodes refusing to bootstrap is a reasonable restriction.
- We don't recommend scaling in the middle of upgrade.
- But if you REALLY must bootstrap, bootstrap an old node.
- The restriction doesn't affect decommission/removenode.
- If you want to bootstrap a new node, finish upgrade first.

We could remove the `bootstrap()` restriction by readding back a lot of code: the old CDC generation insertion code, the old tables definitions (meaning that fresh clusters would also have these tables, although empty) etc. so new nodes bootstrapping to partially upgraded clusters would add a generation in the old format if they see the feature disabled.

But I think we should prevent users from doing "stupid" things more - such as scaling in the middle of upgrade - rather than allowing them more "stupid" things. I don't think QA ever tests those scenarios (quick glance at SCT code didn't reveal it), so why not exclude them in the first place? I'm sure we would hit unexpected bugs right now.

IF we want to start supporting such scenarios, THEN I could readd the old code/table definitions, change the restriction to an if-else (if feature enabled do that, else do that), AND of course QA would have to test those scenarios in their release cycle. Even then I would leave this restriction in our upcoming "safe mode". But why not be safe by default?

File: cdc/generation.cc (hunk 3 above)
Comment (kbr-) [reply cdc/generation.cc:692]: > We don't support it "officially", but the code is written to support it against the day we do.

I don't think that matters much if we never test these scenarios (quick glance at SCT didn't reveal tests which scale in the middle of upgrade).

File: cdc/generation.cc (hunk 4 above)
Comment (avikivity) [reply cdc/generation.cc:313]: The problem is that no one reads the recommendations, least of all the robots in automated services.

Comment (kbr-) [reply cdc/generation.cc:313]: > The problem is that no one reads the recommendations, least of all the robots in automated services.

Programmers of these robots should read them.
If they don't, they have a bug in their code.
If their automated service stumbles on this restriction, this would reveal their bug - which is good! - and force them to fix it.

From that POV having the restriction is better because it forces users to follow recommendations.

Comment (kbr-) [reply cdc/generation.cc:313]: Also, you mentioned Kubernetes autoscaler.
Kubernetes doesn't automatically understand how to manage a database. You must write a dedicated operator.
When writing this operator you obviously should follow the rules of the database.

Comment (kbr-) [reply cdc/generation.cc:313]: Consider this hypothetical scenario:
- I readd all the old code and remove the restrictions, allowing new nodes to be booted into mixed clusters.
- But I never actually check if this scenario works.

That obviously wouldn't be good and I should not do it, but consider: isn't this what we do for everything else? These scenarios are _not_ being tested - at least not regularly before each release (correct me if I'm wrong). But because I thought that we don't support and test them, I added a restriction that _rules out_ the untested scenario, allowing me to simplify the code greatly (mostly by removing a lot of legacy code). And simpler and shorter code means fewer bugs.

Handling the scenario is _a lot_ of additional code which would be executed only if someone actually uses Scylla _incorrectly_, and I doubt it would even be executed ever because it's a very specific edge case (who in their right mind tries to scale in the middle of upgrade). I see negative value in that. From the point of view of tradeoffs, isn't it much better to prevent such incorrect usage instead of keeping a lot of code, increasing the chance of bugs and reducing maintainability? Now if the user _really really_ wants to bootstrap a node into a mixed cluster (which they still shouldn't do), they _do_ have a way (boot old node), so it's not like we completely prevent them from doing the wrong thing, but at least we force them to think about it a bit (if they first try to boot a new node and see that it refuses) before they decide to do it.

cc @slivne - could you confirm what the policy about scaling clusters in the middle of upgrade is? Did such situations happen in practice?

Comment (avikivity) [reply cdc/generation.cc:313]: @kbr- you're obviously right that they should. That doesn't mean that they will. We need to make this thing less brittle.

Comment (kbr-) [reply cdc/generation.cc:313]: But doesn't an explicit restriction that tells the user "don't do that, do this instead" actually _increase_ robustness (so it makes things less brittle)? And allowing scenarios which are not regularly tested on each release decreases it?

Comment (avikivity) [reply cdc/generation.cc:313]: If you try to do something, and it tell you not to do it, then you are more robust, but also more brittle. The user was not able to accomplish what they wanted to do.

Comment (avikivity) [reply cdc/generation.cc:313]: Of course, we have to start testing mixed-cluster operations, or we end up with reduced robustness.

Comment (kbr-) [reply cdc/generation.cc:313]: OK. IF we really eventually start testing those scenarios regularly (tell me sweet lies) then I'll be happy with the change.

**Comment by kbr-** [comment]
v2:
- bring back `limit_number_of_streams_if_needed` and corresponding tests
- `make_new_cdc_generation` now takes an extra parameter: `cluster_supports_generations_v2`, which is supposed to be `true` iff the CDC_GENERATIONS_V2 feature is enabled. If the parameter is `true`, the function will not limit the size of the created generation, insert it into the new table, and return its ID (in V2 format). Otherwise it will limit the size, insert it into the old table, and return its timestamp (i.e. ID in the V1 format) - as it did before.
- `check_and_repair_cdc_streams` no longer prevents running the command in partially upgraded clusters. It uses `make_new_cdc_generation` which creates a generation depending on the CDC_GENERATIONS_V2 feature, as described above (tested).
- same with `bootstrap()` - you can now bootstrap both new and old nodes into partially upgraded clusters (tested). When a new node boots into a mixed cluster, it will print a warning that you should finish the upgrade.
- same with restarting nodes that notice that there is no generation yet.
- improved comments (e.g. in `cdc_generations_v2()` in system_distributed_keyspace.cc).
- there's a new commit that renames all_tables() to ensured_tables() in system_distributed_keyspace.cc, check the commit message for motivation.

**Comment by avikivity** [comment]
How were upgrades tested?

**Comment by kbr-** [comment]
> How were upgrades tested?

I had two binaries, one compiled from master (dev mode) (let's call this "old"), one with this PR (let's call this "new").
One example scenario I ran was:
1. start a 2 node cluster in old binary, confirm that 2 generations are created (in V1 format)
2. upgrade one of the nodes (say 1st) to the new binary, check that nothing happens (no new generation is created etc.)
3. bootstrap 3rd node using the old binary, check that a generation was created (in V1 format)
4. bootstrap 4th node using the new binary, check that a generation was created (also in V1 format). Check that a warning was printed (`cdc - Creating a new CDC generation in the old storage format due to a partially upgraded cluster: the CDC_GENERATIONS_V2 feature is known by this node, but not enabled in the cluster. The old storage format forces us to create a suboptimal generation. It is recommended to finish the upgrade and then create a new generation either by bootstrapping a new node or running the checkAndRepairCdcStreams nodetool command.`).
5. run checkAndRepairCdcStreams on one old node and one new node, in both cases check that it does nothing (generation does not need repair)
6. upgrade 2nd node
7. upgrade 3rd node (at this point the cluster is fully upgraded)
8. run checkAndRepairCdcStreams on any node, check that it creates a new generation (in V2 format)
9. try to boot an old node - it fails (good, because the cluster already enabled the CDC_GENERATIONS_V2 feature)
10. bootstrap 5th node using new binary, a generation is created (in V2 format)

That was the most complex scenario. I also ran some basic / less interesting scenarios (e.g. standard upgrade of 3 node cluster followed by bootstrap of 4th node + check that new generation was created in V2).

**Comment by kbr-** [comment]
BTW the gating job has passed.

**Comment by kbr-** [comment]
Also ran another scenario for checking that checkAndRepairCdcStreams works in partially upgraded cluster:
1. boot 2 node cluster
2. upgrade one of the nodes
3. break the last generation (by deleting its entry from `system_distributed.cdc_generation_descriptions`)
4. run the command on the upgraded node - check that it creates a new generation in V1 (and prints a warning about finishing the upgrade)
5. finish upgrade
6. run command again, it creates a new generation in V2
