### PR TITLE
main, test: integrate perf tools into scylla

### LINKED ISSUE #12484: integrate perf tool to scylla bin to run perf tests and collect, analyze perf results regularly
Integrate performance tools to scylla to run performance tests in regular base and store, compare performance results and find regression:
tools for integration:
 - perf_fast_forward 
 - perf_row_cache_update
 - perf_simple_query

Example of execution:
 - `scylla perf_simple_query --smp 1 -m 1G`
 - `scylla perf_row_cache_update ...`

### PR DESCRIPTION
**Pull request by tchaikov**
following tests are integrated into scylla executable

- perf_fast_forward
- perf_row_cache_update
- perf_simple_query
- perf_row_cache_update
- perf_sstable

before this change
```console
$ size build/release/scylla
   text    data     bss     dec     hex filename
82284664         288960  335897 82909521        4f11951 build/release/scylla
$ ls -l build/release/scylla
-rwxrwxr-x 1 kefu kefu 1719672112 Jan 19 17:51 build/release/scylla
```
after this change
```console
$ size build/release/scylla
   text    data     bss     dec     hex filename
84349449         289424  345257 84984130        510c142 build/release/scylla
$ ls -l build/release/scylla
-rwxrwxr-x 1 kefu kefu 1774204800 Jan 19 17:52 build/release/scylla
```

Fixes #12484

### CODE REVIEW

File: main.cc [hunk 1]
```diff
@@ -1740,30 +1740,42 @@ To start the scylla server proper, simply invoke as: scylla server (or just scyl
...
 }
 
+using main_func_type = std::function<int(int, char**)>;
+static main_func_type lookup_main_func(std::string_view name) {
+    std::pair<std::string_view, main_func_type> funcs[] = {
+        {"server", scylla_main},
+        {"types", tools::scylla_types_main},
+        {"sstable", tools::scylla_sstable_main},
+    };
+    auto found = std::ranges::find_if(funcs, [name](auto& name_and_func) {
```
Comment (denesb) [inline main.cc:1754]: @avikivity can we now use ranges?

Comment (denesb) [reply main.cc:1754]: Please add space between `]` and `(`.

File: configure.py [hunk 2]
```diff
@@ -1151,6 +1151,7 @@ def find_headers(repodir, excluded_dirs):
 
 scylla_tests_generic_dependencies = [
     'test/lib/cql_test_env.cc',
+    'test/lib/debug.cc'
```
Comment (denesb) [inline configure.py:1151]: This should be just `debug.cc` (we already have `debug.hh`).

**Comment by tchaikov** [comment]
@avikivity thanks for your review. shall i add all `test/perf/*` tests to scylla?

```
ninja: error: 'test/lib/debug.cctest/lib/test_services.cc', needed by 'build/debug/test/lib/debug.otest/lib/test_services.o', missing and no known rule to make it
```

it builds and runs fine locally with ` ./configure.py --with scylla --mode debug` though. will take a closer look at the FTBFS tomorrow.

File: configure.py [hunk 3]
```diff
@@ -1899,7 +1905,9 @@ def query_seastar_flags(pc_file, link_static_cxx=False):
                 f.write('build $builddir/{}/{}_g: {}.{} {} | {} {}\n'.format(mode, binary, regular_link_rule, mode, str.join(' ', objs), seastar_dep, seastar_testing_dep))
                 f.write('   libs = {}\n'.format(local_libs))
             else:
-                f.write('build $builddir/{}/{}: {}.{} {} | {}\n'.format(mode, binary, regular_link_rule, mode, str.join(' ', objs), seastar_dep))
+                if binary == 'scylla':
+                    local_libs += ' ' + "$seastar_testing_libs_{}".format(mode)
```
Comment (denesb) [inline configure.py:1906]: Not thrilled about adding all this test stuff to scylla.
Maybe we should look into loosing the test dependency first.

Comment (denesb) [reply configure.py:1906]: Might not be worth it. If it is too complicated, we can defer it to a follow-up.

**Comment by avikivity** [comment]
> @avikivity thanks for your review. shall i add all `test/perf/*` tests to scylla?
> 


I think so, maybe not all are important, but many are.


/cc @tgrabiec

**Review by denesb — CHANGES_REQUESTED** [review]
Please check binary size before/after. I don't expect big change but lets check.

File: configure.py (hunk 3 above)
Comment (tchaikov) [reply configure.py:1906]: we are using `src/testing/random.cc` which is compiled in `seastar_testing`.

Comment (tchaikov) [reply configure.py:1906]: > Not thrilled about adding all this test stuff to scylla.
> Maybe we should look into loosing the test dependency first.

i did look into this. no luck.

**Comment by tchaikov** [comment]
changelog

- add "/debug.cc` instead.
- add space in between `]` and `(`.

note to myself, i will 

- [ ] find out the diff in size
- [ ] fix FTBFS
- [ ] explain the new dependency of `seastar_testing` in commit message.

File: main.cc (hunk 1 above)
Comment (tchaikov) [reply main.cc]: @denesb hi Botond, we are already using them =)
```console
$ git grep std::ranges | wc -l
45
```
BTW, i recall that Avi asked the same question when i was using ranges in Seastar!

Comment (denesb) [reply main.cc]: I once started sending patches converting us from `boost::ranges` to `std::ranges`, then we had to revert these due to some bugs in the standard library. Maybe these bugs were fixed, but every time I see `std::range` I think of this.

**Comment by avikivity** [comment]
> > Please check binary size before/after. I don't expect big change but lets check.
> 
> @denesb Hi Botond, thank you for your review. after a second thought, do we have a dedicated build just for testing? so we don't need to worry about the bloating size? i don't really like to have so many "features" only used for testing delivered to user in production.

We don't, and as soon as we integrate profile-guided optimizations, then we have to use a single build for both testing and production, so we test the same binary.

File: main.cc (hunk 1 above)
Comment (tchaikov) [reply main.cc]: i see. that's sad. probably the new gcc in the toolchain brought a more C++20 compliant libstdc++ to us.

Comment (denesb) [reply main.cc]: The bug might have been fixed since.

**Comment by tchaikov** [comment]
changelog

- fixed the FTBFS (added a missing comma in `configure.py`)
- add "/debug.cc` instead.
- add space in between `]` and `(`.
- added two more perf tests to scylla
  -  `perf_row_cache_update`
  - `perf_sstable`
 - note down the size of `scylla` before and after the change in commit mesage

File: configure.py (hunk 3 above)
Comment (tchaikov) [reply configure.py:1908]: i added more details in the commit message. HTH.

File: configure.py [hunk 4]
```diff
@@ -1172,9 +1171,17 @@ def find_headers(repodir, excluded_dirs):
...
+                'test/perf/perf_simple_query.cc',
+                'test/perf/perf.cc',
+                'test/lib/alternator_test_env.cc',
+                'test/lib/cql_test_env.cc',
+                'test/lib/log.cc',
+                'test/lib/tmpdir.cc',
+                'seastar/tests/perf/linux_perf_event.cc']
 
 deps = {
-    'scylla': idls + ['main.cc', 'debug.cc'] + scylla_core + api + alternator + redis + scylla_tools,
```
Comment (denesb) [inline configure.py]: and neither this

**Review by denesb — APPROVED** [review]
LGTM, one minor comment only.

**Comment by denesb** [comment]
> * note down the size of `scylla` before and after the change in commit mesage

No need to add this to each commit message, it is enough to add to the cover-letter only and compare scylla before vs. scylla after the series.

File: configure.py [hunk 5]
```diff
@@ -1173,7 +1174,7 @@ def find_headers(repodir, excluded_dirs):
 scylla_tools = ['tools/scylla-types.cc', 'tools/scylla-sstable.cc', 'tools/schema_loader.cc', 'tools/utils.cc', 'tools/lua_sstable_consumer.cc']
 
 deps = {
-    'scylla': idls + ['main.cc'] + scylla_core + api + alternator + redis + scylla_tools,
+    'scylla': idls + ['main.cc', 'debug.cc'] + scylla_core + api + alternator + redis + scylla_tools,
```
[the remark this answers is not in the document]
Comment (tchaikov) [reply configure.py]: yes, that's even better!

**Comment by avikivity** [comment]
> > * note down the size of `scylla` before and after the change in commit mesage
> 
> No need to add this to each commit message, it is enough to add to the cover-letter only and compare scylla before vs. scylla after the series.

Better: the output of `size scylla` before and after, so we can see how it looks after debug information is stripped.

Though it's not so important, the tests are tiny compared the scylla core.

**Comment by tchaikov** [comment]
changelog

- note down the size before and after the changeset in the cover letter
- move `debug.cc` to `scylla_core`

**Review by avikivity — APPROVED** [review]

**Comment by tchaikov** [comment]
> > > * note down the size of `scylla` before and after the change in commit mesage
> > 
> > 
> > No need to add this to each commit message, it is enough to add to the cover-letter only and compare scylla before vs. scylla after the series.
> 
> Better: the output of `size scylla` before and after, so we can see how it looks after debug information is stripped.

added.

**Review by denesb — APPROVED** [review]

**Comment by avikivity** [comment]
It added 2MB, more than I expected. Still, it's reasonable, and worthwhile as we can now easily run the performance tests on any machine using packages.

**Comment by michoecho** [comment]
> We don't, and as soon as we integrate profile-guided optimizations, then we have to use a single build for both testing and production, so we test the same binary.

You mean link-time optimizations (and/or BOLT), not profile-guided optimizations. With LTO disabled, all executables are linked from the same object files. (Not that it matters, because we aren't planning to use PGO without LTO).

**Comment by avikivity** [comment]
> > We don't, and as soon as we integrate profile-guided optimizations, then we have to use a single build for both testing and production, so we test the same binary.
> 
> You mean link-time optimizations (and/or BOLT), not profile-guided optimizations. With LTO disabled, all executables are linked from the same object files. (Not that it matters, because we aren't planning to use PGO without LTO).

Yes
