### PR TITLE
utils: azure: Catch system errors when probing IMDS and bump the verbosity of logs

### LINKED ISSUE #25641: test_azure_provider_with_incomplete_creds fails locally
```console
$ ./test.py --mode release test/boost/encryption_at_rest_test.cc
============================= test session starts ==============================
platform linux -- Python 3.13.7, pytest-8.3.4, pluggy-1.5.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/avi/scylla/test
configfile: pytest.ini
plugins: allure-pytest-2.13.5, xdist-3.6.1, repeat-0.9.3, timeout-2.3.1, asyncio-0.24.0
timeout: 24000.0s
timeout method: signal
timeout func_only: False
session timeout: 24000.0s
asyncio: mode=Mode.AUTO, default_loop_scope=session
created: 32/32 workers
32 workers [39 items]

scheduling tests via LoadScheduling

test/boost/encryption_at_rest_test.cc::test_replicated_provider.release.1 
test/boost/encryption_at_rest_test.cc::test_replicated_provider_shutdown_failure.release.1 
test/boost/encryption_at_rest_test.cc::test_kms_provider.release.1 
test/boost/encryption_at_rest_test.cc::test_kms_provider_with_master_key_in_cf.release.1 
test/boost/encryption_at_rest_test.cc::test_kmip_provider_broken_sstables_on_restart.release.1 
test/boost/encryption_at_rest_test.cc::test_azure_provider_with_no_host.release.1 
test/boost/encryption_at_rest_test.cc::test_gcp_provider.release.1 
test/boost/encryption_at_rest_test.cc::test_azure_provider_with_invalid_key_real.release.1 
test/boost/encryption_at_rest_test.cc::test_kms_provider_with_broken_algo.release.1 
test/boost/encryption_at_rest_test.cc::test_kmip_provider_broken_config_on_restart.release.1 
test/boost/encryption_at_rest_test.cc::test_azure_provider_with_certificate.release.1 
test/boost/encryption_at_rest_test.cc::test_gcp_provider_with_impersonated_user.release.1 
test/boost/encryption_at_rest_test.cc::test_azure_provider_with_secret_real.release.1 
test/boost/encryption_at_rest_test.cc::test_gcp_provider_with_master_key_in_cf.release.1 
test/boost/encryption_at_rest_test.cc::test_commitlog_kms_encryption_with_slow_key_resolve.release.1 
test/boost/encryption_at_rest_test.cc::test_user_info_encryption.release.1 
test/boost/encryption_at_rest_test.cc::test_azure_provider_with_invalid_user.release.1 
test/boost/encryption_at_rest_test.cc::test_azure_provider_with_imds.release.1 
test/boost/encryption_at_rest_test.cc::test_azure_provider_with_invalid_key.release.1 
test/boost/encryption_at_rest_test.cc::test_kmip_network_error.release.1 
test/boost/encryption_at_rest_test.cc::test_kmip_provider.release.1 
test/boost/encryption_at_rest_test.cc::test_azure_provider_with_certificate_real.release.1 
test/boost/encryption_at_rest_test.cc::test_replicated_provider_many_tables.release.1 
test/boost/encryption_at_rest_test.cc::test_local_file_provider.release.1 
test/boost/encryption_at_rest_test.cc::test_user_info_encryption_dont_allow_per_table_encryption.release.1 
test/boost/encryption_at_rest_test.cc::test_kms_network_error.release.1 
test/boost/encryption_at_rest_test.cc::test_azure_provider_with_secret.release.1 
test/boost/encryption_at_rest_test.cc::test_commitlog_kmip_encryption_with_slow_key_resolve.release.1 
test/boost/encryption_at_rest_test.cc::test_azure_provider_with_master_key_in_cf.release.1 
test/boost/encryption_at_rest_test.cc::test_kmip_provider_multiple_hosts.release.1 
test/boost/encryption_at_rest_test.cc::test_gcp_provider_with_invalid_user.release.1 
test/boost/encryption_at_rest_test.cc::test_azure_provider_with_incomplete_creds.release.1 
[gw13] PASSED test/boost/encryption_at_rest_test.cc::test_gcp_provider.release.1 
[gw11] PASSED test/boost/encryption_at_rest_test.cc::test_commitlog_kmip_encryption_with_slow_key_resolve.release.1 
[gw6] PASSED test/boost/encryption_at_rest_test.cc::test_kms_provider.release.1 
test/boost/encryption_at_rest_test.cc::test_azure_host.release.1 
[gw16] PASSED test/boost/encryption_at_rest_test.cc::test_gcp_provider_with_impersonated_user.release.1 
[gw30] PASSED test/boost/encryption_at_rest_test.cc::test_azure_provider_with_invalid_key_real.release.1 
[gw18] PASSED test/boost/encryption_at_rest_test.cc::test_kmip_network_error.release.1 
[gw10] PASSED test/boost/encryption_at_rest_test.cc::test_commitlog_kms_encryption_with_slow_key_resolve.release.1 
[gw23] PASSED test/boost/encryption_at_rest_test.cc::test_azure_provider_with_secret_real.release.1 
[gw9] PASSED test/boost/encryption_at_rest_test.cc::test_kms_provider_with_broken_algo.release.1 
[gw25] PASSED test/boost/encryption_at_rest_test.cc::test_azure_provider_with_certificate_real.release.1 
[gw14] PASSED test/boost/encryption_at_rest_test.cc::test_gcp_provider_with_master_key_in_cf.release.1 
[gw7] PASSED test/boost/encryption_at_rest_test.cc::test_kms_provider_with_master_key_in_cf.release.1 
[gw17] PASSED test/boost/encryption_at_rest_test.cc::test_kms_network_error.release.1 
[gw15] PASSED test/boost/encryption_at_rest_test.cc::test_gcp_provider_with_invalid_user.release.1 
[gw29] PASSED test/boost/encryption_at_rest_test.cc::test_azure_provider_with_invalid_key.release.1 
[gw28] FAILED test/boost/encryption_at_rest_test.cc::test_azure_provider_with_incomplete_creds.release.1 
[gw31] PASSED test/boost/encryption_at_rest_test.cc::test_azure_provider_with_invalid_user.release.1 
[gw6] PASSED test/boost/encryption_at_rest_test.cc::test_azure_host.release.1 
[gw12] PASSED test/boost/encryption_at_rest_test.cc::test_user_info_encryption_dont_allow_per_table_encryption.release.1 
[gw27] PASSED test/boost/encryption_at_rest_test.cc::test_azure_provider_with_no_host.release.1 
[gw3] PASSED test/boost/encryption_at_rest_test.cc::test_replicated_provider_shutdown_failure.release.1 
test/boost/encryption_at_rest_test.cc::test_azure_network_error.release.1 
[gw1] PASSED test/boost/encryption_at_rest_test.cc::test_replicated_provider.release.1 
test/boost/encryption_at_rest_test.cc::test_azure_provider_with_both_secret_and_cert.release.1 
[gw8] PASSED test/boost/encryption_at_rest_test.cc::test_user_info_encryption.release.1 
[gw0] PASSED test/boost/encryption_at_rest_test.cc::test_local_file_provider.release.1 
test/boost/encryption_at_rest_test.cc::test_azure_provider_with_invalid_user_real.release.1 
[gw24] PASSED test/boost/encryption_at_rest_test.cc::test_azure_provider_with_certificate.release.1 
[gw0] PASSED test/boost/encryption_at_rest_test.cc::test_azure_provider_with_invalid_user_real.release.1 
[gw22] PASSED test/boost/encryption_at_rest_test.cc::test_azure_provider_with_secret.release.1 
[gw21] PASSED test/boost/encryption_at_rest_test.cc::test_azure_provider_with_imds.release.1 
[gw26] PASSED test/boost/encryption_at_rest_test.cc::test_azure_provider_with_master_key_in_cf.release.1 
[gw3] PASSED test/boost/encryption_at_rest_test.cc::test_azure_network_error.release.1 
[gw1] PASSED test/boost/encryption_at_rest_test.cc::test_azure_provider_with_both_secret_and_cert.release.1 
[gw2] PASSED test/boost/encryption_at_rest_test.cc::test_replicated_provider_many_tables.release.1 
test/boost/encryption_at_rest_test.cc::test_azure_provider_with_both_secret_and_cert_real.release.1 
[gw2] PASSED test/boost/encryption_at_rest_test.cc::test_azure_provider_with_both_secret_and_cert_real.release.1 
[gw19] PASSED test/boost/encryption_at_rest_test.cc::test_kmip_provider_broken_config_on_restart.release.1 
[gw20] PASSED test/boost/encryption_at_rest_test.cc::test_kmip_provider_broken_sstables_on_restart.release.1 
[gw4] PASSED test/boost/encryption_at_rest_test.cc::test_kmip_provider.release.1 
test/boost/encryption_at_rest_test.cc::test_imds.release.1 
[gw5] PASSED test/boost/encryption_at_rest_test.cc::test_kmip_provider_multiple_hosts.release.1 
test/boost/encryption_at_rest_test.cc::test_entra_sts.release.1 
[gw4] PASSED test/boost/encryption_at_rest_test.cc::test_imds.release.1 
[gw5] PASSED test/boost/encryption_at_rest_test.cc::test_entra_sts.release.1 

=================================== FAILURES ===================================
__________________ test_azure_provider_with_incomplete_creds ___________________
[gw28] linux -- Python 3.13.7 /usr/bin/python3
working_dir: /home/avi/scylla
Internal Error: calling /home/avi/scylla/build/release/test/boost/encryption_at_rest_test for test test_azure_provider_with_incomplete_creds failed (return_code=201):
output file: /home/avi/scylla/testlog/release/boost.encryption_at_rest_test.test_azure_provider_with_incomplete_creds.release.1_stdout.1.log
log: <TestLog><Exception file="unknown location" line="0"><![CDATA[std::_Nested_exception<encryption::network_error>: 127.117.215.5//keys/mock-key//wrapkey?api-version=7.4]]><LastCheckpoint file="test/boost/encryption_at_rest_test.cc" line="1569"><![CDATA[]]></LastCheckpoint></Exception></TestLog>
command to repeat: /home/avi/scylla/build/release/test/boost/encryption_at_rest_test --report_level=no --output_format=XML --log_sink=/home/avi/scylla/testlog/release/boost.encryption_at_rest_test.test_azure_provider_with_incomplete_creds.release.1.1.xml --catch_system_errors=no --color_output=false --run_test=test_azure_provider_with_incomplete_creds -- --overprovisioned --unsafe-bypass-fsync=1 --kernel-page-cache=1 --blocked-reactor-notify-ms=2000000 --collectd=0 --max-networking-io-control-blocks=100 --reactor-backend=linux-aio -c2 -m2G
encryption_at_rest_test.cc:1569: C++ failure
------------------------------ Captured log call -------------------------------
14:57:21.491 DEBUG>  Using selector: EpollSelector
--- generated xml file: /home/avi/scylla/testlog/report/pytest_cpp_eaac7.xml ---
=========================== short test summary info ============================
FAILED test/boost/encryption_at_rest_test.cc::test_azure_provider_with_incomplete_creds.release.1
======================== 1 failed, 38 passed in 15.84s =========================
================================================================================
[N/TOTAL]   SUITE    MODE   RESULT   TEST
------------------------------------------------------------------------------

------------------------------------------------------------------------------
CPU utilization: 8.8%
The following test(s) have failed: test/boost/encryption_at_rest_test.cc::test_azure_provider_with_incomplete_creds
Summary: 1 of the total 39 tests failed
```

test.py log:

```
14:57:18.463 CRITICAL> Started ./test.py --mode release test/boost/encryption_at_rest_test.cc
14:57:18.479 INFO> running all tests
14:57:18.625 INFO> [minio] Starting minio server at 127.117.215.2:45759
14:57:18.933 INFO> [minio] minio is up and running
14:57:19.400 INFO> [s3_mock] Starting S3 mock server on ('127.117.215.3', 2012)
14:57:19.401 INFO> [s3_proxy] Setting minio proxy random seed to 1756036639
14:57:19.401 INFO> [s3_proxy] Starting S3 proxy server on ('127.117.215.4', 9002)
14:57:19.401 INFO> [azure_vault] Starting Azure Vault mock server on ('127.117.215.5', 5467)
14:57:35.749 INFO> Cleaning up before exit...
14:57:35.752 INFO> [minio] Killing minio server
14:57:35.752 INFO> [s3_mock] Stopping S3 mock server
14:57:35.916 INFO> [s3_proxy] Stopping S3 proxy server
14:57:35.917 INFO> [azure_vault] Stopping Azure Vault mock server
14:57:36.510 INFO> [minio] Killed minio server
14:57:36.512 INFO> Done cleaning up before exit...
14:57:36.512 INFO> after running all tests
```

Failed tests logs:

```
INFO  2025-08-24 14:57:22,062 seastar - Reactor backend: linux-aio
INFO  2025-08-24 14:57:22,066 [shard 0:main] seastar - IO queue was unable to find a suitable maximum request length, the search was cut-off early at: 16MB
INFO  2025-08-24 14:57:22,066 [shard 0:main] seastar - IO queue was unable to find a suitable maximum request length, the search was cut-off early at: 16MB
random-seed=1978934665
INFO  2025-08-24 14:57:22,084 [shard 0:main] seastar - updated: blocked-reactor-notify-ms=1000000
INFO  2025-08-24 14:57:22,084 [shard 1:main] seastar - updated: blocked-reactor-notify-ms=1000000
INFO  2025-08-24 14:57:22,087 [shard 0:main] azure_vault - [AzureVault:azure_test] Verifying access to master key http://127.117.215.5:5467/mock-key
ERROR 2025-08-24 14:57:22,099 [shard 0:main] azure_vault - [AzureVault:azure_test] Failed to wrap key AES:128 with master_key=http://127.117.215.5:5467/mock-key: std::_Nested_exception<encryption::network_error> (127.117.215.5//keys/mock-key//wrapkey?api-version=7.4): std::system_error (error system:113, No route to host)
```

What can the problem be? race between startup/shutdown of the mock server and the tests?

### PR DESCRIPTION
**Pull request by ndragazis**
This PR fixes a bug in the Azure default credential provider that would cause the `test_azure_provider_with_incomplete_creds` unit test to be flaky. The provider would assume that an unreachable IMDS endpoint would always result in a timeout, but network errors are also possible (e.g., ICMP "host unreachable"). The issue is triggered by this particular test because it sets the IMDS endpoint to a non-routable address. Some routers choose to silently drop such packets, while others return ICMP errors. To fix it, the default credential provider has been updated to catch system errors as well.

This PR also raises the log level of the default credential provider from DEBUG to INFO, making it easier for operators to diagnose authentication issues.

More details in the commit messages.

Fixes #25641.

### CODE REVIEW

File: utils/azure/identity/default_credentials.cc [hunk 1]
```diff
@@ -133,8 +133,11 @@ future<default_credentials::credentials_opt> default_credentials::get_credential
     auto creds = std::make_unique<managed_identity_credentials>(_imds_endpoint, _logctx);
     try {
         co_await creds->get_access_token(resource_uri);
-    } catch (timed_out_error&) {
-        az_creds_logger.info("[{}] Failed to connect to IMDS.", *this);
+    } catch (timed_out_error& e) {
+        az_creds_logger.info("[{}] Failed to connect to IMDS: timed out", *this);
+        co_return std::nullopt;
+    } catch (std::system_error& e) {
+        az_creds_logger.info("[{}] System error while accessing IMDS: {}", *this, e.what());
```
Comment (elcallio) [inline utils/azure/identity/default_credentials.cc:146]: Should this not verify _which_ system error you got? Technically, it could be something that this logic would/should classify as propagation-level.

Comment (ndragazis) [reply utils/azure/identity/default_credentials.cc:146]: I wasn't sure about that. Is there any system error that makes sense to propagate?

Comment (elcallio) [reply utils/azure/identity/default_credentials.cc:146]: Invalid address stuff, anything related to general system error? In general, when handling system error we do (and should) check the error codes as well, and only special treat the based on this...
As usual, none of these other cases will ever happen, but...

File: utils/azure/identity/default_credentials.cc [hunk 2]
```diff
@@ -75,15 +75,15 @@ future<default_credentials::credentials_opt> default_credentials::get_credential
...
-        az_creds_logger.debug("[{}] Client ID is {}set", *this, client_id ? "" : "NOT ");
-        az_creds_logger.debug("[{}] Client Secret is {}set", *this, client_secret ? "" : "NOT ");
-        az_creds_logger.debug("[{}] Client Certificate is {}set", *this, client_certificate_path ? "" : "NOT ");
-        az_creds_logger.debug("[{}] Authority host is {}set", *this, authority ? "" : "NOT ");
+        az_creds_logger.info("[{}] Incomplete credentials. Both 'AZURE_TENANT_ID' and 'AZURE_CLIENT_ID', and at least one of 'AZURE_CLIENT_SECRET', 'AZURE_CLIENT_CERTIFICATE_PATH' must be provided. Currently:", *this);
+        az_creds_logger.info("[{}] Tenant ID is {}set", *this, tenant_id ? "" : "NOT ");
+        az_creds_logger.info("[{}] Client ID is {}set", *this, client_id ? "" : "NOT ");
+        az_creds_logger.info("[{}] Client Secret is {}set", *this, client_secret ? "" : "NOT ");
+        az_creds_logger.info("[{}] Client Certificate is {}set", *this, client_certificate_path ? "" : "NOT ");
+        az_creds_logger.info("[{}] Authority host is {}set", *this, authority ? "" : "NOT ");
```
Comment (xemul) [inline utils/azure/identity/default_credentials.cc]: This will interfere with other logs and will intermix different lines with unrelated (to azure creds) logging. If touching this place, how about merging them into a single info() invocation?

Comment (ndragazis) [reply utils/azure/identity/default_credentials.cc]: Sure, although an interleaving is very unlikely here, since these get printed very early in the initialization process, before starting any services (call chain: `scylla_main()` -> `configurable::init_all()` -> `encryption::register_extensions()` -> `azure_host::init()`). The only exception is when we define a `master_key` in the table schema and no `master_key` in the configuration, in which case this logic is deferred for later.

**Comment by ndragazis** [comment]
v2 Changelog:
* Rebase.
* Concatenate logs for environment credentials into a single log statement to avoid interleaving with other logs.

**Comment by ndragazis** [comment]
> #### 🔴 CI State: FAILURE
> Mode 	Stage 	Status 	Node
> 	[Framework test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19983/) 	✅ 	spider11.cloudius-systems.com
> dev 	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19983/) 	❌ 	spider4.cloudius-systems.com
> #### Build Failure:
> 
> ```
> [2025-09-16T17:15:05.835Z] FAILED: build/dev/service/vector_search/dns.o 
> [2025-09-16T17:15:05.836Z] clang++ -MD -MT build/dev/service/vector_search/dns.o -MF build/dev/service/vector_search/dns.o.d -std=gnu++23 -I/jenkins/workspace/scylla-master/scylla-ci@2/scylla/seastar/include -I/jenkins/workspace/scylla-master/scylla-ci@2/scylla/build/dev/seastar/gen/include -Werror=unused-result -fstack-clash-protection -DSEASTAR_API_LEVEL=7 -DSEASTAR_BUILD_SHARED_LIBS -DSEASTAR_SSTRING -DSEASTAR_ENABLE_ALLOC_FAILURE_INJECTION -DSEASTAR_LOGGER_COMPILE_TIME_FMT -DSEASTAR_SCHEDULING_GROUPS_COUNT=19 -DSEASTAR_LOGGER_TYPE_STDOUT -DSEASTAR_TYPE_ERASE_MORE -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DFMT_SHARED -I/usr/include/p11-kit-1 -g -ffile-prefix-map=/jenkins/workspace/scylla-master/scylla-ci@2/scylla=. -DSEASTAR_NO_EXCEPTION_HACK -march=westmere -DDEVEL -DSEASTAR_ENABLE_ALLOC_FAILURE_INJECTION -DSCYLLA_ENABLE_ERROR_INJECTION -DSCYLLA_ENABLE_PREEMPTION_SOURCE -O2 -DSCYLLA_BUILD_MODE=dev -Xclang -fexperimental-assignment-tracking=disabled -iquote. -iquote build/dev/gen -std=gnu++23 -g -ffile-prefix-map=/jenkins/workspace/scylla-master/scylla-ci@2/scylla=. -DSEASTAR_NO_EXCEPTION_HACK -march=westmere -I/usr/include/p11-kit-1 -DBOOST_ALL_DYN_LINK    -fvisibility=hidden -Ikmipc/kmipc-2.1.0t-rhel84_64/include -DHAVE_KMIP -isystem abseil -Wall -Werror -Wextra -Wimplicit-fallthrough -Wno-mismatched-tags -Wno-c++11-narrowing -Wno-overloaded-virtual -Wno-unused-parameter -Wno-unsupported-friend -Wno-missing-field-initializers -Wno-deprecated-copy -Wno-error=deprecated-declarations -DXXH_PRIVATE_API -DSEASTAR_TESTING_MAIN  -c -o build/dev/service/vector_search/dns.o service/vector_search/dns.cc
> [2025-09-16T17:15:05.836Z] service/vector_search/dns.cc:65:9: error: use of undeclared identifier on_internal_error_noexcept
> [2025-09-16T17:15:05.836Z]    65 |         on_internal_error_noexcept(vslogger, fmt::format("The Vector Store Client refresh task failed: {}", eptr));
> [2025-09-16T17:15:05.836Z]       |         ^
> [2025-09-16T17:15:05.836Z] 1 error generated.
> ```
> 
> | release | [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19983/) | ✅ | spider4.cloudius-systems.com | | | [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19983/) | ✅ | spider4.cloudius-systems.com | | debug | [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19983/) | ✅ | spider2.cloudius-systems.com | | | [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19983/) | ✅ | spider2.cloudius-systems.com | | dtest | [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/7368/) | ✅ | | | | [dtest with consistent topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/10624/) | ✅ | | | | [dtest with gossip topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/18732/) | ✅ | |
> #### Build Details:
> 
>     * Duration: 6 hr 40 min
> 
> 
> **Note:** To re-trigger CI for this PR, comment: `@scylladbbot trigger-ci`

I have no idea why compilation fails. I mean, the error message is clear, but this file does not exist in master. There is another PR that introduces the offending file, and fails to compile the same way, but it hasn't been merged yet: https://github.com/scylladb/scylladb/pull/26052#issuecomment-3300223597. Also, this file does not appear in the build output for release and debug builds.
